### ISSUE TITLE
Figure out the metric Label API

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1000]
With the removal of the LabelSet from that API, we need to decide what to do with labels. Should we have a `Label` object that encapsulates the key/value? Should we support non-String values?

This issue will track the discussion and work on this.

**Comment by thisthat** [comment]
I am in favor of having a key/value object like it is in otel-go.

**Comment by jkwatson** [comment]
From discussion in the metrics gitter channel, it seems that people are ok with just having String-valued labels for metrics. so, unless anyone objects, I think we can close this. Please respond if you feel like we need to expand our labels to include other types.

**Comment by andrewhsu** [comment]
from the java sig mtg today, sounds like the definition of done for this issue is a decision. if noop, this can be closed. if code changes desired, keep this issue open to track the PRs.

**Comment by jkwatson** [comment]
I'm going to close this. We now have a `Labels` class to capture this. If changes are needed, we can open issues to track that.
