### ISSUE TITLE
Fix inconsistency between SpanExporter and MetricExporter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1016]
1. We use Collection vs List.
2. Add shutdown on the MetricExporter.

**Comment by carlosalberto** [comment]
@bogdandrutu Are you working on this? (On using `Collection` for all our exporters). If not, I can take that part.

**Comment by jkwatson** [comment]
> @bogdandrutu Are you working on this? (On using `Collection` for all our exporters). If not, I can take that part.

Are one of you working on it? If so, please assign yourself. Otherwise, I'm assigning myself and doing it.  :)

**Comment by carlosalberto** [comment]
@jkwatson Yours ;) Thanks!
