### ISSUE TITLE
Add flush on the [Span|Metric]Exporter (not only the processor)?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1017]

**Comment by carlosalberto** [comment]
My feeling is that this is a 'Yes' but as a refinement/improve. Something to consider down the road (but before 1.0?)

**Comment by jkwatson** [comment]
We definitely need a `shutdown` on the MetricExporter. I don't have a strong feeling about flushing the exporter. I would guess that most exporters would send the data as they got it from the processor, rather than duplicating the batching functionality.

**Comment by Oberon00** [comment]
As an example, a file-based exporter might want to use flush the file.

**Comment by jkwatson** [comment]
Sure would be nice if we had default methods we could add to the interface for this.  ;)
