### ISSUE TITLE
validation glitches in TraceState.validateKey

### ISSUE THREAD

**Issue by adriancole** [open-telemetry/opentelemetry-java#1027]
I noticed that `TraceState.validateKey` is loose compared to the ABNF in the spec. There are a couple missing tests:

* when tenant format is used (`@`), the right-side can be 1-14 characters. this is not validated
* only when tenant format is used (`@`), the first character can be a digit. Otherwise, it must be a letter

There might be some other problems, but these I noticed. As the spec text doesn't elaborate on the above points, I tried to correct it FWIW https://github.com/w3c/trace-context/pull/386

**Comment by adriancole** [comment]
ps there are a number of cases around @ syntax.. you can look at brave's tests if it helps. https://github.com/openzipkin/brave/pull/693

**Comment by thisthat** [comment]
Based on the latest version (https://github.com/w3c/trace-context/blob/master/spec/20-http_request_header_format.md#list-members), I think the current implementation correctly validates keys and values.

**Comment by jkwatson** [comment]
@adriancole do you concur? Can we close this?

**Comment by adriancole** [comment]
I had pushed this to be errata so the spec would change. It hasn't changed as far as I can tell, rather scheduled to change in some unknown version. https://www.w3.org/TR/trace-context/#list-members

Since many people on the spec are also here, I would get someone to ask someone to push errata or say what version of the spec will have this, so that folks know that this is fixed per pending spec errata 2 or something.
