### ISSUE TITLE
Make TraceConfig.newBuilder public or add comment to use getDefault().toBuilder() instead.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1028]
See https://github.com/open-telemetry/opentelemetry-java/blob/88e0ef464f576c670fe73204d5579eda29fed68e/sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java#L108

Even though I was puzzled why this is private fist, it might actually make sense because if a new config is introduced, `getDefault().toBuilder()` will use the new default while code using `newBuilder()` would break. But this should be documented.

**Comment by bogdandrutu** [comment]
Actually the best use is getCurrentConfig.toBuilder. idea being if you want to change just the Sampler you get the current config and change only the Sampler and keep the other current configs unchanged

**Comment by Oberon00** [comment]
One more reason to properly document this in a javadoc comment.

**Comment by jkwatson** [comment]
> One more reason to properly document this in a javadoc comment.

I'd like to pick this up and get it documented. Where do you think the javadoc should live? On the private `newBuilder` method? On the class itself? I'm not sure where people will actually see it, especially if they're not looking directly at the source code.

**Comment by Oberon00** [comment]
It should be on the private newBuilder too, but that one doesn't appear in the Javadoc. So the class itself would be good I guess (and a link in toBuilder or vice versa)

**Comment by Oberon00** [comment]
Actually, the updateConfig method on the tracerprovider would be a good place to put at least an `@see` too.

**Comment by jkwatson** [comment]
I'll see what I can cook up.
