### ISSUE TITLE
Issues with the current state of the push-based Metric export

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1029]
I'm using this issue to gather my thoughts after working to implement a metric exporter for New Relic, which uses a push-based export model. We support 3 types of metrics natively: incremental counts, numeric gauges and incremental min-max-sum-count Summaries. The incremental types require a start time and an end time on them, to note the aggregation window.

I expect this should be broken out into separate issues to be worked on

Issues perceived, in no particular order:

- It is unclear exactly what the meanings of the various `*Point` types are, since there is no information about what aggregation produced them. The javadoc doesn't clarify how an exporter should interpret the data. I think there's an implicit connection to the `Type` inside the `Descriptor` class, but the connection is confusing (and I helped write some of this code!) Perhaps the solution is to make the `Point` types more diverse and descriptive, or merge the type notion into the Point? I'm not exactly sure, but I do know what we have now is not clear or obvious. 
-  The various aggregations don't behave in the same way. The MinMaxSumCount, which produces a `SummaryPoint` (the descriptor has `Type`= `Summary`) generates delta values, whereas the `Sum` aggregation generates cumulative values. This also means that exporters that need to export deltas have to keep track of the previous value and do the diff themselves, rather than having this be something provided by the SDK.
- The data given to the exporter doesn't have information about the collection interval. When you use the `IntervalMetricReader`, you don't know, unless you keep track of it yourself, the "start time" for the collection cycle. This information should be available to the exporter, maybe in the points themselves, or maybe provided by the `IntervalMetricReader`? Not sure what the right answer is.
- I'm unclear under what circumstances we'd get more than one `Point` per `MetricData` instance in a collection interval. Again, not having access to semantics around the aggregation leads to confusion here.

**Comment by bogdandrutu** [comment]
> It is unclear exactly what the meanings of the various *Point types are, since there is no information about what aggregation produced them. The javadoc doesn't clarify how an exporter should interpret the data. I think there's an implicit connection to the Type inside the Descriptor class, but the connection is confusing (and I helped write some of this code!) Perhaps the solution is to make the Point types more diverse and descriptive, or merge the type notion into the Point? I'm not exactly sure, but I do know what we have now is not clear or obvious.

Yes the idea is that based on the type in the Descriptor you know the type of the points. Don't know how to do a better job there, happy to see proposals.

> The various aggregations don't behave in the same way. The MinMaxSumCount, which produces a SummaryPoint (the descriptor has Type= Summary) generates delta values, whereas the Sum aggregation generates cumulative values. This also means that exporters that need to export deltas have to keep track of the previous value and do the diff themselves, rather than having this be something provided by the SDK.

As part of the "Views" we should support exporter configuring this.

> The data given to the exporter doesn't have information about the collection interval. When you use the IntervalMetricReader, you don't know, unless you keep track of it yourself, the "start time" for the collection cycle. This information should be available to the exporter, maybe in the points themselves, or maybe provided by the IntervalMetricReader? Not sure what the right answer is

I see this being a problem even if we have start/end timestamps that can help a bit, I think there are 3 types:
* Instantaneous (gauge) - data are not associated with any interval, the current value.
* Cumulative - data are aggregated over time and associated with a time interval. they are continuously aggregated and an export does not reset the current state.
* Delta - similar with cumulative but every export we reset the values.

> I'm unclear under what circumstances we'd get more than one Point per MetricData instance in a collection interval. Again, not having access to semantics around the aggregation leads to confusion here.

If you have a label with multiple values you get a point per each label combination.

**Comment by jkwatson** [comment]
> > It is unclear exactly what the meanings of the various *Point types are, since there is no information about what aggregation produced them. The javadoc doesn't clarify how an exporter should interpret the data. I think there's an implicit connection to the Type inside the Descriptor class, but the connection is confusing (and I helped write some of this code!) Perhaps the solution is to make the Point types more diverse and descriptive, or merge the type notion into the Point? I'm not exactly sure, but I do know what we have now is not clear or obvious.
> 
> Yes the idea is that based on the type in the Descriptor you know the type of the points. Don't know how to do a better job there, happy to see proposals.

I suspect this is mostly a naming/documentation thing. The functionality that is being provided seems fine.

> 
> > The various aggregations don't behave in the same way. The MinMaxSumCount, which produces a SummaryPoint (the descriptor has Type= Summary) generates delta values, whereas the Sum aggregation generates cumulative values. This also means that exporters that need to export deltas have to keep track of the previous value and do the diff themselves, rather than having this be something provided by the SDK.
> 
> As part of the "Views" we should support exporter configuring this.

I wonder if we can do something smaller in scope than a full views API to make this easier for beta users.

> 
> > The data given to the exporter doesn't have information about the collection interval. When you use the IntervalMetricReader, you don't know, unless you keep track of it yourself, the "start time" for the collection cycle. This information should be available to the exporter, maybe in the points themselves, or maybe provided by the IntervalMetricReader? Not sure what the right answer is
> 
> I see this being a problem even if we have start/end timestamps that can help a bit, I think there are 3 types:
> 
> * Instantaneous (gauge) - data are not associated with any interval, the current value.
> * Cumulative - data are aggregated over time and associated with a time interval. they are continuously aggregated and an export does not reset the current state.
> * Delta - similar with cumulative but every export we reset the values.

Yes, agreed. I wonder if this is something that should be in the `Point`, to make it super clear what's being provided? I think that might go a long way to clarifying. I'll work on a PR that adds this and see how it feels.

> 
> > I'm unclear under what circumstances we'd get more than one Point per MetricData instance in a collection interval. Again, not having access to semantics around the aggregation leads to confusion here.
> 
> If you have a label with multiple values you get a point per each label combination.

Oh! That definitely wasn't clear to me. That makes a lot of sense, though. I'll work on updating the documentation to make it really clear what's happening.

Thanks for the responses! I think we can make this really great, and I'm happy to help it happen.

**Comment by bogdandrutu** [comment]
I would put that property on the descriptor not the point because it is a property of the whole batch

**Comment by jkwatson** [comment]
This makes sense, yes.

**Comment by evantorrie** [comment]
> * The various aggregations don't behave in the same way. The MinMaxSumCount, which produces a `SummaryPoint` (the descriptor has `Type`= `Summary`) generates delta values, whereas the `Sum` aggregation generates cumulative values. This also means that exporters that need to export deltas have to keep track of the previous value and do the diff themselves, rather than having this be something provided by the SDK.

Yes, this is a pain point for me in writing a custom exporter (which also requires deltas rather than cumulative values). From the exporter side, there doesn't appear to be a way to determine if the aggregation you're receiving is from a stateful/stateless batcher (using the Go Otel terminology).

**Comment by bogdandrutu** [comment]
@jkwatson I would suggest that we close this issue and open more granular issues that we can track easier.

**Comment by jkwatson** [comment]
Closing for more specific issues to come.
