### ISSUE TITLE
Consider having global Propagators in the context-prop package

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#1036]
Currently we plan to have the global propagators in the global `OpenTelemetry` object, but we should consider having them in the `context-prop` artifact (where they are actually defined).

**Comment by jkwatson** [comment]
Now that we've gotten rid of the context-prop package and moved the propagation interfaces to the context package, does this still apply, @carlosalberto ?

**Comment by jkwatson** [comment]
@carlosalberto with #1161 being closed, can we consider this issue closed as well?

**Comment by carlosalberto** [comment]
Ooops, my bad! Was supposed to close this one as well!
