### ISSUE TITLE
Document error handling for auto config

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#1059]
Document how to report **fatal** errors when calling `SpanExporterFactory.fromConfig()`, either:

a) Return `null`.
b) Throw an `Exception`.

@trask Any opinion on this?

**Comment by trask** [comment]
I think throwing exception is good 👍

**Comment by jkwatson** [comment]
@carlosalberto Can we close this? The referenced classes don't exist any more, and all of this has moved to the autoconfigure module, which has it's own exception-throwing error implementation.

**Comment by jkwatson** [comment]
closing do to inactivity.

**Comment by carlosalberto** [comment]
Thanks @jkwatson - I've been rather slow with reviews this week :(
