### ISSUE TITLE
OpenTelemetry singleton shouldn't synchronize on `.class`

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1060]
> you should never synchronize on something that is publicly accessible like a class object. If we need to synchronized, please create an internal lock Object to synchronize on.

_Originally posted by @jkwatson in https://github.com/open-telemetry/opentelemetry-java/pull/1058#discussion_r401045588_

**Comment by bogdandrutu** [comment]
We should use a mutex there :)

**Comment by carlosalberto** [comment]
Any reason to use specifically a mutex here @bogdandrutu ?

**Comment by jkwatson** [comment]
We do need some sort of safe synchronization on this initialization, unfortunately. Otherwise two racing callers could end up getting different copies of the global, one of which would be junk.
