### ISSUE TITLE
Project no longer builds on Windows due to Docker test.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1067]
I guess something needs to be added to CONTRIBUTING.md. Or some Junit assumption could be used to skip the test (or maybe guard it with a gradle/system property).

```
./gradlew build

> Task :opentelemetry-exporters-jaeger:test

io.opentelemetry.exporters.jaeger.JaegerIntegrationTest > classMethod FAILED
    org.testcontainers.containers.ContainerLaunchException: Container startup failed

        Caused by:
        org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@1c3c60df[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)

            Caused by:
            java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration

11 tests completed, 1 failed
```

The test output is not exactly helpful (probably should also be fixed):

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by Oberon00** [comment]
(No, I don't have docker for Windows installed, nor do I want to install it, as I also use Virtualbox)

**Comment by bogdandrutu** [comment]
@Oberon00 docker is a requirement for this, and maybe it should not be. Do you have another proposal on how to do e2e tests?

**Comment by jkwatson** [comment]
docker is a great solution for this; I'd love to hear if there's another, as well. We could consider moving end-to-end tests to a separate gradle task so they could be excluded by those who don't want to run docker.

**Comment by Oberon00** [comment]
I also think docker is great for e2e tests. I also think that it should fail in the CI if docker is not found. But I think docker should not be a requirement for local dev builds.

So a suggestion is to have the CI set a system property "opentelemetry.testing.forceDockerTests=true" so that the tests fail if docker is not found. On the other hand, a Junit assumptions just skips the tests if creating the docker container fails and the system property is not set.

**Comment by Oberon00** [comment]
The other suggestion, is mentioned in the issue: Write down in CONTRIBUTING.md that docker is required to build the project.

**Comment by bogdandrutu** [comment]
@Oberon00 mentioning that docker is required for e2e tests is important.

I also like skipping the e2e tests by default in local builds unless you really want to run them.

**Comment by carlosalberto** [comment]
Late to the party, but would also like to disable the e2e tests by default (which means 'locally' in this context), and enable them in CircleCI.

**Comment by jkwatson** [comment]
ok, let's do this in 2 phases. 

1st, let's document that you need to have docker running to do the full build.  
2nd, figure out the right way to make the docker-based integration tests be easily skippable. On other projects, I've had a separate gradle task called "integrationTest" that would run them, so you could easily tell gradle to skip that task when doing the build. I'm sure there are other options, though.
