### ISSUE TITLE
SemanticAttribute setters are not straightforward to use with SpanBuilder

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1075]
Probably we should introduce some interface SpanOrBuilder that is then passed to *AttributeSetter.set instead of Span.

You can workaround by calling `key` on the setter, but that kinda defeats the purpose.

Follow-up to #758.

**Comment by Oberon00** [comment]
Actually, SpanOrBuilder does not work that well, because Builder.setAttribute returns Builder and Span.setAttribute returns void.

**Comment by Oberon00** [comment]
Actually, we could provide an interface SpanOrBuilder<Derived> if we just changed span to return itself instead of void from setAttribute, which would be a nice usability improvement anyway. Or is this obsoleted by #1130? I think adding some SpanOrBuilder interface would be a relatively small change (basically mostly moving declarations) but still breaking (all Span implementations would need to `return this` in `setAttribute`).

**Comment by jkwatson** [comment]
If we were to do something like this, we'd have to come up with a better name than `SpanOrBuilder`. I'd rather fix the API, rather than introduce odd patches like this.

**Comment by Oberon00** [comment]
I took that name from protobuf, where for each message Foo it generates a Foo, a Foo.Builder and both implement FooOrBuilder. But I'm not married to that name, it was just the first thing that came to my mind.

**Comment by Oberon00** [comment]
This was resolved by #1631 I think.  👍

**Comment by jkwatson** [comment]
resolved with #1631
