### ISSUE TITLE
Metics documentation, examples

### ISSUE THREAD

**Issue by DotSpy** [open-telemetry/opentelemetry-java#1077]
Add metrics documentation, examples
@jkwatson please share video, maybe if u have some source slides\pictures it will help too

**Comment by jkwatson** [comment]
Here's the NewRelic exporter example class that has some usage of the metrics API in it:  https://github.com/newrelic/opentelemetry-exporter-java/blob/master/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java

**Comment by jkwatson** [comment]
@trask is going to request geting the video from the auto-instrumentation SIG uploaded

**Comment by trask** [comment]
Here you go! https://www.youtube.com/watch?v=88ZjCbT6LPc&feature=youtu.be&t=2104

**Comment by jkwatson** [comment]
oof. wish the resolution were just *slightly* better on that upload. It makes all the code just barely unreadable.  :)

**Comment by DotSpy** [comment]
@jkwatson assign me please, i finish my exams and can return to it

**Comment by Jeffrey778** [comment]
@jkwatson  I can't open above links, can anyone fix them?

**Comment by jkwatson** [comment]
> @jkwatson I can't open above links, can anyone fix them?

I no longer work for New Relic, so I can't.
