### ISSUE TITLE
Jaeger requires span.kind tag values to be in lowercase

### ISSUE THREAD

**Issue by sleighzy** [open-telemetry/opentelemetry-java#1079]
The Jaeger Query UI provides functionality for displaying Deep Dependency Graphs of service calls. These are based on the "`span.kind`" tag with the value of "`server`". This is case-sensitive and does not work with the Jaeger auto-instrumentation exporter as the span kind values from the exporter are all in uppercase. The Jaeger deep dependency graph reports that there are no traces found where the span.kind is server. Searching for this manually using the filters using an uppercase value does return results.

In the OpenTracing api string constants were provided for Tags in the `io.opentracing.tag.Tags` class and the values of these were in lowercase.

In OpenTelemetry a new enum can be used for span kind values, see https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/Span.java#L34. These enum values are in uppercase, e.g. "SERVER", "CLIENT". The Jaeger exporter sends the values as-is, https://github.com/open-telemetry/opentelemetry-java/blob/v0.3.0/exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java#L92, so these will be in uppercase when received by the Jaeger collector and stored.

I don't have any experience with other consumers, Zipkin, etc. to know if this impacts them at all. For compatibility purposes with Jaeger the exporter may need to be modified to force these values to lowercase.

**Comment by sleighzy** [comment]
I've posted a question on the jaegertracing Gitter channel as to whether or not this is configurable within Jaeger (or the query component) itself in case its possible to use this value in a case-insensitive nature for this functionality as well.

**Comment by sleighzy** [comment]
Response from Yuri Shkuro on Gitter is that Jaeger follows the the OpenTracing semantics so appears the transformation is incorrect for the OpenTelemetry exporter.

**Comment by carlosalberto** [comment]
@sleighzy Thanks for the background information. So, for the sake of clarity, simply changing the casing should help? Or do we need an actual mapping? (which we do in the OT shim layer).

Also, @pavolloffay might be interested in provide his feedback ;)

**Comment by sleighzy** [comment]
@carlosalberto , thanks for the response. The OpenTracing ones are from this class https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/tag/Tags.java and match the OpenTelemetry ones, except for the usage of the case due to enum. From Yuri's comment they'll be based on https://github.com/opentracing/specification/blob/1.1/semantic_conventions.md. This currently has only four values, whereas the OpenTelemetry one includes the additional "INTERNAL". To be honest I don't know enough to comment as to what, or if, this needs to be mapped to one of the OpenTracing ones for Jaeger. I think I'd just been falling back on "server" when using OpenTracing in the past in my own code for internal calls. To be frank I do actually like the concept of INTERNAL (although lowercased for Jaeger for consistency) as it conveys exactly what it is.

I'll drop a note re: this on my Jaeger Gitter comment to see if there is an explicit desire to have this map to something specific.

**Comment by pavolloffay** [comment]
I do agree with @yurishkuro comment about following OT semantics, however going forward as there will be more types defined in OpenTelemetry and OT will be deprecated we should make Jaeger more resilient. It's also better to fix it at one place rather than in all the clients.

**Comment by yurishkuro** [comment]
`span.kind` in OpenTracing is not _restricted_ to 4 values, you can set it to `internal` as well.

**Comment by sleighzy** [comment]
I have a fix for this I can raise a PR for if no objections.
