### ISSUE TITLE
Add shortcut factory method for tracer and meter

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java#1091]
inspired by the brevity of [LoggerFactory.getLogger](http://www.slf4j.org/apidocs/org/slf4j/LoggerFactory.html#getLogger(java.lang.String)), I'm proposing to add the same for tracer and meter. Once OpenTelemetry is ready, I'd also suggest to add `LoggerFactory`.

```java
public class TracerFactory {
  public static Tracer get(String instrumentationName) {
    return OpenTelemetry.getTracerProvider().get(instrumentationName);
  }
}

public final class TracerSdk implements Tracer {
  public static TracerSdk get(String instrumentationName) {
    return OpenTelemetrySdk.getTracerProvider().get(instrumentationName);
  }
}
```

Same for meter, with `MeterFactory` and static method in `MeterSdk` - and also the flavor that takes `(String instrumentationName, String instrumentationVersion)` as arguments for both.

**Comment by jkwatson** [comment]
Another option might be to just add these shortcuts to the `OpenTelemetry` class itself. 
```
OpenTelemetry.getTracer("tracerName", "v1.0");
OpenTelemetry.getMeter("meterName", "v1.0");
```

**Comment by zeitlinger** [comment]
> Another option might be to just add these shortcuts to the `OpenTelemetry` class itself.
> 
> ```
> OpenTelemetry.getTracer("tracerName", "v1.0");
> OpenTelemetry.getMeter("meterName", "v1.0");
> ```

yes, also a good idea

**Comment by carlosalberto** [comment]
Hey @zeitlinger great to hear you are joining!

So I'm ok with the first proposal, although @bogdandrutu doesn't (usually) likes shortcuts ;) 

I'd personally *slightly* prefer @jkwatson's proposal (I took a similar route with in the OT shim, for example).

**Comment by zeitlinger** [comment]
comparing both suggestions, @jkwatson makes the name OpenTelemtry more prominent - which I like. So I also support that.

**Comment by zeitlinger** [comment]
What about also adding `OpenTelemetry.getTracer()` which would be called by applications (i.e. not a library)?

**Comment by jkwatson** [comment]
> What about also adding `OpenTelemetry.getTracer()` which would be called by applications (i.e. not a library)?

All Tracers need at the minimum a `name`, so this API wouldn't work as-is.

**Comment by zeitlinger** [comment]
> All Tracers need at the minimum a `name`, so this API wouldn't work as-is.

@jkwatson I have questions about this, but I guess this belongs more to the specification group where I've started a thread 

Unfortunately, gitter doesn't provide a thread URL, so this is what I've written:

```
I have a question regarding https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#obtaining-a-tracer

what should I use as name of the tracer if I'm not writing a library?

is it null - since it's not a library?
```

**Comment by jkwatson** [comment]
Yep, can't be null. If you're manually instrumenting your service, you can really put in whatever you want as the name.

**Comment by bogdandrutu** [comment]
I am ok to have a getFoo on OpenTelemetry class with same signature as the current methods on the provider.

**Comment by carlosalberto** [comment]
> I am ok to have a getFoo on OpenTelemetry class with same signature as the current methods on the provider.

I'm ok with that too. Unless @jkwatson disagrees, can we cook a PR for this? Perhaps you want to volunteer @zeitlinger ? ;)

**Comment by zeitlinger** [comment]
@carlosalberto done in #1159.

I also thought about 
1. adding the shortcut methods for correlation context manager as well, but based since it's not even used in https://github.com/open-telemetry/opentelemetry-auto-instr-java/ I didn't do it
2. adding the same methods for `TracerSdk` - but this doesn't work as `TracerSdk` is package protected.
