### ISSUE TITLE
Fix flaky BatchSpansProcessorTest

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1092]
This seems to fail occasionally on CI:

io.opentelemetry.sdk.trace.export.BatchSpansProcessorTest > exportMoreSpansThanTheMaximumLimit

**Comment by jkwatson** [comment]
I ran this test over 5000 times locally on my laptop and couldn't get it to fail. I suspect it might fail in an extremely CPU-starved situation, which is likely to happen on CI.

**Comment by bogdandrutu** [comment]
Have not seen this in the past month or so, closing.
