### ISSUE TITLE
BatchSpanProcessor starts foreground thread, blocks JVM shutdown

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1093]
To reproduce, try the following minimal sample:

```java
 public static void main(String[] args) {
    BatchSpansProcessor.newBuilder(new SpanExporter() {
      @Override
      public ResultCode export(Collection<SpanData> spans) {
        return ResultCode.SUCCESS;
      }

      @Override
      public void shutdown() {

      }
    }).build();
  }
```

The JVM will keep running because the BatchSpanProcessor created a foreground thread. This is a real problem especially for auto-instrumentation where `TracerProvider.shutdown` is usually called from `java.lang.Runtime.addShutdownHook`, which would not get invoked if the JVM never shuts down.

CC @trask

**Comment by Oberon00** [comment]
The same probably applies to the DisruptorEventQueue.

**Comment by carlosalberto** [comment]
I was wondering about this in the past - I'd simply make all of these processor's threads daemon, but I wonder if somebody would ever want that to **not** be the case ;)

Was this ever considered/talked about, back in OC, @bogdandrutu ?

**Comment by Oberon00** [comment]
I would also love to hear from @trask how they handle this in the auto instrumenting agent.

**Comment by trask** [comment]
Auto-instrumentation sets all threads to be daemon, otherwise (as @Oberon00 mentions above), we would prevent normal JVM termination in the case of command-line or batch jobs that run to completion at the end of a `main()` method.

Auto-instrumentation is still only using `SimpleSpanProcessor` (but we should upgrade), so we didn't run into this yet with `BatchSpanProcessor`.

**Comment by johnbley** [comment]
Some usage of the auto-instrumenter can cause this - for example, when experimenting with the otlp exporter I ran into this issue...

**Comment by trask** [comment]
@johnbley Nice catch!
