### ISSUE TITLE
Rename `contrib` and `sdk_contrib`

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java#1100]
`contrib` is causing a bit of confusion around the intention.  Perhaps something like `util` or `ext` instead?

**Comment by iNikem** [comment]
@tylerbenson What IS the intention of those submodules?

**Comment by tylerbenson** [comment]
This was explained on a call by @bogdandrutu but I forgot what he said.

**Comment by iNikem** [comment]
I would love to start transferring some tribal knowledge from peoples head into more readable documentation. I totally feel the pain of new contributor and want to help future generations. So if somebody can explain their meaning to me, I will augment `CONTRIBUTING.md`. And I can make the actual PR of renaming folders, if needed :)

**Comment by bogdandrutu** [comment]
* contrib has functionality that depends only on the API
* contrib_sdk has functionality that depends on the API (may by just indirect via the SDK dep) + SDK

For the moment these were the only rules we applied, but based on the specification https://github.com/open-telemetry/opentelemetry-specification/pull/539 we should split the contrib into `instrumentation` (will have all the instrumentation that depends on the API only) and `contrib` (will contain any helper packages that depend on the API but are not instrumentations like the `WithSpan` annotation)

**Comment by bogdandrutu** [comment]
@iNikem you got it :)

**Comment by iNikem** [comment]
@bogdandrutu but I still don't quite understand what does `contrib` part of those names mean? And I think just renaming them to `util` will not bring any clarity into their intention.

**Comment by bogdandrutu** [comment]
What name do you expect for some utility artifacts? We choose to call them `contrib`, it is a naming decision (maybe a better name can be used). I am not sure what is unclear.

**Comment by iNikem** [comment]
E.g. what are criteria for the decision to put some functionality into contrib/util and not into API/SDK proper? If we just say "this is a bunch of utility/helper artefacts", then I am afraid it will become what every `util` package becomes: big ball of mud :)

**Comment by iNikem** [comment]
Talked to Bogdan during SIG meeting and we agreed on the name `extra` and `sdk_extra`.

**Comment by carlosalberto** [comment]
I don't like the names of `extra` and `sdk_extra`. What is the rationale behind this?

**Comment by iNikem** [comment]
They contain additional, utility functionality that some users may want, while others don't. They are not "contributed" by some external third party, but are maintained by the same "team" (in loos OSS sense of word) as `api` or `sdk` proper.

**Comment by trask** [comment]
I also find the name `contrib` confusing. It gives me the impression that it is a grouping for things that are contributed (and possibly maintained) by other people.

Maybe `extensions` and `sdk_extensions`? (based on @tylerbenson's `ext` proposal above)
