### ISSUE TITLE
HttpTextFormat.extract() can throw StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1107]
`HttpTextFormat.extract()` throws `StringIndexOutOfBoundsException` on short (invalid) `traceparent` due to unchecked `charAt` calls:
https://github.com/open-telemetry/opentelemetry-java/blob/v0.3.0/api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java#L165-L170

**Comment by carlosalberto** [comment]
Maybe this was solved by #1102 ?

**Comment by trask** [comment]
Yes, thanks! Closing this.
