### ISSUE TITLE
Tracing multiple applications in application servers

### ISSUE THREAD

**Issue by fmhwong** [open-telemetry/opentelemetry-java#1109]
In an application server that supports multiple applications, we are using OpenTracing API in JAX-RS filters to automatic instrument applications. Each application has its own instance of `Tracer`. Implementations such as `BraveTracer` or `JaegerTracer` can be instantiated and configured with their own service names.  Multiple tracer implementations can export spans to a single OpenTracing server. 

In OpenTelemetry, created 2 instances of `Tracer` using

```
Tracer tracer1 = OpenTelemetry.getTracerProvider().get("app1");
Tracer tracer2 = OpenTelemetry.getTracerProvider().get("app2");
```

Created a `SpanProcessor` and  `SpanExporter` using
```
ManagedChannel jaegerChannel = ManagedChannelBuilder.forAddress(ip, port).usePlaintext().build();
JaegerGrpcSpanExporter jaegerExporter = JaegerGrpcSpanExporter.newBuilder().setServiceName("app1")
                .setChannel(jaegerChannel).setDeadlineMs(30000).build();
OpenTelemetrySdk.getTracerProvider().addSpanProcessor(SimpleSpansProcessor.newBuilder(jaegerExporter).build());
```

In this case, spans from `tracer1` and `tracer2` got reported as "app1" in the backend because of the serviceName set in the `SpanExporter`.  Creating another instance of `SpanProcessor` for "app2" to the same backend will result of duplication of span IDs in the backend.

**Comment by Oberon00** [comment]
This is an API bug IMHO. addSpanProcessor should be on the TracerProvider, not the tracer, as the list of span processors is shared between all tracers.

**Comment by Oberon00** [comment]
Related to the topic (but not that particular issue) is https://github.com/open-telemetry/opentelemetry-specification/issues/335

**Comment by fmhwong** [comment]
It seems `JaegerGrpcSpanExporter` is capable of exporting spans for a single service name only.  If `JaegerGrpcSpanExporter` can get the name from the `Tracer` and use it as the service name, this will eliminate the need to have multiple Exporters.

**Comment by Oberon00** [comment]
The Tracer is not meant to represent a service. It just represents the reporting artifact name and version. I think there is currently no way to do this properly with a single class loader, but you can look at https://github.com/open-telemetry/oteps/issues/78 and the aforementioned  open-telemetry/opentelemetry-specification#335 to voice your opinions. IMHO the service should be taken from the resource by the JaegerGrpcSpanExporter (we already have `service.name` in https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions#service).

**Comment by bogdandrutu** [comment]
Related https://github.com/open-telemetry/opentelemetry-java/pull/350

**Comment by jkwatson** [comment]
> This is an API bug IMHO. addSpanProcessor should be on the TracerProvider, not the tracer, as the list of span processors is shared between all tracers.

`addSpanProcessor` is already on the TracerSdkProvider. I'm not sure what you're referring to.

**Comment by Oberon00** [comment]
You are right, I misread the posted sample code. addSpanProcessor is where it should be 👍
