### ISSUE TITLE
[meta] Bring back meeting notes or create a new doc

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#1114]
The Google doc we used for writing down meeting notes of the weekly SIG meeting is no longer accessible to the public (as reported on [Gitter](https://gitter.im/open-telemetry/opentelemetry-java?at=5e955f97c52b6a38abe4f6c7)):
https://docs.google.com/document/d/1oHpisisco8J7Yk73ovx3eeXaokSMqgVuEuWNwPOajtY/

If the owner still has access to it, please enable public write access again but don't allow the public to edit permissions. I'd suggest granting those admin rights to all maintainers of the Java SIG, however.
I don't know who the owner is but I could imagine @tedsuo, @SergeyKanzhelev or @carlosalberto created the doc back then when we were bootstrapping the Java SIG.

If we can't find the owner or they no longer have access themselves, we should figure out in which org to best create a new doc and grant the permissions as mentioned above.
If someone downloaded/copied the meeting notes by chance, please let us know so we can at least restore them partially.

We will also have to make sure that the doc doesn't suddenly vanish again in future but that should probably be taken care of in a broader scope on the community repo.

**Comment by carlosalberto** [comment]
I'm sadly not the owner - maybe @bogdandrutu created this doc under his former Google account?

**Comment by carlosalberto** [comment]
Closing this issue as we recovered access already ;)
