### ISSUE TITLE
Consolidate common logic for the Propagators benchmark

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#1117]
The newly added benchmark code for Jaeger is basically identical to the one used for TraceContext, so we should consolidate such common logic (handy also when adding the benchmark code for B3).

**Comment by jarebudev** [comment]
i can pick this up

**Comment by carlosalberto** [comment]
@jarebudev Thanks. The only thing to keep in mind is that now B3/Jaeger propagators live in a separate repo, so not sure this can be still easily shared with the TraceContext one.

Worst case: At least have the B3/Jaeger JHM logic shared ;)
