### ISSUE TITLE
Implement the ALWAYS_PARENT sampler

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1119]
See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#built-in-samplers in the specs

**Comment by bogdandrutu** [comment]
I think the specs is clear, it says if it has a parent and parent is sampled then true otherwise false. I am not sure what is the confusion.

**Comment by bogdandrutu** [comment]
I think I got the confusion and opened a PR in specs.

**Comment by MitchellDumovic** [comment]
I think https://github.com/open-telemetry/opentelemetry-java/pull/1444 resolves this issue?

**Comment by jkwatson** [comment]
closing by #1444 .
