### ISSUE TITLE
Contrib packages should not use "internal" API package.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1125]
Internal package should not be used outside of API (maybe SDK). The reason is called internal is because we don't have the guarantees that we have in the API for the API stability.

**Comment by devinsba** [comment]
I've used [ArchUnit](https://github.com/TNG/ArchUnit) for enforcing this at the CI level before. It would probably be good to have something like this codified so that it's not just tribal knowledge

**Comment by iNikem** [comment]
As a new contributor-to-be I am interested in this task. I support @devinsba suggestion to codify this requirement. [ArchUnit](https://github.com/TNG/ArchUnit) seems like a good option for this.

Concerning current usage, it is very easy to replace `io.opentelemetry.internal.Utils#checkNotNull` with `java.util.Objects#requireNonNull(T, java.lang.String)`. Not sure about `StringUtils#isNullOrEmpty`. It seems quite trivial functionality, so maybe just replace "reuse" with duplication?

**Comment by jarebudev** [comment]
It looks like the B3 and Jaeger propagators that are using the internal classes could be easily changed to use equivalents in guava.

For uses of ```StringUtils``` then methods in ```com.google.common.base.Strings``` class, and for checking null parameters, ```com.google.common.base.Preconditions.checkNotNull``` .

The ArchUnit plugin sounds like a sensible addition too.

**Comment by xSystemErrorx** [comment]
Al chile no les entiendo ni madres, español?

**Comment by berkcan77** [comment]
I've used ArchUnit for enforcing this at the CI level before. It would probably be good to have something like this codified so that it's not just tribal knowledge [okey oyna](https://www.maksatokey.com)

**Comment by simone02f** [comment]
salut comment vas tu Moi je recherche tout d'abord a entamer une relation amicale je veux dire par la que je veux mieux connaitre et apprendre a connaitre la personne avec laquelle je discute avant d'aller plus loin !
Sinon en temps normal je recherche un homme sérieux et sincère avec qui je pourrai entamer une relation sérieuse et durable.
Et compte tenu du fait que je n'ai pas encore d'enfants j'aimerai bien fonder une belle famille avec de très beaux enfants ...car moi j'aime beaucoup les enfants et j'aime bien prendre soins d'eux 
Dis moi tu as un Compte Hangouts pour mieux fais connaissance  si cela ne vous dérange pas tu tout simone080330@gmail.com

**Comment by simone02f** [comment]
hi how are you me I am looking first of all to start a friendly relationship I mean by that I want to know better and get to know the person with whom I am talking before going further!
Otherwise normally I am looking for a serious and sincere man with whom I can start a serious and lasting relationship.
And given the fact that I don't have any children yet, I would like to start a beautiful family with very beautiful children ... because I really like children and I like to take care of them.
Tell me you have a Hangouts Account to get to know each other better if you don't mind all simone080330@gmail.com

**Comment by xSystemErrorx** [comment]
Español?)):

**Comment by Francine09** [comment]
Hello Are you looking for a loan urgently? is : To revive your financial activities? To renovate the interior of your apartment; House; building ? Rental? Buying a car? Credit for marriage? Settlement of a debt? For the realization of a project? Or for other reasons etc ... Loan offer between individuals I put at your disposal a loan from 5,000 to 900,000,000 Euros with very simple conditions at a rate of 2%. I also make investments and loans between individuals of all kinds. I offer short, medium and long term loans. For more information please contact me directly at my email address PS: I only lend to honest people who are likely to refund my money.
offredepret.fr25@gmail.com

https://maribelle-bonnet.business.site/?m=true

**Comment by simone02f** [comment]
Îți trimit mesaj pe gmail

**Comment by simone02f** [comment]
I'm sending you a message on gmail

**Comment by Francine09** [comment]
Ai nevoie de împrumutul de bani

**Comment by Cmpelon210** [comment]
Thanks for your feedback back I'm new and learning

**Comment by Francine09** [comment]
Do you need the loan of money
