### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1126]
It is not easy for new contributors to ensure that their IDE is configured accordingly to the required code style. The only way right now is to carefully read Google Java Style Guide and change their IDE configuration manually. Or to remember to run `gradlew goJF` before commit.

The easier approach would be to provide [.editorconfig](https://editorconfig.org) file which would apply desired formatting rules automatically.

**Comment by jkwatson** [comment]
Is there an editorconfig file that matches the style/format that matches what goJF requires/generates?  Is so, then I'm 100% in favor of this.

**Comment by iNikem** [comment]
I could not find it in 5 minutes, but I am willing to compose one.

**Comment by Oberon00** [comment]
Isn't .editorconfig most useful for just the basics like line endings and tabs vs spaces?

**Comment by iNikem** [comment]
@Oberon00 at least IntelliJ IDEA provides much more: https://blog.jetbrains.com/idea/2019/06/managing-code-style-on-a-directory-level-with-editorconfig/

**Comment by jkwatson** [comment]
I've been able to get it *close*, but not exactly the same. Two things i haven't figured out:
1. javadoc formatting is slightly different
2. force empty constructors to be on a single line : `Constructor() {}`

**Comment by iNikem** [comment]
@jkwatson will you share your result with us? :)

**Comment by pavolloffay** [comment]
We should document `goJF` in contributing guidelines and probably what it into format make target. I always forget the name of gradle task.

**Comment by thisthat** [comment]
What about adding `goJF` as a pre-requisite of `compileJava` in the gradle.build file?

**Comment by iNikem** [comment]
I would even go further and add this as git pre-commit hook

**Comment by carlosalberto** [comment]
I personally would like to have it as a pre-commit hook or similar, but don't have it as a requirement of `compileJava`, i.e. quite often when refactoring or prototyping I get annoyed/distracted by the style messages/errors.

In any case, that's a different conversation. Lets do the .editorconfig change and document the `goJF` case (in a separate commit) as Pavol suggested.

**Comment by thisthat** [comment]
@carlosalberto what I meant was not to call the verify task but the automatic reformatted. This way, every time a compilation is performed, it is automatically formatted correctly.

**Comment by carlosalberto** [comment]
@thisthat I personally still don't like that. My 'dead' code when refactoring is suddenly gone automatically. Wouldn't love that ;) In any case, shall we fill a new issue? We can iterate on our options there and decide what's the best trade-off ;)

**Comment by thisthat** [comment]
> @thisthat I personally still don't like that. My 'dead' code when refactoring is suddenly gone automatically. Wouldn't love that ;) In any case, shall we fill a new issue? We can iterate on our options there and decide what's the best trade-off ;)

Actually, that's a fair point! :smile: You convinced me!

**Comment by jkwatson** [comment]
Here's what I have, which is close, but not perfect. I've also just hooked up a pre-commit hook to do the formatting as a fail safe.

[editorconfig.txt](https://github.com/open-telemetry/opentelemetry-java/files/4529660/editorconfig.txt)

**Comment by jkwatson** [comment]
Here's the pre-commit hook that I've started using.

[pre-commit.txt](https://github.com/open-telemetry/opentelemetry-java/files/4529833/pre-commit.txt)

**Comment by trask** [comment]
We are enforcing goJF in auto-instr-java also, and these Intellij plugins have been working well for me:

* [google-java-format](https://plugins.jetbrains.com/plugin/8527-google-java-format)
* [Save Actions](https://plugins.jetbrains.com/plugin/7642-save-actions)

![image](https://user-images.githubusercontent.com/218610/80235322-66c3e600-860e-11ea-9d1f-e4000b3e9a52.png)

**Comment by iNikem** [comment]
Problem with plugins is that every developer has to install them, and to know that they have to install them. EditorConfig works out the box with IntelliJ.

**Comment by carlosalberto** [comment]
Having .editorconfig is a good start. *Then* we can add a docs section on how to configure commonly used plugins/hooks :)

**Comment by jkwatson** [comment]
I spent a bunch of time in IDEA yesterday trying to perfectly replicate the google java format, and i don't believe it's possible with the current set of options, unfortunately. So, even with a `.editorconfig`, you can/will commit code that doesn't match what the verifier requires. Unless you put in a pre-commit hook, or do it manually, of course.

**Comment by iNikem** [comment]
@jkwatson Thanks for the file. I think it is a great start which will make a life of new contributors significantly easier :)
