### ISSUE TITLE
Jaeger exporter does not set error boolean

### ISSUE THREAD

**Issue by sleighzy** [open-telemetry/opentelemetry-java#1139]
Jaeger (the OpenTracing collector and visualisation tool, https://www.jaegertracing.io/) uses the `error` tag on spans with a boolean value of `true` to identify and display in the UI which spans have errors. This can be used to easily search for traces that contain errors within the Jaeger UI as well. This tag is part of the OpenTracing semantic conventions.

When sending spans to the OpenTelemetry collector using the Jaeger or OTLP exporter it will translate the `span.status.code`, or `status.code` depending on the configured receiver, to the associated `error` tag before exporting the spans to Jaeger. When using the Java Jaeger exporter and sending spans directly to a Jaeger collector however this boolean is not set. Whilst you can query in Jaeger for spans that have a `span.status.code != 0` this is cumbersome, and there is no visual display of any spans with an error state.

**Comment by sleighzy** [comment]
I have a simple fix to add the error boolean tag in the Adapter class if the span status is not OK. Let me know if this is acceptable.

**Comment by jkwatson** [comment]
Please! Fixes absolutely welcome!

**Comment by sleighzy** [comment]
Hmmm. This works successfully when sending directly to the Jaeger collector, and also when sending spans to the OpenTelemetry Collector version 0.3.0 release. I've retested with the latest dev release of the OTel collector Docker container and unfortunately due to the PR https://github.com/open-telemetry/opentelemetry-collector/pull/833 introduced 10 days ago the behaviour has now changed. This is also adding an error tag when the status is not ok and so the Jaeger UI now displays a warning indicated that there are duplicate error tags on the span.

Working as expected (OTel Jaeger exporter -> Jaeger collector):

<img width="1287" alt="Jaeger exporter with Jaeger collector" src="https://user-images.githubusercontent.com/4580060/80268143-29885280-86f9-11ea-9060-48c762d5335a.png">

Duplicate tag warnings (Jaeger exporter -> OTel Collector -> Jaeger exporter -> Jaeger collector):

<img width="1456" alt="Jaeger exporter with OTel collector and duplicate error warnings" src="https://user-images.githubusercontent.com/4580060/80268181-46bd2100-86f9-11ea-829c-d48eed076a08.png">

I'll raise an issue with the OTel collector as this seems at face value something that could occur with other OpenTracing Jaeger clients sending spans to the OTel collector.

**Comment by sleighzy** [comment]
Update: And then a change made to the OTel Collector today modified the behaviour again and fixed this problem with regards to the duplicate "error" tag. Good news. The Jaeger protobuf translations for the collector used for the receiver have now moved to the internal format, and the "error" tag is removed from the attributes if it exists: https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/trace/jaeger/jaegerproto_to_traces.go#L207 after setting the appropriate status code.

The OTel collector adds the "error" tag as expected when doing the outbound translation to the Jaeger exporter if the status code isn't ok. I can go ahead with this change given this is working fine now on the OTel collector side.
