### ISSUE TITLE
java.util.logging does not work in shutdown hooks, but OTel does important things there

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1147]
It seems that java.util.logging [resets](https://docs.oracle.com/javase/7/docs/api/java/util/logging/LogManager.html#reset()) itself in a shutdown hook that is added in the constructor of LogManager. E.g. if you configured a log file and a custom logging level, during shutdown the logs will instead be logged to stderr with the default level of INFO. Note that at shutdown the JVM "will start all registered shutdown hooks in some unspecified order and let them run concurrently." (<https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)>). See https://stackoverflow.com/a/13825590/2128694

opentelemetry-java does quite important things in shutdown (e.g. exporting a final time, which may be the only time for short-running processes) and that shutdown is a prime candidate to be called from a shutdown hook (auto-instrumenting agents basically have no other choice). The linked SO answer suggests overriding the global Log Manger, but that is probably too invasive for auto-instrumenting agents.

IMHO we need to find a solution for this. Either there is a way for auto-instrumenting agents to work around this in a way that does not influence application logging, or some different logging framework needs to be used. In the worst case, the limitations should at least be documented, since debugging a shutdown failure with an unexpected log level has already cost me quite some time.

EDIT: This is https://bugs.openjdk.java.net/browse/JDK-8161253

CC @trask

**Comment by carlosalberto** [comment]
> In the worst case, the limitations should at least be documented, since debugging a shutdown failure with an unexpected log level has already cost me quite some time.

We should definitely document this for a start, while we decide our options there.

**Comment by jkwatson** [comment]
Neither the SDK nor the API register any shutdown hooks. This seems to be an issue for the auto-instrumentation agent, rather than the API or SDK, correct?

**Comment by Oberon00** [comment]
Yes. This issue appears only when you actually try to use the SDK so to speak 😅

**Comment by Oberon00** [comment]
But actually I think the OTel auto instrumentation has solved this already as byproduct of redirecting the `getLogger` calls in their gradle build to something that is not java.util.logging-based, see related https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/335

**Comment by jkwatson** [comment]
It sounds like you're asking to have documentation that we use java.util.logging in the SDK? There are many other bugs in the JDK/JVM (especially for java 7!). We wouldn't want to document them in this repo as well, would we? I guess I'm not sure what this issue is suggesting we actually do.

**Comment by Oberon00** [comment]
You may be right and this may be common knowledge. But I did not know about this bug, I suspect more people could run into it and AFAIK it's still unresolved in newer versions of Java so maybe it's worth adding an FAQ entry or the like for it.

**Comment by carlosalberto** [comment]
@Oberon00 I will be adding a FAQ soon so I might include this note on it ;)

**Comment by trask** [comment]
Nice find! I didn't know about this.

Interestingly, this issue doesn't (shouldn't?) affect opentelemetry-auto-instr-java because it shades all `java.util.logging` usage in its dependencies (including the embedded OTel SDK) and makes them instead use [PatchLogger](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/agent-bootstrap/src/main/java/io/opentelemetry/auto/bootstrap/PatchLogger.java), which has same methods as `j.u.l.Logger`, but delegates to (shaded) SLF4J.

This serves two purposes (well, now three!)
* it prevents dependencies from initializing java.util.logging too early (which causes problems on jboss/wildfly)
* it keeps all auto-instrumentation related logging going to a single place (shaded SLF4J)
* now, this shutdown hook issue 😄

**Comment by jkwatson** [comment]
@Oberon00 I'm curious what logging in particular was getting swallowed that made your life difficult. Is there another approach we could use, that wasn't dependent on logging that might have helped?

**Comment by Oberon00** [comment]
I had my own SpanProcessor and was doing a `logger.fine("shutdown invoked")` there and was puzzled why I did not see it, despite setting the logging level.

**Comment by jkwatson** [comment]
@Oberon00  Is this still an issue, or can we close it?

**Comment by Oberon00** [comment]
I think this is even more of an issue now, because the autoconfigure module will now actually install shutdown hooks, so

> Neither the SDK nor the API register any shutdown hooks.

No longer applies.

**Comment by jkwatson** [comment]
> I think this is even more of an issue now, because the autoconfigure module will now actually install shutdown hooks, so
> 
> > Neither the SDK nor the API register any shutdown hooks.
> 
> No longer applies.

So, this issue should now be to "Add documentation about logging and shutdown hooks to the autoconfigure module"?

**Comment by Oberon00** [comment]
I think that would be one valid solution 👍
