### ISSUE TITLE
Add a Zipkin integration test using Testcontainers

### ISSUE THREAD

**Issue by jarebudev** [open-telemetry/opentelemetry-java#1178]
The Jaeger exporter has an integration test that uses Testcontainers to spin up a container running Jaeger all-in-one for the duration of the test, see ```JaegerIntegrationTest```.

It would be good to have a similar test for Zipkin, using the ```openzipkin/zipkin-slim``` image

**Comment by pavolloffay** [comment]
Testcontainers might not be needed for zipkin. Zipkin project provides a direct integration with junit https://github.com/openzipkin/zipkin/tree/master/zipkin-junit.

**Comment by DotSpy** [comment]
Yeap zipking had it's own Rule and we already had tests for it. Also tests with testcontainers had a lot of time to startup and sometimes failing due to quay.io is unreachable. As long as there are no trouble with zipkin-junit we should stick to it

**Comment by jarebudev** [comment]
> Yeap zipking had it's own Rule and we already had tests for it. Also tests with testcontainers had a lot of time to startup and sometimes failing due to quay.io is unreachable. As long as there are no trouble with zipkin-junit we should stick to it

Yeh thats fair enough - I thought I'd suggest it as I've been using Testcontainers a fair bit recently and its been really useful to verify that end to end code works against real implementations.

**Comment by jkwatson** [comment]
closing this, as we're using the ZipkinRule already in the `ZipkinSpanExporterEndToEndHttpTest`
