### ISSUE TITLE
Extend functionality of No-op implementation: w3c and context propagation

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#118]
Based on this https://github.com/bogdandrutu/openconsensus/pull/113#discussion_r275140182

**Comment by SergeyKanzhelev** [comment]
I'd say we can discuss what API package should be capable of without SPI. I'd argue that basic context extraction, propagation and injection should be possible even when no SPI present.

**Comment by tedsuo** [comment]
Agreement:
* Name this `Default` instead of `Noop`.
* Propagate W3C format
* Propagate Baggage
* Transparent forwarding: no change to trace-context or baggage

**Comment by tedsuo** [comment]
@pavolloffay do you mind tackling this one?

**Comment by bogdandrutu** [comment]
Some related code here:
https://github.com/bogdandrutu/openconsensus/pull/232
https://github.com/bogdandrutu/openconsensus/pull/229

**Comment by pavolloffay** [comment]
Sounds fine I will tackle this.

**Comment by pavolloffay** [comment]
It seems like everything is done. Closing,  renaming is traced in #258
