### ISSUE TITLE
Make ZipkinSpanExporter class public

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java#1182]
Could you please provide info how to use non public class `ZipkinSpanExporter`?
Is it internal class not for usage by apps?

**Comment by carlosalberto** [comment]
It looks we should simply make it public. Any reason to not make `ZipkinSpanExporter` public @jkwatson ?

**Comment by jkwatson** [comment]
Not sure why it ended up non-public. It definitely should be publicly accessible.

**Comment by malafeev** [comment]
thanks for fix, could you make a minor release?
