### ISSUE TITLE
Support "MultiFormat" TextFormat 

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#119]
See https://github.com/bogdandrutu/openconsensus/pull/113#issuecomment-482871188

**Comment by SergeyKanzhelev** [comment]
I'd say it should be implemented in contrib or SDL package. Not in API.

**Comment by carlosalberto** [comment]
Having it in a contrib package sounds the best option to me.

**Comment by jkwatson** [comment]
@carlosalberto I think this one is done now. closing.
