### ISSUE TITLE
TraceID.getLowerLong() returns the less random part of the trace

### ISSUE THREAD

**Issue by thisthat** [open-telemetry/opentelemetry-java#1190]
**Describe the bug**
`TraceId.getLowerLong()` returns the leftmost part of the trace id. This method is expected to return the part of the trace which is more random. According to the [W3C Trace Context Standard](https://www.w3.org/TR/trace-context/#interoperating-with-existing-systems-which-use-shorter-identifiers), this corresponds to the rightmost part of the trace. 

**Steps to reproduce**

```java
TraceId traceId = new TraceId(0x12345L, 0x67890L);
assertThat(traceId.getLowerLong()).isNotEqualTo(0x12345L);
```

**Comment by bogdandrutu** [comment]
@thisthat please don't use the ctor that takes longs because that is an internal representation detail. Use https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/TraceId.java#L111

Also we should consider to remove the API that accepts longs.

**Comment by thisthat** [comment]
@bogdandrutu I just used it to have a minimum example that showcases the error.
