### ISSUE TITLE
Improve performance of trace/metrics export pipeline by reducing number of allocs

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1191]
Currently in the trace and metrics exporters we use SpanData and MetricData, here are some benefits:
1. Both objects are immutable which guarantees that multiple exporters can consume them safely.
2. Another benefit is that for cases where users call into the Span api with a custom `Event` to allow lazy formatting (of attributes or event name) and hold external memory (reference to other objects) we do the formatting when converting to SpanData and remove references to these objects.

I think we should look into providing an alternative implementation that can achieve the same guarantees without having to reallocate all the recorded objects.

One proposal is to have something like "FreezeSpan" on the `ReadableSpanImpl` that will transform all the internal lists/maps into immutable objects as well as will force initialize objects (remove references to the external memory if any, and format names/attributes).

**Comment by jkwatson** [comment]
@bogdandrutu Are you thinking that the "freezing" of the span would happen when the span is ended, or do you think this should live at a different point in the lifecycle?

**Comment by bogdandrutu** [comment]
I think we should do it later and only if needed.

**Comment by jkwatson** [comment]
> I think we should do it later and only if needed.

Are you thinking that it would happen on the first call to "toSpanData" (or the equivalent? Or, a new method on the RERS class that would do the freeze? In that case, who would call the freeze method? SpanProcessor?

**Comment by bogdandrutu** [comment]
Don't know yet. I have not thought all the way to this level of details :).

**Comment by jkwatson** [comment]
Cool. I'm pretty close to having something ready to show.

**Comment by bogdandrutu** [comment]
@jkwatson more ideas:

* Make SpanData.Event interface and have a SpanDataImpl.EventImpl implementation for testing.
* Then make TimedEvent in the SDK implement SpanData.Event, so in the getImmutableTimedEvents we don't create new events for events that are already immutable. Currently we copy all the events.

**Comment by jkwatson** [comment]
@bogdandrutu can we close this now? Or do you have more ideas on how to improve this?

**Comment by jkwatson** [comment]
I think we've got the majority of the low-hanging fruit done for this. Let's open up new issues for any new optimizations that we want to make.
