### ISSUE TITLE
You can add attributes to a started span via the builder that created it

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1199]
**Describe the bug**
When we start a span, we should make a copy of the attributes from the SpanBuilder, but instead we just use a reference to the Builder's collection. This means you can continue to add attributes via the Builder.

**Steps to reproduce**
```
    Span.Builder spanBuilder = tracerSdk.spanBuilder(SPAN_NAME);
    spanBuilder.setAttribute("attr1", "value1");

    // this should make a copy of the attributes from the builder
    RecordEventsReadableSpan span = (RecordEventsReadableSpan) spanBuilder.startSpan();
    Map<String, AttributeValue> startingAttributes = span.toSpanData().getAttributes();

    // add another link to the *builder*
    spanBuilder.setAttribute("attr2", "value2");

    // this number is correct
    assertThat(startingAttributes.size()).isEqualTo(1);
    // but, we actually added an attribute to the underlying collection, via the builder.
    assertThat(span.toSpanData().getAttributes().size()).isEqualTo(1);
```

**Comment by carlosalberto** [comment]
I'd be up for indeed making a copy of the attributes. Wondering what @bogdandrutu thinks about this (as it would mean more allocations ;) )

**Comment by jkwatson** [comment]
I discovered this while starting to work on getting rid of the SpanData allocations, so maybe it'll all balance out. :)

**Comment by bogdandrutu** [comment]
We can avoid an allocation by moving the initial list to the Span instead of copying it. When the Span is created we initialize the span attributes with the list (data structure for attributes) created in the builder, and we make the list in the builder null.
