### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by thisthat** [open-telemetry/opentelemetry-java#1212]
**Is your feature request related to a problem? Please describe.**
Maintaining the year up2date is a cumbersome activity.

**Describe the solution you'd like**
Remove the year value from the license headers.

**Describe alternatives you've considered**
Another option would be a more concise version of the header as reported in 
https://github.com/open-telemetry/community/issues/113#issuecomment-619211462. However, this would still require to fill in the year. 

**Additional context**
The auto-instr already does not report the year in their license, e.g. 
https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/agent-bootstrap/src/main/java/io/opentelemetry/auto/bootstrap/Agent.java

**Comment by jkwatson** [comment]
I think we could use the concise version without the year, but it's worth checking with the TC.

**Comment by bogdandrutu** [comment]
It is correct to use no year :)
