### ISSUE TITLE
Shim from OpenTracing impl to OpenTelemetry API

### ISSUE THREAD

**Issue by joshgav** [open-telemetry/opentelemetry-java#1214]
**Is your feature request related to a problem? Please describe.**
I'd like to use the OpenTelemetry API/SDK with an OpenTracing tracer, specifically [AppDynamics'](https://docs.appdynamics.com/display/PRO45/Open+Tracing+Support). AppD doesn't (yet?) provide an OpenTelemetry or even OpenCensus exporter or tracer, so using their OpenTracing tracer seems to be the only integration option for now.

**Describe the solution you'd like**
I'd like a shim which bridges from an OpenTracing tracer implementation to the OpenTelemetry API, similar to the [existing inverse shim](https://github.com/open-telemetry/opentelemetry-java/tree/master/opentracing_shim), which bridges from an OpenTelemetry tracer impl to the OpenTracing API.

**Describe alternatives you've considered**
I'd be even happier with a shim which bridges from an OpenTracing tracer to the OpenTelemetry _Exporter_ API, so it could be used in the collector rather than in process, but assume that would be more difficult if not impossible due to different correlation identifier formats.
I've asked the vendor and will continue to do so about providing an exporter themselves.

**Comment by bogdandrutu** [comment]
I don't think we will want to support this as it is a harder problem than just making an exporter in Opentelemetry for AppD and rely on the implementation in Opentelemetry to collect span data. Do you think that is reasonable?

**Comment by carlosalberto** [comment]
I'd also vow your having an AppD exporter - this is what we did for Jaeger (which is OpenTracing compliant) and worked great.

**Comment by joshgav** [comment]
@bogdandrutu 

> making an exporter in Opentelemetry for AppD and rely on the implementation in Opentelemetry to collect span data

Yes, that's reasonable and I'll pursue that. :+1: I think we can perceive the OpenTelemetry API as a new version of the OpenTracing API (i.e. v0.34!) and ask vendors to "upgrade", ideally by providing an exporter instead of a tracer.

@carlosalberto 

> I'd also vow your having an AppD exporter

The trouble is AppD's formats and source are proprietary and closed :( so it's iffy for someone other than AppD themselves to write the initial implementations. Best to get AppD themselves on board if possible.

I'll close this request now but follow it, if other users come along with a similar request hopefully they'll find it and +1 and/or comment.

Thanks for the consideration.

**Comment by wimnat** [comment]
@joshgav I assume you're pursuing this with your AppD account team?  If you've got any names or case numbers in AppD I am happy to throw my weight behind this.

**Comment by joshgav** [comment]
Thanks @winmat, I've indeed been working with AppD folks and they now have a plan for OT support soon. In particular I've been watching the work in progress [here](https://github.com/Appdynamics/opentelemetry-collector-contrib) on an AppD exporter :+1:.
