### ISSUE TITLE
Consider naming "RecordBatch" to "NewBatch"

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-java#1253]
**Is your feature request related to a problem? Please describe.**
Noticed some stutter in the API name, discussed here:
https://github.com/open-telemetry/opentelemetry-specification/pull/601#discussion_r427635407

**Describe the solution you'd like**
The name "NewBatch" sounds like it creates a builder interface, "RecordBatch" doesn't.

**Describe alternatives you've considered**
The current solution is OK.

**Additional context**
n/a

**Comment by jkwatson** [comment]
@jmacd The current Java API for this looks like:

```java
BatchRecorder recorder = meter.newBatchRecorder("key1", "value1", "key2", "value2");
recorder.put(counter, 33);
recorder.put(upDownCounter, -44);
recorder.record();
```

I'm not sure I understand what you think should change.

**Comment by jmacd** [comment]
This is fine. In the discussion of spec PR 601 Bogdan suggested the call was `meter.recordBatch()`.  `meter.newBatchRecorder()` sounds good.
