### ISSUE TITLE
Change public APIs to not accept Map<String, AttributeValue>

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1258]
Proposals:
1. Use guava ImmutableMap - probably want to avoid guava dependency in the API.
2. Add our own class that is immutable instead of using a map.

The main motivation is that because the map is not immutable we have to do a copy of the entire map all the time.

**Comment by jkwatson** [comment]
Take a look at #1130 for one proposal to have an `Attributes` class that could probably fulfill this need (although not the specific implementation in that brainstorm)

**Comment by bogdandrutu** [comment]
@jkwatson looked at that, it does more than this issue require. But maybe that's what we need, still thinking about this.

Also: Bonus for labels we have the same problem since the variadic methods can be called with an array (not sure if the compiler copies the array automatically),  may be good to verify that as well.

**Comment by jkwatson** [comment]
There is no secret array-copying when you call a varargs method directly with an array. It just passes it directly to the method.

**Comment by bogdandrutu** [comment]
@jkwatson which means the current labels API suffer from the same problem :(

**Comment by jkwatson** [comment]
It's true. Definitely something to fix.

**Comment by jkwatson** [comment]
Note: I chatted with @trask this morning in the auto-instrumentation meeting, and he mentioned that the auto-instrumentation project never uses any of the methods that take Maps directly. So, maybe we should start by removing the maps from the public API, and figure out an internal, immutable representation as a separate effort.

**Comment by bogdandrutu** [comment]
We discussed this last week, there are other APIs that use map and we cannot completely get rid of all

**Comment by jkwatson** [comment]
This was completed in the 0.6.0 release with the introduction of the Attributes & Labels classes.
