### ISSUE TITLE
Jaeger exporter should not depend on opentelemetry-proto

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1279]
Snip from `./gradlew :opentelemetry-exporters-jaeger:dependencies`:

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- project :opentelemetry-sdk-contrib-otproto
|    +--- project :opentelemetry-proto
```

I think the jaeger exporter should not have this dependency.

The problem seems to be that it actually uses functions defined in sdk-contrib-otproto:
https://github.com/open-telemetry/opentelemetry-java/blob/192137e7759a6aec6c4e17bf378ba6a535463dd5/exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java#L72-L73 namely the `TraceProtoUtils` class. Maybe that class could be moved to some generic protobuf-based-sdk-util, or a function returning a byte array could be added to the API's spancontext, as that could also be passed to protobuf instead of a ByteString.

**Comment by jkwatson** [comment]
closing, as this dependency has been cleaned up.
