### ISSUE TITLE
Add the ability to specify a Span Kind using the WithSpan annotation

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1303]
**Describe the solution you'd like**
Add an optional parameter to the `WithSpan` annotation that specifies the span Kind to create.

**Describe alternatives you've considered**
Doing this manually is possible, but it would be nice to have it built in to the annotation.

**Comment by bogdandrutu** [comment]
I think we agreed on this. Somebody needs to implement it.

**Comment by jkwatson** [comment]
I'll grab it from the API side, and the hand it off to the instrumentation team to make it actually work.
