### ISSUE TITLE
Collector Not collecting metrics if the collection interval is less that the metric generation interval

### ISSUE THREAD

**Issue by godev-learner** [open-telemetry/opentelemetry-java#1313]
**Describe the bug**
I am using the method setExportIntervalMillis to set the collector interval to 2500 ms ans generating metrics at the rate like 4000ms,
although initially the collector will not receive any metrics but on the 2nd attemps means on 5000ms it should pickup some metrics, but that is not happening 

**Steps to reproduce**
Set the setExportIntervalMillis to the value less than the time you are generating the metrics. 

**What did you expect to see?**
should collect the metrics

**What did you see instead?**
No metrics getting collected

**What version and what artifacts are you using?**

Artifacts: opentelemetry-java-sdk, io.opentelemetry.sdk.metrics.export.MetricExporter
Version: latest one
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)
build.gradle

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: macos Mojave
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by godev-learner** [comment]
Any update on this

**Comment by jkwatson** [comment]
Hi @godev-learner . I don't think anyone has had a chance to take a look at this. Do you have a simple code example of this happening you could provide? 

Thanks!

**Comment by godev-learner** [comment]
@jkwatson Thanks for the response you can take a look at the below 
Below is the code I am setting the interval for the reader

` MetricExporter metricExporter =
                OtlpGrpcMetricExporter.newBuilder()
                        .setChannel(ManagedChannelBuilder.forTarget(otlpEndpoint).usePlaintext().build())
                        .build();

        // 2. setup metric collection interval
        IntervalMetricReader intervalMetricReader =
                IntervalMetricReader.builder()
                        .setMetricProducers(
                                Collections.singleton(OpenTelemetrySdk.getMeterProvider().getMetricProducer()))
                        .setExportIntervalMillis(1500)
                        .setMetricExporter(metricExporter)
                        .build();`

and below code I am  generating metrics
`private static void doSomeSimulatedWork(
            LongCounter spanCounter,
            LongMeasure.BoundLongMeasure boundTimer)
            throws InterruptedException {
        Random random = new Random();
        for (int i = 0;; i++) {
            long startTime = System.currentTimeMillis();
            boolean markAsError = random.nextBoolean();
            System.out.println("sending metric data: " + i);
            spanCounter.add(1, "spanName", "testSpan", "isItAnError", "" + markAsError);
            // do some work
            Thread.sleep(2000);
            boundTimer.record(System.currentTimeMillis() - startTime);
        }
    }`

here you can see I am generating metrics every 2 second and collecting metrics after 1.5 second, although I understand at first second there will be no metrics present but on second attempt, the collector should be able to collect some metrics.

**Comment by jkwatson** [comment]
I'll try to take a look at this as soon as possible. Just out of curiosity, if you use the logging exporter, rather than the collector, do you see the same behavior?

**Comment by godev-learner** [comment]
yes I do see the same behaviour for the logging exporter as well.

**Comment by jkwatson** [comment]
> yes I do see the same behaviour for the logging exporter as well.

Excellent. That will make it much simpler to reproduce. We also need to create an "In Memory" metric exporter that we can use to do unit testing for this, I think.

**Comment by godev-learner** [comment]
ok, let me know if you need anything from my side.I was trying to see if there is trigger that will flush the channel, but I am not able to find any. let me know if you find anything.

**Comment by jkwatson** [comment]
@godev-learner I tried to reproduce this with the code here:  https://gist.github.com/jkwatson/de3e333fd9094581c33f1590201da8bd

Everything worked fine for me. Can you try updating to 0.5.0 and see if this code works for you?

**Comment by godev-learner** [comment]
I tried using the 0.5.0 but same thing I am still not able to get it working, I am using to below code for collector
https://github.com/mxiamxia/opentelemetry-collector-contrib/tree/emf_exporter/exporter/awsemfexporter
and below for metrics generation
https://github.com/mxiamxia/aws-cloudwatch-opentelemetry-sample/blob/master/generator/src/main/java/com/amazon/cloudwatch/otel/metrics/MetricGenerator.java

**Comment by jkwatson** [comment]
Did you try running my code to verify it works correctly?

**Comment by godev-learner** [comment]
No even your code doesn't work in my setup.

**Comment by godev-learner** [comment]
Made some simple changes in your code and after that I tested it and it seems it also doesn't work below is the modified code, I have only created a object of OtlpGrpcMetricExporter instaed of TestExporter()
`
public class BugReproTest {
    private static final String OTLP_ENDPOINT = "otlp.endpoint";
    private static String otlpEndpoint = "127.0.0.1:55680";
    private BugReproTest() {}
    public static void main(String[] args) throws InterruptedException {

        MetricExporter metricExporter =
                OtlpGrpcMetricExporter.newBuilder()
                        .setChannel(ManagedChannelBuilder.forTarget(otlpEndpoint).usePlaintext().build())
                        .build();

        MeterSdkProvider meterSdkProvider = MeterSdkProvider.builder().build();

        IntervalMetricReader intervalMetricReader =
                IntervalMetricReader.builder()
                        .setMetricProducers(Collections.singleton(meterSdkProvider.getMetricProducer()))
                        .setMetricExporter(metricExporter)
                        .setExportIntervalMillis(1500)
                        .build();

        Meter foo = meterSdkProvider.get("testing");

        LongValueRecorder timer = foo.longValueRecorderBuilder("recorder").build();
        doSomeSimulatedWork(foo.longCounterBuilder("counter").build(), timer.bind("key", "value"));

        intervalMetricReader.shutdown();
    }

    private static void doSomeSimulatedWork(LongCounter spanCounter,
                                            LongValueRecorder.BoundLongValueRecorder boundTimer) throws InterruptedException {
        Random random = new Random();
        int i = 0;
        while (true) {
            long startTime = System.currentTimeMillis();
            boolean markAsError = random.nextBoolean();
            System.out.println("sending metric data: " + i);
            spanCounter.add(1, "spanName", "testSpan", "isItAnError", "" + markAsError);
            // do some work
            Thread.sleep(2000);
            boundTimer.record(System.currentTimeMillis() - startTime);
            i++;
        }
    }

}
`

**Comment by jkwatson** [comment]
Hang on, before we get to the OLTP exporter...  If you run my example, as is, with the TestExporter, do you see metrics showing up? If you don't, then there's something fundamental going wrong that we need to figure out. Can you provide more details about how you're building, running, etc?

**Comment by godev-learner** [comment]
yes I am able to run your example if I just use the TestExporter.

**Comment by godev-learner** [comment]
For testing your class I am just running the  java program you have provided me nothing special.

**Comment by jkwatson** [comment]
Next step: If you run my example with the LoggingExporter (rather than OLTP), does that work?

**Comment by godev-learner** [comment]
> Next step: If you run my example with the LoggingExporter (rather than OLTP), does that work?

sorry I missed I checked again and it seems that your class is also not working as expected in my environment

**Comment by godev-learner** [comment]
ok let me check

**Comment by jkwatson** [comment]
oh no! So, we need to know more about your environment then, since this works fine when I run locally from my IDE.

**Comment by godev-learner** [comment]
> oh no! So, we need to know more about your environment then, since this works fine when I run locally from my IDE.

no thats ok, my mistake I was 2 programs your test is running fine in my env, I confirmed Thats why I deleted the comment

**Comment by godev-learner** [comment]
> Next step: If you run my example with the LoggingExporter (rather than OLTP), does that work?

I will check on this step.

**Comment by godev-learner** [comment]
I check with the Logging exporter and it seems to be working as you can see below

```
sending metric data: 0
Jun 08, 2020 7:30:10 PM io.opentelemetry.exporters.logging.LoggingMetricExporter export
INFO: Received a collection of 2 metrics for export.
Jun 08, 2020 7:30:10 PM io.opentelemetry.exporters.logging.LoggingMetricExporter export
INFO: metric: MetricData{descriptor=Descriptor{name=recorder, description=, unit=1, type=SUMMARY, constantLabels={}}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=testing, version=null}, points=[null]}
Jun 08, 2020 7:30:10 PM io.opentelemetry.exporters.logging.LoggingMetricExporter export
INFO: metric: MetricData{descriptor=Descriptor{name=counter, description=, unit=1, type=MONOTONIC_LONG, constantLabels={}}, resource=Resource{attributes={}}, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=testing, version=null}, points=[LongPoint{startEpochNanos=1591669808743000000, epochNanos=1591669810200000000, labels={isItAnError=false, spanName=testSpan}, value=1}]}
sending metric data: 1
```

**Comment by jkwatson** [comment]
ok. good news, then. We've isolated the issue to either the OLTP exporter, or the collector itself. My suspicion is that it's the collector, since the OLTP exporter is pretty simple. I'll take a look tomorrow and see if I can locally add some debugging to the exporter and see what's up.

**Comment by godev-learner** [comment]
ok sure thanks.

**Comment by godev-learner** [comment]
@jkwatson  did you get the chance to check on this

**Comment by jkwatson** [comment]
I'm just picking this up (sorry...it's been a busy morning). How are you running the collector?

**Comment by godev-learner** [comment]
same in my intellij. just as it is a go program we have provide some argument like below
args": ["--config=${fileDirname}/../aws-otel.yaml"]

**Comment by jkwatson** [comment]
I've found a bug... the exporter is being given a `null` Point in one of the metrics on the first collection cycle, causing it to blow up and the backing thread to die. Thanks for this report, and providing the detailed case to help reproduce. 

Note: I think the bug is actually in the metric system itself, rather than the exporter, but the exporter should also be a bit more robust to this sort of data condition.

**Comment by jkwatson** [comment]
See 
https://github.com/open-telemetry/opentelemetry-java/issues/1324 
and 
https://github.com/open-telemetry/opentelemetry-java/issues/1326
for 2 bugs I logged around this. Again, thanks for the report!

**Comment by godev-learner** [comment]
Thanks @jkwatson for creating the tickets.
