### ISSUE TITLE
Accessors for Span fields such as kind

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1315]
**Is your feature request related to a problem? Please describe.**

`SpanBuilder` has mutators for aspects like `kind`, but `Span` does not provide accessors. This makes writing unit tests for instrumentations fragile. For example, I have a helper method to create client spans but can't write a unit test verifying the span is the correct kind.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/460/files#diff-6656f9ba344194f8676cac4a2e1f4048R58

**Describe the solution you'd like**

Add accessors for `Span` fields to allow writing unit tests.

**Describe alternatives you've considered**

Mocking `Tracer` and `SpanBuilder` and verifying the methods ran could work, but makes the tests much more tedious / verbose just to check the type of the span.

**Comment by bogdandrutu** [comment]
`Span` must be write only with the exception of spancontext. The reason is that the interface should allow implementation that buffer events and send them when the Span ends, or implementations that stream individual events. For testing you can use our SDK + the testing contrib artifact.

**Comment by anuraaga** [comment]
Not finding the testing artifact, but assuming I find it, I still wonder if that needs to apply to everything and not just to the mutable fields. `kind` is set when creating the span, similar to spancontext, so doesn't that mean it makes sense to expose it? Don't think there's any buffer involved.

**Comment by carlosalberto** [comment]
@anuraaga This is the code: https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/inmemory/src/main/java/io/opentelemetry/exporters/inmemory/InMemoryTracing.java (part of the `inmemory` artifact).

There was also the mention of having a stream-based API, which would be sending the values over the wire always, not keeping them around. In that case, simply exposing/returning `kind` (and other values) wouldn't work.

**Comment by malafeev** [comment]
shouldn't be added `getKind()` to `ReadableSpan` interface?
what's the decision on the issue?

**Comment by jkwatson** [comment]
I'm fine with adding accessors for immutable data to the `ReadableSpan`, since that's an SDK class, not an API class.

**Comment by jkwatson** [comment]
@anuraaga are you ok downgrading this to after-ga, or is this critical to be done before ga?

**Comment by anuraaga** [comment]
After GA is fine by me :)

**Comment by jkwatson** [comment]
@anuraaga are there additional fields you think we should open up, or can we close this now that the `kind` is exposed?

**Comment by anuraaga** [comment]
Seems good if something comes up we'll think about it again
