### ISSUE TITLE
Releases section in readme is outdated

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#1320]
The handcrafted releases section, prominently placed in the README, is outdated:
https://github.com/open-telemetry/opentelemetry-java#releases

> The latest version of the libraries were released on March 27th, 2020. See the v0.3.0 alpha release.

It still lists 0.3.0 as the most recent one and claims spec compatibility with 0.3.0.
Can we just replace everything with 0.5.0 or are there any spec 0.4/0.5 features/updates yet to be implemented?

**Comment by DotSpy** [comment]
Is there any way to automate it? We have a lot of versions in the README that should be updated, not only https://github.com/open-telemetry/opentelemetry-java#releases but also https://github.com/open-telemetry/opentelemetry-java#releases , https://github.com/open-telemetry/opentelemetry-java#releases and etc

**Comment by arminru** [comment]
> Is there any way to automate it? We have a lot of versions in the README that should be updated, not only [open-telemetry/opentelemetry-java#releases](https://github.com/open-telemetry/opentelemetry-java#releases) but also [open-telemetry/opentelemetry-java#releases](https://github.com/open-telemetry/opentelemetry-java#releases) , [open-telemetry/opentelemetry-java#releases](https://github.com/open-telemetry/opentelemetry-java#releases) and etc

@DotSpy isn't that three times the same link? 😅

**Comment by DotSpy** [comment]
@arminru yeah sorry actual ones https://github.com/open-telemetry/opentelemetry-java#gradle https://github.com/open-telemetry/opentelemetry-java#maven

**Comment by jkwatson** [comment]
Proposals on automating this would be very welcome!

**Comment by jkwatson** [comment]
I think this is up-to-date. I'm going to move this issue to after-ga to track is we want to try to build some kind of automation for it.
