### ISSUE TITLE
Implement the metric BatchObserver from the spec

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1331]
See here:  https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#batch-observer

**Comment by Oberon00** [comment]
What is the status of this? I guess we are blocked on https://github.com/open-telemetry/opentelemetry-specification/issues/1090 which in turn is maybe blocked by https://github.com/open-telemetry/opentelemetry-specification/pull/1159?

**Comment by jkwatson** [comment]
Yeah... I really need to find some time to work on metrics API definition for this. If someone else could pick that up, that would be great!
