### ISSUE TITLE
Add name to SpanExporterFactory

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1332]
**Is your feature request related to a problem? Please describe.**
open-telemetry/opentelemetry-java-instrumentation#491 raised a problem of configuring which exporter should instrumentation agent use, when agent's jar contains several embedded collectors. There is no robust way atm to identify or distinguish different implementations of `SpanExporterFactory`.

**Describe the solution you'd like**
Add a new method to `SpanExporterFactory` (and probably to `MetricExporterFactory` as well) interface called `getName()` or `getId()`. This method should return non-null string uniquely identifying the implementation of span exporter. This name/id can later be used for choosing implementation to use.

**Comment by jkwatson** [comment]
Seems reasonable. Are you interested in contributing a quick PR for it?

**Comment by iNikem** [comment]
What name do you prefer? I can add it, sure.

**Comment by jkwatson** [comment]
I think "getName()" is good, especially if the javadoc on it is clear as to what it's going to be used for.

**Comment by anuraaga** [comment]
Isn't it quite normal to use the fully qualified class name when selecting an SPI implementation? SDK currently uses the approach too. It's guaranteed to be unique based on the nature of a Java classpath, while a name provided by a method has chances of collision which seems like something we don't want to deal with.

Having a hard-coded mapping from a short name to the fully qualified name for well-known implementations in the agent like otlp, logging, jaeger and zipkin seems like it could also provide the simpler UX without the risk of conflicting names from random exporters on the classpath.

**Comment by iNikem** [comment]
Hm, @anuraaga does have a good point :) @trask what do you think about it?

**Comment by trask** [comment]
this makes sense to me. it doesn't solve our immediate problem which is that we have no auto-instrumentation tests for `otlp`, `jaeger` or `zipkin` exporters, and so our reliance on the class name is fragile, but probably we should just fix that 👍

**Comment by iNikem** [comment]
Closing this issue in favour of open-telemetry/opentelemetry-java-instrumentation#511
