### ISSUE TITLE
Can CorrelationContext EntryKey/EntryValue be just Strings?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1334]
The `String` values could still be validated on creation of the `Entry`.

These extra wrapper objects (`EntryKey` and `EntryValue`) create extra work for the auto-instrumentation bridge.

Also related to #1314

**Comment by jkwatson** [comment]
@carlosalberto any reason these can't be made into plain strings, as @trask suggests?

**Comment by carlosalberto** [comment]
I don't remember any reason on why we _can't_ do this - overall sounds like a good idea to play with, although I wonder how could 

```java
public interface CorrelationContext {
  Collection<Entry> getEntries();
```

be exposed without `Entry` objects. As this class is *expected* to be used publicly mostly to set values (and not get them), perhaps we can use the same approach used by the newly added `Attributes` class. Any opinion on this @bogdandrutu ?

**Comment by jkwatson** [comment]
@carlosalberto : I think the suggestion is to keep the `Entry`, but get rid of the extra key and value wrappers.

**Comment by bogdandrutu** [comment]
The reason on having Key as a class was to include maybe other metadata in the future. I think we don't have that many apis using the Key so even if that is the case we can have overloads.

Entry has key, value and TTL (if that is still defined)

**Comment by jkwatson** [comment]
If we want this, I've got the PR submitted: #1363
