### ISSUE TITLE
Allow users to specify options other than ManagedChannel for exporters

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#1361]
A few exporters (OTLP, Jaeger) take a gRPC `ManagedChannel` as input, which means that if the user wants to add `Metadata` (or set related values), they have to actually write Interceptors. Wondering if we should simplify this - for reference, the gRPC Python API (and thus the OTLP Python exporter) allows to send `Metadata` in a simple way (it can be specified when a remote request is performed).

Opinions @bogdandrutu @pavolloffay ?

**Comment by malafeev** [comment]
implemented for OTLP exporter: https://github.com/open-telemetry/opentelemetry-java/pull/1373

**Comment by jack-berg** [comment]
This is done, generally. If there's a desire for additional new methods on the exporters we can open new issues.
