### ISSUE TITLE
TraceFlags API should match SpanId, TraceId

### ISSUE THREAD

**Issue by ivangreene** [open-telemetry/opentelemetry-java#1367]
**Is your feature request related to a problem? Please describe.**
TraceFlags.java has a public factory method accepting a single byte, and a method to obtain the single byte. I feel the API should match SpanId and TraceId so that user-code does not have to change as much to accommodate a future version that stores more data in TraceFlags.

**Describe the solution you'd like**
TraceFlags.java should have a `public static TraceFlags fromBytes(byte[] src, int srcOffset);` method to match TraceId/SpanId, the `fromByte(byte src)` factory should be made private or deprecated, and the `getByte()` method should be deprecated or removed.

**Describe alternatives you've considered**
Can't really think of any alternatives. This is a non-issue if we never plan to expand the flags of TraceFlags, but I think it will be a mostly harmless move anyway.

**Comment by jkwatson** [comment]
This seems reasonable to me, especially since we already  have the `copyBytesTo(byte[] dest, int destOffset)` method to do the reverse.

**Comment by jkwatson** [comment]
Now that we've merged all 3 of TraceFlags, SpanId and TraceId into the SpanContext, I think this might be redundant at this point. @ivangreene can we close this?

**Comment by ivangreene** [comment]
@jkwatson yep, looks like this would be a different issue at this point because of the change there
