### ISSUE TITLE
Exporting MetricData from selected instruments?

### ISSUE THREAD

**Issue by tobbaumgartner** [open-telemetry/opentelemetry-java#1370]
Is there a way to export `MetricData` only from selected instruments?
Currently, I receive the `MetricData` by `OpenTelemetrySdk.getMeterProvider().getMetricProducer().getAllMetrics()` as I didn't find another way to do so.
I'm trying to implement an event-based approach (in contrast to the periodically fetching `IntervalMetricReader`) and it would be nice to only export `MetricData` related to the event. 
The same problem applies to the `IntervalMetricReader`, where `.setMetricProducers(OpenTelemetrySdk.getMeterProvider().getMetricProducer())` exports data from all instruments.

**Comment by jkwatson** [comment]
How would you want to specify the metrics that you wanted? Could you just write a filter in your exporter that discarded the metrics you didn't care about?

**Comment by tobbaumgartner** [comment]
The only possible way would be the instrument name or grouping multiple instruments together (similar to the `BatchRecorder`)
But yeah you're right, filtering in the exporter would work too. I just thought there may be some SDK-internal way planned to do that.

**Comment by jkwatson** [comment]
We haven't had any plans to add that, but a contribution of a filtering exporter in sdk_extensions that could be extended from would be a fine addition.

**Comment by jack-berg** [comment]
Closing because views are the correct way to accomplish this.
