### ISSUE TITLE
Installed span exporter, log appears twice in logs

### ISSUE THREAD

**Issue by Tausif28** [open-telemetry/opentelemetry-java#1375]
**Describe the bug**
Hi, i was trying to use OpenTelemetry using Java auto Instrumentation for a simple java project, i followed the instructions on the github page: https://github.com/open-telemetry/opentelemetry-java-instrumentation ,
I am using the logging exporter, i see these 4 lines at he start:

```
[opentelemetry.auto.trace 2020-06-26 10:44:01:020 +0530] [main] INFO io.opentelemetry.auto.tooling.TracerInstaller - Installed span exporter: io.opentelemetry.auto.exporters.logging.LoggingExporter
[opentelemetry.auto.trace 2020-06-26 10:44:01:036 +0530] [main] INFO io.opentelemetry.auto.tooling.VersionLogger - opentelemetry-auto - version: 0.4.0~dbb639a56
[opentelemetry.auto.trace 2020-06-26 10:44:01:052 +0530] [main] INFO io.opentelemetry.auto.tooling.TracerInstaller - Installed span exporter: io.opentelemetry.auto.exporters.logging.LoggingExporter
[opentelemetry.auto.trace 2020-06-26 10:44:01:052 +0530] [main] INFO io.opentelemetry.auto.tooling.VersionLogger - opentelemetry-auto - version: 0.4.0~dbb639a56
```

then i see the last line from OpenTelemetry as this :
```
[opentelemetry.auto.trace 2020-06-26 10:44:04:532 +0530] [opentelemetry-exec-shutdown-hook] WARN io.opentelemetry.auto.common.exec.CommonTaskExecutor - Periodic task scheduler is shutdown. Will not run: cleaner for com.blogspot.mydailyjava.weaklockfree.WeakConcurrentMap@52a9f8cf
```

**The first 2 log lines are repeating, and it does not capture the Jedis call trace**
My program is a simple PSVM with a few calls to redis DB using Jedis, adn few other method calls. This is what i pass to my VM options :

> -javaagent:F:/Experiments/opentelemetry-auto-all.jar
> -Dota.exporter=logging

I don't use the api or the sdk.

**Steps to reproduce**
Create a simple PSVM java application and use the java agent with logging exporter

**What did you expect to see?**
A trace of method calls inside my java application

**What did you see instead?**
I saw the start and end of the OpenTelemetry logs and no traces.

**What version and what artifacts are you using?**
Artifacts:  opentelemetry-auto-all.jar version : 0.4.0~dbb639a56

**Environment**
Compiler: JRE1.8.0_201x64
OS: Windows 10 Enterprise 64-bit
[logs - OpenTelemetry.txt](https://github.com/open-telemetry/opentelemetry-java/files/4835510/logs.-.OpenTelemetry.txt)

**Comment by carlosalberto** [comment]
Hey @Tausif28 !

I think this is actually related to the instrumentation repo (https://github.com/open-telemetry/opentelemetry-java-instrumentation) so would you mind opening a bug there? (the bug itself might end up being in the API/SDK, but it might be in how components are configured for the instrumentation engine).

**Comment by jkwatson** [comment]
@Tausif28 can we close this here?

**Comment by Tausif28** [comment]
@jkwatson Closing this issue, will report it in the opentelemetry java instrumentation repo.
