### ISSUE TITLE
Consider reverting https://github.com/open-telemetry/opentelemetry-java/pull/1363

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1377]
The main motivation I explained in February in a SIG meeting is that systems can use a global registry for the Keys (at least) and replace the string with just an int ID for performance reasons like encoding on the wire.

See https://github.com/open-telemetry/opentelemetry-specification/issues/442

**Comment by jkwatson** [comment]
Could we use the `CharSequence` interface, rather than String so that people who wanted to have an alternative implementation could do that, instead?

**Comment by bogdandrutu** [comment]
That does not enforce that all the instances are created by the SDK. What we need is to make sure all instrumentation creates the key using the SDK so the SDK can inject a different implementation

**Comment by anuraaga** [comment]
Would users of the SDK generally still use `String`, presumably looked up from the global registry? I think we'll generally end up with a simpler API if it follows user expectations, not implementation details like the wire format, and I'd say the wrapper objects don't provide much value to users. Serialization can be handled by a different configurable layer, like `CorrelationContextEncoder` or similar, right?

**Comment by jkwatson** [comment]
I don't understand the use case for the SDK injecting a different implementation. Can you provide a concrete example?

**Comment by jkwatson** [comment]
Changing to after-ga to match the corresponding spec issue.

**Comment by jkwatson** [comment]
closing this for now. If the spec gets updated to include Entry and EntryKey, we will certainly add them then.
