### ISSUE TITLE
Can we stop generating span and trace ids for no-op spans with no parent context?

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1385]
We can save 3-5 allocations per no-op span if we can just return an invalid span from the no-op tracer when there is no parent context.

The behavior of generating random trace and span ids was introduced here:  #382 and references this issue: #392 . There is reference to a decision being made to return valid span ids in this case, but no reasoning provided in the issue or the PR as to why.

A note: if we change the behavior to return an Invalid span in this case, no tests fail in the entire project. This leads me to believe that this behavior is not required, but a vestige of an earlier context design which has been obviated by later context rework.

I also don't find any requirements for this behavior in the tracing specs.

If this is necessary for some reason, then we should definitely document it in the code so our future selves will fully understand the rationale.

**Comment by jkwatson** [comment]
The more I look at this, I think this behavior is actually harmful. The current behavior means that a service that has no SDK installed, but a propagator configured, will propagate trace ids and span ids that will never be reported anywhere, leading to what looks like phantom trace parents in all downstream services.

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev I think you requested this

**Comment by bogdandrutu** [comment]
Also @jkwatson it will be good at least to propagate what we receive at least.

**Comment by jkwatson** [comment]
Propagating what we receive isn't the issue. It's generating new trace/spanids when there is no incoming context and no SDK installed.
