### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by adriancole** [open-telemetry/opentelemetry-java#1392]
**Describe the bug**
0.5 and 0.6 so far have no release notes. and the README is out of date also about releases

**Steps to reproduce**
Look at the release and there are no notes

**What did you expect to see?**
A list of enhancements, bug fixes and breaking changes

**What did you see instead?**
nothing

**What version and what artifacts are you using?**
0.6.0 0.5.0 tags for example

**Comment by adriancole** [comment]
context: people like me click watch releases only. this is pointless when release notes are missing as we have to look at git compare range and run jdiff manually

**Comment by jkwatson** [comment]
yep. I'm aware. This will be being done ASAP

**Comment by jkwatson** [comment]
Release notes have been updated, and a PR created to update the docs. Thanks for pointing this out!

**Comment by adriancole** [comment]
great turnaround thanks john!
