### ISSUE TITLE
Document usage of the OpenTracing Shim

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1396]
The README in the module should have a how-to usage section in it.

**Comment by iNikem** [comment]
@carlosalberto will this how-to be essentially as in https://lightstep.com/blog/opentracing-vs-opentelemetry-building-a-bridge-with-opentelemetry/ ? Or there is another recommended way to use this shim nowadays?

**Comment by carlosalberto** [comment]
Very similar. We just need to put something like that in the README (along probably a few cases, like registering the Tracer in the OpenTracing Global Tracer).
