### ISSUE TITLE
Location for design docs, proposals, etc (maybe even meeting notes)

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1397]
In #1380 I noticed there is an otel design doc in a private Google Doc. I see two problems

- Private. We need to make sure discussion about an open project is open

- Google Doc. From what I understand it's not as available as GitHub, notably it doesn't work in China? Even if it does it is very hard to curate docs into a single location and will disappear if the author happens to delete it / lose their account, etc

I think we should provide a place for these sort of docs on GitHub. It ensures the doc isn't lost to posterity - I don't think there is a reason for doc drafting to be forced to GitHub if a different Doc tool has better UX for that but we should copy it into GitHub when first draft is finalized. This will allow us to have one location to find all docs to look for background or just for fun.

We have oteps for spec extensions but I don't think it's meant for language specific designs which are important too. Any thoughts on

- open-telemetry/opentelemetry-java/docs (current repo, docs subfolder to keep design docs for posterity)
- open-telemetry/opentelemetry-java-docs (java-specific docs repo)
- open-telemetry/docs/java (docs repo that can have language, or whatever, subfolders)
- open-telemetry/oteps/sdks/java - extend scope of oteps to language sdks

**Comment by carlosalberto** [comment]
Let's put everything under open-telemetry/opentelemetry-java/docs.

I think the plan is to have, upon consolidating the zPages effort, consolidate its design documents as well in a markup file. In any case, it's good to have an issue, so we don't forget about the overall need for docs.

**Comment by jkwatson** [comment]
@anuraaga can we close this?

**Comment by anuraaga** [comment]
Maybe there isn't but I figured there must be some related docs already so figured copying those into the desired location would be the step that closes this. One thing that comes to mind is the context discussion.

But if there aren't any docs than just closing is fine too :)

**Comment by jkwatson** [comment]
Looks like we've now got docs in the `docs` directory (as of #1455), so I'm guessing this can be closed. Please re-open if you think there is something more needed.
