### ISSUE TITLE
Inability to create span and set active span in gRPC interceptor

### ISSUE THREAD

**Issue by luka223** [open-telemetry/opentelemetry-java#1398]
I want to create span in gRPC interceptor (using io.grpc) and continue trace from remote service. I used onMessage and onHalfClose events. Here is the code snippet I used:

```
@Override
    public void onMessage(ReqT message) {
      . . .
      // traceId and spanId are received from remote service
      SpanContext parentContext =
          SpanContext.createFromRemoteParent(
              TraceId.fromLowerBase16(traceId, 0),
              SpanId.fromLowerBase16(spanId, 0),
              TraceFlags.builder().setIsSampled(false).build(),
              TraceState.builder().build());

      Span span =
          this.tracer
              .spanBuilder("taas_grpc_api")
              .setParent(parentContext)
              .setSpanKind(Span.Kind.SERVER)
              .startSpan();

      span.setAttribute("messageType", message.getClass().getName());
      this.tracer.withSpan(span);
}

@Override
    public void onHalfClose() {
      try {
        super.onHalfClose();
      } finally {
        this.tracer.getCurrentSpan().end();
      }
    }
```

But as soon as onMessage method is finished, following exception is thrown:
ERROR io.grpc.ThreadLocalContextStorage - Context was not attached when detaching.

When I create span in gRPC service class itself, then tracing is working as expected, but I want to do it in interceptors so it can be reused on multiple services.
Is this possible to do it in interceptors?

**Comment by carlosalberto** [comment]
This might be of help/reference: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/grpc-1.5/src/main/java/io/opentelemetry/auto/instrumentation/grpc/client/TracingClientInterceptor.java

**Comment by jkwatson** [comment]
@luka223 when you call `tracer.withSpan(span)`, the returned `Scope` object is actually very important. It *must* be closed or the span will never be removed from being the active one in the context.

**Comment by luka223** [comment]
> @luka223 when you call `tracer.withSpan(span)`, the returned `Scope` object is actually very important. It _must_ be closed or the span will never be removed from being the active one in the context.

Even with closing the `Scope` the issue persists.

> This might be of help/reference: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/grpc-1.5/src/main/java/io/opentelemetry/auto/instrumentation/grpc/client/TracingClientInterceptor.java

That reference was really helpful, even though I looked at `TracingServerInterceptor` if anyone comes accross this issue.

But it not solved my problem completely. Tracing now works, but remote traceId and spanId must be sent through metadata.
In my implementation, those ids are sent in message body which I have access in `onMessage` method, but I have to start span in `interceptCall` method where I don't have access to the sent message.
Is there any workaround for this?

**Comment by jkwatson** [comment]
> > @luka223 when you call `tracer.withSpan(span)`, the returned `Scope` object is actually very important. It _must_ be closed or the span will never be removed from being the active one in the context.
> 
> Even with closing the `Scope` the issue persists.
 
You still get the error, even with closing the scope appropriately?

**Comment by luka223** [comment]
@jkwatson Yes, my idea was to open the scope in `onMessage` method and then close it in `onCompleted`. But I don't think the problem is closing the scope, as the excepiton is thrown immediately after completing `onMessage`. At that time scope shouldn't be closed.

**Comment by jkwatson** [comment]
Can you share more complete example code that demonstrates this? I'm very interested in what's going on here.

**Comment by luka223** [comment]
Of course, here is the last snippet I tried to make it work:

```
public class TracingContextInterceptor implements ServerInterceptor {
  private final Logger logger;
  private final Tracer tracer;

  public TracingContextInterceptor(Logger logger, Tracer tracer) {
    this.logger = logger;
    this.tracer = tracer;
  }

  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
      ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
    ServerCall.Listener<ReqT> listener = next.startCall(call, headers);
    return new TracingContextServerCallListener<>(this.logger, this.tracer, listener);
  }

  protected static class TracingContextServerCallListener<ReqT>
      extends ForwardingServerCallListener.SimpleForwardingServerCallListener<ReqT> {
    private final Tracer tracer;
    private final Logger logger;

    private static final ThreadLocal<Scope> contextHolder = new NamedThreadLocal<>("Scope");

    protected TracingContextServerCallListener(
        Logger logger, Tracer tracer, ServerCall.Listener<ReqT> listener) {
      super(listener);
      this.logger = logger;
      this.tracer = tracer;
    }
   
    @Override
    public void onMessage(ReqT message) {
      String spanId = "";
      String traceId = "";

      if (message instanceof ExampleService.Message) {
        ExampleService.Message exampleMessage = (ExampleService.Message) message;
        spanId = exampleMessage.getSpanId();
        traceId = exampleMessage.getTraceId();
      } else {
        this.logger.warn("Unknown message type, trace-id is not extracted");
      }

      SpanContext parentContext =
          SpanContext.createFromRemoteParent(
              TraceId.fromLowerBase16(traceId, 0),
              SpanId.fromLowerBase16(spanId, 0),
              TraceFlags.builder().setIsSampled(false).build(),
              TraceState.builder().build());

      Span span =
          this.tracer
              .spanBuilder("example_grpc_api")
              .setParent(parentContext)
              .setSpanKind(Span.Kind.SERVER)
              .startSpan();

      span.setAttribute("messageType", message.getClass().getName());

      Scope scope = this.tracer.withSpan(span);
      contextHolder.set(scope);

      super.onMessage(message);
    }

    @Override
    public void onHalfClose() {
      try {
        super.onHalfClose();
      } catch (Exception e) {
        this.tracer.getCurrentSpan().end();
        contextHolder.get().close();
      }
    }

    @Override
    public void onCancel() {
      try {
        super.onCancel();
      } finally {
        this.tracer.getCurrentSpan().end();
        contextHolder.get().close();
      }
    }
  }
}
```

**Comment by jkwatson** [comment]
@luka223 You need to end the span and close the context in a `finally` block in the `onHalfClose()` method, not in a catch block. When I made this change, it worked for me locally.

**Comment by luka223** [comment]
@jkwatson You are right, my mistake there, but unfortunately that doesn't solve my problem. I got the same error even with this change. As I mentioned, error happens immediately after `onMessage` method is finished, `onHalfClose` method will be executed after that, when exception is already thrown.

**Comment by anuraaga** [comment]
Hi @luka223 - our official instrumentation includes an interceptor, can you compare with your pattern?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/grpc-1.5/src/main/java/io/opentelemetry/auto/instrumentation/grpc/server/TracingServerInterceptor.java

**Comment by luka223** [comment]
Hi @anuraaga, I already saw the instrumentation which is working as it should, but as I already mentioned, with this implementation I have to read traceId and spanId in `interceptCall` method where I don't have access to message object. I need message object as in my implementation traceId and spanId are sent in message body, instead of metadata.

**Comment by anuraaga** [comment]
Sorry, I didn't scroll enough, that link was indeed redundant >< But the pattern is indeed what to follow.

The span is what matters really, scope is literally to model a block of execution of logic but has no other real meaning. So I think you want your listener to have a (initially null) span field, not a scope threadlocal.

Note, I haven't tried this but hopefully it provides some pointer - note saving Span as a field, not Scope, also ThreadLocal doesn't help here since multiple calls can be interpolated on the same thread state has to be stored in the call itself.

```java
public class TracingContextInterceptor implements ServerInterceptor {
  private final Logger logger;
  private final Tracer tracer;

  public TracingContextInterceptor(Logger logger, Tracer tracer) {
    this.logger = logger;
    this.tracer = tracer;
  }

  @Override
  public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
      ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
    ServerCall.Listener<ReqT> listener = next.startCall(call, headers);
    return new TracingContextServerCallListener<>(this.logger, this.tracer, listener);
  }

  protected static class TracingContextServerCallListener<ReqT>
      extends ForwardingServerCallListener.SimpleForwardingServerCallListener<ReqT> {
    private final Tracer tracer;
    private final Logger logger;

    private volatile Span span;

    protected TracingContextServerCallListener(
        Logger logger, Tracer tracer, ServerCall.Listener<ReqT> listener) {
      super(listener);
      this.logger = logger;
      this.tracer = tracer;
    }
   
    @Override
    public void onMessage(ReqT message) {
      String spanId = "";
      String traceId = "";

      if (message instanceof ExampleService.Message) {
        ExampleService.Message exampleMessage = (ExampleService.Message) message;
        spanId = exampleMessage.getSpanId();
        traceId = exampleMessage.getTraceId();
      } else {
        this.logger.warn("Unknown message type, trace-id is not extracted");
      }

      SpanContext parentContext =
          SpanContext.createFromRemoteParent(
              TraceId.fromLowerBase16(traceId, 0),
              SpanId.fromLowerBase16(spanId, 0),
              TraceFlags.builder().setIsSampled(false).build(),
              TraceState.builder().build());

        span =
          this.tracer
              .spanBuilder("example_grpc_api")
              .setParent(parentContext)
              .setSpanKind(Span.Kind.SERVER)
              .startSpan();
        span.setAttribute("messageType", message.getClass().getName());


      try (Scope scope = this.tracer.withSpan(span) {
        super.onMessage(message);
      }
    }

    @Override
    public void onHalfClose() {
      try (Scope scope = this.tracer.withSpan(span) {
        super.onHalfClose();
      } catch (Exception e) {
        span.end();
      }
    }

    @Override
    public void onCancel() {
      try (Scope scope = this.tracer.withSpan(span) {
        super.onCancel();
      } finally {
        span.end();
      }
    }
  }
}
```

**Comment by luka223** [comment]
@anuraaga This snippet works partially, as the all spans in the service itself belong to new trace, and the span in the interceptor belongs to the trace started by a remote service, so at the end there are two traces instead of one.

That's only happened beacuse of the saving span globally, as `this.tracer.withSpan(span);` still throws the exception I mentioned.

I guess because of the exception, `this.tracer.getCurrentSpan()` doesn't return the correct span, so without saving it into a variable it can't be closed.

**Comment by jkwatson** [comment]
@luka223 the `withSpan` method is throwing the exception? That seems like a change from the initial report of the issue.

Is there any other instrumentation in your codebase? Are you using the auto-instrumentation javaagent, or are you just using the API/SDK directly?

**Comment by anuraaga** [comment]
@luka223 What do you mean by "spans in the service" vs "span in the interceptor "? Here we're creating a span with `parentContext` set with the context of the message (meaning it should be connected to the trace of your remote clients if the information in the message is correct). What is in the second trace?

**Comment by luka223** [comment]
@jkwatson I didn't express myself correctly, `withSpan` method isn't throwing exception itself, but when I use it in `onMessage` method, exception is thrown after `onMessage` is completed (`withSpan` executes without errors). I'm using SDK directly.

@anuraaga By spans in the service I mean on spans created in the service itself (after execution of interceptor, but same service as where interceptor is). Trace in the interceptor is connected to trace of remote client (which is good), but spans created after incerceptor execution are in separate trace, not connected to the first one. I hope I explained it better now.

**Comment by anuraaga** [comment]
@luka223 Is it possible to paste the exception with stack trace that you're seeing? An exception after onMessage is not something I'd expect so can't imagine where it's being thrown.

**Comment by bogdandrutu** [comment]
Here is the official gRPC integration using Open emails which used the same context https://github.com/grpc/grpc-java/blob/master/census/src/main/java/io/grpc/census/CensusTracingModule.java

There is a special place where you can modify the context, you don't need to attach yourself because it is automatically done by gRPC framework

**Comment by luka223** [comment]
@anuraaga Actually, I was wrong, exception is not thrown, but this is just a log of exception which is caught in gRPC library itself. You can see the log below:

```
[grpc-default-executor-0] ERROR io.grpc.ThreadLocalContextStorage - Context was not attached when detaching - Username:  - Tenant: 
java.lang.Throwable: null
	at io.grpc.ThreadLocalContextStorage.detach(ThreadLocalContextStorage.java:48) [grpc-context-1.29.0.jar:1.29.0]
	at io.grpc.Context.detach(Context.java:448) [grpc-context-1.29.0.jar:1.29.0]
	at io.grpc.Context$CancellableContext.detach(Context.java:788) [grpc-context-1.29.0.jar:1.29.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:39) [grpc-core-1.29.0.jar:1.29.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.29.0.jar:1.29.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

That happens only if `tracer.withSpan(span)` is not used in `try`, but the result is the same with or without this error.

@bogdandrutu I didn't attached context myself explicitly, if I understood you correctly.

**Comment by anuraaga** [comment]
@luka223 So it sounds like the exception goes away when using `try` which makes sense, using the `try` pattern is required for making sure the scope is cleaned up properly.

So the issue is just the two traces, "but spans created after incerceptor execution are in separate trace, not connected to the first one." So you are making client calls in your business logic that are not being connected. How are you instrumenting the client calls, using the official `TracingClientInterceptor`? 

@bogdandrutu I haven't used the `ServerStreamTracer` API before, it looks more structured than wrapping the call. I think it could make even our code a bit simpler, but here the current snippet is mounting context correctly, I think, and the issue has a good chance of being downstream from the interceptor from what I can tell.

**Comment by bogdandrutu** [comment]
@anuraaga please give a try to that. It was explicitly design for this :)

**Comment by luka223** [comment]
@anuraaga I didn't use `TracingClientInterceptor` on the client side, client side is just a simple API that receives HTTP call and calls server app discussed here using gRPC. 

Here is the code snippet for client application:

```Java
@GetMapping
public boolean get() {
  SpanContext spanContext = this.tracer.getCurrentSpan().getContext();
  String traceId = spanContext.getTraceId().toLowerBase16();
  String spanId = spanContext.getSpanId().toLowerBase16();
  ExampleService.Message request =
      ExampleService.Message.newBuilder()
          .setSpanId(spanId)
          .setTraceId(traceId)
          .build();

  Exampleservice.MessageResponse response = this.exampleServiceClient.notify(request);
  return response.getSuccess();
}
```

**Comment by luka223** [comment]
Just to check what is the meaning of the added label? Is the issue confirmed?

**Comment by jkwatson** [comment]
It's just noting that we need to either confirm that this is an issue, or close it before GA. So far, no one has been able to reproduce your issue. Can you post a full reproduction case in github somewhere?

**Comment by luka223** [comment]
Sorry for later response, will post full code on my Github and share it here in the next few days.

**Comment by jkwatson** [comment]
@luka223 thanks. If no one else picks this up, I'll try to take a look this week.

**Comment by jkwatson** [comment]
@luka223 The issue with your code is that you're holding on to the Scope, and trying to close it on what appears to be a separate thread. The scope *must* only be created/close on the same thread.

Unless you're using automatic thread-local-based propagation, you don't technically need to ever put a span into the scope with a `tracer.withSpan()` call.

**Comment by luka223** [comment]
@jkwatson  I printed out thread ID in `onMessage` and `onHalfClose` methods and it is the same ID. In these methods Scope is opened and closed. Output is:
```
(onMessage) Thread # 51 is doing this task
(onHalfClose) Thread # 51 is doing this task
```

Also, removing `tracer.withSpan()` call from these methods doesn't give the exception anymore, but still doesn't work as I expect.

What I want is to get one trace that looks like:
```
forward_service_api
  grpc_interceptor
     grpc_service
```

But instead, it is separated into two traces:
```
forward_service_api
  grpc_interceptor

grpc_service
```

**Comment by jkwatson** [comment]
With the context association gone, your grpc_service no longer has a parent span in the context to use automatically. If you're going to try to propagate your trace through the payload, rather than using the standard implementation that uses headers, you're going to have to do all the work to stitch your trace together manually.  I don't think there's going to be an easy solution to using this approach, unfortunately. 

Why can't you use the standard interceptor? Why do you need to propagate via payload, rather than header?

**Comment by luka223** [comment]
Propagation via payload is not dictated by my service, that is the reason of using it. Thank you for the explanation! I'm closing the issue.
