### ISSUE TITLE
Document Metric exporter

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1405]
I have spent almost an hour today trying to debug failing test in java instrumentations repo. At last I have discovered, that since #1368 if I call `OpenTelemetrySdk.getMeterProvider().getMetricProducer().getAllMetrics()` two times in a row, as one of our tests did, the second call will return no measurements for `ValueRecorder`s. It would be nice to have this behaviour documented somewhere :)

**Comment by jkwatson** [comment]
I wonder if we could come up with a better name than "getAllMetrics", since it's really, "get all metrics since the last time they were asked for".
