### ISSUE TITLE
opentelemetry-bom published locally but not to maven central

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-java#1413]
**Describe the bug**
When running "./gradlew clean publishToMavenLocal", opentelemetry-bom appears in the local m2 repo (e.g. for 0.6.0 tag), but the same version doesn't appear to have been released to [maven central](https://repo1.maven.org/maven2/io/opentelemetry/).

**Steps to reproduce**
Checking tag `v0.6.0`, run `./gradlew clean publishToMavenLocal`, check local m2 repo and find `opentelemetry-bom`.

**What did you expect to see?**
Expected to see `opentelemetry-bom` in maven central for tag `v0.6.0`.

**What did you see instead?**
`opentelemetry-bom` was missing.

**What version and what artifacts are you using?**
Artifacts: opentelemetry-bom
Version: v0.6.0
How did you reference these artifacts? n/a

**Environment**
n/a

**Additional context**
n/a

**Comment by anuraaga** [comment]
Just took one glance and one suspicious part I found was we may need to filter out the bom project from this line

https://github.com/open-telemetry/opentelemetry-java/blob/master/build.gradle#L354
