### ISSUE TITLE
More logging on exporter failures

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1418]
**Is your feature request related to a problem? Please describe.**
A customer has tried to Otel java instrumentation agent. He has difficulties understanding if he has configured exporters correctly or not. Apparently only Zipkin exporter logs some warnings if data sending fails. All others are silent.

**Describe the solution you'd like**
Provide more feedback if any component fails, e.g. by writing more failure related information to logs.

**Describe alternatives you've considered**
As an alternative make sure that such info is written at least on debug level.

**Comment by jkwatson** [comment]
Looks like the following exporters need at least some amount of error logging:

- [ ] Jaeger
- [ ] OLTP Metrics
- [ ] OLTP Spans

Any others?

**Comment by iNikem** [comment]
Closed by #1480
