### ISSUE TITLE
Span.recordException

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1430]
Implement newly added API method: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#record-exception

Ideally, while solving this issue also add [corresponding semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/exceptions.md) to `SemanticAttributes` class

**Comment by anuraaga** [comment]
I can take this on
