### ISSUE TITLE
Span not exported to Jaeger Collector

### ISSUE THREAD

**Issue by poogurgaon** [open-telemetry/opentelemetry-java#1435]
I have configured JaegerGrpcSpanExporter , so that it can export the created spans to Jaeger-Collector.

I don't want to export the spans to Jaeger-Agent. I have written down below code.
`public BatchSpansProcessor getBatchSpanProcessor(){
 return BatchSpansProcessor.newBuilder(
JaegerGrpcSpanExporter.newBuilder().setServiceName("collector-exporter").
setChannel(ManagedChannelBuilder.forAddress(localhost,14268).usePlaintext().
build()).build();
}`

when i change the port to 14250 i.e. Jaeger-agent port spans are exported to UI but with 14268 I am not able to find any trace at Jaeger UI.

May you please suggest if i need to change above code.

**Comment by objectiser** [comment]
@poogurgaon The port `14250` is the [gRPC port on the Jaeger collector](https://www.jaegertracing.io/docs/1.18/deployment/#collectors), not the agent. So using port `14250` is correct.

**Comment by poogurgaon** [comment]
@objectiser 

Thanks for your response.

With port 14250 it is working fine on localhost.

But issue is arising when below use case executed:
I am having jaeger collector as a pod running on k8s cluster , No jaeger agent is running. 

I did tried with port 14250 and 14268 after deploying my springboot app on k8scluster , but no spans propagated to JaegerUI
running on k8s cluster.

**Comment by thisthat** [comment]
Hi @poogurgaon, `localhost` will work only if your container contains both the Jaeger service and your spring application. If the Jaeger service is in another container, you should replace it with the IP/hostname of such a container

**Comment by poogurgaon** [comment]
> Hi @poogurgaon, `localhost` will work only if your container contains both the Jaeger service and your spring application. If the Jaeger service is in another container, you should replace it with the IP/hostname of such a container

Hi @thisthat I have replaced the hostname with jaeger-host, but still facing same issue.

**Comment by thisthat** [comment]
Please, wait until #1419 is merged. This PR proposes a better error reporting that you can use to identify the reason for the failure.

**Comment by poogurgaon** [comment]
> Please, wait until #1419 is merged. This PR proposes a better error reporting that you can use to identify the reason for the failure.

Great Thank You , I will wait.
