### ISSUE TITLE
Create a stress test that shows trace-SDK behavior under high load

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1438]
I'm particularly interested in making sure that we don't grow our heap in an unbounded fashion under high load. And, if we make changes to the export pipeline, that we don't inadvertently make a change that results in unbounded heap growth.

Note: this does not necessarily need to be a part of the unit test suite, because it might take a few minutes to run. However, having a test harness that can be run to verify this behavior when changes are made would be extremely valuable.

**Comment by huntc** [comment]
In advance, I’d say that we probably are growing the heap in a unbounded manner presently. We should look at the use case where an exporter blocks on a network connection and goes through its retries. The Telemetry should pile up given the unbounded queues used by the schedulers within the sdk.

**Comment by jkwatson** [comment]
The BatchSpanProcessor is built to drop spans beyond the configured limit. If that is not happening, then we definitely need to know about it!

**Comment by huntc** [comment]
The `SimpleSpanProcessor` would be a good one to try. The simple one calls `export` when a span ends. Just keep ending spans...

**Comment by jkwatson** [comment]
Yes, I think that the SSP probably wouldn't do well at all with a slow exporter and high throughput! I'm more worried personally about the BSP, since it actually intends to have dealt with this issue. :)

**Comment by jkwatson** [comment]
Ideally, this stress test would additional include sending the data to the collector via OTLP, and have the ability to introduce network issues in between the running JVM and the collector. Maybe with something like toxiproxy?

**Comment by parallelstream** [comment]
Hey @jkwatson for our internal needs at Atlassian we created a tool which can define OTel data as a simple JSON structure and replay it against running collector - https://github.com/parallelstream/open-telemetry-data-simulator. We can possibly modify it to add toxiproxy. Is this smth which can be useful as general purpose testing tool?

**Comment by jkwatson** [comment]
that sounds very useful, yes. the stress test that I wrote could definitely use additional beefing up. Could your tool run the data through the SDK and then through to the collector?

**Comment by jkwatson** [comment]
I'm going to close this particular issue for now. We have a basic stress test available and I have validated that the SDK behaves acceptably under adverse network conditions. @parallelstream If you are able to contribute more testing tools, that would be fantastic.
