### ISSUE TITLE
Sampling Decision is not Passed From Parent to Child 

### ISSUE THREAD

**Issue by MitchellDumovic** [open-telemetry/opentelemetry-java#1445]
Generally, if the parent span is set to "not sample", then any child span should also be set to "not sample". 

However, by default that is not the case here. If unset, the [default](https://github.com/open-telemetry/opentelemetry-java/blob/322b661e3734ac4dafd89ecd20572a19bbc72cef/sdk/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfig.java#L86) sampler is set to "always sample", and the "always sampler" [ignores the parent span context when making its sampling decision](https://github.com/open-telemetry/opentelemetry-java/blob/aaec09d68d5312b214f85b7b53b7a4e818497462/sdk/src/main/java/io/opentelemetry/sdk/trace/Samplers.java#L148).

**Comment by Oberon00** [comment]
This is a spec defect actually (as you yourself pointed out @MitchellDumovic, thx!): https://github.com/open-telemetry/opentelemetry-specification/issues/728
