### ISSUE TITLE
Event timestamp should be more clearly optional

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1447]
**Is your feature request related to a problem? Please describe.**

Currently, methods like `addEvent` either record a timestamp with current time, or a user-passed in time. But the spec for an event indicates timestamp is optional.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-events

**Describe the solution you'd like**

The Javadoc at least has to make clear that current time is being used as the timestamp, or a user could mistake the methods that don't accept `timestamp` as adding `timestamp-less` events.

It should probably also provide either methods for, or at least pointers to how a user can add an event without a timestamp.

**Describe alternatives you've considered**

**Additional context**

Came up when discussing modeling exceptions as events
https://github.com/open-telemetry/opentelemetry-java/pull/1434#discussion_r458507524

**Comment by jkwatson** [comment]
From the spec: "  Events have a time associated with the moment when they are added to the Span. "

So, this sounds like just a javadoc update to make it explicit that we're using `now` if the user doesn't give us one? I don't think you can have a "timestamp-less" event.

**Comment by anuraaga** [comment]
Hmm - guess need to clarify the spec then. Just two sentences down it says "(Optional) Timestamp for the event" so this does seem to be a contradiction.

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#add-events

**Comment by jkwatson** [comment]
I *think* that's meaning optional in the sense that the SDK will set it for you if you don't provide it via the API call. But, I could be wrong, of course!

**Comment by carlosalberto** [comment]
Marking as required-for-ga, as we should at least take a clear stance on this one.

**Comment by anuraaga** [comment]
Filed https://github.com/open-telemetry/opentelemetry-specification/issues/796

**Comment by malafeev** [comment]
this one looks like done. javadoc updated by @anuraaga

**Comment by anuraaga** [comment]
Yup, thanks!
