### ISSUE TITLE
Modernize unit tests

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1452]
I'd like to propose a couple of options for large refactoring of the unit tests. I'm committed to take on the grunt work for both of them if others are ok :)

### Migrate to JUnit5

JUnit5 has many nice features compared to JUnit4 such as native parameterized tests, repeated tests, and smarter extension API. It's the actively developed version and it'd be nice for us to take advantage of any improvements that come down the line.

In practice, the majority of this refactor will be changing the imports and removing `public` modifier and removing the `@RunWith(JUnit4.class)`, which we could do anyways since I believe that's a relic from Google's build system.

### Migrate to AssertJ

AssertJ is extremely popular in the Java ecosystem while Truth is mostly used by Google projects. While these numbers are likely not extremely precise, I think the multiple orders of magnitude difference is probably generally accurate in indicating the trend.

https://github.com/joel-costigliola/assertj-core/network/dependents
https://github.com/google/truth/network/dependents

I think it would improve our new-contributor experience if we switch from Truth to AssertJ since I'd wager far more Java developers are familiar with that based on these numbers.

In practice, the majority of this refactor will be mechanical, and often just changing imports since the APIs are pretty similar.

**Comment by jkwatson** [comment]
I'm very much in favor of upgrading to junit5, especially since we can, since we updated our tests to use java 8. 100% agreed with removing the `@RunWith` annotations, as well, as they just add noise, IMO.

I have less of of an opinion on AssertJ vs. Truth. I've never used AssertJ and I hadn't used Truth before this project. :)

**Comment by anuraaga** [comment]
I'll tackle the junit5 first - thanks for the vote :)

**Comment by jkwatson** [comment]
@anuraaga I think we can close this now, yes?
