### ISSUE TITLE
Bound Metric Instruments create empty MetricData

### ISSUE THREAD

**Issue by tobbaumgartner** [open-telemetry/opentelemetry-java#1453]
**Describe the bug**
When binding a synchronous instrument, it records empty `MetricData` even though no metrics are recorded. This does not occur with the `BoundValueRecorder`.

**Steps to reproduce**
```
        Meter meter = OpenTelemetry.getMeterProvider().get("test","test:1.0.0");
        DoubleCounter counter = meter
                .doubleCounterBuilder("byte_received")
                .build();
        DoubleCounter.BoundDoubleCounter boundCounter = byteCounter.bind(Labels.empty());
        
        Collection<MetricData> data = OpenTelemetrySdk.getMeterProvider().getMetricProducer().collectAllMetrics();
        for(MetricData md : data) {
            System.out.println(md);
        }
```

**What did you expect to see?**
As with other instruments, points should be empty. 

**What did you see instead?**
Points contains a `DoublePoint` with the value 0.0.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk`
Version: `v0.6.0`
How did you reference these artifacts?  `compile('io.opentelemetry:opentelemetry-sdk:0.6.0-SNAPSHOT')`

**Environment**
Compiler: n/a
OS: Windows 10

**Additional context**
None

**Comment by jkwatson** [comment]
This is an interesting case, and I'm not sure of what the behavior should be. 

In general, for counters, should they always report '0's if nothing has been counted? Should they reporting nothing if nothing was counted in the reporting interval, or should they report '0', since the counter remains at zero?
