### ISSUE TITLE
For alpha review test the new API with 2-3 existing current instrumentation.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#146]

**Comment by tedsuo** [comment]
Create a demo app containing the following:
* New SDK
* 1 -2 OT plugins
* 1 - 2 OC plugins
* 1 - 2 New pieces of instrumentation

https://github.com/opentracing-contrib/java-opentracing-walkthrough could be a good starting point.

**Comment by bogdandrutu** [comment]
Duplicate https://github.com/open-telemetry/opentelemetry-java/issues/531
