### ISSUE TITLE
Support system property otel.resource.attributes corresponding to OTEL_RESOURCE_ATTRIBUTES

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1462]
It looks like currently only way to set resource attributes is via env var `OTEL_RESOURCE_ATTRIBUTES`. Would be nice to also support system property `otel.resource.attributes` similar to other configuration properties which support both env var and system property configuration.

**Comment by dengliming** [comment]
@trask Hi~ It looks good. I submit a PR. Can you review and share your opinion?

**Comment by trask** [comment]
Closed by #1466. Thanks @dengliming!
