### ISSUE TITLE
Add public constants for all exporter default configuration values

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1465]
I found myself wanting these when reviewing: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/729.

And @anuraaga brought up here on my PR also: https://github.com/open-telemetry/opentelemetry-java/pull/1464#discussion_r460351059

**Comment by jkwatson** [comment]
@trask does #1486 work for this? If so, please close. Thanks!

**Comment by trask** [comment]
yes it does!
