### ISSUE TITLE
Hide EnvAutodetectResource

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#1472]
Consider hiding `EnvAutodetectResource` (formerly `EnvVarResource`) and expose its functionality as a static method in `Resource` (such as `createDefault()` or `createFromEnv()`).

(Follow up from #1466 )

**Comment by dengliming** [comment]
So we can use Resource.createDefault() instead of EnvAutodetectResource.getResource()?

**Comment by anuraaga** [comment]
Yeah that's my idea. The less public classes, the more flexibility we have going forward. For example, we may change it to not detect or use env or something with no restrictions.

**Comment by dengliming** [comment]
If so, the method EnvAutodetectResource.parseResourceAttributes and builder should stay on or just put all to Resource.java?

**Comment by anuraaga** [comment]
As long as it's all package private, so hidden from user, having the implementation in a separate class is still fine :) Can prevent Resource from getting too long and it can have more focused tests.

**Comment by dengliming** [comment]
@anuraaga I'm still a little confused. If i do like this. seems make no sense.
```
 public static Resource createDefault() {
    return new EnvAutodetectResource.Builder().readEnvironmentVariables().readSystemProperties().build();
  }
```

**Comment by dengliming** [comment]
@anuraaga Could you please help to see if the modification below make sense?
in `Resource.java` add below method
```
public static Resource createDefault() {
    return new EnvAutodetectResource.Builder().readEnvironmentVariables().readSystemProperties().build();
  }
```
and keep class `EnvAutodetectResource  ` package protected
`final class EnvAutodetectResource {`

**Comment by anuraaga** [comment]
@dengliming Yup that seems good to me, thanks!

**Comment by jkwatson** [comment]
closing via #1477
