### ISSUE TITLE
Allow to configure maximum attribute value size

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1478]
**Is your feature request related to a problem? Please describe.**
Operators who deploy an application together with SDK can now configure e.g. the maximum number of attributes or events per span. This is done, among other things, to protect the application from excessive memory usage by monitoring SDK. But attribute values can still be arbitrary large.

**Describe the solution you'd like**
Add one more parameter to `TraceConfig` to allow for configuration of maximum size of attribute value. Values longer than this given threshold will be truncated. 

**Describe alternatives you've considered**
This may be delegated to Collector, but that is too late to protect application from OOM.

**Additional context**
Although truncating `AttributeValueString` is simple (if we put aside the question of byte/chars/codepoint/grapheme), it is unclear how to truncate `AttributeValueStringArray`.

**Comment by anuraaga** [comment]
Should this be defined in the spec first?

**Comment by iNikem** [comment]
`TraceConfig` already allows for configuring max number of events/links on spans and number of attributes. But this is not in spec yet: https://github.com/open-telemetry/opentelemetry-specification/issues/182. So I want to continue this and allow to configure one more thing :) Who say that language cannot provide more configuration that spec dictates? ;)

**Comment by anuraaga** [comment]
Not me - adding the knob now makes sense too 👍
