### ISSUE TITLE
Lots of Javadoc warnings when building

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1483]
For example
```
...\api\src\main\java\io\opentelemetry\common\ReadableKeyValuePairs.java:28: warning: no @return
  int size();
      ^
```
or
```
...\api\src\main\java\io\opentelemetry\common\Labels.java:86: warning: no @param for value4
  public static Labels of(
```

**Comment by dengliming** [comment]
Can you assigne to me?

**Comment by iNikem** [comment]
Not sure it makes sense to write javadoc for obvious params or return values... Is there any profit in such warnings?

**Comment by anuraaga** [comment]
+1 to changing the defaults to not require param / return, we can make sure javadoc is useful through code review. But I wouldn't block if anyone else feels strongly about them. FWIW, if I had to choose between the style of the JDK or @trustin I'll generally side with the later :)

**Comment by Oberon00** [comment]
Personally I'm especially annoyed by having to write (and read!) `@return` docs that are literally copy and pase from the summary section.

**Comment by jkwatson** [comment]
100% agreed with loosening up the javadoc requirements a bit. Duplicated useless javadoc doesn't help anyone.

**Comment by iNikem** [comment]
You now even require javadoc for benchmarks??

**Comment by jkwatson** [comment]
> You now even require javadoc for benchmarks??

I don't think it was intentional...just got swept up in the madness.

**Comment by carlosalberto** [comment]
+1 to this. We should do (later) a pass to remove things that may be annoying to new contributors.

**Comment by jkwatson** [comment]
@Oberon00 Can we close this? I think this is done now with #1494

**Comment by Oberon00** [comment]
I think so!
