### ISSUE TITLE
Sampler.shouldSample can get a parent SpanContext of null

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1487]
Samplers get `null` for their parent `SpanContext` in `shouldSample` if the parent is "invalid". This seems to be the only place in the whole SDK+API where a SpanContext can be null. Everywhere else we pass an invalid/empty context in such a case. I think the sampling API should behave the same way.

`null` assigned here if the parent is invalid:

https://github.com/open-telemetry/opentelemetry-java/blob/78ed6490ba47568f5241604ea34f18d3ae6f3c4a/sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java#L214

then passed to `shouldSample` here:

https://github.com/open-telemetry/opentelemetry-java/blob/78ed6490ba47568f5241604ea34f18d3ae6f3c4a/sdk/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java#L231-L232

**Comment by jarebudev** [comment]
i can pick this one up
