### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by e-infotech** [open-telemetry/opentelemetry-java#1491]
Hi,

I want to work on an open-source software to be able to monitor it and get its metrics. But I'm confused about the starting point! Should I change anything in the software code or I just need to add a new page and call the software functions in that? 
I would appreciate it if anyone can help with it.

**Comment by jkwatson** [comment]
Can you provide some more context as to what you would like to monitor?

**Comment by e-infotech** [comment]
Does it matter?
I want to monitor the performance of the software such as CPU time, memory and so on. The more, the better 
Also, I need to trace the software and see what's going on in it

**Comment by jkwatson** [comment]
Well, is it a java application? What frameworks are you using? Do you want to use auto-instrumentation or manual instrumentation?

We do have a quickstart guide here:  https://github.com/open-telemetry/opentelemetry-java/blob/master/QUICKSTART.md

Does that help?

**Comment by e-infotech** [comment]
Yes, Java and Maven. Which one do you recommend?
I checked that before but I'm not sure if I have to change the software code?! Because if I need to change its code obviously it wouldn't be a good option.

**Comment by jkwatson** [comment]
If you're interested in auto-instrumentation, I recommend heading over to the instrumentation project, which hosts the auto-instrumentation agent:  https://github.com/open-telemetry/opentelemetry-java-instrumentation

**Comment by e-infotech** [comment]
Thank you for the link, but I went through this documentation, and I found it a bit vague, It's not organized and clear. I need a step by step documentation. If the application was mine that could be helpful though. Right now I can't figure out where exactly should those changes be applied? I installed Zipkin and Prometheus before, but I don't know how I can see the metrics and traces in them.

**Comment by jkwatson** [comment]
Hi @e-infotech . The project is still in beta at the moment, and we know our documentation probably needs more work. Can you try working through the documentation and ask questions about where you got stuck? Reaching out on our gitter channels is probably a great way to get help, and provide feedback.

Gitter for the Java API and SDK:  https://gitter.im/open-telemetry/opentelemetry-java
Gitter for the Java Instrumentation and Agent: https://gitter.im/open-telemetry/opentelemetry-java-instrumentation

**Comment by e-infotech** [comment]
Ok, thank you. I got stuck after downloading the jar file. I'm documenting everything I find out as I'm working on this, so I can share that with you afterwards. Thank you anyway.

**Comment by jkwatson** [comment]
Closing, as this issue is relevant for the instrumentation SIG
