### ISSUE TITLE
Provide programmatic configuration of service name for the OTLP exporter

### ISSUE THREAD

**Issue by dengliming** [open-telemetry/opentelemetry-java#1492]
follow [https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/864](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/864) We discuss here :) 

`OtlpGrpcSpanExporterProperties.serviceName` is not being used and Currently the way to set service name for OTLP is via `OTEL_RESOURCE_ATTRIBUTES`. We should have a way to set OpenTelemetry Resource Attributes programmatically which I think is important for a good Spring Boot experience. Do you have any good Suggestions?

@trask @anuraaga Can you also share your opinion here. Thanks.

**Comment by jkwatson** [comment]
I think this is a duplicate of https://github.com/open-telemetry/opentelemetry-java/issues/1454

**Comment by dengliming** [comment]
thx. let's move to there.
