### ISSUE TITLE
ZPage form handler uses GET

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1517]
**Describe the bug**
Currently, it seems that updating configs of ZPages uses HTTP GET
https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk_extensions/zpages/src/main/java/io/opentelemetry/sdk/extensions/zpages/TraceConfigzZPageHandler.java#L277

**What did you expect to see?**
It should use POST for security reasons. An image tag in an email would be enough to raise sampling rate and take down a service.

**Comment by anuraaga** [comment]
@wtyanan

**Comment by jkwatson** [comment]
I sure hope no-one is exposing zpages to the public internet!

**Comment by jkwatson** [comment]
This is done. closing
