### ISSUE TITLE
When using the env vars to set the TraceConfig, the SDK should wrap the probability sampler with a ParentOrElse sampler.

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1526]
When we introduced the ParentOrElse sampler as the default, we didn't update the TraceConfig builder code to wrap the probability sampler with a ParentOrElse. I think this is probably unexpected behavior, since the ParentOrElse should continue being the default wrapper Sampler.

If/when we change the Probability sampler to not consider the parent sampling decision, then this bug would be more severe.

**Comment by bogdandrutu** [comment]
This whole config needs a revision
