### ISSUE TITLE
API convenience methods for when empty labels are used

### ISSUE THREAD

**Issue by kenfinnigan** [open-telemetry/opentelemetry-java#1533]
**Is your feature request related to a problem? Please describe.**
Currently, to use an unbounded metric without labels it's necessary to do something like:

```
doubleCounter.add(2, Labels.empty())
```

**Describe the solution you'd like**
It would be great if any `add()`, `record()`, or other methods where `Labels` is a parameter for recording an unbounded metric,
that the API provided a convenience method that delegates to the current one.

For `DoubleCounter` it would mean adding:

```
default void add(double increment) {
  add(increment, Labels.empty());
}
```

Allowing the developer to:
```
doubleCounter.add(2)
```

**Comment by dengliming** [comment]
If so, should we update sourceCompatibility  to 1.8? 
```
sourceCompatibility = 1.8
    targetCompatibility = 1.8
```

**Comment by jkwatson** [comment]
Unfortunately, we can't do this with default methods, as the API still needs to support java 7.

**Comment by kenfinnigan** [comment]
So we can do the convenience, just not with a default method?

Is the rationale for requiring JDK 7 documented anywhere? Would be interested to read it

**Comment by dengliming** [comment]
@kenfinnigan sure

**Comment by jkwatson** [comment]
The rationale boils down to Android & grpc wanting to be able to use the APIs for java 7-compatible Android versions.

**Comment by kenfinnigan** [comment]
Thanks @jkwatson

**Comment by thisthat** [comment]
Closing this since #1538 got merged. Please, reopen the issue if you think this was not fully addressed.
