### ISSUE TITLE
Cannot use Gradle composite build

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1547]
**Is your feature request related to a problem? Please describe.**
I tried to develop a feature which requires code changes both in this repo and in java instrumentation repo. To verify that everything works I wanted to build instrumentation agent with changes from this repo using Gradle compose build. Unfortunately build failed:

```
Could not determine the dependencies of task ':smoke-tests:test'.
> Could not resolve all task dependencies for configuration ':smoke-tests:testRuntimeClasspath'.
   > Could not find io.grpc:grpc-api:.
     Required by:
         project :smoke-tests > project :opentelemetry-java:opentelemetry-proto
   > Could not find io.grpc:grpc-protobuf:.
     Required by:
         project :smoke-tests > project :opentelemetry-java:opentelemetry-proto
   > Could not find io.grpc:grpc-stub:.
     Required by:
         project :smoke-tests > project :opentelemetry-java:opentelemetry-proto
   > Could not find io.grpc:grpc-context:.
     Required by:
         project :smoke-tests > project :testing-common > project :opentelemetry-java:opentelemetry-api > project :opentelemetry-java:opentelemetry-context-prop
```

It seems to me that bom support used by this repo prevents from including it into other projects.

I don't know any other way to test instrumentation repo with unreleased changes from this project.

**Comment by anuraaga** [comment]
Fixing this seems important. In the meantime you can use `publishToMavenLocal` and point at 0.8.0-SNAPSHOT I believe.

**Comment by iNikem** [comment]
For some reason that fails with 
```
> Task :javaagent-tooling:compileJava FAILED
error: cannot access ThreadSafe
  class file for javax.annotation.concurrent.ThreadSafe not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

**Comment by jkwatson** [comment]
Is this needed for GA (I assume yes, but I thought I'd ask anyway)?

**Comment by iNikem** [comment]
Not strictly. This is "contributor experience" section. But before GA we may have a lot of changes spanning 2 repos. They will go much faster, if composite build works.

**Comment by jkwatson** [comment]
ok, I'll mark it as after-ga, but of course, if you want to fix it, I will certainly accept the fix!

**Comment by jkwatson** [comment]
I'm not saying this is a good idea, but could you use a git submodule for this? Or two git submodules, one for each project, and then have a separate build that ties them together?

**Comment by imavroukakis** [comment]
@jkwatson I played around with this a bit, and hit the initial wall that @iNikem reported, but I think I have a palatable workaround.
For each of the boms defined in `build.gradle`
```
 boms = [
                grpc           : "io.grpc:grpc-bom:${grpcVersion}",
                guava          : "com.google.guava:guava-bom:${guavaVersion}",
                junit          : "org.junit:junit-bom:${junitVersion}",
                protobuf       : "com.google.protobuf:protobuf-bom:${protobufVersion}",
                zipkin_reporter: "io.zipkin.reporter2:zipkin-reporter-bom:${zipkinReporterVersion}"
        ]
```
add the `${xxxVersion}` in the corresponding `libraries` section e.g.

```
....
                grpc_api                : "io.grpc:grpc-api:${grpcVersion}",
                grpc_context            : "io.grpc:grpc-context:${grpcVersion}",
                grpc_protobuf           : "io.grpc:grpc-protobuf:${grpcVersion}",
                grpc_stub               : "io.grpc:grpc-stub:${grpcVersion}",
....
```

and then the composite build from `opentelemetry-java-instrumentation` should work
```
 ./gradlew clean build --include-build ../opentelemetry-java
```

**Comment by iNikem** [comment]
But that defeats the whole purpose of bom files: ability to skip defining versions on every dependency

**Comment by imavroukakis** [comment]
That's true, hence I'm calling it a workaround. It may be the BOM support is either not well supported in composite builds or it needs to be defined in a different manner.

**Comment by imavroukakis** [comment]
I tried something else that seemed to succeed.

In the `dependencies` closure, I added

```
compile platform(boms.grpc)
compile platform(boms.grpc)
compile platform(boms.guava)
compile platform(boms.junit)
compile platform(boms.protobuf)
compile platform(boms.zipkin_reporter)
```

This allowed the composite build to proceed without having to explicitly define versions - I'm just a little uncertain as to the effect this has on the `opentelemetry-java` build.

**Comment by Oberon00** [comment]
What you did (except for use of the deprecated `compile` configuration) is the normal way I know to apply a bom. It seems we use this code https://github.com/open-telemetry/opentelemetry-java/blob/6c660d92e5cd620f5a8925268b9278b07b8ef233/build.gradle#L319-L327 and probably in composite build mode, there is a problem with it (e.g. there might not be a *Classpath configuration)

**Comment by imavroukakis** [comment]
@Oberon00 funnily enough, I tried `implementation` as well and the composite build would not proceed, gave me the same issue as originally reported by @iNikem . Maybe `api` is appropriate?

**Comment by jkwatson** [comment]
@iNikem any thoughts on whether we need to keep this open?

**Comment by iNikem** [comment]
I will give it a try during next week and then give my opinion

**Comment by iNikem** [comment]
Seems to be working now.
