### ISSUE TITLE
Configuration to disable ResourceProviders

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1551]
As a follow up for #1548 there should be a configuration option to disable any `ResourceProvider` service provider found on the classpath. E.g. add env variable/system property with a coma-separated list of class names of  `ResourceProvider` that should be ignored during Resource composition.

**Comment by iNikem** [comment]
Probably should be assigned to me.

**Comment by anuraaga** [comment]
@zoercai Sorry for the delay I finally found your GitHub handle :) I think this is a good issue to get familiar with the SDK, would you be able to take it on?

@jkwatson Please reassign if task accepted (I confirmed with @iNikem already).

**Comment by zoercai** [comment]
@anuraaga Yep I'll take a look, thanks!

**Comment by jkwatson** [comment]
Done! Thanks for picking it up, @zoercai !

**Comment by zoercai** [comment]
This can be closed now from #1640

**Comment by jkwatson** [comment]
closed via #1640
