### ISSUE TITLE
ResourceConstants -> ResourceAttributes

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1556]
We should use the same `*AttributeSetter` pattern for Resource as we do for span attributes for consistency. Since it's public API we need to knock it out soonish.

**Comment by jkwatson** [comment]
I'm going to bump down the priority on this to a p2, since it's not absolutely critical to be done first.

**Comment by jarebudev** [comment]
i can pick this one up

**Comment by jarebudev** [comment]
@jkwatson is this still required? (I just noticed the proposal in #1580 )

**Comment by jkwatson** [comment]
Let's get this done; if we decide that #1580 is a good idea, we can change lots of things all at once for that.
