### ISSUE TITLE
Replace usages of java.util.Timer with a ScheduledExecutor in the BatchSpanProcessor

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1560]
The Timer has known issues with clock changes. We should use ScheduledExecutors as they are the more modern construct for doing timed executions.

**Comment by anuraaga** [comment]
Is this a dupe of #729?

**Comment by malafeev** [comment]
I can do it, please assign to me to proceed.

**Comment by iNikem** [comment]
There are already 2 PRs addressing this issue :)
