### ISSUE TITLE
Use Java 9+ APIs for better precision in ProcessResource

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1564]
Currently, we use de-facto, but not well defined APIs for extracting process information and are limited in what we can get. We should use reflection to access Java 9+ APIs when available to provide better information when running on modern JVM.

From https://github.com/open-telemetry/opentelemetry-java/pull/1555/files#diff-a802c9460480a3f888b7e6fa984c5686R32

**Comment by anuraaga** [comment]
Also at the same time it would be good to switch the current platform calls to reflection as well to unbreak Android support (though it'd be quite limited still).

**Comment by iNikem** [comment]
Anybody thinks that multi-release jar is a good way to do that?

**Comment by anuraaga** [comment]
Yeah MRJar would work well too :)

**Comment by piotr-sumo** [comment]
@anuraaga can I contribute to this issue?

**Comment by anuraaga** [comment]
Thanks @piotr-sumo!

**Comment by piotr-sumo** [comment]
@anuraaga Basically I have the reflection version ready. 

However, if we want to go with multi-release jar I'll change my code.
