### ISSUE TITLE
Rename ProbabilitySampler to TraceIdRatioBasedSampler

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1573]
Also verify we're meeting the spec after this merge:
https://github.com/open-telemetry/opentelemetry-specification/pull/611

**Comment by carlosalberto** [comment]
Hey @akshay1312 still working on this?

**Comment by dengliming** [comment]
I am willing to take this If no one has started yet.

**Comment by dengliming** [comment]
I have submitted a related PR [here](https://github.com/open-telemetry/opentelemetry-proto/pull/221)
