### ISSUE TITLE
Could we use retrolambda for the building the API and use java 8 language features?

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1576]
Opening this issue so someone can do some research about the feasibility for doing this with the API.

**Comment by jkwatson** [comment]
I haven't looked into it carefully, but could use build a java7-friendly distribution of the OpenTelemetry APIs along side the java8 one that uses default methods, etc? Yes, the java7 would end up looking slightly differently, but they would end up with the same implementation in the SDK? 

I honestly don't know if this is possible, or even makes sense, but I thought it was at least worth a thought experiment.

**Comment by anuraaga** [comment]
`you must always do a clean build` makes me think the backporting uses random IDs or something since if it was deterministic that doesn't seem like it'd be the case. So yeah if it worked that would be awesome but don't have high hopes 😿

**Comment by jkwatson** [comment]
I'm closing this. Was a good thought experiment, but not a good idea.
