### ISSUE TITLE
Rename `HttpTextPropagator` to `TextMapPropagator`.

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#1581]
See: https://github.com/open-telemetry/opentelemetry-specification/pull/793

**Comment by dengliming** [comment]
Are you sure? It seems that this `repository` does not have classes with `HttpTextPropagator`  that name.

**Comment by malafeev** [comment]
`HttpTextFormat` -> `TextMapFormat`
`MultiHttpTextFormat` -> `MultiTextMapFormat`
`CustomHttpTextFormat` -> `CustomTextMapFormat`
`NoopHttpTextFormat` -> `NoopTextMapFormat`
?

**Comment by dengliming** [comment]
I prefer `*Propagator`  this one.

**Comment by carlosalberto** [comment]
I suggest we go with `Propagator` instead of `Format` as a suffix. 

@open-telemetry/java-approvers opinions on this?
