### ISSUE TITLE
BatchSpanProcessor performance goals

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1587]
During recent optimisations of `BatchSpanProcessor` several questions have arisen regarding further performance optimisations. But we don't currently have proper benchmarks that could clearly demonstrate the benefit of any performance gains as opposed to induced code complexity. E.g. we cannot it automatic way compare the percent of dropped spans.

We have to come up with such benchmarking setup and agree on acceptable performance characteristics of `BatchSpanProcessor`.

**Comment by jkwatson** [comment]
Probably related to #1438 .

**Comment by jkwatson** [comment]
There is also an issue to write micro-benchmarks for the BSP: #790

**Comment by jkwatson** [comment]
We have multiple benchmarks now for the BSP, so I'm going to close this.
