### ISSUE TITLE
Sampler should use `toString` to provide a debug String?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1601]
**Is your feature request related to a problem? Please describe.**
Currently, `Sampler` has a separate method, `getDescription` to provide a debug string.

**Describe the solution you'd like**
Use `toString` instead, an API provided by Java for this exact purpose. Works well with everything, including IDE and unit test failure messages.

**Comment by jkwatson** [comment]
I agree that we should definitely have toStrings for this, but the spec currently specifies additionally have the `getDescription` as a part of the sampler:  https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#getdescription

**Comment by XiXiaPdx** [comment]
Dear @jkwatson,

I would like to work on this issue and I want to see if understand what the acceptance criteria would be. 

AFAICT:
some implementators of `sampler` have overrided `toString()` and the respective `getDescription()` calls through `toString`
a few implementators do not follow this pattern. 

So is the acceptance criteria to have all implementations have the same pattern with `getDescription()` calls through `toString` ? 

Thanks

**Comment by jkwatson** [comment]
Dear @XiXiaPdx ;)
I'd make the `toString()` call the `getDescription()` method, not the other way around, personally. That way someone won't accidentally update the toString() thinking that it's purely for debug and break the `getDescription()` method. Make sense?

**Comment by jkwatson** [comment]
closed via #1813
