### ISSUE TITLE
Consider moving TraceState into the SpanContext

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1604]
TraceState a wrapper for a List of key-value pairs. Could we consider moving it into the SpanContext itself and providing a helper class to manipulate it?

The advantage would be to remove one more wrapper from the auto-instrumentation project.
The disadvantage would be that it would be more awkward to provide more advanced functionality, like lazily parsing it.

**Comment by anuraaga** [comment]
Let's stick with the approach in #2138 :)
