### ISSUE TITLE
RecordException overwrites additional attributes with generated ones instead of the other way round.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1607]
See code here:

https://github.com/open-telemetry/opentelemetry-java/blob/0024aa9beeafd512c935b5378d031963e0d4675b/sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpan.java#L440-L442

Spec at https://github.com/open-telemetry/opentelemetry-specification/blob/a6db328ada9bf30ba880b9cfab3296787c39fe67/specification/trace/api.md#record-exception

> If attributes with the same name would be generated by the method already, the additional attributes take precedence.

Also, I wonder if we should still record any additional attributes if exception is null.

**Comment by jkwatson** [comment]
@Oberon00 I think it's even a bit worse than the title of the bug. Currently, Attributes are not deterministic in which one will win, when the same key is provided. So, definitely an issue, and one that's been lurking for a bit. thanks for pointing out the spec that we're not in line with.

**Comment by dengliming** [comment]
I'm a little confused about `take precedence`.  Does this mean that Attributes that the method has already generated can be overridden by additional Attributes?

**Comment by Oberon00** [comment]
Exactly. Would changing the spec to "Attributes MUST NOT be added to the event by the function if an attribute with the same key is in the additional attributes." be more clear?

**Comment by dengliming** [comment]
` SemanticAttributes.EXCEPTION_TYPE.set(attributes, exception.getClass().getCanonicalName()); ` I'm a little confused about what's wrong with this code. if the additional attributes already contain `EXCEPTION_TYPE` attribute, and can't be changed. right?

**Comment by Oberon00** [comment]
Oh, I just assumed it worked like a regular map, instead of the other way round. If I call SetAttribute on the same span multiple times with the same key, will the last key still win?

**Comment by jkwatson** [comment]
> Oh, I just assumed it worked like a regular map, instead of the other way round. If I call SetAttribute on the same span multiple times with the same key, will the last key still win?

SetAttribute on the Span is a little different, since that doesn't use the Attributes implementation. I believe last-one-in wins on the span attributes, but first-one-in wins on Event attributes. I don't think it's a good thing that there's a different in the behavior!

Also, there is already a test that the provided attributes over-ride the "instrinsic" attributes:  https://github.com/open-telemetry/opentelemetry-java/blob/ed08e9f28783978e792156fa97283b384e90bf87/sdk/tracing/src/test/java/io/opentelemetry/sdk/trace/RecordEventsReadableSpanTest.java#L753

**Comment by Oberon00** [comment]
OK, then it seems this bug report is invalid. Sorry, I just read the code and assumed it was an obvious oversight.
