### ISSUE TITLE
Flaky Test (3x): io.opentelemetry.exporters.otlp.OtlpGrpcMetricExporterTest > testExport_DeadlineSetPerExport()

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1608]
```
io.opentelemetry.exporters.otlp.OtlpGrpcMetricExporterTest > testExport_DeadlineSetPerExport() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <false>
    to be equal to:
     <true>
    but was not.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.opentelemetry.exporters.otlp.OtlpGrpcMetricExporterTest.testExport_DeadlineSetPerExport(OtlpGrpcMetricExporterTest.java:137)
```

Instances:
* https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java/3053/workflows/6a3e0d38-b629-484b-8894-5dfb84b2aaf6/jobs/6193
* https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java/3075/workflows/fbdc466c-b6a2-4009-be4f-a23598504620/jobs/6238
* https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java/3091/workflows/ac503067-8c5c-453d-a597-a21af4ad5305/jobs/6271

**Comment by Oberon00** [comment]
I just had this failure locally.

**Comment by jarebudev** [comment]
i can have a look

**Comment by dengliming** [comment]
[https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java/3097/workflows/c5ef1024-8946-42f2-aad9-477347b20318/jobs/6283](https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java/3097/workflows/c5ef1024-8946-42f2-aad9-477347b20318/jobs/6283)

**Comment by anuraaga** [comment]
Pretty sure this is because of missing `.join` calls when calling export in the tests. Will send something tomorrow if no one else gets to it first.

**Comment by jarebudev** [comment]
> Pretty sure this is because of missing `.join` calls when calling export in the tests. Will send something tomorrow if no one else gets to it first.

I started looking at this yesterday, I assumed it was the ```.join``` too but that didnt resolve it.  I think i've got a solution and will aim to get a PR in later today
