### ISSUE TITLE
Update Jaeger exporter to map Resources to process tags

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1609]
See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/jaeger.md#resource

**Comment by malafeev** [comment]
something like:
```
target.addAllTags(toKeyValues(span.getResource().getAttributes()));
```
?
where `target` is: `Model.Span.Builder` (https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/jaeger/src/main/java/io/opentelemetry/exporters/jaeger/Adapter.java#L74)

**Comment by jkwatson** [comment]
Not sure if there might also need to be some naming tweaks along the way...

**Comment by malafeev** [comment]
yes, so question about names... How to tweak them if needed?

**Comment by jkwatson** [comment]
Probably have to look for certain keys (from the spec) and rename them while writing them into the Model.Span.Builder. I'm not sure if there's a better way.

**Comment by jkwatson** [comment]
@malafeev Rereading the spec, it looks like the resource attributes just get mapped over directly. I was thinking of instrumentation library attributes.
