### ISSUE TITLE
Consider not using private type TracerSdk in public API TracerSdkProvider::get

### ISSUE THREAD

**Issue by quijote** [open-telemetry/opentelemetry-java#1635]
``TracerSdkProvider::get`` is currently defined like this:

    @Override
    public TracerSdk get(String instrumentationName) {
      return tracerSdkComponentRegistry.get(instrumentationName);
    }

It uses covariant return types to return a package private type. 

When I use the API like this:

    OpenTelemetrySdk.getTracerProvider().get("foo");

javac will put the private class name ``TracerSdk`` into my own class. 

Renaming this private class would end up breaking binary compatibility. 

Having the covariant return type here also makes it impossible to instrument ``TracerSdkProvider::get`` with a Java agent in order to return an alternative tracer object when ``TracerSdkProvider::get`` is called in application code.

I therefore suggest to not leak internal details into method signatures of public APIs and instead change the method to

    @Override
    public Tracer get(String instrumentationName) {
      return tracerSdkComponentRegistry.get(instrumentationName);
    }

**Comment by jkwatson** [comment]
Hi @quijote . I understand the concern, but I'm curious why you're using the SDK like this? If you want access to Tracers, you should generally do that via the API, not the SDK classes directly.

**Comment by Oberon00** [comment]
@jkwatson Maybe OpenTelemetrySdk.getTracerProvider() should not exist but instead OpenTelemetrySdk.getTracerProviderConfig() which returns an implemenation of an interface that only has the SDK-only methods. That way clients would be forced to use OpenTelemetry.getTracerProvider if they don't need SDK-specifics.

**Comment by jkwatson** [comment]
> @jkwatson Maybe OpenTelemetrySdk.getTracerProvider() should not exist but instead OpenTelemetrySdk.getTracerProviderConfig() which returns an implemenation of an interface that only has the SDK-only methods. That way clients would be forced to use OpenTelemetry.getTracerProvider if they don't need SDK-specifics.

I like this idea. Do you mind creating an issue for it, so we don't lose track of it?

**Comment by quijote** [comment]
@jkwatson Sorry for the late response. 

I looked at the API not as a user but rather as someone who may or may not want to instrument ``TracerSdkProvider::get`` to replace the returned Tracer with a different object. Whether this is a good idea or not, is a different question. 

But right now, ``TracerSdkProvider::get`` is a public API and some user will call it eventually, even if he should not. I also like the idea by @Oberon00 to entirely get rid of the method.

**Comment by anuraaga** [comment]
Thanks @quijote this seems like a pretty bad bug and we need to fix it. I don't think I see a new related issue so let's go ahead and track here @jkwatson.

I also filed an issue for tooling to prevent this.

**Comment by Oberon00** [comment]
> seems like a pretty bad bug 

I agree, but it is labelled as Feature Request

**Comment by anuraaga** [comment]
Thanks - changed the label :)
