### ISSUE TITLE
Publish an opentelemetry-testing artifact

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1647]
Currently, this would include the TestSpanData implementation, but could be expanded to include more testing utilities.

**Comment by punya** [comment]
https://search.maven.org/artifact/io.opentelemetry/opentelemetry-sdk-testing/0.14.1/jar has been published for the last couple of releases. Should this issue be closed out?

**Comment by jkwatson** [comment]
yes, thanks @punya. closing.
