### ISSUE TITLE
Update Sampling result names

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1648]
Per this spec update: https://github.com/open-telemetry/opentelemetry-specification/pull/938

**Comment by eunice98k** [comment]
Hi, I would like to pick this up! -cc @alolita

**Comment by Oberon00** [comment]
Note that there is an open follow-up PR to rename IGNORE to DROP: https://github.com/open-telemetry/opentelemetry-specification/pull/956

**Comment by jkwatson** [comment]
closing via #1661
