### ISSUE TITLE
Drop Java 7 support for both the API and SDK

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1649]
Let's make the minimum JDK requirement java 8.

**Comment by jkwatson** [comment]
@AloisReitbauer @Oberon00 @thisthat If we /you can create a fork for dynatrace ASAP, we could get this done before GA.

**Comment by Oberon00** [comment]
Duplicate of #1543

**Comment by jkwatson** [comment]
> Duplicate of #1543

Disagree. That issue is about making a decision. This issue is about executing that decision. Dynatrace is the only vendor who has interest in Java 7 support at this point, and out-of-band discussion has indicated that you/they would be amenable to maintaining a Java 7 fork of the project.

**Comment by trask** [comment]
Since Dynatrace is the only vendor that requires Java 7 support in OpenTelemetry, it sounds like creating a Java 7 fork (e.g. https://github.com/open-telemetry/opentelemetry-java7) with Dynatrace folks as maintainers would be a good way forward from this impasse.

Btw, other vendors are planning to support the small number of customers that are still on Java 7 by using the prior generation of their java agent/tracer, not sure if this is an option for Dynatrace as well?

**Comment by danielkhan** [comment]
This was a misunderstanding and Dynatrace will not fork, maintain, and support OTel for Java 7 openly.

**Comment by Oberon00** [comment]
>> Duplicate of #1543
> Disagree. That issue is about making a decision.

You have a point, but then why is the issue for making the decision still open while we already haven an issue for executing a decision? 😉

**Comment by jkwatson** [comment]
> @jkwatson
> 
> > > Duplicate of #1543
> > 
> > 
> > Disagree. That issue is about making a decision.
> 
> You have a point, but then why is the issue for making the decision still open while we already have an issue for executing a decision? 😉

Honestly, it was to force the decision to happen, and make sure that it didn't get stalled, which it was looking like it was.

**Comment by Oberon00** [comment]
Why open a new issue though, instead of commenting on the old one?

**Comment by jkwatson** [comment]
> This was a misunderstanding and Dynatrace will not fork, maintain, and support OTel for Java 7 openly.

So, does this mean Dynatrace is ok with us moving to java 8, or not?

**Comment by Oberon00** [comment]
I commented on #1543.

**Comment by AkshayBabbar** [comment]
hi want to take it this up how to proceed any suggestions.

**Comment by Oberon00** [comment]
Hi, #1665 was already merged, so I don't think there is any immediate action. I hope that a "Java 8 feature using cleanup" or something like that is done *after* #1631.

But @jkwatson is the one that should really answer this 😃

**Comment by jkwatson** [comment]
@AkshayBabbar Yes, this is now done. Closing!
