### ISSUE TITLE
BSP timeout setting not very useful

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1651]
I noticed when trying OTel in an environment with easy timeouts, the BSP timeout setting isn't very useful - you have to additionally tweak the timeout of the exporter too. Not sure if we want to remove it, or have it automatically computed based on other values, both seem to have caveats, but IMO either is still better than someone setting BSP timeout and have it not actually fix timeout issues.

**Comment by jkwatson** [comment]
This has always been a difficult nut to crack. The specs say we need a timeout, but the timeout doesn't really mean much if the exporter isn't playing along, and we can't control arbitrary exporters and how they deal with the timeouts. And, with crappy java io blocking, we're even at the mercy of the networking mode being used (old io vs. nio).

I don't think there's a perfect answer here. What ideas did you have around having "it automatically computed based on other values"?

**Comment by anuraaga** [comment]
@jkwatson "it automatically computed based on other values". If exporters had a method like `getTimeout()`, BSP could read it. It's pretty gross, hence caveats ;)

The other idea I just had, which might be a spec change, is to have only one "default timeout" parameter the `TracerProvider`. It's BSP and exporter's job to read that value if a user didn't provide one exporter-specific, and implement a timeout. A default timeout being a global concern seems to make sense though.

**Comment by kenfinnigan** [comment]
@jkwatson pointed me at this after I commented that a timeout for BSP could be set lower than the timeout on `JaegerGrpcSpanExporter` and whether there was a way to validate/prevent such a situation. Though `autoconfiguration` can validate the timeouts, it doesn't help anyone not using it.

From a quick perusal of the spec, it looks like "export timeout" is only defined for `SpanProcessor`. Implying, for me, that `SpanProcessor` should control the timeout for export, and any `SpanExporter` should utilize that timeout and not create their own.

Could this be implemented by having an `AbstractSpanExporter`, and all `SpanExporter` implementations extend it, in the SDK which implements a `setTimeout()` so the BSP Builder can call it during construction? Having `AbstractSpanExporter` prevents the need for a public method on `SpanExporter`, not sure if there's precedent for such an approach.
