### ISSUE TITLE
Opentelemetry-exporter-zipkin: Trace_id & span_id duplicated

### ISSUE THREAD

**Issue by geppetto89** [open-telemetry/opentelemetry-java#1677]
**Describe the bug**
Using OpenTelemetry java and Zipkin as exporter and backend there are different events sharing the same traceId and spanId which are supposed to be unique 

**Steps to reproduce**
Generate and export different spans and use Zipkin as exporter then
 search for duplicated span_id & trace_id on zipkin console or google cloud

**What version and what artifacts are you using?**
OpenTelemetry java : v0.8
Client : Android mobile app

As an example we got this output (we removed the other fields used for tracking)
[
  {
    "spanId": "efaa1ba7afa7282f",
    "startTime": "2020-09-21 07:22:39.302012 UTC",
    "endTime": "2020-09-21 07:22:39.354814 UTC",
    "traceId": "defdc307b8b7ef2e7fd064e9daea18e0"
  },
  {
    "spanId": "efaa1ba7afa7282f",
    "startTime": "2020-09-21 15:55:27.968005 UTC",
    "endTime": "2020-09-21 15:55:27.969261 UTC",
    "traceId": "defdc307b8b7ef2e7fd064e9daea18e0"
  },
  {
    "spanId": "efaa1ba7afa7282f",
    "startTime": "2020-09-21 15:46:40.428011 UTC",
    "endTime": "2020-09-21 15:46:40.513071 UTC",
    "traceId": "defdc307b8b7ef2e7fd064e9daea18e0"
  },
  {
    "spanId": "efaa1ba7afa7282f",
    "startTime": "2020-09-21 15:47:01.656005 UTC",
    "endTime": "2020-09-21 15:47:01.681474 UTC",
    "traceId": "defdc307b8b7ef2e7fd064e9daea18e0"
  },
  {
    "spanId": "efaa1ba7afa7282f",
    "startTime": "2020-09-21 15:53:59.870006 UTC",
    "endTime": "2020-09-21 15:54:00.031606 UTC",
    "traceId": "defdc307b8b7ef2e7fd064e9daea18e0"
  },
  {
    "spanId": "efaa1ba7afa7282f",
    "startTime": "2020-09-21 14:16:39.940005 UTC",
    "endTime": "2020-09-21 14:16:40.003827 UTC",
    "traceId": "defdc307b8b7ef2e7fd064e9daea18e0"
  }
]

<img width="1509" alt="Screen Shot 2020-09-22 at 16 22 57" src="https://user-images.githubusercontent.com/11004926/93910305-31c4d800-fd01-11ea-8726-d0674a4d3630.png">

Could it be similar to https://github.com/open-telemetry/opentelemetry-python/issues/981 ?

**Comment by jkwatson** [comment]
@geppetto89 I believe that Android's implementation of ThreadLocalRandom is buggy on some versions of Android. To fix this, I believe you'll need to provide a custom `io.opentelemetry.sdk.trace.IdGenerator` implementation that works on Android.

**Comment by aresares** [comment]
I noticed the same problem also in java. I get conflicting traceId. Any sugestion on how to fix this or set customs traceId ?

**Comment by jkwatson** [comment]
@aresares and I have been discussing this on gitter, and his issue is not the same, but is do to some problems with not closing the thread-local Scope, hence leaking span contexts across threads in his framework.

**Comment by jkwatson** [comment]
closing this, as it's a known issue with Android and can be solved by installing a custom IdGenerator into the SDK.
