### ISSUE TITLE
Prometheus Push-based MetricExporter

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#1687]
**Is your feature request related to a problem? Please describe.**

* use p8s metric exporter in short lived instances
* use the p8s metric exporter in Java agent: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/385

**Describe the solution you'd like**

MetricExporter implementation for prometheus. 

**Describe alternatives you've considered**

Use push model in OTEL agent.

**Additional context**

This is created from https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/385

**Comment by jkwatson** [comment]
@pavolloffay are you looking for something different than we already have?  https://github.com/open-telemetry/opentelemetry-java/blob/8e61e8d217c6ee5ad9c82a75b7ddddaf94334856/exporters/prometheus/README.md#L1

**Comment by pavolloffay** [comment]
Can be the current p8s exporter used with push-based model?

**Comment by jkwatson** [comment]
> Can be the current p8s exporter used with push-based model?

I don't believe so, no. Is this issue for a push-based model? It's not clear from the description.

**Comment by jack-berg** [comment]
Closing this because [prometheus](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/prometheus.md) export specification explicitly says we "MUST NOT support push mode". If the spec changes we can revisit.
