### ISSUE TITLE
Update allowed span status codes 

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1700]
See this recent spec PR:  https://github.com/open-telemetry/opentelemetry-specification/pull/966

**Comment by carlosalberto** [comment]
Hey @jkwatson 

This is for specifying the actual numerical values, right? I.e. 0, 1, etc.

**Comment by jkwatson** [comment]
No, this was just to reduce down to the 3 Status values, from the existing 16. Although, having clarification on the numeric codes would also be useful. :)
