### ISSUE TITLE
class file for com.google.auto.value.AutoValue not found

### ISSUE THREAD

**Issue by marcingrzejszczak** [open-telemetry/opentelemetry-java#1702]
Adding

```xml

			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-api</artifactId>
				<version>0.8.0</version>
			</dependency>
```

to the POM results in the following error in the compilation of a project

```
class file for com.google.auto.value.AutoValue not found
```

**Comment by jkwatson** [comment]
That's odd. Our examples module depends on API release 0.8.0 and doesn't have this issue. Also, I just tried creating a clean maven project and I don't see this. Can you share your maven build script?

**Comment by jkwatson** [comment]
@marcingrzejszczak any update?

**Comment by marcingrzejszczak** [comment]
I can't replicate it neither anymore. Let's close this.
