### ISSUE TITLE
Rename AttributesKeys to AttributeKeys

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1710]
Or probably you are planning to move those creation methods directly into the AttributeKey interface now with Java 8 👍

**Comment by jkwatson** [comment]
oh wow. that's a major typo! Shame on me (and everyone who reviewed it and didn't catch it!) And, yes, I was also thinking of moving all of those methods to the AttributeKey now that we can. I prefer that.

**Comment by imavroukakis** [comment]
Hello 😃 Will this do the trick? https://github.com/open-telemetry/opentelemetry-java/pull/1743
