### ISSUE TITLE
Is there any way to avoid (long) cast when setting NET_PEER_PORT?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1711]
I've been updating to the new attribute keys, and they are very nice!

The only (very small) issue is having to cast to long (nearly) every time we call:

```
span.setAttribute(SemanticAttributes.NET_PEER_PORT, (long) port);
```

Not sure if it's worth adding `AttributeKey<Integer>`, or if spec even supports doing that, or maybe there's some other clever solution?

If no good solution, feel free to close this.

**Comment by jkwatson** [comment]
We could easily add an overload to the span (and friends) that takes an `int` in addition to the `long`, and does the cast for you. That seems like an easy addition that wouldn't break anything. Thoughts?

**Comment by anuraaga** [comment]
Seems like a nice idea :)
