### ISSUE TITLE
Link should be implemented in Span, not SpanData

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1714]
While working on #1712 I found it very surprising to find `Link` only really exists as part of `SpanData`. I think the span data model should be implemented without being conjoined to `SpanData`, an export concept.

**Comment by jkwatson** [comment]
@anuraaga do you still think it's important to have a `Link` interface in the API at this point?

**Comment by anuraaga** [comment]
Nope think this is fine
