### ISSUE TITLE
Tooling to prevent returning private type from public method

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1718]
We currently return a private type, `TracerSdk` from a public method in a public class. This specific issue needs to be fixed, but we should have tooling to prevent it in the first place since it's never a good idea. I've seen broken releases before because unit tests passed but the end user couldn't even use the new API if they tried.

Not sure but I think even the javadoc tool can confirm this and we're probably missing it since we disable javadoc warnings.

**Comment by Oberon00** [comment]
We have some test using ArchUnit, maybe that tool could be used?

**Comment by Oberon00** [comment]
Caused by: https://github.com/open-telemetry/opentelemetry-java/issues/1635#issuecomment-699964326

**Comment by jkwatson** [comment]
Also true for the Meter side of the equation at the moment, just FYI.
