### ISSUE TITLE
Add a OpenTelemetry BOM

### ISSUE THREAD

**Issue by marcingrzejszczak** [open-telemetry/opentelemetry-java#1719]
It would be much easier to just import an OpenTelemetry BOM with one version and then only reference the projects without setting their versions.

```xml
<dependencyManagement>
  <dependencies>
			<dependency>
				<groupId>io.opentelemetry<groupId>
				<artifactId>opentelemetry-bom</artifactId>
				<version>${opentelmetry.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
  </dependencies>
</dependencyManagement>
```

and then just use the proper dependencies like this

```xml
<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-api</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-sdk</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-exporters-logging</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-sdk-extension-jaeger-remote-sampler</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-sdk-extension-async-processor</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-extension-trace-utils</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-exporters-prometheus</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-exporters-zipkin</artifactId>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-exporters-trace-propagators</artifactId>
			</dependency>
```

**Comment by anuraaga** [comment]
Yup definitely - I think this should be fixed in #1626 but we haven't verified that yet in a maven central release which I think will happen this week.

**Comment by jkwatson** [comment]
Yes, this was supposed to be done long, long ago, and apparently wasn't working as designed; as @anuraaga mentioned, it should have been fixed with #1626 . 🤞  that it will work and we can close this.

**Comment by anuraaga** [comment]
BOM appears to be up - thanks for the patience @marcingrzejszczak 

https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-bom/0.9.1/

**Comment by asarkar** [comment]
@anuraaga `io.opentelemetry.instrumentation:opentelemetry-grpc-1.5` isn't in the BOM.

**Comment by jkwatson** [comment]
> @anuraaga `io.opentelemetry.instrumentation:opentelemetry-grpc-1.5` isn't in the BOM.

The BOM in question for this issue is for the API and SDK and extensions, not for the instrumentation repository, which is a different project over here: https://github.com/open-telemetry/opentelemetry-java-instrumentation

**Comment by asarkar** [comment]
@jkwatson Then are we missing an instrumentation bom?

**Comment by jkwatson** [comment]
> @jkwatson Are we missing an instrumentation bom then?

No clue. I think you'd need to ask over in the instrumentation project. :)
