### ISSUE TITLE
Should SDK configure default propagators?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1742]
The default propagator is now no-op, even in the presence of the SDK, which adds an additional configuration step for users.

Reading comments in https://github.com/open-telemetry/opentelemetry-specification/pull/930#discussion_r485769679 it seems that it would be ok for the SDK to configure default propagators:

> And for clarity purposes: I think any component should be able to override the default values (ASP.NET, SDK, etc).

Alternatively, if the SDK does not configure default propagators, the quick start docs probably need updating to mention how to configure them.

**Comment by jkwatson** [comment]
I agree it would make sense to have the SDK configure the HttpTraceContext propagator by default. (and Baggage when that is available).

**Comment by kenfinnigan** [comment]
+1, was just hit by this issue in updating some code.

Which was even more confusing given the javadoc on `OpenTelemetry.getPropagators()` implying it's not a no-op: https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/OpenTelemetry.java#L147

**Comment by carlosalberto** [comment]
Assigning this to me as I will work on this next week.

**Comment by jkwatson** [comment]
This is done by the autoconfigure module now, which is probably the appropriate place to have this defaulted. Closing this.
