### ISSUE TITLE
Consider compile-time checking of @Nullable and @Nonnull

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1768]
We currently have some nullability annotations in the code, but don't really check them. Errorprone only provides some very basic checks (like ReturnMissingNullable) out of the box. We may consider using additional tooling to check this more strictly, e.g. https://github.com/uber/NullAway might be usable.

**Comment by anuraaga** [comment]
Yup I definitely think we should add this. Recently added it to java-instrumentation build

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1203

**Comment by breedx-splk** [comment]
Since #3668 was merged I think we should close this issue. 
What do you think @Oberon00 and @anuraaga ?

**Comment by anuraaga** [comment]
Thanks - will close with 3845
