### ISSUE TITLE
Rename SpanContext to SpanReference

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1801]
See this recent spec change:  https://github.com/open-telemetry/opentelemetry-specification/pull/1075

**Comment by jkwatson** [comment]
There was a comment in today's maintainer meeting to hold off on this for a bit until the spec group can do some ruminating on it.

**Comment by carlosalberto** [comment]
Closing this as https://github.com/open-telemetry/opentelemetry-specification/pull/1127 was merged.
