### ISSUE TITLE
MetricsProcessor

### ISSUE THREAD

**Issue by as-polyakov** [open-telemetry/opentelemetry-java#1810]
**Is your feature request related to a problem? Please describe.**
Similar to SpanProcessor, we need a hook for metrics which would allow users to intercept metrics lifecycle eventы with their own logic.

**Describe the solution you'd like**

```
public interface MetricsProcessor {

  /**
   * Called when bind() method is called. Allows to manipulate labels which this
   * instrument is bound to. Particular use case includes enriching lables and/or adding more labels
   * depending on the Context
   * @param ctx context of the operation
   * @param descriptor instrument descriptor
   * @param labels immutable labels. When processors are chained output labels of the previous one is passed as
   * an input to the next one. Last labels returned by a chain of processors are used for bind() operation.
   * @return labels to be used as an input to the next processor in chain or bind() operation if this is the last processor
   */
    Labels onLabelsBound(Context ctx, InstrumentDescriptor descriptor, Labels labels);

  /**
   *  Called when .record() method is called. Allows to manipulate recorded value. When chained input of the next
   *  call is the output of the previous call. Final output is recorded
   * @param ctx context of the operation
   * @param descriptor instrument descriptor
   * @param labels immutable labels. When processors are chained output labels of the previous one is passed as
   * @param value recorded value
   * @return value to be used as an input to the next processor in chain or record() operation if this is the last processor
   */

    long onLongMeasurement(Context ctx, InstrumentDescriptor descriptor, Labels labels, long value);

    double onDoubleMeasurement(Context ctx, InstrumentDescriptor descriptor, Labels labels, double value);
}
```

**Describe alternatives you've considered**
Main problem I am trying to address - is to be able to add certain labels to metrics depending on Context (i.e. dynamically). One alternative can be to just do that and make it a standalone feature aka "sticky labels". Had a simple PR for this [here](https://github.com/parallelstream/opentelemetry-java/pull/1). However MetricsProcessor is a more generic solution which can address other use cases.
As for the implementation, instead of using immutable Labels we can pass ReadWriteLables object, this would make it follow the same patter as in SpanProcessor

**Additional context**
There's a problem with this approach - statically bound instruments will not be able to dynamically add labels during record operation. Since we only intercept onLabelsBound() in case one statically binds an instrument and then uses that to record multiple measurements with different contexts, only first bind call will be intercepted

**Comment by jkwatson** [comment]
Hi @parallelstream . Thanks for this suggestion. I think it is a good one, but I think that this is something that should be specified cross-language. Can you open up an issue in the specs to start the discussion there? Just as a heads-up, the specs folks might ask for an OTEP to track this, since it's a significant change to the standard metrics SDK implementation.

In addition, we generally like to see draft PRs in several languages with a rough implementation to go along with the spec issue. Would you be willing to do that prototyping work, as well?

Thanks!

**Comment by parallelstream** [comment]
sure, will do both, @jkwatson

**Comment by parallelstream** [comment]
Opened the one together with PR here https://github.com/open-telemetry/opentelemetry-specification/issues/1116

**Comment by jkwatson** [comment]
@as-polyakov can we close this issue now that we have the ability to deal with labels in views?

**Comment by as-polyakov** [comment]
resolved
