### ISSUE TITLE
Add a way to enforce default context storage implemenation

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1818]
**Is your feature request related to a problem? Please describe.**
For example in an auto-instrumenting agent, we do not want the Context implementation to scan for user-provided SPIs that may or may not work as expected with our agents. But there is not way to enforce the default thread local storage (for example, there is no provider class for the default storage).

Relevant code is in this function: https://github.com/open-telemetry/opentelemetry-java/blob/fa1e876df20910ca5ec3d43a788f2bcf35013d68/context/src/main/java/io/opentelemetry/context/LazyStorage.java#L39

**Describe the solution you'd like**
The simplest solution would be to add a special name like `default` that is accepted for the `io.opentelemetry.context.contextStorageProvider` system property.

**Describe alternatives you've considered**
One could add a Provider implementation returning the default context manually and specify the name of that. However, this is quite a bit of boilerplate and non-obvious.

**Comment by Oberon00** [comment]
Related: #1819 "If there is only one ContextStorageProvider, the system property is ignored without warning"

**Comment by dengliming** [comment]
What if we provide another System property name like( `io.opentelemetry.context.contextStorageProvider.spi.enable` or `io.opentelemetry.context.contextStorageProvider.enforceDefault`)  to enforce it (not `io.opentelemetry.context.contextStorageProvider`) using default context storage implemenation?  Is that more obvious?

**Comment by anuraaga** [comment]
I think one variable with `default` sounds fine to me. It prevents the use of `default.java` as a provider, but that's a very small limitation. Instead we get just one property we have to explain.

**Comment by dengliming** [comment]
@anuraaga Hey~ So you mean we can just accept `default `  for the io.opentelemetry.context.contextStorageProvider system property?
