### ISSUE TITLE
If there is only one ContextStorageProvider, the system property is ignored without warning

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1819]
**Describe the bug**
(Note: This bug report comes only from looking at the code, I did not try to actually reproduce it)

The following conditions must be fulfilled:
1. The `io.opentelemetry.context.contextStorageProvider` system property is set
2. There is exactly a single provider found by `ServiceLoader.load(ContextStorageProvider.class)`
3. The found provider is not the one requested by the system property.

Relevant code: https://github.com/open-telemetry/opentelemetry-java/blob/fa1e876df20910ca5ec3d43a788f2bcf35013d68/context/src/main/java/io/opentelemetry/context/LazyStorage.java#L51-L54

**Steps to reproduce**
Obvious from description.

**What did you expect to see?**
1. A warning message that the requested provider could not be found.
2. The default implementation should be used instead of the one of the provider. (This point is debatable.)

**What did you see instead?**
1. No message at all.
2. The single, found provider was used.

**Comment by dengliming** [comment]
> The default implementation should be used instead of the one of the provider. (This point is debatable.)

@jkwatson Can you confirmed this?

**Comment by jkwatson** [comment]
> > The default implementation should be used instead of the one of the provider. (This point is debatable.)
> 
> @jkwatson Can you confirm this?

I'm not sure what the right behavior is. I'll defer to @anuraaga on this one.

**Comment by anuraaga** [comment]
@dengliming Thanks for the help! I think using the default after logging makes sense.
