### ISSUE TITLE
Original license headers are missing for context package.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1820]
In the PR description of #1658:

> The API is heavily inspired by gRPC and Armeria. Much code / docs are borrowed too and I kept license headers in tact to reflect that.

which is sensible and actually required by the OTel/CNCF policy:

> According to CNCF recommendations if you are contributing third-party code you will need to retain the original copyright notice.

-- https://github.com/open-telemetry/community/blob/master/CONTRIBUTING.md#copyright-notices

However, the statement from the PR description is unfortunately, wrong there is only the OTel license. Maybe the original license header got killed by spotlessApply.

CC @anuraaga

**Comment by Oberon00** [comment]
As it is now, e.g. the PersistentHashArrayMappedTrie.java file has no indication whatsoever that it is a 1:1 copy & paste from grpc-context. Knowing that would have eased my mind about the battle-testedness of this rather complicated code considerably 😃

**Comment by anuraaga** [comment]
@iNikem I came up with a workaround for it but think I didn't merge that into the branch, let me show it in a bit :)
