### ISSUE TITLE
Rename Context.withValues to Context.with

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1825]
I mostly copied the name `withValues` from grpc context, but a Context can't be with anything but a value. How about just `with`?

I think this could be applied to others too, `set` instead of `setAttribute` for example and we should if we think this is in general a good idea.

**Comment by jkwatson** [comment]
No strong opinion here from me. I'm fine with what we have now, but wouldn't be opposed to a pre-GA change if enough people were willing to make it happen, quickly.
