### ISSUE TITLE
Jaeger exporter example is not working

### ISSUE THREAD

**Issue by ChandrewR** [open-telemetry/opentelemetry-java#1826]
Jaeger is not working. The service - example as mentioned in code is not getting listed in Jaeger after running the application.

**Steps to reproduce**
Follow the README.MD file
Install Jaeger - docker run --rm -it --name jaeger -p 16686:16686 -p 14250:14250 jaegertracing/all-in-one:1.16
Run Java app - java -cp build/libs/opentelemetry-examples-jaeger-all-0.1.0-SNAPSHOT.jar io.opentelemetry.example.JaegerExample localhost 14250

**What I expect to see?**
After the running above commands - Service - example with traces should be listed in Jaeger. But its not

**What I see instead?**
Service - example is not listed in Jaeger.

**What version and what artifacts?**
dependencies {
    compile("io.opentelemetry:opentelemetry-api:${opentelemetryVersion}")
    compile("io.opentelemetry:opentelemetry-sdk:${opentelemetryVersion}")
    compile("io.opentelemetry:opentelemetry-exporters-jaeger:${opentelemetryVersion}")
    compile("io.grpc:grpc-protobuf:1.28.0")
    compile("io.grpc:grpc-netty-shaded:1.28.0")
}

**Environment**
Compiler: (e.g., "Java 1.8.0_241")
OS: (e.g., "Windows 10")
Runtime (if different from JDK above): (e.g., "Java 1.8.0_241")

Followed the steps metioned in README.md but not working. Please help on this.

**Comment by jkwatson** [comment]
Hi @ChandrewR . I just tried this locally and it's working fine for me. Can you tell me more about your environment, and whether you see anything interesting in the docker or console logs?

**Comment by ChandrewR** [comment]
Hi @jkwatson , No I don't see any error in console logs..My Jaeger UI is running just fine and showing jaeger-query service. But its not showing the example service which we export from Java sample app.

Below are the logs for your reference.

![Jaeger - Docker](https://user-images.githubusercontent.com/26222838/96706398-29b99000-13b4-11eb-9c4a-757086129da8.PNG)
![Jaeger - Java APP](https://user-images.githubusercontent.com/26222838/96706424-31793480-13b4-11eb-8b70-29ea07a764c6.PNG)
![Jaeger UI](https://user-images.githubusercontent.com/26222838/96706425-3211cb00-13b4-11eb-949c-dd60174ea216.PNG)

Please help on this.

**Comment by jkwatson** [comment]
Hi @ChandrewR . I dug deeper and was able to reproduce the issue, both on the latest release and the main branch. Thanks for the report! No solution yet, but it's a high priority to get it fixed.

**Comment by jkwatson** [comment]
@ChandrewR I've been playing around and it seems like it works if the example is tweaked to send more than a single span. I'm guessing there's just not quite enough time for things to work quite right. We'll get the example fixed so that it works out of the box. Thanks again for the report!

**Comment by jkwatson** [comment]
@ChandrewR this fix seems to get the spans into Jaeger for me reliably:  #1847
