### ISSUE TITLE
Using the tracing SDK module on its own has some usability issues

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1834]
The trace SDK needs to be configured using the `TracerSdkManagement` interface (e.g. to add a span processor). However, this is only possible with the `OpenTelemetrySdk` class https://github.com/open-telemetry/opentelemetry-java/blob/fbfba341349379e423affdc965e79071b41c3372/sdk/all/src/main/java/io/opentelemetry/sdk/OpenTelemetrySdk.java#L31-L32 which is in opentelemetry-sdk-all and depends on all other SDK componentes. One cannot even cast the return value of `OpenTelemetry.getTracerProvider()` to `TracerSdkManagement` due to the internal `Obfuscated` class (which is good in it itself).

**Comment by Oberon00** [comment]
IMHO this would best be fixed by removing the OpenTelemetrySdk and splitting it up into one separate class per module.

**Comment by anuraaga** [comment]
@Oberon00 What do you think about continuing to depend on the SDK but excluding the dependencies you don't want with gradle / maven exclusions? I think that should already work, though I haven't tried it.

I think having `OpenTelemetrySdk` should be fine still to manage shared SDK concerns like `Resource`, but we can probably also add individual accessors in each module if that seems like better UX. But I guess when wanting to trim dependencies, dependency exclusion is relatively idiomatic? Not sure just food for thought :)

**Comment by Oberon00** [comment]
> excluding the dependencies you don't want with gradle / maven exclusions

That cannot work. This is not merely a compile-time dependency declaration problem. If I load the OpenTelemetrySdk, class it *will* reference the baggage classes so a NoClassDefFound error will be thrown I think.

**Comment by anuraaga** [comment]
@Oberon00 Java is suprisingly lazy :) Classes shouldn't be loaded until they're used. Definitely adding examples for partial SDK usage is on my list of follow up PRs with #1857 - my plan is for this to work fine even with dependencies excluded. If I find something wrong will fix it :) 

`OpenTelemetrySdk.builder().setTracerProvider(TracerSdkProvider.builder().build()).setMeterProvider(DefaultMeterProvider.getInstance()).build()`

**Comment by Oberon00** [comment]
OK this still is dirty. If I accidentally call OpenTelemetrySdk.getMeterProvider, the compiler will not warn me but it will fail at runtime, right? Besides, what is the benefit of having a shared class here over one class per module?

**Comment by anuraaga** [comment]
I think it makes the vastly common case of using the whole SDK simpler, one builder to configure the shared features like resource, propagators. We can return a nice error if we detect usage of the SDK method when not available (we sort of do right now) and I think this is relatively conventional. 

However for the case where you really don't want the `OpenTelemetrySdk`, it should still be possible to use `DefaultOpenTelemetry` too instead once it's public - so I'm expecting landing somewhere nice. I'm glad OpenTelemetry is an interface now I think it gives us much more flexibility for this issue :)

**Comment by Oberon00** [comment]
Anyway, from what you said it seems that this is actually possible with some care, so this issue should be re-labeled a feature request to make this easier and/or document it better.

**Comment by jkwatson** [comment]
@Oberon00 Is this still an issue with the changes we've made to the SDK Builder and turning OpenTelemetry into an interface? If so, can you provide a unit test that exposes the issue, because it feels like there are a bunch of things going on here, and it's not clear to me whether we've addressed it or not already.

**Comment by Oberon00** [comment]
Trying to test this, I added this test to the sdk-tracing tests:

```java
  @Test
  public void testApiDefault() {
    OpenTelemetry.set(null);
    try {
      assertThat(OpenTelemetry.getGlobalTracerProvider())
          .isExactlyInstanceOf(TracerSdkProvider.class);
    } finally {
      OpenTelemetry.set(null);
    }
  }
```

But this fails because the sdk-tracing test transitively depend on sdk-all via sdk-testing and I get an obfuscated tracer provider. This is a bit annoying because it can easily break code that was made with depending just on the SDK. As recommended in the above comment, I next tried to set this explicitly, but it seems `DefaultOpentelemetry.builder()` is package-private. Thus I needed to resort to

```java
OpenTelemetry.set(
        new DefaultOpenTelemetry(
            TracerSdkProvider.builder().build(),
            MeterProvider.getDefault(),
            ContextPropagators.create(HttpTraceContext.getInstance())) {});
```

(note this creates an anonymous inner class because the constructor is protected).

While this "works" it disables the SPI logic completely, also e.g. for MeterProvider.

Is it intentional that `DefaultOpenTelemetry.builder()` is package-private?

**Comment by jkwatson** [comment]
> Is it intentional that `DefaultOpenTelemetry.builder()` is package-private?

I think we should make this public, or maybe better, expose a method on the `OpenTelemetry` instance to get a handle to it. This just got lost when we deprecated the `toBuilder()` method.
