### ISSUE TITLE
Span.setAttribute should return `this` to enable chain calls.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1864]
**Describe the solution you'd like**
I want to be able to use `mySpan.setAttribute(MY_KEY, "foo").setAttribute(OTHER_KEY, 42).end()` instead of `mySpan.setAttribute(MY_KEY, "foo"); mySpan.setAttribute(OTHER_KEY, 42); mySpan.end()`.

More often than not, you set multiple attributes at once. SpanBuilder already allows this.

**Comment by dengliming** [comment]
👍 I am willing to take this.
