### ISSUE TITLE
method getSpanContext(): error: cannot find symbol

### ISSUE THREAD

**Issue by jl0x61** [open-telemetry/opentelemetry-java#1877]
**Describe the bug**
I want to print the traceid and spanid of a `span` object. I added 
```java
import io.opentelemetry.trace.SpanContext;
```
and 
```java
SpanContext spancontext = span.getSpanContext();
```
in [JaegerExample.java](https://github.com/open-telemetry/opentelemetry-java/blob/master/examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java).
But this error occurs:
```
> Task :opentelemetry-examples-jaeger:compileJava FAILED
/root/opentelemetry-java/examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java:65: error: cannot find symbol
      SpanContext spancontext = span.getSpanContext();
                                    ^
  symbol:   method getSpanContext()
  location: variable span of type Span
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':opentelemetry-examples-jaeger:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 794ms
1 actionable task: 1 executed

```

**Steps to reproduce**
add
```java
import io.opentelemetry.trace.SpanContext;
```
and 
```java
SpanContext spancontext = span.getSpanContext();
```
in [JaegerExample.java](https://github.com/open-telemetry/opentelemetry-java/blob/master/examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java) and build.
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
build success.
A clear and concise description of what you expected to see.

**What did you see instead?**
```
cannot find symbol
      SpanContext spancontext = span.getSpanContext();
                                    ^
```
A clear and concise description of what you saw instead.

**What version and what artifacts are you using?**
```
opentelemetryVersion = "0.9.1"
compile("io.opentelemetry:opentelemetry-api:${opentelemetryVersion}")
compile("io.opentelemetry:opentelemetry-sdk:${opentelemetryVersion}")
compile("io.opentelemetry:opentelemetry-exporters-jaeger:${opentelemetryVersion}")
```
Artifacts: (e.g., `opentelemetry-api`, `opentelemetry-sdk`, which exporters, etc)
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)

**Environment**
Compiler: openjdk version "1.8.0_265" (e.g., "AdoptOpenJDK 11.0.6")
OS: Ubuntu 20.04 (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**
Any help will be appreciated.

**Comment by jkwatson** [comment]
In 0.9.1 the method is `span.getContext()`. In 0.10.0, this has renamed to `getSpanContext()`.

**Comment by jl0x61** [comment]
> In 0.9.1 the method is `span.getContext()`. In 0.10.0, this has renamed to `getSpanContext()`.

Thanks!
