### ISSUE TITLE
Traceparent header constant

### ISSUE THREAD

**Issue by mariusioana** [open-telemetry/opentelemetry-java#1885]
Hi,

A very simple question :)

Is there any way to get from the open telemetry java sdk the "traceparent" header name as a constant? Traceparent header is not among the common headers list inside a framework that we use and we need to whitelist it so that it goes further to downstream services. Of course, we can whitelist it by just using the "traceparent" string but wondered if there is any way to abstract it and get it from the SDK. I see HttpTraceContext having it as TRACE_PARENT but with package access level. We do not want to extract and do extra processing for now, we just want to let it pass through.

Thanks!

**Comment by jkwatson** [comment]
Hi @mariusioana . the "traceparent" header is part of the W3C trace context specification, so I would guess that it would be a good thing to put onto the allow-list generally. I'd also be fine if we wanted to make that constant public in the `HttpTraceContext` class, if that would be helpful.

**Comment by mariusioana** [comment]
Thanks @jkwatson ! Making it public in HttpTraceContext would be a small thing but would be helpful at least for us.

**Comment by Oberon00** [comment]
Don't forget the `tracestate` header that should always be kept together with `traceparent`.

**Comment by dengliming** [comment]
@mariusioana Seems `fields() `  is good for you. Can we close this?

**Comment by mariusioana** [comment]
Sure thing! Thanks!
