### ISSUE TITLE
Consider moving the SPI interfaces out of the .api. package hierarchy

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1897]
Since they are, in part, the contract between API and SDK, it probably makes sense to have them in their own `io.opentelemetry.spi` package, in neither the API or SDK from a package perspective.

**Comment by breedx-nr** [comment]
I can take this one.  We want a new module and artifact, right?

**Comment by kenfinnigan** [comment]
@breedx-nr, @jkwatson has already submitted a PR for this issue: https://github.com/open-telemetry/opentelemetry-java/pull/2005

**Comment by jkwatson** [comment]
Mine doesn't make them into a separate artifact, though. Not sure if that would be valuable for anyone or not.

**Comment by breedx-nr** [comment]
@kenfinnigan Whoops, missed it.  Thanks for clearing me up.
