### ISSUE TITLE
Merge context_prop into context?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1917]
context_prop is a lonely package which can be confusing vs our context package. I think it makes sense to merge it into context, similar to how the spec groups them into one folder

https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/context

How does that sound?

**Comment by Oberon00** [comment]
I was going to say, I think if Context is meant to be used independently of observability, we should keep it separate from the context_prop. But after looking at the context_prop package, it is small and dependency-free and not really related to observability, so it may be a good idea actually. That would mean keeping it that way (especially dependency-free) in the future though.

**Comment by carlosalberto** [comment]
I think it's fine to do it (as long as we keep the paradigm of keeping `Context` independent of the observability bits).

**Comment by jkwatson** [comment]
Either into context, or into the api itself. Either way is fine with me.

**Comment by carlosalberto** [comment]
> Either way is fine with me.

Oh, I hadn't considered the option of moving `context_prop` into the API. In that case we simplify our lives, but is it worth putting the `Propagator` API in the `Context` API, for general users to leverage? My bet is a soft **yes**.

**Comment by anuraaga** [comment]
Yeah treating remote and local propagation as the same concept seems to make sense to me so also soft yes so going for it!
