### ISSUE TITLE
Do we need EntryMetadata class?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1932]
I'm trying to understand the `EntryMetadata` class. It says it's an opaque wrapper for a string metadata - but it actually exposes the string with `getValue` so isn't quite opaque. Is there anything special we'll add in the future or could it just be a string to reduce the number of concepts?

https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/api/baggage/EntryMetadata.java

**Comment by jkwatson** [comment]
The idea is that the W3C might assign semantic meaning to the contents of the metadata field in the future. By having a wrapper class, we can add methods to that class the expose the semantic meaning without it being a backward incompatible change.

**Comment by anuraaga** [comment]
Cool let's leave it then. Might send a PR to remove the word opaque from the javadoc since that threw me off a bit
