### ISSUE TITLE
Consider dropping guava from core SDK dependencies

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1944]
Guava is a rather big dependency (size-wise) and the usages in the SDK are rather trivial. At Dynatrace we managed to replace Guava with core Java 7 standard library with little effort in our internal fork of opentelemetry-java. With Java 8, it should be even easier to achieve this.

The advantage would be that the deployment size shrinks considerably (for the core SDK + depenendencies probably by at least 80%). This could be important for size-sensitive deployment environments such as AWS lambda.

**Comment by anuraaga** [comment]
Luckily it's not in the API so we can take some time on this, but agree (was going to bring it up at some point myself).

**Comment by jkwatson** [comment]
closing this. we no longer depend on guava transitively in the SDK. Please re-open if you see further work to be done.
