### ISSUE TITLE
Consider to rename the "sdk-tracing" artifact to "sdk-trace" to match package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1948]

**Comment by Oberon00** [comment]
I would prefer the opposite, also in the spec. A trace us a group of spans.

**Comment by bogdandrutu** [comment]
Sure, any consistency is good :)) But I think we should follow the specs https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/library-layout.md

**Comment by bogdandrutu** [comment]
Please consider to open a PR for specs if you feel you have good arguments. But for the moment this is inconsistent and needs to be changed

**Comment by Oberon00** [comment]
@bogdandrutu I created https://github.com/open-telemetry/opentelemetry-specification/pull/1166

**Comment by bogdandrutu** [comment]
@Oberon00 to clarify if the proposal does not get accepted in the specs you are ok to rename the artifact correct? I do understand the preferences, but want to make sure we agree on the consistency

**Comment by Oberon00** [comment]
Yes, I think that would make sense then.

**Comment by jkwatson** [comment]
sounds like we should make this change ASAP because it is a significant breaking change to someone who is consuming the artifact directly.
