### ISSUE TITLE
Move Labels to metrics package

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1959]
Labels are defined in metrics folder in the spec

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md

unlike Attributes which are indeed in common

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md

Should we move Labels to the metrics package?

**Comment by bogdandrutu** [comment]
My opinion is to not do that. Labels may be used in other places as well.

**Comment by jkwatson** [comment]
I think also, IIRC, we're going to end up using some variant of the `Attributes` name for both metrics and spans.

**Comment by anuraaga** [comment]
@bogdandrutu Do you think it makes sense to move the Labels in the spec to common then?

**Comment by jkwatson** [comment]
this has been done. closing.
