### ISSUE TITLE
Remove Baggage Entry?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1960]
It seems like we can remove `Entry` from baggage package if we change `getEntries` to `forEach` pattern like `Attributes` which would also make them a bit more consistent. However if doing that, it makes me wonder again if `EntryMetadata` is really pulling weight it becomes quite lonely.

**Comment by jkwatson** [comment]
How do you forEach with the metadata, then?

**Comment by anuraaga** [comment]
Trying with a tri consumer, does it work?

https://github.com/open-telemetry/opentelemetry-java/pull/1982/files#diff-3dc5218e425f937361a39f3d3d2992cae6ab821451fcf15e54f8fee691278540R12

**Comment by jkwatson** [comment]
> Trying with a tri consumer, does it work?
> 
> https://github.com/open-telemetry/opentelemetry-java/pull/1982/files#diff-3dc5218e425f937361a39f3d3d2992cae6ab821451fcf15e54f8fee691278540R12

I guess that works ok. A little weird given the current state of metadata, but I guess it's an ok way to do it.

**Comment by anuraaga** [comment]
@jkwatson Agree with the current state of metadata being weird. While making the PR, I sort of felt like we could potentially punt on metadata until there are more use cases. e.g., it's not even clear if a String is appropriate since it's supposed to be split on semicolon.

**Comment by jkwatson** [comment]
Mostly, we need to make sure we propagate it. I don't know that being able to access it in-process is all that important right now. But, propagation is pretty important, IMO.
