### ISSUE TITLE
Rename exporter artifacts from opentelemetry-exporters-* to opentelemetry-exporter-*?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1967]
Currently we have exporter artifacts plural but extensions are singular (opentelemetry-extension-*). We should be consistent for them. Singular seem ok?

**Comment by iNikem** [comment]
Singular is actually recommended by the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/library-guidelines.md#protocol-exporters
