### ISSUE TITLE
Inconsistency in tests static imports, need to document what to use

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1994]
I saw usages of:

```java
import static org.junit.Assert.assertEquals;

// AND

import static org.junit.jupiter.api.Assertions.assertEquals;
```

```java
import static org.assertj.core.api.Assertions.assertThat;

// AND

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;  // a simple replace of Assertions works.
```

**Comment by jkwatson** [comment]
We, in my opinion, should standardize on assertj with `import static org.assertj.core.api.Assertions.assertThat;`

**Comment by bogdandrutu** [comment]
what about `assertEquals` which one should we use?

**Comment by kenfinnigan** [comment]
I've found all the `assertX()` methods with assertj to be far easier to use than the ones with JUnit 5

**Comment by Oberon00** [comment]
> what about assertEquals which one should we use?

`assertThat(x).isEqualTo(y)`. Has the great advantage that you don't get expected vs actual wrong about 40% of the time 😄

**Comment by jkwatson** [comment]
> what about `assertEquals` which one should we use?

I think we shouldn't use either of them, and just stick with assertj
