### ISSUE TITLE
Provide default implementations for SpanProcessor.shutdown and forceFlush

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1997]
I think the majority of non-exporting span processors are going to just augment span attributes in `onStart`. For them these two methods don't make any sense and every author will be forced to copy-paste `return CompletableResultCode.ofSuccess()`. Can this be the default implementation?

**Comment by Oberon00** [comment]
Makes sense. The default implementation of shutdown would call forceFlush and the default implementation of forceFlush would do nothing.
