### ISSUE TITLE
Expose Baggage values as an Iterable/Collection/Set

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#2010]
Currently it's possible to access the contents of `Baggage` through its `forEach()` methods, although it may be good to keep an easy way to iterate over them (either as `Collection`, `Iterable` or `Set`).

Specially handy if we expect the end user to read the `Baggage` values.

Marking as GA as I'd like to agree before GA whether we should add this by then, or (maybe) add it after GA.

**Comment by jkwatson** [comment]
If we do this for Baggage, it would probably make sense to also do it for Attributes, Labels, and TraceState.

**Comment by carlosalberto** [comment]
So in theory, if we go for this change, `Labels` / `Attributes` wouldn't need this, as they are expected to be read by SDKs, not the final user.

**Comment by jkwatson** [comment]
This is something we can add post-GA, and I'd like to not add something to the API at this point if we don't absolutely need it.

**Comment by jkwatson** [comment]
marking this as after-ga and changing the title to reflect that it's not a "consideration". :)

**Comment by anuraaga** [comment]
@jkwatson We have `asMap` now so I think this can be closed (just forgot to). Sound right?

**Comment by jkwatson** [comment]
closing since we have `asMap`
