### ISSUE TITLE
Consider making TextMapPropagator.fields() a Collection/Iterable object.

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#2011]
In all other places in the API/SDK we expose, for similar (read-only) cases, either `Collection` or `Iterable`. I suspect we use `List` for legacy reasons in OC, but that's it.

**Comment by Oberon00** [comment]
I think we now usually only export a forEach function. But I would definitely prefer even just Iterable to that.

**Comment by carlosalberto** [comment]
I'd definitely stick to `Iterable` as this is what we use for the closely-related `Getter.keys()` method.

**Comment by SCoceD** [comment]
it must look like this ?
`return C carrier.getOrDefault(keys, null);`

**Comment by ChrisJBurns** [comment]
I'm looking for a good first issue to get stuck into. Is this one good to pickup?

**Comment by anuraaga** [comment]
I think this is a good one to take on. Let's change the return type here

https://github.com/open-telemetry/opentelemetry-java/blob/master/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java#L95

from `List` to `Collection`.

@carlosalberto `Iterable` doesn't seem to make sense even per the javadoc

https://github.com/open-telemetry/opentelemetry-java/blob/master/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java#L93

Fields are a constant of a propagator, so them having a fixed-size `Collection` seems most useful. I guess we went with `Iterable` for `Getter.keys` to allow easier wrapping of the carrier, which isn't needed here.

**Comment by ChrisJBurns** [comment]
Sure, I can make ` Collection` can someone possibly assign this to me? :)

**Comment by ChrisJBurns** [comment]
@jkwatson I believe this can be closed now due to #2156 being merged.

**Comment by anuraaga** [comment]
Yup - thanks @ChrisJBurns!
