### ISSUE TITLE
When will OpenTelemetry release v1.0.0

### ISSUE THREAD

**Issue by HaojunRen** [open-telemetry/opentelemetry-java#2020]
When will OpenTelemetry release v1.0.0? Thanks a lot

**Comment by jkwatson** [comment]
We do not currently have a date planned for 1.0 GA. Currently, in order to satisfy 1.0 GA requirements, we will need to have a complete metrics specification and implementation. For progress on this, I recommend reaching out in the specification repository. Thanks for asking, though!
