### ISSUE TITLE
Latest proto version needed in 0.14.0 release

### ISSUE THREAD

**Issue by gcacace** [open-telemetry/opentelemetry-java#2021]
**Is your feature request related to a problem? Please describe.**
The change in https://github.com/open-telemetry/opentelemetry-java/commit/711efc3ed497df4d796421d004b389c4ff8e972e is needed for our use case and we would like to see this shipped in the next version of this package

**Describe the solution you'd like**
Bump-up to 0.14.0 and release to Maven Central

**Describe alternatives you've considered**
None. For our use case we need the new version in Maven Central

**Additional context**
This is required for a CloudWatch use case

**Comment by jkwatson** [comment]
Hi @gcacace . We have just released 0.10.0. thanks!

**Comment by gcacace** [comment]
Reopening as the new version is not in Maven Centra: https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-proto

**Comment by bogdandrutu** [comment]
And does not have the proto change you need :)

**Comment by gcacace** [comment]
Can we then reopen this issue please?

**Comment by jkwatson** [comment]
We need to wait for a protobuf release before we will depend on it in the project. Otherwise we risk releases with non-released versions of the protobuf that won't be supported by anything.

**Comment by shalk** [comment]
the commit open-telemetry/opentelemetry-proto@8ab21e9 which release in proto  v0.6.0   have released in 0.12.0 or later. ([see proto/build.gradle]( https://github.com/open-telemetry/opentelemetry-java/blob/v0.12.0/proto/build.gradle#L47)).

**Comment by gcacace** [comment]
@bogdandrutu made the change to consume the latest proto package (see: https://github.com/open-telemetry/opentelemetry-java/commit/711efc3ed497df4d796421d004b389c4ff8e972e). Can someone release the new version of this Java package in Maven Central please?

**Comment by jkwatson** [comment]
> @bogdandrutu made the change to consume the latest proto package (see: [711efc3](https://github.com/open-telemetry/opentelemetry-java/commit/711efc3ed497df4d796421d004b389c4ff8e972e)). Can someone release the new version of this Java package in Maven Central please?

This release has been incorporated into the main branch of the java project. It is currently available in snapshot builds. It'll get released on the normal release schedule, within a week or so.

@gcacace I will repeat what I've said before: if you have urgent dependencies on having java protobuf bindings in a more timely manner than what happens to be included in the java SDK, you should maintain your own build/publishing pipeline to manage this, and not rely on the larger java project artifacts.

**Comment by jkwatson** [comment]
closing this
