### ISSUE TITLE
Confusing configuration story

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#2022]
I tried to gather into one place all bits and pieces that SDK allows to configure. So far I got (I concentrated only on tracing, no metrics here):

- SpanProcessor
- SpanExporter
- Sampler
- TracerProvider
- IdGenerator
- ContextPropagator
- BaggagePropagator
- Various limits on TraceConfig, e.g. max attribute count

Ignoring the last point from the above, other configurable objects can be split in two parts: unique, such as Sampler, IdGenerator and TracerProvider, and all others. Configuring unique objects obviously means replacing or _setting_ them. For non-unique objects we may want both to _add_ new objects in addition to defaults or to _set_ and replace default ones.

Now, let us take a look at the example code that tries to configure everything:

```
    OpenTelemetrySdk sdk = OpenTelemetrySdk.get();
    OpenTelemetrySdk.Builder sdkBuilder = sdk.toBuilder();
    TracerSdkManagement tracerSdkManagement = sdk.getTracerManagement();

    tracerSdkManagement.addSpanProcessor(new DemoSpanProcessor());
    TraceConfig currentConfig = tracerSdkManagement.getActiveTraceConfig();
    TraceConfig newConfig = currentConfig.toBuilder()
        .setSampler(new DemoSampler())
        .setMaxLengthOfAttributeValues(128)
        .build();
    tracerSdkManagement.updateActiveTraceConfig(newConfig);

    TracerSdkProvider tracerSdkProvider = TracerSdkProvider.builder().setIdsGenerator(new DemoIdGenerator()).build();
    sdkBuilder.setTracerProvider(tracerSdkProvider);

    sdkBuilder.setPropagators(DefaultContextPropagators.builder().addTextMapPropagator(new DemoPropagator()).build());

    OpenTelemetry.set(sdkBuilder.build());
```

First, is the code above idiomatic for this SDK? If yes, then let us analyse it.

- Different pieces of configuration must be set on different objects: TracerSdkManagement, TraceConfig and OpenTelemetrySdk.Builder
- Why TraceConfig encapsulates different limits (as numbers) and the single object, Sampler?
- If I want to add new SpanExporter, I have to think about SpanProcessor as well.
- If I want to add two SpanExporters, should I add two SpanProcessor? Should I use MultiSpanProcessor?
- If I want to change IdGenerator, I have to know about TracerSdkProvider and to set it.
- Which leads to #2018
- How do I _add_ new propagator? OpenTelemetrySdk.Builder allows me only to _set_ propagators. I am not even sure that my code does what I want :)
- Do I have to add ALL my propagators at once? As it seems I cannot add first context propagator and then later in some other class add baggage propagator.

I think we need to simplify this story :)

**Comment by iNikem** [comment]
A, then we have Clock and Resource, which are in the same bundle as IdGenerator. If I want to change Clock, I have to change TracerProvider.

Do we have an example of programmatically providing additional resource attributes?

**Comment by jkwatson** [comment]
Thanks for pulling this together, @iNikem . We should definitely get this hammered out and made clear before GA.

**Comment by iNikem** [comment]
Demo repository where one can try things out: https://github.com/iNikem/opentelemetry-java-instrumentation-demo

**Comment by iNikem** [comment]
@jkwatson Can you summarise if recent changes in SDK configuration somewhat decreased this confusion?

**Comment by Oberon00** [comment]
There is one point of confusion not mentioned yet when using SDK components without the sdk-all package: Namely you would configure them by calling the respective getter on the OpenTelemetry module and then casting the result. However this stops working when using the sdk-all package, due to the "Obfuscated" class. https://github.com/open-telemetry/opentelemetry-java/issues/1834#issuecomment-732138463

**Comment by jkwatson** [comment]
> There is one point of confusion not mentioned yet when using SDK components without the sdk-all package: Namely you would configure them by calling the respective getter on the OpenTelemetry module and then casting the result. However this stops working when using the sdk-all package, due to the "Obfuscated" class. [#1834 (comment)](https://github.com/open-telemetry/opentelemetry-java/issues/1834#issuecomment-732138463)

@Oberon00 Maybe you can help me understand something. Why do people think that the appropriate way to configure the SDK is to use the API and cast to the implementations? This would be like people using slf4j, and trying to configure it by casting the LoggerFactory to the implementation, which I don't think anyone would think was the right way to go. Is there something in our documentation somewhere that leads people down this path?

Just like we don't want people using the SDK to write instrumentation, we also don't want people using the API to configure the SDK. What can we do to make this more clear?

**Comment by Oberon00** [comment]
> Is there something in our documentation somewhere that leads people down this path?

The only purpose of the SPI as far as I can see is that calling e.g. `OpenTelemetry.getTracer` auto-magically uses the SDK tracer if it is on the classpath. This SPI is useless if you cannot configure the tracer. If you use the explicit setter, you circumvent the SPI. If you use the SPI, the only way to configure the tracer is by casting. Maybe the SPI should be removed here.

**Comment by jkwatson** [comment]
> > Is there something in our documentation somewhere that leads people down this path?
> 
> The only purpose of the SPI for Tracer/Meter/... as far as I can see is that calling e.g. `OpenTelemetry.getTracer` auto-magically uses the SDK tracer if it is on the classpath. This SPI is useless if you cannot configure the tracer. If you use the explicit setter, you circumvent the SPI. If you use the SPI, the only way to configure the tracer is by casting. Maybe the SPI should be removed here.

Um. Not true!  This works fine for me:

```
    TracerSdkManagement tracerManagement = OpenTelemetrySdk.get()
        .getTracerManagement();
    TraceConfig traceConfig = tracerManagement
        .getActiveTraceConfig()
        .toBuilder()
        .setMaxNumberOfEvents(33)
        .build();
    tracerManagement.updateActiveTraceConfig(traceConfig);
```

**Comment by Oberon00** [comment]
Yes, but for `OpenTelemetrySdk` you already need the `all` package, which effectively disables the SPI for TracerProvider by implementing the SPI for OpenTelemetryFactory.

**Comment by jkwatson** [comment]
I'm afraid I don't understand what you're getting at. Can you provide a main method, with dependencies that doesn't work for you without casting from the API classes?

**Comment by Oberon00** [comment]
```java
Tracer tracer = OpenTelemetry.getGlobalTracer('test', null);
```

specifying only the dependency on opentelemetry-sdk-trace.

This will automatically use the TracerProviderSdk thanks to the SPI. But the SPI is rather useless here if you want to avoid casting. Because then you would have to explicitly instantiate, configure, and set your TracerProviderSdk, sidestepping the SPI (as discussed in #1834). I think doing this explicitly is fine, I just don't know if the SPI for TracerProviderFactory is at all useful if we agree this is the better way.

**Comment by jkwatson** [comment]
The SPI is there to not only enable loading the default SDK (configurable with env vars, etc), but also so you can provide your own SPI TracerProviderFactory with your own settings, if you want to load yours instead of the one from the SDK.

And, if you just want to configure it manually, you can just do this:
```
    TracerSdkProvider tracerProvider = TracerSdkProvider.builder().build();
    TraceConfig traceConfig = tracerProvider.getActiveTraceConfig().toBuilder()
        .setMaxNumberOfEvents(33)
        .build();
    tracerProvider.updateActiveTraceConfig(traceConfig);

    OpenTelemetry openTelemetry = OpenTelemetry.builder().setTracerProvider(tracerProvider).build();
    OpenTelemetry.set(openTelemetry);
```

I guess I'm still not clear on what isn't working for you. You should definitely not cast to the SDK to configure it (and it doesn't work because we don't want people to do this). I think we still need more options on the various builders so that it's easier to write a TracerProviderFactory with all the customization included, but I guess I still don't see where what we have today is broken.

**Comment by Oberon00** [comment]
The implementation of TracerProviderFactory by the default SDK is still useless then. The only way to configure it, when using the SPI, is by casting. Unconfigured, it does nothing.

**Comment by jkwatson** [comment]
Sounds like if we had the `TracerProviderFactory` properly handle the environment variables for the various tracing option, it would be useful? I think this is just something we haven't implemented yet.

**Comment by iNikem** [comment]
After recent changes (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2088/files#diff-d4c5a5c24d15ffde53549d4ce792cf6e8b9ee2286fd9f093b51b8a1b914f277e) here is my take on the current state of the 
(auto) configuration.

These (pain) points are still valid:

* Why TraceConfig encapsulates different limits (as numbers) and the single object, Sampler?
* If I want to add new SpanExporter, I have to think about SpanProcessor as well.
* If I want to add two SpanExporters, should I add two SpanProcessor? Should I use MultiSpanProcessor?

Last point from above _probably_ can be solved by documentation. Also there is no documentation for `autoconfigure` sdk extension, which documents all SPIs like `ConfigurablePropagatorProvider` and `SdkTracerProviderConfigurer`.

One question worth documenting: how several `SdkTracerProviderConfigurer` play together? Obvious problem is what if two configurers change `IdGenerator`? Second problem, how to _change_ only one value in `TraceConfig`?

But all in all I think that the current state is much-much better, than it was 2 months ago :) Thank you very much @jkwatson and @anuraaga

**Comment by anuraaga** [comment]
Thanks! For the exporter / processor tension, there is a lot of agreement that it's weird right now but for now most want to leave it to post-ga.

https://github.com/open-telemetry/opentelemetry-specification/issues/1331

We would be able to add something like `addExporter` later even if it means continuing to have the old way as well

**Comment by jkwatson** [comment]
so, can we close this issue as complete-as-we-will-get for 1.0? And open further issues/discussions for a more fluent exporter SDK API?

**Comment by iNikem** [comment]
What about Sampler and documentation?

**Comment by jkwatson** [comment]
What do you propose we do about the current Sampler spec before 1.0? Documentation, sure...what are we missing at this point?

**Comment by iNikem** [comment]
Documentation:

> there is no documentation for autoconfigure sdk extension, which documents all SPIs like ConfigurablePropagatorProvider and SdkTracerProviderConfigurer.

> One question worth documenting: how several SdkTracerProviderConfigurer play together? Obvious problem is what if two configurers change IdGenerator? Second problem, how to change only one value in TraceConfig?

Sampler: spec says nothing about the location of the Sampler, only that it should be available at `TracerProvider`. If I could Sampler directly on `SdkTracerProviderBuilder`, that would solve this problem for me.

**Comment by anuraaga** [comment]
> If I could Sampler directly on SdkTracerProviderBuilder, that would solve this problem for me.

I was especially conservative on this point and didn't move Sampler but I do want to. I'm happy to get this last big change in though since it sounds like our dogfooders want it 😁

**Comment by jkwatson** [comment]
This is just like adding new ways to specify exporters. We can do this after 1.0, correct?

**Comment by jkwatson** [comment]
If what we have right now is good enough for 1.0, I'll remove the 1.0 tag and we can either close this an open specific issues around more "fluent" configuration of exporters and samplers, or keep this open indefinitely.

**Comment by iNikem** [comment]
Do you want to keep Sampler in TraceConfig forever?

**Comment by jkwatson** [comment]
> Do you want to keep Sampler in TraceConfig forever?

eh, I don't care very much, honestly. Very few users are going to care very much about it, and it doesn't kill me to make vendor/distro providers have to work with what we have today. 

I don't want a change to it to hold up 1.0, but if someone wanted to get it in very quickly, I wouldn't fight it.

**Comment by iNikem** [comment]
Thus it depends on @anuraaga :D But yeah, what remains in this task can be done post 1.0

**Comment by jkwatson** [comment]
@iNikem can we close this?

**Comment by jkwatson** [comment]
closing. any new config issues can be opened as new issues.
