### ISSUE TITLE
Rewrite the Metrics SDK

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2033]
Our current Metrics SDK is fully functional and works. It is not, unfortunately, in alignment with the Metrics SDK specification, which is based on the golang SDK. Because of the divergence from the specification, it is difficult to understand the state of our implementation, and how it aligns (or does not) with the specification.

I propose we rewrite the metrics SDK to conform more closely to the specification.

**Comment by kenfinnigan** [comment]
Do you have a specific example of where it differs?

**Comment by jkwatson** [comment]
I actually have no example of where it doesn't differ. The implementations are completely different, as far as I can tell.

**Comment by jkwatson** [comment]
Note: I've been roughing out a cleanroom implementation of the SDK based on the current specification here:  https://github.com/jkwatson/opentelemetry-java/tree/metrics_v2_1

/cc @carlosalberto

**Comment by jkwatson** [comment]
Note: @bogdandrutu is doing some work to coerce our current implementation into something closer to what is in the SDK spec. Thanks, @bogdandrutu !

**Comment by bogdandrutu** [comment]
@jkwatson what is the definition of done for this issue?

**Comment by jkwatson** [comment]
Excellent question! I'd like to have a third-party (i.e. not you or me) take a pass through our implementation and make sure they can explain how it works, and how/if it does or doesn't map to the SDK specification.

**Comment by jkwatson** [comment]
closing for now, as the metrics specifications are getting a re-work.
