### ISSUE TITLE
Remove documentation captured on website from READMEs

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-java#2040]
For GA there is an ask to capture getting started guides as well as instrumentation and configuration documentation on the website. Given open-telemetry/opentelemetry.io#304, several READMEs need to be either updated or removed.

**Comment by flands** [comment]
I can submit a PR for this.

**Comment by flands** [comment]
OK, documentation PR landed on website -- this is ready for review and merge.

**Comment by jkwatson** [comment]
I'm not wild about having to maintain documentation in two places, one of which Java maintainers are not in control of merging and changes. Do we have plans for how we're going to make sure that the public docs are kept up-to-date?

**Comment by jkwatson** [comment]
We've had general agreement that we should not delete the getting-started documentation from this repository, even if there is parallel documentation on the website. If we need some tweaks to our docs, please open a separate issue to track it.
