### ISSUE TITLE
Docs mention TracingContextUtils that I cannot find anywhere

### ISSUE THREAD

**Issue by holyjak** [open-telemetry/opentelemetry-java#2046]
The [Quick start mentions the class `TracingContextUtils`](https://github.com/open-telemetry/opentelemetry-java/blob/master/QUICKSTART.md#create-basic-span) but I cannot find it anywhere. Is the docs wrong or where is the class? Thank you!

**Comment by jkwatson** [comment]
Urgh. Our quickstart needs to be updated, post the 0.10.0 release. Sorry about that! I'll work on that ASAP.
