### ISSUE TITLE
Better package for WithSpan annotation

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#2055]
There is `io.opentelemetry.extension.auto.annotations.WithSpan` annotation in this repo. The package name is not ideal :) The original thought behind it was "this annotation requires javaagent and the latter uses `auto` everywhere". Now javaagent does not use `auto` anywhere and there is Spring Boot integration which supports `WithSpan` annotation even without javaagent. Thus, there should be better package name :)

**Comment by jkwatson** [comment]
Do you have a recommendation on the package name, since it's primarily used by the agent codebase? If we're going to move it, we need to do it ASAP, since it's a breaking API change.

**Comment by iNikem** [comment]
I propose just dropping `auto` from the names:
- package name is io.opentelemetry.extensions.annotations
- artifact name is io.opentelemetry:opentelemetry-extension-annotations

@trask

**Comment by trask** [comment]
Makes sense to me
