### ISSUE TITLE
Gauge to report BatchSpanProcessor current queue size

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-java#2056]
**Is your feature request related to a problem? Please describe.**
Currently the BatchSpanProcessor reports number of spans processed, dropped and exported - however it does not provide a gauge reporting the queue size, to give end users an indication of how close the queue is getting to full (at which point spans would be dropped).

**Describe the solution you'd like**
Add a queue size gauge to enable visibility of the number of spans currently queued.

**Describe alternatives you've considered**
Currently the only option is to monitor the dropped spans, as an indication that the queue is becoming full, but at that point it is too late to do anything about it.

**Comment by jkwatson** [comment]
Love it! Great idea!

**Comment by jkwatson** [comment]
(Note: would be implemented via a `ValueObserver` instance, I believe)
