### ISSUE TITLE
io.netty_netty-codec CRITICAL vulnerabilities 

### ISSUE THREAD

**Issue by dng00** [open-telemetry/opentelemetry-java#2059]
Are there any plans to upgrade netty dependency to the latest. The current version of opentelemetry jar 0.9.0 is being flagged with critical vulnerabilities in the netty package.

![image](https://user-images.githubusercontent.com/69011697/98723656-abbc2980-2360-11eb-9337-5d40d979c0a3.png)

![image](https://user-images.githubusercontent.com/69011697/98723803-dc03c800-2360-11eb-82b1-3bace8f63c7c.png)

**Comment by jkwatson** [comment]
I this issue belongs over in the instrumentation project. The API/SDK have no direct dependency on netty-codec that I can see. Please log over at https://github.com/open-telemetry/opentelemetry-java-instrumentation

Thanks!

**Comment by jkwatson** [comment]
closing as it is not relevant to this project. please re-open if you have evidence otherwise.
