### ISSUE TITLE
GRPC Jaeger exporter authentication

### ISSUE THREAD

**Issue by mariusioana** [open-telemetry/opentelemetry-java#2061]
Hi!

Looked a bit in the otlp Jaeger java exporters but could not find a way to add Auth headers. For example, we need to add something like:

`jaeger_thrift_http: headers: {"Authorization": "Bearer 7:xxxxxxxxxxx"}`

We do not want to use and deploy Open Collector for now. We plan to in the future but now we just want to test quickly directly against the Jaeger backend we have. Is there a way to send some sort of auth using Jaeger otlp java exporter?

Thanks1

**Comment by jkwatson** [comment]
I'm assuming you mean "Jaeger GRPC" rather than OTLP in this.

I'm not an expert in GRPC, but can you get this by customizing the `Channel` that you configure the exporter with?

**Comment by mariusioana** [comment]
@jkwatson yeap, sorry, meant to refer to Jaeger client libraries.

Looking a bit more, I think we can leverage the Jaeger Thrift exporter implementation and have something like:

`thriftSender = new HttpSender.Builder(endpoint).withAuth("TOKEN_HERE").build();`

I am not an expert in GRPC either, but using Thrift seems a little bit easier but if anyone else has other idea, please share. 

Thanks!

**Comment by jkwatson** [comment]
If you can make this work with the thrift exporter, that would be great. Let me know how it goes.

**Comment by bogdandrutu** [comment]
@mariusioana for GRPC you provide your own channel that allows you to configure auth. I would suggest using GRPC because that is the recommended way by Jaeger

**Comment by bogdandrutu** [comment]
Here is a small snippet to add headers (you can configure TLS as well if you want):
```
    // Create metadata to be added to every call
    Metadata metadata = new Metadata();
    metadata.put(Metadata.Key.of("TOKEN_HERE", Metadata.ASCII_STRING_MARSHALLER), "value");

    // Create a channel towards Jaeger end point
    ManagedChannel jaegerChannel =
        ManagedChannelBuilder.forAddress(ip, port)
            .intercept(MetadataUtils.newAttachHeadersInterceptor(metadata))
            .usePlaintext()
            .build();

    // Export traces to Jaeger
    JaegerGrpcSpanExporter jaegerExporter =
        JaegerGrpcSpanExporter.builder()
            .setServiceName("otel-jaeger-example")
            .setChannel(jaegerChannel)
            .setDeadlineMs(30000)
            .build();

```

**Comment by mariusioana** [comment]
Cool, thanks @bogdandrutu !
