### ISSUE TITLE
Change the default grpc deadline for OTLP and Jaeger exporters from 1s to 10s

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#2064]
I think this maps to `deadlineMs`, and the default should be bumped from `1s` to `10s` according to [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/exporter.md#configuration-options)

It doesn't look like there's a corresponding env var for Jaeger, but should we bump default Jaeger grpc deadline from `1s` to `10s` also?

(we've had a couple of `DEADLINE_EXCEEDED` issues reported in otel-java-instrumentation which is why I'm interested 😄)

**Comment by jkwatson** [comment]
Hi @trask . Looks like we already support this env var. Is it not working for you?

We can definitely bump the default to 10s.

**Comment by trask** [comment]
I see `OTEL_EXPORTER_OTLP_SPAN_TIMEOUT` and `OTEL_EXPORTER_OTLP_METRIC_TIMEOUT`, but not `OTEL_EXPORTER_OTLP_TIMEOUT`

**Comment by jkwatson** [comment]
https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/otlp/src/main/java/io/opentelemetry/exporter/otlp/CommonProperties.java#L9

**Comment by trask** [comment]
perfect, I missed that, thanks, I'll modify this issue to just be about the default value
