### ISSUE TITLE
Latest SNAPSHOTs not available

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#2070]
Currently we are not pushing/publishing the SNAPSHOTS. In https://oss.jfrog.org/artifactory/oss-snapshot-local/io/opentelemetry/opentelemetry-api/ there should be a `0.11.0-SNAPSHOT` directory.

**Comment by jkwatson** [comment]
Looks like this is working again. ok to close, @carlosalberto ?

**Comment by carlosalberto** [comment]
Confirmed 😉 https://oss.jfrog.org/artifactory/oss-snapshot-local/io/opentelemetry/opentelemetry-api/0.11.0-SNAPSHOT/ 

Thanks for the fix!
