### ISSUE TITLE
Require `service.name` to be set on the Resource before the SDK will start up

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2076]
Right now, all the exporters have an additional property that can be configured for the service name. I think it might be better to require `service.name` to be set on the Resource in the SDK before it would start up. 

Are there backends that don't want a `service.name`, or that would function just fine without it? 

In the [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/resource/semantic_conventions#service), it's marked as `required`, but it's not enforced at all. Should it be?

**Comment by Oberon00** [comment]
The required only applies if you want to have a service resource (which is not itself required)

> Certain attribute groups in this document have a Required column. For these groups if any attribute from the particular group is present in the Resource then all attributes that are marked as Required MUST be also present in the Resource. However it is also valid if the entire attribute group is omitted (i.e. none of the attributes from the particular group are present even though some of them are marked as Required in this document).

**Comment by jkwatson** [comment]
Maybe we need to enforce that it's there in the Resource if you use one of our exporters?

**Comment by jkwatson** [comment]
Spec discussion seems to be pointing toward always have a fail-safe fallback for the service.name that will always be populated, no matter what. Once that is implemented, we should remove the service name settings from the exporters that currently have them.

**Comment by bogdandrutu** [comment]
@jkwatson is this something that we can close?
