### ISSUE TITLE
Reconsider moving System Metrics to extensions/

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#2078]
We long time ago had considered having [System Metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/system-metrics.md) instrumentation here, as opposed to having them in [Auto-Instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/instrumentation/oshi/library/src/main/java/io/opentelemetry/instrumentation/oshi), reasons being:

1) Currently they are ONLY enabled if the end user application has the Oshi Hardware library in his classpath.
2) It's relatively tricky to enable them in the Auto-Instrumentation, as this potential improvement [PR shows](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1530).
3) We already have something similar under `extensions/runtime_metrics` so it makes sense to have additional, similar pieces here.

In general, I'd imagine users desiring to explicitly enable this in their applications (in the end, you only need the API artifact, which means you could leverage them similarly to `WithSpan`, i.e. `SystemMetrics.registerMetrics()`), and OTel Distro authors would like to include them as well (as we in LS are considering).

(Alternatively, we could add the Oshi library as a dependency to the agent, but I think the agent jar is already **too** fat, so there's no motivation to do so).

cc @jkwatson (who originally suggested we could have these under the Agent) 😉

**Comment by jkwatson** [comment]
will putting them in the java repo make it easier to enable in the agent somehow?

**Comment by carlosalberto** [comment]
Correct me if I'm wrong, but the  @open-telemetry/java-instrumentation-approvers team is not interested in this at all, at least for now 😉 (it doesn't even work out-of-the-box, for a start, unless the user has the Oshi library as a dependency - while it should be the other way around, i.e. **if** the user enables System Metrics, you get the Oshi library imported). 

And the instrumentation repo could have it 'back' in the future if/when they need it, although it will exist as a jar already (`opentelemetry-extension-system-metrics.jar`)

**Comment by jkwatson** [comment]
I thought we originally had planned on moving the `runtime_metrics` extension into the instrumentation project as well, which is why I thought it made sense to have the other one in there.

This stuff *is* instrumentation, so I don't follow why it would belong in this repo...

**Comment by carlosalberto** [comment]
Well, it's totally unusable at this moment there, and it seems simple enough to have it here (although I didn't know or didn't remember you were planning to move `runtime_metrics` there too, my bad). Also, I know it's not a prerogative to make it run out-of-the-box in the agent.

FWIW, in other languages such as Go/Python the system metrics instrumentation exists also as a standalone extension.

(Also, I can imagine the Auto-Instrumentation team **never** accepting the Oshi library as a dependency, even if it's useful for something as the Standard System Metrics)

**Comment by trask** [comment]
@carlosalberto I'm confused by several things mentioned above, can you add this topic to the instrumentation SIG meeting agenda for next week? I'm sure we can get on the same page.

**Comment by carlosalberto** [comment]
@trask Oh, definitely. Just wanted to get the discussion rolling from now 😄  PS - Although I suspect you guys are still not happy about the idea of having Oshi as an included dependency 😅

**Comment by trask** [comment]
@carlosalberto there's a lot of work going on in the Instrumentation repo around vendor-specific distributions, which (among other things) makes it easy for different vendors to make different decisions about something like this

**Comment by carlosalberto** [comment]
Closed based on the latest discussion during the Auto-Instrumentation SIG call.
