### ISSUE TITLE
Unable to build the opentelemetry-java project

### ISSUE THREAD

**Issue by ChandrewR** [open-telemetry/opentelemetry-java#2080]
I'm getting this error while building(executing gradlew.bat) - Could not find method release() for arguments [build_dfiyoporiz4savkbdijrduymk$_run_closure2@4f71c941] on root project 'opentelemetry-java' of type org.gradle.api.Project

**Steps to reproduce**
Download the java project and execute the gradlew.bat to reproduce the issue

**What did you expect to see?**
Build successful

**What did you see instead?**
Error
![Gradle Build Error](https://user-images.githubusercontent.com/26222838/99220708-270c5800-2805-11eb-8ea0-3f1b2105622c.PNG)

**Environment**
Compiler: JAVA 1.8.0_241
OS: Windows 10

**Comment by Oberon00** [comment]
You need at least JDK 11 to build. 8 won't work.

**Comment by anuraaga** [comment]
@ChandrewR Thanks for the report - interesting side effect of the nebula plugin that it is requiring a .git directory. For now, if you can clone from github and install Java 11 it should work ok, will look at fixing that.

**Comment by jkwatson** [comment]
I think this has been fixed with #2082 and #2081. Can you verify, @ChandrewR ?

**Comment by ChandrewR** [comment]
@anuraaga So which components uses JAVA 11?. I see all JAVA 8 in README.md files...Can you pls confirm?

**Comment by anuraaga** [comment]
Hi @ChandrewR - building this repository requires Java 11 as listed here

https://github.com/open-telemetry/opentelemetry-java/blob/master/CONTRIBUTING.md#requirements

The actual built artifacts can be used with a Java 8 app.

I'm trying to find Java 8 in README but can't - can you point me at it? If it's in the context of building this repository, it needs to be updated.

**Comment by ChandrewR** [comment]
Can individual artifacts like api, extensions etc be build with JAVA 8? It says JAVA 8 in README
https://github.com/open-telemetry/opentelemetry-java/tree/master/api
https://github.com/open-telemetry/opentelemetry-java/tree/master/extensions/trace-propagators

**Comment by anuraaga** [comment]
Thanks @ChandrewR - it's indeed confusing to have mention of Java 8 all over the place. I have removed them in #2124 and instead clarify that published artifacts require Java 8+, and building requires looking at CONTRIBUTING.md, in the top-level README. Hopefully this prevents confusion going forward.

**Comment by jkwatson** [comment]
@ChandrewR can we close this? I believe that the documentation has been updated to be more accurate.

**Comment by bogdandrutu** [comment]
No more action, closing since this is clear now (hopefully)
