### ISSUE TITLE
B3 propagator: add support for injecting both single and multi header versions.

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java#2083]
Single OR multi header propagation is supported but not both.

**Comment by jkwatson** [comment]
@malafeev The current propagator will extract whatever is there, single or multi. It will only inject one or the other, which seems like the right decision. Are you asking to have it inject both?

**Comment by malafeev** [comment]
yes @jkwatson 
cc @carlosalberto

**Comment by jkwatson** [comment]
@malafeev I updated the Issue description for this.

Is this a B3 recommend mode of operation, to provide both sets of headers? That seems like an unusual option to choose.

**Comment by carlosalberto** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md#extract-3

I totally forgot to fill an issue here regarding this update (and probably we need a Spec Compliance item to verify this is the expected behavior for all languages).

**Comment by jkwatson** [comment]
@carlosalberto @malafeev I think we're 100% spec compliant already then. We're _not_ supposed to *inject* both types of headers with one propagator instance.

**Comment by carlosalberto** [comment]
@jkwatson I'd disagree, given that part of the Specification talks about the B3 propagator as a single instance (hence the mention of trying to extract both encodings, yet inject only one).

But not a strong feeling, although it feels that we _should have stated_ things differently in the mentioned change back then to avoid these confusions (for example, in Python the single-standing B3 Propagator tries to extract both encodings, and it injects them using the multi-part encoding).

**Comment by jkwatson** [comment]
> @jkwatson I'd disagree, given that part of the Specification talks about the B3 propagator as a single instance (hence the mention of trying to extract both encodings, yet inject only one).
> 
> But not a strong feeling, although it feels that we _should have stated_ things differently in the mentioned change back then to avoid these confusions (for example, in [Python](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/trace/propagation/b3_format.py#L58) the single-standing B3 Propagator tries to extract both encodings, and it injects them using the multi-part encoding).

but...this is exactly what the Java one does! Am I missing something?
