### ISSUE TITLE
Not all artifacts for 0.10.0 and 0.11.0 are available in mvnrepository.com

### ISSUE THREAD

**Issue by mjh-c** [open-telemetry/opentelemetry-java#2107]
While the core artifacts like opentelemetry-api and opentelemetry-sdk are available for the current version 0.10.0 and 0.11.0 some other artifacts, e.g. a lot exporters are only available in 0.9.1.
Therefore we cannot upgrade to the latest version.

We are interested in https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-exporters-zipkin

But if you look through https://mvnrepository.com/artifact/io.opentelemetry there are a lot of entries with "Last Release on Oct 7, 2020" which is the 0.9.1 version.

**Comment by anuraaga** [comment]
@mjh-c Sorry for the trouble. We did a significant renaming of artifacts in 0.10.0 as we get cleaned up for a GA release. The exporter artifacts now lack the "s", so `opentelemetry-exporter-zipkin`. Please check out the other breaking changes too https://github.com/open-telemetry/opentelemetry-java/releases/tag/v0.10.0

**Comment by mjh-c** [comment]
Thanks for the super-fast response. I was not aware of the renaming but now everything makes sense. I'll close the issue.
