### ISSUE TITLE
A way to propagate tracing context into ForkJoinPool.commonPool()

### ISSUE THREAD

**Issue by dh-ger** [open-telemetry/opentelemetry-java#2108]
**Is your feature request related to a problem? Please describe.**
In many places in our project we use the CompletableFuture API to perform some tasks in parallel (usually external calls that can be done in parallel).
```
CompletableFuture.supplyAsync(() -> doSomeExternalCall());
```
At a low level around these http requests we have, using code like the following.

```
                        var spanName = String.format("PUT %s", url);
			var span = this.tracer.spanBuilder(spanName).startSpan();
			try (var ignored = tracer.withSpan(span)) {
				return  httpCallHere();
			finally {
				span.end();
			}
```
We noticed then that these spans were not being recorded properly. Upon further inspection it appeared as though calls to `this.tracer.getCurrentSpan()` were returning the `DefaultSpan` rather than the correct current span, and hence this is why they were not being recorded correctly. I can only assume this is because the thread context is lost when we execute on a separate thread.

**Describe the solution you'd like**

In an ideal world I would like a solution where there was some solution where we could pass a tracing context aware ExecutorService into the `supplyAsync` method. Something like the solution described here, for opentracing.
https://github.com/opentracing-contrib/java-concurrent

However I would prefer to not create a new ExecutorService and manage the threadcount etc myself, I would prefer to be able use ForkJoinPool.

**Describe alternatives you've considered**

I have not considered any alternatives to this.

**Comment by anuraaga** [comment]
Hi @dh-ger - context propagation is indeed a big challenge and we want to make it as smooth as we can.

The Java auto instrumentation agent does have some ability to automatically propagate context across threads, including ForkJoinPool from what I understand. Is this something you can use? /cc @trask 

With only the SDK, unfortunately we don't have any magic. But we do offer `Context.wrap` to wrap runnables or executors in a way that propagates context. It would be great if one of these methods works for you, if not is there any other helper that could solve your use case? Thanks for the feedback!

**Comment by dh-ger** [comment]
Hi @anuraaga ,

Thank you for your suggestions. 
We had initially opted to not use the auto instrumentation since we use GCP and there was no exporter for stackdriver/trace.
However wouldn't you know it there is now! So we will proceed with this.
https://mvnrepository.com/artifact/com.google.cloud.opentelemetry/exporter-auto

On the original question I have not been able to get the `Context.wrap` to work when using the CompletableFuture API specifically for `supplyAsync` mainly because that uses `Supplier` rather than `Runnable`.
But I have not invested too much time in this.
I hope to get back to it some time next week, one I do I'll let you know if I have any feedback.

Thanks

**Comment by pavolloffay** [comment]
The `ForkJoinPool` is not 100% supported in the Java agent see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/709

```java
    IntStream.range(0, 20)
        .parallel()
        .forEach(value -> {
          // currentSpan is not propagated
          printSpan(TRACER.getCurrentSpan());
        });
  
    ForkJoinPool.commonPool().execute(() -> {
      // currentSpan is correctly propagated
      printSpan(TRACER.getCurrentSpan());
    });
```

**Comment by dh-ger** [comment]
@anuraaga 
Just had a more in depth look at `Context.wrap`.
https://github.com/open-telemetry/opentelemetry-java/blob/21fbb36d81c79d81d63abf0a7a64bc8c4124b941/context/src/main/java/io/opentelemetry/context/ContextExecutorService.java
This looks good to me, we have a very similar Executor in our project used to propagate other context (multitenant information etc) into threads on the thread pool.
Thanks for the suggestion.

@pavolloffay 
Thanks for the pointer on this, we did see the open issue you have sent on, however it does not appear to be affecting us, probably because we use `ForkJoinPool.commonPool().execute`. We are happy to live with the possibility of this not working initially and just upgrade as new versions of the auto instrumentation become available.

I will close this issue now as the original answer (`context.wrap`) satisfies initial question.
Thanks
