### ISSUE TITLE
The parent span is not displaying in Zipkin and Jaeger exporter of 0.10.0 version

### ISSUE THREAD

**Issue by ChandrewR** [open-telemetry/opentelemetry-java#2117]
The parent span is not displaying in Zipkin and Jaeger exporter of 0.10.0 version

To reproduce :
Setup example code of Zipkin and Jaeger of 0.10.0 version and add the Parent and child span. 

Expected to see the Parent span and child span in Zipkin and Jaeger. But Parent span is missing. Refer screenshot and code.

Artifacts used 
`<dependencies>
	<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-api</artifactId>
    <version>0.10.0</version>
</dependency>
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-sdk</artifactId>
    <version>0.10.0</version>
</dependency>

<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-logging</artifactId>
    <version>0.10.0</version>
</dependency>
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-zipkin</artifactId>
    <version>0.10.0</version>
</dependency>
<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.2</version>
</dependency>
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-jaeger</artifactId>
    <version>0.10.0</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-protobuf</artifactId>
    <version>1.28.0</version>
</dependency>
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-netty-shaded</artifactId>
    <version>1.28.0</version>
</dependency></dependencies>`

`public void myWonderfulUseCase() throws InterruptedException {
		/*
		 * // Generate span Span span =
		 * tracer.spanBuilder("Start my wonderful use case").startSpan(); // Add some
		 * Event to the span span.addEvent("Event 0"); // execute my use case - here we
		 * simulate a wait doWork(); // Add some Event to the span
		 * span.addEvent("Event 1"); span.end();
		 */
	  
	  // Generate span
	    Span span = tracer.spanBuilder("DoWork - Parent Span").startSpan();
	    span.setAttribute("Root-span-attribute", 1);
	    // Add some Event to the span
	    //span.addEvent("Event 0");
	    // execute my use case - here we simulate a wait
	    //doWork();
	    
	    try (Scope scope = span.makeCurrent()) {

	        //Just pause to pretend we're doing something
	    	//Span childSpan0 = tracer.spanBuilder("DoWork - Child Span - 0").setParent(Context.current().with(span)).startSpan();
	    	Span childSpan0 = tracer.spanBuilder("DoWork - Child Span - 0").startSpan();
	        Thread.sleep(300);
	        childSpan0.end();

	        //Add a couple of child spans to the root span
	        Span childSpan = tracer.spanBuilder("DoWork - Child Span - 1").startSpan();

	        Thread.sleep(500);
	        childSpan.end();

	        Span childSpan2 = tracer.spanBuilder("DoWork - Child Span - 2").startSpan();
	        childSpan2.setAttribute("customer-id", 1);
	        childSpan2.setAttribute("order-no", 100);

	        Thread.sleep(1500);
	        childSpan2.end();
	        
	        Span childSpan3 = tracer.spanBuilder("DoWork - Child Span - 3").startSpan();
	        Thread.sleep(1000);
	        childSpan3.end();
	    }
	        
	        //span.getSpanContext().getTraceState();
	        System.out.println("To check the trace");
	     
  }`

**Environment**
Compiler: (e.g., "JDK 1.8.0_271")
OS: (e.g., "Windows 10")

![Parent-child span code](https://user-images.githubusercontent.com/26222838/99982543-b64ed800-2dd0-11eb-984b-8d9e0ae96819.PNG)
![Jaeger](https://user-images.githubusercontent.com/26222838/99982547-b8189b80-2dd0-11eb-9e6e-c2ec1017562f.PNG)
![Zipkin](https://user-images.githubusercontent.com/26222838/99982548-b8189b80-2dd0-11eb-9f56-66a2b72e20f8.PNG)

**Comment by ChandrewR** [comment]
Note that it was showing parent span with version 0.9.0 and below code 
` public void myWonderfulUseCase() {
    // Generate span
    Span span = tracer.spanBuilder("DoWork - Parent Span").startSpan();
    span.setAttribute("Root-span-attribute", 1);
    // Add some Event to the span
    //span.addEvent("Event 0");
    // execute my use case - here we simulate a wait
    //doWork();
    
    **try (Scope scope = tracer.withSpan(span)) {**

        //Just pause to pretend we're doing something
    	Span childSpan0 = tracer.spanBuilder("DoWork - Child Span - 0").startSpan();
        Thread.sleep(300);
        childSpan0.end();

        //Add a couple of child spans to the root span
        Span childSpan = tracer.spanBuilder("DoWork - Child Span - 1").startSpan();

        Thread.sleep(500);
        childSpan.end();

        Span childSpan2 = tracer.spanBuilder("DoWork - Child Span - 2").startSpan();
        childSpan2.setAttribute("customer-id", 1);
        childSpan2.setAttribute("order-no", 100);

        Thread.sleep(1500);
        childSpan2.end();
        
        Span childSpan3 = tracer.spanBuilder("DoWork - Child Span - 3").startSpan();
        Thread.sleep(1000);
        childSpan3.end();

    } catch (Throwable t) {

    } finally {

    }
    //span.addEvent("Event 1");
    
    
    //Span span1 = tracer.spanBuilder("DoWork - Span - 1").startSpan();
    // Add some Event to the span
    //span1.addEvent("Event 0");
    //doWork();

    //span1.addEvent("Event 1");
    //span1.end();
    span.end();
  }

`

**Comment by jkwatson** [comment]
@ChandrewR I don't see a call to `span.end()` in your code snippet. If you never end the span, it won't get reported, so the parent will never make it to an exporter.

**Comment by ChandrewR** [comment]
Yes, It worked after ending the span.Didnt notice.Thank you @jkwatson
