### ISSUE TITLE
buildscripts/generate.sh is broken

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#2139]
**Describe the bug**
1. It generates the `SemanticAttributes.java` in wrong directory, with wrong package
2. `./generate.sh: line 28: ./gradlew: No such file or directory`
3. The script behaves slightly differently depending from where it's called: `opentelemetry-specification` is always downloaded to the current working directory, but .gitignore only ignores it when it's in `buildscripts/semantic-convention`
4. For some reason the spec repo is frozen in time at sha1 662baae949f01a8ecc950426bf09283be1b657de - this block us from getting any recent changes in the semantic attributes.

**Steps to reproduce**
```sh
./buildscripts/semantic-convention/generate.sh
```

**Comment by Oberon00** [comment]
> For some reason the spec repo is frozen in time at sha1 662baae949f01a8ecc950426bf09283be1b657de

This is intentional. We want the committed `generate.sh` to reproducibly generate `SemanticAttributes.java`. It is important that we know from which version of the spec this was generated.

**Comment by mateuszrzeszutek** [comment]
Hmm, are we going to update it manually to a newer hash when new attributes are needed? I mean, that's perfectly good reason for keeping the hash hard-coded, we should add a comment in the script saying why it's done that way.
