### ISSUE TITLE
Add missing db tags to SemanticAttributes: db.instance, db.type

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java#2158]
Tags are missing in SemanticAttributes:
- db.instance 
- db.type

Spec: https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table

**Comment by Oberon00** [comment]
Hi, as for #2159, we do not provide support for using the OpenTracing semantic conventions here. For OpenTelemetry semantic conventions for DBs, see https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md

**Comment by malafeev** [comment]
thanks @Oberon00
