### ISSUE TITLE
Add missing peer tags to SemanticAttributes

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java#2159]
Tags are missing in SemanticAttributes:
- peer.address
- peer.hostname
- peer.ipv4
- peer.ipv6
- peer.port

Spec: https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table

**Comment by Oberon00** [comment]
Hi, we do not provide support for using the OpenTracing semantic conventions here. They might be useful for the OpenTracing shim, but for OpenTelemetry the "tags" you mentioned are replaced by the attributes defined at https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/span-general.md#general-network-connection-attributes.

**Comment by malafeev** [comment]
thanks @Oberon00
