### ISSUE TITLE
OTLP Exporter not updated in maven

### ISSUE THREAD

**Issue by ballerabdude** [open-telemetry/opentelemetry-java#2163]
**Is your feature request related to a problem? Please describe.**
The latest version of the OTLP exporter is not in maven.
https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-exporters-otlp

**Describe the solution you'd like**
Can we update maven with the updated code

**Comment by jkwatson** [comment]
Hi @ballerabdude . We have recently renamed a bunch of modules to regularize the naming across all the various modules. In particular, we removed the plurals from the module names. So what you're looking for is here:  https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-exporter-otlp

**Comment by jkwatson** [comment]
Closing, as this renaming was covered in the 0.10.0 release notes. Sorry for the trouble, @ballerabdude !
