### ISSUE TITLE
Consider moving the baggage entry validation code to the W3CBaggagePropagator

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2200]
Currently, baggage entries (keys & values) are validated for W3C-correctness when they are added to the Baggage via the builder. This operation is not cheap, as it requires character-by-character inspection of both key & value. 

We should consider moving the validation to the propagator, so in-process Baggage usage would be cheaper and not need to conform to the W3C specification.

**Comment by jimshowalter** [comment]
If you move it out, please also make it overridable, which would solve https://github.com/open-telemetry/opentelemetry-java/issues/2935
