### ISSUE TITLE
TracingContextUtils was removed but still mentioned in JavaDoc

### ISSUE THREAD

**Issue by quijote** [open-telemetry/opentelemetry-java#2204]
While migrating some code from 0.10 to 0.12 I noticed that ``TracingContextUtils`` is still mentioned in docs:

    $ grep -I -r TracingContextUtils
    api/trace/src/main/java/io/opentelemetry/api/trace/Tracer.java: * try(Scope ss = TracingContextUtils.currentContextWith(span)) {
    api/trace/src/main/java/io/opentelemetry/api/trace/Tracer.java: * TracingContextUtils.getCurrentSpan().addEvent("Starting the work.");
    api/trace/src/main/java/io/opentelemetry/api/trace/Tracer.java: * TracingContextUtils.getCurrentSpan().addEvent("Finished working.");
    api/context/src/main/java/io/opentelemetry/context/propagation/ContextPropagators.java: * try (Scope scope = TracingContextUtils.currentContextWith(span)) {
    api/context/src/main/java/io/opentelemetry/context/propagation/ContextPropagators.java: * try (Scope ss = TracingContextUtils.currentContextWith(span)) {
    api/context/src/main/java/io/opentelemetry/context/Scope.java: * try (Scope ignored = TracingContextUtils.currentContextWith(span)) {

Unfortunately I do not know how what do use instead of ``TracingContextUtils.getCurrentSpan()`` so I decided to create a ticket instead of a PR.

**Comment by jkwatson** [comment]
Thanks for finding this! To your specific issue, you can get the span from the current context via: `Span.current()`.
