### ISSUE TITLE
Move B3 and Jaeger trace propagators

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java#2228]
We think it makes short-term sense to continue treating the `extensions/trace-propagators` like a "contrib" space to contain 3rd-party/contributed propagators (see the conversation in #2207).  With that, it makes less sense to leave the B3 and Jaeger propagators there, because they are first-party, supported propagators.

Let's move those two propagators into the `opentelemetry-api-trace` module (`api/trace`) and have them live in the `io.opentelemetry.api.trace.propagation` package as peers of the `W3CTraceContextPropagator`.

**Comment by jkwatson** [comment]
I'd like some resolution on https://github.com/open-telemetry/oteps/issues/142 before making this decision.

**Comment by bogdandrutu** [comment]
I think it is too late for this :) Long live jaeger and zipkin in the `extensions/trace-propagators`
