### ISSUE TITLE
TraceMultiPropagator vs. MultiTextMapPropagator

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java#2244]
There are two very similar ways and classes that allow multiple trace context propagators to be in play at the same time:
* TraceMultiPropagator - lives in extensions module, created by invoking `TraceMultiPropagator.create(...)`
* MultiTextMapPropagator - created by invoking `TextMapPropagator.composite(...)`

The implementations are very similar -- they both allow context injection and extraction by delegating to a list of other propagators.  However, there is a subtle difference between them,  due to the fact that `TraceMultiPropagator.extract()` stops extracting after the first success.

This subtle difference could be confusing to users.  
Since it does seem likely that users will want/need to support multiple formats, we should keep this...but we should avoid the duplicate implementation.  

Let's remove the `TraceMultiPropagator` and add a "stopAfterFirstFound" flag to the `MultiTextMapPropagator` constructor that will be referenced when extracting.  This should default to `false` to preserve the existing behavior.  
The implementation should also beef up the javadoc in `MultiTextMapPropagator`.

**Comment by carlosalberto** [comment]
(Guess that's why I preferred `StackPropagator` :D )

**Comment by breedx-splk** [comment]
Assign to me plz.

**Comment by breedx-splk** [comment]
> (Guess that's why I preferred `StackPropagator` :D )

@carlosalberto do you mind chiming in briefly on the comments in #2273?  Thank you.
