### ISSUE TITLE
Out-of-band Spans for the OT Shim

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#225]
The OT shim needs to support for creating out-of-band Spans (Spans with explicit start and/or finish time). A way to go around this is to use `SpanData` directly, and rely on similar data when exposing a `io.opentracing.Span` shim.

However, if an `openconsensus.trace.Span` object needs to be passed down to the **actual** api, a 'fake' object backed by something similar to `SpanData` could be passed, and this could become tricky if the code tries to cast it to an actual, concrete type. An example of this is setting the active `Span`:

```java
// OT Shim
try (Scope scope = tracer.activateSpan(span)) {
  // Underlying, a call to openconsensus.trace.Tracer.withSpan() is done,
  // passing a openconsensus.trace.Span backed by 'raw' data.
  doWork();
}

// OpenConsensus, somewhere down the doWork() chain,
// perhaps in an internal tracing method.
openconsensus.trace.Span span = tracer.getCurrentSpan();
((com.vendor.using.our.api.Span)span).internalMethod(); // will break
```

Our options here are:
1) Do not guaranteeing that actual, concrete `Span` objects will be passed around when using the Shim.
2) Do not support out-of-band `Span` creation for the OT shim, throwing an exception when the related methods are called.
3) Do not support out-of-band `Span` creation for the OT shim, simply ignoring the passed timestamps, and report them as tags/attributes (as we are currently doing).

@yurishkuro Any opinion on this?

**Comment by yurishkuro** [comment]
I would vote for the minimum work solution, i.e. option 2. It can be listed as an explicit limitation of the shim. If necessary, a better behavior could be added later. Or, if not too much work, do option 3 but log warnings that the explicit timestamps are ignored - it's still not the correct behavior, but it least it won't blow up user code.

**Comment by tedsuo** [comment]
I agree with Yuri: I also prefer `option 2` for now. We can determine better behavior later, after the SDK is more complete.

Hopefully the SDK will have something like an event handler which can emit warnings like this (or we add a Log interface to the project). I would prefer `option 3` in that case, assuming the shim can access it. I don't think that just logging to `stdout` would be enough.

**Comment by carlosalberto** [comment]
As a matter of fact, I haven't been able to find much code that uses this functionality, so, yeah, lets go with 2) then. 

3) is good but it's as @tedsuo said: we lack an event handler or common log that can be reachable from the OT shim.

So going for 2) for now.

Guess will be marking this issue as "Deferred" for the time being ;)

**Comment by bogdandrutu** [comment]
This is already implemented and we support custom start/end/events timestamps.
