### ISSUE TITLE
Remove metrics from the opentelemetry-api module and classes.

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2265]
Before 1.0, we must remove metrics (which are unstable at this point) from the `opentelemetry-api` module and the `OpenTelemetry` interface.

**Comment by jkwatson** [comment]
You would have to get access to the MeterProvider itself and use that. It'll be in an API module with a version tag with an `-alpha` suffix (or something akin to ghat).

**Comment by iNikem** [comment]
Will it be still available on `OpenTelemetrySdk.Builder`?

**Comment by jkwatson** [comment]
> Will it be still available on `OpenTelemetrySdk.Builder`?

It will not. We need to remove the metrics SDK from the omnibus classes until it's stable.

**Comment by iNikem** [comment]
Should #2262 then describe this as well? How do I configure SDK for both stable tracing and experimental metrics?

**Comment by jkwatson** [comment]
> Should #2262 then describe this as well? How do I configure SDK for both stable tracing and experimental metrics?

You won't be able to configure an `OpenTelemetrySdk` for both of those things. You'll configure the MeterProviderSdk independently and use it along side the stable signals provided by `OpenTelemetrySdk`. I believe I added many comments to that PR about this issue. :)

**Comment by jkwatson** [comment]
I think this is now done. Thanks!
