### ISSUE TITLE
Remove the metrics modules from the BOM

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2268]
We don't want non-stable signals to be in the otel java BOM. It will be required for users to manually add them as dependencies and keep the versions in sync themselves.

**Comment by breedx-splk** [comment]
Assign to me and I will take a stab.

**Comment by breedx-splk** [comment]
This should be closed now.

**Comment by jkwatson** [comment]
Thanks! closing
