### ISSUE TITLE
Comment missed in refactor

### ISSUE THREAD

**Issue by jamesylgan** [open-telemetry/opentelemetry-java#2270]
Includes an import and link to W3CTraceContextPropagator but should probably be B3Propagator.

https://github.com/open-telemetry/opentelemetry-java/blob/63aa8e91abc006a445c6edb5028cec98a3937da4/extensions/trace-propagators/src/test/java/io/opentelemetry/extension/trace/propagation/B3PropagatorTest.java#L29

**Comment by jkwatson** [comment]
Thanks! We should really just remove that extraneous javadoc altogether.
