### ISSUE TITLE
Inconsistent import style

### ISSUE THREAD

**Issue by jamesylgan** [open-telemetry/opentelemetry-java#2276]
https://github.com/open-telemetry/opentelemetry-java/blob/d4bddd1fdf56fa957a57d13231f7450a06cb7f2d/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/B3PropagatorExtractorMultipleHeaders.java#L8

In other B3Propagator files, the imports are `B3Propagator.` and rely on existing within the same package as the main propagator class- but in the multiheader and singleheader extractor, on the other hand, static imports are used to access these.

This has minimal impact on developers, mostly just a code style thing. Probably best to be consistent at least between different components for the propagator.

**Comment by breedx-splk** [comment]
Yup, it's inconsistent between the files.  Thanks for pointing this out, I'll put in a change to make it more consistent.
