### ISSUE TITLE
Attributes.get() method does not provide type safety

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#2282]
Since `AttributeKey.equals()` does not include the type, the compiler thinks that this code is type safe, but it will throw `ClassCastException`:

```
AttributeKey<Long> key = AttributeKey.longKey("mykey");
Attributes attributes = Attributes.of(key, 5L);
String value = attributes.get(AttributeKey.stringKey("mykey"));
```

If nothing can be done about this, a warning in the `Attributes.get()` javadoc would be helpful.

**Comment by jkwatson** [comment]
Do you have a preferred behavior if not the current? I could see: throwing a better exception or returning null.

**Comment by trask** [comment]
I think returning null would be most expected to me when looking at the method signature.

If we find there's a use case for getting an attribute value by key name only, we could introduce `Object get(String attributeKey)` later.

**Comment by jkwatson** [comment]
yes, even though the .equals doesn't include the type, we should include the type on the `get` call, so we properly return null.
Good catch.
