### ISSUE TITLE
TracerSdkProvider or TracerProviderSdk?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#2290]
I always get confused by the naming of the SDK implementations since they feel inconsistent. `SpanBuilderSdk`, `TracerSdk` add a `Sdk` suffix to the interface they are implementing. `TracerSdkProvider` has `Sdk` in the middle. Presumably the latter name is because it's a provider of `TracerSdk` but I would lean towards consistency in suffixing API interface name with `Sdk`. `TracerSdkProvider` is the only public class, though, so I guess it's name is most important. In that sense too, since `TracerSdk` is an internal class, naming the API a provider of that hidden class has no real meaning, and I guess just the suffix could be easier to grok for end users.

What do people think?

**Comment by anuraaga** [comment]
Ah, or `SdkTracerProvider` might make the most sense, I guess it's common to _prefix_ an interface, not suffix

**Comment by iNikem** [comment]
+1 for `SDKXxxx`

**Comment by Oberon00** [comment]
If possible, we should make that class package-private anyway (now that we have the Management interface implemented by it).

**Comment by jkwatson** [comment]
> If possible, we should make that class package-private anyway (now that we have the Management interface implemented by it).

we'll need a public builder, but it would be a good restriction if the class itself could be non-public, 👍

**Comment by jkwatson** [comment]
BTW, much prefer `Sdk` as a prefix, so 👍

**Comment by anuraaga** [comment]
Thanks!
