### ISSUE TITLE
Remove helper functions that deal with Runnable/Callable

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#234]

**Comment by tylerbenson** [comment]
Are you referring to those provided by https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/openconsensus/sdk/trace/internal/CurrentSpanUtils.java?  If so I'm curious why... Those seem somewhat useful.

**Comment by bogdandrutu** [comment]
We are referring to remove from the Tracer the `withSpan(Span, Runnable)` and put them in a contrib package for the moment.

**Comment by bogdandrutu** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-java/pull/246
