### ISSUE TITLE
Move protos to opentelemetry-proto repo.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#235]

**Comment by kaushikchaubal** [comment]
Looks like changes for this was merged, right? Is it worth closing the issue?

**Comment by pavolloffay** [comment]
The protos have been copied but they are still here https://github.com/open-telemetry/opentelemetry-java/tree/master/sdk/src/main/proto. Maybe it would be better to consume them as a git submodule.

**Comment by kaushikchaubal** [comment]
Do you want me to create a git submodule for https://github.com/open-telemetry/opentelemetry-java/tree/master/sdk/src/main/proto then? If so, I can aim to create a PR for that.

**Comment by pavolloffay** [comment]
Let's see what others say, I think it's a good idea.

**Comment by songy23** [comment]
+1 to git submodule.
