### ISSUE TITLE
Metrics are exported in every export cycle even if the value doesn't change

### ISSUE THREAD

**Issue by sfarsaci** [open-telemetry/opentelemetry-java#2414]
**Describe the bug**
Metrics are re-exported during each export cycle, even if they were previously exported and there are no changes in the value since the last export.

**Steps to reproduce**
The issue can be observed running [this example](https://github.com/sfarsaci/otel-counters-exported-multiple-times) and looking at the logs.

**What did you expect to see?**
Metrics are not exported again if the value hasn't changed since the last export.

**What did you see instead?**
All metrics are re-exported each time the exporter runs.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk` `opentelemetry-exporters-logging`
Version: `0.13.1`
```
dependencies {
    compile group: 'io.opentelemetry', name: 'opentelemetry-sdk', version: '0.13.1'
    compile group: 'io.opentelemetry', name: 'opentelemetry-exporter-logging', version: '0.13.1'
}
```

**Environment**
Compiler: n/a
OS: macOS Big Sur 11.1

**Additional context**
In our real use case we are exporting metrics with high cardinality, and the instrumented application doesn't survive more than a couple of hours under small load (nowhere near production load). Because we re-export all the metrics each time, the payload size grows in an arithmetic progression and exhausts the grpc's capabilities pretty fast.

**Comment by jkwatson** [comment]
Hi @sfarsaci . In your sample, you `bind` with every recording, but you never `unbind` the bound instruments. When you call `bind`, the expectation is that that particular bound instrument should be long-lived. You don't need to create bound instruments with every recording. Instead, just make a recording with the labels directly. Can you give this a try?

**Comment by sfarsaci** [comment]
Hi @jkwatson , thanks for your suggestion.

I tried `recorder.add(1, labels)`, which I see does the unbinding:

`public void add(long increment, Labels labels) {
    BoundInstrument boundInstrument = bind(labels);
    try {
      boundInstrument.add(increment);
    } finally {
      boundInstrument.unbind();
    }
  }`

Unfortunately I see the same behavior.

I've updated my repo and I'm gonna do some debugging, I'll let you know if I find something. Meanwhile please let me know if you have any ideas.

**Comment by sfarsaci** [comment]
I'm under the impression that the problem is in `io.opentelemetry.sdk.metrics.InstrumentProcessor#completeCollectionCycle()`. It holds a map of aggregators and clears it up only for delta style exports.

Is the expected behavior to remove instruments that are unbound after they've been exported? If so I can work on a PR

**Comment by jkwatson** [comment]
I don't think it's quite that simple. For instance, if you have cumulative counters, they need to continue accumulating, even if they get no recordings during a given collection cycle. And, even if the bound calling convention isn't being used, you don't want to reset those cumulative counters (or the counter + labelset combination, more precisely) every time that a recording isn't made during a given cycle.

I'm honestly not sure what the right answer is here. I assume you *want* cumulative counters, and not delta counters? If you can live with deltas, you could set up a view that changes your counters to be delta-only to work around this.

@bogdandrutu your thoughts?

**Comment by sfarsaci** [comment]
Hi @jkwatson , we decided to go with delta counters and setting up a view for the counters to be delta-only as per your suggestion. [It works as expected.](https://github.com/sfarsaci/otel-counters-exported-multiple-times/tree/delta-export-for-counters) Thanks for your help on this.
