### ISSUE TITLE
The SDK will raise an NPE to the client code if span name is null.

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2424]
**Describe the bug**
The SDK should never adversely impact (aside from possible performance implications) client code. If instrumentation sets a null span name, an NPE is thrown by the SDK when trying to convert to SpanData for the export pipeline. This NPE ends up in the client's application code, which is not acceptable.

**Steps to reproduce**
Install the SDK, start and end a span with a null `name`.

**What did you expect to see?**
Maybe a logged warning, maybe nothing? I'm honestly not sure exactly what is the correct behavior here. Should the Span be sent to the span processor with a null name? Should it be silently dropped?

**What did you see instead?**
A NullPointerException interrupting client code.

**What version and what artifacts are you using?**
OTel API & SDK 0.13.1.

**Comment by dengliming** [comment]
It seems that Zipkin also throws an exception directly.
```
  /** @see brave.Span#name(String) */
  public void name(String name) {
    if (name == null) throw new NullPointerException("name == null");
    this.name = name;
  }
```
Personally. logged warning or dropped seems fine to me. :D

**Comment by anuraaga** [comment]
I would create a span with an artificial name, maybe `<null>`. Breaking a trace because of the null seems like a huge loss of information compared to just scrubbing the name

**Comment by jkwatson** [comment]
> I would create a span with an artificial name, maybe `<null>`. Breaking a trace because of the null seems like a huge loss of information compared to just scrubbing the name. We could even add an attribute to the span with the error.

Would you do the same for a blank name? I think we probably should, but opinions welcome.
