### ISSUE TITLE
Collecting stacktraces on error

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java#243]
When an error occurs, we should capture the full stacktrace on the span, not just the message.  When trying to troubleshoot an error, the full stacktrace is far more useful in providing context than just the error message.

(See comment [here](https://github.com/open-telemetry/opentelemetry-java/pull/229#discussion_r280252988))

**Comment by tedsuo** [comment]
@tylerbenson this seems great to have. Once we get the SDK into working condition, we should address this.

**Comment by pavolloffay** [comment]
We could also consider adding `Span.error(Throwable throwable)` method. The implementation can derive message/stacktrace based on the configuration (if need to be disabled for perf reasons).

**Comment by tylerbenson** [comment]
@pavolloffay my one concern with that is sometimes it's nice to attach a stacktrace that isn't really an "error".

Making it more generic, while also providing improved flexibility in the future, I'd suggest the following:

```java
Span.attach(Throwable throwable)
Span.attach(Object obj)
```

**Comment by jkwatson** [comment]
This is being addressed by #1434

**Comment by jkwatson** [comment]
closing this with the merging of #1434
