### ISSUE TITLE
Publishing for many modules is not working

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2437]
It looks like we stopped publishing a bunch of artifacts (the sdk extension modules for instance) on Dec 17.

**Comment by jkwatson** [comment]
@anuraaga this corresponds to the point when we changed the directory structure/module naming scheme, so it could be related.

**Comment by anuraaga** [comment]
Fixed in #2441

**Comment by jkwatson** [comment]
@anuraaga FYI, it looks like the JFR events module hasn't ever been publishing. Not sure what's up with that.
