### ISSUE TITLE
Current semconv are under a "trace" package but they are also resource semconv

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2457]
See https://github.com/open-telemetry/opentelemetry-java/blob/master/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java#L34

**Comment by jkwatson** [comment]
Yes, this is definitely a problem. The resource attributes should be a part of the `ResourceAttributes` class, and also auto-generated. This has been a problem for quite a while. Good catch!

**Comment by jkwatson** [comment]
In addition, our ResourceAttributes are not up to date with the current semconv spec. [for instance, we have `os.name` rather than the current `os.type`]
