### ISSUE TITLE
Add Rust to Language enum?

### ISSUE THREAD

**Issue by kazimuth** [open-telemetry/opentelemetry-java#248]
Currently there are only a small number of languages in the LibraryInfo enum:

https://github.com/open-telemetry/opentelemetry-java/blob/898f81bf1ca81810061f766e909dad06e2cfb01c/sdk/src/main/proto/agent/common/v1/common.proto#L66-L77

I'd like to write a Rust implementation of OpenTelemetry once the Cross-Language Specification is released. It would be nice if that option were available.

**Comment by bogdandrutu** [comment]
Extending the proto enum is possible at any moment. Happy to add Rust when the work starts.

**Comment by tedsuo** [comment]
Thanks @kazimuth! I'm going to close this issue for now, since the protos are going to move to another repo. Please open it there once the rust project is underway.
