### ISSUE TITLE
Published OpenTelemetry API pom has a bad context dependency

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2485]
The opentelemetry-api pom.xml has this dependency in it:

```xml
    <dependency>
      <groupId>io.opentelemetry.api</groupId>
      <artifactId>context</artifactId>
      <version>0.14.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
```

But it should be : 

```xml
 <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-context</artifactId>
      <version>0.14.0-SNAPSHOT</version>
  </dependency>
```

Note: the bom does have the correct dependency in it.

**Comment by jkwatson** [comment]
Note: there are a number of poms for which this is messed up similarly. 

`opentelemetry-api-metrics`
`opentelemetry-exporter-jaeger`

Basically, anything that has a project dependency looks like it's pom is confused about what the published groupId/artifactIds are.

**Comment by jkwatson** [comment]
Note: it looks like everything was fine in 0.13.1, so this only an issue for the 0.14.0 snapshots at this point.

**Comment by jkwatson** [comment]
For the incorrect groupId: It looks like the workaround for https://github.com/gradle/gradle/issues/847 by hacking the group identifier unfortunately leaked into the publications.

**Comment by anuraaga** [comment]
Worked around by #2496
