### ISSUE TITLE
example to integrate metric with logging or jmx exporter

### ISSUE THREAD

**Issue by maneeshbhunwal123** [open-telemetry/opentelemetry-java#2508]
I have integrated with opentelemetery java sdk manually. And now i want to the metric that i am publishing to opentelemetery sdk. I am not finding any examples to do so, can someone please help here? I would be happy to add the steps as a PR.

**Comment by jkwatson** [comment]
Yes, it would be very useful to have some metrics examples that include an exporter which isn't prometheus. 

If you look at the current metrics examples, it should be as simple as setting up an `IntervalMetricReader` with an exporter attached, and assigning the SdkMeterProvider's MetricProducer to it.

A PR to add this to the metrics examples would be great!

**Comment by maneeshbhunwal123** [comment]
where should it be added, i got it working, 
should it be added https://opentelemetry.io/docs/java/?

**Comment by jkwatson** [comment]
If you could add a running example to our `examples` project, that would be a great start.

**Comment by jkwatson** [comment]
closing. resolved with #2789
