### ISSUE TITLE
Add jmx exporter

### ISSUE THREAD

**Issue by maneeshbhunwal123** [open-telemetry/opentelemetry-java#2522]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Send opentelemetery collected metrics to jmx

**Describe alternatives you've considered**

**Additional context**
There are few exporters written already but i dont see support for writing to jmx mean. Can we add a exporter for this as well?

**Comment by jkwatson** [comment]
I'm not opposed to this, but it's unlikely that the maintainers of this project will have time to do this in the near future. Would you be willing to contribute code for this?

**Comment by maneeshbhunwal123** [comment]
i will discuss internally and get back.

**Comment by breedx-splk** [comment]
@maneeshbhunwal123 Some time has passed, any more thoughts on this?

Writing to JMX feels like an unusual use case to me. Were you thinking about writing to a remote MBean or local to the same JVM? In any case, would be interested to hear what your use case is, and if this request is still relevant/meaningful. Thanks.

**Comment by maneeshbhunwal123** [comment]
we are publishing to local mbean. there is a sidecar process running which keep on reading values from mbean, and send it to remote server. Where it can be plotted using grafana.

the use case i am trying to tackle is, let's say i send a timer metric 2 different places with 2 different tags. If the frequency, timer metrics values  of both these tags is similar then we can just average and look at metric, **but when the 2 have very different pattern** (either rate (lets say 1 is 1000 hit par sec vs another is 10 hit par sec, now 10 hit par sec is much more suspect-able to spikes)or metrics values) i want to see if we can aggregate before publishing itself. As I don't know if any metric plotter (we use grafana) can take weight(oneminuterate) into account while plotting.

@breedx-splk let me know if any further questions.

**Comment by breedx-splk** [comment]
> we are publishing to local mbean. there is a sidecar process running which keep on reading values from mbean, and send it to remote server. Where it can be plotted using grafana.

Interesting and unusual use case, thanks for sharing. Are you still considering writing an exporter for this? Just curious.

**Comment by maneeshbhunwal123** [comment]
for now we used codehale metric registory because both aggregation and jmx reporter was not there at that point of time. 

I can not commit to writing exporter at this time. But i believe it should not take too much time, as i have seen codehale jmx repoter code, and it was straight foreward.
