### ISSUE TITLE
Consider changing property naming convention

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#2526]
The Java instrumentation repo is using `-` instead of `_` in property names, e.g. `otel.java.disabled.resource-providers` instead of  `otel.java.disabled.resource_providers`.

Copying comment here from https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1414#issuecomment-733181398 in favor of kebab-case:

[Spring Boot env var / system property mappings](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-relaxed-binding) supports both camelCase and kebab-case, but recommends kebab-case:

> Property | Note
> -- | --
> acme.my-project.person.first-name | Kebab case, which is recommended for use in .properties and .yml files.

And also interestingly:

> The prefix value for the annotation must be in kebab case (lowercase and separated by -, such as acme.my-project.person).

**Comment by bogdandrutu** [comment]
@jkwatson I think this needs to happen before 1.0 if we want to do it

**Comment by jkwatson** [comment]
this is all in the auto-instrumentation module, which is still tagged as `-alpha` so we can still address it after 1.0.0, I believe. Also... do we actually have anything with dashes or underscores at all right now? My quick search didn't uncover any.

**Comment by jkwatson** [comment]
oh...the only one I found was `"otel.java.disabled.resource_providers"` (and, yes, obviously this was what was being talked about).

**Comment by jkwatson** [comment]
And, this isn't in the autoconfigure module.  🤦   sorry for the brain fart.

**Comment by jkwatson** [comment]
I don't have much of an opinion on this one at all. Consistency with auto-instrumentation is probably the most important thing.

**Comment by jkwatson** [comment]
does the otel spec have any opinion (even implicit) in the naming of things like this?
