### ISSUE TITLE
Unable to remove baggage from context or set Baggage.empty()

### ISSUE THREAD

**Issue by ChandrewR** [open-telemetry/opentelemetry-java#2553]
Once the context is created with bagagge, I'm unable to remove the baggage. 

Steps to reproduce: 
1. Create a context with baggage. 
 Baggage baggage = Baggage.builder().put("key", value")
 Context context = Context.current().with(baggage);
 validateBaggage(context);
 B3Propgator.getInstance.inject(context, carrier, setter);
2. Get the baggage, validate and remove the baggage from Context.
public void validateBaggage(Context context) {
Baggage baggage = Baggage.fromContext(context);
//Validating baggage values
baggage.forEach((key, value, metadata) -> {
//if validation fails, set the context with empty bagagge
context.with(Baggage.empty());
}
}

I expected to see the empty baggage..But the bagggae is not empty. I still see the baggage values injected..

Artifacts: (`opentelemetry-api`, `opentelemetry-sdk`, which exporters, etc)
Version: ( `0.13.1`, )

**Environment**
OS: ("Windows")
Runtime (if different from JDK above): ("Oracle JRE 8u251")

Can you please let me know, how to remove the Baggage from the context..? Help on this

**Comment by anuraaga** [comment]
Hi @ChandrewR - context is immutable, so `with` returns a new object. You will need your method to return `Context`, and either return the original on validation success or a new one using `with` on failure.

**Comment by ChandrewR** [comment]
Ok @anuraaga . Thanks..Is there a way to remove the entry from Baggage? I see that we can remove from BaggageBuilder but cannot remove from Baggage..

**Comment by anuraaga** [comment]
Would `baggage.toBuilder().remove()` work ok?

**Comment by ChandrewR** [comment]
Thanks for the info.
