### ISSUE TITLE
API: Package names consistency

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#259]
Currently we use singular (noun or verb) and plural (nouns):
* trace
* metrics
* tags

Should we go with only plurals?
* trace**s**
* metrics
* tags

Maybe resource**s** as well?

**Comment by bogdandrutu** [comment]
Any thought on this?

**Comment by tylerbenson** [comment]
I'm leaning towards the plural for everything (including resources) since I think consistency is nice and `metric` and `tag` sound weird.

**Comment by SergeyKanzhelev** [comment]
Maybe: 

- trace**ing**
- metrics
- tags

I'm good with `traces` though. Agree about consistency

**Comment by tedsuo** [comment]
## 5/29 Discussion

Let's stick with what we have, but pluralize resources.

* trace
* metrics
* tags
* resources
