### ISSUE TITLE
Release 0.7.0 was not released properly

### ISSUE THREAD

**Issue by gcacace** [open-telemetry/opentelemetry-java#2593]
If you go to https://github.com/open-telemetry/opentelemetry-java/releases the release 0.7.0 doesn't show up like 0.6.0, and it seems it's not linked to a tag.

**Comment by Oberon00** [comment]
0.7.0 shows up normally, but 0.7.1 seems to be only a tag, not a GitHub release.
https://github.com/open-telemetry/opentelemetry-java/releases/tag/v0.7.0 vs https://github.com/open-telemetry/opentelemetry-java/releases/tag/v0.7.1

**Comment by gcacace** [comment]
Sorry I meant to open this into the opentelemetry-proto package. Closing.
