### ISSUE TITLE
API: Span parent/remote parent

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#261]
Currently on the Tracer we have 3 different APIs:
```java
class Tracer {
  Span.Builder spanBuilder(String spanName);

  Span.Builder spanBuilderWithExplicitParent(String spanName, @Nullable Span parent);

  Span.Builder spanBuilderWithRemoteParent(String spanName, @Nullable SpanContext remoteParent) ;
}
```

Proposal to simplify this by having the setParent and setRemoteParent on the Builder.
```java
class Tracer {
  Span.Builder spanBuilder(String spanName);
}

// Option 1:
class Span.Builder{
  // If a null parent or BlankSpan is set then the new Span will become a root Span.
  // If non of the setParent variants is called then the parent is inherited from the Context.
  // If any of the setParent is called it overwrites any previous call.
  Span.Builder setParent(@Nullable Span parent);
  Span.Builder setParent(@Nullable SpanContext remoteParent) ;
}

// Option 2:
class Parent {
  // 3 state class:
  // - a Span as parent
  // - a SpanContext as remote parent
  // - NO Parent (root span)
}

class Span.Builder{
  // By default if no parent set the parent is inherited from the Context.
  Span.Builder setParent(Parent parent);
}

```

**Comment by yurishkuro** [comment]
option 1

**Comment by pavolloffay** [comment]
What is the difference between `spanBuilderWithExplicitParent` and `spanBuilderWithRemoteParent`?Does it use differnet relationshift/link between spans? If so API `Span.Builder setParent(@Nullable SpanContext remoteParent)` can be accidentally used with `spanBuilder.setParent(span.context())`. Perhaps keeping `remote` in name makes sense if it sues a different relationship.

We should also clarify when the inherited context is added as a parent. At span builder creation time or build?

**Comment by bogdandrutu** [comment]
remote in this case means a SpanContext coming from the wire, so users should never use spanBuilder.setParent(span.context()) for in-process parent-child relationship.

Implementation may treat the remote SpanContext as link if the incoming request is not trusted.

**Comment by tedsuo** [comment]
Discusion:
* The main issue is monotonic clocks. We'd like to keep them on the Span, not the SpanContext
* In C++, SpanContext needs to stay small so that it can be passed on the stack. 
* But in other languages, this matter less.
* So the monotonic clock _could_ move to the SpanContext if this proves necessary.

Use cases for setting parent via a SpanContext:
* Extracted SpanContext
* Synthetic SpanContext (continuing a trace from another system)
* Confused users calling `setParent(span.getContext())`

Conclusion:
* `Option 1` looks like the best interface.
* Explicitly document that calling `setParent(span.getContext())` is not preferred or necessary. If you have a span, use that object directly by calling `setParent(span)`.

**Comment by tylerbenson** [comment]
@bogdandrutu if preventing usage like `setParent(span.getContext())` is a big concern, you could have a remote parent context be a distinct type from the context stored inside span.  Not sure this is worth the hassle though.

**Comment by bogdandrutu** [comment]
That was our conclusion as well.

**Comment by mayur-more** [comment]
Hi, I am new to OpenTelemetry word. I have created spans for my services separately, but when i am try to combine spans of two different services, using context propogation, I am not able to do it successfully.
I have used following code:
// at client side:
public static void sendContext(String resource) {
    TextMapSetter<HttpURLConnection> setter =
        new TextMapSetter<HttpURLConnection>() {
          @Override
          public void set(HttpURLConnection carrier, String key, String value) {
            carrier.setRequestProperty(key, value);
          }
        };
    HttpURLConnection transportLayer = null;
    String urlString = "http://127.0.0.1:8080" + resource;
    try {
      URL url = new URL(urlString);
      transportLayer = (HttpURLConnection) url.openConnection();
    } catch (MalformedURLException ex) {
      System.out.println(ex.getMessage());
    } catch (IOException e) {
      System.out.println(e.getMessage());
    }
    GlobalOpenTelemetry.getPropagators()
        .getTextMapPropagator()
        .inject(Context.current(), transportLayer, setter);

// at server side:
public static Context getContext(HttpServletRequest request) {
    TextMapGetter<HttpServletRequest> getter =
        new TextMapGetter<HttpServletRequest>() {
          @Override
          public String get(HttpServletRequest carrier, String key) {
            Enumeration<String> headerNames = carrier.getHeaderNames();
            if (headerNames != null) {
              while (headerNames.hasMoreElements()) {
                String headerName = headerNames.nextElement();
                if (headerName.equals(key)) {
                  String headerValue = request.getHeader(headerName);
                  return headerValue;
                }
              }
            }
            return null;
          }

          @Override
          public Iterable<String> keys(HttpServletRequest carrier) {
            Set<String> set = new HashSet<String>();
            Enumeration<String> headerNames = carrier.getHeaderNames();
            if (headerNames != null) {
              while (headerNames.hasMoreElements()) {
                set.add(headerNames.nextElement());
              }
            }
            return set;
          }
        };
    Context extractedContext =
        GlobalOpenTelemetry.getPropagators()
            .getTextMapPropagator()
            .extract(Context.current(), request, getter);

At server, i am not able to get parent span. 
Kindly help on this.

**Comment by jkwatson** [comment]
@mayur-more this issue has been closed for a long time. If you're having difficulties, can you create a new discussion about it here: https://github.com/open-telemetry/opentelemetry-java/discussions

**Comment by mayur-more** [comment]
Thanks. 
I have posted it at https://github.com/open-telemetry/opentelemetry-java/discussions/3255
