### ISSUE TITLE
Duplication of attributes in `SpanWrapper.toString()`

### ISSUE THREAD

**Issue by kenfinnigan** [open-telemetry/opentelemetry-java#2613]
**Describe the bug**
When printing out `SpanData` instances that were captured, all the attributes on the span are output once as a value on the delegate of `SpanWrapper`, `RecordEventsReadableSpan`, and then again as attributes on `SpanWrapper` directly.

**What did you expect to see?**
I would expect to see the attributes listed only once unless the sets are not meant to be identical.

**What did you see instead?**
It was initially confusing as it had me wondering whether there was a copy, or they were different attributes that just happened to be the same in the case I saw.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk`, `opentelemetry-sdk-testing`
Version: 0.14.1
How did you reference these artifacts?
```
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk-testing</artifactId>
            <scope>test</scope>
        </dependency>
```

**Environment**
Compiler: openjdk version "11.0.8"
OS: Mac Big Sur

**Additional context**
From a chat with @jkwatson on gitter, maybe there's a way to suppress the output of attributes on `SpanWrapper` when calling `toString()`?

**Comment by bogdandrutu** [comment]
Can you add an output example?

**Comment by anuraaga** [comment]
Yeah added a test to demonstrate this, but haven't gotten around to fixing it yet

https://github.com/open-telemetry/opentelemetry-java/blob/15fcadd8d7e7b139f30260bd575b112b827c2734/sdk/trace/src/test/java/io/opentelemetry/sdk/trace/SdkSpanBuilderTest.java#L897

**Comment by kenfinnigan** [comment]
Thanks @anuraaga.

Is that sufficient @bogdandrutu?

**Comment by bogdandrutu** [comment]
Yes, I actually found the bug but waiting for a decision on the https://github.com/open-telemetry/opentelemetry-java/pull/2660 before moving forward with the fix because that will influence a bit how I will fix it :)

**Comment by kenfinnigan** [comment]
not a problem, just wanted to check nothing else was needed from me
