### ISSUE TITLE
Ensure all List/Arrays that we export via different getters are immutable / unmodifiable

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2623]
We have couple of places where we do expose Lists, we need to double check that we always return a new list or an unmodifiable/immutable list if we return the same object multiple times.

This is a tracking issue to ensure we do this before final release.

**Comment by anuraaga** [comment]
Checked this and while I could have missed something, I think we're good. In worst case, I have this class ready for copy-paste :) https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-core/src/main/java/com/amazonaws/xray/entities/NoOpList.java

**Comment by jkwatson** [comment]
Closing this, as the research has been done, and resulted in one fix.
