### ISSUE TITLE
Strange name of TraceConfig and Sampler is not part of the config.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2626]
Based on a user feedback the java implementation changed and moved Sampler from TraceConfig as top level.

The problems that I see with this:
* The name TraceConfig kind of implies it includes all configuration related to tracing (Sampler being one of them). So I suggest we either move Sampler back or change the name of TraceConfig to something like SpanRecordLimits or something like that.
* The current TraceConfig in Java is different than the (alpha proto definition) as well as the other languages. This may be confusing.

**Comment by anuraaga** [comment]
Well, id generation, resource, even exporters I would consider configuration related to tracing, so this has been happening for a while. I considered renaming to `TraceLimits` or similar, but figured not renaming doesn't break the status quo and would be less controversial.

The proto's alpha and there is going to be an entire Sampling SIG which I strongly suspect will come up with a very different way for remote sampling. There doesn't seem to be a strong reason for the SDK to match that, nor is there any other spec related to it.

That being said, if others are up to it, a rename to `TraceLimits` or something would probably still be fine.

**Comment by bogdandrutu** [comment]
SpanLimits I think is more accurate

**Comment by anuraaga** [comment]
> SpanLimits I think is more accurate

It seems to reduce the extension to future more general limits unless creating another class. Don't limits on individual spans also feel natural as limits on traces?

**Comment by bogdandrutu** [comment]
I think this class as it is right now (especially with the Supplier contract) has to be called once at the start of any Span and apply for the entire lifetime of that instance. So once we will define clearly the contract I don't think we can add things that apt to Trace level

**Comment by jkwatson** [comment]
If we're ok with this pre-1.0 SDK-breaking change, I'm fine with `SpanLimits`. Seems concise and is more descriptive than the vague `TraceConfig`.

**Comment by anuraaga** [comment]
Fixed by #2686
