### ISSUE TITLE
Consider to not expose DefaultOpenTelemetry class

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2629]
Right now this class does not have a clear use for being public. Because of this java API should not publicly expose this class and it should be package protected until we get a clear use-case to expose it publicly.

**Comment by jkwatson** [comment]
The use we have for this at the moment are these: 

a) User wants a no-op OpenTelemetry instance with customized propagators. 
b) User wants to provide a completely non-SDK implementation of the TracerProvider. 

If we need this functionality, and we want to keep our implementation as configuration-immutable as possible, we need to expose something to enable these use-cases. Do you have another idea?

**Comment by anuraaga** [comment]
Will evaluate some options, perhaps a factory method just to return a no-op/with propagators instance.
