### ISSUE TITLE
Should we extract Span.Kind as a top level SpanKind?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2635]
So this in one of the PRs and want to document to make a decision

**Comment by jkwatson** [comment]
I would be ok with this, if we're ok with one last breaking API change before 1.0. I think we could survive without it, but it is one little wart on the API that would be nice to polish before release.

**Comment by bogdandrutu** [comment]
I can see this of one of the most used inner class out of all that we had, so if we did all the changes for good reasons, I see no point in not doing this one as well.

**Comment by jkwatson** [comment]
@anuraaga unless you are strongly opposed to this late change, I say we fix it while we still can.

**Comment by jkwatson** [comment]
Thinking further...

Before we make any breaking API changes at this point, I'd like to make sure all of the maintainers are ok with it. This will break existing instrumentation and users.
