### ISSUE TITLE
BaggageEntry vs Map.Entry

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2651]
There is an inconsistency for usage of the term `Entry` between what we call in Baggage an Entry and what is well known as a `Map.Entry`.

**Comment by anuraaga** [comment]
@bogdandrutu Can you clarify?

**Comment by bogdandrutu** [comment]
We have a class called BaggageEntry which is does not include the Key as the Map.Entry

**Comment by anuraaga** [comment]
Ah - yeah we'd avoid adding key to that since we expose iteration as `Map<String, BaggageEntry>`, which would expose `Set<Map.Entry<String, BaggageEntry>>`. We could potentially rename to `BaggageItem` if this seems confusing, I don't find the current name too bad either though.

**Comment by jkwatson** [comment]
I don't find this very confusing either. I think people can generally distinguish between a Map.Entry and entries of other kinds. I vote we don't change this at this point.

**Comment by bogdandrutu** [comment]
I think `BaggageItem` is ok for.

**Comment by anuraaga** [comment]
I also vote for not changing, same reasoning as @jkwatson. But if renaming to `Suitcase`, then that would be a name worth doing so for :D

**Comment by anuraaga** [comment]
We discussed this and didn't find there to be significant confusion vs `Map.Entry` and can keep as is.
