### ISSUE TITLE
Strange name for Baggage `getEntryValue`

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2653]
https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/baggage/Baggage.html#getEntryValue(java.lang.String)

If we refer to the baggage as a map then we should return the `BaggageEntry` which contains all the values associated with the key

**Comment by jkwatson** [comment]
My opinion: I think we can live with this as-is. The name's a little odd, but the whole baggage API is a little odd, as currently specified.

**Comment by anuraaga** [comment]
We think most accesses of Baggage, if they happen in business logic, are for the value. If there is user demand for getting metadata, we can add an accessor `getEntryMetadata` for the metadata as well in the future. We could also consider `get()` or `getEntry()` that returns `BaggageEntry` at that point too.
