### ISSUE TITLE
Hardcoded name in the API package may need to change

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2659]
Currently we use `Class.forName("io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration");` to load the autoconfiguration module.

Some problems:
* The package name should include `extension` because we have this as an extension to follow the same rules;
* Why do we not use SPI instead of `Class.forName()`?

**Comment by anuraaga** [comment]
> The package name should include extension because we have this as an extension to follow the same rules;

We were actually considering moving this to the top level of the folders considering its an entry point rather than functionality, but yeah otherwise we should probably make the package consistent.

> Why do we not use SPI instead of Class.forName()?

We don't want to add a public API to the `api` package for this - it's currently a pure implementation detail of our codebase. Maybe we will later, but we can defer it at the expense of updating that package name if unit tests fail when moving that class around.

**Comment by bogdandrutu** [comment]
>We were actually considering moving this to the top level of the folders considering its an entry point rather than functionality, but yeah otherwise we should probably make the package consistent.

FYI: changing the hardcoded name is ABI incompatible change (or maybe I am wrong). Can you confirm that we can change the name and not break users?

> We don't want to add a public API to the api package for this - it's currently a pure implementation detail of our codebase. Maybe we will later, but we can defer it at the expense of updating that package name if unit tests fail when moving that class around.

This needs to be document as a comment around the "Class.forName"

**Comment by anuraaga** [comment]
> FYI: changing the hardcoded name is ABI incompatible change (or maybe I am wrong). Can you confirm that we can change the name and not break users?

`autoconfigure` is still `-alpha` so is not targeted for ABI stability in 1.0.0. This is mainly because of the env variable churn though, so once those are stable we will also want to be sure of our package name before flipping the release flag on this artifact.

**Comment by anuraaga** [comment]
Also, package name for this can be changed actually since our policy expects using the BOM so artifacts within our codebase are always consistent.
