### ISSUE TITLE
Rename `getActiveTraceConfig` to `getTraceConfig` since no notion of active is present in the SDK.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2664]

**Comment by jkwatson** [comment]
I'm ok with this as-is. It's slightly weird to have the word "active" in there, but it's also technically correct.

**Comment by anuraaga** [comment]
We can wrap this in with renaming to `SpanLimits`

**Comment by anuraaga** [comment]
Fixed by #2686
