### ISSUE TITLE
Cleanup TraceId and SpanId APIs

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2666]
After the refactoring when TraceId and SpanId were embedded in the SpanContext, these classes became utils/helpers. Since then the names of the methods are no longer consistent and some of them are unnecessary:
* ~~copyHexInto - not used outside the TraceID class~~
* fromLong[s] - return the hex representation. We should follow the same conventions as for the bytes/hex helpers and name these hexFromLong[s]
* SpanId.asLong accepts `CharSequence` but all other methods related to the hex representation accept `String`.
* traceIdHighBytesAsLong and traceIdLowBytesAsLong suggest that they convert from the bytes (probably I misunderstand this) but they actually accept hex version. And again inconsistent being the only once with `CharSequence`
* bytesFromHex/bytesToHex - are not necessary if in the SpanData we expose the SpanContext which will allow users to retrieve the ids in hex or bytes.

**Comment by jkwatson** [comment]
I'm good with doing these cleanups. These APIs are probably not used by anyone outside of the project itself at this point, so a last cleanup here seems like a good idea.
