### ISSUE TITLE
API: Sampler interface return sampling decision and details

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#270]
Based on what Jaeger defines, it will be good to have the Sampler return some attributes that will be added to the Span, consider maybe to add them only to the trace initiator (the span that flips the sampling bit).

https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/samplers/SamplingStatus.java

/cc @yurishkuro - What do you think?

**Comment by SergeyKanzhelev** [comment]
sampler may also need to add properties to `tracestate`. Should this object have a `tracestate` field as well?

**Comment by bogdandrutu** [comment]
@carlosalberto can you please take this? We need an interface proposal to agree on.

**Comment by yurishkuro** [comment]
indeed, capturing the actual sampling probability as tags has been very useful at Uber
