### ISSUE TITLE
Exporter configuration

### ISSUE THREAD

**Issue by efimmatytsin** [open-telemetry/opentelemetry-java#2707]
Hello, everyone! Now there is no way to filter traces for export. For example: our team want to store traces only if exception occurred or long time execution. 

I suggest adding this feature.

**Comment by jkwatson** [comment]
Hello @efimmatytsin . This can be accomplished several ways right now. You can write a custom SpanExporter that does this filtering (and wraps the one you want to use for actual export). Or, this could be done in the collector. What exactly are you looking for from the SDK for this?

**Comment by efimmatytsin** [comment]
Thank you @jkwatson ! It's good approach, but looks like workaround for me.

**Comment by jkwatson** [comment]
If you have a concrete implementation of an exporter that would do this, it sounds like an excellent contribution to the java-contrib project: https://github.com/open-telemetry/opentelemetry-java-contrib

**Comment by efimmatytsin** [comment]
Thank you! I will do that!
