### ISSUE TITLE
Change TraceStateBuilder.set --> put?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#2746]
Perfectly reasonable to close this without comment given how close to 1.0 😄.

Was just using the TraceState API, and thought it might be nice for `set` to be `put`, to be consistent with `AttributesBuilder.put`.

**Comment by jkwatson** [comment]
We could always add this later if we feel the need.

**Comment by bogdandrutu** [comment]
That was one of the first feedback I got in OpenCensus that Java people like more put than set. @jkwatson i don't think you can do it later because will be confusing to have both even one is deprecated, but I think set is reasonable as it is so probably no need to change it at all

**Comment by bogdandrutu** [comment]
Just to clarify I think leave it as is will not be a tragedy.

**Comment by Oberon00** [comment]
I think this was an oversight. We changed set->put in attributebuilder and elsewhere because `put` perfectly makes it clear that the last value wins, like in `Map.put`. Question is if we still want to change this before 1.0. IMHO it would be OK since it is probably one of the most-seldom used APIs, but it is also not that important.

**Comment by Oberon00** [comment]
Marking this as required-for-ga to make a decision. I don't think adding `put` in addition as an alias for `set` would be helpful. Although we could make `set` deprecated and remove it after some time.

**Comment by anuraaga** [comment]
We're not making anymore breaking changes for 1.0 so we won't be removing `set`. We may consider deprecating it post-1.0 if users notice this method.

**Comment by Oberon00** [comment]
OK, so even deprecating before 1.0 is not an option? Then I would vote for closing the issue without action.

>  if users notice this method.

What do you mean by this? I think @trask's issue here counts as a user noticing 😃

**Comment by anuraaga** [comment]
> OK, so even deprecating before 1.0 is not an option? Then I would vote for closing the issue without action.

Yeah I wouldn't remove the method post-1.0 even if we deprecated it now. In practice I guess it has a really low chance of causing a problem, but strict semver is simpler than thinking about things too deeply. That being said, maintaining a tiny alias method that's deprecated even long term is not too big a deal I'd say.

> What do you mean by this? I think @trask's issue here counts as a user noticing 😃

True :) I guess I was thinking a non-maintainer just to see how it affects people that aren't in the API-building mindset, but it does make me more interested in the potential deprecated alias.

**Comment by bogdandrutu** [comment]
@trask what about `AttributesBuilder.put` -> `AttributesBuilder.set`. This will be consistent with `Span.setAttribute` and `TraceStateBuilder.set`. Or change everywhere the set to put 🥇

**Comment by anuraaga** [comment]
Let's make a final decision on this next meeting

**Comment by jkwatson** [comment]
I vote not to change this.

**Comment by jkwatson** [comment]
It would be useful to have a full audit of where we use `set` and where we use `put` so I'm not voting based on gut feelings, but based on data.  :)

**Comment by bogdandrutu** [comment]
So far I know, for `set`:

* `TraceStateBuilder` - for setting new values in the state
* `Span` - for setting `Attributes`
* `BaggageBuilde` - for setting new values in the baggage

for `put`:

* `AttributesBuilder`
* `LabelsBuilder`
* `BatchRecorder` - put instrument and value

**Comment by jkwatson** [comment]
BaggageBuilder has `put` at the moment. `set` is only used for the parent property.

**Comment by jkwatson** [comment]
Just some thoughts on this : It seems like we've used `put` in all places, aside from the Span/Builder, which is, perhaps unfortunately, the most common API in use right now, and probably the one that has been stable the longest. 

One difference on the Span/Builder is that it's all `setAttribute()` not a bare `set` method, which I do think makes it a bit of a special case. 

So, if we have opportunity to have another RC with this breaking change, I'd be ok with changing the TraceStateBuilder to be `put` as well, to line up with every other API that we have.
