### ISSUE TITLE
[Breaking Change] Remove AWS X-Ray propagator from the main artifact of propagators

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2758]
Pre specs, this is forbidden:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution

**Comment by jkwatson** [comment]
We had discussed this in #2067 , but I'm happy to re-open if we feel like the new stability guarantee definitions would preclude us from being able to remove this from the repository/project/distribution if AWS support disappears.
