### ISSUE TITLE
Improve performance of Attributes.of(myKey, "value")

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2765]
Right now a call to `Attributes.of(myKey, "value")` allocates around 5 new objects:
* 1 array during the call to `ArrayBackedAttributes.sortAndFilterToAttributes`
* 1 array during the call to `ImmutableKeyValuePairs.mergeSort` + copy of the initial array
* 1 array + 1 object during the call to `ImmutableKeyValuePairs.dedup` (ArrayList object + underlying array in the ArrayList). 
* 1 object the ArrayBackedAttributes

**Comment by JianhuaGong** [comment]
We has the performance issue, can you explain why sorting and filtering are performed during put a attribute?

**Comment by jkwatson** [comment]
> We has the performance issue, can you explain why sorting and filtering are performed during put a attribute?

we just hadn't gotten to the optimization yet. :) PR submitted.

**Comment by JianhuaGong** [comment]
> we just hadn't gotten to the optimization yet. :) PR submitted.

ok, we look forward to this version.
