### ISSUE TITLE
Behavior of `Baggage.toBuilder` seems tricky to understand

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2784]
The current behavior of the `Baggage.toBuilder` seems a bit tricky when it is combine with a parent. I am not sure based on the javadoc if I can understand the behavior (without looking at the code).

So I suggest to improve the javadoc for this method and clearly explain what would be the result when a parent is set, how conflicts (duplicate keys are resolved).

PS: @jkwatson there is always the option to remove this method, used only in tests and benchmarks :)))

**Comment by jkwatson** [comment]
> PS: @jkwatson there is always the option to remove this method, used only in tests and benchmarks :)))

We might be able to get rid of all the APIs!  ;)

**Comment by bogdandrutu** [comment]
Not all, but half :))

**Comment by bogdandrutu** [comment]
To be clear: I think this issue is just to improve documentation and clarify the behavior
