### ISSUE TITLE
Future consistency of simple getter names / accessors in general

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2786]
In general we use the `getFoo` even for static methods and default values, but we missed this in the `Baggage`
https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/Baggage.java#L33

This issue is not to change the API, but to ensure that from now on we stay with the `getFoo` pattern.

**Update** 

* `empty()` looks to be more like what Java prefers based on the usage in `Collections`, but we don't respect that in few places: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfo.java#L42 and https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java#L121

**Comment by trask** [comment]
@bogdandrutu that is not a getter, did you mean to link to something else?

**Comment by bogdandrutu** [comment]
@trask fixed, sorry

**Comment by trask** [comment]
I (personally) don't think that's a getter either.

And there's definitely good precedence for that name, see `java.util.Collections.empty*()`.

**Comment by bogdandrutu** [comment]
@trask I don't think you try to help here. I am asking for consistency, not for one or the other. If we treat `empty` different is fine, but we should document that:

* `getDefault()` and `getInvalid()` are recommended, but when using empty use `empty()`

**Comment by trask** [comment]
> @trask I don't think you try to help here :)

I'm so confused, why? because I disagree with what you said?

Let me try to be clearer:

I don't see any inconsistency here, because I don't consider empty() to be a getter. And there seems to be good precedence for it not to be considered a getter, given that the JDK authors, who put "get" on everything else, didn't put "get" on the `java.util.Collections.empty*()` methods.

**Comment by bogdandrutu** [comment]
Ok sure, then the problem is here https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/common/InstrumentationLibraryInfo.java#L42 :)). I missed that I did not put a clear example of where we have with get

**Comment by bogdandrutu** [comment]
And here https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java#L121 :)

**Comment by bogdandrutu** [comment]
| I'm so confused, why? because I disagree with what you said?

I was smiling, no I just tried to make a joke because I think there is too much tension :)

**Comment by bogdandrutu** [comment]
@trask it took me some time to realize where the `getter` came from, then I saw the issue description, because I was reading the text and did not find anywhere where I called it a getter :))

**Comment by iNikem** [comment]
I have to agree with Bogdan here, there is unnecessary inconsistency in naming `empty` vs `getEmpty`. Choosing between two I would pick `empty`. If you don't want to introduce even more breaking changes, I would suggest adding `empty()` method to `InstrumentationLibrary` and `Resource` and to deprecate current `getEmpty`

**Comment by jkwatson** [comment]
I like a bare `empty()` myself, also. Do we want another minor breaking change, or could we just add the methods and deprecate the old ones forever, do you think?

**Comment by anuraaga** [comment]
I'd lean towards adding methods and deprecating forever the current ones.

**Comment by bogdandrutu** [comment]
Please please don't go to 1.0 with deprecated methods, on this path we will have more deprecated methods than non-deprecated :)) If you don't want to fix leave it as is in my opinion.

**Comment by anuraaga** [comment]
@bogdandrutu Yeah I think just leaving may be best. Let's make a final decision on this at the next meeting.

**Comment by jkwatson** [comment]
Let's leave it as is

**Comment by jkwatson** [comment]
If we decide to have another RC with some breaking changes in it, I'd be ok with changing to `empty()` everywhere where it's not. The decision really boils down to: can we do another RC with breaking changes?
