### ISSUE TITLE
Obfuscate GlobalOpenTelemetry.get()

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#2788]
I'm nervous about users casting the return value of `GlobalOpenTelemetry.get()` to `OpenTelemetrySdk`, e.g.

```
((OpenTelemetrySdk) GlobalOpenTelemetry.get()).getSdkTracerProvider()...
```

It seems like a reasonable way to get the global SDK now that we no longer have `OpenTelemetrySdk.get()`, so I suspect users will find their way to doing it.

The reason I'm nervous about this, is that the javaagent returns a bridged OpenTelemetry instance from GlobalOpenTelemetry.get(), which will then cause the user's app to throw ClassCastException, and a (the?) top priority of the java agent is to not break a user's application.

This is similar to the reason the return value from `GlobalOpenTelemetry.get().getTracerProvider()` is obfuscated, in order to prevent similar global access to the SDK:

```
((SdkTracerProvider) GlobalOpenTelemetry.get().getTracerProvider())...
```

**Comment by jkwatson** [comment]
Wouldn't doing this just change the location of the ClassCastException, not get rid of it altogether?

**Comment by trask** [comment]
It would make sure that application throws `ClassCastException` even without the javaagent, so that users can't depend on this trick to get at the `OpenTelemetrySdk`.
