### ISSUE TITLE
SDK: Implement Span (SpanSdk) interface

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#279]
The implementation of the Span should allow users to configure the maximum attributes, events, etc. to be kept and drop oldest data when these limits are hit.

Suggestion: Import the Span implementation from OpenCensus

**Comment by songy23** [comment]
> The implementation of the Span should allow users to configure the maximum attributes, events, etc. to be kept and drop oldest data when these limits are hit.

IMO to be able to do that we need to import `TraceConfig` first, so I created https://github.com/open-telemetry/opentelemetry-java/issues/335 as a prerequisite.

**Comment by bogdandrutu** [comment]
Sure, the config I think should be part of the TracerSdk. 

```java
class TracerSdk {
  ...
  public final updateTraceConfig(TraceConfig config) {
    ...
  }
}

class TraceConfig {
  ...
  public static TraceConfig fromProtoTraceConfig(proto.trace.v1.TraceConfig) {
    ...
  }
}
```
