### ISSUE TITLE
Consider moving the ResourceProvider SPI to the autoconfigure module

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2796]
This is the only SPI left in the SDK. All others are managed in the autoconfigure module. It would be less confusing to move it now, before 1.0, if we have the appetite for it.

**Comment by anuraaga** [comment]
I think moving would be ok - it's not an API break, and while it's a post-1.0 behavior change we wouldn't do, for RC I'm comfortable. We'll want to refactor the providers we have a bit to expose a `Resource` for merging and `compileOnly` autoconfigure dependency and SPI implementation.

**Comment by anuraaga** [comment]
Discussed more with John that we like the current semantics of `Resource.getDefault`, and that having an exception for the single property being read in the SDK is ok. `autoconfigure` is a mechanism for configuring the SDK based on the environment - `ResourceProvider` is not necessarily in its scope, there just happened to be some overlap with the need to disable resourceproviders by environment somehow. We think we can live with this being in the SDK though. Let's make a final decision at the next meeting.

**Comment by jkwatson** [comment]
This is a tough only because I think if we move this out, I'm not sure how to describe what Resource.getDefault() is providing any more. I like the fact that our current implementation makes it easy to have a rich Resource, simply by pulling in autoconfigure, or the resource artifact. Otherwise, how does a user who wants access to that get a handle to it? 

As an example, if I'm an operator/app owner, and I don't want to use the full autoconfigure functionality, but I want to get access to the full Resource for populating my SDK, how would I do that, without re-implementing the SPI processing logic?

**Comment by bogdandrutu** [comment]
Personal opinion, if we get rid of the `ResourceProvider` and make all the current implementation expose or implement a `Supplier<Resource>` (I think implement is nicer) then users without autoconfig will do:

```java
Resource resource = OsResource.getInstance().get().merge(ProcessResource.getInstance().get()).merge(ProcessRuntimeResource.getInstance().get());
```

**Comment by bogdandrutu** [comment]
An alternative is to allow to the TracerProviderSdk to add multiple "Supplier<Resource>":

```
TracerProviderSdk.builder().addResourceSupplier(OsResource.getInstance()).addResourceSupplier(ProcessResource.getInstance());
```

There are ways to achieve this, that is what I am trying to say. Right now it is a bit hard I think to do it manually anyway correct?

**Comment by jkwatson** [comment]
If we don't put auto-configured Resource entries into the `Resource.getDefault()`, that will be very anemic: Just the sdk tag and version, and a default `service.name`. Does that make a useful "default"? I'm not sure if it does or not.

If we don't put auto-configured Resource entities into the default, I would like an easy way for a user to get all the auto-configured Resource/attributes so they can easily put it into their SDK. 

@bogdandrutu it sounds like you're saying that you don't think that we should have any SPI for resources, and all of the usages should be merged manually? Am I reading that correctly, or am I mis-interpreting what you're saying?

**Comment by jkwatson** [comment]
It's already not hard to use the existing interface in a non-SPI context:

```
    Resource.getDefault()
        .merge(new OsResource().create())
        .merge(new ProcessResource().create())
        .merge(new ProcessRuntimeResource().create())
```

Helper methods could certainly be added to not require calling a constructor, if people felt strongly about that.

This usage just requires users to know about all the resources that are available from a given module, rather than just getting them automatically via SPI.
