### ISSUE TITLE
SDK: Implement TagMap (TagMapSdk)

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#284]
Suggestion: Import the TagMap implementation from OpenCensus

**Comment by bogdandrutu** [comment]
@tylerbenson see some idea about how this should be implemented here:
https://github.com/open-telemetry/opentelemetry-java/issues/312#issuecomment-494826135

See some existing tests:
https://github.com/census-instrumentation/opencensus-java/blob/master/impl_core/src/test/java/io/opencensus/implcore/tags/TagMapImplTest.java#L32

**Comment by bogdandrutu** [comment]
@tylerbenson let's continue the discussion from https://github.com/open-telemetry/opentelemetry-java/issues/312 here.

**Comment by tylerbenson** [comment]
@bogdandrutu I'll see what I can do about the deduping on iteration.

**Comment by bogdandrutu** [comment]
@tylerbenson that is just an idea, if you think doing dedup at build time is faster and simpler in Java (just some benchmarks would be good so that if somebody tries the parent version we can compare the results), happy to accept a PR with that.

**Comment by tylerbenson** [comment]
Closing since the PR was merged.
