### ISSUE TITLE
API: Consider to rename NoopFoo to PropagationOnlyFoo

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#285]
For classes like Tracer/Tagger some of the functionality will be implemented like propagation:
1. Consider to maybe rename these classes from NoopTracer to PropagationOnlyTracer? 
1. Consider to make these classes public and not final to allow TracerSdk implementation to inherit from them to avoid duplicate code?

**Comment by pavolloffay** [comment]
Related to #118

**Comment by pavolloffay** [comment]
Are also various javadocs have to be updated to reflect the change in #118

**Comment by bogdandrutu** [comment]
Another proposal was "DefaultTracer"

**Comment by carlosalberto** [comment]
IHMO "DefaultTracer" sounds better.

**Comment by yurishkuro** [comment]
+1 "default"
