### ISSUE TITLE
Cleanup documentation for Resource implementations

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2859]
See https://github.com/open-telemetry/opentelemetry-java/pull/2837#discussion_r577888781

**Comment by prathik-kaliyambath** [comment]
Hey, I saw that this was open for a few days, and have raised this [PR](https://github.com/open-telemetry/opentelemetry-java/pull/3027)

**Comment by jkwatson** [comment]
closed with #3028
