### ISSUE TITLE
API: spi vs root package vs components package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#290]
I kind of don't like the fact that we have spi pacakge and OpenTelemetry.java (in the main package).

I think we can combine the spi classes under every individual package, or maybe have a subpackage trace/spi/TracerProvider.java?

What do you think?

**Comment by pavolloffay** [comment]
`component/spi/` lgtm

**Comment by pavolloffay** [comment]
Let's merge #299 and them move around.
