### ISSUE TITLE
Documentation in sdk/trace/export/package-info is outdated

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2903]
There are reference to system properties and env variables which were moved to autoconfigure package.

**Comment by cynthiakedu** [comment]
Can I get assigned to this? cc @alolita

**Comment by jkwatson** [comment]
@cynthiakedu any update on this?

**Comment by cynthiakedu** [comment]
Don't have time for this anymore :( , please unassign me.

Apologies for the inconvenience.
