### ISSUE TITLE
Support OTEL_EXPORTER_OTLP_METRICS/TRACES_ENDPOINT

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#2911]
It seems currently only `OTEL_EXPORTER_OTLP_ENDPOINT` is supported, and not `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` nor `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`.

**Comment by carlosalberto** [comment]
Shouldn't this be this part of the 1.0 release? Just wondering ;)

**Comment by jkwatson** [comment]
> Shouldn't this be this part of the 1.0 release? Just wondering ;)

We can always add it afterward in the next minor release. I'd do not want to delay the 1.0.0 release for it.

**Comment by ChrisJBurns** [comment]
I can pick this up, do we know what changes have to be made? Is quite a high level issue description, just need a bit of a lower level point in the right direction :+1:

**Comment by jkwatson** [comment]
@ChrisJBurns If you poke around in the autoconfigure module, you'll see where `otel.exporter.otlp.endpoint` is used. The task would be to additionally add support to the appropriate configuration class (metrics vs. tracing) for the ones referenced in the description.

**Comment by malafeev** [comment]
@ChrisJBurns are you working on this issue? 
If not I have free cycles and can take it.

**Comment by ChrisJBurns** [comment]
Hi @malafeev 
Yes I was going to pick this up this week as work project pressure increased last week. But if you can get it done, feel free :+1:
