### ISSUE TITLE
Verify/update all propagators to make sure they do not throw exceptions on bad inputs.

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2921]
Ideally, all of the propagators should have the same behavior in the face of bad inputs.

extract: return the root Context if null inputs are provided for Context or Setter
inject: return immediately if null inputs are provided for Context or Getter

- [x] B3Propagators
- [x] W3CBaggagePropagator
- [x] W3CTraceContextPropagator
- [x] JaegerPropagator
- [x] OtTracePropagator
- [x] AwsXrayPropagator
- [ ] MultiTextMapPropagator
- [ ] NoOpTextMapPropagator

**Comment by jkwatson** [comment]
#2920 for B3

**Comment by jkwatson** [comment]
See #2904 for most of these...

**Comment by anuraaga** [comment]
No more throwing!

**Comment by anuraaga** [comment]
Closed too soon since no more throwing, but there is some inconsistency.
