### ISSUE TITLE
"stable APIs" link on https://github.com/open-telemetry/opentelemetry-java broken

### ISSUE THREAD

**Issue by slernersplunk** [open-telemetry/opentelemetry-java#2922]
**Describe the bug**

"stable APIs" link on https://github.com/open-telemetry/opentelemetry-java broken

**Steps to reproduce**

click on 'stable apis' 
https://github.com/open-telemetry/opentelemetry-java broken

**What did you expect to see?**
a page describing stable apis

**What did you see instead?**
404

**What version and what artifacts are you using?**
N/A

**Environment**
N/A

**Additional context**
docs error

**Comment by kevinjad** [comment]
Hi @slernersplunk would you review and accept this PR #2926 if possible? This is my first PR, I would certainly like to contribute more in fixing minor bugs & "good first issue" in this Repository. Thank you!

**Comment by jkwatson** [comment]
fixed by #2926 . Thanks for the report, @slernersplunk !
