### ISSUE TITLE
CompletableResultCode.join() suprisingly fail()s on timeout.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#2942]
This is different from the JDK's [CompletableFuture.get(long, TimeUnit)](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#get-long-java.util.concurrent.TimeUnit-) and IMHO quite surprising. It also reduces the flexibility of the method as calling `fail()` in the `catch(TimeoutException)` is easier than re-implementing `join` on top of `whenComplete`.

Code reference:

https://github.com/open-telemetry/opentelemetry-java/blob/v0.17.1/sdk/common/src/main/java/io/opentelemetry/sdk/common/CompletableResultCode.java#L150-L157

I suggest either changing the behavior (silent break) or renaming the method to `joinOrFail`.

**Comment by jkwatson** [comment]
We can't rename the method at this point, as that would be a breaking change. 

I'd be ok with changing the behavior to throw some sort of TimeoutException if it times out. I agree that failing is a little surprising, since it might completely successfully later.

**Comment by Oberon00** [comment]
Another possibility is marking the method deprecated and making it an alias of a new method joinOrFail 🙂 Changing behavior would be the cleanest result IMHO but it would also need a "Breaking Changes" entry and might be risky.

**Comment by Oberon00** [comment]
Hmm, on the other hand TimeoutException is a checked exception, so we would need to invent some unchecked TimeoutException 😞
Another possibility might be to return a new `CompletableResultCode.ofFailure()` instead of failing the existing result. But that is then just a different kind of surprising behavior.

**Comment by jkwatson** [comment]
Changing behavior can be ok without a major version bump, so we can definitely change this post 1.0. A behavioral change like this in the SDK is neither API or ABI breaking, so is something that we can do, if we feel it is the right path.

**Comment by Oberon00** [comment]
Well, it does not break the compilation or even ABI, but IMHO it is a breaking change, as in a change that might adversely affect the runtime behavior of a program that relied on the (documented!) old behavior.

**Comment by jkwatson** [comment]
By the semver specification, this is ok if the community is generally ok with it. It's up to the maintainers' discretion, and I would guess that no one would be overly adversely impacted by this yet.

**Comment by jkwatson** [comment]
Note: I also believe this could be considered as a bugfix, since the behavior is, as you very rightly point out, is surprising.

**Comment by anuraaga** [comment]
Hmm - yeah I didn't realize the discrepancy, I think we can safely change to not fail. The worse that could happen is someone checks `isSuccess` after the join and it returns `true` correctly - this should never cause harm.

**Comment by Oberon00** [comment]
Harm could be caused if someone assumes that `!resultCode.isFailure()` implies `resultCode.isSuccess()` after `join()`. Or if someone checks `isFailure()` in the task tracked by the result code, as a cancellation mechanism.

**Comment by anuraaga** [comment]
@Oberon00 I don't think we have `isFailure` right?

**Comment by Oberon00** [comment]
Oh, you are right. That is good in this case 😃

**Comment by jkwatson** [comment]
So... what do we want to do here. Just change it to not fail the task on timeout, or also introduce some sort of runtime TimeoutException? 

If we just make it not-fail without an exception, then the user can ask `isDone()`, and if it's not done yet, join again, or throw their own exception. Of course, they can also do that today with no changes at all.

**Comment by Oberon00** [comment]
> If we just make it not-fail without an exception, then the user can ask isDone(), and if it's not done yet, join again, or throw their own exception. Of course, they can also do that today with no changes at all.

They can't do that today (without re-implementing join which *is* possible with the public API), becasue isDone will always be true after join, due to the fail(). Just removing the fail()

**Comment by jkwatson** [comment]
> > If we just make it not-fail without an exception, then the user can ask isDone(), and if it's not done yet, join again, or throw their own exception. Of course, they can also do that today with no changes at all.
> 
> They can't do that today (without re-implementing join which _is_ possible with the public API), becasue isDone will always be true after join, due to the fail().

oops! You're totally right. forgot about that key point.
