### ISSUE TITLE
SDK: Lifecycle [Listener|Decorator|Interceptor] for [Scope|Span]

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java#295]
We should have a way to be notified of state changes for these important objects such as:

Span
* afterStart(span)
* beforeFinish(span)

Scope
* updated(old, new)

Span Builder (maybe?)
* beforeStart(builder)

We may want to be able to define these on each span/scope instance, a span.builder, or on the tracer which would be applied to each individual instance automatically.

These types of hooks are useful for supporting features like MDC.

**Comment by tylerbenson** [comment]
Partially defined in #278

**Comment by bogdandrutu** [comment]
@tylerbenson why before end?

**Comment by bogdandrutu** [comment]
Except the Scope the other two requests should go into the related issues that you linked.

**Comment by tylerbenson** [comment]
@bogdandrutu (I admit I didn't see those other issues first but,) since they're closely related I think it makes sense to think of the proper design holistically, rather than each independently.

**Comment by bogdandrutu** [comment]
We need an afterEnd API to implement exporters. See https://github.com/open-telemetry/opentelemetry-java/pull/264 for more details, also there is a link on how I plan to build the export framework on top of this API

**Comment by bogdandrutu** [comment]
@tylerbenson can you explain about the Scope interceptor?

**Comment by tylerbenson** [comment]
There's pretty detailed discussion about it [here](https://github.com/opentracing/opentracing-java/issues/324) and [here](https://github.com/opentracing/opentracing-java/pull/336), but the gist is it would be useful to have this functionality to support things like MDC coordination and JFR reporting.  (I think the best consensus proposal from that discussion was [this one](https://github.com/opentracing/opentracing-java/pull/336#issuecomment-473983583), but I think there are still some kinks to work out.)

**Comment by dschulten** [comment]
Making this an official feature is still important. In the meantime, for java there is https://github.com/opentracing-contrib/java-api-extensions

**Comment by trask** [comment]
Scope listener would be particularly useful, so that current span context can be sync'd with logging context (MDC), which is needed in order to correlate logs with traces (e.g. https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/133).

**Comment by Oberon00** [comment]
I think this issue is using concepts that mostly don't apply anymore. I'd vote for closing it and opening a new issue (maybe in the spec?) if there are still open issues not covered by SpanProcessor already.

**Comment by bogdandrutu** [comment]
@Oberon00 The major remaining part is the Context changes interceptor.

@tylerbenson will close this and open a new issue just for the Context inteceptor.
