### ISSUE TITLE
Review https://opentelemetry.io/docs/java/

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#2952]
Java documentation on OpenTelemetry public site is outdated. It should be reviewed and updated both from the POV of this repo and java-instrumentation one.

**Comment by jkwatson** [comment]
@austinlparker Is this something the docs team can own?

**Comment by austinlparker** [comment]
If the documentation on the website needs to be updated, yes, please open an issue in that repository.

**Comment by jkwatson** [comment]
https://github.com/open-telemetry/opentelemetry.io/pull/473

**Comment by codesuperstarr** [comment]
Has the documentation issue been resolved? If not, I would like to work on this issue.

**Comment by jkwatson** [comment]
> Has the documentation issue been resolved? If not, I would like to work on this issue.

I think we're close to having this resolved, @codesuperstarr . Here's the PR if you want to review it: https://github.com/open-telemetry/opentelemetry-java/pull/3081

**Comment by iNikem** [comment]
@jkwatson closed by #3081 ?

**Comment by jkwatson** [comment]
> @jkwatson closed by #3081 ?

not quite. We still need to get that synched over to the website itself. See #3080

**Comment by jkwatson** [comment]
The docs have been updated and pushed to the website. Thanks @austinlparker for wrangling all of this! Closing.
