### ISSUE TITLE
Adding an invalid span as a link

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#2955]
**Describe the bug**
What should happen when you add an invalid span (traceId=0, spanId=0) as a link?
Currently such a link is added to the span and even exported (I haven't tested it, just read the code: jaeger & otlp exporters do not filter links at all, nor does SDK). That's quite different to how we treat parent contexts - where we check if the context contains a valid span (in `SdkSpanBuilder#startSpan()`).
Is the current behavior correct?

**Comment by jkwatson** [comment]
Does the spec have anything to say on this issue?

**Comment by mateuszrzeszutek** [comment]
It doesn't say anything about it - it does more or less specify what happens on `setParent()` though. I'll create a spec issue for clarifying that, thanks!
