### ISSUE TITLE
Compilation issue - io.opentelemetry.semconv.resource.attributes when packaging with maven in Opentelemetry 1.0.0 version

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java#2973]
I see compilation issue in io.opentelemetry.semconv.resource.attributes when packaging with maven in Opentelemetry 1.0.0 version, but not in 0.17.1 version

Setup a maven project and execute the Zipkin Example..Example run fine and errorred out while packaging..Below is the error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project opentemetry.example: Compilation failure
[ERROR] /P:/Eclipse Workspace/opentemetry.example/src/main/java/zipkin/example/ExampleConfiguration.java:[15,52] package io.opentelemetry.semconv.resource.attributes does not exist

This issue occurs with 1.0.0 version not in previous versions -0.17.1

opentelemetry-1.0.0 version
pom.xml

**Environment**
Compiler: (e.g., "Java 8 ")
OS: (e.g., "Windows")

**Comment by anuraaga** [comment]
Hi @ChandrewR. Semantic attributes are currently not stable so we don't export semantic conventions by default. Do you need to set attributes? Until they stabilize we recommend you inline the keys yourself instead of using our artifact which may have breaking changes at any time. If breaking changes are acceptible to you, you could alternatively add our `bom-alpha` and `semconv` artifacts directly to your build. They're called alpha for a reason though :-)

**Comment by ChandrewR** [comment]
Ok..Got it..How can i set the service name without using the Resource attributes?  You can refer the Zipkin Example..

**Comment by anuraaga** [comment]
This is definitely an important usability gap you've brought to attention, thanks. For now the best is to define your own `AttributeKey.stringKey("service.name")` and use it. We do need to come up with an approach for stabilizing this important attribute ASAP though.

**Comment by ChandrewR** [comment]
Yeah..This works until it gets stabilized. Thank you ! @anuraaga

**Comment by anuraaga** [comment]
Great - I've opened the attached spec issue to see how we can proceed on stabilizing this attribute hopefully we can improve it soon.

**Comment by jkwatson** [comment]
Do we need to keep this issue open?

**Comment by anuraaga** [comment]
Don't think so - @chandru-kumar we are tracking the ability to stabilize certain attributes in https://github.com/open-telemetry/build-tools/issues/35
