### ISSUE TITLE
Helper for merging a Resource with one or two key/value pairs

### ISSUE THREAD

**Issue by kenfinnigan** [open-telemetry/opentelemetry-java#2975]
**Is your feature request related to a problem? Please describe.**
In defining a `Resource` on `SdkTracerProviderBuilder` I have code that does:

```
builder.setResource(
        Resource.getDefault()
                .merge(
                        Resource.create(
                                Attributes.of(
                                        ResourceAttributes.SERVICE_NAME, serviceName,
                                        ResourceAttributes.SERVICE_VERSION, serviceVersion))));
```

It's fairly verbose for adding two key/value pairs to the default resource.

**Describe the solution you'd like**
A convenience method would be nice to remove the intermediate steps:

```
builder.setResource(
        Resource.getDefault()
                .merge(
                        ResourceAttributes.SERVICE_NAME, serviceName,
                        ResourceAttributes.SERVICE_VERSION, serviceVersion);
```

While it's a nice convenience method, I don't think it should go overboard in the number of key/value pairs it can accept.

**Additional context**
As `Resource.merge()` extracts the attributes from the resource to merge them,
creating the intermediary objects is unnecessary.

**Comment by jkwatson** [comment]
I'm not sure what the right API for this is, but I do agree that it's pretty verbose at the moment.

**Comment by jkwatson** [comment]
It would be good to provide an sdk-extension for this convenience function (and others, obviously) that we could consider for eventual inclusion in the SDK proper.

**Comment by kenfinnigan** [comment]
Would that just be a static utility that returns the created `Resource`?

Or is there another example that does something similar?

**Comment by jkwatson** [comment]
> Would that just be a static utility that returns the created `Resource`?
> 
> Or is there another example that does something similar?

yeah... similar to what I started for the API here: #2962

**Comment by anuraaga** [comment]
I've found this pretty annoying already too and think it deserves a relatively low or no time in incubation if possible. 

I've always been wishing for `Resource.builder` since it always feels like I'm working on an `Attributes`.

```java
Resource.getDefault().toBuilder()
  .put(Keys.CAT, "meow")
  .put(Keys.DOG, "bark")
  .putAll(OsResource.get())
  .putAll(MY_ATTRIBUTES)
  .build()
```

**Comment by piotr-sumo** [comment]
@anuraaga I've implemented what you've proposed above in https://github.com/open-telemetry/opentelemetry-java/pull/3065
