### ISSUE TITLE
Add an example that uses auto-configuration

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#2999]
**Is your feature request related to a problem? Please describe.**
The [examples/](https://github.com/open-telemetry/opentelemetry-java/tree/main/examples) directory is missing the simplest example possible of using the Java SDK with auto-configuration, just using the defaults (with maybe logging exporter) to show how easy is to set it up.

**Describe the solution you'd like**
It could be a single-file Java app that just calls `OpenTelemetrySdkAutoConfiguration.initialize()` and starts a span - it could be as simple as the [.NET 5 minute example](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/getting-started).

**Comment by jkwatson** [comment]
Yes, this would be great!

**Comment by mateuszrzeszutek** [comment]
OK, please assign me then -- I'll prepare something by tomorrow morning.
