### ISSUE TITLE
Same metrics exported multiple times while there are more than one SdkMeters

### ISSUE THREAD

**Issue by beanliu** [open-telemetry/opentelemetry-java#3018]
**Steps to reproduce**
- Create more than one `SdkMeter`s;
- set up an `IntervalMetricReader` with `OtlpGrpcMetricExporter`;
- create some instruments with them;
- take a few measurements.

**What did you expect to see?**
The exported OTLP payload should contain one entry for every unique instrument.

**What did you see instead?**
The exported OTLP payload contains multiple entries for a unique instrument.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk`, OTLP exporter.
Version: [f05a8c47927fa12769c29d0c5210c6f20eae4841](https://github.com/open-telemetry/opentelemetry-java/commit/f05a8c47927fa12769c29d0c5210c6f20eae4841), the latest master as written of this issue.

**Additional context**
in `SdkMeterProvider::collectAllMetrics` [ref](https://github.com/open-telemetry/opentelemetry-java/blob/v1.0.x/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProvider.java#L64-L72):
```java
  @Override
  public Collection<MetricData> collectAllMetrics() {
    Collection<SdkMeter> meters = registry.getComponents();
    List<MetricData> result = new ArrayList<>(meters.size());
    // every meter export their own metrics
    for (SdkMeter meter : meters) {
      result.addAll(meter.collectAll(sharedState.getClock().now()));
    }
    return Collections.unmodifiableCollection(result);
  }
```
and in `SdkMeter::collectAll` [ref](https://github.com/open-telemetry/opentelemetry-java/blob/v1.0.x/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeter.java#L97-L105):
```java
  Collection<MetricData> collectAll(long epochNanos) {
    // all the meters share the same instrument registry
    InstrumentRegistry instrumentRegistry = meterSharedState.getInstrumentRegistry();
    Collection<AbstractInstrument> instruments = instrumentRegistry.getInstruments();
    List<MetricData> result = new ArrayList<>(instruments.size());
    // the following loop get executed multiple times if there are more than one meters
    for (AbstractInstrument instrument : instruments) {
      result.addAll(instrument.collectAll(epochNanos));
    }
    return result;
  }
```

**Comment by jkwatson** [comment]
Can you provide some example output that shows what the resulting data looks like?

**Comment by beanliu** [comment]
here's an example: https://github.com/atlassian-forks/opentelemetry-java/blob/duplicated_metrics_with_multiple_meters/examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java#L39

and the result collected in the collector looks like:
```
2021-03-12T14:58:06.612+1100	DEBUG	loggingexporter/logging_exporter.go:388	ResourceMetrics #0
Resource labels:
     -> service.name: STRING(unknown_service:java)
     -> telemetry.sdk.language: STRING(java)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.0.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary io.opentelemetry.example1 
Metric #0
Descriptor:
     -> Name: example_counter    <----------------------------- first appearance
     -> Description: 
     -> Unit: 1
     -> DataType: IntSum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
IntDataPoints #0
StartTime: 1615521484444522000
Timestamp: 1615521486452428000
Value: 10
ResourceMetrics #1
Resource labels:
     -> service.name: STRING(unknown_service:java)
     -> telemetry.sdk.language: STRING(java)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.0.0)
InstrumentationLibraryMetrics #0
InstrumentationLibrary io.opentelemetry.example1 
Metric #0
Descriptor:
     -> Name: example_counter    <----------------------------- second appearance
     -> Description: 
     -> Unit: 1
     -> DataType: IntSum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
IntDataPoints #0
StartTime: 1615521484444522000
Timestamp: 1615521486471865000
Value: 10
```

**Comment by jkwatson** [comment]
Thanks. That does look like a bug. You don't have 2 MeterProviders, right? Just 2 Meters from the same Provider? Interesting that the Meters both have the same InstrumentationLibrary info on them.

**Comment by beanliu** [comment]
> You don't have 2 MeterProviders, right? Just 2 Meters from the same Provider? 

yep, two meters from the same provider. I've included the related codes in the description. seems like all meters share the same instrument registry object.

**Comment by beanliu** [comment]
and only instruments with cumulative temporality are duplicated.

**Comment by jkwatson** [comment]
Can you paste in the code that you're using to set up your meters and instruments? I'm not seeing this with the logging-otlp json exporter but I'm not sure I'm doing the same thing you are.

**Comment by beanliu** [comment]
Here's a branch of example based on the example in the repository: https://github.com/atlassian-forks/opentelemetry-java/blob/duplicated_metrics_with_multiple_meters/examples/otlp/src/main/java/io/opentelemetry/example/otlp/OtlpExporterExample.java#L39

**Comment by jkwatson** [comment]
@beanliu I don't think what you're seeing here has anything to do with creating a 2nd unused meter. I ran this locally and it behaves exactly the same, whether you create that 2nd meter or not. I think what you're seeing is the final export when the SDK is shutdown, which sends another copy of the cumulative metric with the same data in it. Note that the end time of the 2nd metric is later than the first one in the batch. If you remove the shutdown hook that is registered in the ExampleConfiguration, the 2nd copy of the metric disappears.

So, I don't believe that this is a bug, but just a side-effect of an odd boundary condition in the example.

**Comment by beanliu** [comment]
@jkwatson you are right about the example 👍  I missed that. Thanks for pointing it out.

The branch example is something I tried to reproduce the issue which we encountered in an internal project. 
I'll take a deeper look at the problem and come out with another clean example.

**Comment by jkwatson** [comment]
@beanliu any update on this, or can we close it?

**Comment by beanliu** [comment]
closing it since the issue can be reproduced with the latest version.
