### ISSUE TITLE
Update semantic constants generator template

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#3042]
The [template] for generating constants for semantic conventions needs to be updated to work with the latest version of the YAML format and generator tool (https://github.com/open-telemetry/build-tools/releases/tag/v0.3.0) in order to update the spec reference to the next release (after https://github.com/open-telemetry/opentelemetry-specification/pull/1550).

[template]: https://github.com/open-telemetry/opentelemetry-java/blob/main/buildscripts/semantic-convention/templates/SemanticAttributes.java.j2

**Comment by jkwatson** [comment]
This can be done the next time the spec gets released and we re-gen the semconv module code. 👍

**Comment by arminru** [comment]
Pending on the fix https://github.com/open-telemetry/build-tools/pull/36 to be merged and released as `v0.3.1`.

**Comment by Oberon00** [comment]
Another update that will be necessary: Replace the `unique("fqn")` filter by checking for `is_local and not ref`, like here: https://github.com/open-telemetry/opentelemetry-js/pull/2083/files#diff-30b86e034e5acba0b0c9f36baaffc11d373cd389966d609d067deb00bd7dfdf7R30, see open-telemetry/build-tools#41

**Comment by arminru** [comment]
> Another update that will be necessary: Replace the `unique("fqn")` filter by checking for `is_local and not ref`, like here: [open-telemetry/opentelemetry-js#2083 (files)](https://github.com/open-telemetry/opentelemetry-js/pull/2083/files#diff-30b86e034e5acba0b0c9f36baaffc11d373cd389966d609d067deb00bd7dfdf7R30), see [open-telemetry/build-tools#41](https://github.com/open-telemetry/build-tools/issues/41)

Done in adcf6ef.
