### ISSUE TITLE
Common Attributes OtlpGrpcSpanExporter

### ISSUE THREAD

**Issue by RafaelCavazza** [open-telemetry/opentelemetry-java#3046]
Is there a way to define common span Attributes attributes when using the OtlpGrpcSpanExporter? 

Something like:
````
        var spanExporter =
                OtlpGrpcSpanExporter.builder()
                        .setEndpoint("https://my-endpoint")
                        .commomAtrtibutes(Map.of("service.name", "myService"))
                        .build();
````

We want to define the service.name for all spans using this exporter?

**Comment by jkwatson** [comment]
@RafaelCavazza service.name should be provided via the `Resource` that is configured into the SDK, not to the exporter. And, that ends up as a part of the Resource, not the spans themselves.
