### ISSUE TITLE
Update the OT Shim layer

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#3049]
The OT Shim layer needs to be updated to include the latest changes as introduced by

https://github.com/open-telemetry/opentelemetry-specification/pull/1101
https://github.com/open-telemetry/opentelemetry-specification/pull/1563

**Comment by jkwatson** [comment]
@carlosalberto can this now be closed with the 2 merged PRs?

**Comment by carlosalberto** [comment]
@jkwatson Hey, thanks for the poke.

I need to wrap up the context-related effort started by #2982 - I should be able to take this on next week.

**Comment by jkwatson** [comment]
bump @carlosalberto

**Comment by jack-berg** [comment]
I believe this is done given #4911.
