### ISSUE TITLE
docs outdated? (OTEL_EXPORTER_JAEGER_SERVICE_NAME)

### ISSUE THREAD

**Issue by BitProcessor** [open-telemetry/opentelemetry-java#3056]
Something is possibly wrong with the docs.

On kubernetes, the following works:
```
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=dev-mobile-backend
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_TRACES_EXPORTER
          value: jaeger
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: http://jaeger-collector.jaeger:14250
```
and sets `service.name` to `dev-mobile-backend` in Jaeger

While this (from: https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/jaeger/README.md and https://opentelemetry.io/docs/java/automatic_instrumentation/ )
```
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_TRACES_EXPORTER
          value: jaeger
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: http://jaeger-collector.jaeger:14250
        - name: OTEL_EXPORTER_JAEGER_SERVICE_NAME
          value: dev-mobile-backend
```
results in `service.name` set to `unknown_service:java`

I also noticed, that the ENV variable is missing from this page: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md so maybe it's something deprecated and the other 2 pages need an update?

**Comment by jkwatson** [comment]
`OTEL_EXPORTER_JAEGER_SERVICE_NAME` is no longer a valid env var. Looks like the docs on the main website need updating. Can you open an issue over there to track it?

And, our README in the Jaeger exporter docs is also out of date. Thanks for pointing this out!

**Comment by BitProcessor** [comment]
> `OTEL_EXPORTER_JAEGER_SERVICE_NAME` is no longer a valid env var. Looks like the docs on the main website need updating. Can you open an issue over there to track it?
> 
Done: https://github.com/open-telemetry/opentelemetry.io/issues/507

**Comment by jkwatson** [comment]
> > `OTEL_EXPORTER_JAEGER_SERVICE_NAME` is no longer a valid env var. Looks like the docs on the main website need updating. Can you open an issue over there to track it?
> 
> Done: [open-telemetry/opentelemetry.io#507](https://github.com/open-telemetry/opentelemetry.io/issues/507)

@BitProcessor looks like those docs are moving into our repo; I'll make sure they get cleaned up and pushed over to the website as soon as I can.  See the newly created `website_docs` directory if you're interested in helping with the cleanup.
