### ISSUE TITLE
Autoconfiguration: provide option for configuring SdkMeterProvider

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3060]
**Is your feature request related to a problem? Please describe.**
The autoconfiguration module doesn't provide any way configure the `SdkMeterProvider` other than specifying the resource associated with it. I want to be able to configure the views for the meter provider for `opentelemetry-java-instrumentation`, which relies on autoconfiguration.

It would be really helpful to be able to have configurability around view registry normally configured via `SdkMeterProvider.registerView(InstrumentSelector, AggregatorFactory)`.

**Describe the solution you'd like**
Having an SPI hook for metrics analogous to the existing `SdkTracerProviderConfigurer` seems natural and a good starting point, i.e. `SdkMeterProviderConfigurer`. However, the `SdkMeterProviderBuilder` currently doesn't provide any configurability around the views, so the builder would need to be adjusted in some fashion.

**Describe alternatives you've considered**
Could have a set of env / system properties based configuration as well.

**Comment by jkwatson** [comment]
Yes, this is something that is needed, and we should change the view configuration to be on the builder, rather than on the created SDK instance.

**Comment by jack-berg** [comment]
Great!

 Here's a [PR](https://github.com/open-telemetry/opentelemetry-java/pull/3071) which moves the view configuration to the builder. If / when it gets merged, I'll add a followup to add `SdkMeterProviderConfigurer`.
