### ISSUE TITLE
TestClientServerTest flaky in local execution on Windows with Java 8

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3062]
On Windows with Java 8, the timer resolution used for span start time is not great. It can thus happen that client and server get the same start timestamp. This can result in the following assertion failure:

```
org.opentest4j.AssertionFailedError: 
expected: CLIENT
but was : SERVER
```

occurring in the last line here:

https://github.com/open-telemetry/opentelemetry-java/blob/e7cc57d911bb34dcbaf218b8eacb0e5f58a053cd/sdk/trace/src/test/java/io/opentelemetry/sdk/trace/testbed/clientserver/TestClientServerTest.java#L60-L62

I'm not sure what the best solution would be. For that particular test, sorting root spans first in sortByStartTime would work, a bit more elaborate would be to inspect the actual hierarchy, i.e. sort A before B if A is a (also indirect) parent of B with the same start timestamp.

**Comment by Oberon00** [comment]
Another idea would be to solve this in the SDK's clock implementation to ensure that timestamps returned in the same process are strictly increasing at least by one nanosecond. But that would require cross-thread serialization (at least using atomic long).

**Comment by harshita19244** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by harshita19244** [comment]
@Oberon00 I was working on the issue, and I was wondering how about I employ an if-else clause, that performs assertion checks based on what the value of the first index is. If the span kind of the first index is not of the Client type, I could simply create another list to sort it. That way the assertion error could be removed.

**Comment by Oberon00** [comment]
For this particular test, sorting the client span first would also work, yes. I was just thinking anyone else using `TestUtils.sortByStartTime`, also in other projects, might run into similar issues.

**Comment by harshita19244** [comment]
Should I send out a PR to resolve this particular test then?
Making a change in SDK's clock implementation might be cumbersome, based on my understanding. There's a possibility that others might also run into similar issues with  `TestUtils.sortByStartTime`, should we completely eliminate its use by employing manual sorting or something?

**Comment by Oberon00** [comment]
> Should I send out a PR to resolve this particular test then?

I think it would make sense, yes. If the issue comes up again with another test, we can fix it more generally.

Alternatively, I think my original suggestion to sort root spans first among spans with the same timestamp would also be simple enough to implement and maybe a bit more general.
