### ISSUE TITLE
SpanId and TraceId unused

### ISSUE THREAD

**Issue by Gromcio** [open-telemetry/opentelemetry-java#3074]
https://github.com/open-telemetry/opentelemetry-java/blob/f26ffa90eb1465b51c6e4e99ee7e446dc1e956c5/api/all/src/main/java/io/opentelemetry/api/trace/SpanId.java#L30

From what i can see spanid and traceid are no longer needed in the library

**Comment by jkwatson** [comment]
The static methods on these classes are used extensively throughout the project. Is there something in particular you're thinking of?

**Comment by Gromcio** [comment]
Sorry I've seen it wrong as a type for spanid fields but it's just a helper. My bad :)
