### ISSUE TITLE
Enhance X-Ray propagator to support 64 bits traces extraction

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/opentelemetry-java#3075]
**Is your feature request related to a problem? Please describe.**
Current X-Ray propagator (https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/aws/src/main/java/io/opentelemetry/extension/aws/AwsXrayPropagator.java) is very strict, requiring full 128 bit trace Id for extraction. In particular, second part of the ID has to be 8 chars long. The problem arises with 64 bit traces, padded with 0s, that get compressed by AWS. 

Consider following scenario:
- B3 configured as propagator for a service
- 64 bit traced id coming with request (`795bf8769fe8b9c0`), extracted, padded with 0s - OTEL internal 128 bit representation
- trace Id injected into outgoing AWS SDK request (say - SQS), second part (8 chars) - all 0s - `Root=1-00000000-00000000795bf8769fe8b9c0;Parent=7a339e56d8f86bb1;Sampled=1`
- trace id extracted upon consuming SQS message - first part (0s) compressed by AWS to a single 0 - `Root=1-0-00000000795bf8769fe8b9c0;Parent=7a339e56d8f86bb1;Sampled=1`
- AwsXrayPropagator unable to recognize the trace id upon injection, new trace id is created - propagation broken

**Describe the solution you'd like**
Enhance AwsXrayPropagator to recognize "compression" of the second part as done by AWS. In such case the ID should stil be recognized as valid and left-padded with 0s.

**Describe alternatives you've considered**
Filing issue towards AWS to disable "compression" of leading 0s.

**Additional context**
Tested with current agent and AWS infra, leading 0s are always compressed (removed). 

Tagging @anuraaga for AWS visibility :) If the proposal makes sense, should be relatively easy to implement.

**Comment by anuraaga** [comment]
Hey @kubawach - do you happen to know which service truncates the ID like that? Curious since it's against the spec so probably a bug almost certainly because of using `Integer.toString` mistakenly. Bugs are common since very hard to share code libraries at X-Ray :(

That being said because it's in the wild now I don't see a reason not to support it.

**Comment by kubawach** [comment]
@anuraaga I confirmed this with S3 PUT (produce) - SQS notification (consume). Leading zeroes always compressed :)
