### ISSUE TITLE
API: Global registry in application server with multiple deployments

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#308]
Application servers allow deploying multiple applications. Each application can potentially use different tracer, for example set a different service name, report data differently.

Related issues #218 

We should provide a way for the application server to instantiate multiple tracers.

**Comment by tylerbenson** [comment]
Usually those applications have their own classloaders.  Just throwing an idea out there... maybe we should rely on classloaders each having independent instances of `OpenTelemetry`'s static fields?

**Comment by fmhwong** [comment]
MicroProfile OpenTracing supports automatic instrumentation of JAX-RS calls.  The instrumentation code resides in the app server.  The application does not need to have any OpenTracing instrumentation.  Relying on application class loaders in this case may not work.

**Comment by pavolloffay** [comment]
@fmhwong do you have any suggestions on how to resolve this issue?

**Comment by pavolloffay** [comment]
@fmhwong does OpenLiberty support at the moment a different tracer per deployment? 


* `OpenTelemetry` would hold singletons of  `Tracer|Meter|TaggerProvider`
* `getTracer|Meter|Tagger` would always call the provider for an object
* The providers should be resolved via SPI (like now) with they would always use the highest available implementation (we will iterate to the highest class loader)

The provider in the app server would hold a `Map<deployment, Tracer>`. Would this work in OpenLiberty? Would there be a way to identify deployment in the provider packaged in the app server?

**Comment by fmhwong** [comment]
@pavolloffay 
Sounds like this may work.  I need to build a prototype later to confirm.  If `getTracer()` always calls the provider for a `Tracer` object, what is the purpose of keeping the singletons?

**Comment by pavolloffay** [comment]
>  what is the purpose of keeping the singletons?

The SDK implementation would always return a singleton tracer. To keep the current behavior.

**Comment by pavolloffay** [comment]
I have submitted #350 which caches providers inside `OpenTelemetry` and providers are used to every time when an object has to be returned.

@fmhwong could you please test it?

**Comment by SergeyKanzhelev** [comment]
I'm removing "API Complete" milestone as this is java-specific and should not block cross-reference implementation.

**Comment by anuraaga** [comment]
@pavolloffay Now that `OpenTelemetry` is instantiable, is this issue solved on the SDK side? Each deployment can have its own `OpenTelemetry`. On instrumentation side, we probably still have work to allow configuring them though.

**Comment by fmhwong** [comment]
@anuraaga Do you have an example on how to export traces by 2 services in a single JVM and the traces are shown up in Jaeger as 2 separate services?

It looks like I need to create 2 instances of `JaegerGrpcSpanExporter` with different service names.

**Comment by jkwatson** [comment]
> @anuraaga Do you have an example on how to export traces by 2 services in a single JVM and the traces are shown up in Jaeger as 2 separate services?
> 
> It looks like I need to create 2 instances of `JaegerGrpcSpanExporter` with different service names.

That might work today, but it's unlikely to work in the future when we remove the ability to configure a service name outside of the Resource attached to an SDK instance.

I recommend setting up 2 instances of the OpenTelemetry object, each configured independently with their own Resource in order to have 2 services reporting.

**Comment by fmhwong** [comment]
This was my first attempt on creating 2 instances of `OpenTelemetrySdk`.  

```
public class JaegerExample2 {

    // Jaeger Endpoint URL and PORT
    private final String ip; // = "jaeger";
    private final int port; // = 14250;

    // OTel API
    private static final OpenTelemetrySdk otel1 = OpenTelemetrySdk.builder().build();
    private static final OpenTelemetrySdk otel2 = OpenTelemetrySdk.builder().build();
    
    
    
    public JaegerExample2(String ip, int port) {
        this.ip = ip;
        this.port = port;
    }

    private void setupJaegerExporter(OpenTelemetrySdk otel, String serviceName) {
        ManagedChannel jaegerChannel = ManagedChannelBuilder.forAddress(ip, port).usePlaintext().build();
        JaegerGrpcSpanExporter jaegerExporter = JaegerGrpcSpanExporter.builder().setServiceName(serviceName)
                .setChannel(jaegerChannel).setDeadlineMs(30000).build();
        SpanProcessor sp = SimpleSpanProcessor.builder(jaegerExporter).build();
        otel.getTracerManagement().addSpanProcessor(sp);
    }

    private void app(Tracer tracer, String appName) {
        // Generate a span
        Span span = tracer.spanBuilder(appName).startSpan();
        try (Scope scope = span.makeCurrent()) {
            span.addEvent("Event 0");
            // execute my use case - here we simulate a wait
            doWork(tracer);
            span.addEvent("Event 1");
        } finally {
            span.end();
        }
    }

    private void doWork(Tracer tracer) {
        Span span = tracer.spanBuilder("doWork").startSpan();
        try (Scope scope = span.makeCurrent()) {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            // do the right thing here
            span.recordException(e);
        } finally {
            span.end();
        }
    }

    public static void main(String[] args) {
        // Parsing the input
        if (args.length < 2) {
            System.out.println("Missing [hostname] [port]");
            System.exit(1);
        }
        String ip = args[0];
        int port = Integer.parseInt(args[1]);

        // Start the example
        JaegerExample2 example = new JaegerExample2(ip, port);
        
        Tracer tracer1 = otel1.getTracer("Example2-app1");
        Tracer tracer2 = otel2.getTracer("Example2-app2");
        example.setupJaegerExporter(otel1, "Service-A");
        example.setupJaegerExporter(otel2, "Service-B");
        // generate a few sample spans
        for (int i = 0; i < 3; i++) {
            example.app(tracer1, "app1");
            example.app(tracer2, "app2");
        }

        System.out.println("Bye");
    }
}
```
However, both app1 and app2 were reported under Service-A in Jaeger.  What did I miss?

**Comment by jkwatson** [comment]
On the surface this looks right. I'll need to dig in tomorrow and see what's going on here.

**Comment by jkwatson** [comment]
I found the issue. This is a bug that we need to fix ASAP. Thanks for putting together this example; it was very helpful.

**Comment by jkwatson** [comment]
This has been fixed in #2176 . Thanks again for the repro case, @fmhwong !

**Comment by fmhwong** [comment]
Just tested with version 0.12 and it works as expected.  Thanks for fixing this quickly!

**Comment by jkwatson** [comment]
I think we can close this issue, as we now support as many instances of the SDK as you need, and the global is purely optional. Please re-open if you think we're missing something.
