### ISSUE TITLE
Simplify OpenTracingShim creational patterns

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java#3084]
Introduce builder or
instead of 4 leave only two by removing `createTracerShim(OpenTelemetry openTelemetry)` and `createTracerShim()` from `OpenTracingShim` class

**Comment by jkwatson** [comment]
I might rename this to just "simplify OpenTracingShim creational patterns" because we might want to go with a builder.

**Comment by IrisTuntun** [comment]
Hi, can I take this issue?

cc @alolita

**Comment by anuraaga** [comment]
Thanks @IrisTuntun for your interest in this issue! I think we should hold off temporarily until getting some input on this spec issue I filed

https://github.com/open-telemetry/opentelemetry-specification/issues/1608

I am hoping we can reduce to just a single factory `create(OpenTelemetry openTelemetry)` to simplify both the usage but also the concepts.

**Comment by jack-berg** [comment]
Resolved in #5110.
