### ISSUE TITLE
API: How to expose singletons or special instances of classes

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#309]
Currently we use static constant values like `INSTANCE` (for BlankSpan) or `INVALID` (TraceId/SpanId based on the w3c definition).

Alternative we can use static methods, these have more flexibility on how to construct the objects.

**Comment by pavolloffay** [comment]
`OpenTelemetry` will probably have to stick to a method/`getInstance` as we want lazy loading and accessing a member field would look weird.

`private static final Tracer tracer = OpenTelemetry.TRACER`

**Comment by carlosalberto** [comment]
+1 on static methods.

**Comment by tedsuo** [comment]
## 5/29 Discussion
Agreed:
* Static methods are more future proof than variables.
* Want to be consistent across API. Don't expose any singleton variables; only static methods.

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu can you please send PR today

**Comment by songy23** [comment]
I'll take care of this in https://github.com/open-telemetry/opentelemetry-java/pull/376.

**Comment by bogdandrutu** [comment]
@songy23 please also update the tags and other packages.
