### ISSUE TITLE
./gradlew build gives InvocationTargetException on Windows 10

### ISSUE THREAD

**Issue by harshita19244** [open-telemetry/opentelemetry-java#3097]
Setting up the opentelemetry-java project on windows 10 created an issue for me on the execution of the  `./gradlew build` command. The log I obtained is as follows:
Step 'google-java-format' found problem in 'integration-tests\src\test\java\io\opentelemetry\JaegerExporterIntegrationTest.java':
null
java.lang.reflect.InvocationTargetException

This was not in accordance with the "BUILD SUCCESSFUL" output I had expected to see.
OS: (e.g., "Windows 10")
Runtime (if different from JDK above): java 16 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)

Instead, I used the `gradlew.bat `command.
This can be added to the CONTRIBUTING.md documentation so that more Windows users do not run into similar issues.

**Comment by harshita19244** [comment]
https://github.com/open-telemetry/opentelemetry-java/pull/3082 
resolves the bug

**Comment by jkwatson** [comment]
closing since #3082 resolved the issue
