### ISSUE TITLE
API: Class name BlankSpan vs NoopSpan?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#310]

**Comment by carlosalberto** [comment]
`NoopSpan` sounds better to me ;)

**Comment by bogdandrutu** [comment]
And for the what we called blankspan.INSTANCE, what is the suggestion? Related to https://github.com/open-telemetry/opentelemetry-java/issues/309

**Comment by pavolloffay** [comment]
If we do with `Xdefault` then why not to call span also `DefaultSpan`? Related to #285

**Comment by pavolloffay** [comment]
I also like more `Noop` than `Blank` but maybe I just get used to it from OpenTracing.

`Default` also makes sense for consistency reasons. Noop is not entirely noop bc it propagates the context.

**Comment by tedsuo** [comment]
## 5/29 Discussion

* We are going to remove blankspan.INSTANCE; instead, users should start a span with no parent.
* What is the default behavior of the API when no SDK/Tracer is installed?
* We need to identify the situations where we need a unique SpanID.
* Do we need BlankSpan exposed at all? Does not appear to be useful, but we should investigate.

**Comment by SergeyKanzhelev** [comment]
> We need to identify the situations where we need a unique SpanID.

with ASP.NET Core the idea was that the platform will read headers, begin span context and propagate it further out of the box. Basically - only with "API". The idea than is to use span context for all sorts of diagnostics as a unique identifier of the request. Typical examples are: showing error page to the customer with the ID of a request. Logging - associating request ID with custom logs. Taking a stack traces for all threads with the associated Span ID.

There is no need for any of features above to take a dependency on SDK. As we promise basic context propagation with API only - we should allow people to take dependency on it and assume uniqueness.

**Comment by SergeyKanzhelev** [comment]
There are also cases when SPA and client apps re-using `traceid` for the entire session. Which will break some debuggability problems

**Comment by carlosalberto** [comment]
Btw, forgot to comment on this part:

> Do we need BlankSpan exposed at all? Does not appear to be useful, but we should investigate.

In OpenTracing we have the invariant `Tracer.activeSpan() == null` if there's no active instance, compared to the implicit `BlankSpan` value in OTel. And in order for the OT Bridge to work, we need a way to detect this case:

```java
public Span activeSpan() {
  if (wrappedTracer.getCurrentSpan() instanceof BlankSpan) {
    return null;
  }
  // Continue normally otherwise.
}
```

We could simply return a 'fake' `Span` here for the OT Bridge, but that would break the invariant, as instrumentation code and tests rely on this. So I'd suggest keeping the `BlankSpan` available, even if `INSTANCE` gets publicly removed.

**Comment by SergeyKanzhelev** [comment]
@tedsuo and @carlosalberto mentioned on the call today that they'd also prefer new ID to be generated. 

@yurishkuro @bogdandrutu @pavolloffay can you comment?

**Comment by tedsuo** [comment]
I'm concerned that systems will exhibit surprising behavior – and may be hard to reason about – if spans do not always have unique IDs.

**Comment by SergeyKanzhelev** [comment]
- So we will call it `Default` span. 
- `Default` will generate a new span ID. There will be built-in random algorithm.
- We may need `Invalid` span to mark thread as dis-associated from the Trace
