### ISSUE TITLE
Support ubuntu versions beyond 18.04 for builds

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#3107]
At the moment, our builds fail on ubuntu later than 18.04 in Github Actions, due to an issue with SSL and the armeria test framework. This issue tracks addressing this problem.

Note: it also appears that this fails on Windows WSL with ubuntu, even at version 18.04. We suspect the core issue has to do with java certs that are (or aren't) included by default in the installed java packages.

**Comment by anuraaga** [comment]
@jkwatson Since we somehow got bumped to 20.04 can we close this

**Comment by jkwatson** [comment]
yeah...sure wish I knew what was going on, though!
