### ISSUE TITLE
Metric view registry system property autoconfiguration options

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3108]
**Is your feature request related to a problem? Please describe.**
Its hard to configure the views for `SdkMetricProvider` when using `opentelemetry-java-instrumentation`. The addition of `SdkMeterProviderConfigurer` makes it possible, but users are still required to package up their implementation in a special initializer jar. It should be easy to do basic metric view configuration via system properties. 

**Describe the solution you'd like**
I'd like to see a set of system properties / environment variables like:

| System property          | Environment variable     | Description                                                                       |
|--------------------------|--------------------------|-----------------------------------------------------------------------------------|
| otel.mvr.counter.aggregator | OTEL_MVR_COUNTER_AGGREGATOR | The aggregator factory used for COUNTER instruments. Default is `cumulative_sum`.|
| otel.mvr.up_down_counter.aggregator | OTEL_MVR_UP_DOWN_COUNTER_AGGREGATOR | The aggregator factory used for UP_DOWN_COUNTER instruments. Default is `cumulative_sum`.|
| otel.mvr.sum_observer.aggregator | OTEL_MVR_SUM_OBSERVER_AGGREGATOR | The aggregator factory used for SUM_OBSERVER instruments. Default is `cumulative_sum`.|
| otel.mvr.up_down_sum_observer.aggregator | OTEL_MVR_UP_DOWN_SUM_OBSERVER_AGGREGATOR | The aggregator factory used for UP_DOWN_SUM_OBSERVER instruments. Default is `cumulative_sum`.|
| otel.mvr.value_recorder.aggregator | OTEL_MVR_VALUE_RECORDER_AGGREGATOR | The aggregator factory used for VALUE_RECORDER instruments. Default is `summary`.|
| otel.mvr.value_observer.aggregator | OTEL_MVR_VALUE_OBSERVER_AGGREGATOR | The aggregator factory used for VALUE_OBSERVER instruments. Default is `last_value`.|

Supported values for `otel.mvr.{instrument}.aggregator` are

- "cumulative_sum": AggregatorFactory.sum(alwaysCumulative=true)
- "delta_sum": AggregatorFactory.sum(alwaysCumulative=false)
- "cumulative_count": AggregatorFactory.count(temporality=CUMULATIVE)
- "delta_count": AggregatorFactory.count(temporality=DELTA)
- "summary": AggregatorFactory.minMaxSumCount()
- "last_value": AggregatorFactory.lastValue()

**Describe alternatives you've considered**
I also considered the notion of reasonable default aggregation "profiles". The idea being that rather than having low level control over the aggregation of each of the instruments, perhaps a simpler higher level configuration would be suitable. There could be different profiles based on what how different backends support / prefer the metrics to be aggregated. Selecting a profile would configure the aggregations of all the instruments to some suitable value.

**Comment by jkwatson** [comment]
We wouldn't want to add this until it was official in the spec. I suggest opening a spec issue for this.

**Comment by jack-berg** [comment]
Is there no ability to accommodate configuration of beta / prototype features? My understanding is that java metrics are a bit further along than the spec. Could we offer configuration of these beta / prototype features by indicating in the property name that they're experimental and subject to change? 

For example, over in the `opentelemetry-java-instrumentation` project they support a system property called `otel.javaagent.experimental.initializer.jar`.

**Comment by jkwatson** [comment]
hmm. If we made all the env vars have the word "EXPERIMENTAL" in them, I think I could get behind that.

Also, no option for histogram in there?

**Comment by jack-berg** [comment]
The spec specifies [this pattern](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#language-specific-environment-variables) for language specific feature configuration. 

So I suppose the property naming pattern would be something like: `otel.java.experimental.mvr.up_down_counter.aggregator`

Histogram seems a bit more challenging to configure given that the constructor takes a list of arbitrary buckets. I could imagine something like:
```
cumulative_histogram(10.0,100.0,1000.0) => AggregatorFactory.histogram(Arrays.asList(10.0,100.0,1000.0), CUMULATIVE)
delta_histogram(10.0,100.0,1000.0) => AggregatorFactory.histogram(Arrays.asList(10.0,100.0,1000.0), DELTA)
```
Is there a way to configure histograms without defining some syntax for specifying / parsing the bucket values?

**Comment by jkwatson** [comment]
we'd almost certainly need to define a syntax for the histogram configuration.  Could we have one variable for "configuration options" and use it for anything that needs configuration? Any kind of sketch, etc, will certainly need non-trivial config in the future too.

**Comment by jack-berg** [comment]
I like the idea of two variables - one for specification of the factory, another for any options. The options variable could be a comma separated list of name value pairs of argument type, argument value - the same way that resource key value pairs are configured. 

We'd have to choose some syntax for argument values that are complex types, such as the boundaries list of doubles for histograms. We can't use `,` to delimit the values, since we'd already be using it to delimit the key value pairs. One option would be to adopt the JSON list syntax (i.e. `key1=[1.0,2.0,3.0]`).

Anyway, here's what that would look like for the various aggregator factories:
```
// General syntax
-Dotel.java.experimental.mvr.{instrument}.aggregator_factory=histogram|sum|count|last_value|min_max_sum_count
-Dotel.java.experimental.mvr.{instrument}.aggregator_options=key1=value2,key2=value2

// Histogram example
// Aggregator options: List<Double> boundaries, AggregationTemporality temporality
-Dotel.java.experimental.mvr.value_recorder.aggregator_factory=histogram
-Dotel.java.experimental.mvr.value_recorder.aggregator_options=boundaries=[1.0,10.0,100.0],temporality=cumulative

// Sum example
// Aggregator options: boolean alwaysCumulative
-Dotel.java.experimental.mvr.counter.aggregator_factory=sum
-Dotel.java.experimental.mvr.counter.aggregator_options=alwaysCumulative=cumulative

// Count example
// Aggregator options: AggregationTemporality temporality
-Dotel.java.experimental.mvr.counter.aggregator_factory=count
-Dotel.java.experimental.mvr.counter.aggregator_options=temporality=cumulative

// Last value example
// Aggregator options: none
-Dotel.java.experimental.mvr.value_recorder.aggregator_factory=last_value

// MinMaxSumCount (summary) value example
// Aggregator options: none
-Dotel.java.experimental.mvr.value_recorder.aggregator_factory=min_max_sum_count
```

**Comment by jkwatson** [comment]
maybe replace `mvr` with `view`, and remove the `factory` from the `aggregator_factory`, leaving, for instance, `-Dotel.java.experimental.view.value_recorder.aggregator=summary` for example, which is much more human readable?

**Comment by jack-berg** [comment]
Shall I give it a go with an implementation?

**Comment by jkwatson** [comment]
> Shall I give it a go with an implementation?

I'd let @anuraaga chime in about experimental stuff in autoconfigure first. We've also been pondering splitting out metrics configuration into a separate autoconfigure module, so we could stabilize the tracing part, so that could make a difference, as well.

**Comment by jack-berg** [comment]
We discussed shelving this until the metrics API stabilizes. @jkwatson shall I close this issue, or do want to add a label?

**Comment by jkwatson** [comment]
I added the blocked:spec label. We can keep it open, as we'll need it eventually.

**Comment by jack-berg** [comment]
Closing now that #4163 is merged. Would be better if the spec had explicit support for this, but experimental support at least makes view config possible without programatic configuration.
