### ISSUE TITLE
Empty tracestate values are allowed according to W3C spec

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3116]
In #3104 we banned empty tracestate values (per key-value pair). The W3C spec does allow empty values though, see https://www.w3.org/TR/trace-context-1/#value

> ```value    = 0*255(chr) nblk-chr```

(note that it says `0*255`, not `1*255`).

We need to restore the ability to parse/set empty strings as values for a tracestate key (without crashing).

**Comment by anuraaga** [comment]
@Oberon00 Doesn't the nblk-chr after it enforce there's a character?

**Comment by Oberon00** [comment]
Oops, there is a nonblank that is always required.
