### ISSUE TITLE
API: Apply same logic for parent to TagMap as we do for Span

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#312]
Currently we have 3 ways to start a TagMapBuilder, probably we should do the same think as we do for SpanBuilder.

https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/tags/Tagger.java#L45

**Comment by carlosalberto** [comment]
I've been thinking about the names here, as, when building a new `TagMap` based on an existing one, it does **not** feel like a parent-child relationship. Anyway, what about:

```java
  // Tagger
  public TagMap.Builder tagMapBuilder();

  // TagMap.Builder
  public Builder setEmpty();
  public Builder setInitialTagMap(TagMap tagMap);
```
?

This is kinda verbose (specially the last method), but it slightly feels like a better name. Thoughts? (alternative names: `setInitial()`, `setBasedOn()`)

**Comment by bogdandrutu** [comment]
I personally like more "parent". I was also thinking to implement this as:

```java
public final class TaggerSdk implements Tagger {
  Tagger parent;
  List<Tag> tags; 

  // getTagValue will look initially in the tags list then in the parent.getTags

  // getTags will de-dup tags by TagKey and return a single list iterator.
}
```

More about implementation when we do that, but the main idea is that this is chained to avoid de-dup all the time a tag is added. I know that the chain can get long but we can have a limit of the levels and if that level is hit we flatten the chain for example.

**Comment by tylerbenson** [comment]
@bogdandrutu how should `TagMap.Builder.remove(TagKey)` work in relation to the parent?  Do I need to maintain a placeholder value that signifies it was deleted?  Is it worth the additional complexity to avoid the copying?

**Comment by bogdandrutu** [comment]
Remove can be treated as adding with a null value.

**Comment by tylerbenson** [comment]
I was originally going to have `Builder put(TagKey key, TagValue value, TagMetadata tagMetadata)` assert null for each of the arguments, but from your comment it seems like maybe it should be ignored if key/value are null?  In that case, should remove ignore the parent and only apply to the current map?

**Comment by tylerbenson** [comment]
Also, how should that deduping work?  Should that happen in the builder or when constructing the iterator?

(Does this new separation really benefit us much?)

**Comment by bogdandrutu** [comment]
@tylerbenson are you probably talking about the implementation here, so probably we should move this discussion to a different issue, because the initial issue was about https://github.com/open-telemetry/opentelemetry-java/pull/356.

Based on our experience not copying helps (especially in non-gc languages like C++ where you literally have to copy the entire memory).

De-dup happens during iteration, which in our case is less often than addition. That being said we can benchmark this (I would recommend jmh) to see what is better in Java world.
