### ISSUE TITLE
Make ConfigProperties#createForTest() public

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#3141]
**Is your feature request related to a problem? Please describe.**
Creating a `ConfigProperties` instance when you want to unit test your custom `ConfigurableSpanExporterProvider` or `ResourceProvider` is a bit painful right now (if you're not using groovy). By making this method public people implementing (and testing) autoconfig's SPI classes will be able to do it in a bit nicer way.

**Comment by jkwatson** [comment]
Any problem with using Mockito to mock this class?

**Comment by mateuszrzeszutek** [comment]
Yeah, it's final.

**Comment by jkwatson** [comment]
https://www.baeldung.com/mockito-final :)

**Comment by mateuszrzeszutek** [comment]
😮 

Wow, I wasn't aware of that magic - I guess I learned something new today 😄
