### ISSUE TITLE
How can we export the opentelemetry metrics to traces spans?

### ISSUE THREAD

**Issue by ChandrewR** [open-telemetry/opentelemetry-java#3147]
How can we export the opentelemetry metrics to traces spans? I see metrics example code is instrumenting jvm memory, but not using anywhere like attaching it to Span attributes or exporting to traces. How can we use OpenTelemetry metrics to attach it to Span? 

Couldnt understand the usage of metrics with the examples..Can you pls provide us some good exmaples which shows end to end usage of metrics APIs?

**Comment by jkwatson** [comment]
I'm going to convert this to a discussion, since it's a question, not a bug.
