### ISSUE TITLE
why host.name can't be a default attribute in resource

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java#3157]
I have found host.name isn't in any default ResourceProvider. Why it can't be?

**Comment by jkwatson** [comment]
I think it could be. Someone would need to write a ResourceProvider for this. Currently, the EC2Resource does provide this, but nothing else does at the moment.

**Comment by tydhot** [comment]
> I think it could be. Someone would need to write a ResourceProvider for this. Currently, the EC2Resource does provide this, but nothing else does at the moment.

Oh, I am willing to write a ResourceProvider to make it be the default attribute. But I am not sure how should the ResourceProvider be named and what other attributes should be added.

**Comment by iNikem** [comment]
`HostResourceProvider`? :)

**Comment by tydhot** [comment]
> `HostResourceProvider`? :)

I think the name is appropriate, I will try to write one :)
