### ISSUE TITLE
Add delta support for sum aggregator for SumObserver and UpDownSubObserver

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3160]
**Is your feature request related to a problem? Please describe.**
The `opentelemetry-java-instrumentation` runtime metrics use UpDownSumObserver instruments to observe jvm memory usage. Currently, there's no way to configure the agent to export delta sums from these instruments because its not supported in the SDK.

**Describe the solution you'd like**
The current sum aggregator only partially supports delta aggregation temporality. This is reflected in the factory method which accepts `boolean alwaysCumulative` instead of `AggregationTemporality temporality`: 
```
AggregatorFactory sum(boolean alwaysCumulative) 
``` 
This behavior reflects the fact that sum observer and up down sum observer are assumed to be observing cumulative sum metrics. Converting observed cumulative sums to deltas is possible, but requires maintaining state and taking a diff of `currentAccumulation - previousAccumulation`. 

I'd like to see full delta support added to the sum aggregator factory, and this be reflected in a new constructor signature:
```
static AggregatorFactory sum(AggregationTemporality temporality)
```

**Describe alternatives you've considered**
None. 

**Additional context**
None.

**Comment by jkwatson** [comment]
This seems reasonable to me. Are you able to put in a PR for it, @jack-berg ?

**Comment by jkwatson** [comment]
heh. I guess so. :)
