### ISSUE TITLE
Add Span.setAttributes method

### ISSUE THREAD

**Issue by Volodymyr-Maiboroda-Imprivata** [open-telemetry/opentelemetry-java#3178]
**Is your feature request related to a problem? Please describe.**
I'm creating a common library that traces models. This library should not write directly in the span but collect the attributes and return them. The reason for this issue, that there is no possible way to put the `Attributes` object or `Map` in `Span`. 

**Describe the solution you'd like**
It would be nice to add a method `setAttributes` in the Span interface to be able to put a butch of attributes once.

**Comment by jkwatson** [comment]
See #2799

**Comment by Volodymyr-Maiboroda-Imprivata** [comment]
Closed it as a duplicate. This feature should be implemented by this #2799
