### ISSUE TITLE
Expose Resource.TELEMETRY_SDK resource field

### ISSUE THREAD

**Issue by wallezhang** [open-telemetry/opentelemetry-java#3227]
**Is your feature request related to a problem? Please describe.**
I want to create a customer resource and merge `TELEMETRY_SDK` resource. As for now, the `DEFAULT` resource I can get including a `SERVICE_NAME` key with `unknown_service:java` value, and I can't replace the default `SERVICE_NAME` attribute even if I put a new `SERVICE_NAME` key.

**Describe the solution you'd like**
Expose `TELEMETRY_SDK` field just like `io.opentelemetry.sdk.resources.Resource#getDefault` does.

**Comment by jkwatson** [comment]
If you're building a Resource, you can definitely merge with the default resource in either order. You should be able to override the default service name: 
```
    Resource my_service = Resource.getDefault()
        .merge(Resource.builder().put("service.name", "my_service").build());

```

**Comment by wallezhang** [comment]
> If you're building a Resource, you can definitely merge with the default resource in either order. You should be able to override the default service name:
> 
> ```
>     Resource my_service = Resource.getDefault()
>         .merge(Resource.builder().put("service.name", "my_service").build());
> ```
> 
> or
> 
> ```
>     Resource my_service = Resource.getDefault().toBuilder()
>         .put("service.name", "my_service").build();
> ```

OK, thanks for your reply. I will try it.

**Comment by wallezhang** [comment]
It does work, Thanks!
