### ISSUE TITLE
Wrong package referenced in TracerProvider

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#323]
https://github.com/open-telemetry/opentelemetry-java/blob/7f4d9536ad99d38f48b423bf0bc356a90191dfe4/api/src/main/java/io/opentelemetry/trace/spi/TracerProvider.java#L22-L24

I think this should say `META-INF/services/io.opentelemetry.trace.spi.TracerProvider` (trace, not trace**r**) in order to be picked up by `ServiceLoader.load(io.opentelemetry.trace.spi.TracerProvider.class)`.

**Comment by pavolloffay** [comment]
Thanks, there was a typo
