### ISSUE TITLE
Pass user defined values to metrics like Span attributes and events..

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java#3248]
As of now, the OpenTelemetry metrics don't have any options to export the additional values with metrics like we have option to add some key value pairs in attributes and events in Spans. Will we have option to add custom values?? 

Thinking in the perspective to add the trace id and span id with the metrics that we collect and export to co-relate the events...

**Comment by jkwatson** [comment]
Hi @chandru-kumar . The way that OpenTelemetry is planning to address this is by having the metrics SDK have an option to provide a MetricsProcessor that can pull the current span out of the `Context` and use that to provide it as an exemplar along with that metric recording. This hasn't been implemented yet (and, the metrics specification is still in an experimental state), but it should be in the future.

**Comment by chandru-kumar** [comment]
Ok. Thank you..
