### ISSUE TITLE
New family MucterXx and NastasyaVedma, and them son

### ISSUE THREAD

**Issue by PiratkaXx** [open-telemetry/opentelemetry-java#3250]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PiratkaXx** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is.
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 

![Screenshot_20210502-181424.png](https://user-images.githubusercontent.com/52059739/119411449-1d533800-bcf3-11eb-8502-6110dcfa4e72.png)

**Comment by anuraaga** [comment]
I submitted an abuse report to GitHub again, will leave this issue for a couple of days and then delete it.
