### ISSUE TITLE
Manual Instrumentation documentation incomplete

### ISSUE THREAD

**Issue by ecourreges-orange** [open-telemetry/opentelemetry-java#3257]
**Describe the bug**
The [manual instrumentation](https://github.com/open-telemetry/opentelemetry-java/blob/main/website_docs/manual_instrumentation.md) page shows no imports, so with an IDE that has more or less no auto import and for a Java beginner, it is impossible to find what it needed to be imported in order to compile

Also it is not 100% clear if the tracer we get manually connects/configures properly with what is created by the java agent.

**Steps to reproduce**
Copy and paste the code as-is, it won't work
`Tracer tracer = openTelemetry.getTracer("instrumentation-library-name", "1.2.0");`

**What did you expect to see?**
Being able to quickly add manual spans requires the code snippet to be self sufficient.
Googling it leads nowhere recent, as version 1.0+ is recent.
The code example "Tempo" doesn't use tracer so as such it is not helpful
**Please add the proper imports on top of each code snippet** and I will be happy (just like in the @WithSpan examples of the instrumentation repo).

Thanks,
Regards.

**Comment by jkwatson** [comment]
For complete working examples, the `examples` directory is probably a better source for turnkey example code that runs.

**Comment by jkwatson** [comment]
@ecourreges-orange have you had a chance to look at the examples?

**Comment by ecourreges-orange** [comment]
> 
> 
> @ecourreges-orange have you had a chance to look at the examples?

Yes, sorry for the late answer, so the examples do help and show that the initialization is not as simple as "getTracer()".
But now what I need to know and is not clear from the documentation that I have read, is how are exporters linked between the one in the agent and the one in manual code?
I suppose I can use the auto-configure example and it will use the same -Dotel.* as the java-agent, however I also suppose that it will establish its own connections to collectors and will send spans separately? 
Any issues to expect from that?

I guess my real request is to have in documentation an end-to-end example of hybrid agent+manual code and an explanation of how both interact.

Thank you.

**Comment by ecourreges-orange** [comment]
I have to say I really loved the ease of use of the agent, as I can add it generically to all our APIs, and then if I need more instrumentation precision, I go in the code and want to do minimum effort to add manual spans.

In many cases the @WithSpan annotation is not enough, for instance when a method calls 3 methods in libraries that I don't want to instrument, then i want to create 3 manual spans, but I guess I could also split the first method in 3 and put @WithSpan on each...

**Comment by jkwatson** [comment]
> I guess my real request is to have in documentation an end-to-end example of hybrid agent+manual code and an explanation of how both interact.

This sounds like something that belongs in the instrumentation project (rather than here). Could you start a discussion over there?

**Comment by jkwatson** [comment]
> In many cases the @WithSpan annotation is not enough, for instance when a method calls 3 methods in libraries that I don't want to instrument, then i want to create 3 manual spans, but I guess I could also split the first method in 3 and put @WithSpan on each...

If you can split into 3 methods and use `@WithSpan`, it'll be much much easier to read the code, I would guess. If you need to do the more difficult thing, the agent does populate the `GlobalOpenTelemetry` instance for you, so you can use that directly and it will be fully integrated with the agent's own instrumentation.

**Comment by ecourreges-orange** [comment]
> `GlobalOpenTelemetry`

Thanks @jkwatson now that you have given me the keyword GlobalOpenTelemetry, I found your previous conversation which makes sense: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/1945

So closing this an continuing on that conversation.
