### ISSUE TITLE
Support OTLP retry

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3271]
**Is your feature request related to a problem? Please describe.**
The OTLP exporter specification says that [transient errors MUST be handled with a retry strategy](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#retry), where the retriable gRPC error codes are defined in the [OTLP spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-response). 

I don't believe this is currently embodied in the java code anywhere, but that it could be by specifying an appropriate service config when setting up the managed channel when building the Span / Metric OTLP exporters. (Here's an [example](https://github.com/grpc/grpc-java/blob/v1.35.0/examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldClient.java#L74) of setting up a managed channel and [here's](https://github.com/grpc/grpc-java/blob/v1.35.0/examples/src/main/resources/io/grpc/examples/retrying/retrying_service_config.json) the service config JSON that specifies the retry policy. 

**Describe the solution you'd like**
I think we should implement gRPC retry for the Span and Metric OTLP exporters by specifying the service config. 

**Additional context**
I couldn't find any historical context as to why this isn't implemented today, but it seems like it should be reasonably straight forward to do.

**Comment by jkwatson** [comment]
Right now, this is "supported" by letting the user configure a channel explicitly for the exporter when configuring their SDK. I'm not opposed to having some sort of retry-enabled channel be the default, but I'm a little nervous about making an arbitrary choice of that configuration when autoconfigure/auto-instrumentation users don't currently have a way to change it.

**Comment by jack-berg** [comment]
The spec specifies that the retry strategy "MUST implement an exponential back-off with jitter" so it wouldn't be completely arbitrary. Although we'd have to come up with some values for the exponential backoff parameters like the initial and max backoff.

Technically if we did implement this and enable it by default auto instrumentation users still have an escape hatch for not using it via SPI. Not great, but disabling it would still be supported in the same sense that enabling it is supported today.

It feels like the spec could use a little more clarity around exactly the retry backoff strategy could be configured. It could also use some configuration properties around tuning the backoff strategy - perhaps changing the parameters or disabling it altogether. 

Another thought I had was that we could we could add an experimental autoconfigure parameter to either enable or disable this behavior (depending on what the default it). For example, we could let it "incubate" by adding it to the autoconfigure module and having it be enabled by an experimental parameter. Or in the other direction, if we enabled it by default and added the code the the Span and Metric OTLP exporter builders, we could add an experimental parameter to autoconfigure to disable it.

**Comment by jkwatson** [comment]
@jack-berg would you mind opening up a spec issue to track the lack of specificity?

**Comment by jack-berg** [comment]
Here's an [example](https://github.com/newrelic/newrelic-opentelemetry-examples/blob/main/java/shared-utils/src/main/java/com/newrelic/shared/OtlpUtil.java#L72-L74) of how you can configure `ManagedChannel` to retry on retryable status codes. 

Its pretty cumbersome. 

We could improve the ergonomics of enabling retries while awaiting the spec by providing a method like:
```
public OtlpGrpcSpanExporterBuilder setRetryPolicy(RetryPolicy retryPolicy) {...}
```
where `RetryPolicy` is just a data carrier carrying the various configurable knobs for a retrying. 

A helper method could translate the `RetryPolicy` to the `Map<String, ?> serviceConfig` expected when configuring `ManagedChannel`.

Later once the spec catches up, we could enable retry by default, or add an even simpler `public OtlpGrpcSpanExporterBuilder enableRetry()` method.

**Comment by jack-berg** [comment]
Added experimental support for the OTLP grpc exporters in #3791.
