### ISSUE TITLE
javadocs link in logging-otlp exporter broken

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java#3283]
Link to javadocs in [logging-otlp exporter readme] https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/logging-otlp is broken.

![image](https://user-images.githubusercontent.com/75337021/120719942-02fe2480-c480-11eb-8719-7045a455e620.png)

**Comment by jkwatson** [comment]
So, the link is definitely wrong, but what I think should be the correct link isn't working on javadoc.io, either:

https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-exporters-logging-otlp

I'm not sure what's up here.

**Comment by jkwatson** [comment]
ok, dumb typo... should be singular `exporter`

**Comment by breedx-splk** [comment]
Thanks thanks.
