### ISSUE TITLE
This repo need to have CODEOWNERS file to follow the best practices

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-java#329]
See https://github.com/open-telemetry/community/blob/master/docs/how-to-configure-new-repository.md

**Comment by SergeyKanzhelev** [comment]
sorry, missed it's in different location https://github.com/open-telemetry/opentelemetry-java/blob/master/.github/CODEOWNERS Perhaps consider moving it.

**Comment by songy23** [comment]
I think CODEOWNERS file needs to be under `.github/` so that Github can auto-assign reviewers accordingly, though I could be wrong. /cc @bogdandrutu

**Comment by pavolloffay** [comment]
It can be in any of `root/.github/docs` directories https://help.github.com/en/articles/about-code-owners#codeowners-file-location

**Comment by bogdandrutu** [comment]
Happy to move this into the root to follow the best practices.
