### ISSUE TITLE
GlobalMeterProvider Instantiation

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-java#3296]
**Describe the bug**
When getting a meter provider ordering of execution matters to a great extent.

**Steps to reproduce**
Get a meter from the GlobalMeterProvider as part of a class definition.

**What did you expect to see?**
Similar to how `getLogger` works that when `getMeter` can be done anywhere in my class whether as part of a static class attribute or as a variable in a function that the meter does not go to the Noop Meter provider.

I expected to see all metrics which I registered available using my default meter.

**What did you see instead?**

I saw some Instruments go to Noop and some go to the default SDK

**What version and what artifacts are you using?**
Artifacts: , `opentelemetry-api`, `opentelemetry-sdk`, prometheus exporter
Version: v1.2.0-alpha
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)
```
dependencies {
    compile "io.opentelemetry:opentelemetry-api-metrics:${opentelemetry_version}"
    compile "io.opentelemetry:opentelemetry-sdk-metrics:${opentelemetry_version}"
    compile "io.opentelemetry:opentelemetry-exporter-prometheus:${opentelemetry_version}"
```

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6") JDK 1.8.0
OS: (e.g., "Ubuntu 20.04") Fedora 34
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251") 1.8.0_292
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by hdost** [comment]
Actually it looks as though there's already a decent pattern setup for Tracing registry https://github.com/open-telemetry/opentelemetry-java/blob/0a9e77f751fd05b51a38257db6c00de37304b510/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProvider.java#L31 we're just not using it.

**Comment by jkwatson** [comment]
Hi @hdost . Metrics is still in alpha state. When it's stable and ready for official release, it will be integrated into the rest of the OpenTelemetry API/SDK module and will follow the same patterns as the tracing APIs/SDK. 

But, we still very strongly recommend that you initialize your SDK at the earliest possible moment in your application. And, ideally, do not use the global instances unless you have no other recourse.

**Comment by hdost** [comment]
Yup, i know it's still alpha if it's actually considered a bug I think this would still be a bug or at least tech debt because of the wide difference in implementation. At a minimum I point to it out because I could do some implementation changes.

**Comment by jkwatson** [comment]
If you have some quick fixes to the current GlobalMeterProvider implementation (to try to do auto-configuration like we do for tracing, for example), that would definitely be welcome.

**Comment by anuraaga** [comment]
I believe this issue is from before autoconfigure did metrics, and we've integrated metrics into the standard OTel APIs and added setMeterProvider methods where appropriate to control ordering. Hopefully this issue is solved but let us know if there's more we can do.
