### ISSUE TITLE
Flaky test in CI

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#3311]
This seems to be showing up quite a bit now:

```
> Task :context:strictContextEnabledTest

StrictContextEnabledTest > garbageCollectedScope() FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in io.opentelemetry.context.StrictContextEnabledTest Contain the string <Scope garbage collected before being closed.> ==> None of the 0 captured log events matched the filter predicate within 30 seconds.
        at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:166)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at io.opentelemetry.context.StrictContextEnabledTest.garbageCollectedScope(StrictContextEnabledTest.java:32)

        Caused by:
        org.opentest4j.AssertionFailedError: Contain the string <Scope garbage collected before being closed.> ==> None of the 0 captured log events matched the filter predicate
            at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
            at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
            at io.github.netmikey.logunit.api.LogCapturer.lambda$assertContains$3(LogCapturer.java:174)
            at java.base/java.util.Optional.orElseGet(Optional.java:369)
            at io.github.netmikey.logunit.api.LogCapturer.assertContains(LogCapturer.java:173)
            at io.github.netmikey.logunit.api.LogCapturer.assertContains(LogCapturer.java:121)
            at io.opentelemetry.context.StrictContextEnabledTest.lambda$garbageCollectedScope$0(StrictContextEnabledTest.java:36)
```

**Comment by Oberon00** [comment]
Also here in my PR: https://github.com/open-telemetry/opentelemetry-java/actions/runs/935680619

**Comment by Rocksnake** [comment]
> Also here in my PR: https://github.com/open-telemetry/opentelemetry-java/actions/runs/935680619

In the action of this PR, it has run without errors. Has this issue been solved? If not, could you provide the recurring scene. Thanks!

**Comment by jkwatson** [comment]
> > Also here in my PR: https://github.com/open-telemetry/opentelemetry-java/actions/runs/935680619
> 
> In the action of this PR, it has run without errors. Has this issue been solved? If not, could you provide the recurring scene. Thanks!

It's definitely not solved. It just happens sporadically, so it's hard to provide any concrete way to reproduce it.

**Comment by Oberon00** [comment]
Either I posted the wrong link or it switched to the latest build of that PR.

**Comment by jkwatson** [comment]
> Either I posted the wrong link or it switched to the latest build of that PR.

yeah, when you re-run, it replaces the contents with the latest build, rather than generating a new run id, unfortunately.

**Comment by Rocksnake** [comment]
After investigation, I found that the problem may lie in await(). Because there was no captured log events, a timeout exception occurred due to failure of lambda match. I think we should add conditions to determine whether the size of the log event is zero, or add a poll in await(). Just like this:
<img width="782" alt="截屏2021-06-18 13 20 06" src="https://user-images.githubusercontent.com/44219737/122510285-f0671c00-d037-11eb-85b1-2cc0390303ca.png">

Could you tell me roughly the steps that caused this exception? Because I don’t know how to check if it solves the problem. Or I mention a pr and you help me see if there is still a problem.

**Comment by jkwatson** [comment]
@Rocksnake I don't think you can blame the awaitility library for this. it's doing what it should; the source of the issue has to be in the way that we're generating what should be the bad data.

And, no, we have no idea what is causing the test to fail. Hence the issue. :)

**Comment by Rocksnake** [comment]
I went to check the official github project of awaitility and found this [issue](https://github.com/awaitility/awaitility/issues/109), which describes exactly this problem. Share with us. 😃I guess there is no problem with the LogCapturer that log source.

**Comment by jkwatson** [comment]
> I went to check the official github project of awaitility and found this [issue](https://github.com/awaitility/awaitility/issues/109), which describes exactly this problem. Share with us. 😃I guess there is no problem with the LogCapturer that log source.

I don't see how that issue matches this one at all. In this case, we're finding no events in the time window, not that the message is somehow confusing.

**Comment by anuraaga** [comment]
We haven't seen this in a long time - let's go ahead and close for now and can look again if it comes up.
