### ISSUE TITLE
How use OpenTelemetry sends the distributed context over the RPC request，eg:Dubbo

### ISSUE THREAD

**Issue by EricGreen239** [open-telemetry/opentelemetry-java#3322]
i saw the opentelemetry-java gRPC examples，but docs don't have about RPC reuqest example like Dubbo，pls show me Dubbo's example

**Comment by anuraaga** [comment]
Hi @EricGreen239 - you can use the Dubbo instrumentation, as long as it's on the classpath it is automatically registered

https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/apache-dubbo-2.7/library

**Comment by EricGreen239** [comment]
got it ,thanks
