### ISSUE TITLE
Allow using custom configuration sources in sdk-autoconfigure

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#3326]
**Is your feature request related to a problem? Please describe.**
Currently the sdk-autoconfigure module only loads configuration from two sources: system properties and environment variable. Aside from those two, the javaagent also allows using the `PropertySource` SPI and a config file (`otel.javaagent.configuration-file`) to configure agent and SDK.

The ask here is to bridge that gap between the SDK and the javaagent and allow passing configuration from custom sources when using the autoconfigure module. Currently to solve that problem we use a [hack](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/OpenTelemetryInstaller.java#L38) and copy all sdk-related properties to system properties so that SDK picks them up. 

**Describe the solution you'd like**
I don't have any preferred solution, any of the following would do:
* enable passing a `Map<String, String>` that contains full configuration to `OpenTelemetrySdkAutoConfiguration#initialize()`;
* enable passing a `ConfigProperties` instance (assuming it's an interface after https://github.com/open-telemetry/opentelemetry-java/pull/3304 gets merged) to the `initialize()` method; the javaagent `Config` could simply implement that interface;
* porting the SPI class from the javaagent to sdk-autoconfigure;
* any other that I did not think of.

**Additional context**
The javaagent SPI: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/spi/config/PropertySource.java

**Comment by jkwatson** [comment]
The 2nd option (add a method to `initialize()` that takes ConfigProperties as a parameter seems pretty reasonable to me.

**Comment by trask** [comment]
@jkwatson @anuraaga what are your latest thoughts on this? would you like send a PR that converts `ConfigProperties` to an interface and adds an `initialize()` overload that takes `ConfigProperties` (instead of waiting on #3304)?

**Comment by jkwatson** [comment]
Happy to have a PR to implement this.

**Comment by mateuszrzeszutek** [comment]
Cool! Can you assign this to me? I should be able to get it done this week.
