### ISSUE TITLE
Avoid duplicate code for Scope implementation

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#333]
Currently in Default[Tracer|Tagger] we have an implementation of the Scope as well as in the SDK. I think this is not ideal and I would suggest that we remove the duplicated code.

I will suggest that we remove this duplicated code, the options that I see are:
1. We change Default[Tracer|Tagger] to not be final and [Tracer|Tagger]Sdk inherit from the Default.
1. We move the Scope implementation in the usafe.ContextUtil for every package so that both the Default and the Sdk implementation can share this.

Any thoughts?

**Comment by bogdandrutu** [comment]
Links:
https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/DefaultTracer.java#L182
https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java#L80
https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/tags/DefaultTagger.java#L154
https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/tags/internal/CurrentTagMapUtils.java#L48

Also we should do the same as I did and remove the internal/CurrentContextUtil from the tags/sdk.

**Comment by pavolloffay** [comment]
I lean more towards 2. as 1. forces using the same key for different impls.

**Comment by bogdandrutu** [comment]
Even the first version forces that because we call into the unsafe anyway. But I also kind of like more the second.

**Comment by tylerbenson** [comment]
@bogdandrutu I submitted my PR to cover this issue, but I'm not quite clear about this point:
> Also we should do the same as I did and remove the internal/CurrentContextUtil from the tags/sdk.

Is this what you were asking for: https://github.com/open-telemetry/opentelemetry-java/pull/348/commits/94e305df162e9bb7cab94f959f7fa4fe75a3b189?

**Comment by bogdandrutu** [comment]
@tylerbenson but we need same thing in Trace.

**Comment by bogdandrutu** [comment]
Based on a private IM, see:
https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/DefaultTracer.java#L182
https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java#L104

Please do this in a separate PR.

**Comment by tylerbenson** [comment]
@bogdandrutu I think I already did that in #348.  Let me know if I missed something.
