### ISSUE TITLE
(Further) reduce CPU usage of batch span processor 

### ISSUE THREAD

**Issue by franz1981** [open-telemetry/opentelemetry-java#3338]
That's a follow-up issue of https://github.com/open-telemetry/opentelemetry-java/issues/2968

Same purpose, but as mentioned on https://github.com/open-telemetry/opentelemetry-java/issues/2968#issuecomment-864370074

I see that the referenced commit is using a CLQ with a separate size tracker to overcome the size complexity of CLQ; I strongly suggest to use MpscUnboundedXaddArrayQueue on JCTools that offer:

(order of magnitude) better behaviour then any compare-and-set queue alternative, under contention
GC free if correctly configured or lower allocation rate then CLQ
O(1)-ish size although I suggest to try different strategies: size is linearish but it would invalidate producer and consumer sequences if queried before any offer, slowing down a streaming consumer
The latter suggest that using a LongAdder or an atomic counter of JCTools is a better choice

@sbandadd too

**Comment by sbandadd** [comment]
The referenced commit in the issue was used only for benchmarks. The merged PR's used MPSCArrayQueue https://github.com/open-telemetry/opentelemetry-java/blob/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java#L75.

@franz1981 could you run the benchmarks the [benchmark](https://github.com/open-telemetry/opentelemetry-java/blob/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBenchmark.java) with the current queue and the new queue you are proposing?

**Comment by franz1981** [comment]
Not as good as I wished:
![image](https://user-images.githubusercontent.com/13125299/122936986-e6178b80-d371-11eb-8f6f-74648942d99a.png)

Consider that I've used [benchmark](https://github.com/open-telemetry/opentelemetry-java/blob/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorBenchmark.java) setting mpsc array q of capacity == `spanCount * 5` (where 5 is the number of threads calling `export`).

The mpsc array capacity is correct? Or should be less or more?

**Comment by franz1981** [comment]
I've investigated with async-profiler a bit more what's going on here...

mpsc array q: 412 samples with 100 Hz profiler -> ~42% CPU usage
![image](https://user-images.githubusercontent.com/13125299/122948681-61ca0600-d37b-11eb-9884-d98d908e603a.png)

mpsc xadd array q:  282 samples with 100 Hz profiler -> ~28% CPU usage
![image](https://user-images.githubusercontent.com/13125299/122949056-a81f6500-d37b-11eb-9cc7-330710bed2f7.png)

Due to skidding, in both cases the contention seems not a thing, but probably `perfasm` can show that's not correct: I see that the CPU usage improvement is paired with a boost in throughput.
But in both cases `size` is taking too much time, probably because it both invalidate the producer sequence and consumer too: I believe that need to get rid of that bottleneck first to see both queues delivering the best they can do.

**Comment by anuraaga** [comment]
@franz1981 Is this something that can be improved in the jctools implementation itself? It's not intuitive to me why calling `size` could have any dramatic effect on performance

**Comment by franz1981** [comment]
@anuraaga Sadly not: it's something related to how caches works on machine; we just need to reduce the dependency from the size operation to make progresses...

**Comment by franz1981** [comment]
Feel free to review my branch and try it on a bigger server to see if you get the same or better improvement.

**Comment by sbandadd** [comment]
@franz1981 The benchmark I pasted earlier has flush overhead. Let's try [this one](https://github.com/open-telemetry/opentelemetry-java/blob/50408d499f85d5761d0a5ed9bf9d77d5ff01fff5/sdk/trace/src/jmh/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessorMultiThreadBenchmark.java), this benchmark is what I used earlier to surface contention issues before.

**Comment by franz1981** [comment]
@anuraaga
Thanks!
 I don't have a big machine to try it, but just a tuned i7 (without turbo boost, disabling frequency scaling etc etc) with 6 hw threads (12 with HT).
I am going to try it, but feel free to try it on a big server If you can or the producers contention won't be exercised for real

**Comment by franz1981** [comment]
@anuraaga i have given a shot to the mentioned benchmark but it doesn't seem to stress the queue contention, because the XADD queue is unbounded and the test doesn't start at steady state (as the previous one).
The consumer just won't keep up with the producers and the benchmark end up spending most of its time on the garbage collector instead...
I think that to make this to work I should implement some artificial limit to the queue growth first.

Just a semantic question: the queue used have to obey a total FIFO order or each producer must be consumed in FIFO ordering but they can see their items consumed in different orders?

**Comment by anuraaga** [comment]
Thanks for the investigation here @franz1981 happy to make changes if anything can speed things up even more. Order on the consumer side does not matter as long as all the items that have been produced are consumed.

**Comment by franz1981** [comment]
@anuraaga In this case on JCTools we have an unbeateable queue for this: https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpscCompoundQueue.java

It uses a mesh of bounded queue to spread the contention: it should be the right queue for the job, without re-implementing the logic to have an uneeded total ordering

**Comment by anuraaga** [comment]
@franz1981 IIRC, I tried the compound queue for that reason couldn't find any noticable difference in our benchmarks on my laptop, so went with the simpler non-compound one. My main concern with the compound queue was our friend the `size()` method would have less reliable performance, possibly scaling down with the number of CPUs. It could be needing a different benchmark though, but at least with our current ones I couldn't justify using the compound queue.

**Comment by franz1981** [comment]
@anuraaga 
>  I tried the compound queue for that reason but couldn't find any noticable difference in our benchmarks on my laptop, so went with the simpler non-compound one

And I'm seeing the same here: so it just means that the benchmark isn't stressing contention against the q (because the 2 qs behave very differently under contention, by design).
If contention is a thing ie it's a factor that you've found on realistic load to be important (using the right profiler tool) then I'm sure it worths to move on compound unless there are other bottlenecks in place.
I'm going to past a couple of flamegraphs to show what I mean about it

**Comment by franz1981** [comment]
I've used a separate soft/lazy counter on https://github.com/franz1981/opentelemetry-java/tree/xadd_batch_span and I'm getting:

![image](https://user-images.githubusercontent.com/13125299/123389145-ded2c680-d599-11eb-9acc-f8a87967a636.png)

Consider that I don't know yet if the logic is sound

**Comment by franz1981** [comment]
And for 20 threads (that doesn't makes sense on my poor 12 cores laptop):
![image](https://user-images.githubusercontent.com/13125299/123389980-ba2b1e80-d59a-11eb-9d2f-16013c0e291b.png)

**Comment by jack-berg** [comment]
Please re-open if you're interested in continuing pursuing this.
