### ISSUE TITLE
Add factories for SamplingResult

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3354]
We can currently only implement a Sampler by calling `SamplingResult.create`. For results without attributes, we do return singletons from this method so it doesn't have any real overhead. But it's somewhat annoying to have to call `create` with a parameter and not so intuitive - every time I do it I still ctrl-click through the method to confirm it's not creating a new object. The alternative of creating a `private static final` in the Sampler seems redundant vs us providing some factories

`SamplingResult.recordAndSample()`
`SamplingResult.recordOnly()`
`SamplingResult.drop()`

**Comment by Rocksnake** [comment]
My understanding of your point of view is to divide the `oncreate` method into three to obtain the corresponding instance separately, and ensure that there is only one instance globally. To call `oncreate`with a parameter is implemented through these three split methods.

Is my understanding correct? If it is, I am very glad to do it. Could you can assign it to me. If not, can you give me some guidance.

**Comment by anuraaga** [comment]
For backwards compatibility we can't remove the current `create` so would just add these new methods. We already have the singletons as returned by `create` so just have to return those from the factories.

Let's wait to hear what other maintainers think before making any change if we decide to go with it the help is appreciated :)

**Comment by jkwatson** [comment]
This seems ok to me. Making it clear that we're not creating a new object with these calls is a good idea.

**Comment by anuraaga** [comment]
Cool - @Rocksnake if you'd like to help that'd be great

**Comment by Rocksnake** [comment]
I tried the following according to my understanding, and obtained them separately for different factories：
`SamplingResult.java`
<img width="819" alt="截屏2021-07-01 11 03 26" src="https://user-images.githubusercontent.com/44219737/124058621-932b7d00-d9de-11eb-9a67-f55d248e4032.png">
`ImmutableSamplingResult.java`
<img width="766" alt="截屏2021-07-01 11 03 59" src="https://user-images.githubusercontent.com/44219737/124058643-9fafd580-d9de-11eb-9283-ade0d3f7de0c.png">
and I wrote the unit test in SamplingResultTest without errors.
![image](https://user-images.githubusercontent.com/44219737/124059006-3f6d6380-d9df-11eb-861a-66e60d6e59cb.png)

Can you help me check if my understanding is correct? If it is correct, I will optimize the method of obtaining factories in the whole project.

**Comment by anuraaga** [comment]
@Rocksnake Basically looks good but I don't think we need the versions with `Attributes`, it's less common and `create` works well for it (it does actually create a new object).
