### ISSUE TITLE
Add Clock.getDefault returning SystemClock and move TestClock to sdk-testing as public

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3359]
We can expect some external SDK extensions, perhaps a rate limiting sampler, to require a `Clock`. We define this interface but there doesn't seem to be a practical way for extensions outside this repo to use that interface because the implementations of it, `SystemClock` and `TestClock` are not exposed. While there does seem to be difficulty in "injecting" the Clock that is actually used in the SDK into an extension, at least a user should be able to do it, e.g.

```java
OpenTelemetrySdk.builder()
  .setSampler(CustomRateLimitingSampler.create()) // Implemented by delegating to constructor with the default Clock
  .build()
```

```java
OpenTelemetrySdk.builder()
  .setClock(CustomClock.getInstance())
  .setSampler(CustomRateLimitingSampler.create(CustomClock.getInstance())
  .build()
```

And it would also be our duty to help test this code by publishing TestClock in the testing package

**Comment by jkwatson** [comment]
Yes. I needed this recently and grabbed the internal SystemClock, but it would be great if I could just get one legitimately for doing some timing.
