### ISSUE TITLE
How does activate/deactivate relate to context propagation?

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-java#34]
It is not clear how activate/deactivate relates to the underlying context propagation mechanism, given that they are separate.

**Comment by tedsuo** [comment]
@yurishkuro are you clear on this now, or do you have more questions?

**Comment by yurishkuro** [comment]
We need to spike tags/baggage->context package, then we will see.

The idea is that the context will be immutable, so in order to add baggage, or in-process object, or a new active span, a new Scope needs to be created. So span activate/deactivate actually becomes scope push/pop.

**Comment by tedsuo** [comment]
## Current State
* We currently rely on gRPC context propagation
* We don't want a dependency on gRPC project are it weirds people out
* But we would like to share context propagation with them, and any other project which would like to use context propagation.
* So we would like to move context propagation to a neutral spot: an independent repo/project which every project can depend on.
* For now, we will continue to depend on gRPC, and create a roadmap for massaging out this dependency chain for both projects.

## TODO
* Ensure that the OpenTracing bridge can work with the current context propagation implementation.

**Comment by carlosalberto** [comment]
So the OT bridge does work with the gRPC context package (https://github.com/bogdandrutu/openconsensus/blob/otshim_grpc_context/opentracing-shim/src/main/java/openconsensus/opentracingshim/ScopeManagerShim.java).

@yurishkuro I'm wondering if what you were worried was about consecutive calls to propagate tags/Spans - if that's the case, as `io.grpc.Context` inherits the values from the previously active one, we should be fine:

```java
// Pseudo code, mind you.
try (Scope scope = propagateSpan(span)) {
  // span is set as active.
  try (Scope scope2 = propagateTagMap(tagMap)) {
    // tagMap is set as active
    // span is still set as active.
    try (Scope scope3 = propagateSpan(anotherSpan)) {
      // tagMap is still active
      // anotherSpan is set as active.
    }
  }
}
```

(So even **if** we don't go with `Context`, we could require the propagation layer to have this behavior).

**Comment by yurishkuro** [comment]
lgtm

**Comment by carlosalberto** [comment]
Since this seems to be solved, shall we close this Issue? (the aforementioned branch doesn't *have* to be merged right away though IHMO).

(I know @bogdandrutu still is doing some prototyping around OC, but that could be tracked in another PR/Issue)

**Comment by yurishkuro** [comment]
I was looking at this today and I am not seeing the implementation of Context or Scope, am I missing something?

I like the nested contexts in https://github.com/bogdandrutu/openconsensus/issues/34#issuecomment-486213446, but I am curious if we think Scope is the necessary thing (since it causes allocations, although can probably be pooled). E.g. grpc context uses attach/detach and gets away without the Scope objects.

**Comment by carlosalberto** [comment]
Hey @yurishkuro 

Yes, there's no actual `openconsensus.context.Scope` implementation - this was mostly done to make sure this would work fine for the OT Shim (it was suspected it would, but we needed an actual test ;) ). 

The thing about `attach`/`detach` is how you need to keep around **both** the previous and current active `Context` objects, which can be simplified/abstracted by using `Scope`. Else:

```java
Context context = ...; // Create the new context
Context prevContext = context.attach();
try {
  // Do stuff.
} finally {
  context.detach(prevContext);
}
```

**Comment by carlosalberto** [comment]
(And yeah, we shouldn't close this Issue yet - the OT shim part was prototyped out, but the rest of the bits need to be resolved ;) )

**Comment by bogdandrutu** [comment]
@carlosalberto what is the status of this issue?

**Comment by carlosalberto** [comment]
I think this code was not meant to be merged, but to validate that the `grpc.Context` code could work fine with tags/baggage and the rest of the API, which I think was proved. 

Fine if we close this Issue, @yurishkuro ?
