### ISSUE TITLE
Proposal: Not use test prefix

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#340]
Prefixing all test methods with "test" is legacy and I prefer to not use that anymore, any thoughts about that?

**Comment by pavolloffay** [comment]
Sounds fine to me. But it is just a test method and for newcomers, it might be overwhelming to rename all test methods just to keep the convention.

**Comment by bogdandrutu** [comment]
Let's try to keep this rule for the new tests. We may fix the already submitted once later if we feel like.

**Comment by carlosalberto** [comment]
Agreed on both points. We can 'fix' the submitted tests although that shouldn't be a priority.

**Comment by bogdandrutu** [comment]
So we have agreement here. I will try to comment on PRs about this.
