### ISSUE TITLE
Sampler that passes spans based on name prefix

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java#3401]
Users have asked for a way to ensure that their manually created spans are never sampled out while still allowing the rest of instrumentation to sample normally. One approach I'm suggesting here is to create a new sampler that can be preconfigured with a set of span name prefixes to always include. That is, if a span name starts with one of the prefixes, it always passes. If it does not, then this sampler will delegate to another sampler.

Might be a little tricky to choose a name for this. Something like `NamePrefixedForceInclusionSampler`.

**Comment by jkwatson** [comment]
I recommend moving this request to the opentelemetry-java-contrib repository.

**Comment by breedx-splk** [comment]
Ok, moving request to contrib: https://github.com/open-telemetry/opentelemetry-java-contrib/issues/54
