### ISSUE TITLE
Add OTLP gRPC Log Exporter

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3407]
**Is your feature request related to a problem? Please describe.**
Add an OTLP gRPC exporter for logs. 

**Describe the solution you'd like**
Some minimal way to export log protos via OTLP - the logging equivalent of [OtlpGrpcMetricExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/metrics/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporter.java) and [OtlpGrpcTraceExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java). 

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by jkwatson** [comment]
We also need a once-over on the current implementation of the datamodel. For instance, I would like to be very opinionated and say that the log `body` can only be a `String`, even though the OTLP datamodel supports `Any` for the body type.

**Comment by jack-berg** [comment]
So then I presume you are in favor of adding an alternative representation of log payloads besides the proto? A `LogData` class / interface akin to `SpanData`?

**Comment by jkwatson** [comment]
> So then I presume you are in favor of adding an alternative representation of log payloads besides the proto? A `LogData` class / interface akin to `SpanData`?

yes, definitely.

**Comment by yangtaoran** [comment]
Hello. Is the LogExporter interface defined?

**Comment by jkwatson** [comment]
> Hello. Is the LogExporter interface defined?

This is what there is right now, but I think we need to clean up the `LogRecord` before this will really be viable: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/LogExporter.java

**Comment by yangtaoran** [comment]
> > Hello. Is the LogExporter interface defined?
> 
> This is what there is right now, but I think we need to clean up the `LogRecord` before this will really be viable: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/logging/src/main/java/io/opentelemetry/sdk/logging/export/LogExporter.java

here my understanding is to abstract LogRecord into interface akin to SpanData, and enforce the log body from AnyValue to string?

**Comment by jkwatson** [comment]
I'm not completely sure we need it to be an interface. It probably wouldn't hurt though. Good idea. 

Yes, the body should be a string.

**Comment by jack-berg** [comment]
Has anyone volunteered to work on this yet?

**Comment by jkwatson** [comment]
some draft bits here:  https://github.com/open-telemetry/opentelemetry-java/pull/3415

**Comment by jack-berg** [comment]
This was done and merged [here](https://github.com/open-telemetry/opentelemetry-java/pull/3670). Also added a otlp http/protobuf log exporter [here](https://github.com/open-telemetry/opentelemetry-java/pull/3682).
