### ISSUE TITLE
Prometheus Exporter can not be used

### ISSUE THREAD

**Issue by DaGeRe** [open-telemetry/opentelemetry-java#3408]
**Describe the bug**
According to https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#prometheus-exporter, spans could be exported to prometheus using `-Dotel.traces.exporter=prometheus` as command line parameter. Whenever I try this, I get the following exception:

> Caused by: io.opentelemetry.sdk.autoconfigure.ConfigurationException: Unrecognized value for otel.traces.exporter: prometheus
> 	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:59)
> 	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:51)
> 	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:47)
> 	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:39)
> 	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeAgent(OpenTelemetryInstaller.java:26)
> 	at io.opentelemetry.javaagent.tooling.AgentInstaller.runBeforeAgentListeners(AgentInstaller.java:171)
> 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:114)
> 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:97)

According to the code, Prometheus is missing: https://github.com/open-telemetry/opentelemetry-java/blob/6d9e5801c73a1d558a97f56bb23cc5c41c5537cc/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java#L41 I do not know: Is Prometheus supported and there is an error in the code, or was Prometheus removed and should the documentation be removed?

**Steps to reproduce**
Start any application with `opentelemetry-javaagent-all.jar -Dotel.traces.exporter=prometheus`

**What did you expect to see?**
Spans beeing visible in Prometheus.

**What did you see instead?**
The exception above.

**What version and what artifacts are you using?**
Artifacts: opentelemetry-javaagent-all 
Version: 1.3.1
How did you reference these artifacts? `https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent-all.jar` and then call with `-javaagent` 

**Environment**
Compiler: OpenJDK 11.0.11+9-Ubuntu-0ubuntu2.20.04
OS: Ubuntu 20.04

**Comment by jkwatson** [comment]
It's a metrics exporter, not a traces exporter. 

Use 
```
otel.metrics.exporter=prometheus
```

**Comment by jkwatson** [comment]
closing this, as this should work fine if you use the right property. Please re-open if that doesn't work.
