### ISSUE TITLE
Support OTLP signal specific certificate configuration

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3428]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently, you can only specify `OTEL_EXPORTER_OTLP_CERTIFICATE `. It sets the certificates OTLP/gRPC traces, and doesn't do anything for OTLP/gRPC metrics. 

`OTEL_EXPORTER_OTLP_CERTIFICATE` should set certificates for metrics, and  `OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE` and `OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE`  should be supported as defined by the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.5.0/specification/protocol/exporter.md).

**Describe alternatives you've considered**
N/A

**Additional context**
Discussed that this would be addressed in future [here](https://github.com/open-telemetry/opentelemetry-java/pull/2569#discussion_r563455694).

**Comment by jkwatson** [comment]
@jack-berg are you interested in implementing this? Can I assign it to you?

**Comment by jack-berg** [comment]
@jkwatson yup I can implement it. I have it mostly done but was waiting on this [PR](https://github.com/open-telemetry/opentelemetry-java/pull/3425/files) to get merged so I can incorporate the TLS support for for OkHttp when I generally add TLS support for `OtlpGrpcMetricExporter`.
