### ISSUE TITLE
Support OTLP signal specific timeout / headers configuration

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3430]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently, you can only specify `OTEL_EXPORTER_OTLP_TIMEOUT` and `OTEL_EXPORTER_OTLP_HEADERS`.

Per the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.5.0/specification/protocol/exporter.md):
- `OTEL_EXPORTER_OTLP_TRACES_TIMEOUT` and `OTEL_EXPORTER_OTLP_METRICS_TIMEOUT` support should be added.
- `OTEL_EXPORTER_OTLP_TRACES_HEADERS` and `OTEL_EXPORTER_OTLP_METRICS_HEADERS` support should be added.

**Describe alternatives you've considered**
N/A

**Additional context**
Support already exists for signal specific configuration of the OTLP endpoint via `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` and `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT`.

I've also opened a separate ticket for adding [signal specific support for certificates](https://github.com/open-telemetry/opentelemetry-java/issues/3428). Adding support for the signal specific timeout and headers seems small enough for a single ticket.

**Comment by jack-berg** [comment]
Meant to label as a feature not a bug. 🤦

**Comment by jkwatson** [comment]
@jack-berg are you interested in working on this? If so, I'll assign it to you.

**Comment by jkwatson** [comment]
> @jack-berg are you interested in working on this? If so, I'll assign it to you.

ok, I see you put in a PR for it, so I'll assign it. :)
