### ISSUE TITLE
Autoformat/enforce formatting of build scripts (kts)

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3435]
https://github.com/open-telemetry/opentelemetry-java/pull/3427 showed that the build scripts were not consistently formatted. To avoid such large (or any!) formatting-only PRs in the future, we should have something like spotless+googleJavaFormat for the kts files.

**Comment by Rocksnake** [comment]
One solution: I think the format check could perform pre-commit through the git hook. If the newly submitted code does not conform to the format, adjust the format first and then commit.

Although above solution is ok, I propose to format the code as a separate task and use a machine to execute it continuously.
