### ISSUE TITLE
SDK: Javadoc since tags

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#344]
Related to https://github.com/open-telemetry/opentelemetry-java/pull/342#discussion_r286982773

In the API all public APIs are documented with `@since` javadocs. 

Should we do the same in SDK? For the interfaces it does not makes much sense as the since tag is in the API and SDK will have the same version.

**Comment by yurishkuro** [comment]
We should, but maybe  we should defer that until we have a stable API?

**Comment by JasonXZLiu** [comment]
Hi! Is this issue free to pick up? I would love to work on it for a good first issue!

**Comment by jkwatson** [comment]
@JasonXZLiu Sure thing. I'll assign it to you.

**Comment by SaberSeddik** [comment]
Was checking for good first issue, found this. But seems a fix already merged. should this be closed ?

**Comment by jkwatson** [comment]
I think we'll want all of the `@since` tags to be set to 1.0.0, but not until we're ready for a release candidate (which is hopefully coming soon!). So, I think this should be open until then.

**Comment by anuraaga** [comment]
We discussed adding `@since` tags for post-1.0 versions.

**Comment by jkwatson** [comment]
I think we can close this. We'll add `@since` tags on new APIs/methods that we add, and if it becomes important, we can retro-fit the `@since` tags on existing APIs.
