### ISSUE TITLE
Support comma-separated list of exporters for otel.traces.exporter

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#3443]
This has been added to the spec and would be a nice-to-have addition to the auto-configuration module.

**Comment by iNikem** [comment]
Hm... spec says nothing about if all those exporters should use the same span processor or not

**Comment by jkwatson** [comment]
> Hm... spec says nothing about if all those exporters should use the same span processor or not

Yes, I know. I brought this up in the spec PR that added this, but it was decided it would be up to the individual SIGs to decide how to do that. General recommendation was to have each hooked up with their own `BatchSpanProcessor`, I believe.

**Comment by anuraaga** [comment]
> General recommendation was to have each hooked up with their own BatchSpanProcessor, I believe.

I can't think of any benefit of this. I think we should hook up to the same BSP, just by using a composite span exporter.

**Comment by jkwatson** [comment]
> > General recommendation was to have each hooked up with their own BatchSpanProcessor, I believe.
> 
> I can't think of any benefit of this. I think we should hook up to the same BSP, just by using a composite span exporter.

Also fine, and I agree.

**Comment by jack-berg** [comment]
@jkwatson can you assign this issue to me?

**Comment by jack-berg** [comment]
@jkwatson this issue can be closed. Looks like the comment I left on the PR #3529 didn't meet the criteria to close.
