### ISSUE TITLE
Consider moving the OT shim to Instrumentation

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#3451]
My impression is that most users of OT use it in manual fashion, i.e. no automatic instrumentation. But we should do a double check in case there's value in putting the OT Shim right in the Instrumentation repo.

**Comment by jkwatson** [comment]
Can I assign this to you, @carlosalberto ?

**Comment by jack-berg** [comment]
In #4753 we discussed scope of the various repositories and determined that this repo is the correct place for shims defined in the specification like open tracing.
