### ISSUE TITLE
SDK: Decide which default sampler to use.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-java#347]
When a `Span` is built, if no `sampler` is provided, SDK should provide a default sampler.
https://github.com/open-telemetry/opentelemetry-java/blob/c8f0f7cf9c32a3d172439ab713eb0f84b7135e87/api/src/main/java/io/opentelemetry/trace/Span.java#L361

Currently we have a few options:
1. Probability sampler of 1/10000, which is [the default in OpenCensus](https://github.com/census-instrumentation/opencensus-java/blob/02ade038e4c11dece33ad41cfd10dad0953a4f35/api/src/main/java/io/opencensus/trace/config/TraceParams.java#L38).
2. 100% sampler, proposed by @yurishkuro in https://github.com/open-telemetry/opentelemetry-java/pull/337#issuecomment-495045955.
3. Two modes, production and test, and make `test` as the default mode.

See full discussion in https://github.com/open-telemetry/opentelemetry-java/pull/337.

**Comment by carlosalberto** [comment]
At leas initially, I'm heading towards 100% Sampler.

That being said, for the two (or more) modes, what other options/configuration would be included, besides the sampler?

**Comment by tedsuo** [comment]
I would strongly be in favor of 100% as the default.

**Comment by tedsuo** [comment]
## Video Discussion 5/29
* Default will 100% sampling. 
* We want to add backpressure: Should have an algorithm for dropping spans in an explicit manner. @SergeyKanzhelev will make a spec proposal for this.
* `remote-sampler` can be added into the spec, and implemented as `up-for-grabs` (not on critical path).

**Comment by tedsuo** [comment]
Additionally: Add a section to README to warn user about default sampling, and explain how to configure sampling.

**Comment by songy23** [comment]
This is already done as part of https://github.com/open-telemetry/opentelemetry-java/pull/336/files#diff-9cb90b7f1ecf8f5be35e2e769b18936bR35.
