### ISSUE TITLE
Add exporter using OTLP via HTTP, using OpenTelemetry's JSON model

### ISSUE THREAD

**Issue by clarck** [open-telemetry/opentelemetry-java#3486]
**Is your feature request related to a problem? Please describe.**
Including both protobuf-java and protobuf-javalite causes duplicate class errors on build. The simplest reproduction is to just include both as dependencies:
```
implementation "com.google.protobuf:protobuf-javalite:3.11.0"
implementation "com.google.protobuf:protobuf-java:3.11.4"
```

This will generate these errors on build:
```
Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.11.0 (com.google.protobuf:protobuf-javalite:3.11.0)
Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules jetified-protobuf-java-3.11.4 (com.google.protobuf:protobuf-java:3.11.4) and jetified-protobuf-javalite-3.11.0 (com.google.protobuf:protobuf-javalite:3.11.0)
...
```

Since we publish opentelemetry-java library that has a dependency on protobuf-java, this means that our library will always conflict with any library that uses protobuf-javalite.

**Describe the solution you'd like**
We can uses protobuf-javalite both with opentelemetry-java library,  like this:
```
implementation "com.google.protobuf:protobuf-javalite:3.11.0"
implementation('io.opentelemetry:opentelemetry-exporter-otlp') {
 exclude group: 'com.google.protobuf', module: "protobuf-java"
}
```

**Describe alternatives you've considered**
Add exporter using OTLP via HTTP, using OpenTelemetry's JSON model. So we can using JSON exporter resolved duplicate class errors on build.

**Additional context**
Can we add a exporter for this as well?

**Comment by anuraaga** [comment]
Hi @clarck - we're not planning on supporting json exporters since the use case seems small for them. Is the issue that we only publish opentelemetry-proto targeting the full runtime? I would rather publish an additional version that targets proto lite rather than adding json exporters if it works.

**Comment by anuraaga** [comment]
Another option is to shade in protobuf for the http exporter. It should solve dependency issues - though I guess doesn't help with the reason people use lite runtime in the first place, binary size :P @jkwatson Either seem better?

**Comment by clarck** [comment]
> Hi @clarck - we're not planning on supporting json exporters since the use case seems small for them. Is the issue that we only publish opentelemetry-proto targeting the full runtime? I would rather publish an additional version that targets proto lite rather than adding json exporters if it works.

@anuraaga - We tried to use the opentelemetry-java library on Android, but protobuf-javalite is more recommended than protobuf-java on Android. Secondly, we can reduce more binary package size by using json exporter, which is very important for us.

**Comment by clarck** [comment]
> Hi @clarck - we're not planning on supporting json exporters since the use case seems small for them. Is the issue that we only publish opentelemetry-proto targeting the full runtime? I would rather publish an additional version that targets proto lite rather than adding json exporters if it works.

@anuraaga - json exporter is also a way in the standard specification, I think it also needs to be supported

**Comment by anuraaga** [comment]
@clarck Yes I think we can provide support for protolite here. The runtime is about 600K vs 1.6MB of protubuf-java, and jackson-core (which we would use if we did add a json exporter) is about 300K. I don't think we can get too into the detail of the binary size since it's unclear what proguard will do, but would protolite be ok?

**Comment by clarck** [comment]
Thank you very much for your reply. In my experience, any library over 300k on Android needs to be treated with caution, as this will affect the size of the installation package. If necessary, I don’t even want to introduce the opentelemetry-proto library. You can take a look at this PR I submitted[#3489](https://github.com/open-telemetry/opentelemetry-java/pull/3489)

**Comment by anuraaga** [comment]
We have similar hand-coded serialization logic for proto that is incubating

https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/TraceMarshaler.java

It has some better performance than the using protobuf, and with a bit more rework could remove the dependency on `opentelemetry-proto` altogether. It has the same issue that hand-written JSON serialization logic would have, in that we want to find a good way to verify the output is the same as generated proto all the time. But finishing this to improve performance for all users while also reducing the binary size with the protobuf encoding will be more interesting than adding a JSON marshaller, at least for the time being.

I'll take a look at TraceMashaler over the next few days to see if we can go ahead and finish it up, I think it's pretty close. I suspect it will be more worthwhile solving binary size issues for proto rather than expecting any binary-size constrained users to use JSON.

**Comment by clarck** [comment]
I have noticed you TraceMarshaler before, it sounds good. But if the exporter using OTLP via Http, neither the protobuf model nor the json model is used. So in what way should the collector server handle this data, I am confused?

**Comment by anuraaga** [comment]
The binary data will still use the protobuf format - it just won't use the generated protobuf code since we have TraceMarshaller that encodes into that format directly from SpanData. As long as the binary is the same format it doesn't need to actually use the proto :)

**Comment by jkwatson** [comment]
I do think there is probably a use-case for an http-json exporter for otlp (especially on Android). If we do create it, it should absolutely be a separate module with bare minimum dependencies. This would also be a great thing to put into opentelemetry-java-contrib if we don't want to support it here directly. @clarck would you be willing to re-work your PR to have it be a separate module and that doesn't depend on alibaba libraries?

If we move to the hand-coded serialization of otlp proto format, we definitely need a way to verify the output is valid and unchanging, which will be tricky, for sure. It would be cool if the collector had a tck we could run against!

**Comment by anuraaga** [comment]
I would hold off on the JSON for now I think. The problem at hand seems to be the binary size - JSON exporter seems like a very obtuse workaround for this as we can instead improve the binary size of the protobuf format exporter, which can avoid the protobuf compiler and library completely if we want. I guess I feel weird merging in hand-written JSON serializers even though we didn't actually switch to the ones we wrote for protobuf yet ;) Doing so should solve the binary size problem - so we would probably still want to wait on a json exporter until more demand, i.e. rule of three.

**Comment by clarck** [comment]
> I do think there is probably a use-case for an http-json exporter for otlp (especially on Android). If we do create it, it should absolutely be a separate module with bare minimum dependencies. This would also be a great thing to put into opentelemetry-java-contrib if we don't want to support it here directly. @clarck would you be willing to re-work your PR to have it be a separate module and that doesn't depend on alibaba libraries?
> 
> If we move to the hand-coded serialization of otlp proto format, we definitely need a way to verify the output is valid and unchanging, which will be tricky, for sure. It would be cool if the collector had a tck we could run against!

@jkwatson - Yes, my idea is the same as you. This PR can be separated into a module to implement it with minimal dependencies, and jackson-core can be used to replace alibaba libraries

**Comment by anuraaga** [comment]
@clarck #3533 finishes the work to remove the dependency on generated protos and the protobuf-java (or javalite) libraries from the HTTP exporter. This is our recommended exporter for environments where binary size is constrained - it should have both better performance and smaller binary size than either the previous protobuf implementation or a future JSON implementation where we would still need a dependency on a low level library like Jackson (unicode encoding in JSON is too tricky to avoid a library dependency...). I hope this works for your use case!
