### ISSUE TITLE
Consider removing DoubleCounterBuilder.ofLongs

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3494]
We start with LongCounterBuilder and can switch it to double (for exceptional cases) with `ofDoubles`, I don't think we really need to be able to go back.

https://github.com/open-telemetry/opentelemetry-java/blob/7a89a197003df3be2dca9796f7d95f49a6a8fab2/api/metrics/src/main/java/io/opentelemetry/api/metrics/DoubleCounterBuilder.java#L29

**Comment by jkwatson** [comment]
I agree, unless there's some esoteric use-case that I'm missing here.

**Comment by breedx-splk** [comment]
`ofLongs()` also exists in the `DoubleGaugeBuilder` and `DoubleHistorgramBuilder` and the `DoubleUpDownCounterBuilder`. Do we think we would want to remove all 4 of these for consistency?

**Comment by jsuereth** [comment]
consensus here is to remove the "backwards" `ofLongs`/`ofDoubles`, so if a builder defaults to Double, there will be an `ofLongs` on that builder, but not a corresponding `ofDoubles` on its paired builder.
