### ISSUE TITLE
LongCounter and LongUpDownCounter have exact same API - delete one?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3496]
I noticed LongCounter and LongUpDownCounter have the exact same API. Is it better to have something like `disallowNegative` on a single type?

**Comment by jkwatson** [comment]
Heh. In the first iteration of the metrics API, this is the way it was done. In the intervening year or so, the metrics spec group has preferred to have separate instruments for these use-cases, rather than having options on them. IIRC, the idea here is that the semantics will be more clear at the call site if you have differently named instruments, even if the API usages look the same.

**Comment by anuraaga** [comment]
Ah the boolean was isMonotonic I'm presuming. I still have trouble grokking it and wonder if it's not supposed to be an SDK concern, in the view, instead of API. I guess we can't throw an exception for negative measurements to a monotonic counter in the API either way? Anyways just wanted to confirm it two APIs with the same API feels like a smell.

**Comment by jkwatson** [comment]
It's curious. In the spec, there's clearly a section for creating an UpDownCounter, but no description of what one is, any more:  https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#updowncounter-creation. @jsuereth do you know what's up here?

**Comment by jsuereth** [comment]
I think it's too late to change this.  There is a different semantic/context between them.  Sorry for not responding here earlier, think we had this discussion offline.

UpDownCounter supports increments + decrements: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#updowncounter, we only have one "add" method in Java though.

I think the framing here should be do we add a "subtract" method?

**Comment by anuraaga** [comment]
The idea was that it could be possible to handle monotonicness in the SDK instead of the API. It's a significant spec change though and agree it's too late to try now so we can stick with what we have.
