### ISSUE TITLE
API: Should SpanBuilder.setNoParent() clear any explicit parent?

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#353]
I'm wondering if, upon calling `SpanBuilder.setNoParent()`, any explicit parent registered through `SpanBuilder.setParent()` should be cleared. Im inclined to a YES.

But would like to hear any opinion on this one @yurishkuro @bogdandrutu 

(In OT things worked differently, as the related method was `ignoreActiveSpan()`, which mentioned nothing about any explicit parent interaction ;) )

**Comment by bogdandrutu** [comment]
I would say yes. If `setNoParent()` is called after any `setParent()` we should clear all previous calls, same for `setParent()` being called twice, the last call overwrites previous calls.

**Comment by tedsuo** [comment]
## 5/30 Discussion
* Agreed this should remove previous call to setParent().

**Comment by bogdandrutu** [comment]
@carlosalberto Please clarify this in the documentation.

**Comment by bogdandrutu** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-java/pull/364
