### ISSUE TITLE
Add MetricDescriptor to SDK for exporting

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3534]
While writing custom marshaling code for metrics, I realized it would be good to have a class to encapsulate "effectively singleton" information, the name / description / unit. We would be able to cache the marshaled representation of this descriptor more directly than caching each individual part.

**Comment by jsuereth** [comment]
There is a MetricDescriptor class, what more do you want to see on it?  I'm happy to update it.

**Comment by anuraaga** [comment]
MetricsDescriptor looks to be an internal class for view configuration I believe. Shall we promote it to a public class? I'm just looking at the export pipeline for this, MetricData just has three fields for the name / description / unit, not a class.

**Comment by anuraaga** [comment]
A bit more color is I found that unlike tracing, where instrumentation library is the end of the "singleton graph" it seems like metric have one more branch, the name / description / unit. So we should probably be memoizing them the same way we memoize instrumentation library.

**Comment by jsuereth** [comment]
The more I think about this, the more it seems like an optimisation for OTLP export.  Can we update this bug appropraitely with a short design and put "help wanted"?

Recent PR moves MetricDescriptor more into diagnostics territory so it'll have more information than you want.

**Comment by jack-berg** [comment]
@anuraaga do you think we need to do anything for this issue before stabilizing the metric SDK artifact?

**Comment by jack-berg** [comment]
We spoke in the 4/7 Java Office Hours SIG and decided this isn't necessary.
