### ISSUE TITLE
[Doc] Manual Instrumentation - Java Missing dependencies

### ISSUE THREAD

**Issue by violette** [open-telemetry/opentelemetry-java#3536]
In the doc page https://opentelemetry.io/docs/java/manual_instrumentation/, it would be nice if a layer could be added, using the latests dependencies, bom and inner project dependencies(api, sdk, and opentelemetry-exporters-otlp)  to use the provided code.

It would be nice if the sample could provide the gradle/maven, etc. dependencies as a block to copy/paste int the https://opentelemetry.io/docs/java/manual_instrumentation/#set-up part.

**Comment by jkwatson** [comment]
@violette Great idea. The website docs are sourced from this repository. Are you interested in updating the docs with these features?

**Comment by sharmavishalvk** [comment]
I will work on it and submit PR later.

**Comment by rahuldimri** [comment]
@jkwatson @violette Do we need to still update the document? If yes I can work on this ?

**Comment by jkwatson** [comment]
> @jkwatson @violette Do we need to still update the document? If yes I can work on this ?

The docs are no longer hosted here, but in the website repo. I'm sure the maintainers there would appreciate doc cleanups!

**Comment by MartinGallauner** [comment]
Hi, should this issue be closed?

**Comment by violette** [comment]
I think it is ok to close it. Thank you.
