### ISSUE TITLE
Exponential Histogram Prototype

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-java#3550]
This bug tracks work/progress around generating exponential histograms in the Java SDK.

- [x] Add exponential histogram to `sdk.metrics.data` package
- [ ] Add exponential histogram to OTLP exporters
- [ ] Create an exponential histogram Aggregator

**Comment by jamesmoessis** [comment]
@jsuereth I'm going to implement this now that the OTEP seems in it's final form. Would these three items be three separate PRs or one big one?

**Comment by jkwatson** [comment]
> @jsuereth I'm going to implement this now that the OTEP seems in it's final form. Would these three items be three separate PRs or one big one?

Please favor smaller, focussed PRs if at all possible. Thanks!

**Comment by jamesmoessis** [comment]
PR for OTLP marshalers: https://github.com/open-telemetry/opentelemetry-java/pull/3995

Once the above PR gets merged, I think it's safe to close this issue.

**Comment by jamesmoessis** [comment]
@jsuereth We have the data model, aggregator, and OTLP exporters all merged now - so we can close this one 🎉
