### ISSUE TITLE
[Metrics] An Aggregation Temporality of delta，isMonotonic always true

### ISSUE THREAD

**Issue by clarck** [open-telemetry/opentelemetry-java#3594]
**Describe the bug**
Use AggregationTemporality.DELTA mode create MetricData，isMonotonic always is true

**Steps to reproduce**
```java
SdkMeterProvider meterProvider = SdkMeterProvider.builder()
                .registerView(InstrumentSelector.builder()
                                .setInstrumentType(InstrumentType.COUNTER)
                                .build(),
                                View.builder()
                                .setLabelsProcessorFactory(LabelsProcessorFactory.noop())
                                .setAggregatorFactory(AggregatorFactory.count(AggregationTemporality.DELTA))
                                .build())
                .build();
        GlobalMeterProvider.set(meterProvider);
```

Export data results:
```
...
 "metrics":[
                        {
                            "description":"Processed jobs",
                            "sum":{
                                "aggregation_temporality":"AGGREGATION_TEMPORALITY_DELTA",
                                "data_points":[
                                    {
                                        "exemplars":[

                                        ],
                                        "labels":[
                                            {
                                                "key":"request.cmd",
                                                "value":"cmd"
                                            }
                                        ],
                                        "start_time_unix_nano":1631194617077000000,
                                        "time_unix_nano":1631194627089000000,
                                        "value":2
                                    },
                                    {
                                        "exemplars":[

                                        ],
                                        "labels":[
                                            {
                                                "key":"request.cmd.cost",
                                                "value":"cost_time"
                                            }
                                        ],
                                        "start_time_unix_nano":1631194617077000000,
                                        "time_unix_nano":1631194627089000000,
                                        "value":2
                                    }
                                ],
                                "is_monotonic":true
                            },
                            "name":"processed_jobs2",
                            "unit":"1"
                        }
                    ]
...
```

**What did you expect to see?**
Use AggregationTemporality.CUMULATIVE mode create MetricData，isMonotonic is true; AggregationTemporality.DELTA mode create MetricData，isMonotonic is false.

**Comment by jack-berg** [comment]
I believe the behavior you've outlined is correct.

The [metrics data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#sums) says the following about the monotonic flag on sum data points:
> For delta monotonic sums, this means the reader SHOULD expect non-negative values.
For cumulative monotonic sums, this means the reader SHOULD expect values that are not less than the previous value.

Since this is a counter instrument, negative values aren't possible, so the monotonic designation is correct. If your instrument was an up down counter, negative values would be possible, so the monotonic flag would be false.

**Comment by jkwatson** [comment]
@jack-berg is correct. The monotonicity is describing the instrument and the values that are being recorded, not the values being emitted post-aggregation. This is not a bug, but the intended behavior. A Counter cannot record negative increments, hence the results are always monotonically increasing.

**Comment by clarck** [comment]
> Since this is a counter instrument, negative values aren't possible, so the monotonic designation is correct. If your instrument was an up down counter, negative values would be possible, so the monotonic flag would be false.

@jack-berg Yes, you are right. I understand it as a description of increment and accumulation. After all, the cumulative reported value is more and more, and the incremental report is not necessarily
