### ISSUE TITLE
Create child span in grpc failed

### ISSUE THREAD

**Issue by yuxiaoba** [open-telemetry/opentelemetry-java#3610]
**Describe the bug**
When I  instrumented opentelemetry code in my code, I found that it cannot create child span right. 
How can I instrument the code to achieve that *AdService/GetAds* is the child span of *AdService/QueryAds*?

**Steps to reproduce**
```
  private static class AdServiceImpl extends hipstershop.AdServiceGrpc.AdServiceImplBase {
    public void getAds(AdRequest req, StreamObserver<AdResponse> responseObserver) {
      AdService service = AdService.getInstance();
      Span span = tracer.spanBuilder("hipstershop.AdService/GetAds").startSpan();
      SpanContext spancontext = span.getSpanContext();
      ...
      } catch (StatusRuntimeException e) {
        responseObserver.onError(e);
      }finally {
        span.end();
      }
    }
  }
  private class OpenTelemetryServerInterceptor implements io.grpc.ServerInterceptor {
    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
        ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
      // Extract the Span Context from the metadata of the gRPC request
      Context extractedContext = textFormat.extract(Context.current(), headers, getter);
      InetSocketAddress clientInfo =
          (InetSocketAddress) call.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR);
      // Build a span based on the received context
      Span span =
          tracer
              .spanBuilder("hipstershop.AdService/QueryAds")
              .setParent(extractedContext)
              .setSpanKind(SpanKind.SERVER)
              .startSpan();
      try (Scope innerScope = span.makeCurrent()) {
        ......
        // Process the gRPC call normally
        return Contexts.interceptCall(io.grpc.Context.current(), call, headers, next);
      } finally {
        span.end();
      }
    }
  }
```

**What did you expect to see?**
The spans can connect together with the same traceid.  
hipstershop.AdService/GetAds is the childspan of hipstershop.AdService/QueryAds.
```
hipstershop.AdService/QueryAds -->  hipstershop.AdService/GetAds
```

**What did you see instead?**
The spans cannot connect together with the two traceid.
The two spans are Independent
```
hipstershop.AdService/QueryAds
hipstershop.AdService/GetAds

```

**What version and what artifacts are you using?**
opentelemetry-java 1.5

**Environment**
Compiler:  JDK 8
OS: Ubuntu 18.04

**Comment by jkwatson** [comment]
There is grpc instrumentation in the opentelemetry-java-instrumentation project that should work: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/grpc-1.6/library If it doesn't work as desired, please log a bug in that project.

**Comment by jkwatson** [comment]
In your example code, I don't see anything injecting the span context into the grpc request headers. Without something doing that work, there will be no propagation.

And, what is the `textFormat` that is doing the extracting on the request side, in your code?

**Comment by yuxiaoba** [comment]
Thank you for your reply. 
Actually , I follow the example https://github.com/open-telemetry/opentelemetry-java/blob/main/examples/grpc/src/main/java/io/opentelemetry/example/grpc/HelloWorldServer.java in this project.

**Comment by jkwatson** [comment]
The example is working correctly for me. Why do you think it isn't?

**Comment by yuxiaoba** [comment]
> The example is working correctly for me. Is it working for you?

Thank you for your reply.

**Comment by trask** [comment]
hey @yuxiaoba, if you are looking for out-of-the-box non-javaagent grpc instrumentation, check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/grpc-1.6/library.

here's the maven artifact to use: https://search.maven.org/search?q=g:io.opentelemetry.instrumentation%20AND%20a:opentelemetry-grpc-1.6

and here's the main entry point for usage: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/grpc-1.6/library/src/main/java/io/opentelemetry/instrumentation/grpc/v1_6/GrpcTracing.java

**Comment by jkwatson** [comment]
> However, this example does not have the code about creating the child span in the grpc.
> Can you give me some suggestions about creating the chid span based on this example.

As you can hopefully see from @trask's link, instrumenting grpc is not easy to get correct. We should probably remove this example from our repository and rely on the expertise of the instrumentation folks to do it right. Or, perhaps our examples should use the library instrumentation rather than doing a half-way job of implementing it?

**Comment by yuxiaoba** [comment]
@jkwatson @trask Thank you for your reply. Now I have  instrumented my code with Java agent, it is fantastic.    
@jkwatson  May be we should remove the manually instrumentation of grpc in the examples.
