### ISSUE TITLE
gradlew does not exist

### ISSUE THREAD

**Issue by tnevolin** [open-telemetry/opentelemetry-java#3612]
https://github.com/open-telemetry/opentelemetry-java/blob/main/CONTRIBUTING.md#building-opentelemetry-java

The description above recommends to run `gradlew` immediately after cloning. This file does not exist in root project directory. The gradlew is a wrapper that should be created in the project with `gradle wrapper` command.

**Comment by anuraaga** [comment]
Hi @tnevolin - we have `gradlew` in the repo

https://github.com/open-telemetry/opentelemetry-java/blob/main/gradlew

Can you verify your clone is ok?

**Comment by tnevolin** [comment]
I see it now.
