### ISSUE TITLE
Proto to JSON conversion issue

### ISSUE THREAD

**Issue by dittakaviram** [open-telemetry/opentelemetry-java#3627]
**Describe the bug**

Below is a brief on our use case:

We are using the opentelemetry collector to read metric data from end user machines (macOS and Windows) and forwarding the same to open telemetry gateway where the metric data is forwarded to a kafka topic. Our Flink application reads the data from the topic and converts it to JSON using the below logic eventually saving the metric data into a database table as a json string from where further metric extraction happens.

Below is the piece of code we are using to deserialize protobuf:

```java
import com.google.protobuf.util.JsonFormat;
import io.opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest;
import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.streaming.connectors.kafka.KafkaDeserializationSchema;
import org.apache.kafka.clients.consumer.ConsumerRecord;

@SuppressWarnings("serial")
public class MyProtoSchema implements KafkaDeserializationSchema<KafkaRecord>
{
    @Override
    public KafkaRecord deserialize(ConsumerRecord<byte[], byte[]> record) throws Exception {
        ExportMetricsServiceRequest request = ExportMetricsServiceRequest.parseFrom(record.value());
        
        KafkaRecord data = new KafkaRecord();
        data.key =  record.key() == null ? "" : new String(record.key());
        data.value = JsonFormat.printer().print(request);
        data.timestamp = record.timestamp();
        data.offset=record.offset();
        data.partition=record.partition();		
        return data;
    }

    @Override
	public boolean isEndOfStream(KafkaRecord nextElement) {
		return false;
	}

    @Override
	public TypeInformation<KafkaRecord> getProducedType() {
		return TypeInformation.of(KafkaRecord.class);
	}
}
```

The above data object is eventually used in the below code to get a JSONObject:

```java
JSONObject json = new JSONObject(data.getValue().trim());
```

The obtained json object has the below issues:

1) The "sum" attributes are getting converted to "doubleSum" and "gauge" to "doubleGauge".

2) If under "sum" there is an "asInt", it is getting removed completely. We are forced to use pdata.NumberDataPoint.SetDoubleVal() even though the data type of the metric is an int like the number of network packets dropped. Below is an excerpt from https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/networkscraper/network_scraper.go 

```go
func initializeNetworkConnectionsDataPoint(dataPoint pdata.NumberDataPoint, now pdata.Timestamp, protocolLabel, stateLabel string, value int64) {
	labelsMap := dataPoint.LabelsMap()
	labelsMap.Insert(metadata.Labels.NetworkProtocol, protocolLabel)
	labelsMap.Insert(metadata.Labels.NetworkState, stateLabel)
	dataPoint.SetTimestamp(now)
	dataPoint.SetDoubleVal(float64(value))
	//dataPoint.SetIntVal(value)
}
```

3) "asDouble" attributes are getting converted to "value".

4) Any metric value of 0 is getting removed.

I'm not sure if this is a bug or the way we are converting the protobuf to json is flawed or this is expected behaviour. Kindly guide me.

**Steps to reproduce**
Generate metric data of int type using any of the existing scrapers (ex: network scraper) and export that to the gateway. The protobuf encoded metric data when converted to json has the above mentioned issues.

**What did you expect to see?**
The attribute names don't change and the int values retained including 0 values.

**What did you see instead?**
Attribute names changes and int values including 0 values get removed as explained above.

**What version and what artifacts are you using?**

opentelemetry-collector: https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.31.0 
opentelemetry-java: https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-proto/1.5.0-alpha 
protobuf-java-util: https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util/3.15.3

How did you reference these artifacts: go.mod & pom.xml

**Environment**
Compiler: Go 1.16, java version "1.8.0_291"
OS: macOS

**Additional context**
We use fileexporter (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter) on the collector side to first verify the metric data by exporting it to a json file. There we could see the attribute names as expected and no missing integer or 0 values. When we convert the protobuf to json using the opentelemetry-java and protobuf-java-util, the issue is seen. Please note that for debugging, we use a fileexporter on the gateway side as well and could see the metric data in the same format as on the collector side. It is only when we use the conversion logic as explained above, we could see the discrepancy and data loss.

**Comment by anuraaga** [comment]
@dittakaviram It sounds like your kafka job must be using an old version of opentelemetry-proto that's targeted at v0.7.0, as here

https://github.com/open-telemetry/opentelemetry-proto/blob/v0.7.0/opentelemetry/proto/metrics/v1/metrics.proto#L141

There we can see fields like `double_gauge` and there is no `as_int`. I see you mention using opentelemetry-proto 1.5.0 but can you confirm you actually are using it?

**Comment by dittakaviram** [comment]
@anuraaga I confirm we are using opentelemetry-proto 1.5.0. Below is an excerpt from pom.xml:

```
</dependency>
              <dependency>
                  <groupId>com.google.protobuf</groupId>
                  <artifactId>protobuf-java-util</artifactId>
                  <version>3.15.3</version>
              </dependency>
              <dependency>
                  <groupId>com.google.protobuf</groupId>
                  <artifactId>protobuf-java</artifactId>
                  <version>3.15.3</version>
              </dependency>
              <dependency>
                  <groupId>io.opentelemetry</groupId>
                  <artifactId>opentelemetry-proto</artifactId>
                  <version>1.5.0-alpha</version>
              </dependency>
<dependency>
```

**Comment by dittakaviram** [comment]
@anuraaga Please also refer these 

https://github.com/open-telemetry/opentelemetry-proto/pull/278 
https://github.com/open-telemetry/opentelemetry-proto/pull/330 
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes

**Comment by anuraaga** [comment]
@dittakaviram I'm not too sure exactly what role the collector is playing in your setup, but I notice now that the collector version is quite old and does not use the latest proto, which was updated in 0.32.0 of the collector. There will be mysterious issues when the proto version isn't compatible, before using the stable metrics protocol.

Can you try updating to the latest collector?

**Comment by dittakaviram** [comment]
@anuraaga We are using 0.31.0 and 0.35.0 got released just yesterday. I wouldn't say it is quite old. But, I already tried using the collector with version 0.34.0 and the issue persists.

As for the role of collector in our setup, as I explained in the use case, we are trying to extract various system related metrics using hostmetricsreceiver (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver) component of the opentelemetry-collector.

**Comment by anuraaga** [comment]
0.34.0 would be fine to try too, yeah.

Unfortunately, I don't think we'll be able to provide much more points TBH. The protos published in opentelemetry-proto 1.5 have no reference of fields like doubleGauge so there isn't really any reason they would get outputted with such fields. Are you 100% sure that the Kafka job is actually referencing the new protos, even with that POM definition? Perhaps the deployed jar is still bundling the old one for some reason. Nothing else seems possible - the output you are getting is definitely expected if the proto was 1.2.0 for some reason, 1.3.0 is when we targeted the new structure.

**Comment by cwildman** [comment]
@dittakaviram I was seeing the same issue as you with metric values of zero being dropped and confirmed this is an incompatibility with v0.7.0 and earlier of the proto. Commented on that change [here](https://github.com/open-telemetry/opentelemetry-proto/pull/278/files#r711815462).

**Comment by dittakaviram** [comment]
Thanks @anuraaga & @cwildman. I was able to resolve the issue by removing the jars of the older versions of opentelemetry-proto which were lying around in the local maven repository on my machine and somehow getting built into the application jar even though the pom.xml indicates a newer version. I'm now using the latest version and the metric data is appearing in the expected format post json conversion. Thanks again.
