### ISSUE TITLE
No documentation on artifact names (or it is not easy to find)

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3632]
Slightly related to https://github.com/open-telemetry/opentelemetry-java/pull/3603, it is not obvious what artifacts one needs to depend on when using certain packages.
The readme documents

```gradle
dependencies {
  implementation platform("io.opentelemetry:opentelemetry-bom:1.6.0")
  implementation('io.opentelemetry:opentelemetry-api')
}
```

But what do I need for https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure for example? I think it's `opentelemetry-sdk-extension-autoconfigure` (with singular "extension") but I only know that because I worked on #3603...

If there is any documentation on this, it should be linked more prominently in the README, e.g. the (incomplete) table at https://github.com/open-telemetry/opentelemetry-java#releases would be a good place to add artifact IDs to.

**Comment by jkwatson** [comment]
Agreed. I usually look at the bom for this but we should have better documentation. Can you write some for us, @Oberon00 ?

**Comment by Oberon00** [comment]
Linking to the BOM content may actually be a good "workaround", I didn't think of this.
