### ISSUE TITLE
Wildcard support Tracer

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-java#3641]
What I'm looking for:
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Trace/TracerProviderBuilderBase.cs#L58

There is a concept of AddSource() for the TracerProviderBuilder.

I know that the concepts are not exactly the same, and maybe this could be clarified with documentation. However, what would be the recommended way in Java to filter out information from certain sources.

Such that if provide a list of:
"com.example.suba"
"com.example.subb"

If I get a Tracer for "com.example.subc" then spans wouldn't get sent for that particular one.

**Comment by jkwatson** [comment]
Can you explain what you mean by this? I don't read .Net code particularly well, and it would be helpful to outline what you're trying to accomplish. Is this something that we're out of compliance with the specification?

**Comment by hdost** [comment]
@jkwatson I've updated, sorry for the delay. 🕐

**Comment by jkwatson** [comment]
Is this an API that was added in .Net, but was never added to the specification? If so, it will need to be added to the otel specification before we would add it to the java APIs. Otherwise, this is not something we will support in Java.
