### ISSUE TITLE
Autoconfigure SHOULD append /v1/(traces|metrics) to OTEL_EXPORTER_OTLP_ENDPOINT 

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3650]
See the description of "Endpoint (OTLP/HTTP)" at https://github.com/open-telemetry/opentelemetry-specification/blob/v1.6.1/specification/protocol/exporter.md#configuration-options:

> When using `OTEL_EXPORTER_OTLP_ENDPOINT`, exporters SHOULD follow the collector convention of appending the version and signal to the path (e.g. `v1/traces` or `v1/metrics`), if not present already.

Note this does not apply to the signal-specific envvars.

This is actually an important SHOULD, because otherwise OTEL_EXPORTER_OTLP_ENDPOINT cannot sensibly be used because metrics and traces would be sent to the same URL.

Not sure about the "if not present already" part though, that seems like a spec defect, because configuring a URL ending with /v1/traces as endpoint for all signals would mean that metrics are also sent to /v1/traces, which makes no sense at all. Will file a spec issue.

EDIT: I should mention that I was made aware of this issue by @rypdal. Thank you!

**Comment by jack-berg** [comment]
Good catch! I'm happy to fix this.

**Comment by rypdal** [comment]
Thanks to @Oberon00  for discussion of the issue and specification. It applies to [opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet) as well. I'm going to fix it in a scope of this PR: https://github.com/open-telemetry/opentelemetry-dotnet/pull/2316

**Comment by Oberon00** [comment]
I created open-telemetry/opentelemetry-specification#1975 to clarify the spec.
