### ISSUE TITLE
Java - Parent Span does not cover @Async method Child Span

### ISSUE THREAD

**Issue by jaz1414** [open-telemetry/opentelemetry-java#3660]
**Describe the bug**
I've created a sample code to implement OpenTelemetry Tracing. I made a custom annotation and within this annotation contains the Trace code, custom annotation was used to track all methods in the application and become dynamic. When using span on async child methods. It creates a new parent span instead of becoming a child span. We are using Google Cloud Platform's Trace to view the trace list. When I've tried on non-async methods, it works.

**Steps to reproduce**
1. I have the following custom annotaion (Java AOP)

`public class TelemetryAspect {
	
	private final OpenTelemetryConfig openTelemetryConfig;
	
	public static int spanCount = 0;
	
    @Value("${enableTrace}")
	private boolean isTraceEnabled;
	
	@Autowired
	public TelemetryAspect(OpenTelemetryConfig openTelemetryConfig) {
		this.openTelemetryConfig = openTelemetryConfig;
	}
	
	@Around("@annotation(telemetryInterface)")
	public Object logExecutionTime(ProceedingJoinPoint joinPoint, TelemetryInterface telemetryInterface) throws Throwable {
	    Object proceed = null;
		if (isTraceEnabled) {
		    long start = System.currentTimeMillis();
		    String tracer = getClass().getPackage().getName();
		    String method = (String) telemetryInterface.method();
		    boolean isParent = (boolean) telemetryInterface.isParent();
		    String signature = joinPoint.getSignature().toString();
		    String funcName = signature.substring(signature.lastIndexOf(".")+1);
		    MethodSignature signatureDef = (MethodSignature) joinPoint.getSignature();

		    Span dashboardSpan = openTelemetryConfig.startSpan(tracer, funcName, isParent);
				try (Scope scope = dashboardSpan.makeCurrent())  {
					openTelemetryConfig.setSpanAttributes(dashboardSpan, method);
				    proceed = joinPoint.proceed();
					
				} catch (Throwable t) {
				    return null;
				} finally {
				    long executionTime = System.currentTimeMillis() - start;
					System.out.println(joinPoint.getSignature() + " executed in " + executionTime + "ms");
					dashboardSpan.end();
				}

		} else {
			proceed = joinPoint.proceed();
		}

	    return proceed;
	}
}`

2. I have the following Configuration class to initialize OpenTelemetry on start up and also custom methods for spans.

`public class OpenTelemetryConfig {
    
    @Value("${enableTrace}")
	private boolean isTraceEnabled;

    @Value("${envURL}")
	private String url;
    
    @Value("${workload}")
	private String workload;
	
	private OpenTelemetrySdk sdk;
	
	private Span span;
	
	private Span parentSpan;
	
	private Context context;
	
	int spanCount = 0;

	private Tracer tracer;

	@PostConstruct
	public void openTelemetrySdk() throws IOException {
		if (isTraceEnabled) {
			TraceConfiguration config = TraceConfiguration.builder()
					.setDeadline(Duration.ofMillis(30_000)).build();
			TraceExporter traceExporter = TraceExporter.createWithConfiguration(config);
			sdk = OpenTelemetrySdk.builder()
					.setTracerProvider(SdkTracerProvider.builder()
							.addSpanProcessor(BatchSpanProcessor.builder(traceExporter).build())
							.build())
					.buildAndRegisterGlobal();
			System.out.println("STARTING");
			String tracerName = getClass().getPackage().getName();
			tracer = sdk.getTracer(tracerName);
		}

	}
	
	public Span startSpan(String tracers, String builder, boolean isParent) {

		span = tracer
				.spanBuilder(builder)
				.startSpan();
		System.out.println("setting span " + builder);
		context = Context.current();
		parentSpan = Span.current();
		spanCount = 0;
		System.out.println("parentSpan span " + parentSpan);
		System.out.println("parentSpan context " + context);
		return span;
	}`

3.  Plug in annotation to parent method and child method which is async.
     
    **Parent Method**

`@Service
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS, value = "request")
public class DemoService implements IDemoService {
	private final OpenTelemetryConfig openTelemetryConfig;

	private final AsyncTestHelper asyncTestHelper;
	
	@Autowired
	public DemoService(OpenTelemetryConfig openTelemetryConfig, DemoHelper demoHelper, TestHelper testHelper, RestTemplateBuilder restTemplateBuilder,
			AsyncTestHelper asyncTestHelper, SecondTestHelper sectestHelper) {
		this.openTelemetryConfig = openTelemetryConfig;
		this.asyncTestHelper = asyncTestHelper;
	}

	
	  @Override
	  @TelemetryInterface(method="GET")
	  public User getAttendance(long num, String view) {
		  User page1 = null;
		  try {
			Thread.sleep(3000);
			System.out.println("timer done");
			page1 = asyncTestHelper.findUser("PivotalSoftware", 3000).get();
			return page1;
		  } catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return null;
		  } catch (ExecutionException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return null;
		  }
	    
	  }`

  

`  **Child Method** public class AsyncTestHelper {
	
	private final RestTemplate restTemplate;
	
	@Autowired
	public AsyncTestHelper(RestTemplateBuilder restTemplateBuilder) {

		this.restTemplate = restTemplateBuilder.build();
	}
	  @TelemetryInterface(isParent = false)
	  @Async 
	  public CompletableFuture<User> findUser(String user, int timeout) throws InterruptedException {
	    String url = String.format("https://api.github.com/users/%s", user);
	    User results = restTemplate.getForObject(url, User.class);
	    // Artificial delay of 1s for demonstration purposes
	    System.out.println("pullinggg");
	    Thread.sleep(timeout);
	    return CompletableFuture.completedFuture(results);
	  }`

**What did you expect to see?**
I was expecting the findUser()  method to be the child of getAttendance(). I've tried this on non-async methods and they work as expected.
![image](https://user-images.githubusercontent.com/91311976/134639919-19683b7b-a3d6-475c-bac6-883ab5d8a1f1.png)

**What did you see instead?**
Both became parent spans. The getAttendance trace however still shows the total duration including the time for findUser().
![image](https://user-images.githubusercontent.com/91311976/134639634-bb6a174a-959e-4652-bb64-8b22b46e0e77.png)
![image](https://user-images.githubusercontent.com/91311976/134639713-72b136f6-a8fa-4676-8d5b-bd9d4bf3d8d1.png)
![image](https://user-images.githubusercontent.com/91311976/134639772-f5f6ef9e-de1a-47f6-8dad-b2b2e2880654.png)

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-api`, `opentelemetry-sdk`
Version: (1.1.0)

**Environment**
Compiler: ("AdoptOpenJDK 11.0.6")
OS: ("Windows 10")

**Comment by anuraaga** [comment]
Async causes the child method on another thread so it doesn't have access by default to the "current" span of the parent thread. You need to configure propagation of context across threads.

If you already have a task executor you can just wrap it, or otherwise may have to define a task executor first to wrap.

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/EnableAsync.html

If you wrap the async task executor with `Context.taskWrapping` it will propagate context

https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/Context.java

**Comment by jaz1414** [comment]
I already have a task executor. How would you suggest I use this `Context.taskWrapping `in my current code?

**Comment by anuraaga** [comment]
@jaz1414 Are you able to provide a snippet on how you implement your task executor? For example, is it a bean that returns `Executor`?

**Comment by jaz1414** [comment]
yep it looks like this

![image](https://user-images.githubusercontent.com/91311976/135017930-ba717b32-be90-409b-a639-919352fe7827.png)

**Comment by anuraaga** [comment]
So I think you should just be able to do something like `return Context.taskWrapping(executor)` on line 22. Are you able to give that a try?

**Comment by jaz1414** [comment]
it worked, the async child attached to its parent. thanks a lot for the help! closing this issue

**Comment by sijonelis** [comment]
@anuraaga does this solution exist somewhere in the documentation (this PR was the first thing that I found, when looking up a similar issue). If not, do you think its worth me making a pr to the docs about it?

**Comment by trask** [comment]
hi @sijonelis, I could see general doc about context propagation across threads fitting in https://opentelemetry.io/docs/instrumentation/java/manual/

and the more spring specific parts fitting in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring
