### ISSUE TITLE
Getting  error to run otlp docker compose script

### ISSUE THREAD

**Issue by dijadhav** [open-telemetry/opentelemetry-java#3698]
**Describe the bug**
We are using latest repo and the scripts given in below url. 
https://github.com/open-telemetry/opentelemetry-java/tree/main/examples/otlp/docker

Once we execute docker compose command we are facing below mentioned error.
docker logs docker_otel-collector_1
2021-10-05T14:52:54.027Z info service/collector.go:303 Starting otelcol...

{"Version": "v0.33.0-50-g0594aa1a", "NumCPU": 12}
2021-10-05T14:52:54.027Z info service/collector.go:242 Loading configuration...
Error: cannot load configuration: unknown extensions type "pprof" for pprof
2021/10/05 14:52:54 collector server run finished with error: cannot load configuration: unknown extensions type "pprof" for pprof

**Steps to reproduce**
1)Clone the latest repo
2) Go to <repo>/examples/otlp/docker
3) execute docker compose command mentioned in Readme

**What did you expect to see?**
otlp collector should be started successfully.

**What did you see instead?**
otlp collector failed to start

**What version and what artifacts are you using?**
https://github.com/open-telemetry/opentelemetry-java/tree/main/examples/otlp/docker

Artifacts: 
opentelemetry-java
Running docker scripts from https://github.com/open-telemetry/opentelemetry-java/tree/main/examples/otlp/docker

**Environment**
OS-Ubuntu 20.04

**Comment by jkwatson** [comment]
Thanks for the report. I'll try to take a look at this today or tomorrow. If you have the fix, a PR would be great!
