### ISSUE TITLE
Make MINIMUM_COLLECTION_INTERVAL_NANOS configurable

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3725]
We have a TODO

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/DefaultSdkMeterProvider.java#L54

But I realized it's particularly important because it makes using `InMemoryMetricReader` usage currently awkward because it is also getting throttled by the collection interval check (I think).

**Comment by anuraaga** [comment]
Example awkwardness: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4340/commits/7931f25ba7029cf8273663098c507b297aec7eef

**Comment by jack-berg** [comment]
Solved in #3831. [Relevant code](https://github.com/open-telemetry/opentelemetry-java/pull/3831/files#diff-43649c1a3764f60112c2d8c8eaf7bed806ef456c6802e0a35d1ef8f310faf272R138-R144).
