### ISSUE TITLE
Change MetricData to interface

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3733]
`MetricData` is an abstract class while `SpanData` is an interface. We should be consistent and change `MetricData` to be an interface. 

Additional context: I'm proposing switching `LogData` to be an interface in PR #3732.

**Comment by breedx-splk** [comment]
@jack-berg do we think there's anything left to do on this? If not, plz close. Thanks. 👍🏻

**Comment by jack-berg** [comment]
Thanks!
