### ISSUE TITLE
Allow mutable accumulations

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-java#3766]
**Is your feature request related to a problem? Please describe.**
As discussed with @jsuereth in #3724, it would be beneficial to allow accumulations to be mutable. Specifically for the exponential histogram, immutability of accumulations requires a decent amount of CPU + memory. 

**Describe the solution you'd like**
`DeltaMetricStorage` relies on accumulations being immutable, however switching it to a clone + mutate approach would allow accumulations to be mutated while merging. i.e. merge into existing accumulation rather than creating a new one. 

Additionally, we should be careful about the lifecycle and ownership of accumulations. Anything to aid this is encouraged.

**Comment by jack-berg** [comment]
Accumulations have been optimized out of the SDK implementation in #5154. This was in addition to several other recent metrics SDK optimizations, some of which were specific to exponential histograms.

Can further optimize allocations by going forward with something like the #5178 prototype, but that's a distinctly different problem than what is requested here.
