### ISSUE TITLE
Refine log fields

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3804]
A handful of questions have come up regarding log fields. This issue tracks them so we don't forget.

1. All the fields in the [log proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto) are optional except timestamp, but only traceId, spanId, severityText, and Name are `@Nullable`. The other fields have default values. We should have a uniform strategy on this, or good reasons for breaking uniformity.
2. There have been [discussions](https://github.com/open-telemetry/opentelemetry-java/pull/3759#discussion_r738021302) about removing the `setBody(Body body)` method and simply keeping `setBody(String message)`. 
3. There have been [discussions](https://github.com/open-telemetry/opentelemetry-java/pull/3759#discussion_r738020720) about dropping or renaming the `name` field. 
4. We should make `setFlags(int flags)` more usable. Perhaps `setFlags(LogFlags)` akin to `TraceFlags`?

**Comment by jack-berg** [comment]
I've included the change of the pattern to `LogEmitter.logBuilder().emit()` in PR #3759.

**Comment by jack-berg** [comment]
I believe 2 is resolved now that spec [PR #2096](https://github.com/open-telemetry/opentelemetry-specification/pull/2096) was merged explaining why log body should be structured. 

> 2. There have been discussions about removing the setBody(Body body) method and simply keeping setBody(String message).

**Comment by anuraaga** [comment]
Would it make sense to leave the structured version out of the SDK until someone asks for it? It mentions compatibility with certain existing log formats, but perhaps we can wait until we know this actually exists in the Java ecosystem, unless someone already has an example.

**Comment by jack-berg** [comment]
I'd be on board to make it an internal implementation detail until required. Can keep the `setBody(String)` method and add a `setBody(Body)` overload when requested?

**Comment by jack-berg** [comment]
All but one of these items were addressed in #3837. 

The last unaddressed item is about the log `name` field. This is being actively discussed in [the specification](https://github.com/open-telemetry/opentelemetry-specification/issues/2074). If the field is removed in the spec, I'll remove it here. But for now, I'll close this ticket.
