### ISSUE TITLE
[spec compliance] Metrics SDK does not fail on duplicate name/different instrument metrics.

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-java#3809]
Currently, the metric storage component does not fail if in the current scenario:

- There are two different instruments (e.g. Counter + Histogram) with the same name on the same meter
- A user provided `View` configuration renames the Counter to another name with no conflict.

This should fail, according to the specification.

**Comment by jack-berg** [comment]
> There are two different instruments (e.g. Counter + Histogram) with the same name on the same meter

@jsuereth I believe this is no longer possible now that `MetricDescriptor#isCompatible(MetricDescriptor)` checks that the instruments are of the [same type](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/descriptor/MetricDescriptor.java#L85). The user should get a compatibility warning log if they try to do this.

**Comment by jack-berg** [comment]
Closing because the spec has [clarified](https://github.com/open-telemetry/opentelemetry-specification/pull/2317) the behavior in the presence of identity conflicts. This was implemented in #4222.
