### ISSUE TITLE
Add ability to configure clock for SdkLogEmitterProvider

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3817]
`SdkMeterProviderBuilder` and `SdkTracerProviderBuilder` each have a `setClock(Clock clock)` method, while `SdkLogEmitterProviderBuilder` does not.

****Should `SdkLogEmitterProvider` need the ability to customize the clock?****

The logs that are emitted from `LogEmitter` instances can have their timestamps set by the caller. If not set, they'll default to `System.currentTimeMillis()`. Arguably if log timestamps are not set they should default to `clock.now()`. 

On the other hand, the [log proto](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L117) says that a timestamp field of 0 indicates an unknown or missing timestamp. So arguably, if a caller fails to the timestamp it should default to 0, or `null`.

**Comment by jkwatson** [comment]
agreed. We should let the clock be configured.  

> Arguably if log timestamps are not set they should default to clock.startTime()

??? startTime? Not `now()`?

**Comment by jack-berg** [comment]
Sorry typo! Yes, `now()`. Corrected. 

As for a timestamp value of `0`, that can still be accomplished by calling `setEpoch(0, TimeUnit.SECONDS)`.

**Comment by breedx-splk** [comment]
I could take this.
