### ISSUE TITLE
Add version properties file in jars

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#3818]
**Is your feature request related to a problem? Please describe.**

In "jarjar/shaded" deployments, `getImplementationVersion()` is not useful, and getting/logging the OpenTelemetry SDK/API version can be helpful in some cases (e.g. supportability message in an exporter).

Also, it seems that `getImplementationVersion()` doesn't work under the Java Module system (or could just be my inability to get anything to work under the Java Module system 😭). Some reading here in case it's useful: https://github.com/junit-team/junit5/issues/600

**Describe the solution you'd like**

I would like for each artifacts to have a properties file, e.g. `opentelemetry-api.properties`, that can be queried to check the version at runtime.

**Comment by jkwatson** [comment]
We already have this in our jars. There is a `version.properties` file in each jar, usually in the package related to the content of the jar. For example, in the opentelemetry-api jar, it's in the 'io.opentelemetry.api' package in the jar structure.

**Comment by trask** [comment]
oh, how did I miss this, thx!
