### ISSUE TITLE
what time to implement semantic_conventions metrics

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-java#3850]
I find the specification https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/rpc.md had defined some universal metrics，so when java sdk will implement them.

**Comment by jkwatson** [comment]
HI @yangtaoran . We'll implement these when the code generator works for the metric semantic conventions like it does for spans. 

The metrics themselves would be implemented in the instrumentation, not in the SDK itself.

**Comment by yangtaoran** [comment]
thank you
