### ISSUE TITLE
Remove Aggregator.diff, no need to support Cumulative -> Delta based on the metrics SIG.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#3883]

**Comment by jack-berg** [comment]
`Aggregator.diff` is used to support delta export of asynchronous instruments, which are assumed to be cumulative. If we remove this method, than you can only export asynchronous instruments as cumualtive.

**Comment by bogdandrutu** [comment]
The SDK should not do this because may not be able to do it for all the Aggregators so if any of exporter needs this they can implement it. See https://github.com/open-telemetry/opentelemetry-go/pull/2350

**Comment by jack-berg** [comment]
> exporter needs this they can implement it.

True. Right now `Aggregator` is an internal class because you can't define your own `Aggregation`. So I think its fine now, but something needed if we want to make it possible to define custom `Aggregation`s.

**Comment by jack-berg** [comment]
Closing because: 1. Cumulative -> delta is necessary in the SDK for delta export of async counter and async up down counter. 2. Aggregator is an internal implementation detail.
