### ISSUE TITLE
[Prometheus Exporter] Remove Exemplar Data for metrics type of Gauge/Sum

### ISSUE THREAD

**Issue by zmapleshine** [open-telemetry/opentelemetry-java#3884]
**Describe the bug**
Hi all,I used Prometheus(v2.31.1) to collect metrics generated by opentelemetry-sdk-metrics .

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpServerMetrics.java#L59

In OpenMetrics specification, metrics that do not support the Gauge type include Exemplar data.
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#gauge

However, I found that the SDK generates exemplar data for the Gauge type.

```shell
# TYPE http_server_active_requests gauge
# HELP http_server_active_requests The number of concurrent HTTP requests that are currently in-flight
http_server_active_requests{http_flavor="1.1",http_host="localhost:8080",http_method="GET"} 804.0 # {span_id="ac077bb161fbad99",trace_id="8f2a9dd8df7d10f07b9bf43651b7e391"} -1.0 1636979234.824
http_server_active_requests{http_flavor="1.1",http_host="localhost:8080",http_method="GET"} 0.0 # {span_id="536633e974994e4a",trace_id="526471f870257edda11761f8c71f8897"} -1.0 1636979237.229
```

Prometheus failed to parse such data and thus failed to collect all metrics data for the instance.

**What version and what artifacts are you using?**

opentelemetry-sdk-metrics : 1.7.0-alpha

**Comment by jsuereth** [comment]
FYI - For a workaround, you can set the following when running the agent:

```-Dotel.metrics.exemplar.filter=none```

This will disable all exemplar sampling.

Pushing a fix for this shortly.
