### ISSUE TITLE
Determine fate of summary

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3888]
There are remnants of `Summary` aggregation in the metrics SDK public API, which appears in the metrics [data model spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#summary-legacy), but not in the [sdk spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md). 

Appearances in the SDK:
- `MetricData#getDoubleSummaryData()`
- `MetricDataType#SUMMARY`
- (non public) `LongMinMaxSumCountAggregator`
- (non public) `DoubleMinMaxSumCountAggregator`

Summary also shows up in the OTLP metric exporter, which supports serialization of the summary flavor of `MetricData`, as well as in the prometheus exporter.

One argument for keeping around parts of it is because `min` and `max` fields are coming to histogram, and a the `*MinMaxSumCountAggregator` could be adapted as an optimization of a single bucket histogram. This isn't convincing to me though - I would rather see explicit bucket histogram just optimized for the single bucket use case. 

I think we get rid of all the summary remnants from the SDK, and by extension the exporters as well, until the SDK specifies them.

**Comment by jack-berg** [comment]
Another option is to leave the summary implementation of `MetricData`, but to remove the MinMaxSumCount stuff.

**Comment by jsuereth** [comment]
We need Summary for OpenCensus compatibility (which will be spec'd fully in Q1, shortly after stability).

I think I'm on board removing `MinMaxSumCount`, but we will need `Summary` for compatibility hooks (like OpenCensus -> OTel, Dropwizard Metrics -> OTel, other legacy metric systems).

**Comment by jack-berg** [comment]
So @jsuereth under that thinking, the `MetricData` interface is the java embodiment of the metric data model [data points](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#metric-points) section, despite it being published in the sdk module?

Just want to clarify this is ok. If the sdk module is supposed to be a strict embodiment of the [sdk spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md), then we should omit summary until its spec out.
