### ISSUE TITLE
AWS Resources are not adding all necessary attributes

### ISSUE THREAD

**Issue by luneo7** [open-telemetry/opentelemetry-java#3898]
**Describe the bug**
AWS Resources in the SDK extension are not adding all the required attributes, so the collector is not extracting origin for instance.
The collector was changed to require the cloud platform attribute, but the Java counter part is not adding this info (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/426244389f8f6326ba368946cda28eba85284adf/exporter/awsxrayexporter/internal/translator/segment.go#L224)

The Golang version of the ECS detector, and all others are adding more info (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/426244389f8f6326ba368946cda28eba85284adf/processor/resourcedetectionprocessor/internal/aws/ecs/ecs.go#L57)

It would be awesome to have this fixed in the Java side so AWS X-Ray can decode the origin successfully, and also have more info in the AWS X-Ray Dashboard

**Steps to reproduce**
Create one trace and export to AWS Collector with X-Ray exporter, check the trace segment origin, and there will be nothing

**What did you expect to see?**
AWS X-Ray with correct information of origin and ECS/EKS info.

**What did you see instead?**
Nothing =]

**Comment by jkwatson** [comment]
assigning to @anuraaga as our AWS expert
