### ISSUE TITLE
Manual Instrumentation

### ISSUE THREAD

**Issue by dd00f** [open-telemetry/opentelemetry-java#3899]
The tutorial should show how to import the right libraries to run the code sample. ( Maven or Gradle ).
Following the library guidelines, it's possible to see samples importing the API, but not the SDK.

    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
    </dependency>    
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk</artifactId>
    </dependency>

**Comment by jkwatson** [comment]
@dd00f which tutorial are you referring to, in particular?

**Comment by dd00f** [comment]
@jkwatson I was following the tutorial on the page : 
https://opentelemetry.io/docs/java/manual_instrumentation/

I thought that by clicking on "Create documentation issue" the page would be automatically linked, but it wasn't the case. My bad.

I was trying to create Spans and metrics based on that page.

I found sample imports for the api package by following the link to the opentelemetry-java project
https://github.com/open-telemetry/opentelemetry-java

This page describers how to import the API  package in Maven, but not the SDK.

I found the code samples also assumed some static method imports, which made applying those samples tricky.

Example : 
`  BoundLongCounter someWorkCounter = counter.bind(Attributes.of(stringKey("Key"), "SomeWork"));`

In this code, the method `stringKey` must be statically imported to work.

**Comment by jkwatson** [comment]
Yes, we don't really have a good way to provide fully runnable examples in the website docs at the moment. This is definitely a known issue. The `examples` sub-project in this repo is probably the best place to find fully runnable examples, rather than the tutorial on the opentelemetry.io website.

**Comment by jkwatson** [comment]
Closing this, as the website docs now link to the repository with the examples in it.
