### ISSUE TITLE
OkHttp Dispatcher thread keeps JVM from shutting down

### ISSUE THREAD

**Issue by pmv** [open-telemetry/opentelemetry-java#3900]
**Describe the bug**
We had an issue where once we applied the java agent with the otlp exporter to a JVM, the JVM would no longer shut down.  A thread dump identified the OkHttp Dispatcher thread as a non-daemon thread.

It appears the issue is in 
https://github.com/open-telemetry/opentelemetry-java/blob/v1.9.0/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/okhttp/OkHttpExporterBuilder.java#L88-L89

and

https://github.com/open-telemetry/opentelemetry-java/blob/v1.9.0/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/OkHttpGrpcExporterBuilder.java#L113

We tested a fix by changing the OkHttpClient builder to specify a custom dispatcher that uses daemon threads.  After making this change, the JVM shuts down as expected.

We changed
```java
OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();
```

to

```java
//matches OkHttp defaults except daemon=true instead of false
ThreadPoolExecutor daemonExecutorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE, 60,
        TimeUnit.SECONDS,
        new SynchronousQueue<>(), Util.threadFactory("OkHttp Daemon Dispatcher", /* daemon= */true));
Dispatcher daemonDispatcher = new Dispatcher(daemonExecutorService);
OkHttpClient.Builder clientBuilder =
         new OkHttpClient.Builder()
            .dispatcher(daemonDispatcher);
```

Thanks for looking - let me know if you need any more information.

**Comment by anuraaga** [comment]
Hi @pmv - to confirm, what version of the javaagent are you using? Previous versions weren't shutting down the okhttp thread when the app shutdown, but that should be happening now. If it isn't, then it's a bug (which may be causing missed telemetry, not just a hanging thread)

**Comment by pmv** [comment]
1.7.2 is the version that is hanging.  I see your point about missing telemetry...if you prefer to not switch these to daemon threads, do you have other suggestions for finding the bug?  My first thought is to turn up logging / perhaps add logging to the shutdown process - if you have better ideas let me know.

**Comment by anuraaga** [comment]
@pmv Do you think you'd be able to provide a simple repro app so we can trigger the behavior and see what could be going on?

**Comment by pmv** [comment]
@anuraaga - sorry for the delayed response.  Thank you for the additional change, however, it did not fix our issue.  

After doing some reading, I believe there is a valid use case that is currently not covered.

> A program terminates all its activity and exits when one of two things happens:
>  * All the threads that are not daemon threads terminate.
>  * Some thread invokes the exit method of class Runtime or class System, and the exit operation is not forbidden by the security manager.

(from https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.8)

As far as I can tell the opentelemetry shutdown process works for the second bullet, but the use of the non-daemon dispatcher thread stops people from relying on the first one.

Consider a vendor that allows execution of arbitrary java code inside their product.  The logic may look something like this:
1. Native code starts the JVM with user supplied parameters
2. One or more native threads are built, attached to the JVM, and execute user code
3. join() is called on the threads, with the expectation that each thread's user code will finish (all non-daemon threads will complete) and the JVM will exit

I think the situation we're in is that we've added the opentelemetry agent to the JVM parameters in step 1 to gain visibility into our code, but the non-daemon thread started by opentelemetry makes it so step 3 never completes.

I see two potential solutions:
1. A command line flag for using daemon threads (something like -Dotel.exporter.otlp.daemon-threads.enabled=true )?  To your earlier point, this has the potential to miss some telemetry on JVM shutdown, but it would not be the default, and the risk could be documented.
2. A separate daemon thread that periodically looks at all threads in the JVM.  If it detects the opentelemetry OkHttpClient dispatcher thread is the only non-daemon thread, initiate the shutdown process.

This is definitely an edge case, but it would be nice if it could be supported.

**Comment by anuraaga** [comment]
Thanks for clarifying @pmv - making the thread daemon isn't a problem I think just wanted to understand the scenario best. We usually use OTel in servers where thread shutdown is not used for exiting, but thanks to your explanation I realize there are non-server situations which are affected by this, we'll just change it to daemon.

**Comment by anuraaga** [comment]
Hmm - it looks like even if we change the dispatcher threadpool to daemon, HTTP/2 will always use non-daemon on 3.x

https://github.com/square/okhttp/issues/4009

So there isn't a complete fix unless we also bring in the kotlin stdlib with 4.x... 

Given how much slimming we were able to do, perhaps we should just accept the 1.6MB for kotlin - @trask any thoughts from agent perspective?

**Comment by trask** [comment]
> Given how much slimming we were able to do, perhaps we should just accept the 1.6MB for kotlin - @trask any thoughts from agent perspective?

I'm ok with adding back 1.6mb. I think it's good not to be pinning ourselves to an old okhttp library version anyways.
