### ISSUE TITLE
API: Move Samplers to util package under trace

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#391]
Following the same mode as Collections, Arrays do in java lang we should probably move the Samplers under an util sub-package under trace.

Also for Event and Link interfaces the default implementation can be under Events, Links classes that will expose a create static method. Events and Links can also be in util.

**Comment by carlosalberto** [comment]
> Also for Event and Link interfaces the default implementation can be under Events, Links classes that will expose a create static method

You mean getting them out from `SpanData` and put them there?

**Comment by bogdandrutu** [comment]
@carlosalberto I was thinking about that :)
