### ISSUE TITLE
Remove bound metric instruments

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3913]
Last call for this - we have discussed removing instrument binding in the past, but currently are on track for releasing stable with them. There seems to be no mention of binding in the spec

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md

Therefore I strongly advocate for removing them from our initial stable metrics release and adding them after spec work - they don't appear to be a Java-specific concern to me where we'd have API that's not in the spec.

**Comment by anuraaga** [comment]
@jsuereth Please give your blessing

**Comment by jsuereth** [comment]
Honestly, I think bound instruments are critical for high-performance workflows.   There are two points against this proposal:

1. Bound instruments are hard to add back in if we don't build + test them now.   They *are allowed* by the specification and I think they're necessary for high-performance use cases.
2. The specification will NOT be able to churn your stable APIs going forward, especially for features like this.  While I anticipate the design of "bound" in the Specification to eventually exactly match Java (as other languages are copying this, and our design of batch matches the previous specification), the more direct answer to this question is that the Specification should *not* break publicly exposes APIs of Java.

I'm definitely opposed to removing bound instruments (and the key performance tests verifying they work).

**Comment by jkwatson** [comment]
I think we need extended TC blessing to keep this in. @jsuereth can you discuss with your TC cohort and/or at the spec meeting?

**Comment by jsuereth** [comment]
Ok, let's remove this for now.  Plan is to bring it back in tandem w/ the batch-record API.  Hopefully it'll manifest in a cleaner way for end-users.
