### ISSUE TITLE
Rename ObservableMeasurement.observe -> ObservableMeasurement.record?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3914]
I feel as if `Consumer<Measurement>` is the observer and doing the observing - the method on the callback seems like it's actually recording, and is meant to be "semantically" the same as the record methods on the synchronous instruments.

**Comment by jsuereth** [comment]
@anuraaga This seems reasonable to me.   This version of the callback is java-specific (The specification only denotes a callback which collects measurements, it doesn't specify `ObservableMeasurement` in detail, that was java-specific.).

Going to reassign to you if you'd like to clean it up.

**Comment by jsuereth** [comment]
Also want to call out some conventions here:


- `record` means I'm recording a *complete* (or cumulatively added) value.  (Histogram + Async* instruments)
- `add` means I'm recording a *partial* or (delta) value that needs to be combined to produce a metric value. (Counter instruments)
