### ISSUE TITLE
Should async counters have a different callback parameter?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3915]
I think asynchronous instruments are supposed to have the same semantics as their synchronous counterpart. So it seems like a potential contradiction for us to have e.g., `LongCounter.add`, but `LongCounterBuilder.buildWithCallback` accepts a callback that only has `observe`, not `add`. Should we have callbacks matching the sync versions for these?

**Comment by anuraaga** [comment]
I have a feeling this is the asynchronous counters and gauges are the same, but not aspect of OTel metrics I hate, so suspecting there isn't actually a need to change. Just want to confirm.

**Comment by jsuereth** [comment]
Right now we're trying to use `observe` and `record` to denote *cumulative measurements*.   A method `add` would imply you're adding the value to previous values, which you aren't.    The difference between `Gauge` and `(Async) Counter`and `(Async) UpDownCoutner` is that the *default* metric is a Gauage or Sum.  The way measuring works is similar (sampling a value via callback).

So, actually, we specifically *don't* want the methods to match to avoid confusion, which it seems like we've failed at :)   Any recommendations?

**Comment by jack-berg** [comment]
> So, actually, we specifically don't want the methods to match to avoid confusion, which it seems like we've failed at :) Any recommendations?

I'm not sure I follow - how have we failed?

**Comment by anuraaga** [comment]
@jack-berg A counter I would expect to be what to use when I want to count, hence the add methods. It's confusing to me that async wouldn't look the same with add methods. But I understand that it isn't supposed to. I think we can expect a lot of counters that should have been gauges and vice versa in our lives going forward :)

In the meantime glad to confirm that the current API matches semantics
