### ISSUE TITLE
API: Finish default (also called no-op implementation) for Trace

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#392]
So far what we decide on this:
1. The default implementation will provide the w3c propagators.
1. The default Span will propagate the parent SpanContext, but will generate a new spanId for every new Span.
1. [Not decided] The default sampler will be to keep the sampling decision from the parent.
1. [Not decided] Tracestate will not be modified.
1. All recorded events, attributes, status, links will be dropped.

**Comment by songy23** [comment]
> The default Span will propagate the parent SpanContext, but will generate a new spanId for every new Span.

Note if a default span is a root span, it will also generate a new (and valid) trace ID.

**Comment by bogdandrutu** [comment]
Correct, so we need a Default SpanBuilder which should do the id generation.

**Comment by pavolloffay** [comment]
I can have a look at this issue.

> 2. The default Span will propagate the parent SpanContext, but will generate a new spanId for every new Span.

What would `SpanContext.getSpanId()` return? The newly generated spanId or parentId?

**Comment by bogdandrutu** [comment]
@SergeyKanzhelev:
I think child.getContext().getSpanId() will return a newly generated spanId

**Comment by pavolloffay** [comment]
Then how would `HttpTextFormat` know the original parent id?

**Comment by bogdandrutu** [comment]
I am confused, can you clarify a bit?

**Comment by pavolloffay** [comment]
> 2. The default Span will propagate the parent SpanContext, but will generate a new spanId for every new Span.

A component receives valid span context. Then it creates 2 new descendant spans and makes a downstream call. How would the `HttpTextFormat` get the original spanId from the incoming context?

**Comment by bogdandrutu** [comment]
Obsolate.
