### ISSUE TITLE
Replace exceptions with logs for incorrect metrics API usage

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3932]
As per OTel error conventions, we cannot throw exceptions within app code. We need to replace the exceptions in methods that implement the metrics API interfaces, such as this one

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleCounter.java#L35

**Comment by jack-berg** [comment]
Resolved in #3977.
