### ISSUE TITLE
GlobalMeterProvider doesn't respect auto-configure like GlobalOpenTelemetry does

### ISSUE THREAD

**Issue by BerndFarkaDyna** [open-telemetry/opentelemetry-java#3933]
**Describe the bug**
GlobalMeterProvider doens't check if it is 'maybeAutoConfigured' like GlobalOpenTelemetry does

**What did you expect to see?**
if i have opentelemetry-sdk-extension-autoconfigure on the ClassPath and set the corresponding properties the MetricsProvider should be configured to work out of the box.

**What did you see instead?**
A NoopMeterProvider is created.

**What version and what artifacts are you using?**
1.9.1
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)
implementation(platform("io.opentelemetry:opentelemetry-bom:1.9.1"))
implementation platform('io.opentelemetry:opentelemetry-bom-alpha:1.9.1-alpha')
..
..
..
[group: 'io.opentelemetry', name: 'opentelemetry-exporter-otlp'],
[group: 'io.opentelemetry', name: 'opentelemetry-sdk-metrics'],
[group: 'io.opentelemetry', name: 'opentelemetry-sdk'],
[group: 'io.opentelemetry', name: 'opentelemetry-sdk-extension-autoconfigure'],

**Environment**
Compiler:  AdoptOpenJDK 11.0.6
OS: Ubuntu 21.04

**Comment by anuraaga** [comment]
Hi @BerndFarkaDyna - while metrics is in alpha, you need to opt-in by enabling the exporter, `OTEL_METRICS_EXPORTER=otlp`. Would that fix it for you?

**Comment by BerndFarkaDyna** [comment]
@anuraaga: THX for your fast response but unfortunately it doesn't resolve my problem...

Even if i set OTEL_METRICS_EXPORTER=otlp 

the `GlobalMeterProvider` doesn't check the exporter in any way

```
public class GlobalMeterProvider {
  private static volatile MeterProvider globalMeterProvider = NoopMeterProvider.getInstance();

  private GlobalMeterProvider() {}

  /** Returns the globally registered {@link MeterProvider}. */
  public static MeterProvider get() {
    return globalMeterProvider;
  }

  /**
   * Sets the {@link MeterProvider} that should be the global instance. Future calls to {@link
   * #get()} will return the provided {@link MeterProvider} instance. This should be called once as
   * early as possible in your application initialization logic, often in a {@code static} block in
   * your main class.
   */
  public static void set(MeterProvider provider) {
    globalMeterProvider = (provider == null) ? NoopMeterProvider.getInstance() : provider;
  }
}
```

While `GlobalOpenTelemetry` does 

```
 public static OpenTelemetry get() {
    if (globalOpenTelemetry == null) {
      synchronized (mutex) {
        if (globalOpenTelemetry == null) {

          OpenTelemetry autoConfigured = maybeAutoConfigure();
          if (autoConfigured != null) {
            return autoConfigured;
          }

          set(OpenTelemetry.noop());
          return OpenTelemetry.noop();
        }
      }
    }
    return globalOpenTelemetry;
  }

private static OpenTelemetry maybeAutoConfigure() {
    final Class<?> openTelemetrySdkAutoConfiguration;
    try {
      openTelemetrySdkAutoConfiguration =
          Class.forName("io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk");
    } catch (ClassNotFoundException e) {
      return null;
    }
....
}

```

Is there any other recommended way to get an already configured MeterProvider for now?

**Comment by anuraaga** [comment]
Ah I see - yes currently you need to run `AutoConfiguredOpenTelemetrySdk.initialize()` for example yourself. We generally recommend this to have more control of the autoconfiguration and its lifecycle.

But implicit use through GlobalOpenTelemetry.get() will work in the next version of OTel as we are removing GlobalMeterProvider - metrics API is going stable so there will be `OpenTelemetry.getMeterProvider()`

**Comment by BerndFarkaDyna** [comment]
@anuraaga: THX for the Information. 

> But implicit use through GlobalOpenTelemetry.get() will work in the next version of OTel as we are removing GlobalMeterProvider - metrics API is going stable so there will be OpenTelemetry.getMeterProvider()

In that case feel free to close my issue since this looks even much better to not have 2 different factories for Traces and Metrics

**Comment by anuraaga** [comment]
Thanks for confirming @BerndFarkaDyna. We have a monthly release so it should be out next month. The cadence may be slightly slower than normal because it's the release that makes metrics stable but I would expect it by end of month.

**Comment by BerndFarkaDyna** [comment]
@anuraaga : just a sidenode:  AutoConfiguredOpenTelemetrySdk.initialize() doesn't touch Metrics at all for now (which i could explain myself due to the 'opt-in' of dependencies for metrics at the moment...

But anyway: since the metrics are going to be stable with the next release I'm totally fine
