### ISSUE TITLE
More detailed information is necessary for metric data type 'Histogram'

### ISSUE THREAD

**Issue by JasmineJ1230** [open-telemetry/opentelemetry-java#3938]
**Is your feature request related to a problem? Please describe.**

For metric data type 'Histogram', it seems that I can only get a summary data in the metric exporter.
Class DoubleHistogramPointData only have a sum, some boundaries and the count of data in each range.
It's hard for us to calculate the 95line 99line when monitoring the execution time.

**Describe the solution you'd like**

Would you please to provide an aggregation to collect all the recorded data points for Histogram data? 
Or is there any other ways to help us to get more detailed information?

**Comment by jack-berg** [comment]
A histogram will allow you to determine the percentage of measurements that are above or below each of the bucket boundaries, but there isn't enough to calculate an exact percentile. 

For example, the default histogram has explicit buckets boundaries at `[0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000]`. If you have a service level objective that 99% of measurements are < 100, you can determine whether or not that objective was achieved. However, you can't say which value represents the 99th percentile - it will always fall somewhere between bucket boundaries. 

The only way I know of to compute a percentile accurately is to capture everyone of the measurements and order them. 

> Would you please to provide an aggregation to collect all the recorded data points for Histogram data?

Right now there is only a fixed set of aggregations as defined in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#aggregation). There have been discussions about allowing custom aggregations, but that would come in some later update to the metrics spec.

**Comment by pmarschik** [comment]
The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation) mentions RecordMinMax for the Explicit Bucket Histogram Aggregation which [looks like](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/aggregator/DoubleHistogramAggregator.java) isn't implemented in OTEL java.
Another useful data-point for histogram aggregations would be the [squared deviations from the mean](https://en.wikipedia.org/wiki/Squared_deviations_from_the_mean) which could then be used to calculate the variance.

Adding those 3 data points (min, max, squared deviations from the mean) would allow us to provide more information in for GCloud Monitoring (see [Distribution](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TypedValue#Distribution))

**Comment by jsuereth** [comment]
> The spec mentions RecordMinMax for the Explicit Bucket Histogram Aggregation which looks like isn't implemented in OTEL java.

Yes, these were late additions and still optional.   We're still working through upgrading the OTel Collector to allow optional primitives in proto3, so there are technical limitations downstream preventing these being added just yet.

> Another useful data-point for histogram aggregations would be the squared deviations from the mean which could then be used to calculate the variance.

This is something that was dropped from OpenCensus -> OpenTelemetry.  Not entirely sure why, perhaps @jmacd has some insight here?

> Adding those 3 data points (min, max, squared deviations from the mean) would allow us to provide more information in for GCloud Monitoring (see Distribution)

As an FYI - I work on GCloud monitoring, so we're aware of this issue.   If you're having issues with Distributions from OTel, please let us know, or file a [bug here](https://github.com/googleCloudPlatform/opentelemetry-operations-java).

**Comment by jack-berg** [comment]
Since this issue was opened we've added [min and max](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/data/HistogramPointData.java#L31-L47) to histogram point data, per the spec. I'm inclined to close this issue since I've addressed how to answer percentile questions with a histogram, and since the inclusion of additional fields like variance and squared deviation from the mean would have to be added at the spec level before we could add them in the java implementation.

Please reopen if you feel otherwise.
