### ISSUE TITLE
InMemoryMetricReader vs InMemoryMetricExporter

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#3943]
The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/in-memory.md) defines the `InMemoryMetricExporter`, but does [not mention](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader-operations) anything like the `InMemoryMetricReader`.

Practically speaking, `InMemoryMetricReader` is a bit more useful for testing, since it allows you to collect all metrics ad hoc. However, you can accomplish the same thing with `InMemoryMetricExporter` (albeit with worse ergonomics) by calling flush on the: `SdkMeterProvider`, `PeriodicMetricReader` the `InMemoryMetricExporter` is associated with, or on `InMemoryMetricExporter` itself. 

`InMemoryMetricReader` is really closer to a [pull metric exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#pull-metric-exporter) like prometheus. Without a mention in the spec, should we remove `InMemoryMetricReader`?

On a related note, its strange and potentially incorrect that `InMemoryMetricExporter#flush()` forces the collection of metrics. The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#forceflush-1) says that flush should hint that the export of any metrics the exporter has received prior to the call should be completed as soon as possible, but in our case flush initiates a metric collect.

**Comment by jsuereth** [comment]
Sorry I didnt' comment here specifically.  The Specification *should* allow InMemory "reader" for pull-based testing and InMemory "push"-baed testing.   IF the current wording of the spec makes us remove InMemoryMetricReader, we need to go fix the spec.  That class is super important for testing.
