### ISSUE TITLE
[Autoconfigure] Allow to configure defaults for ConfigProperties via SPI

### ISSUE THREAD

**Issue by BerndFarkaDyna** [open-telemetry/opentelemetry-java#3944]
**Is your feature request related to a problem? Please describe.**
When using autoconfigure many things can be configured via SPI so the actual code doesn't get polluted. (for example ResourceProvider). It even is possible to share e.g. ResourceProviders between projects via dedicated jars. 

However, setting defaults needs to interact directly with the AutoConfiguredOpenTelemetrySdk API which should not be needed.

**Describe the solution you'd like**
Introduce DefaultPropertiesProvider which allows to set default values in the ConfigProperties via SPI.

**Comment by anuraaga** [comment]
Hi @BerndFarkaDyna - you should be able to use `AutoConfigurationCustomizerProvider` to set defaults via SPI. Does that work for you?

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizerProvider.java#L15

**Comment by BerndFarkaDyna** [comment]
I was looking for a dedicated SPI Provider for defaults and completly missed this one.

THX, this exactly what i wanted to have!
