### ISSUE TITLE
Allow setting trustedCertificatesPem in JaegerGrpcSpanExporterBuilder

### ISSUE THREAD

**Issue by pokusak** [open-telemetry/opentelemetry-java#3958]
Allow calling Jaeger collector which is protected by mTLS. (Agent uses parameters: --reporter.grpc.tls.cert and --reporter.grpc.tls.key to set security context which is used to call collector.)

It would be enough to expose method setTrustedCertificates from underlying delegate via JaegerGrpcSpanExporterBuilder.

**Comment by kyle-lt** [comment]
@jkwatson I can take a crack at this if it's still desired.  I haven't dug into it fully yet, but as the requestor calls out, it looks to be pretty easily achievable similar to the [OtlpHttpSpanExporterBuilder.setTrustedCertificates](https://github.com/open-telemetry/opentelemetry-java/blob/6933de18e5acfd5566ea1ca350c655e6c3f5a267/exporters/otlp-http/trace/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java#L82-L85) implementation.  The underlying GrpcExporterBuilder delegate [seems to support](https://github.com/open-telemetry/opentelemetry-java/blob/6f755cc8128f8077643b4990327c22b293c46e45/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/GrpcExporterBuilder.java#L27) this method.

**Comment by anuraaga** [comment]
Thanks @kyle-lt!
