### ISSUE TITLE
Expose Autoconfigure APIs

### ISSUE THREAD

**Issue by radcortez** [open-telemetry/opentelemetry-java#3959]
**Is your feature request related to a problem? Please describe.**
Right now, to configure `OpenTelemetry` you either build one with `OpenTelemetrySdkBuilder` or use the auto-configuration one with `OpenTelemetrySdkAutoConfiguration`. 

**Describe the solution you'd like**
It would be interesting if you could have something in between, where you would use the `OpenTelemetrySdkBuilder` combined with some of the private apis of the auto-configuration. The motivation is to be able to use all of the autoconfiguration features and configuration properties, but allow to further customize it for third-party libraries.

This could be achieved by turning `io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration#configureTracerProvider` into a public API and making it return the builder instead, so you could consume it. It may require exposing some other APIs as well like `io.opentelemetry.sdk.autoconfigure.PropagatorConfiguration#configurePropagators`.

**Comment by anuraaga** [comment]
@radcortez We've added an auto configuration builder recently which is meant for this use case, a library that uses autoconfiguration but with full customization of the auto configuration. It's used in the maven extension for example

https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/maven-extension/src/main/java/io/opentelemetry/maven/OpenTelemetrySdkService.java#L85

**Comment by radcortez** [comment]
@anuraaga sorry, I didn't notice this before. I was only looking into the released versions.

It should help. I'll explore the new API and see if something is missing. Thanks!
