### ISSUE TITLE
AutoConfiguration of the IdGenerator

### ISSUE THREAD

**Issue by radcortez** [open-telemetry/opentelemetry-java#3964]
**Is your feature request related to a problem? Please describe.**
Provide a way to set the`IdGenerator` with auto-configuration. Right now, this seems to be the only option from the `SdkTracerProviderBuilder` not exposed with auto-configuration.

**Describe the solution you'd like**
There are multiple ways to do this:
- Add the desired instance of the `IdGenerator` as a parameter in the `io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration#configureTracerProvider` and work the way up from there so it can be exposed.
- A new configuration property that takes the FQN of the `IdGenerator` to use
- ServiceLoader

**Additional context**
If you want to use the AWS `IdGenerator`, you need to manually set it up with the `TracerProvider`, but if you are using auto-configuration, you can only use the random default one.

**Comment by anuraaga** [comment]
Hi @radcortez - we currently have an SPI mechanism for that

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/traces/SdkTracerProviderConfigurer.java

It is indeed not on the builder though

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java

Is it correct that you'd like to see a similar knob on the builder? I think that would make sense

**Comment by radcortez** [comment]
> Is it correct that you'd like to see a similar knob on the builder? I think that would make sense

Yes, effectively to avoid having to go with the `SdkTracerProviderConfigurer` to set the `IdGenerator`, when everything else is available in the auto-configuration.

If we are ok with this, I'm happy to push a PR.

**Comment by jack-berg** [comment]
> Is it correct that you'd like to see a similar knob on the builder? I think that would make sense

Do we envision the `AutoConfiguredOpenTelemetrySdkBuilder` expanding and largely superseding the other SPIs that exist today?

**Comment by anuraaga** [comment]
@jack-berg Yeah I expect the builder to provide all the functionality of current SPIs for simpler usage. The SPI that takes the builder would be then the one SPI to rule them all though I don't think we'd deprecate anything.

**Comment by radcortez** [comment]
Very well, I'll be working on this. Thanks!
