### ISSUE TITLE
Why can't uppercase letters exist in tracestate

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java#3965]
I have tried and found if I add some uppercase letters in tracestate from http request header, it will get noting tracestate in the span. Is this a default hidden rule？

**Comment by jkwatson** [comment]
Our implementation is (or should be) based on the W3C specification here: https://www.w3.org/TR/trace-context/#key If there is something that differs from that spec, please let us know.

**Comment by tydhot** [comment]
@jkwatson  Thank you for your reply. I got it:)
