### ISSUE TITLE
Issue configuring endpoint for spans collector

### ISSUE THREAD

**Issue by LeonorLunatech** [open-telemetry/opentelemetry-java#3972]
**Describe the bug**
I am trying to setup tracing in a Scala application, using the java libraries.
I have a docker-compose with my application, an Otel-collector, Prometheus and Grafana.
By default the application tries to send spans to `http://localhost:4317`, but I need to configure it to send spans to `http://otel-collector:4317` instead and I have not been able to.

What am I missing?

**Steps to reproduce**

Code in the application:
```
  lazy val sdkTracerProvider: SdkTracerProvider = SdkTracerProvider
    .builder()
    .addSpanProcessor(BatchSpanProcessor.builder(OtlpGrpcSpanExporter.getDefault).build())
    .build()

  lazy val openTelemetry: OpenTelemetrySdk = OpenTelemetrySdk
    .builder()
    .setTracerProvider(sdkTracerProvider)
    .setPropagators(ContextPropagators.create(W3CTraceContextPropagator.getInstance()))
    .buildAndRegisterGlobal()

  implicit lazy val tracer: Tracer = openTelemetry.getTracer("my-application")

  val mySpan = tracer.spanBuilder("handling stuff").startSpan()
  try doStuff()
  finally mySpan.end
```

In docker-compose I have tried to setup several env variables like
```
OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
```
also 
```
-Dotel.exporter.otlp.traces.endpoint=http://otel-collector:4317
-Dotel.exporter.otlp.endpoint=[otel-collector:4320](http://otel-collector:4317)
```
But the values is ever picked up, I have tried to setup random ports like 4317 and the error message always mentions localhost:4317

**What did you expect to see?**
Successful log messages like (in otel-collector) `loggingexporter/logging_exporter.go:40	TracesExporter	{"#spans": 2}`

**What did you see instead?**
Error log messages `SEVERE: Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317`

**What version and what artifacts are you using?**
"io.opentelemetry" % "opentelemetry-api" % "1.9.1"
"io.opentelemetry" % "opentelemetry-sdk" %"1.9.1"
"io.opentelemetry" % "opentelemetry-exporter-otlp" % "1.9.1"

**Comment by jack-berg** [comment]
Those environment variables are only used if you're utilizing the [autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure) module to configure your SDK, which in java would look something like:
```
    OpenTelemetrySdk sdk = AutoConfiguredOpenTelemetrySdk.builder()
        .build()
        .getOpenTelemetrySdk();
```

If you're going to programmatically configure the SDK, as you've shown in your snippet, you need to explicitly set the endpoint:
```
    SdkTracerProvider sdkTracerProvider = SdkTracerProvider.builder()
        .addSpanProcessor(
            BatchSpanProcessor.builder(
                    OtlpGrpcSpanExporter.builder()
                        .setEndpoint("http://otel-collector:4317")
                        .build())
                .build())
        .build();
``` 
If you want to use env vars, its up to you to grab the endpoint from the appropriate environment variable and set it using the `OtlpGrpcSpanExporter` builder.

**Comment by LeonorLunatech** [comment]
Thank you for the quick reply!
Would you mind explaining what is the difference between using the autoconfigure module vs not using it? I have failed to understand that part so far

**Comment by yangtaoran** [comment]
AutoConfiguredOpenTelemetrySdk can autoconfigure the exporter by environment variables,which will read configuration parameters to set up OtlpGrpcSpanExporter.if not use it,you need init OtlpGrpcSpanExporter by program by youself in your application.

**Comment by jkwatson** [comment]
> FWIW, this is not [what the Javadocs on `OtlpGrpcSpanExporter.getDefault`](https://github.com/open-telemetry/opentelemetry-java/blob/60cc5f452a3609ce748441c6ad75cac471b35bfd/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java#L22-L29) would lead you to believe:
> 
> https://github.com/open-telemetry/opentelemetry-java/blob/60cc5f452a3609ce748441c6ad75cac471b35bfd/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporter.java#L22-L29
> 
> That's pretty confusing. Should the Javadoc be updated to indicate that the environment variables will only be used when the autoconfigure module is used?

Yes, this javadoc needs to be updated. Can you submit a PR to fix it? Thanks!
