### ISSUE TITLE
Tag RC and Milestone Releases as UNSTABLE or NIGHTLY

### ISSUE THREAD

**Issue by driverpt** [open-telemetry/opentelemetry-java#3997]
**Is your feature request related to a problem? Please describe.**
I have a script that automatically fetches latest version from GitHub Releases API and i noticed that 1.10.0-RC1 is marked as Latest and Stable Release, which is not correct.

**Describe the solution you'd like**
Tag RC and Milestone Releases as UNSTABLE or NIGHTLY

**Describe alternatives you've considered**
"Dark Magic" on Shell script

**Additional context**
N/A

**Comment by anuraaga** [comment]
Hi @driverpt - I guess you are referring to the GitHub release. This is a good callout - I have checked the box to mark it as a prerelease. Does that look ok now?

https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.10.0-rc.1

**Comment by driverpt** [comment]
Sorry, I forgot to mention that. It works now properly, thanks!
