### ISSUE TITLE
API: Consider removing TagMap.Builder.buildScoped()

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#400]
We removed `Span.Builder.buildScoped()`, as the try-with pattern made it hard to report errors on finished `Span`s. Out of uniformity we should consider removing this one too.

**Comment by bogdandrutu** [comment]
I understand that it does not have side effect but still if for example an exception is thrown and then logged (and assume we do have a log plugin where we dump the tags/dctx with every log statement) the newly added tags/entries will miss from that log statement (same problem with spans).

**Comment by carlosalberto** [comment]
Fine by me to remove it - we can add it later if actually needed.
