### ISSUE TITLE
API: Return Collection when iterating over TagMap's items.

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#401]
At this moment we return them as:

```java
Iterator<Tag> getIterator();
```

Lets consider changing it to:

```java
Collection<Tag> getItems(); // or similar name
```

**Comment by bogdandrutu** [comment]
I think collection is better because we can save an extra allocation (every time we need to create a new iterator). Also it is easier to use (size, iterator can be easily created, etc).

**Comment by bogdandrutu** [comment]
Do we have a decision here? I think nobody complained, anyone has an opinion about this?

**Comment by pavolloffay** [comment]
+1 on the collection.

**Comment by carlosalberto** [comment]
I'm fine with it as well. @yurishkuro anything against this one?

**Comment by yurishkuro** [comment]
Collection or Map?
