### ISSUE TITLE
One-to-many, many-to-one traceid relationships

### ISSUE THREAD

**Issue by xrom888** [open-telemetry/opentelemetry-java#4010]
**Is your feature request related to a problem? Please describe.**
We have a situation when service consume several messages from Kafka, each message has it's own traceId extracted from headers. In business logic we made grouping of messages (each has different traceId) in new message that will be sent to new topic. 

So the question if it possible to connect old traceids with new traceId created for new message?

Example:
Consumed messages:
1. Message 1, traceId=1.
2. Message 2, traceId=2.
3. Message 3, traceId=3.

Result message:
1. New Message,  traceId=New TraceId
ArraysList [
   - Message 1, rtaceId=1.
   - Message 2, rtaceId=2.
   - Message 3, rtaceId=3.
]

**Additional context**
We are looking for a way to connect traceIds, or alternative solution.

**Comment by kenfinnigan** [comment]
As we're restricted to a single parent for a span, the best option would be for **New Message** to `Link` to each of the three previous traces.

It would mean **New TraceId** then has a `Link` to traceId=1, traceId=2, and traceId=3

**Comment by xrom888** [comment]
Thanks for mentioning `Link`, will check how it works.
Thanks one more time.
