### ISSUE TITLE
Switch Jaeger remote sampler to "grpc" lite mechanism

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#4014]
**Is your feature request related to a problem? Please describe.**

This is required for https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4898#issuecomment-995178433

I am starting to work on this

**Comment by pavolloffay** [comment]
@anuraaga the remote sampler needs to get the response from the grpc service. So far the grpc lite mechanism is not parsing the response e.g. - https://github.com/open-telemetry/opentelemetry-java/blob/a1a45d2657468a6cd095b5e41c20dd67e3c577dc/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/GrpcExporter.java#L40

Any preferences how it should be done? I have started by defining `public interface GrpcService<REQ extends Marshaler, RES extends Marshaler> ` I don't have it working yet.

**Comment by anuraaga** [comment]
@pavolloffay `GrpcExporter` is an abstraction for exporting, but the actual stub is classes like these

https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/trace/src/main/java/io/opentelemetry/exporter/otlp/trace/MarshalerTraceServiceGrpc.java#L43

For the remote sampler, I don't think we need an additional abstraction should be able to use that type of class for the gRPC stub, and actually implement the RESPONSE_MARSHALER instead of returning a singleton.

**Comment by pavolloffay** [comment]
The issue is that we need logic from https://github.com/open-telemetry/opentelemetry-java/blob/a1a45d2657468a6cd095b5e41c20dd67e3c577dc/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/grpc/GrpcExporterUtil.java#L14 and `{OkHttp,Default}GrpcExporterBuilder` to make it all work.

an abstraction that would handle generic response type would be helpful.

**Comment by anuraaga** [comment]
I see - in that case the interface you mentioned does seem like a reasonable direction. I don't expect to need it outside the Jaeger sampler artifact though so if there is a solution that keeps things simpler without abstracting more than needed, we don't need to consider anything very general.

FWIW, I think we could consider making `setChannel` deprecated and a no-op, only having one implementation, unless we later got a complaint. I have a feeling in practice it's never used for the Jaeger sampler. But it is a bit risky, I would personally approve a PR that did that if you are up to it.
