### ISSUE TITLE
Identify classes that are Thread Safe vs not with Annotations

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java#402]
This might be over doing it, but do we want to have annotations on classes to indicate the expected "thread safetyness"?
For example: https://aalmiray.github.io/jsr-305/apidocs/javax/annotation/concurrent/package-summary.html

**Comment by bogdandrutu** [comment]
Yes I think we should use Immutable (implies ThreadSafe because nothing changes) and ThreadSafe annotations to identify these classes.

**Comment by tylerbenson** [comment]
Is this something that can be required in the checkstyle config?

**Comment by bogdandrutu** [comment]
Unfortunately not because the developer decides which classes are ThreadSafe or immutable. Or maybe I miss something.

**Comment by tylerbenson** [comment]
No, I mean having a checkstyle enforce the presence of one of those annotations... not verifying the accuracy of such declaration.
