### ISSUE TITLE
Prometheus Exporter Tests Should Cover for Async Counter (CounterObserver) Metrics and Async UpDownCounter (UpDownCounterObserver) metrics

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-java#4031]
While checking the consistency of the tests in the repository, the instruments Counter, Histogram, UpDownCounter, Gauge are tested and could see Async Counter (CounterObserver) and Async UpDownCounter (UpDownCounterObserver) are not tested. By following this [documentation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#default-aggregation) in order to support all the metrics. the tests for Async counter and Async UpDownCounter needs to be added.

**Comment by anuraaga** [comment]
@vasireddy99 since the current tests cover the four types of aggregations, isn't there already full coverage?

**Comment by vasireddy99** [comment]
Yeah Anuraag, Although four aggregations are covered, the instrument kind [Asynchronous Counter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-counter) and [Asynchronous UpDownCounter] (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-updowncounter) doesn't seems to be covered.

**Comment by anuraaga** [comment]
The exporters run on the aggregated values, not the raw instruments.

We tend to like precise code, including tests. If we add tests for async instruments, someone may later read them and wonder, does async and sync affect the exporter code? This would cause confusion.

Another issue is that the only time an async test would fail but not the sync one is if the aggregation code is problematic, not the Prometheus exporter. Promethean tests failing could cause someone to follow the red herring when debugging the problem. I suspect we have this sort of situation in tests already but not intentionally.

I think there's some confusion around how the exporters work, unless it is different in other languages which for this seems unlikely.

/cc @alolita @Aneurysm9

**Comment by Aneurysm9** [comment]
I think I agree with @anuraaga here that the tests for the exporter should be agnostic to the type of instrument that was used to create the aggregated values it is being asked to export.  If the current exporter tests are covering the range of aggregation types then I think that is sufficient.

**Comment by vasireddy99** [comment]
Thank you so much. Agreeing with comments. Closing the issue
