### ISSUE TITLE
Which package should processors live in

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4036]
The location of `LogProcessor`, `SpanProcessor`, and their implementations is inconsistent.

Locations of span processors are spread between `io.opentelemetry.sdk.trace` and `io.opentelemetry.sdk.trace.export`:

- `io.opentelemetry.sdk.trace.SpanProcessor` - public
- `io.opentelemetry.sdk.trace.NoopSpanProcessor` - package private
- `io.opentelemetry.sdk.trace.MultiSpanProcessor` - package private
- `io.opentelemetry.sdk.trace.export.BatchSpanProcessor` - public
- `io.opentelemetry.sdk.trace.export.SimpleSpanProcessor` - public

Locations of log processors are spread between `io.opentelemetry.sdk.logs` and `io.opentelemetry.sdk.logs.export`:

- `io.opentelemetry.sdk.logs.LogProcessor` - public
- `io.opentelemetry.sdk.logs.NoopLogProcessor` - package private
- `io.opentelemetry.sdk.logs.MultiLogProcessor` - package private
- `io.opentelemetry.sdk.logs.export.BatchLogProcessor` - public
- `io.opentelemetry.sdk.logs.export.SimpleLogProcessor` - public

Logs are inconsistent because I modeled them after traces. 

Was this arrangement in traces intention? Should the log SDK be similarly arranged for the sake of consistency, or get it right while it can? 

Potential solution: move the package private noop and multi processors to the `*.export` package. Means base interface lives in different package than implementations, but at least all implementations are together. Also is backwards compatible for traces while keeping logs and traces consistent.

**Comment by jkwatson** [comment]
I think this was done intentionally, or at least semi-intentionally. Why do you think it's a problem the way it is?

**Comment by anuraaga** [comment]
Agree the current structure is intentional - there are processors specific to exporting, with required *Exporter parameters when constructing them, but processors themselves are not an export concept. Noop / Multi are non-export related processors.

**Comment by jack-berg** [comment]
> there are processors specific to exporting, with required *Exporter parameters when constructing them, but processors themselves are not an export concept

I buy that explanation 👍. Just wanted to make sure that the layout makes sense before we double down on it with the logs.
