### ISSUE TITLE
Can I set AggregationTemporality.DELTA to OtlpJsonLoggingMetricExporter?

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java#4049]
```
    MetricExporter exporter = OtlpJsonLoggingMetricExporter.create();
    System.out.println(exporter.getSupportedTemporality()); //[DELTA, CUMULATIVE]
    System.out.println(exporter.getPreferredTemporality());  //null
```

**Comment by anuraaga** [comment]
Hi @chenjazz - this has been fixed at HEAD and is currently available in the 1.10 RCs. Would you be able to try them out to confirm your issue is fixed?

**Comment by chenjazz** [comment]
@anuraaga Thank you.
Another question:
When us CUMULATIVE, no metrics data to export,the value is return to original value. For Example:

```java
LongCounter counter = GlobalMeterProvider.get().get(INSTRUMENTATION_NAME).counterBuilder("work_done").build();
...
for (int i = 0; i < 15; i++) {
      Thread.sleep(1000);
      counter.add(1);
 }

```
result data is :  1 ,2,3,<No data>,1,2,3,4,<No data>...
Why not is:  1,2,3,4,5...15  ?

**Comment by anuraaga** [comment]
@chenjazz To confirm did you try out 1.10? I believe that was also fixed but will doublecheck if you're seeing it on the latest version

**Comment by jack-berg** [comment]
@chenjazz if you're using a delta exporter, then the data is reset each time a collection occurs such that only the difference in value is exported each interval.

**Comment by chenjazz** [comment]
@jack-berg 3q.
