### ISSUE TITLE
LogExporter export() contract should be ordered

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java#4057]
While I am a fan of the whole use-least-specific-type coding convention, I think that logs need to have a strong ordering guarantee. That is, the logs need to be exported in the same order that they are provided to the exporter, and the same order they are batched (assuming that the batch processor is used).

Currently, the [export method](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/LogExporter.java#L59) is:

`CompletableResultCode export(Collection<LogData> logs);`
and I think we should change it to 
`CompletableResultCode export(List<LogData> logs);`

We _could_ just add a note in the javadoc about iteration order being respected or something, but I think a stronger interface is warranted, and we can still do this before logs are stable, right?

I decided to open this as an issue rather than a PR directly in case folks have other opinions. If we like this, feel free to assign to me. Thanks.

**Comment by breedx-splk** [comment]
Also,[in the protobuf](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L68) the word "list" is used. 😁

**Comment by jkwatson** [comment]
Can you explain *why* it's important to have a strong ordering guarantee for log exports? There's no guarantee they'll be provided in strict temporal order to the exporter, given the multi-threaded nature of things that are generating logs, in general. 

Doesn't any logging backend need to account for out-of-order log delivery anyway, for all sorts of standard distributed computing reasons?

**Comment by breedx-splk** [comment]
> Can you explain _why_ it's important to have a strong ordering guarantee for log exports? There's no guarantee they'll be provided in strict temporal order to the exporter, given the multi-threaded nature of things that are generating logs, in general.

I consider logs to be a form of historical record of what happened some time in the past. A historical record without a consistent meaningful order is just chaos. The exporter is a key piece of the logs pipeline, and if it doesn't export records in the same order it was provided, I think we run the risk of confusing downstream components (backends, whatever) and making it difficult for users.

To me, an interface that takes `Collection` instead of `List` is really suggesting that the order of the incoming data doesn't matter. "Maybe it's ordered, maybe it's not...don't worry about it, we'll just pass it along and the order isn't important.". Seems wrong to me.

I believe and expect that logs will hit the exporter in the same order they were `emit()`ted. Even tho it's async, it's backed by a queue, which is DEFINITELY ordered, and the `BatchLogProcessor.Worker` keeps the batch as an `ArrayList`. Why/how would the order not be maintained to the exporter?

> Doesn't any logging backend need to account for out-of-order log delivery anyway, for all sorts of standard distributed computing reasons?

Maybe? Are there facilities in the data model to help a backend to do this? I don't remember seeing anything like that.

**Comment by jkwatson** [comment]
But, the timestamps on the logs themselves provide that ordering, correct? Not the order in which they were sent to an exporter.

**Comment by breedx-splk** [comment]
Sure, if you're trying to render stuff that came from a bunch of distributed systems and blend it together or work around something in your pipeline that doesn't maintain order, then yeah, the timestamps almost get you close. But for two logs that have the same timestamp, it sure would be useful to keep them in the same order.
