### ISSUE TITLE
Implement our own ThreadLocalRandom

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java#406]
The API should be compatible with older versions of Android, which haven't implemented some classes found in the standard JDK.  `ThreadLocalRandom` is one of these classes.

This new class should replace what is currently being used in `DefaultSpan` for ID generation.

Things to consider:
* Is there a backport we can use instead of creating our own?
* Separate seeds should be used for each thread to avoid duplicate id generation.
* Should be little to no lock contention across threads.

See further discussion in #404.

**Comment by kbrockhoff** [comment]
I suggest providing a strategy interface for id generation. Then a different approach could be used on Android. It would also help when coding for a particular backend system. An example would be AWS X-Ray which uses a 128 bit trace id and 64 bit span id like the defaults but the first 32 bits of the trace id is the Unix epoch seconds when the trace started. I am guessing they use the trace id as a sort key when storing in DynamoDB.

**Comment by adriancole** [comment]
fwiw in brave we dont have a strategy except 64 vs 128 bit. due to the AWS
issue mentioned we simply inherited their scheme. all of our 128 bit ids
are generated like that as no one had strong feelings otherwise. this has
been the case for at least a couple of years and no complaints I can recall
either.

**Comment by jkwatson** [comment]
`ThreadLocalRandom` is available in java 7, so this should be ok for the versions of Android we're targeting, correct?

**Comment by jkwatson** [comment]
nevermind. I see that it's not valid for android 14, even though it's in java 7.  :(
