### ISSUE TITLE
run examples with the latest snapshot jar [just question]

### ISSUE THREAD

**Issue by zbhuang2008** [open-telemetry/opentelemetry-java#4060]
Right now examples are using 1.9.1, and the main branch is in 1.10.0-SNAPSHOT.
When is the next release (such that examples will use 1.10.0) ?
or where can I see the release plan, I mean the link/url of the release plan ?
Thanks.

**Comment by jkwatson** [comment]
We're planning on releasing 1.10.0 this week, probably tomorrow. This sort of thing is generally captured in the meeting notes for our public SIG meetings.

Examples should be updated shortly after release to point at the latest released version.

**Comment by zbhuang2008** [comment]
Nice, thanks.
