### ISSUE TITLE
Looking for some suggestion

### ISSUE THREAD

**Issue by zbhuang2008** [open-telemetry/opentelemetry-java#4062]
Hi,
I am writing to see someone can give me some suggestions.
Here is what I want to do - use open telemetry to collect the raw log files from different locations, then send it over to the backend (which is already implemented in java for further process).

So far, what I found is - the following example has done the first part of the work, collecting the log files, but it is implemented in go.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/kubernetes
So my next step is to figure out how to receive the log file from the collector, which I have not figured it out yet.

I went through the examples on opentelemetry-java side, but did not find similar one (let me know if java side does have, but I just missed it). I also notice that there are exporter implementation on opentelemetry-java side.

So the diagram I have right now is like this -

log file1--|
log file2--|
....................|--->|collector| ---> |exporters|--->...
log filen--|

1)Right now, I am a little bit confused about whether I need exporters or not ?
2)how java side can receive the log file ?

Hope someone can help point out the direction or share some information.
Thanks.

**Comment by jkwatson** [comment]
This isn't really something that the OpenTelemetry language SDKs are intended to support. You might be able to implement something like this from the components in the java SDK, but it's definitely not something that we're intended on supporting as a core component.

**Comment by zbhuang2008** [comment]
Just want to know the reason why it is not. 
Do you mind elaborating a little bit more ? or share with the link that I can check ?

"OpenTelemetry is a collection of tools, APIs, and SDKs. Use it to instrument, generate, collect, and export telemetry data (metrics, logs, and traces) to help you analyze your software’s performance and behavior."
And note that log data is one of them, and it can be used to analyze the behavior.
And also the above collector-contrib project, it provides such an example.

or do you mean it is NOT now ?

Thanks.

**Comment by zbhuang2008** [comment]
Thanks  @jkwatson and @kenfinnigan
