### ISSUE TITLE
Meter-API Summary support. 

### ISSUE THREAD

**Issue by tjiuming** [open-telemetry/opentelemetry-java#4075]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I noticed that there are no `Summary` support in `Meter` yet, according to this 'feature', if I want to collect `Summary` metrics by using open-telemetry, what should I do? I didn't find any examples in tests.

Waiting for your reply.
Thanks.

**Comment by pirgeo** [comment]
As far as I am aware, `Summary` is only part of the data model (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#summary-legacy), and is marked as Legacy there. It only exists for Prometheus compatibility (i.e., it is possible to transport Prometheus data via OTLP), and is not intended to be used for any other purpose. Therefore, there is no API available for it here.

**Comment by tjiuming** [comment]
> As far as I am aware, `Summary` is only part of the data model (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#summary-legacy), and is marked as Legacy there. It only exists for Prometheus compatibility (i.e., it is possible to transport Prometheus data via OTLP), and is not intended to be used for any other purpose. Therefore, there is no API available for it here.

Got it, thanks for ur reply~
