### ISSUE TITLE
OpenCensus Datadog Exporter

### ISSUE THREAD

**Issue by mattstep** [open-telemetry/opentelemetry-java#4077]
**Is your feature request related to a problem? Please describe.**
OpenCensus includes an exporter for DataDog traces. It would be ideal if we could just get the same functionality in OpenTracing without having to use DataDog's java agent.

**Describe the solution you'd like**
Can the OpenCensus trace exporter be brought over to the OpenTelemetry project as it's now being merged into one project https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/trace/datadog ?

**Describe alternatives you've considered**
DataDog provides this functionality in their own java agent, but this agent brings along some unfortunate side-effects such as the JFR instrumentation and automatic instrumentation that involves some amount of byte code manipulation. This is mostly an awesome feature that makes it easy to integrate with, but some very high-performance java applications (such as the Trino project) that rely heavily on a predictable JIT are not compatible with this model.

**Comment by jkwatson** [comment]
In general, we don't host vendor-specific exporters for the SDK. That is the responsibility of DataDog to create and host. Please reach out to them for this, as we won't be maintaining that code here.

**Comment by mattstep** [comment]
I'm confused as the OpenCensus project did host that code and has been folded into OpenTelemetry.  Is the OpenCensus DataDog exporter now derelict?

**Comment by mattstep** [comment]
It seems for rust there is support for DataDog. https://github.com/open-telemetry/opentelemetry-rust/tree/main/opentelemetry-datadog

**Comment by anuraaga** [comment]
OpenTelemetry is a reimagining of OpenCensus but components aren't automatically copied over. It would be possible to have a datadog exporter in the [java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib) repo but definitely not in this SDK one. But we would expect it to be actually maintained, meaning two datadog members taking active ownership of such a component - the OpenTelemetry Java maintainers wouldn't create such a vendor-specific component. So it still stands that you'd need to reach out to datadog on whether they are interested in implementing and owning this.

**Comment by jkwatson** [comment]
Closing this issue, as this is not something we'll support here. Please contact DataDog for support for this. Thanks!
