### ISSUE TITLE
How to know OpenTelemetry had initialized

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-java#4110]
https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L86
Here, I can set global OpenTelemetry. But I want to konw the set had invoked. I set global OpenTelemetry if it is not set, otherwise, I am not.
https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L55
If I using above `get` to judge, but it will set default OpenTelemetry to global. And then it will throw exception when I set my OpenTelemetry.
So, there are any method to judge global OpenTelemetry  had initialized before I set?

**Comment by jkwatson** [comment]
There isn't a way to know. And, in fact, we strongly recommend that you don't utilize the `GlobalOpenTelemetry` class at all unless you have a very strong reason for it. You should, in our opinion, prefer using an instance of `OpenTelemetry` to avoid these sorts of initialization order issues.

**Comment by jack-berg** [comment]
Closing. This was partially addressed in #4223 and we don't plan on providing tooling to know if `GlobalOpenTelemetry#set` has been called.
