### ISSUE TITLE
Adjust tracer provider customizer execution order and add metric/log provider customizer

### ISSUE THREAD

**Issue by wallezhang** [open-telemetry/opentelemetry-java#4121]
**Is your feature request related to a problem? Please describe.**
I think the tracer provider customizer should be executed at the last step, so users can modify the auto configured fields. For example, if I want to set different resource to different provider. And I suggest expose metric provider customizer and log emitter provider customizer.

**Comment by anuraaga** [comment]
Hi @wallezhang - can you describe your use case for "if I want to set different resource to different provider."? We would generally never expect traces, metrics, and logs to have different resources in the same app.

**Comment by wallezhang** [comment]
> Hi @wallezhang - can you describe your use case for "if I want to set different resource to different provider."? We would generally never expect traces, metrics, and logs to have different resources in the same app.

For some historical reasons, log and trace have to use different resource, but this is not important. Actually, what I want to express is that the execution order of trace provider customizer (or maybe metric provider customizer) should be at the last step of initialization, which can give users more customization.

**Comment by wallezhang** [comment]
So, if this feature request is reasonable, I can submit a PR to adjust the execution order of trace provider customizer.

**Comment by anuraaga** [comment]
Thanks @wallezhang, executing the customizers last so they can have the final say seems reasonable to me, a PR would be great

**Comment by wallezhang** [comment]
Ok, I'm working on it.
