### ISSUE TITLE
Deprecate configurable exporter providers

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4149]
Now that `AutoConfigurationCustomizer` exists, I think we should deprecate [ConfigurableMetricExporterProvider](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/metrics/ConfigurableMetricExporterProvider.java), and [ConfigurableSpanExporterProvider](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/traces/ConfigurableSpanExporterProvider.java).

Their usefulness has diminished quite a bit now that you can directly add your own span processor / metric reader with whatever exporter you want. Only value remaining is being able to take advantage of autoconfiguration options for BSP / PMR, which isn't much.

**Comment by anuraaga** [comment]
The `Configurable*` is to add a component that can be enabled by name, e.g. packaging into distros, e.g. a distro that allows a user to set `OTEL_PROPAGATORS=xray`. I don't think these overlap with our other customizers since they don't do customizing, just provide a new option

**Comment by jack-berg** [comment]
That makes sense, but doesn't that suggest that this should be part of the agent extension API?

**Comment by anuraaga** [comment]
An agent distro is common use but it doesn't have to be. You can imagine a server framework that depends on multiple propagators giving the user a choice, even if it's not a javaagent.

**Comment by jack-berg** [comment]
That makes sense. I'm convinced!
