### ISSUE TITLE
AbstractMethodError crash on Android 

### ISSUE THREAD

**Issue by ber4444** [open-telemetry/opentelemetry-java#4161]
**Describe the bug**
 ```
java.lang.AbstractMethodError: abstract method "void io.opentelemetry.api.common.Attributes.forEach(j$.util.function.BiConsumer)"
at io.opentelemetry.exporter.zipkin.ZipkinSpanExporter.generateSpan(SourceFile:39)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at io.opentelemetry.exporter.zipkin.ZipkinSpanExporter.export(SourceFile:3)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at na.g0$c.export(SourceFile:1)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at na.j.export(SourceFile:10)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at na.s0.export(SourceFile:18)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at na.l0.export(SourceFile:15)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(SourceFile:3)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(SourceFile:8)
02-07 16:14:48.698 13877 13916 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

**Steps to reproduce**
Run sample Android app with the Splunk SDK that uses OpenTelemetry. 

**What did you expect to see?**
No crash

**What did you see instead?**
Crashes as the Splunk SDK initializes.

**What version and what artifacts are you using?**
Artifacts: https://github.com/signalfx/splunk-otel-android
Version: com.splunk:splunk-otel-android:0.12.0, seems to be using opentelemetry 1.6.0
How did you reference these artifacts? [(excerpt from your `build.gradle`, `pom.xml`, etc)](https://github.com/signalfx/splunk-otel-android/blob/97bdf58966bf878f555823ad0bb5ad4b0f3caa44/splunk-otel-android/build.gradle#L46)

**Environment**
OS: Android 10
Only happens in release mode (proguard rules likely incomplete... what they shipped is https://github.com/signalfx/splunk-otel-android/blob/9d51a1feffb765a741463fb15d59555af354e2b6/splunk-otel-android/consumer-rules.pro)
We are using AGP 7.1.0 and minSdk = 23

**Comment by jkwatson** [comment]
I believe there is a bug with desugaring with AGP 7.1.0. See this bug that I logged many months ago with the Android team: https://issuetracker.google.com/issues/202188674

Can you downgrade to AGP 4.1.2 and see if that fixes the issue?

**Comment by ber4444** [comment]
We cannot downgrade as we use jetpack compose and the issue you linked to is specific to API level 21 while we have minsdk 23.

**Comment by jkwatson** [comment]
> We cannot downgrade as we use jetpack compose and the issue you linked to is specific to API level 21 while we have minsdk 23.

I found that issue at API 21, but it also occurs at 23. This is definitely a real bug in the AGP that breaks core-library desugaring.

**Comment by ber4444** [comment]
This is working without desugaring as long as we run on API >= 26. (E.g. API 23 would crash with ` java.lang.NoClassDefFoundError: io.opentelemetry.api.common.a at io.opentelemetry.api.common.ArrayBackedAttributes.<clinit>(SourceFile:1)`, while API 24 would crash with ` java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration`).

**Comment by jkwatson** [comment]
@ber4444 Please please please comment on that google ticket that I logged. We really need the Android team to fix this AGP bug, and they won't do it without people saying that they need it.

Why won't jetpack-compose work with a 4.x AGP version?

**Comment by laurit** [comment]
I believe the issue is that desugaring handles calls to `Map.forEach(j.u.f.BiConsumer)` by rewriting the call site, but it does not handle calling `Attributes.forEach(j.u.f.BiConsumer)` on an `Attributes` implementation that extends `HashMap` and inherits `forEach` from `HashMap`. We have 2 such implementations: `AttributesMap` and `UnsafeAttributes` in javaagent repo. I guess handling such construct is a bit too much for desugaring, it can't be handled by call site rewriting. To fix it I see two options, either don't extend `HashMap` and use an internal map or provide implementation for `forEach`.
Note that desugaring does not handle calls to `HashMap.forEach(j.u.f.BiConsumer)` and https://developer.android.com/studio/write/java8-support-table does not list it as an API available through desugaring. I guess this is an oversight from android developers, they probably didn't anticipate that `HashMap` has a custom `forEach` implementation. Event if they did handle `HashMap.forEach(j.u.f.BiConsumer)` the same way as `Map.forEach(j.u.f.BiConsumer)` I doubt it would help here.

**Comment by anuraaga** [comment]
@laurit Thanks for the digging! Does implementing in the subclass just calling `super` work? That seems pretty simple

**Comment by laurit** [comment]
@anuraaga yes, just calling super works
```
  @Override
  public void forEach(BiConsumer<? super AttributeKey<?>, ? super Object> action) {
    super.forEach(action);
  }
```
gets transformed to
```
  public void forEach(j$.util.function.BiConsumer<? super io.opentelemetry.api.common.AttributeKey<?>, ? super java.lang.Object>);
    descriptor: (Lj$/util/function/BiConsumer;)V
    Code:
       0: aload_0
       1: aload_1
       2: invokestatic  #85                 // Method j$/util/Map$_CC.$default$forEach:(Ljava/util/Map;Lj$/util/function/BiConsumer;)V
       5: return

  public void forEach(java.util.function.BiConsumer);
    descriptor: (Ljava/util/function/BiConsumer;)V
    Code:
       0: aload_0
       1: aload_1
       2: invokestatic  #92                 // Method j$/util/function/BiConsumer$VivifiedWrapper.convert:(Ljava/util/function/BiConsumer;)Lj$/util/function/BiConsumer;
       5: invokevirtual #94                 // Method forEach:(Lj$/util/function/BiConsumer;)V
       8: return
```
