### ISSUE TITLE
Vararg versions of AttributeBuilder.put(AttributeKey<List<?>>)

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#4172]
We currently have vararg versions of AttributesBuilder put methods that accept a string key

https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/common/AttributesBuilder.java#L96

But we don't have similar for `AttributeKey`. This means that you can't take code that uses a vararg String key and "optimize it" by replacing the key with `AttributeKey`, you currently need to also add `Arrays.asList`. I think having symmetry here would be good.

**Comment by gcatanese** [comment]
@anuraaga Happy to have a look if that's ok

**Comment by anuraaga** [comment]
Thanks @gcatanese assigned the issue

**Comment by gcatanese** [comment]
Addressed in PR #4188
