### ISSUE TITLE
JPMS and prometheus exporter

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#4192]
From @laurit's https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5408#issue-1144660181

> Note that when using jpms user will need to use --add-modules jdk.httpserver so it would be best if prometheus exporter did not use these classes.

Short of documenting it (e.g. [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#prometheus-exporter)), wondering (as @laurit mentioned) if we can get rid of the dependency on `com.sun.net.httpserver`.

org.apache.hc.core5.http.impl.bootstrap.HttpServer in `org.apache.httpcomponents.core5:httpcore5` looks reasonable (actively developed, no transitive dependencies, 831 kb, may be worth shading into the prometheus exporter to avoid conflicts, especially since this is in an `impl` package doesn't give much confidence in API stability).

**Comment by anuraaga** [comment]
For reference found upstream issue indeed doesn't seem to have been resolved

https://github.com/prometheus/client_java/issues/533

httpcore seems like a reasonable option

**Comment by anuraaga** [comment]
Though I wonder if providing a real module-info file with a declaration on `jdk.httpserver` is also an option
