### ISSUE TITLE
API: `record` should take a generic `Attachment` class instead of having tracing dependency.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-java#421]
See https://github.com/open-telemetry/opentelemetry-java/blob/70a7ce19d48b978c333f196a0f0a32af134b2a23/api/src/main/java/io/opentelemetry/metrics/Meter.java#L194

It would be problematic for `Metrics` APIs to depend on `Tracing`, and that's why we added the [`AttachmentValue`](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/metrics/data/AttachmentValue.java) class in OpenCensus-Java.

**Comment by SergeyKanzhelev** [comment]
Probably need to file it in specs first

**Comment by bogdandrutu** [comment]
This is how it was in OpenCensus, and because this is not available anywhere I think we are fine. But happy to to it in specs.

**Comment by bogdandrutu** [comment]
@songy23 do we have a specs issue/pr for this?

**Comment by songy23** [comment]
Spec: https://github.com/open-telemetry/opentelemetry-specification/issues/144

**Comment by bogdandrutu** [comment]
Obsolete
