### ISSUE TITLE
Add otel.java.enabled.resource.providers config key

### ISSUE THREAD

**Issue by wallezhang** [open-telemetry/opentelemetry-java#4220]
**Is your feature request related to a problem? Please describe.**
In my case, I only need a few resource fields while so many resource fields are auto configured. More resource fields mean more storage space, and these fields don't care for my scenario.
I can only disable these auto configured resource fields by setting `otel.java.disabled.resource.providers` config. However there are too many `ResourceProvider` implementations I want to disable.

**Describe the solution you'd like**
I want to add a config key `otel.java.enabled.resource.providers` that just configure `ResourceProvider` what I want to enable. Enabled resource providers configuration takes precedence over disabled configuration.
If the enabled config key is not configured, all resource providers will be enabled.

**Comment by jkwatson** [comment]
This seems like a reasonable request to me.

**Comment by wallezhang** [comment]
I will try to submit a PR adding this configuration.
