### ISSUE TITLE
Security in Prometheus exporter

### ISSUE THREAD

**Issue by fmhwong** [open-telemetry/opentelemetry-java#4230]
**Is your feature request related to a problem? Please describe.**
When using the automatic instrumentation opentelemetry-javaagent.jar and the Prometheus exporter is enabled, the metrics endpoint (e.g. http://localhost:9464) is not protected.

**Describe the solution you'd like**
There should be an option to use https and have the metrics endpoint protected by 
- username/password
- OpenShift service account token

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anuraaga** [comment]
Hi @fmhwong - could you file an issue in the spec repo about adding details on configuring prometheus exporter?

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/prometheus.md

https://github.com/open-telemetry/opentelemetry-specification/issues

It will be good to have more details on what we need to add in the spec for prometheus export so all the languages expose the features users need.

**Comment by fmhwong** [comment]
Opened https://github.com/open-telemetry/opentelemetry-specification/issues/2400
