### ISSUE TITLE
Make `io.opentelemetry.exporter.prometheus.MetricAdapter` public

### ISSUE THREAD

**Issue by edwardxia** [open-telemetry/opentelemetry-java#4262]
**Is your feature request related to a problem? Please describe.**
We have an internal library that support exporting `io.prometheus.client.Collector.MetricFamilySamples.Sample` to our in house metrics system. In order to write a custom exporter, we need `io.opentelemetry.exporter.prometheus.MetricAdapter.toSamples()` to be public accessible.

**Describe the solution you'd like**
Make `io.opentelemetry.exporter.prometheus.MetricAdapter` public. Some other metric adapters are already public, I don't see issue making this public as well.

**Describe alternatives you've considered**
https://github.com/open-telemetry/opentelemetry-java/issues/4071, however, the proposed solution in the linked issue is being deprecated so it is not a viable choice anymore.

**Comment by anuraaga** [comment]
Hi @edwardxia - I will actually be removing that class fairly soon. It would sound like you may want to write an adapter directly from OpenTelemetry `MetricData` to your internal format, but if in the meantime you need this conversion code it is probably best to copy it into your codebase. We don't want to commit to supporting an API that converts to the format of a different library.
