### ISSUE TITLE
io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans

### ISSUE THREAD

**Issue by GarikVologodskiy** [open-telemetry/opentelemetry-java#4279]
Hello!

Use javaagent version 1.12.1 but get an error when exporting. But everything is OK with the agent version 0.7.0
Export to jaeger

Could you help me please?

**error**
io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317

#!/bin/bash

[ -z "$JAVA_XMS" ] && JAVA_XMS=2048m
[ -z "$JAVA_XMX" ] && JAVA_XMX=2048m

set -e

JAVA_OPTS="${JAVA_OPTS} \
  -Xms${JAVA_XMS} \
  -Xmx${JAVA_XMX} \
  -Dapplication.name=${APP_NAME} \
  -Dapplication.home=${APP_HOME} \
  -Dotel.exporter=jaeger \
  -Dotel.jaeger.endpoint=jaeger-all-in-one:14250 \
  -Dotel.jaeger.service.name=spring-boot-rest-service \
  -javaagent:${APP_HOME}/opentelemetry-javaagent-all.jar"

exec java ${JAVA_OPTS} \
  -jar "${APP_HOME}/${APP_NAME}.jar" \
  --spring.config.location=/config/application.yml

**Jaeger**
jaeger-all-in-one:
image: "jaegertracing/all-in-one:latest"
ports:
- 5775:5775/udp
- 6831:6831/udp
- 6832:6832/udp
- 5778:5778
- 16686:16686
- 14268:14268
- 14250:14250

**Comment by trask** [comment]
hi @GarikVologodskiy! 4317 is default otlp port, so it sounds like it's trying to export using otlp instead of jaeger.

I think you need to use `otel.traces.exporter` instead of `otel.exporter`, check out https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#jaeger-exporter

(I believe this changed at some point in the past, which is why `otel.exporter` probably used to work for you)

**Comment by GarikVologodskiy** [comment]
> otel.traces.exporter

Hello @trask ! Thank you so much!

But now I'm getting another error. Probably because of my jaeger instance..

SpringBootRestService_1  | [otel.javaagent 2022-03-20 05:54:59:007 +0000] [OkHttp http://localhost:14250/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:14250

**Comment by kushal-ti** [comment]
hi, did you manage to solve this, i'm facing the same issue

**Comment by kushal-ti** [comment]
I think i know what the problem was on my end and i suspect it's the same issue for @GarikVologodskiy 
It was a networking problem. I had the jaeger server running in one docker container and the spring boot server in another.
For the spring boot server to connect to jaeger, the JVM options should be modified to 
-Dotel.exporter.jaeger.endpoint=http://jaeger:14250/ (jaeger is the name of the container, substitute it with whatever is the name for your container)
the reason it was working with version 0.7 is because that version accept jaeger:14250 as a valid endpoint, whereas the newer version expects the end point to begn with http/s leading me (and i suspect @GarikVologodskiy) to use http://localhost:14250 which leads to the spring boot server trying to connect to it's own localhost:14250 and not the jaeger server's port

**Comment by manvitha9347** [comment]
[otel.javaagent 2022-04-27 17:44:59:056 +0530] [OkHttp http://localhost:55680/...] ERROR io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Required SETTINGS preface not received

i am getting this error with the following vars:
-javaagent:C:\opentelemetry-javaagent.jar 
-Dotel.metrics.exporter=none 
-Dotel.traces.exporter=otlp
-Dotel.exporter.otlp.traces.endpoint=http://localhost:55680
-Dotel.resource.attributes="service.name=myotelapp"

and
[otel.javaagent 2022-04-27 17:48:25:570 +0530] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317

with vars as:
-javaagent:C:\opentelemetry-javaagent.jar 
-Dotel.metrics.exporter=none 
-Dotel.traces.exporter=otlp
-Dotel.exporter.otlp.traces.endpoint=http://localhost:4317
-Dotel.resource.attributes="service.name=myotelapp"


what ever the error is, if i try to print trace_id in my log lines,the trace_id is getting printed in logs 

how can i resolve this?
@GarikVologodskiy @trask @kushal-ti

**Comment by trask** [comment]
hi @GarikVologodskiy, I'd recommend opening a new discussion in https://github.com/open-telemetry/opentelemetry-java-instrumentation

**Comment by tejeswar-komma** [comment]
> manvitha9347

Hi @manvitha9347, I am also facing the same issue. Did you get the resolution for this issue?

**Comment by manvitha9347** [comment]
> > manvitha9347
> 
> Hi @manvitha9347, I am also facing the same issue. Did you get the resolution for this issue?

Hi @tejeswar-komma you need to have a service running at 4317 port 
This is the service to which you want to export the traces
I my case I am using an grafana agent
So when I started the grafana agent first,this error didn't appear again

**Comment by tejeswar-komma** [comment]
> > > manvitha9347
> > 
> > 
> > Hi @manvitha9347, I am also facing the same issue. Did you get the resolution for this issue?
> 
> Hi @tejeswar-komma you need to have a service running at 4317 port This is the service to which you want to export the traces I my case I am using an grafana agent So when I started the grafana agent first,this error didn't appear again

I want to use the OpenTelemetry Collector to collect the traces and then transport them to AppDynamics backend. I have few queries. 
1. Is OpenTelemetry Collector available within the Opentelemetry Java agent? or Should I download and run the OpenTelemetry Collector along with my service.
2. In your query, you are exporting the traces to OTLP "-Dotel.traces.exporter=otlp" which means that you are exporting the traces to the OpenTelemetry Collector. why are you running Grafana at the 4317 port?

**Comment by jeicy07** [comment]
> 

Hi [tejeswar-komma](https://github.com/tejeswar-komma), I am also facing the same issue. Did you get the resolution for this issue?

**Comment by jeicy07** [comment]
> > > > manvitha9347
> > > 
> > > 
> > > Hi @manvitha9347, I am also facing the same issue. Did you get the resolution for this issue?
> > 
> > 
> > Hi @tejeswar-komma you need to have a service running at 4317 port This is the service to which you want to export the traces I my case I am using an grafana agent So when I started the grafana agent first,this error didn't appear again
> 
> I want to use the OpenTelemetry Collector to collect the traces and then transport them to AppDynamics backend. I have few queries.
> 
> 1. Is OpenTelemetry Collector available within the Opentelemetry Java agent? or Should I download and run the OpenTelemetry Collector along with my service.
> 2. In your query, you are exporting the traces to OTLP "-Dotel.traces.exporter=otlp" which means that you are exporting the traces to the OpenTelemetry Collector. why are you running Grafana at the 4317 port?

Hi @manvitha9347, I am also facing the same issue. Did you get the resolution for this issue?

**Comment by pourgholi** [comment]
> @trask , @kushal-ti thank you so much indeed! The problem has been solved. OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250

Documentation is here:  https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-span-metric-and-log-exporters

**Comment by ziyoushibo** [comment]
> Hi, I'm also having the same issue:
> 
> after running the curl command.
> 
> <img alt="image" width="671" src="https://user-images.githubusercontent.com/121836290/210704287-b2578632-e244-46fa-8f5e-2e8089676961.png">
> 
> and this what happens of microservice:
> 
> <img alt="image" width="760" src="https://user-images.githubusercontent.com/121836290/210703743-f580a4e2-60ef-47c5-b1c5-5b56eb274fd6.png">
> 
> and this current value of run-microservice file: `mvn clean package -Dmaven.test.skip=true AGENT_FILE=opentelemetry-javaagent-all.jar
> 
> if [ ! -f "${AGENT_FILE}" ]; then curl -L https://github.com/aws-observability/aws-otel-java-instrumentation/releases/download/v1.19.2/aws-opentelemetry-agent.jar --output ${AGENT_FILE} fi
> 
> export OTEL_TRACES_EXPORTER=otlp export OTEL_METRICS_EXPORTER=otlp export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:5555 export OTEL_RESOURCE_ATTRIBUTES=service.name=hello-app,service.version=1.0
> 
> java -javaagent:./${AGENT_FILE} -jar target/hello-app-1.0.jar`
> 
> and this is the value of collector-config-local.yaml
> 
> `receivers: otlp: protocols: grpc: endpoint: 0.0.0.0:5555
> 
> exporters: logging: loglevel: debug
> 
> service: pipelines: metrics: receivers: [otlp] exporters: [logging] traces: receivers: [otlp] exporters: [logging] `

do you have solutions now?
