### ISSUE TITLE
Don't force reliance on Prometheus HTTP Server

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-java#4284]
👋🏼 https://github.com/open-telemetry/opentelemetry-java/pull/4185 As it seems there's a desire for feedback on this.
My first inclination is that mandating a particular HTTP server is restrictive. By limiting consumption of the MetricReader to the Prometheus Collector anyone using alternative HTTP Frameworks can easily keep their applications integrated. 
This is actually my usecase 😓

_Originally posted by @hdost in https://github.com/open-telemetry/opentelemetry-java/discussions/4235#discussioncomment-2297369_

**Comment by anuraaga** [comment]
Hi @hdost - sorry for missing this issue from so many months ago. While the built-in server is meant to be easy to get going, I agree that being able to use a different HTTP framework is good, and is what I'd do in my apps too. We'd probably want to add a `byte[] serialize` type of method instead of encoding into a collector for that use case, which allows using our optimized serialization code. Would that satisfy your use case?

**Comment by hdost** [comment]
@anuraaga I guess that depends, I would need to think a bit more as potentially there might be selectors which could be useful. Especially as there may be potential want/need in the future to export in Protobuf Prometheus Format for [Sparse Histograms](https://docs.google.com/document/d/1cLNv3aufPZb3fNfaJgdaRBZsInZKKIHo9E6HinJVbpM/edit#heading=h.9mzwd6fune1b)

**Comment by anuraaga** [comment]
Thanks for the context @hdost - my understanding was that OTel settled on the text protocol for Prometheus via the push there in OpenMetrics. If there is community consensus for supporting protobuf as well, then we would definitely need to add support for marshaling it here too.

**Comment by hdost** [comment]
After talking internally I could also be desirable to make it more compatible with explicit parameter by being able to pass in a registry

**Comment by jack-berg** [comment]
Take a look at [opentelemetry-java-contrib#660](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/660), which adds `PrometheusCollector` as a published component in `opentelemetry-java-contrib`. It could use another maintainer if @hdost or @nicu-da are interested.

**Comment by jack-berg** [comment]
I'm going to close this now that [opentelemetry-java-contrib#660](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/660) is merged. If that is still insufficient, we can reopen this issue to discuss options for adding a `byte[] serialize` method to allow use with other HTTP servers.

**Comment by hdost** [comment]
Thank you 🙏
