### ISSUE TITLE
Add retry to OtlpHttpSpanExporter

### ISSUE THREAD

**Issue by joske1234** [open-telemetry/opentelemetry-java#4291]
**Is your feature request related to a problem? Please describe.**
(Experimental) retry was added in release 1.11.0 but OtlpHttpSpanExporter does not support setting a retry yet.

**Describe the solution you'd like**
Retries should be configurable in the OtlpHttpSpanExporterBuilder, best solution is to allow setting a RetryPolicy.

**Describe alternatives you've considered**
We could switch to the grpc exporter that allows configuring retries on it's managed channel, however that is marked as deprecated so it is not a long term solution.

**Comment by joske1234** [comment]
Thanks Jack that seems like a good workaround, I'll try it.

**Comment by jack-berg** [comment]
I'm going to close this issue for now. Feel free to comment or re-open if you have additional feedback.
