### ISSUE TITLE
Better support for OTLP header authentication

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4292]
The OTLP exporter builders have `addheader(String key, String value)` for adding static headers, but header based authentication often requires that the header value be refreshed over time.

The OTLP exporter builders should be enhanced to allow for more header based authentication scenarios. 

Originally discussed in [#4165](https://github.com/open-telemetry/opentelemetry-java/issues/4165#issuecomment-1039160038).

Related to spec issue [#1344](https://github.com/open-telemetry/opentelemetry-specification/issues/1344).

**Comment by jack-berg** [comment]
Resolved in #4630.

**Comment by jack-berg** [comment]
The internal API can be used, but is subject to change. Its effectively an experimental API. To use, do something like:
```
OtlpHttpSpanExporterBuilder builder = OtlpSpanExporter.builder()
  .setEndpoint(...);
Authenticator.setAuthenticatorOnDelegate(builder, () -> Map.of("header-key", "header-value"));
OtlpHttpSpanExporter exporter = builder.build();
```
If you want to discuss promoting the API to be public facing and stable, please open a new issue.

**Comment by GerardPaligot** [comment]
I thought so too but it's not. `setAuthenticatorOnDelegate` checks that the builder is typed by `OkHttpExporterBuilder` (or `GrpcExporterBuilder` but throw an exception if it is the case). This class isn't extended by `OtlpHttpSpanExporterBuilder` but use internally to build the http client.

New issue created here: https://github.com/open-telemetry/opentelemetry-java/issues/5389

**Comment by shadow0wolf** [comment]
> The internal API can be used, but is subject to change. Its effectively an experimental API. To use, do something like:
> 
> ```
> OtlpHttpSpanExporterBuilder builder = OtlpSpanExporter.builder()
>   .setEndpoint(...);
> Authenticator.setAuthenticatorOnDelegate(builder, () -> Map.of("header-key", "header-value"));
> OtlpHttpSpanExporter exporter = builder.build();
> ```
> 
> If you want to discuss promoting the API to be public facing and stable, please open a new issue.

but where is () -> Map.of("header-key", "header-value") getting executed to set header values per otel signal request .
@trask

**Comment by trask** [comment]
hi @shadow0wolf, can you open a new issue for this? thx

**Comment by shadow0wolf** [comment]
> hi @shadow0wolf, can you open a new issue for this? thx
https://github.com/open-telemetry/opentelemetry-java/issues/5959
