### ISSUE TITLE
None otel.metrics.exporter still sends metrics to collector

### ISSUE THREAD

**Issue by vasigorc** [open-telemetry/opentelemetry-java#4297]
**Describe the bug**
We want to be able to control metrics exporting via the existing `OTEL_METRICS_EXPORTER` or `otel.metrics.exporter` properties file property. Unfortunately even when the latter is set to `none` metrics are still getting exported by the app to the collector.

**Steps to reproduce**
1. Create a `Meter` from a `MeterProvider <- MetricReaderFactory, MetricResource`
2. Make sure that code somehow calls `buildWithCallback` or `record` on the meter
3. Set `otel.metrics.exporter` to `none`
4. Attach `-Dotel.javaagent.configuration-file=path/to/file/otel.propertie` to the running java process
5. Make sure that you have a opentelemetry-collector running at port 4317
6. Observe collector logs

**What did you expect to see?**
I would _not_ expect to see business metrics to appear in the collector logs

**What did you see instead?**
Business metrics appear in the collector logs

**What version and what artifacts are you using?**
Artifacts: (e.g., `opentelemetry-api`, `opentelemetry-exporter-otlp`, `opentelemetry-exporter-otlp-metrics`, `opentelemetry-extension-annotations`, `opentelemetry-sdk`, `pentelemetry-sdk-metrics`, `opentelemetry-logback-mdc-1.0`)
Version: (for opentelemetry - `1.12.0`, for openetelemetry metrics - `1.11.0-alpha`)
How did you reference these artifacts? 
```scala
// we use sbt
  lazy val otelVersion = "1.12.0"
  lazy val otlpMetricsVersion = "1.11.0-alpha"
...
 val compileDependencies: Seq[ModuleID] = Seq(
    "io.opentelemetry" % "opentelemetry-api" % otelVersion,
    "io.opentelemetry" % "opentelemetry-exporter-otlp" % otelVersion,
    "io.opentelemetry" % "opentelemetry-exporter-otlp-metrics" % otlpMetricsVersion,
    "io.opentelemetry" % "opentelemetry-extension-annotations" % otelVersion,
    "io.opentelemetry" % "opentelemetry-sdk" % otelVersion,
    "io.opentelemetry" % "opentelemetry-sdk-metrics" % otlpMetricsVersion,
    "io.opentelemetry.instrumentation" % "opentelemetry-logback-mdc-1.0" % otlpMetricsVersion,
```

**Environment**
Compiler: openjdk 11.0.11 2021-04-20
OS: MacOS Monterey 12.3

**Comment by trask** [comment]
hi @vasigorc! this is surprising, especially since the default for `otel.metrics.exporter` is `none` until the Metrics SDK stable version is released (likely in 1.13.0).

can you provide a full repro so we can see if something else is going on to explain the issue?

**Comment by vasigorc** [comment]
Hello @trask , thank you for a prompt follow-up.

Here is our properties file:

```properties
otel.service.name=our-app
otel.service.language.name=scala
otel.resource.attributes=service.namespace=APP
otel.metrics.exporter=otlp
```
This is how we initialize our `Meter`:

```scala
    private lazy val serviceName = config.getString("observability.service-name")

    private lazy val metricReaderFactory =
      PeriodicMetricReader
        .builder(OtlpGrpcMetricExporter.getDefault)
        .setInterval(Duration.of(config.getInt("observability.read-metrics.interval-seconds"), ChronoUnit.SECONDS))
        .newMetricReaderFactory()

    private lazy val metricResource = Resource.create(Attributes.of(SERVICE_NAME, serviceName))

    private lazy val messageTimesSelector =
      InstrumentSelector
        .builder()
        .setType(InstrumentType.HISTOGRAM)
        .build()
    private lazy val bucketHistogramView = View.builder().setAggregation(Aggregation.explicitBucketHistogram()).build()

    private lazy val meterProvider = SdkMeterProvider
      .builder()
      .registerMetricReader(metricReaderFactory)
      .registerView(messageTimesSelector, bucketHistogramView)
      .setResource(metricResource)
      .build()

    private lazy val meter = meterProvider
      .meterBuilder(serviceName)
      .setInstrumentationVersion(config.getString("observability.instrumentation-version"))
      .build()
```

And here is an example of how we record metrics:

```scala
case TimerMetric(metricName, labels, duration) =>
   meter
     .histogramBuilder(metricName.value)
     .setUnit("Milliseconds")
     .ofLongs()
     .build()
     .record(duration.toMillis, toOtelAttributes(labels))
```

**Comment by jack-berg** [comment]
The `otel.metrics.exporter` is only taken into consideration when using the [autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure) module to configure the SDK.

In your example you programmatically configure the `PeriodicMetricReader`, `OtlpGrpcMetricExporter`, and `SdkMeterProvider`, which means that none of the properties in your properties file are considered.

**Comment by vasigorc** [comment]
Thank you @jack-berg, I somehow skipped that... Does this principle equally apply to other items in the [auto-configure list](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-both-span-and-metric-exporters)?

**Comment by jack-berg** [comment]
Yes. As a rule, the SDK components do not read environment variables or system properties for configuration. 

The autoconfigure module contains all the code that reads the various [specified](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md) configuration properties, and from them builds the appropriate SDK components.

**Comment by vasigorc** [comment]
Makes sense, thanks Jack - this is resolved!
