### ISSUE TITLE
Implement Autocloseable in Span and Trace

### ISSUE THREAD

**Issue by chrylis** [open-telemetry/opentelemetry-java#4299]
The docs for manual granular instrumentation show repeated try-with-resources with `finally { span.end() }`. The "end span" is typical Java boilerplate, and it would make sense for the spans to implement `Autocloseable` and simply be able to be used in the idiomatic try-with-resources approach to eliminate the repetitive `end` calls.

**Comment by anuraaga** [comment]
Hi @chrylis - we may need to update those docs to be more complete. The reason we don't implement autocloseable is the pattern encourages missing errors.

```
Span span = startSpan()
try {
  logic()
} catch (Throwable t) {
  span.addExecption(t);
} finally {
  span.end();
}
```

If trying to use span with try/resources, the span would already be ended when trying to catch an exception and the exception would be missed. We consider this an antipattern for tracing.

**Comment by jkwatson** [comment]
Closing this, as we will not be implementing this. See @anuraaga's comment and https://github.com/open-telemetry/opentelemetry-java/blob/main/docs/rationale.md#span-not-closeable

**Comment by wcurrie** [comment]
Thanks for the docs! Would it be worth linking them from the javadoc on Span? So [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L26) say

> See https://github.com/open-telemetry/opentelemetry-java/blob/main/docs/rationale.md#span-not-closeable for why this class does not implement Autocloseable

**Comment by jkwatson** [comment]
> Thanks for the docs! Would it be worth linking them from the javadoc on Span? So [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L26) say
> 
> > See https://github.com/open-telemetry/opentelemetry-java/blob/main/docs/rationale.md#span-not-closeable for why this class does not implement Autocloseable

Sure. I'd have no problem with a PR that added a note in the Span javadocs.
