### ISSUE TITLE
Drop views that aggregate asynchronous instruments as histograms

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4327]
As discussed in this [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/2462#discussion_r840004121) we can't (and currently don't) produce semantically correct histograms when views are used to change async instruments (async counter, async up down counter, async gauge) to aggregate as histograms.

I think we should get ahead of the spec. Instead of producing bad histograms we should log a warning and not produce the view.

**Comment by jkwatson** [comment]
As discussed in the Java office hours on Apr 1 (GMT), these histograms aren't necessarily wrong...they would be correctly collecting the distribution of the async observations. It might not be what people want, but it does seem like there's a valid use-case for this.

**Comment by jack-berg** [comment]
@jkwatson its possible someone may want these, but IMO its unlikely that they would be happy with the results they currently get (especially aggregating instruments that can produce negative values as histograms). 

I think we should disallow certain aggregations for certain instruments for now, but keep the door open for changing as more enhancements are made to the metrics SDK spec. There's a related [conversation](https://github.com/open-telemetry/opentelemetry-specification/pull/2462#discussion_r840004121) in the spec that it would be good to get your perspective on, particularly if you think we support all aggregations on all instruments.
