### ISSUE TITLE
Start the application and load `opentelemetry javaagent.jar` exception

### ISSUE THREAD

**Issue by lrwh** [open-telemetry/opentelemetry-java#4332]
**Describe the bug**
Start the application and load `opentelemetry javaagent.jar`, if `otel exporter.otlp.endpoint` does not fill in the protocol, the system throws an exception "OTLP endpoint must be a valid URL". If the wrong protocol is filled in, the system throws an exception "OTLP endpoint scheme must be HTTP or HTTPS:". The agent only supports HTTP and HTTPS protocols. Is it better to put the verification code in front.

**Steps to reproduce**
```  URL endpointUrl;
    try {
      endpointUrl = new URL(endpoint);
    } catch (MalformedURLException e) {
      throw new ConfigurationException("OTLP endpoint must be a valid URL: " + endpoint, e);
    }
    if (!endpointUrl.getProtocol().equals("http") && !endpointUrl.getProtocol().equals("https")) {
      throw new ConfigurationException(
          "OTLP endpoint scheme must be http or https: " + endpointUrl.getProtocol());
    }
```
**What did you expect to see?**
```  URL endpointUrl;
    if (!endpoint.startsWith("http://") && !endpoint.startsWith("https://")) {
      throw new ConfigurationException(
          "OTLP endpoint scheme must be http or https: " + endpoint);
    }
    try {
      endpointUrl = new URL(endpoint);
    } catch (MalformedURLException e) {
      throw new ConfigurationException("OTLP endpoint must be a valid URL: " + endpoint, e);
    }
    
```

**What version and what artifacts are you using?**
Artifacts: opentelemetry-javaagent, opentelemetry-sdk-extension-jaeger-remote-sampler
Version: all

**Comment by jkwatson** [comment]
Not everything that starts with "http://" or "https://" is a valid URL, so I think you're just trading one error order for another one if you made this change.

**Comment by lrwh** [comment]
ok , You are right
