### ISSUE TITLE
Prometheus exporter creates a syntax error for histogram recording without attributes

### ISSUE THREAD

**Issue by OliverO2** [open-telemetry/opentelemetry-java#4367]
**Describe the bug**

Recording a histogram entry without attributes produces a syntax error in Prometheus export data, as Prometheus indicates on its `targets` status page:
> expected label name or left brace, got "COMMA"

**Steps to reproduce**

1. Create a `LongHistogram`.
2. Record a value without attributes via `histogram.record(value)`. 

**What did you expect to see?**

Bucket counts with a correctly formatted Prometheus label list, that is, not starting with a comma:
``` 
outer_span_histogram_bucket{le="5.0"} 0.0 1649457071167
outer_span_histogram_bucket{le="10.0"} 0.0 1649457071167
[...]
```

**What did you see instead?**

Bucket counts with a label list starting with a comma:
``` 
outer_span_histogram_bucket{,le="5.0"} 0.0 1649457071167
outer_span_histogram_bucket{,le="10.0"} 0.0 1649457071167
[...]
```

**What version and what artifacts are you using?**

* io.opentelemetry:opentelemetry-sdk:1.12.0
* io.opentelemetry:opentelemetry-sdk-metrics:1.12.0-alpha
* io.opentelemetry:opentelemetry-extension-kotlin:1.12.0
* Prometheus exporter

**Additional context**

The cause seems to be a hard-wired comma, which should have been dependent on `if (!attributes.isEmpty())`:

https://github.com/open-telemetry/opentelemetry-java/blob/5f2d74ed55ec79c83bba6277a2769ada5a61b224/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java#L289-L291

**Comment by jkwatson** [comment]
Thanks for the bug report, @OliverO2 . Do you have the time to put in a PR to fix it?

**Comment by OliverO2** [comment]
@jkwatson Sure, will do.
