### ISSUE TITLE
API: Change Sampler signature shouldSample to accept list of span contexts

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#437]
Created from https://github.com/open-telemetry/opentelemetry-java/pull/430#discussion_r296905082

Change signature of `Sampler.shouldSample` to accept `List<SpanContext>`. The reason being span builder has only list of `Links` which wrap `SpanContext` and not `Span`.

https://github.com/open-telemetry/opentelemetry-java/blob/ed42237b6c71052bbffe4d849647c53fae81b246/api/src/main/java/io/opentelemetry/trace/Sampler.java#L44-L50

https://github.com/open-telemetry/opentelemetry-java/blob/ed42237b6c71052bbffe4d849647c53fae81b246/api/src/main/java/io/opentelemetry/trace/Link.java#L36

**Comment by bogdandrutu** [comment]
Should we use the List<Link> instead?
