### ISSUE TITLE
Ensure callbacks of asynchronous instruments cannot run indefinitely

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4377]
According to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#observations-inside-asynchronous-callbacks), "The implementation SHOULD use a timeout to prevent indefinite callback execution".

**Comment by jkwatson** [comment]
So... does that mean we need some sort of future construct here, and to track it on a separate thread, for every callback? I would push back on that as a requirement.

**Comment by anuraaga** [comment]
@jkwatson FWIW, it's a SHOULD so maybe not necessarily a requirement. Our current plan is to not support this unless we find users have trouble because of it.

**Comment by jack-berg** [comment]
Closing because there's agreement that this isn't practical.
