### ISSUE TITLE
Enforce metric instrument unit requirements

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4379]
We do no validation on instrument units, but should according to the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-unit).

Similar to the metric name validation issue #4378, we could do a number of different things if a unit violates the rule. However, we may choose to do something different given that unit is optional and doesn't play as crucial a role in the identity of a metric. For example, we could decide to omit the unit if invalid and continue to export data - the same option isn't available for instrument name.

**Comment by jkwatson** [comment]
So I think the only requirement is length <= 63 characters?
