### ISSUE TITLE
JAX-RS endpoints annotated with WithSpan lose information and parent

### ISSUE THREAD

**Issue by JapuDCret** [open-telemetry/opentelemetry-java#4391]
**Describe the bug**
In `OpenTracing` it was possible to override the `operationName` of an automatically created Span of JAX-RS endpoints by using `@Traced`. This is no longer possible with `opentelemetry-java`. Also it seems that the connection to the previous span is lost (see screenshots)

**Steps to reproduce**
Annotate your JAX-RS REST endpoint with `@WithSpan(..)`, see:

```java
    @WithSpan("Create new Carrier")
    @POST
    @Path("/carriers")
    @Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
    @Consumes(MediaType.APPLICATION_JSON)
    public Response createCarrier(
            final NewCarrierDTO newCarrierDto
    ) {
        return Response
                .status(Response.Status.CREATED)
                .entity(applicationService.createNewCarrier(newCarrierDto))
                .build();
    }
```

**What did you expect to see?**
* Without annotating our REST-APIs with `@WithSpan(..)`
  * Complete Trace
    ![2022-04-19 14_55_28-Jaeger UI — Firefox Developer Edition](https://user-images.githubusercontent.com/14893450/164010561-bdd7be58-dd38-45c8-887c-b6e9cf957dc5.png)
  * First Span
    ![2022-04-19 14_56_11-Jaeger UI — Firefox Developer Edition](https://user-images.githubusercontent.com/14893450/164010556-c6eaf410-ff0a-4510-aab2-fb1fb2bec095.png)

**What did you see instead?**
* With annotating our REST-APIs with `@WithSpan(..)`
  * Complete Trace
    ![2022-04-19 14_55_43-Jaeger UI — Firefox Developer Edition](https://user-images.githubusercontent.com/14893450/164010560-9f42eb3a-73d7-4efa-ae17-105df9f6a5c5.png)
  * First Span
    ![2022-04-19 14_56_25-Jaeger UI — Firefox Developer Edition](https://user-images.githubusercontent.com/14893450/164010550-57809c12-cd2b-4d6e-9e02-5b23871c4053.png)

**What version and what artifacts are you using?**
We are using Quarkus `2.7.2.Final`, which also defines the following Dependency versions:

We are using the following dependencies:
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-extension-trace-propagators</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-jdbc</artifactId>
        </dependency>
```

**Environment**
Compiler: `AdoptOpenJDK (build 11.0.10+9)`
OS: `Windows 10`
Runtime (if different from JDK above): n/a
OS (if different from OS compiled on): n/a

**Additional context**
n/a

**Comment by mateuszrzeszutek** [comment]
Hey @JapuDCret ,
Have you tried submitting a bug to the Quarkus repo? The `@WithSpan` annotation is ours, but the advice/interceptor that actually creates spans based on it is part of the Quarkus code.

**Comment by JapuDCret** [comment]
Created an issue at quarkus: [quarkus#25002](https://github.com/quarkusio/quarkus/issues/25002)

**Comment by anuraaga** [comment]
Thanks @JapuDCret - for reference the code is https://github.com/quarkusio/quarkus/blob/39912acbfdc00b5b1d36b11bcf436c1e89831dc6/extensions/opentelemetry/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/cdi/WithSpanInterceptor.java

There isn't anything here related to generating spans from WithSpan in quarkus so will go ahead and close this issue but let us know if anything comes up when using the OpenTelemetry API.
