### ISSUE TITLE
build project failed, can not find the package(io.opentelemetry.proto.metrics.v1.internal) 

### ISSUE THREAD

**Issue by HiCubee** [open-telemetry/opentelemetry-java#4394]
I'm trying to include opentelemetry with source code, but there is some class doesn't exist

`import io.opentelemetry.proto.metrics.v1.internal.SummaryDataPoint;
import io.opentelemetry.proto.metrics.v1.internal.ExponentialHistogramDataPoint;
import io.opentelemetry.proto.metrics.v1.internal.ExponentialHistogramDataPoint;
import io.opentelemetry.proto.metrics.v1.internal.ExponentialHistogram;
import io.opentelemetry.proto.metrics.v1.internal.Gauge;
import io.opentelemetry.proto.metrics.v1.internal.HistogramDataPoint;`

these file used in opentelemetry-java/exporters/otpl/common

Anyone help me ? thanks!

**Comment by anuraaga** [comment]
Copying in response from opentelemetry-proto issue

Hi @HiCubee - those classes are generated for internal use in the opentelemetry-java repository and aren't related to this repository.

They are bundled into the otlp-common artifact, and I just checked the sources jar and found them there. Is this what you're looking for?

https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-otlp-common/1.13.0/
https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-otlp-common/1.13.0/opentelemetry-exporter-otlp-common-1.13.0-sources.jar

**Comment by HiCubee** [comment]
@anuraaga  thank you for your quick replay, I'm sorry that I post a iusse on wrong repository(opentelemetry-proto)

and I would like to know how are these files generared?

**Comment by anuraaga** [comment]
@HiCubee The files are generated using the wire compiler

https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/common/build.gradle.kts#L8

We have a special plugin to generate our trimmed down proto definitions

https://github.com/open-telemetry/opentelemetry-java/blob/main/buildSrc/src/main/kotlin/io/opentelemetry/gradle/ProtoFieldsWireHandler.kt

**Comment by HiCubee** [comment]
@anuraaga Thank you for your help! you solved my doubt.

Best wishes!
