### ISSUE TITLE
Use ByteBuffer with Binary propagation instead of byte[]

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#44]
I'm wondering what are the reasons to not use `ByteBuffer` with the Binary injection/extraction.

I'm thinking using `ByteBuffer` could be a nice thing to use (you can even wrap a `byte[]` with it), with all its range/limit capabilities (and potential re-use).

**Comment by bogdandrutu** [comment]
I think using ByteBuffer everywhere is ok, the only downside is that it forces a new allocation every time you need to serialize, probably the JIT will optimize this.

**Comment by bogdandrutu** [comment]
Can we please hold on to this, the main user of this API is gRPC which uses byte[], so extra unnecessary allocation after this change

**Comment by carlosalberto** [comment]
@bogdandrutu Sure
