### ISSUE TITLE
Flaky Test RetryInterceptorTest

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#4407]
Luckily have a seemingly easy to debug stack trace
```
> Task :exporters:otlp:common:test

RetryInterceptorTest > connectTimeout() FAILED
    java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "java.lang.Throwable.getMessage()" is null
        at io.opentelemetry.exporter.internal.retry.RetryInterceptorTest.lambda$connectTimeout$2(RetryInterceptorTest.java:156)
        at org.assertj.core.api.AbstractAssert.matches(AbstractAssert.java:992)
        at org.assertj.core.api.AbstractAssert.matches(AbstractAssert.java:755)
        at io.opentelemetry.exporter.internal.retry.RetryInterceptorTest.connectTimeout(RetryInterceptorTest.java:154)
```

https://github.com/open-telemetry/opentelemetry-java/runs/6120597180?check_suite_focus=true

**Comment by jack-berg** [comment]
Hooray for helpful NullPointerExceptions!

**Comment by laurit** [comment]
The way I see it there are two options. Either accept that this test can throw `SocketTimeoutException` without a message or increase connection timeout. For me this exception is thrown from https://github.com/openjdk/jdk/blob/b9d1e85151d9d4016639e6298c90737db10f6072/src/java.base/share/classes/java/net/SocksSocketImpl.java#L102-L111 To reproduce just set a breakpoint there, you need to pause the app for 10ms (current connection timeout) to trigger the exception.

**Comment by jack-berg** [comment]
So there's a code path that produces a `SocketTimeoutException` without a message? Nice find @laurit! 

I think its fine to relax the test and not assert on the message. The test cases are interested in the number of retries and that an exception is ultimately raised to the caller, rather than the message itself.
