### ISSUE TITLE
Something is wrong with my agent configuration: Resource attributes are missing

### ISSUE THREAD

**Issue by nicklocaso** [open-telemetry/opentelemetry-java#4448]
**A description of what the problem is**

I am using the Java JAR [opentelemetry-javaagent.jar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases) file in order to generate traces from my Java JAR services like what I could understand from the [getting started guide](https://opentelemetry.io/docs/instrumentation/java/automatic/) of the official site.

I have done several tests with different configurations with logging exporter and the [google-exporter-auto](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto) but every single time there are not present in traces attributes like "service.name" which is an essential attribute for me.

It does not works with both "System property" as well as "Environment variable" configurations. I even tried with different opentelemetry-javaagent.jar versions.

On debug mode there are not logged errors

**Docker**
I am using openjdk:11-jre-slim-bullseye

**Local**
$ java --version
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment Homebrew (build 11.0.14.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.14.1+0, mixed mode)

**Here some of my configurations**

With [Loggin exporter](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#logging-exporter):

`java -javaagent:opentelemetry-javaagent.jar -Dotel.traces.exporter=logging -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.resource.attributes=service.name=shifts-srv -jar ./shifts-srv-1.0-SNAPSHOT.jar`

With [Google Exporter Auto](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto):

`java -javaagent:opentelemetry-javaagent.jar -Dotel.javaagent.extensions=exporter-auto.jar -Dotel.traces.exporter=google_cloud_trace -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.resource.attributes=service.name=shifts-srv -jar ./shifts-srv-1.0-SNAPSHOT.jar`

Results are the same both local or on docker, with google-exporter or with local exporter. Traces are present in console and on GCP but there is not the service.name attribute in them.

**Question**

What is wrong with my configuration?
Thank you

**Comment by jkwatson** [comment]
Resource attributes do not generally become span attributes. I know our logging exporter definitely does not export the resource attributes, just to keep things light weight. I can't speak for what the google cloud trace exporter does with resource attributes, however, since that's not maintained here.

**Comment by nicklocaso** [comment]
Thank you for your answer.

I have doubts about my configuration with logging exporter because I don't find any difference in the console between

`java -javaagent:opentelemetry-javaagent.jar -Dotel.traces.exporter=logging -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.resource.attributes=service.name=shifts-srv -jar ./shifts-srv-1.0-SNAPSHOT.jar`

and 

`java -javaagent:opentelemetry-javaagent.jar -Dotel.traces.exporter=logging -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.resource.attributes=service.name=shifts-srv -Dotel.exporter.logging.prefix=shifts -jar ./shifts-srv-1.0-SNAPSHOT.jar`

Note the difference in the execution is: `-Dotel.exporter.logging.prefix=shifts`

I took this system property from the doc of the [Logging exporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#logging-exporter)

What am I doing wrong here with prefix?

**Comment by jkwatson** [comment]
hm. I actually have no idea what that prefix system property is about. I don't see anything in the code about it, and I don't remember when it might have done anything.  @anuraaga I see you added that documentation; do you remember where it came from?

**Comment by anuraaga** [comment]
I think you mean @jack-berg - should we remove the documentation about `OTEL_EXPORTER_LOGGING_PREFIX`?

**Comment by jack-berg** [comment]
The `OTEL_EXPORTER_LOGGING_PREFIX` was introduced in the original documentation commit for [autoconfigure](https://github.com/open-telemetry/opentelemetry-java/blame/29140bdf7b74e64accdba2deb7969d0e7376881a/sdk-extensions/autoconfigure/README.md). Can't find any reference to it in the code. Seems like a mistake. Removed in #4462.

**Comment by jack-berg** [comment]
I believe this is resolved. Please reopen  if you have additional questions.
