### ISSUE TITLE
[Doc] OpenTelemetry SDK Autoconfigure - otel.exporter.otlp.client.key

### ISSUE THREAD

**Issue by marcalff** [open-telemetry/opentelemetry-java#4471]
Greetings,

In the OpenTelemetry SDK Autoconfigure documentation:

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md

The system property `otel.exporter.otlp.client.key` is related to the `OTEL_EXPORTER_OTLP_CERTIFICATE` environment variable.

> | otel.exporter.otlp.client.key                     | OTEL_EXPORTER_OTLP_CERTIFICATE                    | The path to the file containing private client key to use when verifying an OTLP trace, metric, or log client's TLS credentials. The file should contain one private key PKCS8 PEM format. By default no client key is used.                                                                                                                                                                                         

Should it be `OTEL_EXPORTER_OTLP_CLIENT_KEY` instead ?

Regards.

**Comment by jack-berg** [comment]
Good catch, yes it should be `OTEL_EXPORTER_OTLP_CLIENT_KEY`.
