### ISSUE TITLE
Support updating current span's name with @WithSpan

### ISSUE THREAD

**Issue by paulolieuthier** [open-telemetry/opentelemetry-java#4480]
**Is your feature request related to a problem? Please describe.**
I'm using Micronaut, which is currently lacking proper integration with OpenTelemetry. Because of that, root spans are listed with duplicate names (e.g. HTTP GET, HTTP POST).

**Describe the solution you'd like**
I'd like to have something as `@WithSpan(update = true)`, or maybe another annotation for that to use on controllers' methods. That way the root spans will always be named correctly according to the application's entry points.

**Describe alternatives you've considered**
I can of course use `Span.current().updateName("GET /my/path")`, but it would be nice to rely on annotations only.

**Additional context**
I'm using OpenTelemetry's Java agent.

**Comment by paulolieuthier** [comment]
I don't think so. My point is to be able to achieve it independently of the framework.

**Comment by jkwatson** [comment]
This is an issue for the instrumentation project, isn't it?

**Comment by paulolieuthier** [comment]
Well, the annotation must support it as well.

**Comment by jkwatson** [comment]
oh I see. Hm. I don't know. The difference between an annotation and a single line of code seems very minor to me. And, the single line of code is definitely less magical and easier to understand.
