### ISSUE TITLE
please make OpenTelemetry Java build reproducible

### ISSUE THREAD

**Issue by hboutemy** [open-telemetry/opentelemetry-java#4488]
last 1.14.0 release is not reproducible: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/io/opentelemetry/java/README.md

OpenTelemetry Java Instrumentation has done some work on the topic: see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6072

It would be nice that OpenTelemetry Java does the same update to the build

**Comment by jkwatson** [comment]
Are you able to contribute work towards this? The maintainers of this project currently have very little time to take on any additional work.
