### ISSUE TITLE
Allow overriding authority and GrpcChannel used for GRPC exporter stub

### ISSUE THREAD

**Issue by donce** [open-telemetry/opentelemetry-java#4513]
**Is your feature request related to a problem? Please describe.**

We're using Envoy proxy for all GRPC requests, which relies on `authority` field to distinguish requests to different servers going through the same proxy (same `endpoint`).
We're using OTLP GRPC exporter (`OtlpGrpcSpanExporter`), which doesn't allow overriding `authority` or any other `CallOptions`, since it's being created with default empty `CallOptions` and it's not being exposed anywhere ([OtlpGrpcSpanExporterBuilder.java:42](https://github.com/open-telemetry/opentelemetry-java/blob/77f5a174d4d6f735ee7fe4717cab720844f77395/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L42)).

Also, we need to pass `GrpcChannel` because of the proxy to re-use the same proxy connection. This can be achieved by using `OtlpGrpcSpanExporterBuilder.setChannel` ([OtlpGrpcSpanExporterBuilder.java:57](https://github.com/open-telemetry/opentelemetry-java/blob/77f5a174d4d6f735ee7fe4717cab720844f77395/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L57)), but the method is deprecated hence it's probably not wise to use it.

**Describe the solution you'd like**

1. Undeprecate `OtlpGrpcSpanExporterBuilder.setChannel`
2. allow overriding authority on `OtlpGrpcSpanExporterBuilder` via one of these:
a. allowing overriding `authority` directly, or
b. allowing overriding `CallOptions`, which would allows overriding `authority` among other things

**Describe alternatives you've considered**
Tried extending builder and/or exporter, but that doesn't seem feasible, because most of relevant classes aren't public and/or are final, or methods of public classes are private. Alternative solution might be to relax visibility by making related classes and methods extensible, but it would expose more internal things so the main solution seems better.

**Comment by donce** [comment]
Thank you for a quick reply @anuraaga !

>https://github.com/open-telemetry/opentelemetry-java/pull/4514 will allow setting the host header to override authority when using the gRPC exporter

So this would allow to override authority pseudo-header with `builder.addHeader("host", "my-authority")` (from [OtlpGrpcSpanExporterBuilder.java:132](https://github.com/open-telemetry/opentelemetry-java/blob/77f5a174d4d6f735ee7fe4717cab720844f77395/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L132)), right?

>And https://github.com/open-telemetry/opentelemetry-java/issues/4515 would also achieve the same by switching off of the gRPC exporter codepath

And this would allow undeprecating `setChannel` so we could pass existing `GrpcChannel` instance?

>I'm assuming you have gRPC on the classpath for other reasons than opentelemetry
Yeah, we're already using gRPC widely for other RPC connections, all (or most) of which go through the same gRPC proxy.

**Comment by donce** [comment]
Since all gRPC requests are going to the same Envoy proxy, we're re-using same channel for all different gRPC clients, which we manage uniformly - e.g. channel error handling. We'd like to re-use this connection for exporter not to manage it separately and not to allocate dedicated connection to the same proxy host from the same machine.

**Comment by anuraaga** [comment]
Hi @donce - we discussed the issue of allowing sharing a channel with other gRPC stubs but decided not to support it. We do need the flexibility to change underlying library even while supporting the gRPC protocol (not library) and will remove `setChannel` at some point. It would be best to consider the OTel SDK's transport a black box, similar to other SDKs like maybe AWS one. On the bright side, not sharing the connection with business logic means that telemetry can still be sent if the business logic connection has problems, for example HTTP/2 flow control causing it to get stuck. Or the other side where sending telemetry could cause problems for the business logic RPCs.
