### ISSUE TITLE
OpenTelemetryMeterRegistry Exemplar

### ISSUE THREAD

**Issue by quequiere** [open-telemetry/opentelemetry-java#4542]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I use java agent with Sprinboot framawork and I would like to use exemplar. I use OTEL exporter. I do not expose prometheus endpoint
I saw in OpenTelemetryMeterRegistry there is no way to use exemplar.

Is it possible to the java agent to expose automaticaly metrics with exemplar ?
Or, can we do it manually ?

**Describe alternatives you've considered**
Expose prometheus endpoint (but i want to avoid that by using otel exporter for metrics )

**Comment by jkwatson** [comment]
This will be coming as soon as the spec for how to configure it has been approved.

**Comment by jack-berg** [comment]
Exemplars are enabled by default in the otel java SDK. By default the `with_sampled_trace` filter is used, as described in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#metrics-sdk-configuration). 

It sounds like you're using the `micrometer-shim`. There's nothing special about using exemplars with the `micrometer-shim`. However, here's some advice that may be helpful in practice:
- Exemplars are only recorded for synchronous instruments. If you're using something like a micrometer gauge that maps to an asynchronous opentelemetry instrument, no exemplars will be recorded. If you're using something like a micrometer timer that maps to synchronous opentelemetry instrument, exemplars _may_ be recorded (see next tip).
- The exemplar filter is what determines whether or not a measurement is send to the exemplar reservoir as a candidate for storage. As mentioned above, the default exemplar filter is `with_sampled_trace`. This means that a measurement may be stored as an exemplar if there is a sampled span in progress. If you're not using opentelemetry for tracing, there will never be sampled spans and measurements will never be candidates for storage. As @jkwatson mentions, exemplars are still experimental in the spec, and in java as well. However, you can still change the exemplar filter using this [experimental method](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/SdkMeterProviderUtil.java#L31-L43). You might consider using the [always on sampler](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/Sampler.java#L29-L30) if only using metrics. If using autoconfigure, this can be configured using environment variables / system properties as described [here](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#exemplars). 


Sorry for the delayed reply.

**Comment by jack-berg** [comment]
I'm going to close this but feel free to re-open if more clarity is needed.
