### ISSUE TITLE
AWS Propagator appending other baggage

### ISSUE THREAD

**Issue by TopoDiFogna** [open-telemetry/opentelemetry-java#4545]
**Describe the bug**
`AwsXrayPropagator` is appending other baggages (headers) when used with spring cloud sleuth

**Steps to reproduce**
In a spring boot web application include spring boot starter sleuth exclude brave from it's dependencies and include the open telemetry spring dependency as explained here https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel

Create a bean of type `TextMapPropagator` and implement the creation and injection of any baggage using `context.with(newBaggage)`

**What did you expect to see?**
In the outgoing request the AwsXrayPropagator should only add it's header with the incoming value or a new value if not received

**What did you see instead?**
The `X-Amzn-Trace-Id` header is present but has happended any other baggage created that are also propagated as different headers until a max size of 256 bytes

**What version and what artifacts are you using?**
opentelemetry 0.14 but the same code causing the issue is also in 0.15.0
How did you reference these artifacts? 
See steps to reproduce

**Environment**
Compiler: AdoptOpenJDK 11.0.12 but it should not matter
OS: Windows 10 but it should not matter

**Additional context**
See `AwsXrayPropagator` following lines:
https://github.com/open-telemetry/opentelemetry-java/blob/852e755eebcad4c740b1de9d606812a5a470eb72/extensions/aws/src/main/java/io/opentelemetry/extension/aws/AwsXrayPropagator.java#L131-L155

Why this behaviour is enforced, can it be disabled?

**Comment by anuraaga** [comment]
@TopoDiFogna The same thing would happen if using w3c propagator - baggage is meant to be propagated between services. We don't have any mechanism for local-only baggage right now, if you don't want it propagated can you add it to context with a different key instead of using `Baggage`?

**Comment by TopoDiFogna** [comment]
This baggage is not local only unfortunately; for legacy compatibility our code must propagate a custom tracing header used by legacy systems deployed on prem and if this header is not received we need to generate it from scratch.

So in practice what we need to achieve is to propagate the AWS tracing header and an additional custom header without mixing values. Using a custom `TextMapPropagator`, in addition to the `AwsXrayPropagator` the new header is correctly generated and put in the following requests but the problem is that it gets appended also to the AWS header.

In this way requests made by instrumented clients will have 2 headers: 
1. CustomHeader: CustomValue
2. X-Amzn-Trace-Id: Root=1-67891233-abcdef012345678912345678;CustomHeader=CustomValue

**Comment by anuraaga** [comment]
This sounds like a custom propagator rather than baggage. Instead of using the `Baggage` class, can you store the data as a separate item in `Context` with some way to access it?

```
public class MyCustomPropagator {
  private static final ContextKey<Map<String, String>> customData

  public static getData(Context context) {
    return context.get(customData);
  }

  extract() {
    return context.with(customData, Map.of(key, getter.get(key)));
  }

  inject() {
    getData(context).forEach(setter::set);
  }
```

If you wanted to make it easier to get data, you could define a class instead of `Map` that is `ImplicitContextKeyed`, similar to what `Baggage` implements

https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/Baggage.java#L30

Baggage has a very specific meaning in OpenTelemetry, so if you want control of how something is propagated in your own way, you probably don't want to use baggage. On the flip side, if you want to migrate your custom headers to OTel baggage over time, then sending both headers in the request would allow compatibility during such a migration.

**Comment by TopoDiFogna** [comment]
Thank you for your suggestion; I'll try to implement it with an object that implements `ImplicitContextKeyed` and report back on the results asap

**Comment by TopoDiFogna** [comment]
I had it worked with @anuraaga suggestion: creating a class that is implementing `ImplicitContextKeyed` and adding a new `TextMapPropagator` that adds my object into the context and retrieves it.
