### ISSUE TITLE
Using Metrics View config to filter out http_route attribute not working

### ISSUE THREAD

**Issue by alvinhom** [open-telemetry/opentelemetry-java#4546]
**Describe the bug**
I am trying to use the metrics view configuration option to customize the metrics that are being generated.  Specifically, I want to remove the http_route parameter from the http_server_duration metric as the cardinality explodes in our application.  I am not sure if the view configuration is correct, but I copied it from the example, where I am keeping the attribute keys that I want.  It would be nice to have feature to just exclude specific attributes.

**Steps to reproduce**
Set the environment variable with the option to enable view config:

OTEL_EXPERIMENTAL_METRICS_VIEW_CONFIG=/mnt/auto-trace/view-config.yaml

In the view-config.yaml, I have written a view to only retain certain attributes, but specifically exclude http_route:

- selector:
    meter_name: http_server_duration*
  view:
    name: remove_http_route
    description: Remove HTTP route in metrics to reduce cardinality
    attribute_keys:
      - http_flavor
      - http_host
      - http_status_code
      - http_method
      - http_scheme
      - exported_job
      - le

**What did you expect to see?**
I am expecting the http_route attribute should be remove from the metric

**What did you see instead?**
I go and retrieve the metrics from Prometheus port of the otel-collector, I am still seeing the http_route attribute:

http_server_duration_bucket{host_arch="amd64",host_name="tomcat-deployment-slave-8694c8cfbd-gm2lk",http_flavor="1.1",http_host="10.42.15.37:9000",http_method="GET",**http_route="//read-data",**http_scheme="http",http_status_code="200",job="testdv1b/testdv1b-dwp",service_name="testdv1b-

**What version and what artifacts are you using?**
Artifacts: otel java instrumentation 1.14,   otel-collector 0.53
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by jack-berg** [comment]
You're configuration is close but not quite correct. `meter_name` refers to the name of the meter. You want to select by instrument name. Additionally, it looks like you're using the prometheus versions of the instrument name and attribute keys, which replace characters like `.` and `-` with `_`. This conversion is an implementation detail of the prometheus metric reader, and happens after views are applied. 

Try changing `meter_name: http_server_duration*` to `instrument_name: http.server.duration`. Also, change attribute keys to be `http.*`, which reflects how they're recorded in line the [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#attributes).

**Comment by alvinhom** [comment]
Thanks Jack.  That work.  I changed to use instrument_name: http.server.duration and it worked.

I have a separate question on aggregation.  Is it possible to use explicitBucketHistogram as the aggregation and specify custom bucket boundaries instead of using the default.  It does look like it parse the boundaries, but maybe I overlook something.

**Comment by alvinhom** [comment]
Ok.  Thanks.  I will close this issue then.
