### ISSUE TITLE
Add ConfigurableLogExporterProvider

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#4549]
**Is your feature request related to a problem? Please describe.**
I'd like to provide a "named" log exporter in our agent distro and provide a default `otel.logs.exporter` (via `ConfigCustomizer`) that points to this name, so that users can override it if they want using the standard otel properties.

**Describe the solution you'd like**
`ConfigurableLogExporterProvider` class similar to `ConfigurableSpanExporterProvider` and `ConfigurableMetricExporterProvider`.

**Additional context**
I think we discussed this in #4095, but I can't remember if we intentionally didn't create it, or if we deferred it since logs are not stable yet.

**Comment by jack-berg** [comment]
Seems reasonable 👍. We can add the SPI to the autoconfiguration module (versus the autoconfigure-spi module) while logs remain unstable.

**Comment by mateuszrzeszutek** [comment]
> Seems reasonable 👍. We can add the SPI to the autoconfiguration module (versus the autoconfigure-spi module) while logs remain unstable.

That's a good idea; but, at the same time, I noticed that we already expose parts of unstable logs SDK in the `AutoConfigurationCustomizer`: there are methods for customizing [`LogEmitterProvider`](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java#L118) and [`LogExporter`](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java#L131)
