### ISSUE TITLE
Should AutoConfigurationCustomizerProvider provide guarantees around the order in which customisations are processed?

### ISSUE THREAD

**Issue by GrahamLea** [open-telemetry/opentelemetry-java#4555]
**Is your feature request related to a problem? Please describe.**
I've encountered [this issue](https://github.com/honeycombio/honeycomb-opentelemetry-java/issues/315) with Honeycomb's agent where their `AutoConfigurationCustomizerProvider` calls `setSampler()`, which overrides a `Sampler` which is installed as a decorator by an extension I've written.
Because `AutoConfigurationCustomizerProvider`s are loaded and executed non-deterministically, and `tracerProviderCustomizer`s are run after `samplerCustomizer`s, there is no way to force my decorating Sampler to be installed after Honeycomb's override of the sampler.

**Describe the solution you'd like**
Either of the following changes in this project would make it possible to fix this particular problem:
* Provide a means by which `AutoConfigurationCustomizerProvider`s can be prioritised so that the order in which they're run is deterministic.
* Apply `samplerCustomizer`s _after_ `tracerProviderCustomizer`s, instead of before.

**Describe alternatives you've considered**
I've proposed a change to Honeycomb to make their own Sampler a decorator rather than an override.
That would solve my problem, but wouldn't solve the more generic problem that `AutoConfigurationCustomizerProvider`s are ordered non-deterministically (I believe?) and can contain a mix of both decorating and overriding operations.

**Additional context**
More detail about the extension I'm creating is here, but probably isn't necessary to understand the issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5008#issuecomment-1163162647

/cc @trask (who suggested raising this issue)

**Comment by jack-berg** [comment]
We could add a default method to `AutoConfigurationCustomizerProvider` to indicate priority:
```
default int priority();
```
If this is a useful concept, we could extend it to other SPIs as needed, perhaps adding a super interface (i.e. `Prioritizable`). 

I do think in this case honeycomb is perhaps making a stronger statement than they intend. By calling `setSampler`, they're essentially saying "ignore the autoconfigured sampler and set it this instead". Maybe that's the intent of their distro, but if they intend to offer more flexibility maybe they consider adding a `ConfigurableSamplerProvider`, and adding `AutoConfigurationCustomizer#addPropertiesSupplier` with properties that default to their sampler.

**Comment by mateuszrzeszutek** [comment]
You could bring the javaagent's [`Ordered`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/extension/Ordered.java) interface to this repo, and later on we'd remove our copy - I think it makes sense for the autoconfigure SPIs and javaagent extension SPIs to use the same pattern for ordering things.

**Comment by trask** [comment]
> You could bring the javaagent's [`Ordered`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/extension/Ordered.java) interface to this repo, and later on we'd remove our copy - I think it makes sense for the autoconfigure SPIs and javaagent extension SPIs to use the same pattern for ordering things.

this would be nice I think

@anuraaga @jkwatson (comment already got 👍 from @jack-berg)?

**Comment by anuraaga** [comment]
Yeah when someone needs ordering is when it's time to implement ordering. The javaagent interface looks good

**Comment by GrahamLea** [comment]
Thanks @mateuszrzeszutek !
