### ISSUE TITLE
correct way to init GlobalOpenTelemetry

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java#4556]
**Is your feature request related to a problem? Please describe.**

It's not clear how to correctly init the GlobalOpenTelemetry.

- You cannot check if it's already set without initializing it.
- It's also not possible to ensure that nobody has initialized it before (if you don't run in the java agent)

**Describe the solution you'd like**

Not sure, but this is what I'm doing right now:

```java
private static void registerGlobalOpenTelemetry(OpenTelemetry openTelemetry) {
        try {
            GlobalOpenTelemetry.set(openTelemetry);
        } catch (Exception e) {
            LOG.warn("please initialize the ObservabilitySdk before starting the application");
            // will throw an exception if it was already set - problem is that we cannot check if was set by a third-party library before
            GlobalOpenTelemetry.resetForTest();
            try {
                GlobalOpenTelemetry.set(openTelemetry);
            } catch (Exception ex) {
                LOG.warn("unable to set GlobalOpenTelemetry", ex);
                //now we give up - must be a race condition
            }
        }
    }
```

**Describe alternatives you've considered**

Letting the application crash and fix the root cause.
Discarded this solution because Tracing libraries must never crash IMO.

**Comment by jkwatson** [comment]
In general, unless you are using the agent, we strongly recommend *against* using the GlobalOpenTelemetry instance at all, for exactly these reasons. Initialization order is often tricky to get right.

**Comment by jack-berg** [comment]
This recommendation is documented in [GlobalOpenTelemetry](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L32-L35).

**Comment by zeitlinger** [comment]
That's indeed news to me.

I'm not using the agent (and it's not easy to change) and I want to use other libraries that depend on the global instance, such as [riptide](https://github.com/zalando/riptide/blob/944d3017fe7d5db16d42f30595fa83369849be81/riptide-opentelemetry/src/main/java/org/zalando/riptide/opentelemetry/OpenTelemetryPlugin.java#L45).

What would be the recommendation for library authors such as riptide - what's the recommended way to get the `OpenTelemetry` instance?

**Comment by anuraaga** [comment]
Hi @zeitlinger - It looks like riptide has a constructor that accepts `OpenTelemetry` as a pattern, so that would be the one to use.

https://github.com/zalando/riptide/blob/944d3017fe7d5db16d42f30595fa83369849be81/riptide-opentelemetry/src/main/java/org/zalando/riptide/opentelemetry/OpenTelemetryPlugin.java#L48

**Comment by zeitlinger** [comment]
> Hi @zeitlinger - It looks like riptide has a constructor that accepts `OpenTelemetry` as a pattern, so that would be the one to use.

Yes, I could do that - but it would require me to create an adapter library.
It doesn't allow library authors (riptide) and SDK providers (me) to develop independently - both only relying on the Otel API.
Maybe the answer is that this is only supported in the agent.

**Comment by anuraaga** [comment]
Could you describe more what you mean by develop independently? It's only passing a dependency to a constructor, there isn't really any coupling of the API itself. I think this pattern is fairly common for java libraries that use external dependencies. One example is configuring HikariCP metrics

https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/HikariDataSource.java#L252

This generally reduces the chance of unexpected behavior I think.

**Comment by zeitlinger** [comment]
OK, I guess it would be possible to do that.
In a spring boot environment, it's a bit unusual - you usually rely on dependency injection.
It would be possible to establish the convention that the `OpenTelemetry` object is managed by spring - is this a good idea?

In the concrete case I faced, I used [jdbc instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcSingletons.java#L30) outside of the agent - maybe this is an unexpected use - even though it works fine.

Note that I did fix the initialization order to set my global instance before the jdbc instrumentation gets the global instance - but it doesn't guarantee that I've missed other cases.

**Comment by anuraaga** [comment]
Yes, having a `@Bean OpenTelemetry` or similar provider makes a lot of sense. Actually I've thought our instrumentation could probably do this automatically, but haven't looked into it in detail /cc @trask

> In the concrete case I faced, I used [jdbc instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcSingletons.java#L30) outside of the agent - maybe this is an unexpected use - even though it works fine.

As you've found, it is true that there are cases where the global is required - there is no way to instrument JDBC without a global. We think that apps still tend to run into less edges without relying on the Global so always first suggest not using it, but for JDBC you'll indeed need it (for riptide you don't :) ). The pattern is to call `OpenTelemetrySdk.buildAndRegisterGlobal()` once in your app. Ideally the return value is also exposed as a `OpenTelemetry` for DI into other places and the usage of the global is kept to a minimum.

**Comment by jkwatson** [comment]
> > Actually I've thought our instrumentation could probably do this automatically, but haven't looked into it in detail
> 
> you mean the agent?

I think @anuraaga was referring to the spring instrumentation, but I could be wrong.

**Comment by zeitlinger** [comment]
> I've noticed that I can plugin into the auto initialization of the global instance by implementing my own [AutoConfiguredOpenTelemetrySdk](https://github.com/open-telemetry/opentelemetry-java/blob/d78cadabaa5ef1d423b89b1aaec0bd381d86ebd8/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L217). Would this be an idiomatic solution or an abuse of this API?

@jkwatson what's your take?

**Comment by jkwatson** [comment]
> > I've noticed that I can plugin into the auto initialization of the global instance by implementing my own [AutoConfiguredOpenTelemetrySdk](https://github.com/open-telemetry/opentelemetry-java/blob/d78cadabaa5ef1d423b89b1aaec0bd381d86ebd8/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L217). Would this be an idiomatic solution or an abuse of this API?
> 
> @jkwatson what's your take?

You're free to do that, but I we aren't providing any guarantees that this won't break in the future, or even that the interface to the `AutoConfiguredOpenTelemetrySdk` won't change in the future, so do so at your own risk.

**Comment by zeitlinger** [comment]
thanks for the feedback!
