### ISSUE TITLE
Prometheus exporter aggregationTemporality

### ISSUE THREAD

**Issue by bouillipx** [open-telemetry/opentelemetry-java#4561]
https://github.com/open-telemetry/opentelemetry-java/blob/31be1dcc3fa73d4c11818bdf7c868281b9554dc9/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java#L74

The aggregationTemporality of the prometheus exporter can configure from the builder?

**Comment by jack-berg** [comment]
AggregationTemporality isn't configurable in the prometheus exporter because prometheus only works with cumulative temporality.

**Comment by jack-berg** [comment]
Closing because we can't / won't fix.
