### ISSUE TITLE
Add hyphen normalization to `ConfigProperties`

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#4562]
**Describe the bug**
Currently `ConfigProperties` does not normalize the property name when retrieving the value; this is inconsistent with javaagent's `Config` class. We'll need to add the normalization if we aim to use `ConfigProperties` in the agent too.

**Additional context**
Related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6202

**Comment by trask** [comment]
> Isn't there the other option of _not_ normalizing hyphens when parsing environment variables / system properties? Would achieve the same affect as normalizing on get.

`get("otel.my-property")` would check for both `"otel.my-property"` and `"OTEL_MY_PROPERTY"`?

that sounds like a good option

**Comment by mateuszrzeszutek** [comment]
That is an option, although if we want to preserve the sysprop->envvar->default priority ordering it would require keeping 3 separate maps for default properties, env vars and system properties - we'd have to make up to 3 map lookups for every property get.
