### ISSUE TITLE
 Implement JSON logging exporter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#457]
The list will be defined in open-telemetry/opentelemetry-specification#6

This is the work left from https://github.com/open-telemetry/opentelemetry-java/issues/277.

**Comment by KrzysztofKowalczyk** [comment]
Can I suggest adding a standard JSON format definition and potentially consider standard JSON exporter? 

Many organisation have existing infrastructure to collect logs in ELK, Splunk or other. It is sometimes hard to introduce another sidecar/agent/collector talking in another protocol to another service. Also those tools in future could recognise standard Open Telemetry data, store them in efficient way and present them properly. 

There is an option to use Open Telemetry Proto and use JSON format, but:
- OpenTelemetry seems to be not using it's own Protobuf classes at all at the moment (at least for tracing)
- JSON protobuf format is somewhat verbose

If I take SpanData and convert it to Span it looks more or less like that:
```json
{
  "traceId": "Q2LN6qEV/WA06wPpF1nd7g==",
  "spanId": "y3PM9Aprh48=",
  "name": "GET /hello/{name}",
  "startTime": "2019-10-14T20:23:57.614000395Z",
  "endTime": "2019-10-14T20:23:59.935991949Z",
  "attributes": {
    "attributeMap": {
      "http.path": {
        "stringValue": "/hello/Jack"
      },
      "http.method": {
        "stringValue": "GET"
      },
      "http.server": {
        "boolValue": true
      }
    }
  },
  "timeEvents": {
  },
  "links": {
  }
}
```

I did not map all fields here, but one can see that maps are verbose, empty collections could be skipped and there might be a better way to do tags, but it would work nonetheless.

**Comment by manoj260191** [comment]
Is this functionality has been implemented for opentelemetry-java, as i need to implement a functionality where span should be exported to file as json.

**Comment by KrzysztofKowalczyk** [comment]
It is pretty simple to achieve on your own, you can implement your own exporter that use for instance slf4j with logstash JSON encoder or similar.

I did try that with Jaeger (In Jaeger you can extend Sender or Reporter):
https://github.com/KrzysztofKowalczyk/demo-tracing-through-logs/blob/master/tracing-with-logback-json-classic/src/main/groovy/demo/export/LogTraceReporter.groovy

You could also try to miss-use protobuf exporter, as there is way to get JSON out of protobuf, but it would not be pretty as mentioned above.

**Comment by manoj260191** [comment]
> It is pretty simple to achieve on your own, you can implement your own exporter that use for instance slf4j with logstash JSON encoder or similar.
> 
> I did try that with Jaeger (In Jaeger you can extend Sender or Reporter):
> https://github.com/KrzysztofKowalczyk/demo-tracing-through-logs/blob/master/tracing-with-logback-json-classic/src/main/groovy/demo/export/LogTraceReporter.groovy
> 
> You could also try to miss-use protobuf exporter, as there is way to get JSON out of protobuf, but it would not be pretty as mentioned above.

Thank you for suggestion, I will try to implement same in java.

**Comment by thisthat** [comment]
If you succeed, a PR is well welcomed :)

**Comment by manoj260191** [comment]
> If you succeed, a PR is well welcomed.
Definitely

**Comment by jkwatson** [comment]
Closing this, as we now have the `opentelemetry-exporter-logging-otlp` module that should fulfill the need.
