### ISSUE TITLE
How to pass value in the trace context?

### ISSUE THREAD

**Issue by kevinten10** [open-telemetry/opentelemetry-java#4587]
**Is your feature request related to a problem? Please describe.**

I am trying to pass a value in the `trace context`.

Initially, I used this way:

```java
        // trace
        // span
        {
            // try to set 'value' to the `context`
            Context.current().with(ContextKey.named("test-key"), "test-value").makeCurrent();

            // try to get 'value' from the `context`
            Object value2 = Context.current().get(ContextKey.named("test-key"));

            // but the value2 is null
        }
        // span end
```

But I see that the `ContextKey` uses a reference comparison, which causes me to be `null` when get the value

But if I want to pass the key object all the `trace`, it is too complicated, I need to do a set of `threadlocal` tools (if I do a threadlocal tool, why should I use the context transfer function of opentelemetry?)

**Describe the solution you'd like**

I would like to ask, is there a way to achieve such an effect in a trace?
like the way in some other frameworks:

```java
TraceContext traceContext = Cat.getTraceContext(true);

 // try to set 'value' to the `context` 
traceContext.add("test-key","test-value"); 

// try to get 'value' from the `context` 
String value2 = traceContext.get("test-key");

 // the value2 is 'test-value'
```

**Comment by jkwatson** [comment]
Our Context is intentionally immutable, and requires reference-only keys, also intentionally. You should declare your key as a constant somewhere and only access the value via that constant.

This isn't something we will be changing. You don't have to put the Context into a thread local with `makeCurrent`. You can just get the value returned from the `with` function and pass it around however you like.

**Comment by kevinten10** [comment]
Like the request model, when request-trace=1:1

Exist in constants, whether it may cause memory leak?

**Comment by jkwatson** [comment]
> Like the request model, when request-trace=1:1
> 
> Exist in constants, whether it may cause memory leak?

I don't understand what you are asking.
