### ISSUE TITLE
Why does the property `otel.experimental.sdk.enabled` contains `experimental`

### ISSUE THREAD

**Issue by Emily-Jiang** [open-telemetry/opentelemetry-java#4589]
Is the property `otel.experimental.sdk.enabled` on the whole an experimental? If yes, when will it be stable? If not, why use the word `experimental`?

**Comment by jkwatson** [comment]
Yes, it is experimental. It will be stabilized when we have a specification for it.

**Comment by brunobat** [comment]
@jkwatson How can we help to make this property stable? Any idea on the remaining work?

**Comment by jkwatson** [comment]
It needs to be added to the official spec. Not sure, but I think there's existing work ongoing.

**Comment by Emily-Jiang** [comment]
@jkwatson I would probably find out by checking out the code base. I am wondering whether you know for sure whether there is a programmatic api to switch on/off OTel (basically does the same thing as the configuration property `otel.experimental.sdk.enabled`.

**Comment by jkwatson** [comment]
> @jkwatson I would probably find out by checking out the code base. I am wondering whether you know for sure whether there is a programmatic api to switch on/off OTel (basically does the same thing as the configuration property `otel.experimental.sdk.enabled`.

IIRC, this just turns off all the configuration of the SDK, so returns the equivalent of just creating an SDK instance from a new builder with nothing else called on the builder.

**Comment by brunobat** [comment]
Will ask tomorrow on the Java meeting the best course of action.

**Comment by jack-berg** [comment]
Resolving in #4810.
