### ISSUE TITLE
Improved support to enable Authentication on otlp exporters (or any exporter?)

### ISSUE THREAD

**Issue by sfriberg** [open-telemetry/opentelemetry-java#4590]
**Is your feature request related to a problem? Please describe.**
The problem I'm trying to solve is to send metrics and traces (later logs) over OTLP with authentication. This works well with otel-collector-contrib with using the authentication extensions. However this would require the Java application to use send through a locally running collector which would then be used to send to the next step in the pipeline. This adds resource usage and complexity.

In Java I can create a SpanExporter implementation that simply wraps OtlpHttpSpanExporter and set it up to be loaded by the java-instrumentations autoconfiguration. The issue here is that headers are being set as part of creating the exporter and can't be changed, while they are actually used on a per request basis. This requires the wrapper to teardown and setup a completely new delegated OtlpHttpSpanExporter each time the auth token needs to be refreshed and the header updated.

For metrics as far as I can tell there is no support yet for easily setting up a your own MetricExporter using autoconfiguration (but might have just missed it).

**Describe the solution you'd like**
I can see to straightforward ways to expand the capabilities here, but there are most likely other ideas out there.

1. Enable headers to accept a lambda that returns the string and is called on each request. This should be enough to at least support oauth setting a Authorization token.
2. Extend the SDK API to enable a type of Auth extension similar to otel-collector. This would allow building more complex authentication protocols that might require more than just a simple header call back.

**Describe alternatives you've considered**
Running otel-collector as an extra step, or creating wrapped exporters.

CC @trask

**Comment by sfriberg** [comment]
Found ConfigurableMetricExporterProvider which will enable the metrics exporter part, what I was referring to above was AutoConfigurationCustomizer and addMeterProviderCustomizer.

**Comment by sfriberg** [comment]
In the collector an exporter can depending on if it exports via HTTP or GRPC pull in different standard configurations as part of it's own configuration.

```
// HTTPClientSettings defines settings for creating an HTTP client.
type HTTPClientSettings struct {
...
	// Additional headers attached to each HTTP request sent by the client.
	// Existing header values are overwritten if collision happens.
	Headers map[string]string `mapstructure:"headers"`

	// Custom Round Tripper to allow for individual components to intercept HTTP requests
	CustomRoundTripper func(next http.RoundTripper) (http.RoundTripper, error)

	// Auth configuration for outgoing HTTP calls.
	Auth *configauth.Authentication `mapstructure:"auth"`
...
```

**Comment by sfriberg** [comment]
Would the following expansion of the OtlpHttp exporters be acceptable? This would allow for a very trivial implementation of authentication.

https://github.com/sfriberg/opentelemetry-java/pull/1/files

```
import io.opentelemetry.exporter.otlp.http.metrics.OtlpHttpMetricExporter;
import io.opentelemetry.sdk.common.CompletableResultCode;
import io.opentelemetry.sdk.metrics.InstrumentType;
import io.opentelemetry.sdk.metrics.data.AggregationTemporality;
import io.opentelemetry.sdk.metrics.data.MetricData;
import io.opentelemetry.sdk.metrics.export.MetricExporter;
import java.util.Collection;

public class AuthMetricExporter implements MetricExporter {

    private final MetricExporter delegate;

    AuthMetricExporter(Auth auth, String endpoint) {
        this.delegate = OtlpHttpMetricExporter.builder()
                .setAuthorization(() -> "Bearer " + auth.getToken())
                .setCompression("gzip")
                .setEndpoint(endpoint)
                .build();
    }

    @Override
    public CompletableResultCode export(Collection<MetricData> metrics) {
        return delegate.export(metrics);
    }

    @Override
    public AggregationTemporality getAggregationTemporality(InstrumentType instrumentType) {
        return delegate.getAggregationTemporality(instrumentType);
    }

    @Override
    public CompletableResultCode flush() {
        return delegate.flush();
    }

    @Override
    public CompletableResultCode shutdown() {
        return delegate.shutdown();
    }

    @Override
    public void close() {
        delegate.close();
    }
}

```

**Comment by anuraaga** [comment]
I think there can be something like `setAuthenticator` on the exporter builders like `OtlpGrpcSpanExporterBuilder.setAuthenticator`.

A callback that takes no parameters satisfies many auth but some need access to the request to sign it for example so it'd be good to be extendable to that. Maybe can have

```
interface Authenticator {
  void getHeaders(Consumer<Map<String, String>)
```

And in the future we can have a sub interface and use instanceof 

```
interface RequestAuthenticator extends Authenticator {

  void getHeaders(Map requestHeaders, byte[] requestBody, Consumer<Map>)
```

Note the use of a consumer callback since some auth needs to fetch from an external server or similar so should use async pattern.

**Comment by jack-berg** [comment]
> Enable headers to accept a lambda that returns the string and is called on each request. This should be enough to at least support oauth setting a Authorization token.

This is related to #4292. 

I believe this is a duplicate

**Comment by jack-berg** [comment]
What do folks think about adding "experimental" APIs for this while we hash out exactly what the contract needs to be long term? Could do something like we do for `RetryPolicy`, where we have methods on the delegate builders (i.e. [GrpcExporterBuilder](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#supporting-target-metadata-in-both-push-based-and-pull-based-systems)) that accept the experimental config, and have an internal but public method for reflectively setting it (i.e. [RetryUtils#setRetryPolicyOnDelegate](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/retry/RetryUtil.java#L58-L74)). 

Would allow us to get something into users hands fairly quickly, while reserving the ability to change the contract until we get a couple of implementations to increase confidence.

**Comment by sfriberg** [comment]
@jack-berg if I follow your reason adding to OkHttpExporterBuilder.java would be OK, but we want to avoid adding it to OtlpHttpSpanExporterBuilder.java.

Currently I have it in both places, but can look at how I can remove the OtlpHttp... one and see how I can build my custom exporter using OkHttpExporter directly.

**Comment by jack-berg** [comment]
> if I follow your reason adding to OkHttpExporterBuilder.java would be OK, but we want to avoid adding it to OtlpHttpSpanExporterBuilder.java.

Correct. As soon as its available on OtlpHttpSpanExporterBuilder its part of our public API and we have to maintain backwards compatibility going forward. [RetryUtils#setRetryPolicyOnDelegate](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/retry/RetryUtil.java#L58-L74) is a decent example to mimic. Here's an [example](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java#L130) of it being used. It's a bit more clunky to use, but because the only public accessor is in `RetryUtils` which lives in an `*.internal` package, we can change the contract if needed.

**Comment by sfriberg** [comment]
Seems to make for a pretty clean solution as well. https://github.com/sfriberg/opentelemetry-java/pull/2

The extension is still easy to implement

```
public class AuthMetricExporter implements MetricExporter {

    private final MetricExporter delegate;

    AuthMetricExporter(Auth auth, String endpoint) {
        OtlpHttpMetricExporterBuilder builder = OtlpHttpMetricExporter.builder()
                .setCompression("gzip")
                .setEndpoint(endpoint);
        Authenticator.setAuthenticatorOnDelegate(builder,
                (Consumer<Map<String, String>> headers) -> {
            headers.accept(Map.of("Authorization", "Bearer " + auth.getToken()));
        });
        this.delegate = builder.build();
    }
```


@anuraaga Not sure if this is how you intended the Consumer pattern to look like.

**Comment by sfriberg** [comment]
Merged internal API. Will be re-reviewed again once https://github.com/open-telemetry/opentelemetry-specification/issues/1344 is resolved.
