### ISSUE TITLE
Add Influx Client as Metric Exporter

### ISSUE THREAD

**Issue by MariusBrill** [open-telemetry/opentelemetry-java#4598]
**Is your feature request related to a problem? Please describe.**
Currently OpenTelemetry does not provide a default InfluxDB Exporter. Since we would like to add an InfluxDB Exporter to the [inspectIT Ocelot](https://github.com/inspectIT/inspectit-ocelot), we would like to contribute to Open Telemetry and add this exporter to the project.

**Describe the solution you'd like**
The exporter would use the [Influx Java Client](https://github.com/influxdata/influxdb-client-java#how-to-use) and would integrate it similar to the OTLP Metric Exporter to ensure a seamless integration into OTLP.

**Additional context**
Could you guys give me short feedback if this would fit for you into the project? I am open to discuss changes/alternatives.

Best Regards
Marius

**Comment by jkwatson** [comment]
I think this is a great idea, but until there's a official specification for this, it would need to live in the [contrib](https://github.com/open-telemetry/opentelemetry-java-contrib) repo, rather than the core repo.

**Comment by MariusBrill** [comment]
Hey @jkwatson,
I just opened the corresponding issue in the contrib repo. Thanks alot!

Greetings
Marius

**Comment by MariusBrill** [comment]
Hi @jkwatson,

sounds cool! It's always awesome to contribute features others too see a need in :) Are there any learnings or pitfalls you encountered that i should be aware of during development?

**Comment by jkwatson** [comment]
> Hi @jkwatson,
> 
> sounds cool! It's always awesome to contribute features others too see a need in :) Are there any learnings or pitfalls you encountered that i should be aware of during development?

Not really. My personal project only uses gauges, so I only implemented what was the absolute minimum to support that. :)

**Comment by jack-berg** [comment]
Closing in favor of [open-telemetry/opentelemetry-java-contrib#394](https://github.com/open-telemetry/opentelemetry-java-contrib/issues/394).
