### ISSUE TITLE
Jaeger Grpc Exporter export Span Data with trace flags

### ISSUE THREAD

**Issue by blueswhisper** [open-telemetry/opentelemetry-java#4601]
**Is your feature request related to a problem? Please describe.**
[Jaeger Collector Proto](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/jaeger-proto/src/main/proto/jaeger/api_v2/model.proto#L59) has define flags field. But [SpanMarshaler](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/SpanMarshaler.java#L158) not write trace flags when postSpan request.

**Comment by jkwatson** [comment]
Before implementing this, I'd like to have this added to the [opentelemetry specification for the Jaeger exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#opentelemetry-to-jaeger-transformation).

**Comment by blueswhisper** [comment]
Any schedule for this specification I can track ?

**Comment by jkwatson** [comment]
> Any schedule for this specification I can track ?

someone (you?) will need to drive this to happen. It won't happen without a sponsor and someone willing to make sure it happens. :)

**Comment by jack-berg** [comment]
The jaeger exporters were removed in #6119 so this is no longer relevant.
