### ISSUE TITLE
Fix release contributors generator action

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4617]
The release process fails to generates the set of contributors. When I recently ran the 1.16.0 release, it generated the [release notice](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.16.0) and [discussion](https://github.com/open-telemetry/opentelemetry-java/discussions/4606) as:
```
This release targets the OpenTelemetry SDK 1.16.0.

....

### 🙇 Thank you
This release was possible thanks to the following contributors who shared their brilliant ideas and awesome pull requests:

@
```
The discussion has a change history which allows you to see the edits I manually made to get it right. 

When I manually ran the script locally to get the list of contributors, I noticed it wasn't working until I ran `git fetch --all`. I suspect that when the action is running in github actions, its missing a tag ref that it depends on to calculate the time window it uses to query for contributors. 

cc @trask

**Comment by trask** [comment]
oops! I will fix
