### ISSUE TITLE
span.recordException() with timestamp

### ISSUE THREAD

**Issue by sambishop** [open-telemetry/opentelemetry-java#4629]
**Is your feature request related to a problem? Please describe.**
I'm using this library as part of a project where I have my own clock.  I'm able to ensure consistency between OTEL spans and the data recorded elsewhere because most of the time-related `Span` methods accept timestamps.  However, there isn't an overloaded `recordException()` method on the `Span` interface that accepts a timestamp, so exceptions are recorded with a different time source than the other span data.

**Describe the solution you'd like**
Consistent with the `addEvent()` and `end()` methods, two more `recordException()` methods that take `Instant timestamp` and `long timestamp`/`TimeUnit unit` arguments.

**Describe alternatives you've considered**
This seems straightforward.  I almost skipped to opening a PR until I realized that it would be a breaking change between the API and SDK libraries.

**Additional context**
The `recordException()` method appears to just add an event, so I may duplicate its implementation for now but use my own clock.

**Comment by jack-berg** [comment]
Have you considered providing your own clock to `SdkTracerProvider` via `SdkTracerProviderBuilder#setClock`?

**Comment by sambishop** [comment]
It's a library, so I don't have control over the SDK configuration.

**Comment by jack-berg** [comment]
I wasn't involved in the design of the trace API so I'm not sure if this omission was intentional or an oversight. Maybe @jkwatson can provide some context.

**Comment by jkwatson** [comment]
> I wasn't involved in the design of the trace API so I'm not sure if this omission was intentional or an oversight. Maybe @jkwatson can provide some context.

I recommend asking in the specs. I don't remember, TBH.

**Comment by sambishop** [comment]
Sounds good.  I didn't realize that the APIs were so tightly bound to the spec.  Thanks everyone!
