### ISSUE TITLE
Enhance tracing in otel-demo for v1 release

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-java#4638]
Tracing instrumentation needs to be enhanced in the community demo in preparation for the v1 release.

Referencing issue:
https://github.com/open-telemetry/opentelemetry-demo/issues/235

**Comment by jkwatson** [comment]
I don't think this issue belong in this repository. Why was it created here?

**Comment by cartersocha** [comment]
The OTel demo is the community showcase for various features by language. Many new users will be using it as an onboarding & best practices tool. 

My thought is that the Java community would have an interest in ensuring the demo accurately represents the current best state of the SDK.

**Comment by jkwatson** [comment]
But this repository doesn't contain any demo code or instrumentation. The issue should live where the changes are needed.

**Comment by cartersocha** [comment]
The wording is a bit specific here but the generic ask is help from the java community on fleshing out the community example. We've had similar asks on other language sigs. However, I didn't realize Java had so many different repos.

Do you think the demo support ask would make more sense on the instrumentation repo or the java-docs repo?

**Comment by jkwatson** [comment]
> The wording is a bit specific here but the generic ask is help from the java community on fleshing out the community example. We've had similar asks on other language sigs. However, I didn't realize Java had so many different repos.
> 
> Do you think the demo support ask would make more sense on the instrumentation repo or the java-docs repo?

I think that the ask should be to the people who will be doing the work. I very much doubt that any of the maintainers of this project will have any time to work on this. I can't answer for the instrumentation project, but I assume that's true there as well.

**Comment by trask** [comment]
@cartersocha I'd recommend tracking the issue in the demo repo where the code lives, but feel free to tag @open-telemetry/java-instrumentation-maintainers and we can at least help review the work being done there
