### ISSUE TITLE
Intercepting Spans to enhance them before getting exported

### ISSUE THREAD

**Issue by LikeTheSalad** [open-telemetry/opentelemetry-java#4679]
**Is your feature request related to a problem? Please describe.**
I'm working on an OTel Android instrumentation and currently there's an issue with the current time sync across mobile devices and the observability backend. It's sorted if I can send an extra span attribute with the mobile's current time right before exporting the span to the backend, so probably a good place to do so would be in the SpanExporter.export method, however, the span representation provided in there (SpanData) is immutable. So I was wondering if it'd be ok to add a mechanism to "enhance" the span's data, or at least its attributes as part of the exporting process?

**Describe the solution you'd like**
Adding an "interceptor" mechanism that allows to enhance spans right before exporting them.

**Describe alternatives you've considered**
Wrapping a SpanExporter so that I can intercept spans within the "export" method before passing them to the wrapped exporter, however, due to the immutability of SpanData, I'd also need to wrap it around a SpanData that would add the extra attributes when the `SpanData.getResource()` method is called, but that's not ideal, especially because I'd need to call all the wrapped SpanData's methods as well, which might need to be kept up to date in time due to potential changes to SpanData in the future.

**Additional context**
N/A

**Comment by jkwatson** [comment]
we have the `DelegatingSpanData` class to facilitate these use cases. Any more significant changes would definitely require a change to the specification.

**Comment by LikeTheSalad** [comment]
Thanks @jkwatson, I wasn't aware of the `DelegatingSpanData` class which seems to solve my main concern about having to keep a custom wrapper of mine updated!

Cheers.
