### ISSUE TITLE
deltaPreferred should be configure to use less memory?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#4680]
The `deltaPreferred` https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/AggregationTemporalitySelector.java#L37 is inconsistent with other implementation like golang which uses CUMULATIVE for `OBSERVABLE_COUNTER` to minimize memory usage.

**Comment by jack-berg** [comment]
The java implementation is correct. See the [spec definition](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/metrics/sdk_exporters/otlp.md#L50-L51):

> Choose Delta aggregation temporality for Counter, Asynchronous Counter and Histogram instrument kinds, choose
  Cumulative aggregation for UpDownCounter and Asynchronous UpDownCounter instrument kinds.

The idea isn't to be a minimal memory usage, but to reflect the fact that the delta backends we discussed all preferred cumulative temporality for non-monotonic cumulative sums.

**Comment by bogdandrutu** [comment]
We should also offer a "minimal memory" option, which does delta for sync instruments (including updown) and cumulative for async (including counter)

**Comment by jack-berg** [comment]
If the spec adds it, we'll add it 🙂

Users do currently have the ability to define their temporality preference for each instrument type, so additional options are just for added convenience.

**Comment by jack-berg** [comment]
I'm going to close this issue because the implementation is currently aligned with the spec.
