### ISSUE TITLE
Is Tracer Provider Mandatory?

### ISSUE THREAD

**Issue by AlexP-Coding** [open-telemetry/opentelemetry-java#4681]
If I only care for sending metrics, is it possible to only set a MeterProvider and not a TracerProvider while building an instance of OpenTelemetry?
What are the consequences of using only a MeterProvider?

**Comment by jkwatson** [comment]
yes, this should be fine. Any API calls that use the tracer provider will get a no-op version.

**Comment by AlexP-Coding** [comment]
Understood, thank you!
