### ISSUE TITLE
WARNING: Failed to export metrics. Server responded with HTTP status code 415

### ISSUE THREAD

**Issue by AlexP-Coding** [open-telemetry/opentelemetry-java#4685]
I've been trying to periodically send a value as a metric to dynatrace using an ```OtlpHttpMetricExporter``` with a ```PeriodicMetricReader```. 

However, I've been getting the same error over and over again: 
```WARNING: Failed to export metrics. Server responded with HTTP status code 415. Error message: Unable to parse response body, HTTP status message: Unsupported Media Type```. 

On the other hand, using a OtlpGrpcMetricExporter instead returns:
```WARNING: Failed to export metrics. Server responded with HTTP status code 200. Error message: OK```

Both these warnings come from ```io.opentelemetry.sdk.internal.ThrottlingLogger doLog```

What am I doing wrong?

Code:

```
MetricExporter metricExporter = OtlpHttpMetricExporter.builder()
				.setEndpoint(Constants.DYNATRACE_ENDPOINT_M)
			        .addHeader(Constants.DYNATRACE_AUTH,Constants.DYNATRACE_TOKEN)
				.build();

SdkMeterProvider sdkMeterProvider = SdkMeterProvider.builder()
				.registerMetricReader(PeriodicMetricReader.builder(metricExporter).build())
				.build();	
		
OpenTelemetry openTelemetry = OpenTelemetrySdk.builder()
					.setMeterProvider(sdkMeterProvider)
					.buildAndRegisterGlobal();

Meter meter = openTelemetry.meterBuilder(Constants.INSTRUMENTATION_LIB)
				.setInstrumentationVersion(Constants.INSTRUMENTATION_VERSION)
				.build();

// Builds set of metric's attributes
Attributes attributes = getAttributes();
		
// Builds gauge meter to record metric
meter.gaugeBuilder(metricStorage.getId()) // sets metric label
			.buildWithCallback(measurement -> { 
			measurement.record(5.00, attributes); // sets metric value and attributes
			});

```

**Comment by jack-berg** [comment]
What backend are you sending those to? 

The "WARNING: Failed to export metrics. Server responded with HTTP status code 415. Error message: Unable to parse response body, HTTP status message: Unsupported Media Type" message is pretty self explanatory. The `OkHttpMetricExporter` exports with `Content-Type: application/x-protobuf`, per the specification. It appears that your server doesn't accept that. 

The "WARNING: Failed to export metrics. Server responded with HTTP status code 200. Error message: OK" error message is produced when the server isn't following the gRPC protocol and doesn't return a gRPC status code in the `grpc-status` response header. Strange that your server accepts the payload but doesn't appear to be implement the gRPC protocol.

**Comment by AlexP-Coding** [comment]
"The OkHttpMetricExporter exports with Content-Type: application/x-protobuf, per the specification"
Does this mean I should import the opentelemetry proto repository, also, in this case?

I am attempting to send the metric (currently static, for testing) to Dynatrace (```Constants.DYNATRACE_ENDPOINT_M="https://{id}.live.dynatrace.com/api/v2/metrics/ingest"```)

The program the code is from is running on my own computer

Thank you for your continued patience

**Comment by jack-berg** [comment]
Does dynatrace accept OTLP metrics? Based on this [documentation](https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/opentelemetry-metrics/instrument-for-metrics/opent-java-metrics) it appears they publish their own exporter which presumably uses a proprietary protocol.

**Comment by AlexP-Coding** [comment]
From what I understand, using OTLP metrics is one of the options available for dynatrace metrics ingestion. 

They do publish their own exporter (and that one does work), however I am now interested in figuring out why the other two exporters do not work, if possible.

**Comment by jkwatson** [comment]
> From what I understand, using OTLP metrics is one of the options available for dynatrace metrics ingestion.
> 
> They do publish their own exporter (and that one does work), however I am now interested in figuring out why the other two exporters do not work, if possible.

It sounds like you should probably work with Dynatrace on that, rather than opening an issue here.

**Comment by jack-berg** [comment]
I'm going to close this issue because it seems related to dynatrace's implementation. Please reopen if you have reason to believe code from this repository is involved in the issue!
