### ISSUE TITLE
SDK: Implement Jaeger exporter

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#469]
Implement span exporter for Jaeger server.

hint: import from OpenCencus.

**Comment by jpkrohling** [comment]
I'm working on this one.

**Comment by jpkrohling** [comment]
We have a few options here. 

1. The easiest for a first implementation is probably to add a dependency on the Jaeger Client for Java. A new OpenTelemetry `SpanExporter` would then create a Jaeger Span, which gets reported to Jaeger Agent/Collector via its own client;
1. For the long term, it might make sense to avoid a dependency to the Jaeger Client for Java. In the name of maintainability, we'd implement only gRPC/protobuf (preferred) or Thrift. Sending spans to the Jaeger Agent in protobuf format isn't supported yet, so, if we decide to use it already for the first implementation, we'd have support only for communication with the Jaeger Collector, bypassing the agent.

**Comment by jpkrohling** [comment]
cc @objectiser, @yurishkuro

**Comment by bogdandrutu** [comment]
Please for the moment put it in a separate gradle subproject under `exporters/` directory, so that SDK does not depend on this.

**Comment by jpkrohling** [comment]
@bogdandrutu, what's the preferred approach from other maintainers? Should we attempt to avoid a dependency to the Jaeger Client, or should we reuse the Jaeger Client when possible (making sure to isolate this as its own module)?

**Comment by bogdandrutu** [comment]
I think we aim to become the official client for Jaeger or (recommended), so I think we need to directly implement the wire protocol. Also we already have all the batching logic etc, so no point in using the client unless they have a raw client that is a helper to just talk to the server.

**Comment by jpkrohling** [comment]
> unless they have a raw client that is a helper to just talk to the server

There's a reporter+sender that could be directly used, but we might want to start supporting gRPC only, as we were already looking to phase out the Thrift channels. And for gRPC, it's quite easy to build the client. The biggest "problem" is to get the proto files, or their outcomes (generated client/models).
