### ISSUE TITLE
Update exponential histogram to use upper-inclusive boundaries

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-java#4698]
**Describe the request**

Specification PR https://github.com/open-telemetry/opentelemetry-specification/pull/2633 has changed the boundary conditions for exponential histograms and specified that SDKs SHOULD be exact for powers-of-two. This implies a fairly complex change, see https://github.com/open-telemetry/opentelemetry-go/pull/2982 for example.

**Comment by jack-berg** [comment]
I've been working on this! Will have a PR sometime today.

**Comment by jack-berg** [comment]
FYI, the corresponding change to the [proto definition](https://github.com/open-telemetry/opentelemetry-proto/pull/409) has yet to be merged / released. Despite this, I think its ok for us to proceed with this change beforehand given the experimental status of our exponential histograms.
