### ISSUE TITLE
TraceId is not propagated completely when using Camel-Quarkus -> Quarkus and ottrace propagator

### ISSUE THREAD

**Issue by iabughosh** [open-telemetry/opentelemetry-java#4707]
Dears,

I am using Camel-Quarkus and ottrace propagator, I already opened and issue at Quarkus Project [here](https://github.com/quarkusio/quarkus/issues/27371) with all details, but after delved deeper into this, it looks like a propagator issue rather than Camel or Quarkus issue.

At [OtTracePropagator](https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/OtTracePropagator.java) I found this line : 

 ```
 // Lightstep trace id MUST be 64-bits therefore OpenTelemetry trace id is truncated to 64-bits
  // by retaining least significant (right-most) bits.
  setter.set(
      carrier, TRACE_ID_HEADER, spanContext.getTraceId().substring(TraceId.getLength() / 2));
```

I read the comment above but I didn't get what is Lightstep, doesn't this cause similar bug to what I have :

Got two different traces (one 32 characters and the propagated one is 16) and they are not linked together on Jaeger.

Appreciate your feedback/help here.

**Comment by jkwatson** [comment]
Unless you have a strong reason to use the ottrace propagator, you shouldn't be using it; if you do have a good reason, you might need to be using it everywhere, and not assume that traces will propagate correctly without some custom interop work. ottrace doesn't interoperate with the other propagators in any way that I know of.

**Comment by iabughosh** [comment]
I switched propagator to 'jaeger' and everything worked smoothly, thanks for the hint @jkwatson!

Just for curiosity, what is the use cases for ottrace exporter ?

**Comment by jkwatson** [comment]
> Just for curiosity, what is the use cases for ottrace exporter ?

As far as I know, only legacy users who are already using it (probably Lightstep customers, I would guess).  

If you have a choice, we recommend using the W3C trace context propagator, as the first-class propagator for OpenTelemetry.
