### ISSUE TITLE
SemanticAttributes class is outdated

### ISSUE THREAD

**Issue by brunobat** [open-telemetry/opentelemetry-java#4715]
After 1.17.0 the attribute  net.sock.peer.addr
is being used, at least in GRPC calls but it’s not showing up in the SemanticAttributes class.

io.opentelemetry.semconv.trace.attributes.SemanticAttributes does not have attribute  net.sock.peer.addr and others recently introduced in the otel specification

That class needs regeneration.

Artifacts: `opentelemetry-semconv`
Version: `1.17.0-alpha`

**Environment**
Compiler: 11.0.15, vendor: Eclipse Adoptium
OS: Mac: 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64

**Comment by jack-berg** [comment]
1.17.0 uses the semantic conventions from version 1.12.0 of the specification, which [did not include](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.12.0/semantic_conventions/trace/general.yaml#L2) `net.sock.peer.addr`. 

`net.sock.peer.addr` [does exist](https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/general.yaml#L49-L53) in the yet to be released 1.13.0 of the spec. Once released, we'll bump semconv to match, and the changes will be reflected in release, most likely 1.18.0.

**Comment by jkwatson** [comment]
> Then metrics are being produced already with the 1.13.0 semantics. Maybe we need some tests around this.

which metrics? From which instrumentation?

**Comment by trask** [comment]
we may have jumped the shark and updated instrumentation to use the new spec attributes after they were merged but before they were released

> Maybe we need some tests around this

I believe this is ok as long as we are not dealing with stable portions of the specification
