### ISSUE TITLE
Add ability to distinguish traces from different services located in the same JVM

### ISSUE THREAD

**Issue by Jokser** [open-telemetry/opentelemetry-java#472]
The issue is coming from a discussion https://github.com/census-instrumentation/opencensus-java/issues/1952

There is a problem about how to distinguish traces from different services located in the same JVM. I mean service in terms of Zipkin exporter configuration. As I see the exporter has "service" field which represents a logical separation between some business and internal processes.
Let's suppose the situation if you have some web-service that does some business logic and embedded database for storing/querying a data to it. Physically they share the same JVM but logically it's two different service - business and db.
At the moment we can use tags to separate spans come from business service and db but both of them will relate to the same service. 
This problem can be resolved by using separated tracing components stacks in the same JVM but the ability to create several tracing components is a difficult task at the moment because of the singleton nature of some internals.
Another approach is that we can use different span exporters with different "service" parameters. At the moment all spans in JVM go through all registered exporters. We can add span filtering for exporters that some spans go to one exporter while some to another using "resource" field in Span.
WDYT?

**Comment by adriancole** [comment]
if you go with exporter dispatch approach, you should probably implement
localRoot so that the service label can be applied consistently through the
subtree. that's what it was made for (in brave)

**Comment by pavolloffay** [comment]
hi @Jokser, It seems what you are describing is related to https://github.com/open-telemetry/opentelemetry-java/issues/308 and PR https://github.com/open-telemetry/opentelemetry-java/pull/350.

The PR https://github.com/open-telemetry/opentelemetry-java/pull/350 adds the ability to have multiple tracers.

**Comment by Jokser** [comment]
@pavolloffay @adriancole Thank you for the responses. Does it mean that the approach described in the issue you mentioned will only way to resolve the problem described here?
If you have the ability to create multiple tracers do we really need the ability to filter spans in exporters? Or it may be a useful feature anyway?

**Comment by adriancole** [comment]
multiple tracers will work if similarly scoped down the tree of requests and don't make local calls to things handled by other traces. if all tracers share the same exporter, you can increase the effectiveness of the batching handled there. If they share the same sampling impl, this can help avoid overrunning the policy you want because otherwise a rate is increased by tracer count (unless the sampler itself has some global coordination)

**Comment by jkwatson** [comment]
Now that the exporters all use the `Resource` `service.name` attribute, and we can very easily have multiple instances of the SDK, I think we can close this issue.
