### ISSUE TITLE
Container detection fails in kubernete v1.24.0+ environments

### ISSUE THREAD

**Issue by wzy531a** [open-telemetry/opentelemetry-java#4730]
**Describe the bug**
On cgroups with entries with the container format:
`11:devices:/system.slice/containerd.service/kubepods-pod87a18a64_b74a_454a_b10b_a4a36059d0a3.slice:cri-containerd:05c48c82caff3be3d7f1e896981dd410e81487538936914f32b624d168de9db0`
containerId will return as null.

**Steps to reproduce**
Any cgroup has colons

**What did you expect to see?**
ContainerId should be `05c48c82caff3be3d7f1e896981dd410e81487538936914f32b624d168de9db0`

**What did you see instead?**
Returns as `null`

**What version and what artifacts are you using?**
1.17.0

**Environment**
JDK 11
k8s v1.25.0
containerd 1.6.8

**Additional context**
The method of operating cgroupdriver as `systemd` is changed since containerd v1.5.0+, you can find the difference between [v1.5.0](https://github.com/containerd/containerd/blob/release/1.5/pkg/cri/server/helpers_linux.go#L64) and [v1.4.0](https://github.com/containerd/containerd/blob/release/1.4/cmd/ctr/commands/run/run_unix.go#L254).

**Comment by jkwatson** [comment]
Thanks for the report. Are you able to submit a PR to fix the issue?
