### ISSUE TITLE
Have opentelemetry-bom-alpha depend on opentelemetry-bom?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#4747]
I noticed in the instrumentation repo that `opentelemetry-instrumentation-bom-alpha` depends on `opentelemetry-bom-alpha` and `opentelemetry-bom`, which I think makes sense(?) to force all of those things to align.

For similar reason, I think it makes sense to have `opentelemetry-bom-alpha` depend on `opentelemetry-bom`, but don't have great instincts for boms, so not certain.

If you think it makes sense I can send PR, I'm working through the bom stuff currently in instrumentation repo, trying to align more with this repo where possible.

**Comment by jack-berg** [comment]
This makes sense to me 👍 . Extending BOMs (or platforms) is a use case that is described in the [gradle docs](https://docs.gradle.org/current/userguide/java_platform_plugin.html#sec:java_platform_bom_import), so seems reasonable for us to do.
