### ISSUE TITLE
Define Link attributes

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-java#475]
I'm currently working on #469 and I'm writing a translator, from OpenTelemetry Span to Jaeger Span, and I can't seem to find out how to properly convert the `SpanLinks` into `SpanRefs`, as I couldn't find where the link attributes are defined.

It looks like the SDK currently has no distinction about the types of Links that a span can have. I'm not sure if it's defined already by OpenTelemetry, but spans right now seem to have only links to parents, ignoring the reference type when a value is specified:

https://github.com/open-telemetry/opentelemetry-java/blob/0478651e34ede5960d6275626c97103e32470846/opentracing_shim/src/main/java/io/opentelemetry/opentracingshim/SpanBuilderShim.java#L77-L92

I'm using the OpenTracing shim for the example, as this is a sample consumer of the official API.

Should I just assume that Links are parent references for now?

**Comment by carlosalberto** [comment]
@jpkrohling correct, it's safe to assume Links are parent references (only).

**Comment by jpkrohling** [comment]
Thanks for the clarification, @carlosalberto!

**Comment by jpkrohling** [comment]
As per https://github.com/open-telemetry/opentelemetry-java/pull/481/files#r312577862 , those links should be `FOLLOWS_FROM` when converted to Jaeger.

**Comment by carlosalberto** [comment]
(It could still change to CHILD_FROM if we ever support different parent-child relationships in OTel in the future ;) )
