### ISSUE TITLE
Utilities for working with TLS - TlsUtil

### ISSUE THREAD

**Issue by vevikram** [open-telemetry/opentelemetry-java#4751]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Function Key Manager only allows certificate of type RSA.
 KeyFactory factory = KeyFactory.getInstance("RSA");
Other Certificate types should also be allowed like ECDSA 

**Describe the solution you'd like**
Their should be method which allows algorithm to be provided as a input to KeyFactory.

**Describe alternatives you've considered**

**Additional context**

**Comment by jack-berg** [comment]
Sorry, but its not clear what you're asking for. `TlsUtil` is an internal class. Maybe you're using it with an exporter and want additional certificate types to be supported? If so, please provide more information.
