### ISSUE TITLE
okhttp3 is a problematic transitive dependency in modular applications

### ISSUE THREAD

**Issue by io7m** [open-telemetry/opentelemetry-java#4777]
**Describe the bug**
Currently, `opentelemetry-exporter-otlp` depends on `opentelemetry-exporter-otlp-common`, which depends on `okhttp3`. `okhttp3` depends on various Kotlin artifacts, which are incompatible with JPMS modules due to having split packages, missing descriptors, and so on.

![modules](https://user-images.githubusercontent.com/612494/191992175-491a3724-a2bc-49d5-b89c-7d252145a001.png)

This leads to exceptions on attempting to boot applications when artifacts are on the module path:

```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okhttp3@4.10.0/okhttp3.ConnectionPool.<init>(ConnectionPool.kt)
	at okhttp3@4.10.0/okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3@4.10.0/okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at io.opentelemetry.exporter.internal@1.18.0/io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder.build(GrpcExporterBuilder.java:136)
	at io.opentelemetry.exporter.otlp@1.18.0/io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:153)
	at com.io7m.idstore.server@0.0.1-SNAPSHOT/com.io7m.idstore.server.internal.IdServerTelemetryService.create(IdServerTelemetryService.java:125)
	at com.io7m.idstore.server@0.0.1-SNAPSHOT/com.io7m.idstore.server.internal.IdServer.start(IdServer.java:131)
```

**Steps to reproduce**
Rather than running an application with the various artifacts present on the classpath, run the application with artifacts on the module path instead (with `-p`).

**What did you expect to see?**
No `java.lang.NoClassDefFoundError` errors.

**What did you see instead?**
See above!

**What version and what artifacts are you using?**

```
      ...
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>1.18.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-semconv</artifactId>
        <version>1.18.0-alpha</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-semconv</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-otlp</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk-metrics</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk-common</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk-trace</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-context</artifactId>
    </dependency>
  </dependencies>
```

**Environment**
Compiler: openjdk version "17.0.4.1" 2022-08-12
OS: Arch Linux (current)

**Additional context**

**Comment by io7m** [comment]
I think, ultimately, the "right" way to fix this is to provide an extra artifact that uses the JDK's built-in HTTP client instead of `okhttp`. Obviously this would only be compatible with JDK 11+.

**Comment by io7m** [comment]
At the moment, I'm hacking around this by squashing the Kotlin jars into a single jar, and removing their broken module descriptor. That's less than ideal, though.

**Comment by jkwatson** [comment]
I wonder if this could be related to the JDK bug that @aalmiray just uncovered: https://mastodon.social/@aalmiray/109796793626961093

**Comment by pedrolamarao** [comment]
I have just been bitten by this bug.
This is stopping us from adopting OpenTelemetry in at least one product.
Netty provides an HTTP client.
Is this project interested in a merge request to replace okhttp with netty?

**Comment by jkwatson** [comment]
> I have just been bitten by this bug. This is stopping us from adopting OpenTelemetry in at least one product. Is this project interested in a merge request to replace okhttp with netty or similar alternative?

Ideally, if it is possible, we would love to use the built-in java 11+ http client for everything but java 8, where modules aren't in play. I vaguely remember there maybe being a gap in the java 11 HttpClient around HTTP trailers that were required for grpc, maybe?

**Comment by jack-berg** [comment]
Well the java 11 http client would definitely work for otlp http/protobuf, which doesn't require trailers. Maybe that's a good enough reason for us to default otlp http/protobuf over otlp grpc.

**Comment by aalmiray** [comment]
An update on the bug linked by @jkwatson https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8301864

**Comment by jkwatson** [comment]
> An update on the bug linked by @jkwatson https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8301864

Thanks @aalmiray . Looks like we won't get help from the JDK on this one, unfortunately, and so should look into alternatives to okhttp for modular applications.

**Comment by pedrolamarao** [comment]
Is Apache HttpComponents an acceptable dependency? Or perhaps Netty? I have experience using these libraries and could contribute with this effort.

**Comment by jkwatson** [comment]
> Is Apache HttpComponents an acceptable dependency? Or perhaps Netty? I have experience using these libraries and could contribute with this effort.

As mentioned, if we want to replace okhttp (and we probably do), we should only do it for things that are modular, and we'd really like to use the built-in java 11+ http client in as many casses as is feasible. 

Both of those (apache's and netty's) also come with a bunch of fairly heavy dependencies, so I'm not sure they're great options for a general-purpose solution to this, either.

**Comment by pedrolamarao** [comment]
The status quo is such that Kotlin runtime is a dependency. Would not netty *reduce* the weight of dependencies?

**Comment by jkwatson** [comment]
> The status quo is such that Kotlin runtime is a dependency. Would not netty _reduce_ the weight of dependencies?

Maybe? But netty is very complex and layered, and using it is _not_ simple. okhttp has a very simple API to work with, unlike netty.

**Comment by Sineaggi** [comment]
As of kotlin 1.8, the contents of the jdk7 and jdk8 jars have been merged into the standard lib jar. https://kotlinlang.org/docs/whatsnew18.html#updated-jvm-compilation-target

This should eliminate issues with running kotlin in a modular app.

**Comment by jack-berg** [comment]
Closing now that the `opentelemetry-exporter-sender-jdk` alternative has been added in #5351. This [comment](https://github.com/open-telemetry/opentelemetry-java/discussions/5703#discussioncomment-6702697) describes how to use.
