### ISSUE TITLE
hasAttributesSatisfying vs hasAttributesSatisfyingExactly

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#4778]
SpanDataAssert has hasAttributesSatisfying and hasAttributesSatisfyingExactly, while AbstractPointAssert has only hasAttributesSatisfying but with behavior matching SpanDataAssert's hasAttributesSatisfyingExactly

DoubleExemplarAssert and LongExemplarAssert also have hasFilteredAttributesSatisfying, which matches the "*Exactly" behavior

Unfortunately I don't have any good ideas for what to do about it given stability of the artifact, but I did find it confusing when using AbstractPointAssert, I originally came here to open an issue about it missing an "*Exactly" variant before I dug a little further.

**Comment by jkwatson** [comment]
That sounds like a bug that needs to be fixed, which we can definitely do in stable artifacts.

**Comment by lmonkiewicz** [comment]
I would gladly take care of this issue, can it be assigned to me?
