### ISSUE TITLE
android example

### ISSUE THREAD

**Issue by manang** [open-telemetry/opentelemetry-java#4780]
Hi,
simple question: could you link me an android example? I need it just to start.
Thanks a lot
Angelo

**Comment by jkwatson** [comment]
Everything should just work normally per our standard docs with Android with one small exception. You *must* enable core-library desugaring, as otel uses java 8 constructs extensively.

**Comment by manang** [comment]
ok, could you show me how I can set the grpc exporter on a android device?
My problem is mainly this.
Thanks a lot
Angelo

**Comment by jkwatson** [comment]
It shouldn't be different from doing it on a standard JDK. What troubles are you having?

**Comment by manang** [comment]
Hi, thanks for your help.
I want to use this example:
https://github.com/open-telemetry/opentelemetry-java-docs/tree/main/autoconfigure
on java it works well and I launch it with
```
java -Dotel.exporter.otlp.endpoint=http://10.11.12.13:4317 \
     -Dotel.service.name=service-test \
     -Djava.util.logging.config.file=/path/to/resources/logging.properties \
     -cp build/libs/opentelemetry-examples-autoconfigure-0.1.0-SNAPSHOT-all.jar \
     io.opentelemetry.example.autoconfigure.AutoConfigExample 
```
On android I don't understand how to use.

I enabled in gradle this:
```
coreLibraryDesugaringEnabled true 
```
this is my code
```
class ExampleConfiguration {
    static OpenTelemetry initOpenTelemetry() {
        System.setProperty("otel.exporter.otlp.endpoint", "http://10.11.12.13:4317");
        System.setProperty("otel.service.name", "service-test");
        return AutoConfiguredOpenTelemetrySdk.initialize().getOpenTelemetrySdk();
    }
} 
```

```
public class MainActivity extends AppCompatActivity {
    private static final OpenTelemetry openTelemetry = ExampleConfiguration.initOpenTelemetry();
    private static final Tracer tracer = openTelemetry.getTracer("io.opentelemetry.example");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    public void onClickBtn(View v) {
        Span span = tracer.spanBuilder("span-test")
                .setAttribute("foo", 42)
                .setAttribute("bar", "abc")
                .startSpan();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            span.end();
        }
    }
} 
```
do you have idea about it?
Thanks a lot
Angelo

**Comment by manang** [comment]
the result is that I don't have a stream of data from the app to the server.
Could you point me an example that for sure works on android?
Thanks
Angelo

**Comment by manang** [comment]
so, do you have an example with manual configuration that can be used as test?
Thanks a lot
Angelo

**Comment by jkwatson** [comment]
I don't personally, but I know that splunk uses Otel in their android instrumentation here: https://github.com/signalfx/splunk-otel-android. @breedx-splk might be able to help out here.

**Comment by breedx-splk** [comment]
Hey @manang. As @jkwatson pointed out, the community doesn't yet have a known example of an android app using the otel core java sdk.  I'm sure [we would welcome one over here](https://github.com/open-telemetry/opentelemetry-java-docs). 

Splunk does have a working example in that repo linked above, but make sure you understand that it uses the Splunk android sdk, which is an additional layer built on the core repo. We in the process of donating it to OpenTelemetry (for RUM/client instrumentation).

I also am not sure if the service provider mechanisms work in android. Definitely worthy of some research/and an experiment, but I may not have time to attempt it any time soon.

It can be frustrating when you run something and nothing happens with no errors. One idea is to try and more closely [mimic how we create the vanilla, non-autoconfigure sdk](https://github.com/signalfx/splunk-otel-android/blob/main/splunk-otel-android/src/main/java/com/splunk/rum/RumInitializer.java#L118). Using the `LoggingSpanExporter` can also come in handy.

**Comment by breedx-splk** [comment]
Relates to #3438.

**Comment by ponomarevlm** [comment]
@manang [this](https://github.com/ponomarevlm/otel-demo-android/tree/master) may help.
It has some crutches but fully works.

**Comment by manang** [comment]
Thank you very much

**Comment by ponomarevlm** [comment]
@breedx-splk @jkwatson btw, FYI, still welcome for improvements [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8144)

**Comment by jkwatson** [comment]
> @breedx-splk @jkwatson btw, FYI, still welcome for improvements [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8144)

Urgh, yeah. I'm sure some work will be needed in getting the otel Context to properly propagate through Rx.

**Comment by Alka1703** [comment]
@manang Did you find a solution on how to run it on android app? 
Whenever I run the app get this error: 
`Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost:4317`

@ponomarevlm I tried cloning your [demo](https://github.com/ponomarevlm/otel-demo-android/tree/master) application but got the same error. 

I am new to Opentelemetry and may have some lack in understanding. 
What I want to do is send the data collected by Tracers and Spans in the android application to Jaeger (collector). 

I tried to create a dummy java project and add the same configuration as in my android application. I could successfully see the data in the Jaeger UI. 

So, what I understand is that apk will clearly not be able to interact with localhost:4317  and neither is Jaeger running on  my local machine able to collect the data from the application and display it. 
We need some kind of mediator/bridge where the application can send/ log the data which will in turn be used by Jaeger to process and display it.  But I am not sure how to implement it.

**Comment by breedx-splk** [comment]
When you run from an emulator, its essentially like a virtual machine. If you configure the exporter to send to the true IP address of the host jaeger is listening on (not localhost), it should work.

**Comment by Alka1703** [comment]
Thanks @breedx-splk . This helped

**Comment by cforce** [comment]
@breedx-splk  "We in the process of donating it to OpenTelemetry (for RUM/client instrumentation)."
Is there any pull request/branch/activity in github you can link where this work is visible? Is the RUM (still) based on closed source or dedicated to protocol which are not part of opensource otel project or is it just a different "cfg" to use otlp and any compatible receiver on the other side like e.g. an otel colletcor:

How does the example https://github.com/ponomarevlm/otel-demo-android/tree/master differs from the RUM/SPlunk instrumentation.  Does the example from  @ponomarevlm  does also the plumbing to see android apps as "isolated" services on otel but running on the the same jvm(android) and support the features lime RUM does? 

* Crash reporting
*   ANR detection
*  Network change detection
*  Full Android Activity and Fragment lifecycle monitoring
*  Access to an OkHttp3 Call.Factory implementation for monitoring http client requests
*  APIs to redact any span from export, or change span attributes before export
*  Slow / frozen render detection
*  Offline buffering of telemetry via storage

**Comment by mateuszrzeszutek** [comment]
Hey @cforce ,

The Android instrumentation was recently donated to OpenTelemetry, here's the repo: https://github.com/open-telemetry/opentelemetry-android
It's almost empty for now, but you can expect more things being added as people start working on that.

**Comment by breedx-splk** [comment]
@cforce You might want to follow [this issue](https://github.com/open-telemetry/opentelemetry-android/issues/8) as things start picking up speed in the android repo. Thanks!

**Comment by MaximKrasikov** [comment]
@Alka1703 How did you solve the problem with launching a demo project? I have the same problem: Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost:4317

**Comment by jack-berg** [comment]
Closing since there is an official `opentelemetry-android` repo now.
