### ISSUE TITLE
Move opentelemetry-extension-aws to contrib

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4831]
This is the last remaining item of #4661. Splitting it out to avoid the noise of the larger conversation. 

Here's the last [comment](https://github.com/open-telemetry/opentelemetry-java/issues/4661#issuecomment-1227751126) about `opentelemetry-extension-aws`:

> The opentelemetry-extension-aws extension. As mentioned https://github.com/open-telemetry/opentelemetry-java/issues/4661#issuecomment-1224676203, we can leave it where it is as an exception. However, if we don't need to continue publishing stable artifacts forever, it seems like quite an odd exception. In that case, would be better to move it to opentelemetry-java-contrib and include it in the proposed opentelemetry-javaagent-contrib-{version}.jar.

We've decided we don't need to publish stable artifacts forever. The only reason **not** to move it to `opentelemetry-java-contrib` today is because the otel java agent still includes it. Here are the options I see:

1. Move to contrib. Have the otel java agent depend on the contrib artifact 1 minor version behind the latest.
2. Move to contrib. Remove the dependency from the otel java agent. Publish a contrib version of the java agent which depends on it. 
3. Move to contrib. Remove the dependency on the otel java agent. Require users to include / enable it via the java agent extension mechanism. (Note, users already have to do this today to utilize aws resource providers.)
4. Keep it here as an exception to the general rule that vendor specific protools [must not be maintained](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/context/api-propagators.md#L350-L352) as part of core repositories. Note, the argument to keep it here is pretty flimsy now that we've established we don't need to keep publishing stable artifacts forever. 

I like options 1 and 3 the best. Option 2 makes sense if we foresee a growing number of instrumentations in contrib. I'm against option 4.

**Comment by mateuszrzeszutek** [comment]
There are several instrumentations that reference the `AwsXrayPropagator` class: AWS SDK, AWS lambdas, Apache Camel, and the Spring Boot Starter. Option 1 requires the least amount of changes, and I think I prefer it the most. Options 2 & 3 will require us to move these instrumentations to contrib as well.

**Comment by trask** [comment]
Option 1 sounds good to me also. We'll probably figure out the general instrumentation vs contrib story eventually, but not today 😄.

**Comment by jack-berg** [comment]
@jkwatson if you agree the first option I'll go ahead and get started on that by copying the code to contrib and deprecating it here.
