### ISSUE TITLE
Internal version mismatch of Kotlin-stdlib & Kotlin-stdlib-common

### ISSUE THREAD

**Issue by namespaceahr** [open-telemetry/opentelemetry-java#4835]
**Describe the bug**
Internal version mismatch of Kotlin-stdlib & Kotlin-stdlib-common in opentelemetry-exporter-jaeger:1.18.0
![image](https://user-images.githubusercontent.com/6684718/195058595-7c1fff85-8006-4787-a389-d9a97a915dee.png)
![image](https://user-images.githubusercontent.com/6684718/195062417-ff306bba-959a-476f-8699-b8b182016503.png)

**Steps to reproduce**
Add **opentelemetry-exporter-jaeger:1.18.0** as dependency.

**What did you expect to see?**
no mismatch in the internal version.

**What did you see instead?**
Internal version mismatch of Kotlin-stdlib & Kotlin-stdlib-common

**What version and what artifacts are you using?**
Artifacts: opentelemetry-exporter-jaeger
Version: 1.18.0
How did you reference these artifacts? **pom.xml**

**Environment**
Compiler: openjdk 17.0.4 2022-07-19
OS: Ubuntu 20.04
Runtime (if different from JDK above): No different
OS (if different from OS compiled on): No different

**Additional context**

**Comment by jkwatson** [comment]
Can you submit a PR with the fix?

**Comment by namespaceahr** [comment]
> Can you submit a PR with the fix?

I have investigated this issue. There is no problem with opentelemetry-exporter-jaeger.  Actually, okhttp brings  different versions of Kotlin-stdlib & Kotlin-stdlib-common. Source: [okhttp-issues](https://github.com/square/okhttp/issues/7373)
