### ISSUE TITLE
SDK: Determine how to convert OpenTelemetry::Resources into Jaeger

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-java#486]
During the review for #481, the topic about converting OpenTelemetry Resources into Jaeger came up. Once it's clear what's to be done, the Adapter's `toJaeger` method needs to incorporate this conversion.

Context:
https://github.com/open-telemetry/opentelemetry-java/pull/481#discussion_r312575248

**Comment by pavolloffay** [comment]
The resource is set on only on tracer at the moment. We can treat it as process information which maps to `Process` struct in Jager. We could get the resource from the first span and merge it with the process created at exporter startup. We do the same in Jaeger client exporters.

**Comment by songy23** [comment]
FYI in opentelemetry-service we translate resource into Jaeger process tags: https://github.com/open-telemetry/opentelemetry-service/pull/325.

**Comment by thisthat** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/848 has been resolved. Resources must be mapped to process tags: [spec link](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/jaeger.md).

**Comment by jkwatson** [comment]
We should probably change the title of this issue to match the fact that it just needs to be implemented now.  :)

**Comment by jkwatson** [comment]
Aha. This is now a dupe of #1609 . I'll revert the title change for this issue and close it, now that the spec is done.

**Comment by jkwatson** [comment]
Closing, now that the spec is complete and #1609 is ready to be implemented.
