### ISSUE TITLE
MultipleCallbacksTest is flaky

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#487]
> Task :opentelemetry-opentracing-shim:test

io.opentelemetry.opentracingshim.testbed.multiplecallbacks.MultipleCallbacksTest > test FAILED
    org.junit.ComparisonFailure: expected:<[parent]> but was:<[subtask]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.opentelemetry.opentracingshim.testbed.multiplecallbacks.MultipleCallbacksTest.test(MultipleCallbacksTest.java:55)

**Comment by bogdandrutu** [comment]
See https://circleci.com/gh/open-telemetry/opentelemetry-java/31

**Comment by carlosalberto** [comment]
Damn, thanks. 

I had implemented earlier today a way to sort Spans by their end time (to mimic the OT testing behavior), but it seems that the nano conversion being done (when converting to proto data) messes them up **sometimes**:

```sh
    # values as defined by RecordEventsReadableSpan.end()
    # ** subtask ended first **
    subtask END TIME =  101550749774250
    task END TIME =     101550750043391
    # values as exposed by RecordEventsReadableSpan.toSpanProto()
    # through TimestampConverter
    # ** task ended first (got 'swapped') **
    task END TIME =      1565813352:503037352
    subtask END TIME =   1565813352:503105288
```

I will fill a bug report once I can cook a proper, reproducible test case for this ;)
