### ISSUE TITLE
Support creating an UpstreamGrpcExporter without setChannel 

### ISSUE THREAD

**Issue by scjody** [open-telemetry/opentelemetry-java#4896]
**Is your feature request related to a problem? Please describe.**
We need to use `UpstreamGrpcExporter` in order to use `grpc-java` because OkHttp 4 conflicts with another library we use that requires OkHttp 3. Currently this requires using the deprecated [setChannel](https://github.com/open-telemetry/opentelemetry-java/blob/140c6360e06b42339a36912cb8ed73b698e8787f/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java#L77) method in order to trigger [this code path](https://github.com/open-telemetry/opentelemetry-java/blob/77be2e0136a82907c24d55e16fa46dfd7a7921ac/exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java#L132-L134) in `GrpcExporterBuilder`.

**Describe the solution you'd like**
We would be happy to use `setEndpoint`, but we need another way to cause `UpstreamGrpcExporterFactory` to be used.

**Describe alternatives you've considered**
The only other alternative I can see is for us to use `UpstreamGrpcExporter` or `UpstreamGrpcExporterFactory` directly, but both are marked "internal" and "not for public use": [UpstreamGrpcExporter](https://github.com/open-telemetry/opentelemetry-java/blob/f912f824ae79de6bdc5d302ebac239b4f17df163/exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/UpstreamGrpcExporter.java#L26-L27), [UpstreamGrpcExporterFactory (in GrpcExporterBuilder)](https://github.com/open-telemetry/opentelemetry-java/blob/140c6360e06b42339a36912cb8ed73b698e8787f/exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java#L41-L42).

**Comment by jack-berg** [comment]
Are you running into issues using OkHttp4 with a library that has a dependency on OkHttp3? OkHttp4 [claims to be binary and source compatible](https://square.github.io/okhttp/changelogs/upgrading_to_okhttp_4/#upgrading-to-okhttp-4) with OkHttp3.

**Comment by laurit** [comment]
@scjody If you need a solution for this right now then your best option is to shade otel dependencies and relocate `okhttp3` and `okio` packages so that they wouldn't conflict with the okhttp you already have. If it is easier you could also shade the datadog libraries with the okhttp they use.

**Comment by jack-berg** [comment]
I believe this was resolved in #6110.
