### ISSUE TITLE
Why not use List<double> and List<long> instead of that 

### ISSUE THREAD

**Issue by wang007** [open-telemetry/opentelemetry-java#4897]
**Is your feature request related to a problem? Please describe.**
In metrics impl,  HistogramPointData use List\<Double\> and List\<Long\>.
Why not use List<double> and List\<long\> instead of that ?

**Describe the solution you'd like**
use  List\<double\> and List\<long\>
```java
public interface HistogramPointData extends PointData {
...

List<double> getBoundaries();
List<long> getCounts();
}

```

**Comment by jkwatson** [comment]
Java 8 doesn't support generics of primitive types (does any version yet?), so this wouldn't be valid Java.

**Comment by wang007** [comment]
Hey @jkwatson.
Sorry, I'm wrong. 
I mean use double[] and. long[] instead of that.

**Comment by wang007** [comment]
From the point of view of saving resources, it seems more appropriate to use double[] and long[].
In my case, There is a lot of use Histogram and so I worry about resource consumption

**Comment by jkwatson** [comment]
Internally, the SDK stores the data as primitives. It's only at the point in time when export happens that it is converted to a List. And, even then, internally, the List implementation we have stores the primitives under the hood. So, the values are only wrapped at the actual moment of export. This shouldn't be very often (just whenever metric export is triggered periodically), so I don't think this is something to worry too much about.
