### ISSUE TITLE
[Request help]version update caused connection increase

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java#4905]
Hello, i've used java agent + collector for my project. The last version is 1.12.0, and recently we update the version to 1.14.0. And then the connections to our collector increase about 25% in one week (hundreds of applications update in different batch). Is there any changes between these two versions that will cause this problem?

**Comment by breedx-splk** [comment]
Hey @xiangtianyu . You said you are using the java agent -- maybe you intended to open this issue in [the opentelemetry-java-instrumentation repo](https://github.com/open-telemetry/opentelemetry-java-instrumentation) where the agent is maintained?

With your approval, maybe @trask or @jack-berg can move this issue over there.

Anyway, can you share a bit more about your configuration? What exporter are you using? 

I'm not aware of any changes between those two versions you listed that would cause an increase. However, I will note that 1.14.0 is already 5+ months old.

**Comment by xiangtianyu** [comment]
we use otlp to export trace and prometheus to export metrics.  Collector config is the common config to receive otlp and prometheus data. I raise the problem here because i thought it might be something wrong when handle grpc connection with collector(when handle error address, or timeout or etc.)

**Comment by breedx-splk** [comment]
Using netstat or other network tools, are you actually able to observe multiple connections from a single process to the otlp port?

**Comment by jack-berg** [comment]
I scanned all the commits from [1.12.0 -> 1.14.0](https://github.com/open-telemetry/opentelemetry-java/compare/v1.12.0...v1.14.0) and there aren't any changes that jump out to me as having the potential to impact the number of connections.

**Comment by xiangtianyu** [comment]
I found the problem, in 1.13.0 the metrics config set to `otlp` instead of `none`. So when we update version, the metrics connection auto create, so the connection increased!

**Comment by jack-berg** [comment]
Ah, yes. Nice find!
