### ISSUE TITLE
Dotel.java.disabled.resource-providers is not valid

### ISSUE THREAD

**Issue by daocr** [open-telemetry/opentelemetry-java#4919]
**Describe the bug**

Configuration "-Dotel.java.disabled.resource-providers=io.opentelemetry.instrumentation.resources.ContainerResourceProvider,io.opentelemetry.instrumentation.resources.HostResourceProvider,io.opentelemetry.instrumentation.resources.OsResourceProvider,io.opentelemetry.instrumentation.resources.ProcessResourceProvider,io.opentelemetry.instrumentation.resources.ProcessRuntimeResourceProvider" is not valid
 

**What did you expect to see?**
Do not collect resources information

**What did you see instead?**
![image](https://user-images.githubusercontent.com/28719772/200307235-9b74f8db-61a7-4d5f-85d2-b32e2b73ebfe.png)

**What version and what artifacts are you using?**
Version: 1.19.2-alpha

**Environment**
Compiler: (e.g., "oracle 1.8.0_281 ")
OS: (e.g., "Mac OS X 10.16")

**Comment by jack-berg** [comment]
It looks like you're using the otel java agent. The resource providers from [/opentelemetry-java-instrumentation/instrumentation/resources/library](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/resources/library) are shaded into the java agent, so their fully qualified class names change from `io.opentelemetry.instrumentation.resources.<ProviderClassName>` to `io.opentelemetry.javaagent.shaded.instrumentation.resources.<ProviderClassName>`.

For example, `ProcessResourceProvider` is disabled with `-Dotel.java.disabled.resource-providers=io.opentelemetry.javaagent.shaded.instrumentation.resources.ProcessResourceProvider`. 

@open-telemetry/java-instrumentation-maintainers this seems a bit surprising to me. Perhaps we shouldn't shade it, and thus allow users to provide different versions of the `io.opentelemetry.instrumentation:opentelemetry-resources` artifact.
