### ISSUE TITLE
Add bug reporting guidelines and issue templates

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#493]
We want to be prepared for the unlikely event that a bug ever has to be reported for opentelemetry-java :wink:

Some examples from our friends at .NET and JS:
* https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/CONTRIBUTING.md#report-a-bug-or-requesting-feature
* https://github.com/open-telemetry/opentelemetry-js/blob/master/CONTRIBUTING.md#report-a-bug-or-requesting-feature
* https://github.com/open-telemetry/opentelemetry-js/tree/master/.github/ISSUE_TEMPLATE

**Comment by andrewhsu** [comment]
From the sig mtg today, if doesn't go in with this milestone, will carry over to next.
