### ISSUE TITLE
Error creating bean with name 'otelOtlpGrpcSpanExporter' defined in class path resource [org/springframework/cloud/sleuth/autoconfig/otel/OtelExporterConfiguration$OtlpExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter]: Factory method 'otelOtlpGrpcSpanExporter' threw exception; nested exception is java.lang.NoClassDefFoundError: okhttp3/Interceptor

### ISSUE THREAD

**Issue by aditi9991** [open-telemetry/opentelemetry-java#4965]
```
 <dependency>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
   </dependency>
```
I am using okhttp maven dependency as test scope dependency. Why is this used inside opentelemetry-exporter-otlp-trace as a runtime dependency.
Getting error logs

Error creating bean with name 'traceFunctionAroundWrapper' defined in class path resource [org/springframework/cloud/sleuth/autoconfig/instrument/messaging/TraceFunctionAutoConfiguration.class]: Unsatisfied dependency expressed through method 'traceFunctionAroundWrapper' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'otelTracerBridge' defined in class path resource [org/springframework/cloud/sleuth/autoconfig/otel/OtelBridgeConfiguration.class]: Unsatisfied dependency expressed through method 'otelTracerBridge' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'otelTracer' defined in class path resource [org/springframework/cloud/sleuth/autoconfig/otel/OtelAutoConfiguration.class]: Unsatisfied dependency expressed through method 'otelTracer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelTracerProvider' defined in class path resource [org/springframework/cloud/sleuth/autoconfig/otel/OtelAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.sdk.trace.SdkTracerProvider]: Factory method 'otelTracerProvider' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelOtlpGrpcSpanExporter' defined in class path resource [org/springframework/cloud/sleuth/autoconfig/otel/OtelExporterConfiguration$OtlpExporterConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter]: Factory method 'otelOtlpGrpcSpanExporter' threw exception; nested exception is java.lang.NoClassDefFoundError: okhttp3/Interceptor

please help.

**Comment by jkwatson** [comment]
Can you please provide all the versions of things you are using?

**Comment by jack-berg** [comment]
> Why is this used inside opentelemetry-exporter-otlp-trace as a runtime dependency.

`opentelemetry-exporter-otlp-trace` was last published in version [1.14.0](https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-otlp-trace/) and we've just recently published so [1.20.1](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.20.1) so things have likely change since then. However I can say that `com.squareup.okhttp3:okhttp` is a dependency because `opentelemetry-exporter-otlp-trace` uses okhttp to produce gRPC requests by default instead of `io.grpc:*`.

**Comment by aditi9991** [comment]
I am using below dependendies for integrating opentelemetry in my microservice
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>${spring-cloud.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-otel-dependencies</artifactId>
            <version>${spring-cloud-sleuth-otel.version}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-sleuth</artifactId>
        <exclusions>
            <exclusion>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-sleuth-brave</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-sleuth-otel-autoconfigure</artifactId>
    </dependency>
    <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-exporter-otlp-trace</artifactId>
    </dependency>
</dependencies>
```

Here versions on analysing dependencies:

spring-cloud-sleuth-otel-dependencies -  version 1.1.0-M6
spring-cloud-starter-sleuth - version 3.1.3
spring-cloud-sleuth-otel-autoconfigure - version 3.1.3
opentelemetry-exporter-otlp-trace - version 1.14.0


**Spring versions are as follows**
<spring.framework.version>5.3.21</spring.framework.version>
<spring.boot.version>2.7.1</spring.boot.version>
<spring-cloud.version>2021.0.3</spring-cloud.version>

**Comment by jkwatson** [comment]
This looks like you should probably reach out to the spring-cloud-sleuth folks, as we don't support that here.
