### ISSUE TITLE
OTLP Proto: The java file I generated using the "make gen-java" command does not contain LogsServiceGrpc.java、TraceServiceGrpc.java、MetricsServiceGrpc.java, how can I generate these

### ISSUE THREAD

**Issue by nickzxing** [open-telemetry/opentelemetry-java#4972]
How to generate the above ServiceGrpc, and generate the GRPC JSON

**Comment by jack-berg** [comment]
We publish generated classes from the protos from [open-telemetry/opentelemetry-proto-java](https://github.com/open-telemetry/opentelemetry-proto-java). Have you given that a try?
