### ISSUE TITLE
End to end tests

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-java#498]
As the complexity of the client grows, it's necessary to have end-to-end tests to make sure all the pieces are integrated correctly. @pavolloffay suggested using [testcontainers](https://github.com/testcontainers/testcontainers-java) with jaeger all-in-one distribution based on the following examples:

* https://github.com/opentracing-contrib/java-spring-jaeger/blob/master/opentracing-spring-jaeger-web-starter-it/src/test/java/io/opentracing/contrib/java/spring/web/jaeger/starter/it/JaegerIntegrationTest.java#L49
* https://github.com/jaegertracing/spark-dependencies/blob/master/jaeger-spark-dependencies-elasticsearch/src/test/java/io/jaegertracing/spark/dependencies/elastic/JaegerElasticsearchEnvironment.java#L63

Context: https://github.com/open-telemetry/opentelemetry-java/pull/481#pullrequestreview-275414278

**Comment by DotSpy** [comment]
@jkwatson assign me tho this one please

**Comment by andrewhsu** [comment]
looks like this one can be closed
