### ISSUE TITLE
Restore Metric data after Application restart

### ISSUE THREAD

**Issue by jingyuanli001** [open-telemetry/opentelemetry-java#4981]
Hi Developers,

We are using OpenTelemetry java agent and the metrics sdks to record the metrics in our application. We noticed that when the java program restarts, the values in the metrics will be reset to the default value. I found it to be useful if we can restore the metrics values that were recorded before the application start. So I wonder if there is any mechanism that could support this, or if there any tools that can help us implement such operations. Thanks!

**Comment by jkwatson** [comment]
No, there is nothing in the SDK that would allow you to preserve state across JVMs.

**Comment by jingyuanli001** [comment]
I see. Thanks for the information!
