### ISSUE TITLE
Add static method to check if OpenTelemetry instance is globally registered

### ISSUE THREAD

**Issue by thomaszub** [open-telemetry/opentelemetry-java#4983]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy feasible way to check if the global `OpenTelemetry` instance is registered which can lead to problems for library developers to decide e.g. if tracing can be used or an own configuration of `OpenTelemetry` should be provided. See for example: 
https://github.com/open-telemetry/opentelemetry-java/issues/4180
https://github.com/SeleniumHQ/selenium/issues/10251

**Describe the solution you'd like**
A new static method in `GlobalOpenTelemetry` to check if a registered `OpenTelemetry` instance exists. I would make a PR with a suggestion.

**Describe alternatives you've considered**
An alternative would be a side-effect free `get` static method in `OpenTelemetrySdk` in comparison to the current method which creates an instance if not existing.

**Additional context**
A check method would be not "thread-safe" in the sense that after returning a value of `false` (meaning no global instance is registered) another thread could possibly configure the global instance. In most use cases this should be not a problem as tracing initialization is typically part of the application startup where multi-threading does not play a role.

**Comment by jkwatson** [comment]
What is your use-case for even using the global instance? We strongly recommend against it, unless you are using the OTel javaagent.

**Comment by thomaszub** [comment]
Thanks for explanation @jkwatson! After thinking more about it, the usage of global instance should actually not be recommended in manual instrumentation. Maybe you could add a note in the documentation that makes this point more clear. Therefor the issue can be closed.

**Comment by jkwatson** [comment]
If you have doc improvements, please submit a PR for them!
