### ISSUE TITLE
OpenCensus metrics shim: update to new experimental specification

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-java#5011]
**Describe the solution you'd like**

After https://github.com/open-telemetry/opentelemetry-specification/pull/2951, and https://github.com/open-telemetry/opentelemetry-specification/pull/2979, we should update our OpenCensus bridge implementation to comply with the new specification.

Note that the specifications are experimental.

Changes:

* [ ] Define a MetricProducer interface, following https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricproducer
* [ ] Define a RegisterProducer(metricProducer) function on MetricReader, following https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#registerproducermetricproducer
* [ ] Update the OpenCensus metric bridge to implement the MetricProducer interface, following https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opencensus.md

cc @jack-berg @jsuereth @psx95

**Comment by psx95** [comment]
I would like to take this up if its ok with everyone.

**Comment by jack-berg** [comment]
Go for it! Some notes:

- There's already a [MetricProducer](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/export/MetricProducer.java) interface that mirrors the spec. Its in an internal package and has to stay internal until the spec stabilizes. 
- MetricProducer extends an empty interface called [CollectionRegistration](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/CollectionRegistration.java). CollectionRegistration shows up in [MetricReader#register](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/export/MetricReader.java#L30), which is akin to the proposed `MetricReader#registerProducer` method. The idea is that MetricProducers register are each registered with MetricReaders during SdkMeterProvider initialization. 
- CollectionRegistration is empty and we use a [weird trick](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/export/MetricProducer.java#L29-L35) to cast to MetricProducer, which is actually useful.
- I think we once the spec is stable, we could shake things up and achieve an API that is in line with the spirit of the spec, but with some minor changes we're locked into by the fact that the recently added spec details didn't exist when we had to write some of this code. I would propose adding a `CollectionRegistration#getMetricProducer` method. It would be ideal if we could rename `CollectionRegistration` to `MetricProducer` and include the `collectAllMetrics()` method, but that would be a breaking change.

Now that I've written that all out, I'm not sure how much progress can be made on this front with stabilizing the spec.
