### ISSUE TITLE
messaging.message_id should be a string (semconv) but is defined as Long

### ISSUE THREAD

**Issue by cykl** [open-telemetry/opentelemetry-java#5019]
**Describe the bug**

Semantic convention defines messaging.message_id as a string but opentelemetry-java implements it as a `AttributeKey<Long>`

**Steps to reproduce**

* https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#messaging-attributes
* https://github.com/open-telemetry/opentelemetry-java/blob/main/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java#L996

**What did you expect to see?**

AttributeKey<String>

**What did you see instead?**

AttributeKey<Long>

**What version and what artifacts are you using?**

Latest rev from both.

**Environment**

Not applicable. 

**Additional context**

I discovered this discrepancy while trying to manually instrument a Kafka processor. Since then, I have checked kafka-clients instrumentation implementation and discovered that this instrumentation doesn't set message.id but some Kafka specific attributes. But that's another likely another topic.

**Comment by jkwatson** [comment]
I think you're mistaking two very similar attributes: https://github.com/open-telemetry/opentelemetry-java/blob/main/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java#L799 is the string one I think you're looking for.

**Comment by jack-berg** [comment]
It looks like `message.id` comes from the RPC semantic conventions [here](https://github.com/open-telemetry/opentelemetry-specification/blob/120f60ff70ed2a64af26017c8fe611f85e09d13f/specification/trace/semantic_conventions/rpc.md#events). 

Its unexpected that its not prefixed with `rpc.`.

**Comment by cykl** [comment]
@jkwatson You are absolutely right. I got confused between MESSAGE_ID and MESSAGING_MESSAGE_ID. Everything is right except that naming is confusing. But this comes from the semantic convention.

Thanks for the clarification :+1:
