### ISSUE TITLE
how traceid generate and transmit in thread pool

### ISSUE THREAD

**Issue by IcebergXTY** [open-telemetry/opentelemetry-java#5042]
1、some code like this
```java
String traceId1 = Span.current().getSpanContext().getTraceId();
Executors.newCachedThreadPool().execute(() -> {
    String traceId2 = Span.current().getSpanContext().getTraceId();
});
```
Dose traceId1 eqauls to traceId2 ?
If not, how can I realize it.

2、some code like this
```java
Executors.newScheduledThreadPool(1).scheduleAtFixedRate(() -> {
    String traceId = Span.current().getSpanContext().getTraceId();
}, 5, 5, TimeUnit.SECONDS);
```
Dose traceId  empty?
If it's empty, how can I generate it.

**Comment by IcebergXTY** [comment]
well, maybe this question should be in [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation)?

**Comment by mateuszrzeszutek** [comment]
If you're not using the javaagent, and you're manually instrumenting the application: you can use one of the [`Context`](https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/Context.java) `taskWrapping()` or `wrap()` methods to ensure that context is properly propagated to across threads.

If you're using the javaagent, the agent does the context propagation for you out of the box.

**Comment by IcebergXTY** [comment]
@mateuszrzeszutek Thank you for quick reply. I'm using the javaagentI but when tried this code, the traceId is always 00000000000000000000000000000000, is this right?
```java
Executors.newScheduledThreadPool(1).scheduleAtFixedRate(() -> {
    String traceId = Span.current().getSpanContext().getTraceId();
}, 5, 5, TimeUnit.SECONDS);
```
![image](https://user-images.githubusercontent.com/15325243/207569077-d29a0cd7-4c50-4016-9983-d3cb1ccc3991.png)

This is my command param
```bash
-Xms512M
-Xmx512M
-javaagent:D:\\DevelopSoftware\\OpenTelemetry-agent\\opentelemetry-javaagent.jar
-Dotel.exporter.otlp.endpoint=http://localhost:21694/
-Dotel.resource.attributes=service.name=EXECUTORS-DEMO,a=b,c=d
-Dotel.traces.exporter=logging
-Dotel.metrics.exporter=logging
-Dotel.logs.exporter=logging
-Dotel.exporter.otlp.protocol=http/protobuf
-Dotel.instrumentation.executors.include-all=true
```

**Comment by mateuszrzeszutek** [comment]
Is there any span in the context before the `executorService` is called? The javaagent will propagate context, but in your case the context was probably empty.
Just to test things out, you can try adding the `@WithSpan` annotation to the `run()` method - you should be able to see that the span created by this annotation is propagated into your thread.

**Comment by trask** [comment]
@IcebergXTY it looks like you are using `scheduleAtFixedRate`, check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3184

**Comment by IcebergXTY** [comment]
@mateuszrzeszutek @trask Thanks,  my instrument version is 1.19.2 and it works with `@WithSpan` annotation to the `run()` method. 
```java
Executors.newScheduledThreadPool(1).scheduleAtFixedRate(new Runnable() {
    @Override
    @WithSpan
    public void run() {
        String traceId = Span.current().getSpanContext().getTraceId();
        log.info("---------------------------" + traceId + "-------------------------------");
    }
}, 5, 5, TimeUnit.SECONDS);
```
