### ISSUE TITLE
JPMS support with module-info.java

### ISSUE THREAD

**Issue by claytonwohl** [open-telemetry/opentelemetry-java#5052]
I'd like to request full JPMS (Jigsaw) module support for OpenTelemetry with module-info.java files for all OpenTelemetry java modules. This would enable applications and other client libraries that use this library to fully adopt JPMS themselves. jlink packaging requires all dependencies and transitive dependencies be full JPMS modules with module-info.java descriptors. Applications that want to use this library currently have to forfeit jlink packaging since this library isn't a JPMS module.

**Comment by jkwatson** [comment]
Would you have time to contribute this, @claytonwohl ?

**Comment by claytonwohl** [comment]
Upon further investigation, adding module-info while maintaining Java 8 support is more complexity than its worth. I'm cancelling this feature request and I'd request revisiting this at some future date when the minimum supported Java version can be raised. @jkwatson thank you so much for the offer. Upon
