### ISSUE TITLE
Can we monitor JVM metrics like Heap, GC, Threads in OpenTelemetry agent?

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java#5067]
Can we monitor JVM metrics like Heap, GC, Threads in OpenTelemetry agent?
I haven't found any example to configure the metrics in agent. I can see the traces and spans exported, But not JVM metrics.

Is this feature already in OpenTelemetry agent or not yet available?

**Comment by jack-berg** [comment]
JVM runtime metrics are available with and without the opentelemetry java agent. See [documentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-metrics/library) for usage outside the java agent.

**Comment by chandru-kumar** [comment]
@jack-berg Thank you. Will check it.
