### ISSUE TITLE
Cannot connect to OTEL Collector: ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Required SETTINGS preface not received

### ISSUE THREAD

**Issue by makigurapo** [open-telemetry/opentelemetry-java#5084]
Hi, I'm also having the same issue:

after running the curl command. (**ERROR**)

<img width="671" alt="image" src="https://user-images.githubusercontent.com/121836290/210707082-ef442117-fb6d-4289-8c6f-14f7f2b6b5ca.png">

and this what happens of microservice:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/121836290/210707370-3d150785-104b-4dd8-9796-ce06962cdd90.png">

and this current value of run-microservice file:
```
mvn clean package -Dmaven.test.skip=true
AGENT_FILE=opentelemetry-javaagent-all.jar

if [ ! -f "${AGENT_FILE}" ]; then
curl -L https://github.com/aws-observability/aws-otel-java-instrumentation/releases/download/v1.19.2/aws-opentelemetry-agent.jar --output ${AGENT_FILE}
fi

export OTEL_TRACES_EXPORTER=otlp
export OTEL_METRICS_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:5555/
export OTEL_RESOURCE_ATTRIBUTES=service.name=hello-app,service.version=1.0

java -javaagent:./${AGENT_FILE} -jar target/hello-app-1.0.jar
```

and this is the value of collector-config-local.yaml

```
receivers:
otlp:
protocols:
grpc:
endpoint: 0.0.0.0:5555

exporters:
logging:
loglevel: debug

service:
pipelines:
metrics:
receivers: [otlp]
exporters: [logging]
traces:
receivers: [otlp]
exporters: [logging]
```

**Comment by jack-berg** [comment]
This is unexpected. What collector build / version are you running?

**Comment by yassenb** [comment]
Having the same issue here with 1.22.1 version of the Java agent, trying to use the OTLP GRPC exporter

**Comment by jack-berg** [comment]
What version of the collector are you using?

**Comment by yassenb** [comment]
> What version of the collector are you using?

Sorry, I don't really know. I'm trying to set things up with a third party provider - Instana. I doubt their version is very old. What are the supported collector versions?

**Comment by trask** [comment]
hi @yassenb! can you check with your backend provider if they support OTLP metrics ingestion, and if you are using the correct setup for their OTLP service?

**Comment by yassenb** [comment]
> hi @yassenb! can you check with your backend provider if they support OTLP metrics ingestion, and if you are using the correct setup for their OTLP service?

So I managed to get it working but only by running a collector locally with an OTLP GRPC exporter configured. I couldn't find any documentation on it but circumventing the collector and exporting directly should work just the same right? There seems to be some difference between what the collector OTLP GRPC receiver accepts and what the OTLP GRPC exporter sends which makes the open telemetry collector a mandatory component. I understand the benefits of the collector but for now would like to go without it, what is the proper way to do it?

**Comment by jack-berg** [comment]
If your vendor accepts OTLP directly they may be doing so without the collector. There may be something wrong (or different than the collector) in their implementation of the OTLP receiver protocol that is causing the problem.
