### ISSUE TITLE
Generate a `service.instance.id` if it is not present?

### ISSUE THREAD

**Issue by srikanthccv** [open-telemetry/opentelemetry-java#5103]
Spec says https://github.com/open-telemetry/opentelemetry-specification/tree/v1.6.1/specification/resource/semantic_conventions#service

> MUST be unique for each instance of the same service.namespace,service.name pair (in other words service.namespace,service.name,service.instance.id triplet MUST be globally unique). The ID helps to distinguish instances of the same service that exist at the same time (e.g. instances of a horizontally scaled service). It is preferable for the ID to be persistent and stay the same for the lifetime of the service instance, however it is acceptable that the ID is ephemeral and changes during important lifetime events for the service (e.g. service restarts). If the service has no inherent unique ID that can be used as the value of this attribute it is recommended to generate a random Version 1 or Version 4 RFC 4122 UUID (services aiming for reproducible UUIDs may also use Version 5, see RFC 4122 for more recommendations).

The built-in default Resource doesn't appear to do this. While it is not mandatory by specification, it is important when scaling a service horizontally. 

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#single-writer

https://github.com/open-telemetry/opentelemetry-specification/blob/7e9ba1683995c34846b942fbc23c3290610e9347/specification/compatibility/prometheus_and_openmetrics.md#resource-attributes

**Comment by jack-berg** [comment]
I'm in favor of adding this to the default resource, and I think this specific sentence from the semantic conventions makes it reasonable to do:

> If the service has no inherent unique ID that can be used as the value of this attribute it is recommended to generate a random Version 1 or Version 4 RFC 4122 UUID (services aiming for reproducible UUIDs may also use Version 5, see RFC 4122 for more recommendations).

@srikanthccv do you know if any other language SDKs include it by default?

**Comment by srikanthccv** [comment]
I know erlang does it by default, and Python and JS have planned to include it by default, but it hasn't been implemented yet.

**Comment by jack-berg** [comment]
FYI I opened [spec issue #3136](https://github.com/open-telemetry/opentelemetry-specification/issues/3136) to request clarity on whether SDKs should generate a value for `service.instance.id`.

**Comment by jack-berg** [comment]
Resolved in #6226.
