### ISSUE TITLE
`ArrayBackedAttributes` is not equal to `AttributesMap`

### ISSUE THREAD

**Issue by iRevive** [open-telemetry/opentelemetry-java#5148]
**Describe the bug**

I'm not sure whether this is a bug or expected behavior. In my tests, the identical attributes backed by different implementations of `Attributes` are not equal.

Should the `ArrayBackedAttributes` and `AttributesMap` be equal if they back the same attributes? 

**Steps to reproduce**

```java
import io.opentelemetry.api.common.Attributes;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.sdk.testing.exporter.InMemorySpanExporter;
import io.opentelemetry.sdk.trace.SdkTracerProvider;
import io.opentelemetry.sdk.trace.data.SpanData;
import io.opentelemetry.sdk.trace.export.SimpleSpanProcessor;

import java.util.List;

class MyClassTest {
    private static final InMemorySpanExporter testExporter = InMemorySpanExporter.create();
    private static final SdkTracerProvider tracerProvider = SdkTracerProvider
            .builder()
            .addSpanProcessor(SimpleSpanProcessor.create(testExporter))
            .build();

    public static void main(String[] args) {
        Tracer tracer = tracerProvider.tracerBuilder("test-scope").build();

        Attributes attributes = Attributes.builder().put("key", "value").build();

        tracer.spanBuilder("span").setAllAttributes(attributes).startSpan().end();

        List<SpanData> spanItems = testExporter.getFinishedSpanItems();
        SpanData spanData = spanItems.get(0);

        System.out.println(spanData.getAttributes()); // AttributesMap{data={key=value}, capacity=128, totalAddedValues=1}
        System.out.println(attributes); // {key="value"}
        System.out.println(spanData.getAttributes().equals(attributes)); // false
    }
}
```

**What did you expect to see?**

`spanData.getAttributes().equals(attributes) == true`

**What did you see instead?**

`spanData.getAttributes().equals(attributes) == false`

**What version and what artifacts are you using?**

Artifacts: `opentelemetry-api`, `opentelemetry-sdk`, `opentelemetry-sdk-testing`)
Version: `1.22.2`
How did you reference these artifacts? I'm using **[sbt](https://www.scala-sbt.org/)**.
```scala
libraryDependencies ++= Seq(
  "io.opentelemetry" % "opentelemetry-api" % "1.22.2",
  "io.opentelemetry" % "opentelemetry-sdk" % "1.22.2",
  "io.opentelemetry" % "opentelemetry-sdk-testing" % "1.22.2"
)
```

**Environment**
Compiler: Azul 11.0.17
OS: MacOS Ventura 13.1

**Comment by jkwatson** [comment]
This is a known issue. When writing tests, I've mostly called `asMap` and done equality on the returned `Map` implementation. Since `Attributes` is a public interface, we can't guarantee that all implementations will conform to equality across all implementations
