### ISSUE TITLE
CI build for java11

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#515]
Add java11 build to CI. 

@bogdandrutu is there a reason why we build with Java9 at the moment? Java11 is the next LTS version. Java9 public updates ended `March 2018`. https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by bogdandrutu** [comment]
@pavolloffay Happy to see a PR to build Java 11 :)

**Comment by bogdandrutu** [comment]
I tried a PR to build this using java11 which fails because of bootclasspath warning. I think what we want is probably to run the testbed with java11 and the jars maybe built with java8?

**Comment by pavolloffay** [comment]
> I think what we want is probably to run the testbed with java11 and the jars maybe built with java8?

Yes, I think that is exactly what we do for java 9. We just need to bump the version.

**Comment by bogdandrutu** [comment]
That was not the case, we build and run tests with java9 currently

**Comment by bogdandrutu** [comment]
Thanks @jkwatson
