### ISSUE TITLE
Is there a way to select which metric to export like trace sampler?

### ISSUE THREAD

**Issue by IcebergXTY** [open-telemetry/opentelemetry-java#5152]
**Is your feature request related to a problem? Please describe.**
1、Example One
There is a module named [HttpUrlConnectionInstrumentationModule ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/6345cdad9d73ef80c991ffb3d5a9b6fb95405ed1/instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlConnectionInstrumentationModule.java#L16) in opentelemetry-java-instrument, it not only record metric (etc. http.client.duration) but also trace data.
In my application, the `http.client.duration` metric is useless and it's number is so large. Now I use `otel.instrumentation.http-url-connection.enabled=false` to disable it but the useful trace data is also disabled

2、Example Two
We have a metric that records the number of url requests, but we just need record those urls of key business so the most metric data are superfluous. These useless data takes up a lot of disk space and network bandwidth.

**Describe the solution you'd like**
I have seen a [RuleBasedRoutingSampler](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/0a384d1a12b1ae46c144ef751d21cb6bc31f893f/samplers/src/main/java/io/opentelemetry/contrib/samplers/RuleBasedRoutingSampler.java#L34) which can select trace data to export.
So is there a way to select which metric to export like trace?

**Comment by jkwatson** [comment]
You could write a custom exporter to accomplish this. There's nothing in the SDK or the specification that would allow this before export as as far as I know.

**Comment by jack-berg** [comment]
Views would allow you to selectively disable instruments, i.e.
```
    SdkMeterProvider.builder()
        .registerView(
            InstrumentSelector.builder().setName("http.client.duration").build(),
            View.builder().setAggregation(Aggregation.drop()).build())
        .build();
```
Can do this using a config file with the experimental [view file config](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator#view-file-configuration) functionality.

> We have a metric that records the number of url requests, but we just need record those urls of key business so the most metric data are superfluous. These useless data takes up a lot of disk space and network bandwidth.

Yeah the only way tot do this is a custom exporter which drops the unwanted points.

**Comment by IcebergXTY** [comment]
@jkwatson @jack-berg Thank you, use a custom exporter works well
