### ISSUE TITLE
Print duration in LoggingSpanExporter

### ISSUE THREAD

**Issue by MaheshGPai** [open-telemetry/opentelemetry-java#5162]
**Is your feature request related to a problem? Please describe.**
Currently LoggingSpanExporter logs the span details like name, traceId, spanId, kind etc along with all the attributes. This can enhanced to print the duration of the span as well. Tools which are used to parse and ingest logs can use this derive latency metrics and dashboarding

**Describe the solution you'd like**
In addtion to the exist details being logged by LoggingSpanExporter.java, capture the duration of the span (EndTime - StartTime)

**Describe alternatives you've considered**

**Additional context**

**Comment by jack-berg** [comment]
Have you considered using the [OtlpJsonLoggingSpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/logging-otlp/src/main/java/io/opentelemetry/exporter/logging/otlp/OtlpJsonLoggingSpanExporter.java)? It logs a protobuf JSON encoding of the spans, and is ideal for machine readability.

**Comment by jkwatson** [comment]
The LoggingSpanExporter is _not_ intended to be used for any sort of production use-cases, so I'm very hesitant to start adding information to its output in an ad-hoc way.
