### ISSUE TITLE
Enhance SDK Configuration Options

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-java#517]
Enhancements fall into 2 categories.

1. Configuration should work like logging frameworks configuration. It can either be accomplished by use of a standard name configuration file loaded from the classpath or else done programmatically. Programmatically will be especially useful in creating a Spring Boot actuator for OpenTelemetry.
2. Additional configuration items would be useful such as:
    a. IdGenerator implementation class - This would support a different implementation for Android. It would also allow the substitution of a generator compatible with a particular backend such as AWS X-Ray.
    b. Formatter implementation classes - This would support a different implementation for a particular backend. It would also support integrating with multiple external systems using different formats. For example, system uses W3C Trace Context internally but receives messages from systems using the b3-propagation format.

**Comment by jkwatson** [comment]
related to spec issue:  https://github.com/open-telemetry/opentelemetry-specification/issues/390

**Comment by bogdandrutu** [comment]
@kbrockhoff can this be closed? What is left?

**Comment by kbrockhoff** [comment]
At the bare minimum, methods need to be added to MeterSdkRegistry or MeterSdk to programmatically wire in Aggregator, Aggregation, MeterExporter, MetricProducer implementations.

I would like to see it possible for configuration to be controlled by loading a configuration file on startup but this can wait until later. As long as an application can control everything programmatically this should be easy to add later.

**Comment by jkwatson** [comment]
@kbrockhoff we've done a ton of work to make the SDK super configurable, both programmatically and via the autoconfigure sdk extension module. I'm going to close this. If you have specific asks, please open new issues to track them. Thanks!
