### ISSUE TITLE
Provider Mechanism for Resource

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-java#518]
Add a provider interface for Resource for use with ServiceLoader. This would enable the runtime platform to provide its own implementation. Some use cases where this would be useful would be JEE application servers where the server itself is best positioned to provide the correct information. Another use case would be the Spring Cloud vendor-specific libraries which are already loading most of the KVPs which the Resource would need.

**Comment by jkwatson** [comment]
It would be even better if there was also a java code (eg. builder) way to do this, rather than requiring a particular configuration option.

**Comment by bogdandrutu** [comment]
I think we can have a "SetResource" on the SDK. So if the SDK was loaded you can configure the Resource as one of the first thing in your main function.

**Comment by jkwatson** [comment]
That seems like a fine alternative, although I get nervous with having the SDK be mutable like that.

**Comment by kbrockhoff** [comment]
I agree

**Comment by jkwatson** [comment]
related to spec issue:  https://github.com/open-telemetry/opentelemetry-specification/issues/390
