### ISSUE TITLE
Support zstd compression codec for open-telemetry/opentelemetry-java

### ISSUE THREAD

**Issue by patrick-me** [open-telemetry/opentelemetry-java#5196]
Hi there!

Could you please, support zstd codec for the [exporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L103) or all of them.
ZSTD codec is much faster and more efficient than gzip, sure you know.

Btw, zstd is already supported by [Collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md#compression-comparison)

I'm looking forward to hearing from you
Thanks in advance

**Comment by jack-berg** [comment]
Do you have any thoughts on how this would be delivered, given that there isn't any native support in java?

There's a popular library called [zstd-jni](https://github.com/luben/zstd-jni), but it looks like it packages up a architecture-dependent native library and has artifacts that are quite big, each on the order of 400kb. The main jar comprising all architectures is ~5.7mb. 

Maybe we could provide an SPI to allow for bringing your own codec, and publish artifacts with some popular implementations. This would essentially allow users to opt-in to the big additional dependency.

Thoughts @jkwatson?

**Comment by jkwatson** [comment]
"bring your own codec" seems fine, but maybe that's just "bring your own exporter and configure it however you like".

**Comment by jack-berg** [comment]
https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1108 adds publishes a new artifact from contrib which adds support for `zstd`. Please take a look. Planning on closing this issue after #6103 is merged since we don't plan on adding support for other algorithms in this repo.

**Comment by patrick-me** [comment]
Thank you very much, Jack 🙏

**Comment by jack-berg** [comment]
Closing now that https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1108 is merged.
