### ISSUE TITLE
Support mTLS for JaegerRemoteSampler [java]

### ISSUE THREAD

**Issue by chicobento** [open-telemetry/opentelemetry-java#5209]
### Background
Jaeger [supports mTLS for GRPC interface](https://www.jaegertracing.io/docs/1.42/cli/) via `--query.grpc.tls.client-ca` parameter. 
However, [JaegerRemoteSampleBuilder](https://github.com/open-telemetry/opentelemetry-java/blob/v1.23.0/sdk-extensions/jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/JaegerRemoteSamplerBuilder.java#L62) is not exposing the a `setClientTls` operation for setting the privateKey / certificate PEM, as done by other Builders, such as [OtlpHttpSpanExporterBuilder.setClientTls](https://github.com/open-telemetry/opentelemetry-java/blob/v1.23.0/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java#L98).

### Solution
Align JaegerRemoteSamplerBuilder with other Builders by providing a similar `setClientTls` operation.

**Alternative**
Ideally, all builders should also support ways for passing the key/trust store pairs rather than the raw pem files. In our solution we already have the general code for handling the conversion of pem files to keystore / truststore pairs done externally, so an overload of the `setClientTls` and `setTrustedCertificates` operations with the keystore/trustore params would come handy.
See #5211

**Comment by liangyuanpeng** [comment]
Seems like this issue can be closed.

**Comment by jack-berg** [comment]
Resolved in #5209.
