### ISSUE TITLE
Exponential histograms support for the prometheus exporter 

### ISSUE THREAD

**Issue by nicu-da** [open-telemetry/opentelemetry-java#5210]
**Is your feature request related to a problem? Please describe.**
The specification recently added conversions for exponential histograms into prometheus histograms ([https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#exponential-histograms](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#exponential-histograms)).
This is not supported as of yet by the java implementation, leading to exponential histograms being dropped when using prometheus https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java#L110

**Describe the solution you'd like**
Exponential histograms are converted to the prometheus metric format as specified in the specification.

**Comment by jkwatson** [comment]
Are you able to contribute the work to make this happen?  Thanks!

**Comment by nicu-da** [comment]
Started looking at this, realized that the `native histogram` support in promtheus is still experimental and only supported in the protobuf read/write format and not yet standardized for the text format, therefore this change cannot be feasibly be implemented until Prometheus defines the text format for native histograms.
Will be closing this until the text format for native histograms is defined by prometheus.
