### ISSUE TITLE
Autoconfigured GlobalOpenTelemetry not flushing spans on shutdown, v1.23.0

### ISSUE THREAD

**Issue by rossabaker** [open-telemetry/opentelemetry-java#5218]
**Describe the bug**
Using `GlobalOpenTelemetry` with auto-configuration enabled, the application is no longer flushing spans in the JVM shutdown hook.  If I sleep for some time at the end of the main method, it works.  It works reliably without sleep on 1.22.0. 

**Steps to reproduce**

I am running the following code:

```java
import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.api.common.Attributes;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.context.Scope;

class PlainJava {
    public static void main(String[] args) throws Exception {
        OpenTelemetry openTelemetry = GlobalOpenTelemetry.get();
        Tracer tracer = openTelemetry.getTracer("plain-java", "1.0.0");
        Span span = tracer.spanBuilder("my span").startSpan();
        try (Scope ss = span.makeCurrent()) {
            // In this scope, the span is the current/active span
        } finally {
            span.end();
        }
        // Thread.sleep(10000);
    }
}
```

This is running with `-Dotel.java.global-autoconfigure.enabled=true` and no other otel-related system properties or environment variables.  A local Jaeger is listening on port `4317`. 

**What did you expect to see?**
I expected to see a trace with `my span` in my local Jaeger UI.

**What did you see instead?**
No trace was received.

**What version and what artifacts are you using?**
Artifacts:
* `opentelemetry-sdk`
* `opentelemetry-sdk-extension-autoconfigure`
* `opentelemetry-exporter-otlp`

Version: `v1.23.0`
How did you reference these artifacts?  From SBT:

```scala
    libraryDependencies ++= Seq(
      "io.opentelemetry" % "opentelemetry-exporter-otlp" % OpenTelemetryVersion,
      "io.opentelemetry" % "opentelemetry-sdk" % OpenTelemetryVersion,
      "io.opentelemetry" % "opentelemetry-sdk-extension-autoconfigure" % s"${OpenTelemetryVersion}-alpha"
    ),
    run / fork := true,
    javaOptions += "-Dotel.java.global-autoconfigure.enabled=true"
```

**Environment**
Compiler: Azul Systems, Inc. Java 19.0.1
OS: MacOS Ventura 13.1

**Additional context**
* It works as expected on 1.22.0
* I built opentelemetry-java locally, and can confirm `OpenTelemetry.close()` is called and that shutdown completes successfully.
* The changes in 4df4a0ae0985a448e95dcf06415af629bfea80d6 seem relevant, but I don't see a problem.  
* I originally hit this in Scala's otel4s, but I've minimized it to pure Java aside from the build.  I can throw together a POM to completely eliminate Scala, but I don't think that's it.

**Comment by jack-berg** [comment]
I can verify that this is a bug. Looks like I botched the ordering of the [shutdown hook](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java#L381-L383) and its not operating on the `OpenTelemetrySdk` instance that ends up being used.

@jkwatson we should issue a patch for this. @trask can we hold off on the instrumentation release to incorporate the patch?

**Comment by trask** [comment]
> @trask can we hold off on the instrumentation release to incorporate the patch?

👍
