### ISSUE TITLE
Make the NoopSpanExporter a public class. 

### ISSUE THREAD

**Issue by psx95** [open-telemetry/opentelemetry-java#5240]
**Is your feature request related to a problem? Please describe.**
While working on custom exporters, under certain circumstances, it becomes necessary to provided a no-op TraceExporter. I see [NoopSpanExporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/NoopSpanExporter.java#L12), which provides with a noop implementation for a SpanExporter. 

It seems this could be made public. It would avoid the need to create the exact same class in client code. 

**Describe the solution you'd like**
The NoopSpanExporter class is made public.

**Describe alternatives you've considered**
Providing noop implementation in client code helps avoids defensive coding and writing checks everywhere to see if the exporter was initialized correctly. 

**Additional context**
One common circumstance where this class being public would help is -  when some misconfiguration causes exporter to not be initialized correctly, at that point, a noop implementation can be provided.

**Comment by jkwatson** [comment]
This class is so simple, I think it's easy enough for you to just have a copy if you need it. Anything we make public, we have to commit to supporting forever, and I'm not sure this falls into that bucket.
