### ISSUE TITLE
Support PKCS1 encoded private keys

### ISSUE THREAD

**Issue by chicobento** [open-telemetry/opentelemetry-java#5245]
**Describe the bug**
The `setClientTls` method supported by client builders such as [OtlpHttpSpanExporterBuilder](https://github.com/open-telemetry/opentelemetry-java/blob/v1.23.0/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/trace/OtlpHttpSpanExporterBuilder.java) takes only the raw pem files as byte array and takes care of the conversion. However, the conversion code on does not support PKCS1 format, as supported by default for many certificate providers such as [cert-manager](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.PrivateKeyEncoding).

Although this is fair and can be a design choice given that PKCS1 is not supported out-of-the-box by the JDK (bouncy castle supports it), alternative means to reach support for PKCS1 type of keys must be provided, such as supporting more generic arguments such as `SSLContext` as requested on #5211. As of now, the only way to support PKCS1 is to re-write most of the SDK client code.

**Comment by jack-berg** [comment]
Closing since we support low level configuration of the SSL context in #5280. It seems unlikely that we would add direct support for formats not supported out of the box by the JDK since we try to avoid dependencies.
