### ISSUE TITLE
Support Bill of Materials pom.xml

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-java#525]
BOM helps keep working versions across artifacts. With BOM lots of issues caused by incompatible transitive dependencies can be avoided, e.g https://github.com/census-instrumentation/opencensus-java/issues/1215, https://github.com/census-instrumentation/opencensus-java/issues/1220.

Original issue in OpenCensus: https://github.com/census-instrumentation/opencensus-java/issues/1117.

/cc @suztomo

**Comment by kbrockhoff** [comment]
I am working on this issue.

**Comment by bogdandrutu** [comment]
Ping @kbrockhoff

**Comment by DotSpy** [comment]
i can take this one with https://github.com/open-telemetry/opentelemetry-java/issues/1111
