### ISSUE TITLE
gradlew build fails at main commit dfaa681b222aad84fed74f508ed8cb52f2b4ded2

### ISSUE THREAD

**Issue by pedrolamarao** [open-telemetry/opentelemetry-java#5250]
**Describe the bug**
`gradlew build` at main dfaa681b222aad84fed74f508ed8cb52f2b4ded2 fails.

**Steps to reproduce**
1. git clone https://github.com/open-telemetry/opentelemetry-java.git .
2. ./gradlew build

**What did you expect to see?**
Gradle evidence of build success.

**What did you see instead?**
```
> Task :exporters:otlp:common:generateMainProtos FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':exporters:otlp:common:generateMainProtos'.
> Error while evaluating property 'sourceInput$wire_gradle_plugin' of task ':exporters:otlp:common:generateMainProtos'.
   > Failed to calculate the value of task ':exporters:otlp:common:generateMainProtos' property 'sourceInput$wire_gradle_plugin'.
      > 'other' has different root

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
23 actionable tasks: 2 executed, 21 up-to-date
```

**What version and what artifacts are you using?**
commit dfaa681b222aad84fed74f508ed8cb52f2b4ded2

**Environment**
Windows 10 Pro
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

**Additional context**
Nothing that I can think of.

**Comment by jkwatson** [comment]
Hm. I know we've definitely had problems with builds on windows. I can confirm that the build works fine on mac, and linux, however. @trask can you shed any light on the state of building otel on windows?

**Comment by jack-berg** [comment]
I cannot recreate this on my windows machine. Tried with and without WSL2. When I build on windows I get a variety of test failures, but the build get's past the "assemble" phase no problem.

**Comment by jack-berg** [comment]
Closing. Please re-open if you think something about this repo's gradle configuration causes the build to fail in drives other than `:c`.
