### ISSUE TITLE
`OtelToZipkinSpanTransformer` silently deletes all resource attributes

### ISSUE THREAD

**Issue by braunsonm** [open-telemetry/opentelemetry-java#5251]
**Describe the bug**
In the `OtelToZipkinSpanTransformer` when the span is being created for the reporter, only the service name is pulled from the resource attributes on the span while the rest are dropped silently. 

**Steps to reproduce**
- Create a `SdkTracerProvider` with resource attribute `environment` set to something like `dev.
- Use the Zipkin reporter to report the span

**What did you expect to see?**
All of my resource attributes should be available, or put into the attribute field.

**What did you see instead?**
The extra resource attributes are silently dropped. The service name only stays because it happens to be pulled directly by a special case on the endpoint: https://github.com/open-telemetry/opentelemetry-java/blob/dfaa681b222aad84fed74f508ed8cb52f2b4ded2/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/OtelToZipkinSpanTransformer.java#L153

**Comment by jack-berg** [comment]
The specification defines the mapping in the zipkin exporter [here](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/trace/sdk_exporters/zipkin.md#L36-L41).

Note that there is currently no mapping for resources. 

Spec issue [#1196](https://github.com/open-telemetry/opentelemetry-specification/issues/1196) is tracking the issue, and would need to be resolved for the java implementation to fix this.

**Comment by jack-berg** [comment]
This is actually a duplicate of #1970.

**Comment by braunsonm** [comment]
Thanks @jack-berg I'll track the duplicate.
