### ISSUE TITLE
Modify the class in the SDK to public

### ISSUE THREAD

**Issue by Woodrow1026** [open-telemetry/opentelemetry-java#5267]
**Is your feature request related to a problem? Please describe.**
All classes in the SDK are private (or final) and cannot be modified through inheritance. It is easy to have restrictions in production scenarios

**Describe the solution you'd like**
Consider making the concrete implementation class public, or at least make the abstract class public

**Describe alternatives you've considered**
In the production environment, it is necessary to consider the integration with the company's infrastructure, such as uploading the call point of Instrument to the company's monitoring system (rather than relying entirely on OpenTelmetry to complete this work). At this time, some modifications need to be made to the implementation of the SDK

**Additional context**
For example, when I use Histogram Instrument, I'd like to send call point to  company's monitoring system. Code may like this:
`public class CatTraceDoubleHistogram extends SdkDoubleHistogram {
    @Override
    public void record(double value) {
        sendToOurMonitor(value, otherThing);
        record(value, Context.current());
    }
}`
But now it's not possible because SdkDoubleHistogram is final class

**Comment by jack-berg** [comment]
You can accomplish this today by providing your own implementation of the metrics API (`MeterProvider` / `Meter` / instruments), which delegates to `SdkMeterProvider` in all cases, and which adds the additional behavior you've described for `DoubleHistogram`.

**Comment by Woodrow1026** [comment]
> You can accomplish this today by providing your own implementation of the metrics API (`MeterProvider` / `Meter` / instruments), which delegates to `SdkMeterProvider` in all cases, and which adds the additional behavior you've described for `DoubleHistogram`.

However, we only wanted to make a small change to some Instruments. To implement MeterProvider / Meter / instruments requires a lot of changes, because we cannot reuse the existing functions in the SDK.

I think it's unreasonable, or am I misunderstanding what you mean?

**Comment by jkwatson** [comment]
We intentionally restrict the API surface area that we have to support, because if we wanted to make any changes to it, they would end up being breaking. I'm sorry this is an inconvenience. If you have a use-case that would be universal and apply to many implementations, please consider opening an issue with the specification, so it can be built in such a way that everyone can benefit. 

I don't think we'll make things public, or open them to extension unless there is an extremely compelling case for it.
