### ISSUE TITLE
Add put method with Map param to AttributesBuilder

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-java#5275]
Hi all, 

I was wondering if there's a reason the Attributes builder ([here](url)), there's no put method that accepts a Map of attributes.

It's easy enough to create a helper to do so but was wondering if there was a reason it was omitted from the api as I imagine it's a pretty common use case.

**Comment by jack-berg** [comment]
Attributes currently don't support complex types (maps and heterogenous arrays). There's a [spec issue](https://github.com/open-telemetry/opentelemetry-specification/pull/2888) where the addition of complex types is being debated. 

As part of that discussion, I [prototyped](https://github.com/open-telemetry/opentelemetry-specification/pull/2888#issuecomment-1332837092) extending the java Attributes API as you've suggested.

So we're blocked on the spec, but if the spec issue resolves, there's a reasonable path forward for including it in opentelemetry-java.

**Comment by jkwatson** [comment]
@akats7 Are you asking about having map-valued attributes, or simply a helper method that extracts the values from a map and adds them each as attributes?  If the former, see @jack-berg 's answer. If the latter, then the main reason is to avoid extra allocations. Our Attribute API is built to avoid extra memory allocations, and if we had to turn every map key into an attribute, then that's a lot of extra allocations.  Again, if the latter, then this is a trivial thing for you to write if you need it, and hence I don't think it's something we would add to the API, as it would encourage a usage that generates un-needed allocations.

**Comment by breedx-splk** [comment]
@akats7 Did @jkwatson 's answer make sense? I read your issue as needing the latter (eg. `<T> putAll(Map<AttributeKey<T>,T> attributes)`), but you could help confirm.

Curious what your use case is -- or what you are doing that has the attributes in a `Map` anyway. To Watson's point, if you have some code that pre-collects attributes, you can reduce allocations by using the same `AttributesBuilder` instance....but I also understand that program flow/structure doesn't always make that easy (and passing around a builder isn't always best practice).

I think that `putAll(Attributes)` (which exists) is not terribly different from `<T> putAll(Map<AttributeKey<T>,T)`, and would seem to me like a reasonable addition.
