### ISSUE TITLE
Support propogating Envoy's x-request-id header

### ISSUE THREAD

**Issue by Spitfire1900** [open-telemetry/opentelemetry-java#5285]
The OpenTelemetry javaagent is a great tool to automatically forward multiple [Trace Context Propogation](https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation) headers. And while it supports sending the default x-b3 headers used by Red Hat Service Mesh (istio), it does not support sending the x-request-id header that is also expected to be forwarded in Istio service mesh.

**Comment by jkwatson** [comment]
If we were going to implement this in _this_ particular repository, it would need to be added to the specification. I think, absent that, this would be a fine thing to have in the opentelemetry-java-contrib repository as an optional component for people to use.

**Comment by Spitfire1900** [comment]
Closing. x-request-id header support should go in an extension jar
