### ISSUE TITLE
Prometheus exporter add duplicated suffix for counter metrics

### ISSUE THREAD

**Issue by ShadowySpirits** [open-telemetry/opentelemetry-java#5304]
**Describe the bug**
Prometheus exporter will add duplicated suffix `_total`.

**Additional context**
Prometheus exporter will add a `_total` suffix for all counter metrics. I think it should have a check that the metrics name already ends at `_total`.

https://github.com/open-telemetry/opentelemetry-java/blob/3d5424a54ae6930e721e8c4813ad956047009394/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Serializer.java#L515-L520

If the community agrees that this is a bug, I'm willing to submit a patch to fix it.

**Comment by jack-berg** [comment]
@dashpole this seems reasonable but I don't see any mention of this scenario in the [prometheus openmetrics compatibility](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#sums) document. What do you think? Should the compatibility doc be updated to say that "_total" should be appended if not already present?

**Comment by ShadowySpirits** [comment]
> @dashpole this seems reasonable but I don't see any mention of this scenario in the [prometheus openmetrics compatibility](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#sums) document. What do you think? Should the compatibility doc be updated to say that "_total" should be appended if not already present?

Hi, @jack-berg. I notice that there is such a requirement in the specification:

> Monotonic Sum metric points MUST have _total added as a suffix to the metric name.

**Comment by jack-berg** [comment]
Sorry @ShadowySpirits for the delayed reply. I see that the spec says "Monotonic Sum metric points MUST have _total added as a suffix to the metric name". I think for the behavior to be what you suggest the text would need to read something like: "Monotonic Sum metric points MUST have _total suffix. If the metric name does not end with _total, it MUST be added."

**Comment by ShadowySpirits** [comment]
> Sorry @ShadowySpirits for the delayed reply. I see that the spec says "Monotonic Sum metric points MUST have _total added as a suffix to the metric name". I think for the behavior to be what you suggest the text would need to read something like: "Monotonic Sum metric points MUST have _total suffix. If the metric name does not end with _total, it MUST be added."

Your explanation makes sense, but repeating `_total` after metrics suffixed with `_total` is weird and causes different behavior from otlp-exporter. Is it possible to clarify the interpretation of the spec?

**Comment by jack-berg** [comment]
> repeating _total after metrics suffixed with _total is weird and causes different behavior from otlp-exporter.
 💯 

@dashpole can you offer some insight here?

**Comment by ShadowySpirits** [comment]
@jack-berg @dashpole Have there been any updates? I noticed that my pull request was closed due to being stale.

**Comment by jack-berg** [comment]
Sorry about that - I thought we might get some feedback from the spec. Even though the spec doesn't explicitly describe the behavior of only adding "_total" if the name doesn't already end with it, I think its reasonable. I also think this is the behavior of the prometheus java http client. I believe this [code](https://github.com/prometheus/client_java/blob/da243e272d80d58d4b8bbf5c63d4aec4feaed51a/simpleclient/src/main/java/io/prometheus/client/Collector.java#L96-L99) strips the `_total` suffix if it exists, and this [code](https://github.com/prometheus/client_java/blob/da243e272d80d58d4b8bbf5c63d4aec4feaed51a/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L87-L89) appends it when serializing to the text format.

I re-opened and approved your PR. Thanks for you patience.

**Comment by ShadowySpirits** [comment]
@jack-berg Thanks a lot!

**Comment by jack-berg** [comment]
Thanks @dashpole. I did not update the spec.
