### ISSUE TITLE
Exercise the API with some instrumentation/integration.

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#531]
We need to exercise the API against some actual instrumentation code, and porting instrumentation for a component like Spring or OkHttp would help with that (in OpenTelemetry Python we are doing this , for example).

**Comment by kbrockhoff** [comment]
I am working on this. See issue #522 and my clone of the project.

**Comment by pavolloffay** [comment]
+1 

We should also document and bootstrap how to add instrumentations to the official release stream (assuming we agree on the package maintenance).

**Comment by jkwatson** [comment]
New Relic has a simple sample application that we're using to exercise OT via the API (i.e. no instrumentation, just manually using the API to create Spans, etc). Is there a good place to contribute that?
