### ISSUE TITLE
API: Implement OTEP 6 (Sampling)

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#532]
See https://github.com/open-telemetry/oteps/blob/master/text/0006-sampling.md

**Comment by carlosalberto** [comment]
Currently, we are only missing `SamplerHint` at the API level, as the rest has been done already.

**Comment by zenmoto** [comment]
I see that SamplingHint was removed from the OTEP with [PR #79](https://github.com/open-telemetry/oteps/pull/79)- is there anything else that needs to be done with this issue?
