### ISSUE TITLE
put baggage as Span attribute

### ISSUE THREAD

**Issue by whughchen** [open-telemetry/opentelemetry-java#5320]
**Is your feature request related to a problem? Please describe.**
Yes, I didn't find anywhere to put baggage as Span attribute

**Describe the solution you'd like**
My opentelemetry-java have `tracecparent` and `baggage` propagation, span data was export by `otlp` exporter.

I have some information propagated through baggage, I want to put baggage to Span attribute to make information be visible in jaeger UI. How can i implement this feature ?

**Describe alternatives you've considered**
PS : I already tried in SimpleSpanProcessor.onStart() but baggage is empty(not generated yet), and SimpleSpanProcessor.onEnd() but no `context` provided.
Also tried in w3cTraceContextPropagator and w3cBaggagePropagator, i can get baggage from `context` , but it doesn't provide dataobject to set baggage.

```java
// SimpleSpanProcessor
  public void onStart(Context parentContext, ReadWriteSpan span) {
   // here no baggage exist in parentContext
  }

public void onEnd(ReadableSpan span) {
   // here no baggage should exist, but no context provided
 }

// W3CTraceContextPropagator
public <C> Context extract(Context context, @Nullable C carrier, TextMapGetter<C> getter) {
    if (context == null) {
      return Context.root();
    }
    if (getter == null) {
      return context;
    }
    SpanContext spanContext = extractImpl(carrier, getter);
    if (!spanContext.isValid()) {
      return context;
    }
    return context.with(Span.wrap(spanContext));
    // here I can extrace baggage from carrier, but spanContext didn't have any fields to set baggage.
}

```

**Additional context**

**Comment by jkwatson** [comment]
Take a look at the W3CBaggagePropagator. It will put baggage into the Context, and that can be seen in a SpanProcessor implementation.

**Comment by whughchen** [comment]
> onStart() but baggage is empty(not generated yet), and SimpleSpanProcessor.onEnd() but no `context` provided.

the problem is that  in `SpanProcessor.onStart()` method baggage is empty(haven't generated/propagated yet), and `SimpleSpanProcessor.onEnd()` method no context provided.

**Comment by whughchen** [comment]
> 

the problem is that in SpanProcessor.onStart() method baggage is empty(haven't generated/propagated yet), and SimpleSpanProcessor.onEnd() method no context provided.

**Comment by whughchen** [comment]
> Take a look at the W3CBaggagePropagator. It will put baggage into the Context, and that can be seen in a SpanProcessor implementation.

the problem is that in SpanProcessor.onStart() method baggage is empty(haven't generated/propagated yet), and SimpleSpanProcessor.onEnd() method no context provided.

**Comment by jkwatson** [comment]
Well, there are several things here, so let's keep them separate:
1) Putting some baggage into the context, and making that context the current context.
2) Getting the baggage out of the current context and adding some baggage item as a span attribute.
3) Propagating baggage in & out of your process using the provided W3CBaggagePropagator

Have you been able to do any of these three things successfully? Do you have some working code you can share with what you're trying?

**Comment by mukutbhattacharjee** [comment]
@flodetan were you able to find a solution for this?

**Comment by flodetan** [comment]
> @flodetan were you able to find a solution for this?
@mukutbhattacharjee  yes, see above  :  https://github.com/open-telemetry/opentelemetry-java/issues/5320
