### ISSUE TITLE
Add unit to view's instrument selector

### ISSUE THREAD

**Issue by asafm** [open-telemetry/opentelemetry-java#5334]
**Is your feature request related to a problem? Please describe.**
OTel SDK Spec was modified to allow specifying a unit in the instrument selector: https://github.com/open-telemetry/opentelemetry-specification/issues/3101

**Describe the solution you'd like**
Adding the ability in the SDK to specify a unit in a view's instrument selector.

**Comment by asafm** [comment]
Once my design for Pulsar is approved, and no one has done it yet, I will do it.

**Comment by jack-berg** [comment]
This was completed in #5255.
