### ISSUE TITLE
SDK: Port the OC Zipkin exporter

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#534]

**Comment by breedx-nr** [comment]
Relevant source: https://github.com/census-instrumentation/opencensus-java/tree/c960b19889de5e4a7b25f90919d28b066590d4f0/exporters/trace/zipkin

**Comment by jkwatson** [comment]
@breedx-nr and I are going to tackle this one, after we've gotten the exporters reworked to use `SpanData`

**Comment by simone02f** [comment]
??
