### ISSUE TITLE
OTLP endpoint must not have a path... message

### ISSUE THREAD

**Issue by aborigene** [open-telemetry/opentelemetry-java#5345]
**Describe the bug**
Using the autoinstrumentation agent, and having to send the traces to "https://cpm50854.live.dynatrace.com/api/v2/otlp/v1/traces", I receive an error on startup complaining about misconfigurattion:

`OpenTelemetry Javaagent failed to start
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: OTLP endpoint must not have a path: /api/v2/otlp/v1/metrics`

Here is an example of my startup script:

```
#!/bin/bash
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
export OTEL_METRICS_EXPORTER=otlp
export OTEL_TRACES_EXPORTER=otlp
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=https://cpm50854.live.dynatrace.com/api/v2/otlp/v1/traces
export OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=https://cpm50854.live.dynatrace.com/api/v2/otlp/v1/metrics
export OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=delta
export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Api-Token <redacted>"
export OTEL_RESOURCE_ATTRIBUTES=service.name=SQSSample,service.namespace=DynatraceSE
#java -javaagent:/home/ec2-user/opentel-agent/aws-opentelemetry-agent.jar -jar target/demosqs-0.0.1-SNAPSHOT.jar
java -javaagent:/home/ec2-user/opentel-agent/opentelemetry-javaagent.jar -jar target/demosqs-0.0.1-SNAPSHOT.jar
```

I have tested both we the official release and AWS' agent. Both we same results.

**Steps to reproduce**
Just configure the agent to point to and endpoint that already has a path before the "v1/traces" part.

**What did you expect to see?**
The agent to startup properly and send traces and metrics to the configured endpoint. We should be able to have paths on the endpoint and the agent should enforce only that the last part of URL to be "v1/metrics/" of "v1/traces". I have tested pointing to:

`export OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=https://cpm50854.live.dynatrace.com/`

The agent starts up fine, but this endpoint does not exist.

**What did you see instead?**
The error message telling about misconfiguration.

**What version and what artifacts are you using?**
Artifacts:  opentelemetry-javaagent
Version: 1.24.0
Just loaded the agent on the command line using -javaagent: directive.

**Environment**
Compiler: N/A
OS: Amazon Linux 2
Runtime (if different from JDK above): OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

**Additional context**

**Comment by mateuszrzeszutek** [comment]
Hey @aborigene ,
Please make sure to rotate your API token - I've removed it from your post above, but it's still pretty easy to find.

**Comment by mateuszrzeszutek** [comment]
You probably need to add 
```shell
export OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
```
too. Or use the more generic
```shell
export OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
```
that handles all telemetry signals.

**Comment by aborigene** [comment]
I have changed the variables as suggested and with that I was able to workaround the problem. However I do believe this behavior should be adjusted:
1. Variable OTEL_EXPORTER_OTLP_TRACES_ENDPOINT should be checked just if it already includes the /v1/metrics, /v1/traces etc... part
2. If a signal specific configuration is missing, that should be alerted properly, in this case the OTEL_EXPORTER_OTLP_METRICS_PROTOCOL was missing, but the error did not mention that at all, it mentioned that I should not have a path on my endpoint, this error message was confusing and misleading.

**Comment by jack-berg** [comment]
We're following the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp), which requires that we use the endpoint as is without modification: 

> Based on the environment variables above, the OTLP/HTTP exporter MUST construct URLs for each signal as follow:
>
> For the per-signal variables (OTEL_EXPORTER_OTLP_<signal>_ENDPOINT), the URL MUST be used as-is without any modification. The only exception is that if an URL contains no path part, the root path / MUST be used (see [Example 2](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#example-2)).
> 
> If signals are sent that have no per-signal configuration from the previous point, OTEL_EXPORTER_OTLP_ENDPOINT is used as a base URL and the signals are sent to these paths relative to that:
> 
> Traces: v1/traces
Metrics: v1/metrics.
Logs: v1/logs.

**Comment by aborigene** [comment]
I understand, but the situation above was different.

As I was setting the protocol just for traces and not for metrics:

`export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf`

This was causing the message about the path to be shown. Per the spec above I believe we need to:

I have tested the following scenarios: 
1. All generic variables used: no verification on the endpoint path is made and no message is shown. Application along with the agent starts up fine
2. All signal specific variables (metrics and traces) used: no verification on the endpoint path is made and no message is shown. Application along with the agent starts up fine
3. Missing the OTEL_EXPORTER_OTLP_METRICS_PROTOCOL variable: a verification of the path is made and the error message is shown. We should in this case alert on the missing protocol definition instead of complaining about the endpoint, which in this case was correctly configured

Please let me know if I am missing anything here.

**Comment by jack-berg** [comment]
>As I was setting the protocol just for traces and not for metrics:

> Missing the OTEL_EXPORTER_OTLP_METRICS_PROTOCOL variable: a verification of the path is made and the error message is shown. We should in this case alert on the missing protocol definition instead of complaining about the endpoint, which in this case was correctly configured

When you set the protocol to `http/protobuf` only for traces, the metrics OTLP exporter was initialized using the default `grpc` protocol. When the protocol is `grpc` you're not allowed to specify a path since the path is automatically derived. We can't alert on the missing protocol definition because it's perfectly valid to not include the protocol definition, and therefore we don't know that the protocol definition is missing. 

You can see this more clearly in the [source code](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/internal/OtlpMetricExporterProvider.java#L35-L73). We first determine the protocol, http/protobuf or grpc. Based on the protocol, we extract and set other properties of the exporter. Note that the OTLP metric exporter is configured completely independently of the OTLP span exporter - it doesn't know (nor should it need to know) that the OTLP span exporter was configured with `http/protobuf`.

**Comment by trask** [comment]
> When the protocol is `grpc` you're not allowed to specify a path

I'm not clear why this is the case?

**Comment by jack-berg** [comment]
The path is automatically derived from the gRPC service definition. For example, a gRPC service implementing the [TraceService](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/trace/v1/trace_service.proto#L30-L34) always has a path of `/opentelemetry.proto.collector.trace.v1.TraceService/Export`. No path prefixes are allowed.

**Comment by jack-berg** [comment]
> Maybe when no protocol is defined and the configuration will fall back to default grpc a message telling that it is falling back to grpc

Adding this type of message would mean that for consistency, we should log when default values are used in all cases, since its not clear what makes the protocol case special.

The advice is to use the generic versions of the environment variables unless you have a good reason not too. Using the signal specific environment variables requires users to know more about the default values and is more error prone, as you've encountered.
