### ISSUE TITLE
Tracking getResourceAsStream() performance

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java#5369]
@jack-berg asked in #5365 for this issue to be opened.

The basic idea is that `getResourceAsStream()` can have negative performance ramifications on some platforms, specifically Android.

This can be detected when initializing the SDK on the main thread with strict mode enabled, [as shown in this issue](https://github.com/signalfx/splunk-otel-android/issues/507).

There is some detailed information about the performance of `getResourceAsStream()` and some of the causes in this article: 
https://blog.nimbledroid.com/2016/04/06/slow-ClassLoader.getResourceAsStream.html

To the extent that we can provide reasonable alternatives or remove usages of `getResourceAsStream()`, especially in SDK internals, this will help Android users. There is already a pretty well-establish precedent of not doing any heavy lifting in the service/application path and doing IO in the background, so this seems to fit in with that.

**Comment by breedx-splk** [comment]
One might be inclined to simply say "Well easy,  the Android app should just initialize the SDK on a background thread and not the main/ui thread.". 

But it's not that easy. Unfortunately, in order to track startup time and follow early application lifecycle events, the SDK must first be initialized. Without that, a mobile telemetry solution would essentially need to create its own flavor of instrumentation that could be used and deferred/buffered until the SDK initialization is completed. This parallel/shadow/deferred telemetry implementation would result in significant increase in complexity and weakens what is otherwise a straightforward use of the otel sdk.

As far as I can tell so far, there's really nothing else that's thread-blocking, nor is there other IO being done in SDK creation. If we discover some, we could address those on a case-by-case basis.

**Comment by breedx-splk** [comment]
> I'm not very familiar with android environments - are there other types of things we need to be aware of / avoid during SDK initialization besides reading from resources?

Yeah, the primary concern is doing any blocking I/O, like disk and network. The `StrictMode` builder has these methods:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/75337021/231508503-f21ce276-2b1c-4092-9180-0e8f20d2a908.png">

I wonder if we'll hit DNS lookups again. 

There are a few things in the android sdk that we were already able to defer or otherwise make lazy, but I can't remember details offhand.

**Comment by jack-berg** [comment]
> I wonder if we'll hit DNS lookups again.

Do you have ideas of when DNS lookups might occur during initialization?

**Comment by breedx-splk** [comment]
> > I wonder if we'll hit DNS lookups again.
> 
> Do you have ideas of when DNS lookups might occur during initialization?

I don't. 

I don't mind chatting through these things so that there's a record in case we eventually want to circle back....but I hope we can prevent this issue from becoming an android startup-delay omnibus instead of keeping the discussion narrowly focused on the thing we do know already causes a problem.
