### ISSUE TITLE
`Authenticator` interface can't be used with `OtlpHttpSpanExporter`

### ISSUE THREAD

**Issue by GerardPaligot** [open-telemetry/opentelemetry-java#5389]
**Describe the bug**
We can't use the `Authenticator` interface to configure http client used by `OtlpHttpSpanExporter`. You can only use `Authenticator` interface with `OkHttpExporterBuilder` which is used internally by the span exporter.

**Steps to reproduce**
```kotlin
val exporter: OtlpHttpSpanExporter =
    OtlpHttpSpanExporter.builder()
        .setEndpoint("http://localhost:4318/v1/traces")
        .build()
Authenticator.setAuthenticatorOnDelegate(exporter, Authenticator {
    return@Authenticator mapOf(
        "Authorization" to "Bearer <token>"
    )
})
```

```bash
Caused by: java.lang.IllegalArgumentException: Delegate field is not type DefaultGrpcExporterBuilder or OkHttpGrpcExporterBuilder.
    at io.opentelemetry.exporter.internal.auth.Authenticator.setAuthenticatorOnDelegate(Authenticator.java:48)
```

**What did you expect to see?**
It should be possible to configure an authentication interceptor / delegate to generate a valid token when it is necessary

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-api`, `opentelemetry-sdk`, `opentelemetry-exporter-otlp`, `opentelemetry-exporter-common`
Version: 1.25.0

**Environment**
Compiler: zulu JDK 17
OS: macOS 13.3.1

**Comment by jack-berg** [comment]
I've verified authenticator and `Authenticator.setAuthenticatorOnDelegate` are working as expected. Added an additional test case in #5391 to be sure.

I see in your repro you are trying to set the authenticator on the exporter instead of on the exporter builder. Try this instead:
```
val exporterBuilder: OtlpHttpSpanExporterBuilder =
    OtlpHttpSpanExporter.builder()
        .setEndpoint("http://localhost:4318/v1/traces")
Authenticator.setAuthenticatorOnDelegate(exporterBuilder, Authenticator {
    return@Authenticator mapOf(
        "Authorization" to "Bearer <token>"
    )
})
```

**Comment by jack-berg** [comment]
Closing as #5391 indicates that the API is working as expected.
