### ISSUE TITLE
Add trace information in responses.

### ISSUE THREAD

**Issue by lurbanski-equinix** [open-telemetry/opentelemetry-java#5421]
Hi guys, 

**Is your feature request related to a problem? Please describe.**
When I receive request/response from client. I don't see trace-id header in http response. With that debugging a problem would be a lot faster.
I think it refers to all kind of responses. e.g. grpc, http etc

**Describe the solution you'd like**
I would gladly see "trace-id" in responses e.g. as http header etc.

Best,
Łukasz

**Comment by jkwatson** [comment]
Hello @lurbanski-equinix . 
1) This is probably an issue for instrumentation, not for the core APIs and SDK
2) You can implement this yourself today, by getting access to the current span and using it's SpanContext to write your response headers.

**Comment by lurbanski-equinix** [comment]
Thank you @jkwatson for your quick response.
I've created an issue https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8421
