### ISSUE TITLE
OTLP gRPC exporter giving error while sending lots of attributes with 3 metrics instrumentation together

### ISSUE THREAD

**Issue by bhupeshpadiyar** [open-telemetry/opentelemetry-java#5471]
**Describe the bug**

When I am sending 3 different metrics (2 counter and 1 histogram) simanteously with OTEL java SDK, I am having a weird issue of dropping the metrics with the following GRPC error message.

**2023-05-24 18:25:54.185 ERROR 1379487 --- [ty.net:4318/...] i.o.e.internal.grpc.OkHttpGrpcExporter   : Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR**

[**okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR, okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR]**

**Steps to reproduce**
Here is a sample code to reproduce the error.

```
private static final String[] COUNTRIES = new String[] {"MY","SG","TH", "PH", "ID", "JP", "KR", "VN"};
	private static final String[] PRODUCTS = new String[] {"product1","product2","product3", "product4", "product5", "product6", "product7", "product8"};

	private static final String[] SUCESS = new String[] {"true", "false"};

	private static final String[] LATENCY_URL = new String[] {"/url1", "/url2", "/url3", "/url4"};

	private static final String[] OBJECT_ARRAY = new String[] {"attrObject1", "attrObject2", "attrObject3", "attrObject4", "attrObject5","attrObject6", "attrObject7", "attrObject8", "attrObject9"};

	private static final String[] PC_CHANNEL = new String[] {"PC1","PC2","PC3", "PC4", "PC5", "PC6", "PC7", "PC8"};

	private static final String METRIC_NAME_COUNT_TRANSACTION="pay.transactions.count.debug";
	private static final String METRIC_NAME_HISTOGRAM_TRANSACTION="pay.transactions.latency.debug";
	private static final String METRIC_NAME_TPV="pay.transactions.tpv.debug";

	
	public static void main(String[] args) throws Exception {

		OpenTelemetry openTelemetry = OpentelemetryConfiguration.initOpenTelemetry();

		Meter meter = openTelemetry.getMeter("io.opentelemetry.example");
		LongCounter txnCounter = meter.counterBuilder(METRIC_NAME_COUNT_TRANSACTION).build();
		DoubleCounter tpvCounter = meter.counterBuilder(METRIC_NAME_TPV).ofDoubles().build();
		LongHistogram latencyHistogram = meter.histogramBuilder(METRIC_NAME_HISTOGRAM_TRANSACTION).ofLongs().setUnit("ms").build();

		sendPayMetrics(txnCounter, tpvCounter, latencyHistogram);

	}

	public static void sendPayMetrics(LongCounter txnCounter, DoubleCounter tpvCounter, LongHistogram latencyHistogram) {

		while(true) {
			try {
				Map<String, String> attributes = getMetricsAttributes();
				Attributes attributesList = null;


				for(Map.Entry<String , String> entry : attributes.entrySet()) {
					Attributes attrObject = Attributes.of(stringKey(entry.getKey()), entry.getValue());
					if(attributesList==null) {
						attributesList = attrObject;
					}
					attributesList = attributesList.toBuilder().putAll(attrObject).build();

				}

				sendTransactionCountMetrics(txnCounter, attributesList);
				sendTransactionLatencyMetrics(latencyHistogram, attributesList);
				sendTPVMetrics(tpvCounter, attributesList);
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

	private  static void sendTransactionCountMetrics(LongCounter txnCounter, Attributes attributesList) {

		try {
			txnCounter.add(1, attributesList);
		} catch (Exception e) {
			e.getMessage();
		}
	}

	private static void sendTransactionLatencyMetrics(LongHistogram latencyHistogram, Attributes attributesList) {
		try {
			long latencyTime =  generateRandomLatency();
			latencyHistogram.record(latencyTime, attributesList);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static void sendTPVMetrics(DoubleCounter tpvCounter, Attributes attributesList) {
		Map<String, String> metricsTags = new LinkedHashMap<>();
		try {
			tpvCounter.add(generateRandomTPV(), attributesList);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static Map<String, String> getMetricsAttributes() {
		Map<String, String> attributes = new LinkedHashMap<>();
		String isSuccess = getRandomStatus();
		String product = getRandomProduct();
		String country = getRandomCountry();
		String currency = "USD";
		String pcChannnel= getRandomPC();
		String endpoint = getRandomUrl();

		attributes.put("environment", "staging");

		attributes.put("isSuccess", isSuccess);
		attributes.put("product", product);
		attributes.put("country", country);
		attributes.put("currency", currency);
		attributes.put("endpoint", endpoint);
		attributes.put("pcChannel", pcChannnel);
		attributes.put("dumyAttributeKey1", getRandomIndex());
		attributes.put("dumyAttributeKey2", "dumyAttributeValue2");
		attributes.put("dumyAttributeKey3", "dumyAttributeValue3");
		attributes.put("dumyAttributeKey4", "dumyAttributeValue4");
		attributes.put("dumyAttributeKey5", "dumyAttributeValue5");
		attributes.put("dumyAttributeKey6", "dumyAttributeValue6");
		attributes.put("dumyAttributeKey7", "dumyAttributeValue7");
		attributes.put("dumyAttributeKey8", "dumyAttributeValue8");
		attributes.put("dumyAttributeKey9", "dumyAttributeValue9");
		attributes.put("dumyAttributeKey10", "dumyAttributeValue10");
		attributes.put("dumyAttributeKey11", "dumyAttributeValue11");
		attributes.put("dumyAttributeKey12", "dumyAttributeValue12");
		attributes.put("dumyAttributeKey13", "dumyAttributeValue13");
		attributes.put("dumyAttributeKey14", "dumyAttributeValue14");
		attributes.put("dumyAttributeKey15", "dumyAttributeValue15");

		return  attributes;
	}

	private static double getValues() {
		double rnd = new Random().nextDouble();
		return rnd;
	}

	private static long getValues(int rangeMin, int rangeMax) {
		Random r = new Random();
		long randomValue = rangeMin + (rangeMax - rangeMin) * r.nextLong();
		return randomValue;

	}

	private static String getRandomPC() {
		int rnd = new Random().nextInt(PC_CHANNEL.length);
		return PC_CHANNEL[rnd];

	}

	public static synchronized String getRandomCountry() {
		int rnd = new Random().nextInt(COUNTRIES.length);
		return COUNTRIES[rnd];
	}

	public static synchronized String getRandomProduct() {
		int rnd = new Random().nextInt(PRODUCTS.length);
		return PRODUCTS[rnd];
	}

	public static synchronized String getRandomStatus() {
		int rnd = new Random().nextInt(SUCESS.length);
		return SUCESS[rnd];
	}

	public static synchronized String getRandomUrl() {
		int rnd = new Random().nextInt(LATENCY_URL.length);
		return LATENCY_URL[rnd];
	}

	public static synchronized int generateRandomLatency() {
		Random objGenerator = new Random();
		return objGenerator.nextInt(30000);
	}

	public static synchronized int generateRandomTPV() {
		Random objGenerator = new Random();
		return objGenerator.nextInt(10);
	}

	public static synchronized String getRandomIndex() {
		int rnd = new Random().nextInt(OBJECT_ARRAY.length);
		return OBJECT_ARRAY[rnd];

	}
}
```

**What did you expect to see?**

Metrics were smoothly sent to Collector without any disruption/exceptions in App and collector side

**What did you see instead?**

Losing the metrics and getting the following error logs in the App console:

2023-05-24 18:25:54.185 ERROR 1379487 --- [ty.net:4318/...] i.o.e.internal.grpc.OkHttpGrpcExporter   : Failed to export metrics. The request could not be executed. Full error message: stream was reset: NO_ERROR

**What version and what artifacts are you using?**
Artifacts: (e.g., `opentelemetry-api`, `opentelemetry-sdk`, `opentelemetry-exporter-otlp`, `opentelemetry-semconv`, `grpc-netty-shaded`, )
Version: (e.g., `v1.26.0`, `v1.26.0`, `v1.26.0`, `1.24.0-alpha`, `1.54.0`,)
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`)

**Environment**
Compiler: openjdk version "1.8.0_362
OS: Mac OS Ventura - 13.3.1 (a)
Runtime (if different from JDK above): OpenJDK Runtime Environment Corretto-8.362.08.1 (build 1.8.0_362-b08)
OS (if different from OS compiled on): Amazon Linux 2023

**Additional context**
This problem arises when we instrument 3 metrics together with lots of attributes (around 22) per metric instrumentation. 
This seems working fine with 3 metrics instrumentation together but less attributes (around 15-8 attributes).

**Comment by trask** [comment]
can you check if you're seeing the same issue as #5394?

**Comment by bhupeshpadiyar** [comment]
Hi, It looks partially similar. 

- I am getting this error only if I increase the number of attributes and instrument 3 metrics together.
- I am not receiving any error on receiving side (Collector) in my case. The collector just stopped receiving the metrics.

**Comment by jack-berg** [comment]
@bhupeshpadiyar I'm not able to recreate the error with the provided code. Couple of followup questions:

- Is the collector on the same machine as the java app? 
- Is there any load balancer between the app and the collector? 
- Do you get the same error if you export to a collector running locally on the same machine as the application? 
- Do you get the same error if using the http/probotuf version of the OTLP exporter, `OtlpHttpMetricExporter`?

**Comment by bhupeshpadiyar** [comment]
Hi @jack-berg, the error is not appearing immediately but appears 5-6 mins after starting the application. Can you please keep it running for 5-7 mins to reproduce?

- Is the collector on the same machine as the Java app?

> I tried both ways: 
> 
> - Sending to the local collector first and then sending it to a centralized collector load balancer. 
> - Sending it to a centralized collector load balancer.

In both cases, I am having this problem.

- Is there any load balancer between the app and the collector?

> - Yes there is a load balancer between the app and the collector to export the metrics

- Do you get the same error if you export to a collector running locally on the same machine as the application?

> - Yes I am getting the same error in both cases.
 
- Do you get the same error if using the http/probotuf version of the OTLP exporter, OtlpHttpMetricExporter?

> - Yes I tried it with OtlpHttpMetricExporter, and with that, I am getting following timeout error message after some time
> - **Failed to export metrics. The request could not be executed. Full error message: timeout**
> - Following is my configuration at SDK and collector level   
> 
> ```
> receivers:
>   # Receive OTLP metrics from apps
>   otlp:
>     protocols:
>       http:
>         endpoint: "0.0.0.0:4318"
> ```
> 
>  ```
> SdkMeterProvider.builder()
>                                         .setResource(resource)
>                                         .registerMetricReader(
>                                                 PeriodicMetricReader.builder(OtlpHttpMetricExporter.builder()
>                                                         .setEndpoint(OTEL_EXPORTER_ENDPOINT)
> ```

**Comment by jack-berg** [comment]
I tried replicating this running a collector locally, and also running a collector behind a load balancer in an external kubernetes environment. I was not able to replicate in either case. It seems particularly unlikely for the error to occur when the collector is running locally.

Some general thoughts:
- For `stream was reset: NO_ERROR` errors: These are almost always due to some sort of transient networking issue. Most often I've seen them with load balancers which have connection timeout mismatches with the server they sit in front of. I've seen these types of issues with gRPC a lot more than with http. General advice is to enable retry, since transient network issues are always going around, see if you can debug the load balancer to make sure its settings are aligned with the server, and consider using the `OtlpHttp{Signal}Exporter` instead of `OtlpGrpc{Signal}Exporter`.
- For `The request could not be executed. Full error message: timeout` errors: These will occur as a function of payload size, timeout settings, and network latency. To reduce the payload size for traces and logs, you can reduce the batch size of the `Batch{Signal}Processor`, or reduce the number / length of attributes. Its harder to control the payload size of metrics, but one option is to limit cardinality with views. Also be sure to enable gzip compression. You can extend the timeout setting of the exporters as well. Nothing you can do about network latency in SDK configuration. However, you can increase the probability of a successful export by enabling retry.

There doesn't appear to be any programming error with the OTLP exporters, so I'm inclined to chalk this up to transient network issues. If you can provide data that suggests otherwise, I can look into it further.

**Comment by bhupeshpadiyar** [comment]
Hi @jack-berg, this is strange. I am able to replicate this issue in all the environments (local, docker, EC2). with the above example code.

One thing I have missed is to include the SDK config code in the sample code above.

`OpenTelemetry openTelemetry = OpentelemetryConfiguration.initOpenTelemetry();`

Following is my SDK init code. Can you please help to verify if the OTEL SDK config code is correct and the same as yours? Or I am missing something here?

```
import static io.opentelemetry.semconv.resource.attributes.ResourceAttributes.SERVICE_NAME;

import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.exporter.otlp.http.metrics.OtlpHttpMetricExporter;
import io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter;
import io.opentelemetry.sdk.OpenTelemetrySdk;
import io.opentelemetry.sdk.metrics.SdkMeterProvider;
import io.opentelemetry.sdk.metrics.export.PeriodicMetricReader;
import io.opentelemetry.sdk.resources.Resource;
import java.time.Duration;


public class OpentelemetryConfiguration {
    /**
     * Initialize OpenTelemetry.
     *
     * @return a ready-to-use {@link OpenTelemetry} instance.
     *
     */

    private static final String OTEL_EXPORTER_OTLP_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT";
    private static final String OTEL_EXPORTER_OTLP_ENDPOINT_DEFAULT = "http://localhost:4318/v1/metrics";

    static OpenTelemetry initOpenTelemetry() {
        // Include required service.name resource attribute on all spans and metrics

        String OTEL_EXPORTER_ENDPOINT = System.getenv(OTEL_EXPORTER_OTLP_ENDPOINT) == null ? OTEL_EXPORTER_OTLP_ENDPOINT_DEFAULT : System.getenv(OTEL_EXPORTER_OTLP_ENDPOINT);

        Resource resource =
                Resource.getDefault()
                        .merge(Resource.builder().put(SERVICE_NAME, "OtlpExporterExample").build());

        OpenTelemetrySdk openTelemetrySdk =
                OpenTelemetrySdk.builder()
                        .setMeterProvider(
                                SdkMeterProvider.builder()
                                        .setResource(resource)
                                        .registerMetricReader(
                                                PeriodicMetricReader.builder(OtlpGrpcMetricExporter.builder()
                                                        .setEndpoint(OTEL_EXPORTER_ENDPOINT)
                                                        .build())
                                                        .setInterval(Duration.ofMillis(1000))
                                                        .build())
                                        .build())
                        .buildAndRegisterGlobal();

        Runtime.getRuntime().addShutdownHook(new Thread(openTelemetrySdk::close));

        return openTelemetrySdk;
    }
}
```


Thanks

**Comment by jack-berg** [comment]
Sorry for the delay - lost track of this. Your code is correct.
