### ISSUE TITLE
Empty string should be a valid attribute value

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#5501]
From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute:

> Attribute values expressing a numerical value of zero, an empty string, or an empty array are considered meaningful and MUST be stored and passed on to processors / exporters.

Empty strings are important for `url.query` where empty strings are important to preserve to represent urls like `http://xyz/path?`

The Span API javadoc currently says that the behavior for an empty string value is "undefined" (I haven't checked what the actual implementation does):

https://github.com/open-telemetry/opentelemetry-java/blob/60bb0a7025f557f2de3b485d9f8c62bc1d93faed/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L94-L95

**Comment by jack-berg** [comment]
It looks like the implementation ignores `null` values, but sets empty strings. Should update the javadoc and confirm with a test (if none exists) while we're at it.

**Comment by erharjotsingh** [comment]
hello @jack-berg @trask 
Could you please summarize the issue and I can pick this up. Thanks!
