### ISSUE TITLE
Current Span API doesn't meet the requirements of the Resources specification

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#551]
Specification here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-resources.md

Here is the relevant paragraph in the spec:
```
When used with distributed tracing, a resource can be associated with the Tracer. When associated with Tracer, all Spans produced by this Tracer will automatically be associated with this Resource. When associated with a Span explicitly for out-of-band spans - Resource that is set on Tracer MUST be ignored. Note, that association of Tracer with the Resource will be done in SDK, not as API call.
```

Currently, the only way to get a Resource associated with a Tracer is via a legacy `OC_*` environment variable. And, there is no API to associate a Resource with a Span directly. I'm not sure what "Note, that association of Tracer with the Resource will be done in SDK, not as API call." means for this; perhaps the spec needs some clarification on that point and what it means.

**Comment by jkwatson** [comment]
Just a note...I chatted offline with @mwear and he said that parts of this spec might be being superceded by https://github.com/open-telemetry/oteps/blob/master/text/0007-no-out-of-band-reporting.md#resource-changes

**Comment by bogdandrutu** [comment]
We do not want to allow in the API users to configure the Resource:
1. The instrumentation/library developer does not know information about the environment where the final application will run.
1. The information about the Resource is only known by the SRE (or the person who deploys/runs the binary in production). So it cannot be hardcoded in Code.

So I think supporting a config file and environment variables is probably enough.

**Comment by jkwatson** [comment]
The current environment variable method leaves a lot to be desired. Rather than having that environment variable (which has the old open census name right now), be required to be a strange comma/equals format, why not leave the configuration up to the engineer who is using Open Telemetry? Why would we want to restrict the ways that people can use these libraries? We should support the most flexible possible means of configuring the SDK, rather than forcing people down a path that we think is "best". 

I don't know how you get the current host name out of an environment variable in all environments. Maybe it works in a subset to get host names out of the environment, but it's certainly not a universal truth. 

Ultimately, an engineer is going to have to put OT into their codebase. Leaving the means of configuring the SDK up to them seems like the most flexible option.

I think @kbrockhoff might have some opinions on this, as well.

**Comment by bogdandrutu** [comment]
Resource was moved to the SDK. Probably worth closing this and opening another issue that is related to the SDK.

**Comment by bogdandrutu** [comment]
@jkwatson do we still need this issue, if yes please explain what is left

**Comment by jkwatson** [comment]
yeah, let's close this. The issue is now in the SDK, rather than the API.
