### ISSUE TITLE
Issue while sending metrics to prometheus (grafana cloud).

### ISSUE THREAD

**Issue by akshayraina-github** [open-telemetry/opentelemetry-java#5551]
Hello Team,

While sending metrics to grafana prometheus cloud, i am getting below error 
`[otel.javaagent 2023-06-19 17:12:17:649 +0530] [OkHttp https://prometheus-us-central2.grafana.net/...] WARN io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export metrics. Server responded with HTTP status code 400. Error message: Unable to parse response body, HTTP status message:`

Note: /actuator  and /actuator/prometheus endpoints are working fine.

application.properties
```
otel.exporter.otlp.traces.endpoint=https://tempo-prod-09-us-central2.grafana.net
otel.exporter.otlp.traces.headers=Authorization=Basic encoded username and password
otel.exporter.otlp.logs.endpoint=https://logs-prod-us-central2.grafana.net/loki/api/v1/push
otel.exporter.otlp.logs.headers=Authorization=Basic encoded username and password
otel.exporter.otlp.metrics.endpoint=https://prometheus-us-central2.grafana.net/api/prom/push
otel.exporter.otlp.metrics.headers=Authorization=Basic encoded username and password
otlp.metrics.exporter=prometheus
otel.resource.attributes=service.name=app-a,compose_service=app-a
otel.exporter.otlp.metrics.protocol=http/protobuf
logging.pattern.level=trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p
management.endpoints.web.exposure.include=prometheus
management.metrics.tags.application=app
management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.application.name=monitoring-demo
```

Please help

Thank you

**Comment by jack-berg** [comment]
> I am getting trace id in logs, How can get trace id in service methods?

This likely isn't the right repository for this type of question. If you're using instrumentation from `opentelemetry-java-isntrumentation` I can transfer the issue to that repository.
