### ISSUE TITLE
Unable to export logs, getting "SEVERE: Failed to export logs. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180"

### ISSUE THREAD

**Issue by quintonn** [open-telemetry/opentelemetry-java#5596]
**Describe the bug**
I am trying to have my **log.info** calls go to my OTLP collector, but it's failing with the error in the title.

I am trying to determine the most simple way to do this, but I am struggling to process the documentation around this.
I would really appreciate some help.

Below is the code I am running.
``` JAVA
public class OtlpTest {

    private static final Resource RESOURCE = Resource.getDefault().toBuilder()
        .put(ResourceAttributes.SERVICE_NAME, "quintonn java test")
        .build();

    public static void run() {

        final String otlpEndpoint = "http://localhost:4312";
        final String logEntry = "This is a log entry.";

        // Create an OTLP HTTP exporter
        final OtlpHttpLogRecordExporter exporter = OtlpHttpLogRecordExporter.builder()
            .setEndpoint(otlpEndpoint)
            .build();

        System.setProperty("otel.exporter.otlp.endpoint", otlpEndpoint);
        System.setProperty("otel.exporter.otlp.timeout", "10000");
        System.setProperty("otel.blrp.schedule.delay", "60000");

        final OpenTelemetrySdk openTelemetrySdk = AutoConfiguredOpenTelemetrySdk.initialize().getOpenTelemetrySdk();

        final io.opentelemetry.api.logs.Logger logger = GlobalOpenTelemetry.get().getLogsBridge().get("test");
        logger.logRecordBuilder().setBody("debug log message").setSeverity(io.opentelemetry.api.logs.Severity.DEBUG).emit();
        logger.logRecordBuilder().setBody("info log message").setSeverity(io.opentelemetry.api.logs.Severity.INFO).emit();

        openTelemetrySdk.getSdkLoggerProvider().forceFlush().join(10, TimeUnit.SECONDS);

        final org.slf4j.Logger log = LoggerFactory.getLogger(OtlpTest.class);
        log.info("This is a test");
    }

}
```
And my Maven POM dependency extrac:
``` XML
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-bom</artifactId>
				<version>1.27.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-semconv</artifactId>
            <version>1.26.0-alpha</version>
        </dependency>
        
        <!-- https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure -->
		<dependency>
		    <groupId>io.opentelemetry</groupId>
		    <artifactId>opentelemetry-sdk-extension-autoconfigure</artifactId>
		    <version>1.27.0-alpha</version>
		</dependency>		
		<dependency> 
		  <groupId>org.slf4j</groupId>
		  <artifactId>slf4j-simple</artifactId>
		  <version>2.0.7</version>
		</dependency>
```

I want to send logs that are created with `log.info` to my otel collector.

**Steps to reproduce**
Run my code

**What did you expect to see?**
Expected to see the logs being sent to my otel collector listening on the http endpoint.

**What did you see instead?**
Saw the error: SEVERE: Failed to export logs. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk`, OtlpHttpLogRecordExporter
Version: 1.27.0
How did you reference these artifacts? Maven in **pom.xml**

**Environment**
Compiler: Eclipse. Setting compiler  to 1.8. 
OS: windows 10

**Additional context**
Another thing I noticed is that I want my http endpoint to be "http://localhost:4312/otlp" but the /otlp results in another error that I cannot set the path value in the URL. Why is that, or is there a work-around?

**Comment by jack-berg** [comment]
Have you seen the [docs](https://opentelemetry.io/docs/instrumentation/java/manual/#logs) explaining the different workflows for using logs, for [manually configuring the SDK](https://opentelemetry.io/docs/instrumentation/java/manual/#logs-sdk), or for leveraging [autoconfigure](https://opentelemetry.io/docs/instrumentation/java/manual/#auto-configuration) to automatically configure the SDK based on environment variables. system properties?

> final io.opentelemetry.api.logs.Logger logger = GlobalOpenTelemetry.get().getLogsBridge().get("test");
 logger.logRecordBuilder().setBody("debug log message").setSeverity(io.opentelemetry.api.logs.Severity.DEBUG).emit();

The logs bridge API is not meant for use by appenders to bridge logs from other frameworks (e.g. log4j2 / logback) into OpenTelemetry. Its not meant for direct use by users as you show here.

> Saw the error: SEVERE: Failed to export logs. The request could not be executed. Full error message: FRAME_SIZE_ERROR: 4740180

You receive this code running the code you show here? That's unexpected since the error message indicates that a frame is too big, yet I only see a couple small log records being emitted.

```
final OtlpHttpLogRecordExporter exporter = OtlpHttpLogRecordExporter.builder()
            .setEndpoint(otlpEndpoint)
            .build();

        System.setProperty("otel.exporter.otlp.endpoint", otlpEndpoint);
        System.setProperty("otel.exporter.otlp.timeout", "10000");
        System.setProperty("otel.blrp.schedule.delay", "60000");

        final OpenTelemetrySdk openTelemetrySdk = AutoConfiguredOpenTelemetrySdk.initialize().getOpenTelemetrySdk();
```
Here you setup an exporter which is unused, since you initialize the SDK using autoconfigure.

>final String otlpEndpoint = "http://localhost:4312";

You probably have the port wrong - the standard port for OTLP is 4317.

> Another thing I noticed is that I want my http endpoint to be "http://localhost:4312/otlp" but the /otlp results in another error that I cannot set the path value in the URL. Why is that, or is there a work-around?

By default the gRPC version of the OTLP protocol is used. In gRPC, the path is not configurable since it is automatically implied from the protobuf specification implemented by the server. In the http/protobuf version of OTLP, the path is configurable, but is almost always `/v1/traces`, `/v1/metrics`, `/v1/logs`. The collector definitely doesn't accept OTLP data at path `/otlp`. At least not by default anyway.

**Comment by jkwatson** [comment]
> The logs bridge API is not meant for use by appenders to bridge logs from other frameworks (e.g. log4j2 / logback) into OpenTelemetry. Its not meant for direct use by users as you show here.

I think you mean "The logs bridge API _is_ meant for use by appenders.... "

**Comment by quintonn** [comment]
Hi,
I found some example code to do what I need.
Not using the auto configure code.

**Comment by SatishSingh2103** [comment]
I am trying to send data over http by using following code
 opentelemetry::sdk::resource::ResourceAttributes attributes = {
   {"service.name", "my_test_service"} };
 auto resource = opentelemetry::sdk::resource::Resource::Create(attributes);

	
 logs_exporter::OtlpHttpLogRecordExporterOptions opts;
	opts.url = "http://localhost:4318/v1/logs";
	opts.console_debug = true;
	opts.content_type = logs_exporter::HttpRequestContentType::kJson;
	opts.json_bytes_mapping = logs_exporter::JsonBytesMappingKind::kBase64;
	opts.use_json_name = true;
	opts.timeout = std::chrono::system_clock::duration(1000ms);  

  
 auto exporter = std::unique_ptr<logs_sdk::LogRecordExporter>(new logs_exporter::OtlpHttpLogRecordExporter(opts));  
 auto processor = logs_sdk::SimpleLogRecordProcessorFactory::Create(std::move(exporter));


 
 std::shared_ptr<logs_sdk::LoggerProvider> sdk_provider(
     logs_sdk::LoggerProviderFactory::Create(std::move(processor), resource));

 
 const std::shared_ptr<logs_api::LoggerProvider>& api_provider = sdk_provider;    
 opentelemetry::logs::Provider::SetLoggerProvider(api_provider);

auto provider = logs_api::Provider::GetLoggerProvider();
auto logger = provider->GetLogger("my_test_logger");
std::string str = "Hello This is http data sending to collector..!";
logger->Log(logs_api::Severity::kInfo, str.data());


but is is giving error as 
'SampleConsoleApp.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'. Symbol loading disabled by Include/Exclude setting.
Critical error detected c0000374
Exception thrown at 0x00007FFB5E00F3C9 (ntdll.dll) in SampleConsoleApp.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFB5E0797F0).
Unhandled exception at 0x00007FFB5E00F3C9 (ntdll.dll) in SampleConsoleApp.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFB5E0797F0).

Please see the issue.. And try to give some solution what I can do now..

**Comment by jack-berg** [comment]
Hi @SatishSingh2103 please open a new issue to make sure this gets seen. Also, I'm not familiar with some of this syntax. What language are you using?
