### ISSUE TITLE
Java OtlpHttpMetricExporter does not produce JSON formatted output

### ISSUE THREAD

**Issue by prashanthr-sn** [open-telemetry/opentelemetry-java#5598]
**Describe the bug**
Per the docs, setting environment variable OTEL_EXPORTER_OTLP_METRICS_PROTOCOL or setting Java system property to "http/json" is supposed to produce JSON formatted output.  However, neither of the settings produce JSON.

https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/#otel_exporter_otlp_metrics_protocol

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-span-metric-and-log-exporters

**Steps to reproduce**
Any instrumented program using OtlpHttpMetricExporter.builder()....build() and run with the environment variable or system property set as described.  Upon running the output is still binary/protobuf and not JSON.  The Content-Type remains application/x-protobuf

**What did you expect to see?**
JSON formatted output. The Content-Type from the client should be "application/json" (https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding)

**What did you see instead?**
Output was binary/protobuf format and not JSON.  The Content-Type remains application/x-protobuf

**What version and what artifacts are you using?**
Artifacts: (e.g., `opentelemetry-api`, `opentelemetry-sdk`, which exporters, etc)
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)

**Environment**
Compiler: Azul JDK 8
OS: Mac OS
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**
Looking at
https://github.com/open-telemetry/opentelemetry-java/blob/f20ee6ccbf75b277e4652ef08b9677f9e17b3767/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/http/metrics/OtlpHttpMetricExporterBuilder.java#L160
there is an exportAsJson().  But, the method is not public.  Is it supposed to have been public?  

The test class
https://github.com/open-telemetry/opentelemetry-java/blob/f20ee6ccbf75b277e4652ef08b9677f9e17b3767/exporters/otlp/all/src/test/java/io/opentelemetry/exporter/otlp/internal/OtlpMetricExporterProviderTest.java#L4
also does not have any tests for "http/json", but only for "http/protobuf".
So.. is JSON output supported?

**Comment by mateuszrzeszutek** [comment]
Hey @prashanthr-sn ,

SDK support for the `http/json` format is [optional](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#specify-protocol):
> SDKs SHOULD support both `grpc` and `http/protobuf` transports and MUST support at least one of them. If they support only one, it SHOULD be `http/protobuf`. They also MAY support `http/json`.

The Java SDK does not have the JSON exporter implemented. Here's some more history about that: #3651 #3486
I'm quite convinced we're not planning to implement it in the future -- ping @jack-berg to confirm.

**Comment by jack-berg** [comment]
> I'm quite convinced we're not planning to implement it in the future 

I can confirm that it's not supported and we do not plan on implementing it. Closing this issue accordingly.
