### ISSUE TITLE
Allow tracestate to begin with a digit

### ISSUE THREAD

**Issue by breedx-nr** [open-telemetry/opentelemetry-java#562]
The tracestate spec changed to allow tracestate identifier to begin with a digit.  Reference https://www.w3.org/TR/trace-context/#key and corresponding fix merged in this PR:
https://github.com/w3c/trace-context/pull/332

The Open Telemetry Tracestate should change its verification to allow start digits in tracestate identifiers.  It currently results in an exception like:

```
java.lang.IllegalArgumentException: Invalid key 1@nr
```

**Comment by adriancole** [comment]
wow numbers and '@' signs now. I'm sure shell scripted will love having to
single quote.

**Comment by adriancole** [comment]
anyway it is less a shell script issue vs generally questionable to choose
to allow characters that routinely require escaping in key names in a new
spec.

**Comment by breedx-nr** [comment]
That's fair.  I don't have much insight at the moment on the why of the choice of `@`, but the spec creators needed something to denote the vendor prefix...and all the standard chars were taken 🤷‍♂ ?

**Comment by adriancole** [comment]
rigor is limited to a few companies. almost never amazon for example. in
fact amazon ARN permits * but primarily uses colons as a delimiter

https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html

I dont have the time or patience to try again to push w3c back into shape
but if you or someone else could get things more rigorous, less calamity
for others
