### ISSUE TITLE
How to get parent span information based on span？

### ISSUE THREAD

**Issue by jjiiee11** [open-telemetry/opentelemetry-java#5623]
Hi,
opentelemetry-api: 1.25.0
How to get parent span information based on span？Is there an API that supports this feature？

**Comment by breedx-splk** [comment]
The design is such that the `Span` interface is intended to be mostly writable. That is, when dealing with a `Span` you are generally adding things to it (events, attributes, status), not reading from it. 

The `ReadableSpan` is able to expose the parent information. The `SdkSpan` is an implementation of a `ReadableSpan`.

```
ReadWriteSpan span = [...];
SpanContext parentContext = span.getParentSpanContext();
Span parentSpan = Span.wrap(parentContext);
[...]
```

The `SpanData` interface also exposes parent span context.

Hopefully that helps with your use case.

**Comment by jjiiee11** [comment]
Thank you, your answer helped a lot.
