### ISSUE TITLE
Trace propagation relies on case-sensative headers

### ISSUE THREAD

**Issue by esecules** [open-telemetry/opentelemetry-java#5626]
**Describe the bug**
Trace propagation only properly works when the headers map being passed in has keys which equal exactly the keys in the specific trace propagator they correspond to. HTTP header names are case-insensitive.

**Steps to reproduce**
Use b3multi trace propagation and send the following headers exactly
Kong creates these headers and Linkerd Proxy also lower-cases all headers passing through it.
```
x-b3-traceid: 7163ec7f03088aa4a8f8e78e8898d990
x-b3-spanid: ca15d6f7f53af190
x-b3-sampled: 1
```
This does not result in a child span getting created within trace `7163ec7f03088aa4a8f8e78e8898d990`

However when I transform the headers to this before feeding them to OpenTelemetry, it works:
```
X-B3-TraceId: 7163ec7f03088aa4a8f8e78e8898d990
X-B3-SpanId: ca15d6f7f53af190
X-B3-Sampled: 1
```
This is not specific to b3multi propagation, it also happens to the W3C tracecontext propagator. If I send `traceparent` header it works, but not `traceParent` or any other combination.

**What did you expect to see?**
I expect that trace propagation works when the proper headers are sent using any case.

**What did you see instead?**
Rather than creating a child span under an existing trace, it created a new trace because it could not find an exact match for the headers.

**What version and what artifacts are you using?**
I am using scala, `otel4s` version 0.2.1 and opentelemetry version 1.27.0 including `opentelemetry-extension-trace-propagators`

**Environment**
Compiler: scalac with sbt 1.4.7 (Eclipse Adoptium Java 11.0.13)
OS: MacOS Ventura

**Additional context**
the B3 Multi schema definition talks about this issue here: https://github.com/openzipkin/b3-propagation#multiple-headers

**Comment by breedx-splk** [comment]
I think the spec covers this [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#textmap-extract). Regarding "TextMap Extract"

```
The Get function is responsible for handling case sensitivity. If the getter is intended to work with a HTTP request object, the getter MUST be case insensitive.
```

Weirdly, I couldn't easily find our implementation of `TextMapGetter` to cross reference.

**Comment by mateuszrzeszutek** [comment]
What HTTP library are you using @esecules ? The `TextMapGetter` is usually implemented by the HTTP instrumentation; it might be the instrumentation that does not handle case correctly.

**Comment by esecules** [comment]
I've been using http4s (scala). I did not know that it was supposed to be implemented by the http library. I will check there later today.
