### ISSUE TITLE
How to suppress specific agent instrumentation using SPI?

### ISSUE THREAD

**Issue by Anyuoo** [open-telemetry/opentelemetry-java#5649]
Could you please advise me on how to proceed if I want to use the provided SPI extension to suppress specific agent instrumentation, rather than configuring it through files or environment variables?

**Comment by breedx-splk** [comment]
I think you can use the `AutoConfigurationCustomizerProvider`.  We have an example of that [here](https://github.com/signalfx/splunk-otel-java/blob/main/custom/src/main/java/com/splunk/opentelemetry/SplunkConfiguration.java#L71), where we _enable_ some instrumentation out-of-the-box. Let us know if that gets you unblocked. 👍🏻

**Comment by breedx-splk** [comment]
Also, I'm just now noticing that this issue was logged against the core repo and probably should have been logged against the java instrumentation repo. Maybe @trask or @jack-berg or @jkwatson can move it.

**Comment by Anyuoo** [comment]
@breedx-splk Thank you so much, your response was extremely helpful.

**Comment by breedx-splk** [comment]
Great to hear! @Anyuoo please close the issue if you think it's resolved. 🥂
