### ISSUE TITLE
Failed to export metrics with error message "data dropped due to high memory usage"

### ISSUE THREAD

**Issue by onfla11** [open-telemetry/opentelemetry-java#5663]
Failed to export metrics with error message "data dropped due to high memory usage"

**Steps to reproduce**
Micronaut java jdk17 based service, gradle dependencies are as below:
```
 api "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure"
 api ('io.opentelemetry:opentelemetry-exporter-otlp') 
```
Configured metrics exporters and used simple custom metric with `LongCounter`, code snippet.
```
AutoConfiguredOpenTelemetrySdk sdk = AutoConfiguredOpenTelemetrySdk.builder().build();
sdk.getOpenTelemetrySdk().getMeter("TestMetric");
```
Environment Variable set is:
`OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://servicename.namespace.svc.cluster.local:4317`

**What did you expect to see?**
My expectation is periodically Prometheus should scrape the metrics and I should be able to query the prometheus metrics.

**What did you see instead?**
I see metrics get reported to Prometheus. However, initial 1-2 mins, I see following errors in my service.
```
Jul 21, 2023 11:27:14 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with gRPC status code 2. Error message: data dropped due to high memory usage
```

**What version are you using?**
opentelemetry sdk version 1.19.0

**Environment**
Compiler: zulu17.42.20-sa-jre17.0.7-linux_musl_x64
OS: Alpine Linux v3.18 (Dockerimage)

**Additional context**
Same error can be reproduced on Mac Os, JDK 17.
So, error is caused due to low memory cpu of docker-image/pod possibility can be eliminated.
Also, number of metrics generated/scrapped are less than 10. One of the metric has 5 attributes, registered 3 metrics.

**Comment by jack-berg** [comment]
This error message is referring to the memory usage of the OTLP server you're exporting metric data to, i.e. the server at this location: `http://servicename.namespace.svc.cluster.local:4317`. 

Not sure of your configuration, but if that server is a collector, I do believe the collector will return error messages like this when near its memory limit.

**Comment by onfla11** [comment]
@jack-berg Thanks for the quick response. 

So, most likely there is no issue with the application from which I am scrapping the metrics. We currently have many micro services from which data is being reported to the collector. i.e. http://servicename.namespace.svc.cluster.local:4317

Yes we're using open-telemetry collector as server. How should I check if there is indeed an issue with memory limit of the server? any parameters to check? pod memory or any Prometheus query? Most of the services are using golang based sdk. My service is first one, to use java sdk and that's when we are seeing the error is reported multiple time as warning message. 

Wondering, if there is any way to disable these warning messages?

**Comment by jack-berg** [comment]
I'm not an expert at the collector so don't have good intuition on which component produces that exact error message, but maybe take a look at the settings [memory limiter processor](https://github.com/open-telemetry/opentelemetry-collector/tree/3089ea878eef022913a053600f3599b3fddffb95/processor/memorylimiterprocessor) or the sending queue size settings for [exporter helper](https://github.com/open-telemetry/opentelemetry-collector/tree/3089ea878eef022913a053600f3599b3fddffb95/exporter/exporterhelper), which contains common configuration for many exporters. You'll need to ask the folks in `opentelemetry-collector` for further advice on that front.

In terms of disabling warning messages, the SDK logs using JUL, so you'd have to configure JUL to have a higher severity threshold for the logger you want to suppress.

**Comment by trask** [comment]
hi @onfla11, some of these related issue may help: https://github.com/search?q=org%3Aopen-telemetry+%22data+dropped+due+to+high+memory+usage%22&type=issues

**Comment by onfla11** [comment]
Thanks @jack-berg @trask I will go through the links shared and check with the `opentelemetry-collector` team.
