### ISSUE TITLE
Log messages from OpenTelemetry Exporter use JUL instead of SLF4J

### ISSUE THREAD

**Issue by sergeykad** [open-telemetry/opentelemetry-java#5715]
**Describe the bug**
At least some of the classes in `io.opentelemetry.exporter` use [JUL](https://docs.oracle.com/javase/8/docs/api/java/util/logging/package-summary.html) logger instead of SLF4J despite https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1328 

**Steps to reproduce**
Check sources of the `io.opentelemetry.exporter.internal.grpc.GrpcExporterUtil` class for example.

**What did you expect to see?**
I expected it to use SLF4J which can easily be redirected to a logger that my application already uses

**What did you see instead?**
I see that JUL is used, which requires an adapter and extra configuration to use with a different logger.

**What version are you using?**
1.29.0

**Environment**
Compiler: Temurin 17.0.7
OS: Ubuntu 22.04

**Additional context**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1447

**Comment by mateuszrzeszutek** [comment]
> Maybe it will make sense to move this configuration setting into a common configuration section?

That is unfortunately impossible, this feature depends on the javaagent's internal machinery, and requires bytecode instrumentation.

**Comment by sergeykad** [comment]
This is strange since I started getting messages through logger instead of `stdout` after adding `otel.javaagent.logging=application` and I do not use the Java agent.

**Comment by trask** [comment]
it seems something else may be going on in your setup, is it possible for you to reduce this to a small standalone repro in order to better understand what's going on?

**Comment by andrebrait** [comment]
If you happen to have a JUL-to-slf4j or JUL-to-whatever-logging-framework-you-use in your classpath, you'll see the log messages there, but I can confirm the code still uses JUL. I had to use JUL to get a reference to the logger in HttpSender in order to add filters, for example.

**Comment by andrebrait** [comment]
@sergeykad was something that fixed this merged just now?

**Comment by sergeykad** [comment]
No, but @mateuszrzeszutek this behavior is by design, unless I misunderstood him.

**Comment by trask** [comment]
@andrebrait are you facing a related issue?

**Comment by andrebrait** [comment]
> @andrebrait are you facing a related issue?

@trask not a related *issue* but right now it's one of the few things I need to touch JUL for. But it's not specific to OTEL itself.

My application treats any logged SEVERE lines during startup as a deployment failure (don't ask, legacy stuff) and HttpSender logs that when it fails to export a Span. 

Having to use JUL to touch that specific log filter is not a problem per se, but the fact it's an internal class is.

**Comment by trask** [comment]
> My application treats any logged SEVERE lines during startup as a deployment failure (don't ask, legacy stuff) and HttpSender logs that when it fails to export a Span.
>
> Having to use JUL to touch that specific log filter is not a problem per se, but the fact it's an internal class is.

@jack-berg what do you think of reducing failed exports from SEVERE to WARNING, under the assumption that networks and endpoints can be flaky?

**Comment by jack-berg** [comment]
Seems reasonable to me.

**Comment by trask** [comment]
@andrebrait if this would help, go ahead and open an issue and/or PR, thx!
