### ISSUE TITLE
[security] audit repository tooling

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-java#5745]
The security SIG is looking to ensure that security tooling is setup consistently across the organization. As a result, we're asking maintainers to ensure the following tools are enabled in each repository:

- [ ] CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml)
- [ ] Static code analysis tool (the collector uses govulncheck [https://pkg.go.dev/golang.org/x/vuln] on every build)
- [ ] Repository security settings
    - [ ] Security Policy ✅
    - [ ] Security advisories ✅
    - [ ] Private vulnerability reporting ✅
    - [ ] Dependabot alerts ✅
    - [ ] Code scanning alerts ✅

Parent issue: https://github.com/open-telemetry/sig-security/issues/12

**Comment by jack-berg** [comment]
I've went ahead and checked all the boxes and closed the issue. Feel free to re-open if my answers warrant further discussion.

Some notes on each item:

- [ ] CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml) - Yes, see runs [here](https://github.com/open-telemetry/opentelemetry-java/actions/workflows/codeql-daily.yml).
- [ ] Static code analysis tool (the collector uses govulncheck [https://pkg.go.dev/golang.org/x/vuln] on every build). Yes, we use [OWASP dependency check gradle plugin](http://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html). See runs [here](https://github.com/open-telemetry/opentelemetry-java/actions/workflows/owasp-dependency-check-daily.yml). We also run [error prone](https://errorprone.info/) as a part pf every build.
- [ ] Repository security settings
    - [ ] Security Policy ✅ - We inherit the general security policy. See [opentelemetry-java/security/policy](https://github.com/open-telemetry/opentelemetry-java/security/policy).
    - [ ] Security advisories ✅ - Enabled.
    - [ ] Private vulnerability reporting ✅ - Enabled.
    - [ ] Dependabot alerts ✅ - Dependabot alerts are set up, but we use renovate for automatically updating versions.
    - [ ] Code scanning alerts ✅ - Enabled.
