### ISSUE TITLE
TraceId and SpanId base64 encoded on top of hex encoding?

### ISSUE THREAD

**Issue by angela278** [open-telemetry/opentelemetry-java#5785]
When receiving messages at `/v1/traces` I noticed that traceId and spanId are coming in as base64 encoded values in the JSON object. These are decoded in `parseBytes(JsonElement json)` in com.google.protobuf.util.JsonFormat.java when being transformed into ExportTraceServiceRequest, which returns the hex-encoded string that then we decode in our own code.

However I was wondering if this base64 encoding was expected, as it differs from the specification [here](https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#json-protobuf-encoding) which states "The traceId and spanId byte arrays are represented as case-insensitive hex-encoded strings; they are not base64-encoded as is defined in the standard Protobuf JSON Mapping."

This is a message sent using the OpenTelemetry Java SDK:
`{
	"resourceSpans": [{
		"resource": {
			"attributes": [{
					"key": "telemetry.sdk.language",
					"value": {
						"stringValue": "java"
					}
				},
				{
					"key": "telemetry.sdk.name",
					"value": {
						"stringValue": "opentelemetry"
					}
				},
				{
					"key": "telemetry.sdk.version",
					"value": {
						"stringValue": "1.16.0"
					}
				}
			]
		},
		"scopeSpans": [{
			"scope": {
				"name": "io.opentelemetry.spring-webmvc-3.1",
				"version": "1.16.0-alpha"
			},
			"spans": [{
				"traceId": "esUixH6XspwnHT8vyIO2cA==",
				"spanId": "4PfM081AnbI=",
				"name": "HTTP GET",
				"kind": "SPAN_KIND_SERVER",
				"startTimeUnixNano": "1693492024940223000",
				"endTimeUnixNano": "1693492024987787292",
				"attributes": [{
					"key": "http.status_code",
					"value": {
						"intValue": "200"
					}
				}],
				"events": [{
					"timeUnixNano": "1693492024956196542",
					"name": "annotated instrumentation",
					"attributes": [{
						"key": "message",
						"value": {
							"stringValue": "Fetching greeting for Angela"
						}
					}]
				}],
				"status": {}
			}]
		}, {
			"scope": {
				"name": "io.opentelemetry.spring-boot-autoconfigure"
			},
			"spans": [{
				"traceId": "esUixH6XspwnHT8vyIO2cA==",
				"spanId": "+oTvw4n2cZk=",
				"parentSpanId": "4PfM081AnbI=",
				"name": "sayHello @WithSpan",
				"kind": "SPAN_KIND_INTERNAL",
				"startTimeUnixNano": "1693492024965735625",
				"endTimeUnixNano": "1693492024978630792",
				"events": [{
					"timeUnixNano": "1693492024977674208",
					"name": "Trying to fetch custom message for Angela"
				}],
				"status": {}
			}]
		}]
	}]
}`

**Comment by tigrannajaryan** [comment]
@angela278 please add more details to help reproduce this bug.

**Comment by tigrannajaryan** [comment]
@open-telemetry/java-maintainers FYI.

**Comment by jack-berg** [comment]
The java SDK does not support OTLP json encoding. Not sure where that message is coming from.

**Comment by jack-berg** [comment]
As for the binary encoding, we have integration tests that send spans round trip (java sdk -> otel collector -> java OTLP receiver) and validate that the ids are not mangled: https://github.com/open-telemetry/opentelemetry-java/blob/14f16b002ec30f215e8f331b423cc1d452deef5b/integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java#L314-L315

**Comment by angela278** [comment]
Sorry about the delay. We were actually writing our own HTTPSpanExporter for testing purposes so I'm not sure if this actually comes out of the Java SDK. But this is the code that created the message above. 

```
private final RestTemplate restTemplate =
      new RestTemplate(
          List.of(
              new ProtobufJsonFormatHttpMessageConverter(), new ProtobufHttpMessageConverter()));

  @Override
  public CompletableResultCode export(Collection<SpanData> spans) {
    List<ResourceSpans> resourceSpans =
        Arrays.stream(ResourceSpansMarshaler.create(spans))
            .map(
                marshaler -> {
                  ByteArrayOutputStream bos = new ByteArrayOutputStream();
                  try {
                    marshaler.writeBinaryTo(bos);
                    return ResourceSpans.parseFrom(bos.toByteArray());
                  } catch (IOException e) {
                    throw new UncheckedIOException(e);
                  }
                })
            .collect(Collectors.toList());
    ExportTraceServiceRequest exportTraceServiceRequest =
        ExportTraceServiceRequest.newBuilder().addAllResourceSpans(resourceSpans).build();

    final CompletableResultCode result = new CompletableResultCode();

    HttpHeaders headers = new HttpHeaders();
    headers.add("Content-Type", MediaType.APPLICATION_JSON_VALUE);

    try {
      ResponseEntity<ExportTraceServiceResponse> response =
          restTemplate.postForEntity(
              "http://localhost:8443/v1/traces/",
              new HttpEntity<>(exportTraceServiceRequest, headers),
              ExportTraceServiceResponse.class);

      LOG.info("Span publish response {}", response);

      return result.succeed();

    } catch (Exception ex) {
      LOG.error("Failed to publish spans", ex);
    }

    return result.fail();
  }
```

**Comment by breedx-splk** [comment]
This is almost certainly a symptom of something in the marshalling/demarshalling process that you've implemented. 

The core handling of traceId and spanId within SpanData has been stable for for a long time now, and in-place base64 encoded content would be a clear violation of the specification.

**Comment by laurit** [comment]
In protobuf trace and span id type is `bytes` which in java corresponds to a byte array. As this can contain binary data that is not an utf-8 string it can not be directly represented in json. See https://github.com/protocolbuffers/protobuf/blob/6703802f2043e78d4f2eb6cc54e255af1b55b5c7/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1214-L1218 for how it is converted to json.
