### ISSUE TITLE
Add context overload to synchronous gauge API

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#5795]
The synchronous gauge API currently does not allow you to set context, which contrasts with the other synchronous instrument APIs.

Are there use cases for synchronous gauge in which context is present?

_Originally posted by @jsuereth in https://github.com/open-telemetry/opentelemetry-java/pull/5506#discussion_r1310891533_

**Comment by breedx-splk** [comment]
s/contrast/context/ in the first sentence. Just had me a little confused. 🙃
