### ISSUE TITLE
How to Configure Proxy when using otlp exporter with Otel to send traces to New Relic

### ISSUE THREAD

**Issue by kulkarniparth** [open-telemetry/opentelemetry-java#5844]
Hi,

We are configuring our java microservice with otel exporter to send traces to New Relic on endpoint - https://otlp.eu01.nr-data.net:4317/

We are passing our license key too along with the request. But the request is getting timed out, looks like a proxy issue. Can you pls guide, any syntax to set proxy host and port config in application.properties.
 
Currently, trying with the following config but looks its incorrect syntax:

spring.sleuth.otel.exporter.otlp.headers.proxy-host=userproxy.intranet.db.com
spring.sleuth.otel.exporter.otlp.headers.proxy-port=8080

**Comment by jkwatson** [comment]
Based on your properties, it looks like this is a spring-sleuth issue, rather than an issue with the core OTel libraries?
