### ISSUE TITLE
B3PropagatorInjectorMultipleHeaders doesn't inject baggage as headers

### ISSUE THREAD

**Issue by AshokVardhanM** [open-telemetry/opentelemetry-java#5853]
**Describe the bug**
B3PropagatorInjectorMultipleHeaders doesn't inject baggage as headers, it only injects traceId, spanId, sampled and flags.

**Steps to reproduce**
In the tracing configuration, use "b3" as  value for parameter "propagation" and inject baggage on the span. while propagating we observed that baggage is not being injected.

**What did you expect to see?**
B3PropagatorInjectorMultipleHeaders should also set baggage along with traceId, spanId, sampled and flags like B3TextMapCodec from io.jaegertracing.

**What did you see instead?**
B3PropagatorInjectorMultipleHeaders doesn't inject baggage as headers, it only injects traceId, spanId, sampled and flags.

**What version and what artifacts are you using?**
Artifacts: opentelemetry-extension-trace-propagators
Version: 1.22
How did you reference these artifacts? pom.xml via io.helidon.tracing:helidon-tracing-opentelemetry

**Environment**
Compiler: (e.g., "Temurin 17.0.7")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-java/issues/3661 and https://github.com/open-telemetry/opentelemetry-java-contrib/issues/101 and the linked issues. b3 as specified in https://github.com/openzipkin/b3-propagation does not define baggage propagation also see https://github.com/openzipkin/b3-propagation/issues/22

**Comment by AshokVardhanM** [comment]
we have updated our propagation configuration with "B3,W3C"  to get baggage propagation.
hence closing this issue.
