### ISSUE TITLE
JaegerGrpcSpanExporterBuilder fails with exception : problem accessing trust store

### ISSUE THREAD

**Issue by AshokVardhanM** [open-telemetry/opentelemetry-java#5854]
**Describe the bug**
Even though application is not providing properties ("client-cert-pem" and "trusted-cert-pem") in tracing configuration (but there was a system property set like -> **System.setProperty("javax.net.ssl.trustStore", "/etc/faaas/wallet/cwallet.sso");** )   , JaegerGrpcSpanExporterBuilder's build method fails with exception as below.
**problem accessing trust store [java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73), java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:282), okhttp3.internal.platform.Platform.platformTrustManager(Platform.kt:80), okhttp3.OkHttpClient.<init>(OkHttpClient.kt:237), okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069), io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder.build(GrpcExporterBuilder.java:180), io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.build(JaegerGrpcSpanExporterBuilder.java:140), com.oracle.tools.trace.helidon.TraceServerTracerBuilder.getOpenTracingTracer(TraceServerTracerBuilder.java:727), com.oracle.tools.trace.helidon.TraceServerTracerBuilder.wrapTracer(TraceServerTracerBuilder.java:703),**

**Steps to reproduce**
In any standalone application, please add a system variable like **System.setProperty("javax.net.ssl.trustStore", "/etc/faaas/wallet/cwallet.sso");** and don't add any tracing configuration parameters like "client-cert-pem" and "trusted-cert-pem" .
Build tracer using TracerBuilder or inject Tracer (MP), and then observe the exception with JaegerGrpcSpanExporterBuilder's

**What did you expect to see?**
when tracing configuration parameters like "client-cert-pem" and "trusted-cert-pem" are not set on any application, JaegerGrpcSpanExporterBuilder's build method shouldn't fail with exception problem accessing trust store.

**What did you see instead?**
please look at the description section.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-exporter-jaeger`
Version: 1.22.0
How did you reference these artifacts? 
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-jaeger</artifactId>
    </dependency>

**Environment**
Compiler: (e.g., "Temurin 17.0.7")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by laurit** [comment]
Firstly it would be nice to also add the caused by from the exception so we could see why this really failed. Secondly to me this looks more like a misconfiguration on your part rather than an actual issue. The trust store that you have configured seems to be unusable, have you considered either removing the trust store or fixing whatever prevents java from using it?
The simplest way to reproduce is with
```java
System.setProperty("javax.net.ssl.trustStore", "/tmp/a");
TrustManagerFactory factory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
factory.init((KeyStore) null);
```
It works as long as `/tmp/a` doesn't exist, fails when it is an empty file.

**Comment by AshokVardhanM** [comment]
After some code changes in application code related to environment variables that point to ssl security, this problem is resolved. I can close this issue as not a problem now. 
In my opinion, ssl security should have triggered (from tracing/opentelemetry) only if user provide security related configuration but even when not submitted it tried to execute security related protocols and failed the application.
