### ISSUE TITLE
Implement "Named Meters"

### ISSUE THREAD

**Issue by z1c0** [open-telemetry/opentelemetry-java#588]
The "Named Tracers and Meters" RFC (https://github.com/open-telemetry/oteps/blob/master/text/0016-named-tracers.md) has been approved and was added to the specification (open-telemetry/opentelemetry-specification#264).

OpenTelemetry language repositories now need to implement this mechanisms.

Please make sure to also update the documentation if necessary (tracer, meter creation).

This issue is specifically for the implementation of "Named Meters".

Named Tracers are already worked on in https://github.com/open-telemetry/opentelemetry-java/issues/573.

**Comment by ptravers** [comment]
@z1c0 Would this be a reasonable first contribution? If so I would like to pick up this issue.

**Comment by z1c0** [comment]
@ptravers Sure, that would be really helpful!
AFAIK this would be the first implementation of "Named Meters" - so if have questions or input on the specification, please bring those up.

**Comment by ptravers** [comment]
Awesome cheers!
