### ISSUE TITLE
W3CBaggagePropagator wipe baggage from other propagators

### ISSUE THREAD

**Issue by ddark008** [open-telemetry/opentelemetry-java#5883]
### Describe the bug

I am currently working on developing custom propagators that parse baggage from specific headers.
However, when trying to use these custom propagators alongside the W3CBaggagePropagator, I encounter an unexpected behavior.
It seems that the W3CBaggagePropagator [creates a new BaggageBuilder](https://github.com/open-telemetry/opentelemetry-java/blob/5ccc7fccb3fd0bdfa902bfea7bcee43384cdcf3e/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java#L106) and discards the current context Baggage, preventing my custom propagators from functioning properly.

Best solution use exist baggage:
```java
Baggage baggage = Baggage.fromContext(context);
```

### Steps to reproduce

```java
import java.util.List;

import javax.annotation.Nullable;

import io.opentelemetry.api.baggage.Baggage;
import io.opentelemetry.api.baggage.BaggageBuilder;
import io.opentelemetry.api.internal.StringUtils;
import io.opentelemetry.context.Context;
import io.opentelemetry.context.propagation.TextMapGetter;
import io.opentelemetry.context.propagation.TextMapPropagator;
import io.opentelemetry.context.propagation.TextMapSetter;

public class XReqIdPropagator implements TextMapPropagator {
    public static final String X_REQUEST_ID_HEADER = "X-Request-Id";

    @Override
    public List<String> fields() {
        return List.of(X_REQUEST_ID_HEADER);
    }

    @Override
    public <C> void inject(Context context, @Nullable C carrier, TextMapSetter<C> setter) {
        Baggage baggage = Baggage.fromContext(context);
        String outgoingReqId = baggage.getEntryValue("req-id-key");
        if (!StringUtils.isNullOrEmpty(outgoingReqId)) {
            setter.set(carrier, X_REQUEST_ID_HEADER, outgoingReqId);
        }
    }

    @Override
    public <C> Context extract(Context context, @Nullable C carrier, TextMapGetter<C> getter) {
        String incomingReqId = getter.get(carrier, X_REQUEST_ID_HEADER);
        if (!StringUtils.isNullOrEmpty(incomingReqId)) {
           // Use exist Baggage
            Baggage baggage = Baggage.fromContext(context);
            BaggageBuilder builder = baggage.toBuilder();
            builder.put("req-id-key", incomingReqId);
            return context.with(builder.build());
        }
        return context;
    }
}
```
```java
import com.google.auto.service.AutoService;
import io.opentelemetry.context.propagation.TextMapPropagator;
import io.opentelemetry.sdk.autoconfigure.spi.ConfigProperties;
import io.opentelemetry.sdk.autoconfigure.spi.ConfigurablePropagatorProvider;

@AutoService(ConfigurablePropagatorProvider.class)
public class XReqIdPropagatorProvider implements ConfigurablePropagatorProvider {
    @Override
    public TextMapPropagator getPropagator(ConfigProperties config) {
        return new XReqIdPropagator();
    }

    @Override
    public String getName() {
        return "xreqid";
    }
}
```

Add  to config `otel.propagators = tracecontext,baggage,xreqid`

### Expected behavior

Context contain baggage from all propagators

### Actual behavior

Context contain baggage only from W3CBaggagePropagator

### Javaagent or library instrumentation version

1.29.0

### Environment

**JDK**: 17
**OS**: Ubuntu

**Comment by jack-berg** [comment]
@ddark008 can't you get the behavior you intend by ensuring that your custom `xreqid` propagator runs after `W3CBaggagePropagator`?

**Comment by ddark008** [comment]
@jack-berg Thank you for your answer!
That will be sufficient. The propagators are runining according to the in the property `otel.propogators` ?

**Comment by jack-berg** [comment]
@ddark008 yup you can see the source code that interprets `otel.propagators` [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/PropagatorConfiguration.java). We read in the property, translate each to the corresponding `TextMapPropagator`, and call `TextMapPropagator.composite(..)` with the resulting collection, which ultimately returns [MultiTextMapPropagator](https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/propagation/MultiTextMapPropagator.java. `MultiTextMapPropagator` will iterate through the propagators in order and [apply each to the resulting context](https://github.com/open-telemetry/opentelemetry-java/blob/1453f3f1814a56c2719a089b4c96cb173f486e22/context/src/main/java/io/opentelemetry/context/propagation/MultiTextMapPropagator.java#L64-L66).

So setting `otel.propagators=baggage,xreqid` should result in `xreqid` running after W3CBaggagePropagator, and achieve the behavior you want.

**Comment by breedx-splk** [comment]
@ddark008 please close if this has been satisfied. Thanks! 🙏🏻
