### ISSUE TITLE
Discuss versioning strategy for core, instrumentation, contrib ahead of otel java agent 2.0

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#5885]
The `opentelemetry-java-instrumentation` repo is [planning on bumping to major version 2.0](https://github.com/orgs/open-telemetry/projects/54) to accommodate a large number breaking changes to the HTTP and JVM semantic conventions.

For some time (maybe since 1.0.0?) `opentelemetry-java`, `opentelemetry-java-instrumentation`, and `opentelemetry-java-contrib` have all been versioned in lockstep with each other:
- Each month, we bump the minor version and release all components of all repos, regardless of whether or not they have changes
- The exception to the version symmetry is patch versions. I.e. if `opentelemetry-java` releases a patch (i.e. 1.30.1), `opentelemetry-java-instrumentation` does not follow suit. And vice versa for patches from instrumentation and contrib.

This strategy has been very useful for consumers. For many versioning issues that may have been complicated to resolve, the advice of "make sure your versions are aligned" has worked. Some folks aren't even aware of that version differences in patches can arise, and depend on a single "otel java" version across all dependencies.

If / when `opentelemetry-java-instrumentation` releases a new major version, the dependency situation gets muddy for users. The fact that `opentelemetry-java-instrumentation` and `opentelemetry-java` release / recommend BOMs somewhat salvages the situation. But what about `opentelemetry-java-contrib`? @trask raises the [question](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1059/files#r1343268926) of whether it should bump to 2.0 as well since at least some of its components are impacted by the breaking changes to the semantic conventions.

But bumping to a major version is not without downside: it sends a signal to users that they should be much more cautious with an upgrade, and they may be reluctant of the upgrade for fear of breaking changes. If only 1 component in contrib is impacted by the breaking changes to the semantic conventions, should all components be burdened with to bump their major version? If not, how should we handle contrib releases from a tooling perspective once the versions of components diverge? Bumping the version of all components, whether or not they had any updates, is a convenient simplifying assumption. Allowing versions to diverge within the contrib repository will complicate releases and add confusion for users.

This issue is to discuss various options and tradeoffs and work towards decision on how we want to version going forward.

**Comment by jack-berg** [comment]
Some thoughts:
- Its probably not possible to continue versioning all otel java repos in lockstep. Some components will need to bump major versions, for the core repo is especially important that we send a signal that we're committed to backwards compatibility, and we should probably take a major version bump off the table. Even if the major version bump didn't introduce breaking changes, its still probably not a good idea at this stage in the project.
- Within the core repo, versioning all the components in lockstep has been beneficial and I think we should continue. I don't feel like any particular component would need a major version bump such that it would need to break version lockstep or drag all the other components with it. 
- I think the same thing is true in opentelemetry-java-instrumentation. The value of keeping all instrumentation in lockstep seems to outweigh any downsides. 
- Breaking opentelemetry-java and opentelemetry-java-instrumentation versioning symmetry will start to create issues where users use instrumentation version ahead of SDK version, and are forced to bump SDK to use new features of the API / SDK that instrumentation relies on. We should probably explicitly list the version of `opentelemetry-java` that each version of `opentelemetry-java-instrumentation` depends on. I know its in the instrumentation BOM, but it also probably belongs in the release notes or somewhere else humans read.
- Letting contrib components version independently of core, instrumentation, and even of other components in contrib seems like a tooling challenge I don't want to solve right now. I'm in favor of keeping contrib components in lockstep with each other if we can.
- Breaking opentelemetry-java and opentelemetry-java-instrumentation versioning symmetry does open the door for opentelemetry-java adjusting its release schedule. The pace of work has slowed down and we might consider moving to releases every other month instead.

**Comment by jkwatson** [comment]
> Its probably not possible to continue versioning all otel java repos in lockstep. Some components will need to bump major versions, for the core repo is especially important that we send a signal that we're committed to backwards compatibility, and we should probably take a major version bump off the table. Even if the major version bump didn't introduce breaking changes, its still probably not a good idea at this stage in the project.

💯

**Comment by trask** [comment]
I think we're aligned now, all 3 repos will be versioned independently going forward

**Comment by breedx-splk** [comment]
Yup, I think we have this sorted. Reopen if I'm mistaken or there's more to add.

**Comment by jack-berg** [comment]
One additional piece of info is that we discussed that contrib components don't necessarily need to be versioned in lockstep with each other. If one is stable and needs to make breaking changes, that component should be able to bump to 2.x without dragging the others with it. Long term, contrib should probably evolve to a bunch of independently versioned components, which share tooling to perform monthly minor releases with each other.
