### ISSUE TITLE
Names of resource env variables may be revisited

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-java#59]
This may need to be re-visited: 

https://github.com/bogdandrutu/openconsensus/blob/8535aabedcb0b5759047cdb2be2da285e9ca9279/api/src/main/java/openconsensus/resource/Resource.java#L44-L45

**Comment by SergeyKanzhelev** [comment]
Perhaps make those names non-prefixed. Just `Resource_type` and `Resource_labels`?

**Comment by tedsuo** [comment]
DOCS: https://github.com/census-instrumentation/opencensus-specs/tree/master/resource

TODO: Once we pick a new name, we need to update these ENV vars.

**Comment by bogdandrutu** [comment]
Are we good with OTEL_RESOURCE_LABELS?

**Comment by SergeyKanzhelev** [comment]
I'd suggest `TELEMETRY_RESOURCE_LABELS`. Drop Open, make it readable with the full word `telemetry`
