### ISSUE TITLE
Should `opentelemetry-extension-kotlin` have a lower `languageVersion`?

### ISSUE THREAD

**Issue by felixscheinost** [open-telemetry/opentelemetry-java#5903]
**Is your feature request related to a problem? Please describe.**

One of our Spring Boot applications is still on Spring Boot 2.7.x and therefore on Kotlin 1.6.21.

`opentelemetry-extension-kotlin` is currently compiled against a very new version of Kotlin (1.9.10) (it seems it gets updated by Renovate).

By doing so people stuck on older Kotlin versions are prevented from upgrading to newer version of OTel libraries.

**Describe the solution you'd like**

I think you could set a lower `languageVersion`, so a newer Kotlin compiler could generate a `.kotlin_module` which is backwards-compatbile with older Kotlin versions.

**Describe alternatives you've considered**

My current workaround is to use newer versions of `io.opentelemetry:opentelemetry-sdk` and `io.opentelemetry.javaagent:opentelemetry-javaagent`,
but to keep `opentelemetry-extension-kotlin` pinned to `1.24.0`, which was the latest version which supports Kotlin 1.6.21.

Another alternative could be to use a newer Kotlin version than 1.6.21 myself but I don't know which consequences that would have.

**Comment by jack-berg** [comment]
Closing this in #5983 was premature as #5910 still needs to reflect the decision to use kotlin 1.6.
