### ISSUE TITLE
there is not way to reset context (for a given thread)

### ISSUE THREAD

**Issue by kares** [open-telemetry/opentelemetry-java#5904]
**Is your feature request related to a problem? Please describe.**

In cases where threads are re-used e.g. using an executor, OTEL's `Context.current()` would need to be cleared.

**Describe the solution you'd like**

Not sure what the impl details would be but some kind of `ContextStorage#reset` mechanism would be useful.

**Describe alternatives you've considered**

The only alternative for the thread-pooling case I found was to unreflect the [internal `THREAD_LOCAL_STORAGE` thread-local](https://github.com/open-telemetry/opentelemetry-java/blob/v1.31.0/context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java#L17) and do a `THREAD_LOCAL_STORAGE.remove()` to cleanup state from the previous run.

**Additional context**

Please, let me know if I missed a feature how potential thread re-use could reset the context. :bow:

**Comment by laurit** [comment]
The best solution to this is to properly close all the scopes and not leak the context. Have you considered doing this?

**Comment by kares** [comment]
Yep, did and indeed all span scopes end up closed. 

What is left is the baggage, for which it is really hard to come up with a scope that would close in the place where baggage items are added. I kind of assumed this is common use-case e.g. at a point where your user authenticates it's hard to scope the baggage, basically would need to store that scope in a thread-local a close from a completely different place (which seemed more of an anti-pattern in terms of OTEL).

**Comment by trask** [comment]
maybe `Context.root().makeCurrent()`?

**Comment by kares** [comment]
> maybe `Context.root().makeCurrent()`?

yep, that's what I stumbled upon but initially rejected as not "being the same as cleaning up the thread-local" (in a new thread).
effectively and practically it achieves the very same thing, still wanted to see whether exposing some kind of 'intentional' (explicit) cleanup mechanism would make sense...

if you feel the current mechanism are sufficient supporting a thread-pooling scenario I am fine with closing the ticket,

**Comment by laurit** [comment]
Context storage is customizable, I believe you can replace it with your own implementation that could allow resetting the thread local storage.
I totally understand that finding suitable instrumentation points can be hard and sometimes instrumentation has to do things in a roundabout fashion. If you need to set authentication details to baggage but the place where you currently do it isn't something like a filter that would allow easy cleanup then consider perhaps you can stash the info you need to something like a request attribute that you could access later in the code where cleanup would be easier and create the baggage there? Or perhaps you could pass the scope returned from making baggage current similarly with a request attribute so you could clean it up when the request completes. Or you could even use the otel context. Add a mutable holder object at the start of the request (for example in a filter) and use that object to store the scope from the baggage and clean it up when the request completes.
