### ISSUE TITLE
Exception with OtlpGrpcSpanExporter and latest grpc

### ISSUE THREAD

**Issue by croudet** [open-telemetry/opentelemetry-java#5907]
**Describe the bug**
Got an exception when trying to build and `OtlpGrpcSpanExporter` not using default okhttp exporter but `opentelemetry-exporter-sender-grpc-managed-channel`

```noformat
Exception in thread "main" java.lang.NullPointerException: channel
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:921)
	at io.grpc.ClientInterceptors.intercept(ClientInterceptors.java:87)
	at io.grpc.ClientInterceptors.intercept(ClientInterceptors.java:74)
	at io.opentelemetry.exporter.sender.grpc.managedchannel.internal.UpstreamGrpcSenderProvider.createSender(UpstreamGrpcSenderProvider.java:59)
	at io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder.build(GrpcExporterBuilder.java:158)
	at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:189)
```

**Steps to reproduce**
```java
public static void main(String... args) {
        OtlpGrpcSpanExporter.builder()
                .setEndpoint("https://collector-service:4317")
                .build();
```

**What did you expect to see?**
No Exception.

**What did you see instead?**
An exception because `channel` is null and `io.grpc.ClientInterceptors.intercept` checks that.

**What version and what artifacts are you using?**
grpc-java: 1.58.0
```xml
<dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-otlp</artifactId>
      <version>1.31.0</version>
      <exclusions>
        <exclusion>
          <groupId>io.opentelemetry</groupId>
          <artifactId>opentelemetry-exporter-sender-okhttp</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.squareup.okhttp3</groupId>
          <artifactId>okhttp</artifactId>
        </exclusion>
      </exclusions>
 </dependency>
 <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-sender-grpc-managed-channel</artifactId>
      <version>1.31.0</version>
 </dependency>
```

**Environment**
Compiler: OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OS: Windows

**Comment by laurit** [comment]
As far as I understand you should supply the channel instead of the endpoint like it is done in https://github.com/open-telemetry/opentelemetry-java/blob/3827ee1e5b9dd34db715a0f1675f59e40382f611/exporters/otlp/all/src/testGrpcNetty/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcNettySpanExporterTest.java#L37 to use the upstream grpc implementation. Did this worke in a previous version?

**Comment by croudet** [comment]
Yes, but `setChannel` is deprecated, I wonder if there was another way to initialize it.

**Comment by jack-berg** [comment]
Yes @laurit is correct.

#4531 describes a use case where `setEndpoint` is insufficient and requests that we do not deprecate `setChannel`. In general, we want to encourage use of the OkHttp exporter and expand the capabilities of it where missing. I'm going to close this in favor of #4531, but it would be helpful if you could describe your use case for using `opentelemetry-exporter-sender-grpc-managed-channel` on that issue.

**Comment by croudet** [comment]
it is just that okhttp brings kotlin dependencies, and in the project I plan to use it, we already have grpc-java.

**Comment by jack-berg** [comment]
If you're on java 11+, consider using `opentelemetry-exporter-sender-jdk`. It only supports `OtlpHttp{Signal}Exporter`s (i.e. the `http/protobuf`) version of the protocol), but uses the built in JDK HttpClient and has zero transitive dependencies.

**Comment by fax4ever** [comment]
@jack-berg is there a way to setChannel using [autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure)? thanks
