### ISSUE TITLE
SpanProcessor called even when isStartRequired / isEndRequired are false

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#5930]
The following test shows a span processor which doesn't require start or end, and despite this, onStart and onEnd are called! Yikes!
```
@Test
void foo() {
    AtomicLong onStartCount = new AtomicLong();
    AtomicLong onEndCount = new AtomicLong();

    SpanProcessor processor = new SpanProcessor() {
        @Override
        public void onStart(Context parentContext, ReadWriteSpan span) {
            onStartCount.incrementAndGet();
        }

        @Override
        public boolean isStartRequired() {
            return false;
        }

        @Override
        public void onEnd(ReadableSpan span) {
            onEndCount.incrementAndGet();
        }

        @Override
        public boolean isEndRequired() {
            return false;
        }
    };

    SdkTracerProvider sdkTracerProvider = SdkTracerProvider.builder()
            .addSpanProcessor(processor)
            .build();

    Tracer tracer = sdkTracerProvider.get("tracer");

    for (int i = 0; i < 100; i++) {
        tracer.spanBuilder("span").startSpan().end();
    }

    assertThat(onStartCount.get()).isEqualTo(0);
    assertThat(onEndCount.get()).isEqualTo(0);
}
```

**Comment by jkwatson** [comment]
Seems like a minor bug...why would you build a span processor that literally didn't want to ever see spans, either on start or on finish/

**Comment by jkwatson** [comment]
> > why would you build a span processor that literally didn't want to ever see spans, either on start or on finish/
> 
> This shows we call onEnd even if only isOnStartRequired=true, and we call onStart even if only isOnEnd=true.

The test case posted above has both set to false. Am I missing something?

**Comment by jack-berg** [comment]
Sorry I mispoke. The example shows isStartRequired=false and isEndRequired=false, and both getting called anyway. But it doesn't actually matter what isStartRequired and isEndRequired are set to. In general, if only on span processor is added, the responses of isStartRequired and isEndRequired are ignored and both onStart and onEnd are always called.

**Comment by jkwatson** [comment]
🤔  has this always been the case? what a weird bug to last this long.

**Comment by jack-berg** [comment]
Not sure, I think probably yes. Oddly, we rely on MultiSpanProcessor to decide whether to call onStart / onEnd. Its [constructor](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/MultiSpanProcessor.java#L82-L94) is the only place in the code base which calls isStartRequired / isEndRequired. So the bug exists because we transform all the registered processors into a single MultiSpanProcessor, except when there's exactly 1 processor because of [this code](https://github.com/open-telemetry/opentelemetry-java/blob/e06d35add577fd702104b5b2836201e76f72d88b/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SpanProcessor.java#L45-L47).

It is definitely a weird bug to have made it this far.
