### ISSUE TITLE
Exported OTLP data being parsed incorrectly (data point labels being parsed as unknown fields)

### ISSUE THREAD

**Issue by hxliu33** [open-telemetry/opentelemetry-java#5945]
I am currently using a Collector with an `otlphttp` exporter to send metrics to a custom backend I am writing in Java, but when I process the request body using `ExportMetricsServiceRequest.parseFrom()` method, it parses data point attributes into the data point's `unknownFields` instead of its `labels_`. Logging the output to stdout shows everything correctly (in the right places, as attributes under each data point). Here is the structure of the parsed request:
![unknown fields](https://github.com/open-telemetry/opentelemetry-collector/assets/26282331/c479971e-078e-4f6f-8d2d-d3c6a038b5c5)

And here is what I am (correctly) getting through the logging exporter:
![logging exporter](https://github.com/open-telemetry/opentelemetry-collector/assets/26282331/c826e8ab-090a-4281-a2f2-6d656efa803f)

Through attaching a debugger, I have pinpointed the issue to the constructor methods of the `IntDataPoint` and `DoubleDataPoint` classes. In the `switch`-`case` statements, the labels are associated with tags of `58` (putting them in the `default` case that moves it to the `unknownFields` attribute) rather than tags of `10` (which would've put them in the correct `labels` attribute).
<img width="899" alt="Screenshot 2023-10-26 at 4 12 26 PM" src="https://github.com/open-telemetry/opentelemetry-proto/assets/26282331/549e7350-fbee-436e-ade4-4a1973cbd38e">

Please let me know if this is not actually a bug, and I am doing something incorrectly.

**Comment by tigrannajaryan** [comment]
@open-telemetry/java-maintainers please take a look.

**Comment by jack-berg** [comment]
@hxliu33 it looks like you may be trying to parse the message with classes generated from an older version of the protos. What version of [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto) is used to generate the `ExportMetricsServiceRequest`?

**Comment by hxliu33** [comment]
> @hxliu33 it looks like you may be trying to parse the message with classes generated from an older version of the protos. What version of [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto) is used to generate the `ExportMetricsServiceRequest`?

@jack-berg The dependency version that I am calling `ExportMetricsServiceRequest.parseFrom()` from is `1.0.0-alpha` (I was using `0.17.0` at first but changed it to `1.0.0-alpha` and continued to see the issue), but I'm using an OTel Collector to send the requests (the collector is scraping the data from a prometheus endpoint and exporting it to both console and my custom endpoint). I'm assuming then that the Collector is generating the `ExportMetricsServiceRequest`, but how can I tell which version of opentelemetry-proto the Collector is using for that? The version of the Collector itself was `0.83.0`.

**Comment by jack-berg** [comment]
I'm seeing indications in your screenshot that you're not using `1.0.0-alpha` - your screenshot shows a field called `instrumentationLibraryMetrics`, but this was renamed to `scopeMetrics` prior to 1.0.0-alpha. Also, the idea of labels on metrics was replaced quite a while ago with attributes. Can you double check that you are using `io.opentelemetry.proto:opentelemetry-proto:1.0.0-alpha` as published from [opentelemetry-proto-java](https://github.com/open-telemetry/opentelemetry-proto-java)? The source code I see in that artifact appears to be different than what you show.

**Comment by hxliu33** [comment]
@jack-berg Ohh interesting, maybe the package never updated to the version I was declaring. I will try ensuring that I am using 1.0.0-alpha (by making sure I see `scopeMetrics`/`attributes` instead of `instrumentationLibraryMetrics` and `labels`) and see if that works, thanks!

**Comment by jack-berg** [comment]
I'm going to close this because there are numerous tests which show this working. Also, parsing OTLP isn't technically part of the scope of this project. 🙂  If you have future issues with `io.opentelemetry.proto:opentelemetry-proto`, please open an issue in [opentelemetry-proto-java](https://github.com/open-telemetry/opentelemetry-proto-java).
