### ISSUE TITLE
Suppressing Zipkin exporter's instrumentations

### ISSUE THREAD

**Issue by LikeTheSalad** [open-telemetry/opentelemetry-java#5967]
Add instrumentation suppressing context key to the exporter. Similar to what was done for OkHttp-related exporters [here](https://github.com/open-telemetry/opentelemetry-java/pull/5918).

**Comment by chungngoops** [comment]
I'm working on this issue.

**Comment by breedx-splk** [comment]
Hi @chungngoops . Any updates?

**Comment by chungngoops** [comment]
@breedx-splk : sorry I didn't have time to continue the work, but back on it now.

**Comment by SylvainJuge** [comment]
The way to suppress Zipkin exporter instrumentation might change a bit if https://github.com/open-telemetry/opentelemetry-java/pull/6546 is merged.

**Comment by chungngoops** [comment]
I created a draft PR #6552, I am struggling with creating test for the new changes, could anyone help me with this.

**Comment by breedx-splk** [comment]
I think this is done. @LikeTheSalad reopen if not the case. Thanks.
