### ISSUE TITLE
Getting top level span from other spans

### ISSUE THREAD

**Issue by zilinjak** [open-telemetry/opentelemetry-java#6019]
Hello,
Our tech stack involves Kotlin, javaagent, Spring, and the Elastic APM stack. 
Within Elastic APM, there exists a powerful feature designed to correlate long latencies or errors based on labels and other metadata, as detailed in their [docs -- Find transaction latency and failure correlations](https://www.elastic.co/guide/en/kibana/current/correlations.html).

Unfortunately, this feature currently aggregates metadata exclusively from the first span. In our scenario, as the javaagent always creates the first 2 spans, we face a limitation where no records can be added to it. 

To enhance our workflow, we are seeking the ability to add more labels to the root span. AFAIK obtaining the top-level span context seems to be unattainable.

**Solution Request:**
Static method that returns the top-level Span object of the current trace.

**Alternatives Considered:**
Method that can be invoked on a Span object to retrieve the parent Span.

**Comment by trask** [comment]
hi @zilinjak!

there are a couple of options in your scenario:
* disable the INTERNAL controller spans (we will likely disable them by default in next month's OTel Java agent 2.0 release: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9787). this will allow you to use `Span.current()` to get the top-level span
* use `opentelemetry-instrumentation-api` and use `LocalRootSpan.current()` to get the top-level span

**Comment by zilinjak** [comment]
Hello,
thanks very much, the `LocalRootSpan.current()` seems to be working perfectly.
