### ISSUE TITLE
Failed to configure ResourceProvider

### ISSUE THREAD

**Issue by liililil** [open-telemetry/opentelemetry-java#6020]
**Describe the bug**
When I configure ResourceProvider, I get the default ResourceProvider.

**Steps to reproduce**
otel.service.name=service-test
otel.resource.attributes=test=111
otel.java.enabled.resource.providers=io.opentelemetry.instrumentation.resources.HostResourceProvider

**What did you expect to see?**
The metrics attributes only provide HostResource.

**What did you see instead?**
Neither the otel.service.name nor the otel.resource-attributes configuration is valid.
The metrics service.name attributes  is unknown_service:java

**What version and what artifacts are you using?**
opentelemetry-javaagent.jar 1.32.0 (opentelemetrySdk 1.32.0)

**Environment**
Java

**Additional context**
https://github.com/open-telemetry/opentelemetry-java/pull/5679
ResourceConfiguration.Class
```
if (!enabledProviders.isEmpty() && !enabledProviders.contains(resourceProvider.getClass().getName())) {
    continue;
}
```
Whether the Class name fails to match? @jack-berg

**Comment by jack-berg** [comment]
HI @liililil - if you use the `otel.java.enabled.resource.providers` option, you're specifying an allow list of resource providers, and any that is not in the list will be omitted. A while back we refactored the code which interprets `otel.service.name` and `otel.resource.attributes` to be contained in a resource provider called [EnvironmentResourceProvider](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/internal/EnvironmentResourceProvider.java). The solution for you is to include `io.opentelemetry.sdk.autoconfigure.internal.EnvironmentResourceProvider` in the value for `otel.java.enabled.resource.providers`. I.e. `otel.java.enabled.resource.providers=io.opentelemetry.instrumentation.resources.HostResourceProvider,io.opentelemetry.sdk.autoconfigure.internal.EnvironmentResourceProvider`.

**Comment by jack-berg** [comment]
Going to close this. Feel free to re-open if there is more to discuss.

**Comment by AntonioLyubchev** [comment]
@jack-berg leaving a comment here to notify you that this hasn't been mentioned here: https://opentelemetry.io/docs/languages/java/configuration/#resourceprovider

**Comment by AntonioLyubchev** [comment]
@jack-berg  opened https://github.com/open-telemetry/opentelemetry-java/issues/6772
