### ISSUE TITLE
Add artifact tags when publishing to maven central

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/opentelemetry-java#6054]
**Is your feature request related to a problem? Please describe.**
Top of [DistributedTracing](https://mvnrepository.com/open-source/distributed-tracing) category on mvnrepository does not include otel
<img width="360" alt="image" src="https://github.com/open-telemetry/opentelemetry-java/assets/2347409/f6191c35-885c-4137-8bbe-3a1ef0405efa">

Top of observability:
<img width="503" alt="image" src="https://github.com/open-telemetry/opentelemetry-java/assets/2347409/62c78cd5-c9da-485c-a461-f87813ece3e2">

Top of metrics:
<img width="493" alt="image" src="https://github.com/open-telemetry/opentelemetry-java/assets/2347409/044ed6b4-2216-4029-87d6-17633627b409">

**Describe the solution you'd like**
OTel artifacts should add tags and participate in these vanity metrics to be a bit more discoverable and avoid any confusion users might have by looking at metrics alone.

**Describe alternatives you've considered**

**Additional context**

**Comment by jack-berg** [comment]
I looked into this and wasn't able to determine how it works. The `io.opentelemetry:opentelemetry-api` artifact [currently has](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-api/1.33.0) tags: `telemetry`, `opentelemetry`, `monitoring`, and `api.

This [stackoverflow](https://stackoverflow.com/questions/42729444/how-can-i-populate-what-is-indexed-under-the-tags-metadata-field-in-maven-centra) post hints that the tags might be generated from certain elements in the `pom.xml`, but several of the tags currently assigned don't show up at all in the [pom](https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-api/1.33.0/opentelemetry-api-1.33.0.pom).

**Comment by lmolkova** [comment]
I believe @trask wrote to info@mvnrepository.com to ask and also according to other offline conversations it seems it's site admin who assigns these categories.

**Comment by jack-berg** [comment]
I'm going to close this issue because it doesn't appear this is something we can control
