### ISSUE TITLE
MIssing latest alpha version in maven repo index

### ISSUE THREAD

**Issue by saez0pub** [open-telemetry/opentelemetry-java#6087]
**Describe the bug**
Renovate uses the maven repo index to validate the release date of versions and does not see the 1.33.0-alpha version.

If I look at several alpha versions:
https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-bom-alpha/
https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-api-events/
https://repo.maven.apache.org/maven2/io/opentelemetry/opentelemetry-exporter-prometheus/

We can see 1.32.0-alpha but not 1.33.0-alpha

the metadata file is OK but not the index.

**What did you expect to see?**
I would like to see 1.33.0-alpha in the page.

**Comment by saez0pub** [comment]
Oh, maybe that's a maven repo problem 🤔 
https://issues.sonatype.org/browse/OSSRH-97465?filter=-8&jql=text%20~%20%22cache%22%20AND%20updated%20%3E%3D%20-1w%20order%20by%20updated%20DESC

**Comment by saez0pub** [comment]
I've sent a mail to info@mvnrepository.com just to check it 🤷

**Comment by saez0pub** [comment]
OK, that's resolved by the jira ticket.

**Comment by jack-berg** [comment]
Thanks for following up on that @saez0pub
