### ISSUE TITLE
Merge opentelemetry-api-events into opentelemetry-extension-incubator

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#6121]
> Writing this made me realize that its silly that we incubate APIs in both `opentelemetry-api-events` and `opentelemetry-extension-incubator`. I propose we merge events into `opentelemetry-extension-incubator`, and do it in lockstep with #6001 to minimize churn.

_Originally posted by @jack-berg in https://github.com/open-telemetry/opentelemetry-java/pull/6120#discussion_r1443197913_

**Comment by trask** [comment]
adding https://github.com/open-telemetry/opentelemetry-java/pull/6120#discussion_r1443348187 here as well:

> maybe `opentelemetry-extension-incubator` -> `opentelemetry-api-incubator`?
>
> since it's not really an incubator for extensions
>
> (also https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation-api-incubator)

**Comment by jack-berg** [comment]
> maybe opentelemetry-extension-incubator -> opentelemetry-api-incubator?

Yeah that makes sense to me.

**Comment by jkwatson** [comment]
seems fine to me
