### ISSUE TITLE
Possibility to configure http proxy on OtlpGrpcMetricExporter side

### ISSUE THREAD

**Issue by alexandru-roman-db** [open-telemetry/opentelemetry-java#6194]
**Is your feature request related to a problem? Please describe.**
Possibility to configure http proxy on OtlpGrpcMetricExporter side

**Describe the solution you'd like**
Similar to the _OtlpGrpcMetricExporter.setEndpoint_ method an additional one would be nice to be added so that the proxy configuration is reaching the _OkHttpGrpcExporter_

**Additional context**
Currently we are using [another library](https://github.com/newrelic/micrometer-registry-newrelic?tab=readme-ov-file#opentelemetry-micrometer-shim) provided by NewRelic but this reached it's end-of-life and their documentation is recommending to use OpenTelemetry instead.

With the suggested usage of the OpenTelemetry library, when the micrometer data is being sent the following error occurs: **java.net.SocketTimeoutException: Connect timed out**

**Comment by jack-berg** [comment]
Hi - I'm a maintainer for this project and also an engineer for new relic. Can you tell me a little bit about your configuration and why supporting forward proxy configuration would resolve your issue?

**Comment by alexandru-roman-db** [comment]
Hi @jack-berg , Thank you for you message. The entire organisation network is configured that all the trafic going to the Internet needs to be forwarded through the proxy (for security reasons) and without having a possibility to configure this on library the traffic to NewRelic is blocked. Personally, I would suggest to have at least the possibility (we as developers) to configure the proxy for such cases.

**Comment by jack-berg** [comment]
Got it. Coincidentally, another issue (#6204) was just filed as well with essentially the same request. My [comment](https://github.com/open-telemetry/opentelemetry-java/issues/6204#issuecomment-1932298603) may be interesting to you:

> we could extend programatic configuration for these options. The trick will be figuring out how proxy config manifests in different http clients (like the jdk httpclient and okhttp clients we use) and exposing some sort of generic representation. I'm open to adding support for this if somebody wants to contribute it.

> In the short term, you might consider exporting to a [collector running the otlphttpexporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter), which does support proxy configuration. The docs don't mention it - support was added recently and the option is sort of a "hidden option" at the moment. See this https://github.com/open-telemetry/opentelemetry-collector/issues/5761 for more details.

The author of that issue mentioned they are working on preparing a PR.
