### ISSUE TITLE
Kotlin API compatibility

### ISSUE THREAD

**Issue by rocketraman** [open-telemetry/opentelemetry-java#6198]
**Is your feature request related to a problem? Please describe.**

The Kotlin extension is compiled against 1.9.x and by default can only be used by Kotlin 1.9 and above.

**Describe the solution you'd like**

Unless the extension is using language features that are only accessible in 1.9.x, the apiVersion and langaugeVersion should be specified in the build, which will allow it to generate code with earlier metadata (recommend 1.6.x) and be usable for users with earlier versions of Kotlin.

See https://kotlinlang.org/docs/maven.html#attributes-specific-to-jvm, specifically languageVersion.

**Comment by jack-berg** [comment]
Our goal (as documented [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/VERSIONING.md#language-version-compatibility)) is to have compatibility with kotlin 1.6 and above. Here's the code where we set the [kotlin version](https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/kotlin/build.gradle.kts#L51).

Can you clarify or provide a reproduction of the problem you're experiencing?

**Comment by rocketraman** [comment]
Ah, I see that `languageVersion` is now set (https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/kotlin/build.gradle.kts#L51) but was not set in 1.31.0 (https://github.com/open-telemetry/opentelemetry-java/blob/release/v1.31.x/extensions/kotlin/build.gradle.kts#L50), which I am currently using.

In that case this is not an issue, thanks.
