### ISSUE TITLE
Add compiled binaries to Assets page for the active version

### ISSUE THREAD

**Issue by bryan-splunk** [open-telemetry/opentelemetry-java#6205]
Some companies, due to security practices, are unable to use Maven to add this project to a larger solution and instead need to be able to download the compiled libraries.  Under the assets page you can download the source but there are no binaries.

As a solution it would be very beneficial to have a compiled version of the entire project available to download from the Assets page.  This would drastically lower the barrier to entry for using this library, and overall be beneficial to the OpenTelemetry community.

**Comment by jack-berg** [comment]
We publish on the order of 30 artifact. For each one of these, we publish a number of different files (.jar, -javadoc.jar, -sources.jar, .module, .pom), and for each file we publish a number o different checksums used to validate the contents. See here for all the files we publish for a single artifact [io.opentelemetry:opentelemetry-exporter-otlp:1.34.1](https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-exporter-otlp/1.34.1/), which has something like 45 total files. ~30*~45 = ~1350 files published per release.

Presumably, you want this to avoid building from sources. But I have a few questions:
- Where would you have us draw the line in terms of which files we publish? 1350 seems impractical. 
- Presumably you rely on a number of other open source projects as well. Scanning through other oss java projects on github, it does not seem common to include compiled jar files directly in releases. What is your experience with other porjects?

**Comment by bryan-splunk** [comment]
We have customers that are not allowed to use Maven or Gradle for security reasons and have to manually download and all the files.  So when using projects like this it gets cumbersome to try and download and build the source due to number of dependencies.  Having even a link to the compiled binaries within the docs would be helpful as the Maven repo is very large. 
 A college recently pointed out the Maven Central badge (see screenshot below) on the Readme page is actually the link to the compiled binaries, so this badge essentially satisfies this request.  The badge, sadly, is not obviously clickable, but that is another issue.  Since the badge solves the issue I will close it.
![image](https://github.com/open-telemetry/opentelemetry-java/assets/117778967/fe0fd024-a7f5-4104-8281-b236e5730abf)
