### ISSUE TITLE
> The resource attributes MAY be copied to labels of exported metric families if required by the exporter configuration

### ISSUE THREAD

**Issue by gabrieljones** [open-telemetry/opentelemetry-java#6235]
**Describe the bug**
Prometheus metrics exporter is missing config option to copy resource attributes to labels.

> The resource attributes MAY be copied to labels of exported metric families if required by the exporter configuration
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#resource-attributes-1

**What did you expect to see?**
A config option to copy resource attributes to labels on metric families.

https://github.com/open-telemetry/opentelemetry-java/tree/v1.35.0/sdk-extensions/autoconfigure#prometheus-exporter

**What did you see instead?**
No such config option

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk-extension-autoconfigure`, `opentelemetry-exporter-prometheus`
Version: v1.35.0

**Comment by gabrieljones** [comment]
I see https://github.com/open-telemetry/opentelemetry-java/pull/6179 just got merged.

**Comment by gabrieljones** [comment]
Looks like you guys already discussed this:
https://github.com/open-telemetry/opentelemetry-java/pull/6179#discussion_r1473048035

**Comment by breedx-splk** [comment]
@gabrieljones Are you cool with this outcome, or is there something else you're looking for?

**Comment by gabrieljones** [comment]
I'd like to avoid using a customizer here.

**Comment by gabrieljones** [comment]
```application.conf
//application.conf
//...
otel-attributes {
  service-namespace = NAMESPACE-missing //something other than empty string, in case env var below is missing
  service-namespace = ${?NAMESPACE}
  deployment-environment = PAAS_ENV-missing
  deployment-environment = ${?PAAS_ENV}
  service-instance-id = HOSTNAME-missing
  service-instance-id = ${?HOSTNAME}
  service-cluster = CLUSTER_ENV-missing
  service-cluster = ${?CLUSTER_ENV}
  service-version = VERSION_JAR-missing
  service-version = ${?VERSION_JAR}
}

otel {
  exporter.otlp.endpoint = "https://<otlp inbox>"
  service.name = ${APP_NAME}
  resource {
    attributes = "service.namespace="${otel-attributes.service-namespace}
    attributes = ${otel.resource.attributes}",deployment.environment="${otel-attributes.deployment-environment}
    attributes = ${otel.resource.attributes}",service.instance.id="${otel-attributes.service-instance-id}
    attributes = ${otel.resource.attributes}",service.cluster="${otel-attributes.service-cluster}
    attributes = ${otel.resource.attributes}",service.version="${otel-attributes.service-version}
  }
  metrics.exporter = prometheus
  logs.exporter = otlp
}
```

```Main.scala
//Main.scala
//...

    val configRoot: Config = ConfigFactory.load()

    val configOpenTelemetry: Config = configRoot.withOnlyPath("otel")
    configOpenTelemetry.entrySet().asScala.foreach { e =>
      val k = e.getKey
      val v = e.getValue.unwrapped().toString
      // .- is used to denote properties that share a name with a config object name
      // https://github.com/lightbend/config/blob/v1.4.2/HOCON.md#:~:text=there%20is%20an-,intractable%20case,-where%20a%20single
      // eg
      // `otel.traces.sampler.- = parentbased_traceidratio`
      // becomes
      // `otel.traces.sampler = parentbased_traceidratio`
      val km = k.replaceAll("""\.-$""", "")
      System.setProperty(km, v)
    }
```

Result:
```scala
System.setProoerty("otel.exporter.otlp.endpoint", "https://<otlp inbox>")
System.setProoerty("otel.logs.exporter", "otlp")
System.setProoerty("otel.resource.attributes", "service.namespace=some-namespace,deployment.environment=dev,service.instance.id=some-deployment-78648ffc65-9p8jj,service.cluster=devc,service.version=3.4.1-55758a5")
System.setProoerty("otel.service.name", "some-service-name")
System.setProoerty("otel.metrics.exporter", "prometheus")

```

**Comment by jack-berg** [comment]
> I'd like to avoid using a customizer here. A customizer would require adding code to 10+ different microservices.

The system properties and environment variables we interpret in [autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure) is governed by the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md). There's currently no spec'd environment variable for configuring the prometheus resource attributes. There's a [moratorium](https://github.com/open-telemetry/opentelemetry-specification/issues/2891#issuecomment-1289241503) in place preventing any non-essential environment variable extensions while [file configuration](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md) is being worked out. Hence, my [comment](https://github.com/open-telemetry/opentelemetry-java/pull/6179#discussion_r1471934364) about adding programmatic configuration but not adding environment variable / system property support.

**Comment by gabrieljones** [comment]
Given the moratorium I guess this part of the spec is in limbo until file config is finished.
> The resource attributes MAY be copied to labels of exported metric families if required by the exporter configuration
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#resource-attributes-1

Hardcoding it is then. After https://github.com/open-telemetry/opentelemetry-java/pull/6231 goes in that is.

I don't suppose Prometheus allows for creating "views" over join queries?
> This[joins] is not a common pattern in Prometheus, and we recommend copying the most common resource attributes into metric labels.
> https://grafana.com/blog/2023/07/20/a-practical-guide-to-data-collection-with-opentelemetry-and-prometheus/#2-copy-common-resource-attributes
