### ISSUE TITLE
Insecure skip verification property using OpenTelemetry SDK

### ISSUE THREAD

**Issue by DaniduWijendra** [open-telemetry/opentelemetry-java#6256]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but searching on the documentation seems like there is no an specific property to skip CA verification using HTTPS. It should be fine to have something like this.

**Describe the solution you'd like**

I tryout the same scenario as per the internal [1] and I would like to know is there any parameter like **-Dotel.tls.insecure=true** (false by default) just to allow insecure traffic or debugging purpose.

Same as the above internal, I’m trying to configure OpenTelemery for Java through the implementation of WSO2 Micro Integrator. In that case, as mentioned in the comment [2], Below is the snippet of how WSO2 MI builds the tracer using OpenTelemetry SDK. Is there any way to provide this through OtlpGrpcSpanExporter.builder().addHeader() (If so, what would be the headerKey)? or do you have any other way to do this?
       

```
        OtlpGrpcSpanExporterBuilder otlpGrpcSpanExporterBuilder = OtlpGrpcSpanExporter.builder() 
                .setEndpoint(endPointURL)
                .setCompression("gzip")
                .addHeader(headerKey, headerValue);

        Resource serviceNameResource = Resource.create(Attributes.of(ResourceAttributes.SERVICE_NAME,
                TelemetryConstants.SERVICE_NAME));

        sdkTracerProvider = SdkTracerProvider.builder()
                .addSpanProcessor(BatchSpanProcessor.builder(otlpGrpcSpanExporterBuilder.build()).build())
                .setResource(Resource.getDefault().merge(serviceNameResource))
                .build();

        openTelemetry = OpenTelemetrySdk.builder()
                .setTracerProvider(sdkTracerProvider)
                .setPropagators(ContextPropagators.create(W3CTraceContextPropagator.getInstance()))
                .build();
```

Furthermore, is there any plan to add support for honoring such environment variables in upcoming releases? IMHO, these are defined parameters in the OpenTelemetry spec, so there should be a way to directly provide these to the OpenTelemetry SDK. We have observed that certain attributes are not honored by the Java OpenTelemetry SDK (eg: OTEL_RESOURCE_ATTRIBUTES which was fixed in a later version) although Python/Go SDKs honor the attributes.

Hence could you please let me know is there any way to achieve my requirement using an environment variable to allow insecure traffic or debugging purpose?

[1] https://github.com/open-telemetry/opentelemetry-java/issues/6214
[2] https://github.com/open-telemetry/opentelemetry-java/issues/6214#issuecomment-1948045777

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by breedx-splk** [comment]
Hey @DaniduWijendra , thanks for the issue. I'm unclear on what's being requested/asked here. It initially sounds like you are looking for a way to disable the CA check for HTTP exporters TLS, but I'm a little confused because you then go on to ask about headers and the otel specification. 

If the main issue is about ignoring the CA check, then this is a duplicate of #6214.

I'll also point out that you seem to have copied a chunk of another user's comment from #6214 and pasted it into this issue again.

> is there any parameter like -Dotel.tls.insecure=true (false by default) just to allow insecure traffic or debugging purpose.

No, not currently. This would be a new feature, which is fine, but as @jack-berg pointed out in #6214, we would want the configuration (env vars) to be applied consistently across implementations, so it should first be driven through the specification. 

> is there any plan to add support for honoring such environment variables in upcoming releases?

No plan right now. Help wanted.

> We have observed that certain attributes are not honored by the Java OpenTelemetry SDK

Please be more specific and provide concrete examples of this. The authors have gone through great pains to make sure that required environment vars are supported. Certainly `OTEL_RESOURCE_ATTRIBUTES` is well supported, and has been for quite a long time.

> Hence could you please let me know is there any way to achieve my requirement using an environment variable to allow insecure traffic or debugging purpose?

No, not currently.

**Comment by DaniduWijendra** [comment]
Hi @breedx-splk,

Thanks for the input. The **purpose of initiating this ticket is to continue the investigation of how we can set this OTEL_EXPORTER_OTLP_INSECURE parameter as per the comment [1]**.In WSO2 MI builds the tracer using OpenTelemetry SDK. Is there any way to provide this through OtlpGrpcSpanExporter.builder().addHeader() (If so, what would be the headerKey)? or do you have any other way to do this?


Furthermore, is there any plan to add support for honoring such environment variables in upcoming releases? IMHO, these are defined parameters in the OpenTelemetry spec, so there should be a way to directly provide these to the OpenTelemetry SDK. We have observed that certain attributes are not honored by the Java OpenTelemetry SDK (eg: OTEL_RESOURCE_ATTRIBUTES which was fixed in a later version) although Python/Go SDKs honor the attributes.




[1] https://github.com/open-telemetry/opentelemetry-java/issues/6214#issuecomment-1948045777

Thanks,
Danidu

**Comment by jack-berg** [comment]
> Furthermore, is there any plan to add support for honoring such environment variables in upcoming releases? IMHO, these are defined parameters in the OpenTelemetry spec

Please see the spec definition of [OTEL_EXPORTER_OTLP_INSECURE](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/protocol/exporter.md#L34-L36):

> Whether to enable client transport security for the exporter's gRPC connection. This option only applies to OTLP/gRPC when an endpoint is provided without the `http` or `https` scheme - OTLP/HTTP always uses the scheme provided for the `endpoint`. Implementations MAY choose to not implement the `insecure` option if it is not required or supported by the underlying gRPC client implementation.

`opentelemetry-java` accepts endpoints with the scheme (`http` or `https`) and its therefore unnecessary to include a separate `OTEL_EXPORTER_OTLP_INSECURE` option. If you want to connect to an OTLP endpoint without TLS, set the endpoint scheme to be `http`. 

I think you might be misinterpreting the intent of `OTEL_EXPORTER_OTLP_INSECURE` to mean "connect to an TLS endpoint (i.e. https) but don't perform validation against the certificates". This is not what `OTEL_EXPORTER_OTLP_INSECURE` does. Rather, if an SDK accepts an endpoint without a scheme (i.e. `localhost:4317`), it instructs the SDK whether or not to use TLS at all. The equivalent to setting `OTEL_EXPORTER_OTLP_INSECURE=false` is to set the `OTEL_EXPORTER_OTLP_ENDPOINT` endpoint scheme to be `http`.  

> We have observed that certain attributes are not honored by the Java OpenTelemetry SDK (eg: OTEL_RESOURCE_ATTRIBUTES which was fixed in a later version) although Python/Go SDKs honor the attributes.

I think you may be confused. In `opentelemetry-java`, the [opentelemetry-sdk-extension-autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure) is the component responsible for interpreting environment variables and outputting a fully configured `OpenTelemetrySdk` instance. `OTEL_RESOURCE_ATTRIBUTES` (and many other env vars) are definitely supported.
