### ISSUE TITLE
opentelemetry-exporter-otlp mark opentelemetry-exporter-sender-okhttp as default

### ISSUE THREAD

**Issue by driverpt** [open-telemetry/opentelemetry-java#6268]
**Describe the bug**
Adding `opentelemetry-exporter-otlp` is bringing `opentelemetry-exporter-sender-okhttp` as Default, which brings Kotlin into the Classpath, causing our Service (Using Micronaut) to fail GraalVM Compilation due to the attempt of `micronaut-core` attempting to initialize Kotlin via `IntrinsictsKt`

**Steps to reproduce**
https://github.com/micronaut-projects/micronaut-core/issues/10561

**What did you expect to see?**
I expected to be able to `sender` of choice, i.e.: `opentelemetry-exporter-sender-jdk`.

**What did you see instead?**
`opentelemetry-exporter-sender-okhttp` is always there, even if I exclude it.

**What version and what artifacts are you using?**
Artifacts: 
Version: 1.31.0 and 1.31.0-alpha
How did you reference these artifacts?

```
    implementation(enforcedPlatform(libs.boms.otel))
    implementation(enforcedPlatform(libs.boms.otel.alpha))

    implementation("io.micronaut.tracing:micronaut-tracing-opentelemetry-http")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
    implementation("io.opentelemetry:opentelemetry-exporter-sender-jdk")
    implementation("io.opentelemetry:opentelemetry-extension-aws")
    implementation("io.opentelemetry.contrib:opentelemetry-aws-xray")
    implementation("io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2")
```

**Environment**
Compiler: Corretto 17
OS: N/A

**Additional context**
Can you please make `opentelemetry-exporter-sender` an SPI and not have a Default Implementation?

Thanks

**Comment by jack-berg** [comment]
> I expected to be able to sender of choice, i.e.: opentelemetry-exporter-sender-jdk.

This is the case. The way you make the choice is by including / excluding the respective artifacts. If both `opentelemetry-exporter-sender-jdk` and `opentelemetry-exporter-sender-okhttp`, you can specify a preference by setting the system property `io.opentelemetry.exporter.internal.http.HttpSenderProvider` to the FQCN of the the `HttpSenderProvider` implementation of your choosing.

> opentelemetry-exporter-sender-okhttp is always there, even if I exclude it.

Sounds like an issue with the build configuration. 

> Can you please make opentelemetry-exporter-sender an SPI and not have a Default Implementation?

It is an SPI. The SPIs are `HttpSenderProvder` / `GrpcSenderProvider` for the HTTP / gRPC implementations of OTLP exporters, respectively.

**Comment by raghavsheoran** [comment]
Hi @driverpt , any progress on this. I was also working on a similar project to check if I can send metric and logs via opentel_micronaut graal vm application to datadog
