### ISSUE TITLE
DoubleHistogram override set Bucket export use inital bucket

### ISSUE THREAD

**Issue by ShangfengDing** [open-telemetry/opentelemetry-java#6282]
**Describe the bug**
I build a histogram meter and set the bucket first, such as
```
static List<Double> buckList = Arrays.asList(0.0, 0.005, 0.01);

OpenTelemetry openTelemetry = GlobalOpenTelemetry.get();
Meter meter = openTelemetry.meterBuilder("server_metrics").build();
DoubleHistogram histogram = meter.histogramBuilder("rpc_server_handled_seconds")
                .setExplicitBucketBoundariesAdvice(buckList)
                .build();
histogram.record(handleTime);
```

In my business logic, I will modify the bucket value, such as
```
private Runnable syncBuckList() {
        return () -> {
            .... // some business logic
            buckList = newBucket;
        };
    }
```

then I will call the logic of reporting meter again, but use different bucket
```
OpenTelemetry openTelemetry = GlobalOpenTelemetry.get();
Meter meter = openTelemetry.meterBuilder("server_metrics").build();
DoubleHistogram histogram = meter.histogramBuilder("rpc_server_handled_seconds")
                .setExplicitBucketBoundariesAdvice(buckList)
                .build();
histogram.record(handleTime);
```

I hope to see using the new bucket to pour out the indicators, but in reality, the old bucket values were still used when exporting.

<img width="1727" alt="image" src="https://github.com/open-telemetry/opentelemetry-java/assets/28734521/edfabea9-184a-4cfc-9369-8a88567bcda2">
<img width="1727" alt="image" src="https://github.com/open-telemetry/opentelemetry-java/assets/28734521/2df1b438-6fc8-41a5-87c3-b0b6a3b7845b">

**What version and what artifacts are you using?**
<opentelemetry.bom.alpha.version>1.36.0-alpha</opentelemetry.bom.alpha.version>
<opentelemetry.bom.version>1.36.0</opentelemetry.bom.version>

             <dependency>
                <artifactId>opentelemetry-bom</artifactId>
                <groupId>io.opentelemetry</groupId>
                <scope>import</scope>
                <type>pom</type>
                <version>${opentelemetry.bom.version}</version>
            </dependency>
            <dependency>
                <artifactId>opentelemetry-bom-alpha</artifactId>
                <groupId>io.opentelemetry</groupId>
                <scope>import</scope>
                <type>pom</type>
                <version>${opentelemetry.bom.alpha.version}</version>
            </dependency>

**Environment**
Compiler: jdk 1.8
OS: mac

**Comment by jkwatson** [comment]
closing, as this is working as designed.
