### ISSUE TITLE
Jaeger Exporter documentation is out of date

### ISSUE THREAD

**Issue by helpermethod** [open-telemetry/opentelemetry-java#6305]
**Is your feature request related to a problem? Please describe.**
While the Jaeger exporter has been deprecated for some time, the documentation is not up to date in all places.

**Describe the solution you'd like**
Regarding

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#jaeger-exporter

I would like to see a hint that the jaeger exporter is not supported anymore includeing some advice on migrating to the OTLP protocol.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by jack-berg** [comment]
> While the Jaeger exporter has been deprecated for some time, the documentation is not up to date in all places.

> I would like to see a hint that the jaeger exporter is not supported anymore included some advice on migrating to the OTLP protocol.

Thanks for calling this out. We should definitely do this.

**Comment by helpermethod** [comment]
Wow, that was fast! Thanks alot!
