### ISSUE TITLE
[Enhancement request] for NATIVE image, fix class: io.opentelemetry.sdk.common.export.RetryPolicy without reflect-config.json

### ISSUE THREAD

**Issue by KafkaProServerless** [open-telemetry/opentelemetry-java#6350]
Hello team,

This is my first post on this project.
I have been using open telemetry java for a while now, and if not anything else, thank you for the work here.

Just wanted to reach out with a small enhancement request.
Our team has some 61 microservices, all with this jar.

In a recent initiative, we are converting them into NATIVE images.
All 61 projects encountered the issue described here: 
https://github.com/open-telemetry/opentelemetry-java/issues/6127

We confirm the fix is correct, as we created 61 folders and subfolders, followed by creating 61 reflect-config.json.
While I can confirm this fixes the issue, may I reach out asking if it is possible to fix at the code level, so any clients with this dependency (and there are many of them) do not need to do this "trick" when building native images?

Another team in our company has some 200+ microservices, and if you take into account every other project trying to convert itself into the native image, that is quite a number.

It would be great if the code could be changed to avoid this issue for native image.
Thank you in advanced.

**Comment by jack-berg** [comment]
What version are you using? I was able to recreate the issue in #6127 and we included the `reflect-config.json` in source code in #6139.

If you encounter a different error, I would be interested in knowing the specifics. Our graal test coverage is still a work in progress so some things might be slipping through.

**Comment by KafkaProServerless** [comment]
Thank you for your answer @jack-berg 

We are using springboot 3.2.4, which pulls those versions:

```
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:3.2.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:3.2.4:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:3.2.4:compile
[INFO] |  \- io.micrometer:micrometer-jakarta9:jar:1.12.4:compile
[INFO] +- io.opentelemetry:opentelemetry-exporter-otlp:jar:1.31.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.31.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.31.0:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-extension-incubator:jar:1.31.0-alpha:runtime
[INFO] |  +- io.opentelemetry:opentelemetry-sdk-logs:jar:1.31.0:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-api-events:jar:1.31.0-alpha:runtime
[INFO] |  +- io.opentelemetry:opentelemetry-exporter-otlp-common:jar:1.31.0:runtime
[INFO] |  |  \- io.opentelemetry:opentelemetry-exporter-common:jar:1.31.0:runtime
[INFO] |  +- io.opentelemetry:opentelemetry-exporter-sender-okhttp:jar:1.31.0:runtime
[INFO] |  |  \- com.squareup.okhttp3:okhttp:jar:4.12.0:runtime
[INFO] |  |     +- com.squareup.okio:okio:jar:3.6.0:runtime
[INFO] |  |     |  \- com.squareup.okio:okio-jvm:jar:3.6.0:runtime
[INFO] |  |     |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.9.23:runtime
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.9.23:runtime
[INFO] |  |        +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.23:runtime
[INFO] |  |        |  \- org.jetbrains:annotations:jar:13.0:runtime
[INFO] |  |        \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.23:runtime
[INFO] |  \- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:jar:1.31.0:runtime
[INFO] +- io.micrometer:micrometer-registry-otlp:jar:1.12.4:compile
[INFO] |  \- io.opentelemetry.proto:opentelemetry-proto:jar:1.0.0-alpha:runtime
[INFO] |     \- com.google.protobuf:protobuf-java:jar:3.23.4:runtime
[INFO] +- io.micrometer:micrometer-tracing-bridge-otel:jar:1.2.4:compile
[INFO] |  +- io.micrometer:micrometer-tracing:jar:1.2.4:compile
[INFO] |  |  +- io.micrometer:context-propagation:jar:1.1.1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:2.0.12:compile
[INFO] |  +- io.opentelemetry:opentelemetry-api:jar:1.31.0:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-context:jar:1.31.0:compile
[INFO] |  +- io.opentelemetry.semconv:opentelemetry-semconv:jar:1.21.0-alpha:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.31.0:compile
[INFO] |  +- io.opentelemetry:opentelemetry-sdk:jar:1.31.0:compile
[INFO] |  +- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-semconv:jar:1.31.0-alpha:compile
[INFO] |  |  \- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:jar:1.31.0:compile
[INFO] |  \- io.opentelemetry:opentelemetry-extension-trace-propagators:jar:1.31.0:compile
```

Alongside graalvm 21.0.2

**Comment by KafkaProServerless** [comment]
Ah, I see what you are referring to. Indeed, I am not using the latest version.
I switch to the latest version and observed an issue:

Please allow me to close this ticket in favor of: https://github.com/open-telemetry/opentelemetry-java/issues/6352

Thank you again
