### ISSUE TITLE
Clean logic in RandomIdsGenerator.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#642]
Context: https://github.com/open-telemetry/opentelemetry-java/pull/640/files#r339639316

**Comment by breedx-nr** [comment]
This issue could use some clarification.  See https://github.com/open-telemetry/opentelemetry-java/pull/645 for one way to not do this.  :)

**Comment by jkwatson** [comment]
Agree with @breedx-nr . Unless someone can clarify what this means, I think we should close it.
