### ISSUE TITLE
Maven module opentelemetry-exporter-prometheus is not in the BOM POM

### ISSUE THREAD

**Issue by garydgregory** [open-telemetry/opentelemetry-java#6421]
The maven module opentelemetry-exporter-prometheus:

https://search.maven.org/artifact/io.opentelemetry/opentelemetry-exporter-prometheus/1.37.0-alpha/jar

is not in the BOM POM:

https://search.maven.org/artifact/io.opentelemetry/opentelemetry-bom/1.37.0/pom

**Environment**
```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\java\apache-maven-3.9.6
Java version: 17.0.11, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.11.9-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by jkwatson** [comment]
It's in the alpha bom, along with all the other `alpha` artifacts: https://central.sonatype.com/artifact/io.opentelemetry/opentelemetry-bom-alpha/overview

**Comment by jkwatson** [comment]
closing, as the alpha artifacts are in the alpha bom, where they belong.

**Comment by garydgregory** [comment]
@jkwatson 
Thank you for the pointer!

**Comment by garydgregory** [comment]
Hm, but `io.opentelemetry.instrumentation:opentelemetry-log4j-appender-2.17:2.3.0-alpha` is not in `io.opentelemetry:opentelemetry-bom-alpha:1.37.0-alpha`
Is there a BOM for that one?

**Comment by jkwatson** [comment]
instrumentation bom questions should probably be redirected over to the instrumentation repository at : https://github.com/open-telemetry/opentelemetry-java-instrumentation

The boms provided by the opentelemetry-java project are for the core libraries, but not any instrumentation.

> @jkwatson Hm, but `io.opentelemetry.instrumentation:opentelemetry-log4j-appender-2.17:2.3.0-alpha` is not in `io.opentelemetry:opentelemetry-bom-alpha:1.37.0-alpha` Is there a BOM for that one?

**Comment by garydgregory** [comment]
TY @jkwatson
