### ISSUE TITLE
1.33.x cannot work with metrics.view.config yaml file for gauge

### ISSUE THREAD

**Issue by tinshou** [open-telemetry/opentelemetry-java#6482]
**Describe the bug**
I have use -Dotel.experimental.metrics.view.config=otel.yaml to use autoconfiguration for creating SdkMeterProvider, and inside the otel.yaml I have specify a selector that only have instrument type and meter name, what I mean to do is to set the below view to all gauge that created from this meter.
But I keep getting the  "Found duplicate metric deinition: gaugeView", is this mean for one selector can only work for one instrument instead of a goup instrumentation?
![image](https://github.com/open-telemetry/opentelemetry-java/assets/25699098/5b120b7e-458f-438c-adf1-835f0a66098d)

**Steps to reproduce**
use  -Dotel.experimental.metrics.view.config=otel.yaml  , and set up one - selector in otel.yaml

**What did you expect to see?**
different gauge create from the same meter will set up the same view defined in otel.yaml

**What did you see instead?**
"Found duplicate metric deinition: gaugeView"
![image](https://github.com/open-telemetry/opentelemetry-java/assets/25699098/a3ac9193-0824-429b-a9e2-cb14dafe2aa5)

**What version and what artifacts are you using?**
Artifacts: opentelemetry-api`, `opentelemetry-sdk`
Version: 1.36.0
`pom.xml`

**Environment**
Compiler: java 17
OS: windows10
Runtime same above
OS same above

**Additional context**

**Comment by jack-berg** [comment]
Can you share the entire view configuration file? Thanks

**Comment by tinshou** [comment]
> Can you share the entire view configuration file? Thanks

Hi jack, thank you for your relpy. The whole view config file is shown in the screeshot, I only define one selector , with only instrument type and meter name, but seems that won't work.

Actually I have tried some further move, with adding all instrument inside my code, and defined each of them a separate view config selector, for eample, if I have ten gauge using inside my project, I need to write ten selector inside view config file, that will work normally. But I think that shouldn't be the approah, If have I want to set all instrument type to the same view config, I dont actually need to defined each of them right, as there's instrument type and meter name are all the same.

**Comment by jack-berg** [comment]
> The whole view config file is shown in the screenshot.

Ah thanks for that clarification.

I think there may be a misunderstanding about the `[*].view.name` field. This field dictates the output name of any metrics which match this view. Generally, this should only be used when the selector matches one instrument. If the selector selects matches multiple instruments, then you'll see multiple instruments with the same name in the output. 

I believe this is the cause for your error message: `sonic.db_table_operation_time_sum` and `sonic.db_table_operation_time_max` each match the view selector and are being renamed to `gaugeView`, which produces a conflict.

**Comment by tinshou** [comment]
> .
_“ Generally, this should only be used when the selector matches one instrument. If the selector selects matches multiple instruments, then you'll see multiple instruments with the same name in the output.”_
By this you mean that  indeed we should set up one to one selector for each instrument right? But this require us to set up twice when we using a new instrument, one is the initilization, and one is the view.config, which is not that flexible.

Other than using view.config to set up the configuration such as Aggregation type, Temporality and so on, do we have another choice to achieve this? Earliy I was creating my own SdkMeterProvider, and set up all the View and Resource and Reader, but I cannot regist the provider to GlobalOpentelemetry because I still using this otel java agent for Logs and Traces, so the GlobalOpenteletry.set() will be called by otel-java first.

**Comment by jack-berg** [comment]
> Other than using view.config to set up the configuration such as Aggregation type, Temporality 

I think I see what you're getting at. You want to use views to do some general configuration for all instruments, and then some instrument specific configuration. Unfortunately, the view mechanism isn't a very good tool for this. Notably, there is no "merging" of configuration when multiple views match a particular instrument. Instead, a separate metric stream is creating for each matching view.

However, there are specific config tools for configuring aggregation type and temporality. Both MetricReader and MetricExporter have methods to specify the default aggregation temporality for each instrument type, and the default aggregation for each instrument type. For example, see `OtlpHttpMetricExporterBuilder#setAggregationTemporalitySelector`, `OtlpHttpMetricExporterBuilder#setDefaultAggregationSelector`.

**Comment by tinshou** [comment]
> For example, see `OtlpHttpMetricExporterBuilder#setAggregationTemporalitySelector`, `OtlpHttpMetricExporterBuilder#setDefaultAggregationSelector`.

ok, thank you for your clarification. As for the example you provide, because currently I am using GlobalOpentelemetry.get().MeterProvider(), so I think I dont have the access to invoke the method you method "OtlpHttpMetricExporterBuilder#setAggregationTemporalitySelector, OtlpHttpMetricExporterBuilder#setDefaultAggregationSelector.", so in that case should I use customize SdkMeterProvider instead of Global one provided by Otel java agent?

**Comment by jack-berg** [comment]
If you're using the agent, there are a few env vars you can use to set these options:

- `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE`
- `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION`

See full details [here](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#otlp-exporter-span-metric-and-log-exporters).

If these options are insufficient, you can include an [agent extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation?tab=readme-ov-file#creating-agent-extensions) to programmatically customize the SdkMeterProviderBuilder or MetricExporter via [AutoConfigurationCustomizer](https://github.com/open-telemetry/opentelemetry-java/blob/788347e262b34ccf287a5b32a9976eb43e170c5f/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java#L141-L159).

**Comment by tinshou** [comment]
> If you're using the agent, there are a few env vars you can use to set these options:
> 
> * `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE`
> * `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION`
> 
> See full details [here](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#otlp-exporter-span-metric-and-log-exporters).
> 
> If these options are insufficient, you can include an [agent extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation?tab=readme-ov-file#creating-agent-extensions) to programmatically customize the SdkMeterProviderBuilder or MetricExporter via [AutoConfigurationCustomizer](https://github.com/open-telemetry/opentelemetry-java/blob/788347e262b34ccf287a5b32a9976eb43e170c5f/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java#L141-L159).

Thank you so much for your quick and patient reply, I think you have clear all my concerns, thank you again
