### ISSUE TITLE
Trace specific logic always causes a 30% performance hit, even when tracing is disabled 

### ISSUE THREAD

**Issue by ryanohnemus** [open-telemetry/opentelemetry-java#6539]
I am trying to find the most performant way to record a histogram that works with the opentelemetry-java api & sdk. While profiling a test app I noticed the trace logic seems to take 30% of the processing time, even when tracing is disabled. I'm opening this ticket in case there's already a solution or there's ideas on how to improve the speed.

I am using opentelemtry-java 1.39.0 api & sdk directly (not using the opentelemtry-java-instrumentation/javaagent). 

I am attempting to only use the metrics sdk as I have no current need for traces (or exemplars).

I initialize the library as follows:
```java
Resource resource = Resource.getDefault()
    .toBuilder()
    .put(ResourceAttributes.SERVICE_NAME, "dummyapp")
    .put(ResourceAttributes.SERVICE_VERSION, "0.1.0")
    .put(ResourceAttributes.SERVICE_INSTANCE_ID, UUID.randomUUID().toString())
    .put(ResourceAttributes.HOST_NAME, InetAddress.getLocalHost().getHostName())
    .build();


SdkMeterProviderBuilder meterProviderBuilder = SdkMeterProvider.builder();
// Disable exemplar filter, instead of default traceBased filter
SdkMeterProviderUtil.setExemplarFilter(meterProviderBuilder, ExemplarFilter.alwaysOff());

SdkMeterProvider sdkMeterProvider = meterProviderBuilder
    .registerMetricReader(PeriodicMetricReader.builder(OtlpJsonLoggingMetricExporter.create()).setInterval(Duration.ofSeconds(10)).build())
    .setResource(resource)
    .build();

// Only create the sdk with a meterProvider
OpenTelemetry openTelemetry = OpenTelemetrySdk.builder()
    .setMeterProvider(sdkMeterProvider)
    .buildAndRegisterGlobal();
```

I am not providing/initializing a TracerProvider which states in the [doc](https://opentelemetry.io/docs/languages/java/instrumentation/#initialize-tracing): 
> If a TracerProvider is not created, the OpenTelemetry APIs for tracing will use a no-op implementation and fail to generate data.

My logic for the test: 

```java
Meter meter = GlobalOpenTelemetry.meterBuilder("DummyTest").build();

testHistogram = meter
    .histogramBuilder("dummyapp.test.latency")
    .setDescription("The duration of time to process dummyapp test latency")
    .setUnit("ns")
    .setExplicitBucketBoundariesAdvice(Arrays.asList(0.0, 50.0, 250.0, 500.0, 1000.0, 5000.0, 10000.0, 30000.0, 60000.0, 120000.0, 300000.0, 600000.0))
    .build();

Random random = new Random();

int count;
while (true) {
    //pause a tiny bit before each run
    long end = System.nanoTime() + 10000000;
    while (System.nanoTime() < end) {
      //busy spin
    };

    //running histogram.record in bursts of 10k
    count = 10000;
    while(count > 0) {
    int latency = random.nextInt(1000);
      testHistogram.record(latency);
      count -= 1;
    }
}
```

I then profiled this using visualvm:

### Test Run
![default_record](https://github.com/open-telemetry/opentelemetry-java/assets/19394817/a71305f0-0127-4869-8e8b-77fb6976b8c0)
- from the above code, I am using the default histogram.record(latency) without passing attributes or context
1. 9577ms for 706885 invocations = 0.0135 ms per `histogram.record` call
2. 28.7% of this time is just for retrieving `Context.current()` 
   1. which happens because SdkDoubleHistogram.record(`value`) calls
      1. SdkDoubleHistogram.record(`value`, `Attributes.empty()`) which calls 
         1. SdkDoubleHistogram.record(`value`, `attributes`, `Context.current()`) (where we see the `Context.current()` per hit)
   2. This context is passed around to nearly every call under storage.record, but since exemplar filters and traces are off, it's just thrown away/unused as far as i can tell (maybe this isn't correct?)
3. 5.3% of the time is spent in FilteredExemplarReservoir.offerDoubleMeasurement (even when exemplar filter is specifically disabled)
---

While using this as is will most likely be neglible for most applications, I am trying to use the histogram.record method within a high perf app that generally sustains processing of 30k messages / sec, so I need to be able to record the histogram in the most performant way possible. (If my math is correct) At 30k histogram.record / sec for 1 min, >24s of that min would just be for recording this histogram with ~8s of that for the tracing/context logic overhead.

1) Is there a way to prevent opentelemetry-java sdk from traversing these paths or using any Context at all when tracing is disabled? or is there an empty Context that can be used (similar to Attributes.empty()) when someone is not using tracing?

2) is there a way to prevent traversing the exemplar logic when that is also disabled? 

Are there other known ways to improve performance? Or should I be looking into one of the following:

- write my own MeterProvider, that factors out all of the tracing logic
  - this would be a pain because I'd have to rewrite my own version of every possible instrument type
- Not using instruments from the sdk at all, creating my own version of an explicit bucket histogram (and any other wanted instrument types). I would then need to write my own MetricProducer that reads these non-sdk metrics and converts them to a `Collection<MetricData>` on the `produce` timer callback. 
  - This seems overly custom & complicated?

I appreciate any feedback / ideas!

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-api`, `opentelemetry-sdk`
Version: 1.39.0

**Environment**
Compiler: (e.g., "Java Zulu 17.0.11+9")
OS: (e.g., "MacOS 14.5")

**Additional context**

**Comment by jkwatson** [comment]
If you don't want/need any Context, you could replace the `ContextStorage` implementation with one that always just returns simple, empty Context instance. This can be done via the ContextStorageProvider SPI: https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/ContextStorageProvider.java#L27

**Comment by ryanohnemus** [comment]
@jkwatson thank you for the advice! I gave that a try by creating my own ContextStorageProvider, ContextStorage, and Context classes. The `Context` being returned via my `ContextStorage` is an empty Context class implementation. 

This took the `Context.current()` time down to only being 7.3% of the record time call, which is an improvement from the 28.7% before. 

However, context is nullable, so I found the fastest is actually to not use my own ContextStorageProvider via SPI and instead just use a `null` when calling the function with full parameters: `histogram.record(value, attributes, null)`. This skips the need for going through a ContextProvider code path at all and I "gain" all of the 28.7% performance impact back. 

So... is it worth suggesting that if `otel.traces.exporter=none` that the `histogram.record(value, attributes)` function just calls `histogram.record(value, attributes, <context>)` with context=null instead of Context.current()? (or perhaps the `Context.current()` just returns null when that property is set?)... That would even give people that use the javaagent with traces disabled a perf improvement on metric recording.

Thank you for the advice, this ticket can be closed unless the maintainers think that suggestion it worth looking in to!

**Comment by jkwatson** [comment]
I think we're unlikely to change that behavior, as it would be a significant breaking change for most users who are assuming the Context will be auto-associated with the recording when not providing one explicitly. 

I think your use-case is relatively rare, and our goal is to make the common case simple and obvious, but still enable the more rare case (and, it looks like your case has been fulfilled with the explicit `null` parameter value).

thanks for the feedback!

**Comment by jack-berg** [comment]
> 9577ms for 706885 invocations = 0.0135 ms per histogram.record call

0.0135 milliseconds is equal to 13,500 ns. This is a very pessimistic estimate. Your test setup incudes includes intentional pause / busy waiting. When I get rid of that on my machine I see that each record call takes 49ns, which is 275x faster than your estimate. I recently published a [blog post](https://opentelemetry.io/blog/2024/java-metric-systems-compared/) talking about the performance of the java metrics SDK, which performance figures (on my machine) as well as code for you to run on your own.

> At 30k histogram.record / sec for 1 min, >24s of that min would just be for recording this histogram with ~8s of that for the tracing/context logic overhead.

Since each record call takes ~49 ms, 30k records would take just 0.00147 seconds. Its true that the context API portions of the record operation do take some time. On my machine they take ~15.5% of the total time to call record. But the way to think about it is that your app is doing some other work when processing 30k records per second. Each one of those records takes about (1 second / 30k records per second * 1e9 nanoseconds per second) = 33k nanoseconds. The question is whether the 49 additional nanoseconds to record a measurement to a histogram is too much? It adds .148% overhead, which is not nothing, but is quite low.

There's an idea called "bound instruments" which we punted on but which may allow you to achieve even higher performance. However, it requires that you always know your attribute sets for each measurement ahead of time. I talk about this in more details in my blog post I linked above. Is this something your app would benefit from?

**Comment by ryanohnemus** [comment]
@jack-berg apologies for my inability to do time math properly 🤦 ... thank you for the response, the blog, and the jmh examples!!

I was actually starting down the path of writing my own sdk external instrument types that would be bridged to opentelemetry via a MetricProducer. These instruments would be considered bound instruments that have known attribute values ahead of time. I started by looking at the `DoubleExplicitBucketHistogramAggregator` implementation which has the base of what I wanted to record (basically narrowing this down to mostly the `Handle::doRecordDouble(double value)` logic, so no exemplar or trace context at all). I then tested this by adding this in to your jmh benchmark suite. I'm running my tests on an older ~2019 macbook pro, so a tiny bit slower than your machine, but still got some interesting results on the record testing...

recordOneThread: 
- Bound Explicit Double Histogram - ~26ns
- otel explicit histogram reusable data known attributes - ~56.8ns

So my current plan is to continue down the more custom route here for the speed-up, but if bound instruments became a reality in the sdk I would move to use that over my custom code 😄

**Comment by jack-berg** [comment]
@ryanohnemus I opened an issue in the spec to track support for bound instruments here: https://github.com/open-telemetry/opentelemetry-specification/issues/4126 I recommend you go upvote that issue to indicate that you would benefit from it.

I've heard interest in the concept from several people recently so I'd say its pretty realistic that this actually gets added, albeit on a schedule that is slower than you / I might like. 🙂
