### ISSUE TITLE
Support PKCS#1 private keys

### ISSUE THREAD

**Issue by abvaidya** [open-telemetry/opentelemetry-java#6571]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Today TLSUtil.java only supports PKCS#8 format - https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/common/src/main/java/io/opentelemetry/exporter/internal/TlsUtil.java#L76

**Describe the solution you'd like**
Request for enhancement to handle PKCS#1 in addition to PKCS#8

**Describe alternatives you've considered**
Existing users with PKCS#1 keys would need to convert the keys to PKCS#8 format only to make it work with java sdk. It will also have additional maintenance work if the keys are rotated frequently.

**Additional context**

**Comment by jack-berg** [comment]
[Java doesn't come with out-of-the-box support for PKCS#1](https://stackoverflow.com/questions/41934846/read-rsa-private-key-of-format-pkcs1-in-java) - you have to use bouncycastle. We probably don't want to impose this dependency on users, which means that we would need to add some sort of SPI mechanism for adding support for reading different key formats.

You can use PKCS#1 keys today if you're willing to read the contents yourself and call [setSslContext](https://github.com/open-telemetry/opentelemetry-java/blob/38aeffff145338ae0f65730fd69f94c83219592a/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/metrics/OtlpGrpcMetricExporterBuilder.java#L188-L198) (link is for the metric exporter, but all OTLP exporter builders have this method).

**Comment by abvaidya** [comment]
Hah! I didnt realize java doesnt support pkcs#1 natively. Thank you for the prompt response. We prefer to use mtls with short expiry certificates so I would have to use the sslcontext anyways!
