### ISSUE TITLE
Support PEM trust bundles with explanatory text in it

### ISSUE THREAD

**Issue by abvaidya** [open-telemetry/opentelemetry-java#6572]
**Is your feature request related to a problem? Please describe.**
PEM format can export explanatory text inside it ( ref: https://datatracker.ietf.org/doc/html/rfc7468#section-5.2 ) but https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/common/src/main/java/io/opentelemetry/exporter/internal/TlsUtil.java#L130 expects only PEM encoded content and nothing else

**Describe the solution you'd like**
Update the code in TLSUtil.java to be able to handle explanatory text

**Describe alternatives you've considered**
A workaround would be to convert existing PEM bundle(s) with explanatory text to the one without explanatory text.

**Additional context**
I am willing to submit a PR. 

Thank you.

**Comment by jack-berg** [comment]
This seams reasonable. A PR would be appreciated!
