### ISSUE TITLE
W3CBaggagePropagator usecase illustration

### ISSUE THREAD

**Issue by kulkravi** [open-telemetry/opentelemetry-java#6607]
I am a relative newbie to Java programming and Open Telemetry. I must be missing something very basic. I have done enough Google search and read through the example code provided with Open Telemetry for manual tracing. Still not able to figure out how to implement tracing across process boundaries. I have a toy application that consists of the following:

Order Service (SpringBootApplication)
Local Service Client (WebClient from Spring Framework)
Product Service (SpringBootApplication)

Product service stores product details. Order Service accepts orders, queries Product Service via Local Service Client for product details and stores them. 

I initialize Open Telemetry in Order Service like so:

`    @Bean
    public OpenTelemetrySdk openTelemetry() {

        final AttributeKey<String> SERVICE_NAME = AttributeKey.stringKey("service.name");
        final AttributeKey<String> SERVICE_VERSION = AttributeKey.stringKey("service.version");

        Resource resource = Resource.create(Attributes.builder()
            .put(SERVICE_NAME, "OrderService")
            .put(SERVICE_VERSION, "0.1.0")
            .build());

        SdkTracerProvider sdkTracerProvider = SdkTracerProvider.builder()
            .addSpanProcessor(SimpleSpanProcessor.create(LoggingSpanExporter.create()))
            .addSpanProcessor(BatchSpanProcessor.builder(ZipkinSpanExporter.builder().setEndpoint("http://localhost:9411/api/v2/spans").build()).build())
            .setResource(resource)
            .build();

        OpenTelemetrySdk sdk =
            OpenTelemetrySdk.builder()
            .setTracerProvider(sdkTracerProvider)
            .setPropagators(ContextPropagators.create(W3CBaggagePropagator.getInstance()))
            .build();

        Runtime.getRuntime().addShutdownHook(new Thread(sdk::close));
        // io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender.install((OpenTelemetry) sdk);
        return sdk;
    }`

I do the same in Product Service like so:

`    @Bean
    public OpenTelemetrySdk openTelemetry() {

        final AttributeKey<String> SERVICE_NAME = AttributeKey.stringKey("service.name");
        final AttributeKey<String> SERVICE_VERSION = AttributeKey.stringKey("service.version");

        Resource resource = Resource.create(Attributes.builder()
            .put(SERVICE_NAME, "ProductService")
            .put(SERVICE_VERSION, "0.1.0")
            .build());

        SdkTracerProvider sdkTracerProvider = SdkTracerProvider.builder()
            .addSpanProcessor(SimpleSpanProcessor.create(LoggingSpanExporter.create()))
            .addSpanProcessor(BatchSpanProcessor.builder(ZipkinSpanExporter.builder().setEndpoint("http://localhost:9411/api/v2/spans").build()).build())
            .setResource(resource)
            .build();

        OpenTelemetrySdk sdk =
            OpenTelemetrySdk.builder()
            .setTracerProvider(sdkTracerProvider)
            .build();

        Runtime.getRuntime().addShutdownHook(new Thread(sdk::close));
        // io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender.install((OpenTelemetry) sdk);
        return sdk;
    }`

Order Service calls Product Service with the following code:
`            Product product = client.getProduct(order.getItem()).block();
`
And Local Service client implements the getProduct method like so:

`public Mono<Product> getProduct(String name) {
        logger.debug("Getting product details for " + name);
        Mono<Product> result;
        Span currentSpan = tracer.spanBuilder("Get Product Details").startSpan();
        result = this.webClient.get()
                .uri("/products/".concat(name))
                .retrieve()
                .bodyToMono(Product.class);
        currentSpan.end();
        return result;
    }
}`

My question is: how do I propagate the baggage from Order Service to Product Service and back?

Ravi

**Comment by jkwatson** [comment]
1. Are you trying to "implement tracing across process boundaries" or are you trying to just propagate baggage between processes? 
2. You aren't configuring the baggage propagator in your product service.
3. In order to propagate _anything_ you have to be using the configured propagator to put the data into the cross-process-boundary carrier on the calling client side (looks like HTTP headers in your case), and extracting that data from the carrier on the server side.
4. Are you using any pre-built instrumentation, such as the otel spring boot starter instrumentation?

**Comment by kulkravi** [comment]
> 1. Are you trying to "implement tracing across process boundaries" or are you trying to just propagate baggage between processes?

My intention is to implement observability. So, I want to choose whichever approach is best suited in a specific use case. In this case, let's say I want to implement tracing across process boundaries.

> 2. You aren't configuring the baggage propagator in your product service.

Correct. So, if I want the baggage to get back to Order Service with payload from Product Service, I suppose it is necessary.

> 3. In order to propagate _anything_ you have to be using the configured propagator to put the data into the cross-process-boundary carrier on the calling client side (looks like HTTP headers in your case), and extracting that data from the carrier on the server side.

OK, do I have to implement a custom propagator on both sides? Is there a mechanism in Open Telemetry to inject the baggage into the HTTP headers automatically?

> 4. Are you using any pre-built instrumentation, such as the otel spring boot starter instrumentation?

No. This is a manual tracing use case.

**Comment by kulkravi** [comment]
> You don't have to implement a custom propagator. The standard propagators will work fine. You do have to use the propagators, though, to inject & extract the relevant Context.

I have one last question: propagators automatically inject the trace into the HTTP headers or I have to make explicit calls to do so? I don't see a example that addresses this specific usecase, or perhaps I misunderstand that part as well.

Thanks for engaging with me, much appreciated!

**Comment by jkwatson** [comment]
This example has both client and server propagator usage: https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/http/src/main/java/io/opentelemetry/example/http

**Comment by kulkravi** [comment]
Thank you! That teaches me to read all of the examples, not just those that say tracing :). But I think it will help if we rename http with something more descriptive.
