### ISSUE TITLE
What's plan to support Spring/SpringBoot/SpringCloud

### ISSUE THREAD

**Issue by HaojunRen** [open-telemetry/opentelemetry-java#662]
Opentracing has already support these, how about opentelemetry? Thanks a lot

**Comment by kbrockhoff** [comment]
This work is part of #522 which I am currently working on,

**Comment by HaojunRen** [comment]
Cool

**Comment by kbrockhoff** [comment]
Partially implemented by PR #736

**Comment by cforce** [comment]
What is missing?

**Comment by HaojunRen** [comment]
Maybe refer to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1497#issuecomment-616630833

**Comment by jkwatson** [comment]
This is an issue for the instrumentation project. Closing this issue. Please open in the instrumentation project if more is needed.

**Comment by marcingrzejszczak** [comment]
In case anyone is interested in the topic. There's the incubating Spring Cloud Sleuth OTel project that you can use - https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/
