### ISSUE TITLE
Stackdriver Exporter

### ISSUE THREAD

**Issue by dansiviter** [open-telemetry/opentelemetry-java#663]
OpenCensus has this for both trace and metrics however I cannot find a single reference to this in Java OpenTelemetry and is not on the default specification open-telemetry/opentelemetry-specification#6. It seems other languages are looking at this (see [opentelemetry-dotnet/OpenTelemetry.Exporter.Stackdriver](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Exporter.Stackdriver) and [opentelemetry-go/trace/stackdriver](https://github.com/open-telemetry/opentelemetry-go/tree/master/exporter/trace/stackdriver)).

**Comment by bogdandrutu** [comment]
We are waiting to create a new org/repo for the stackdriver expoters. OpenTelemetry decided to not host the Stackdriver exporters in the main repos and all languages will remove that soon, we will move them in a separate repo.

**Comment by dansiviter** [comment]
Thanks for the info. I'm assuming Googlers are going to get involved with this soon? Any idea of timelines?

**Comment by bogdandrutu** [comment]
Yes. Don't have right now a real timeline estimate.

**Comment by jkwatson** [comment]
I think we should close this, since it won't be hosted by the otel project.

**Comment by dansiviter** [comment]
Happy for it to be closed, but would be useful to get some clarity on where it will be hosted.

**Comment by eli-jordan** [comment]
Any update on when this is coming / where it will be published?

I noticed that a stackdriver exporter was recently added to the collector

**Comment by dansiviter** [comment]
Found it: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java

**Comment by nilebox** [comment]
This issue can be closed, see link for official repo above.

**Comment by jkwatson** [comment]
closing
