### ISSUE TITLE
Stabilize ExceptionEventData

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#6630]
I think we've just waiting for feedback, positive or negative. Personally, its simple enough that I'm willing to go out on a limb and stabilize it. Waiting for feedback may be overkill.

_Originally posted by @jack-berg in https://github.com/open-telemetry/opentelemetry-java/discussions/6619#discussioncomment-10259365_

**Comment by vasantteja** [comment]
Hello @jack-berg !! Can I work on this if it's approved?

**Comment by jack-berg** [comment]
Sure - I've assigned it to you.

**Comment by olamideTiana** [comment]
@jack-berg I don't see a PR, can I also give this a try?

**Comment by jack-berg** [comment]
Sure go ahead @olamideTiana!

**Comment by olamideTiana** [comment]
@jack-berg On it!
