### ISSUE TITLE
Make the exporter and relevant builder class extendable. 

### ISSUE THREAD

**Issue by galahad098** [open-telemetry/opentelemetry-java#6636]
**Is your feature request related to a problem? Please describe.**
In relation to the problem described in : https://github.com/open-telemetry/opentelemetry-java/issues/6306, we finally decided to implement a custom exporter which takes care of the scenario in question. But to make this happen, it would be easier if some of the opentelemetry helper classes were extendable, for example : OtlpHttpSpanExporterBuilder, HttpExporter, HttpExporterBuilder and OtlpHttpSpanExporter.
 

**Describe the solution you'd like**
Making these classes extendable (not final) would be helpful.

**Comment by jack-berg** [comment]
What types of things would be possible if the classes were extensible which are not possible in a delgation model?

Also, now that #6348 is merged, we need to update HttpExporter, GrpcExporter to record exceptions with detailed info about failed export attempts.

**Comment by galahad098** [comment]
> What types of things would be possible if the classes were extensible which are not possible in a delgation model?
We are only creating a custom exporter to also get the error details. So most of the functionality we can re-use. Hence the ask to make the classes extendable. 

> Also, now that #6348 is merged, we need to update HttpExporter, GrpcExporter to record exceptions with detailed info about failed export attempts.

If this enhancement lets record the exceptions thrown by the collector application, then this solves our problem

**Comment by jack-berg** [comment]
> Specifically, whenever the exporter sends data to a collector that responds with an error message and a response body,

You'll be able to get the exception which will probably include status code, but not the response body. At least not yet. See my comment [here](https://github.com/open-telemetry/opentelemetry-java/issues/6306#issuecomment-2040627486) about the complexity of deserializing response body.

I'd be open to contributions to introduce deserialization of response body in the OTLP exporters.

**Comment by jarrodrobins** [comment]
>You'll be able to get the exception which will probably include status code, but not the response body. At least not yet.

I have opened a PR (pending review) which at least does this first part of returning an exception and status code (#6645). While that doesn't solve the full problem discussed here of parsing response bodies, perhaps it could be extended to solve that with further contributions?

**Comment by galahad098** [comment]
@jack-berg Understood. 
@jarrodrobins Thanks! If this is made available, we could proceed with the status code at least for now.
I'll go through the code to see if we can get the response body as well.

**Comment by galahad098** [comment]
Hi @jack-berg, Can we already get @jarrodrobins's PR reviewed & merged? We'd like to test if we're able to get the status code in a failed export response.

**Comment by jack-berg** [comment]
> However, is it okay to add the response body as a byte[] to the FailedExportException so that we could deserialize it in our code?

I think that's the simplest path forward. We could evolve that to have a properly decoded type eventually, but still grant access to the raw bytes so a motivated consumer can deserialize and act on them.

**Comment by SmithaMJ** [comment]
Thank you @jack-berg for confirming that.

@jarrodrobins, 
The changes that you have done for the status code is already very helpful for us. We would like to have the raw bytes as well added to the FailedExportException, Is it okay for you to add this also to your PR? I'm also open to contribution if you can guide me through the process.

**Comment by jarrodrobins** [comment]
Hey @SmithaMJ, I believe with my PR you should be able to access the response body now. If you're using the HttpExporter and you get a server failure, the `response` property of `FailedExportException.HttpExportException` will be set. You can then call `responseBody()` on that to get the bytes (or `statusCode()` or `statusMessage()` for those values). Does that make sense, or have I misunderstood you? 

The only cases where the `response` property won't be set is if you get some other kind of exception, eg, an IOException.

**Comment by SmithaMJ** [comment]
Hi @jarrodrobins , I thought that the HttpExporter was already reading the response body:

                    try {
                        body = httpResponse.responseBody();
                    } catch (IOException var7) {
                        this.logger.log(Level.FINE, "Unable to obtain response body", var7);
                    }
My concern was that since the response body has been read one time, will not the byte stream return empty since it was already read. I have not tested this yet.

**Comment by jarrodrobins** [comment]
Ah right, of course. Looks like the response body is only read to log a couple of things - the easiest thing would be to just remove that and let the client deal with it, or we keep it and return the status code, message and body separately to the exception rather than the `HttpSender.Response`. Personally the first option feels cleaner to me, but I'll defer to @jack-berg.

**Comment by SmithaMJ** [comment]
Hello @jack-berg and @jarrodrobins ,
We did a quick test with a plain OkHttpClient and tried reading the bytes multiple times.
 ResponseBody responseBody = response.body();
                    System.out.println("Okhttp11 : response string : {}" + responseBody.bytes());
                    System.out.println("Okhttp222 : response string : {}" + responseBody.bytes());
It printed the first line and failed at the second line with the below exception.
Caused by: java.lang.IllegalStateException: closed
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:279)
	at okio.Buffer.writeAll(Buffer.kt:1308)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:243)
	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124) 

The easier solution would be to comment out the log or just store the byte[] body in the Exception itself.
Please share your views.

**Comment by jarrodrobins** [comment]
I have pushed a commit to my PR removing the response body read and log message. Just awaiting final review.

**Comment by galahad098** [comment]
Hi @jack-berg, I see @jarrodrobins 's PR is merged! Thanks a lot both of you! How can we test this now? Is there a milestone build version we can use?

**Comment by jack-berg** [comment]
You can test against [snapshots of the main branch](https://github.com/open-telemetry/opentelemetry-java?tab=readme-ov-file#snapshots) now. We publish releases the [friday after the first monday of the month](https://github.com/open-telemetry/opentelemetry-java/blob/main/RELEASING.md#release-cadence) (i.e. 9/6/24).

**Comment by galahad098** [comment]
Hi @jack-berg @jarrodrobins, we have tested the change and this solves our problem! Thanks a lot! Closing this issue.
