### ISSUE TITLE
Rename Tracer/MeterFactory to Tracer/MeterRegistry

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#664]

**Comment by arminru** [comment]
> No description provided.

Where does this requirement originate from?

**Comment by bogdandrutu** [comment]
I like the names better than `Factory`. Main reason is that we do have an internal shared state between all Tracers that is owned by the `Registry` or `Factory`, usually factories do not share state with elements created.

I don't feel very strong but I do think it is a better name.

**Comment by arminru** [comment]
I'm perfectly fine with TracerRegistry and do agree with your considerations, I just didn't know where this issue originated from. Once https://github.com/open-telemetry/opentelemetry-specification/pull/354 is merged we are free to name it either way, I'm all in for TracerRegistry then.

**Comment by carlosalberto** [comment]
+1 on having it as `Registry`.

**Comment by Oberon00** [comment]
In my python PR (https://github.com/open-telemetry/opentelemetry-python/pull/301) I named it `TracerSource` because it does not keep track of the created tracers, so registry would be wrong.
