### ISSUE TITLE
Add "Model" suffix to declarative configuration generated types

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#6676]
The declarative configuration model defines a large number of types corresponding to different aspects of SDK configuration, and we generate classes from these models.

These generates classes often have the same name as types in the SDK. For example, `io.opentelemetry.sdk.extension.incubator.fileconfig.internal.model.Sampler` is the generated type to configure `io.opentelemetry.sdk.trace.samplers.Sampler`. These conflicts mean that one of the two has to be fully qualified in the factory classes, which reduces readability. For example:

https://github.com/open-telemetry/opentelemetry-java/blob/902c46e2a74239bc13e140f8d70a0106c8f10ee1/sdk-extensions/incubator/src/main/java/io/opentelemetry/sdk/extension/incubator/fileconfig/SamplerFactory.java#L40-L43

We can resolve this, and make the purpose of these generated classes more obvious by appending a suffix like "Model" to each.

**Comment by jkwatson** [comment]
seems like a reasonable request!

**Comment by vasantteja** [comment]
Can I please work on this?

**Comment by jack-berg** [comment]
Sure @vasantteja. I've assigned it to you.
