### ISSUE TITLE
SimpleLogRecordProcessor, SimpleSpanProcessor call export concurrently, but shouldn't

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#6681]
`SpanExporter#export`, `LogRecordExporter#export` [should not be called concurrently](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#exportbatch), but `SimpleSpanProcessor`, `SimpleLogRecordExporter` don't have any synchronization:

https://github.com/open-telemetry/opentelemetry-java/blob/ee7fd2744949ae0c060d28c73edfca56633dc170/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/SimpleSpanProcessor.java#L84-L102

https://github.com/open-telemetry/opentelemetry-java/blob/ee7fd2744949ae0c060d28c73edfca56633dc170/sdk/logs/src/main/java/io/opentelemetry/sdk/logs/export/SimpleLogRecordProcessor.java#L63-L79

Noted by @pellared in https://github.com/open-telemetry/opentelemetry-specification/issues/4134#issuecomment-2218883965

**Comment by pellared** [comment]
Credits go to @cijothomas (not me 😉)

**Comment by slodha** [comment]
i'm working on this issue.
