### ISSUE TITLE
Trying to find opentelemetry bom(s) for some leftover dependencies

### ISSUE THREAD

**Issue by jimshowalter** [open-telemetry/opentelemetry-java#6682]
We are using org.springframework.boot:spring-boot-dependencies, which imports most of opentelemetry, and io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha, which adds more opentelemetry, but we still have some leftover opentelemetry dependencies we are managing by hand because we can't find them in any bom:

- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api
- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-incubator
- io.opentelemetry:opentelemetry-api-events
- io.opentelemetry:opentelemetry-api-incubator
- io.opentelemetry:opentelemetry-api-logs
- io.opentelemetry:opentelemetry-extension-incubator
- io.opentelemetry:opentelemetry-sdk-logs
- io.opentelemetry:opentelemetry-semconv

Is there another bom or boms that contain(s) them?

**Comment by jkwatson** [comment]
A number of these are in the alpha bom: https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-bom-alpha/1.41.0-alpha

**Comment by jimshowalter** [comment]
Thank you!
