### ISSUE TITLE
Add library resources to named meters in the SDK

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#670]
Part of / follow-up for #588:

The implementation of `MeterSdkFactory` added in #668 currently discards the passed instrumentation name and version. As specified in the [OTEP](
https://github.com/open-telemetry/oteps/blob/master/text/0016-named-tracers.md#internal-details), it has to be made available as a `Resource` (in case of Java we use a dedicated info object `InstrumentationLibraryInfo`, see #632).
The metrics API currently has changes pending, this will have to be addressed once the SDK spec for metrics is updated.

(analogous to #617 for named tracers)

**Comment by bogdandrutu** [comment]
@arminru I think all the libraries should use a different object and not resource.

**Comment by arminru** [comment]
> @arminru I think all the libraries should use a different object and not resource.

@bogdandrutu The OTEP mentions that a `Resource` has to be used but the spec doesn't impose any limitations so I'm fine with keeping the `InstrumentationLibraryInfo`.

**Comment by jkwatson** [comment]
I believe this is done. closing. Please reopen if something else is needed.
