### ISSUE TITLE
Make StrictContextStorage public

### ISSUE THREAD

**Issue by johnpoth** [open-telemetry/opentelemetry-java#6716]
**Is your feature request related to a problem? Please describe.**
It would be cool to make the StrictContextStorage class public so that other projects can use it in their own tests. Thanks !

**Describe the solution you'd like**
make the StrictContextStorage class public 

**Describe alternatives you've considered**
Copy paste

Thanks !

**Comment by jkwatson** [comment]
I'm not opposed to this idea, but can you not leverage `-Dio.opentelemetry.context.enableStrictContext=true` to turn it on in tests?

**Comment by johnpoth** [comment]
@jkwatson thanks for your response! Yes that is great thank you !

**Comment by trask** [comment]
hi @johnpoth, did you still want to pursue making `StringContextStorage` public, or does this address your needs and we can close the issue? thanks!

**Comment by johnpoth** [comment]
@trask I think we can close the issue thank you so much!
