### ISSUE TITLE
better API for interacting with BaggageEntryMetadata

### ISSUE THREAD

**Issue by stevesea** [open-telemetry/opentelemetry-java#6729]
**Is your feature request related to a problem? Please describe.**
if I have a baggage header like: 

`corp.key1=val1;tag2;tag3`

```java
String result = Baggage.current().getEntryValue("corp.key1");
// result is "val1"
```

If I want the additional data, I have to write code like: 
```java
String result = Baggage.current().asMap().get("corp.key1").getMetadata().getValue()
// result is "tag2;tag3"
```

**Describe the solution you'd like**
I'd like an additional API: 
`Baggage.current().getEntry()` that returns the `BaggageEntry`

**Comment by breedx-splk** [comment]
Hi @stevesea . This seems completely reasonable to me -- especially considering that `asMap()` is considerably more expensive if there are many entries. Let's try it!

One thing to note is that the [baggage api](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md) is considered stable and in feature freeze, but hopefully this doesn't prevent _adding_ a method like this. There could be push back that wants this added to the spec first. I guess we'll see...

**Comment by trask** [comment]
> hopefully this doesn't prevent adding a method like this

my understanding is that languages are free to add convenience sugar around the core spec'd methods
