### ISSUE TITLE
Alpha release for Tracing API and Tracing sdk.

### ISSUE THREAD

**Issue by samvaity** [open-telemetry/opentelemetry-java#674]
Currently, the release schedule mentions releasing an alpha version of the library by middle October 2019 [Oct 21st, 2019]. But we still do not have a non-snapshot version.

What could be the best estimate to get a non-snapshot version of this library released on Maven?

**Comment by bogdandrutu** [comment]
@carlosalberto can you please make a release to maven for `0.2.0-alpha` version (or just `0.2.0`)?

**Comment by joshfree** [comment]
Thank you @bogdandrutu and @carlosalberto -- yes pushing a non-snapshot to Maven will help keep the Azure SDK for Java team's infra happy (https://github.com/Azure/azure-sdk-for-java/issues/6301).  Would it be possible to get a 0.2.0 (or 0.2.0-alpha) pushed to Maven before 11/22 (https://github.com/Azure/azure-sdk-for-java/milestone/62)?

Thank you

**Comment by lizthegrey** [comment]
Can you also update the website ASAP to indicate this status so I don't misrepresent your status onstage at KubeCon? Thx. cc @austinlparker

**Comment by austinlparker** [comment]
The website data is generated from the milestones in GitHub (see https://github.com/open-telemetry/community/issues/201). Please update the milestones in this repo and ping me on this thread and I can force a website update.

**Comment by samvaity** [comment]
@carlosalberto, @bogdandrutu Do we have any update on the release of the packages? I still don't see them on Maven yet.

**Comment by samvaity** [comment]
Packages released to Maven - https://repo.maven.apache.org/maven2/io/opentelemetry/
Thank you for doing this @carlosalberto  and @bogdandrutu  :)
