### ISSUE TITLE
SdkSpanBuilder returns a non-recording Span when SpanProcessor has exportUnsampledSpans to true

### ISSUE THREAD

**Issue by dreedyman** [open-telemetry/opentelemetry-java#6740]
**Is your feature request related to a problem? Please describe.**
When setting the SpanProcessor's exportUnsampledSpans to true, I would expect that when the Span is created by the `SdkSpanBuilder.startSpan()` that it would not return a PropagatedSpan That never gets sent to the SpanProcessor. 

**Describe the solution you'd like**
Is it possible that the exportUnsampledSpans could be added to the SdkSpanBuilder? Something like the following:
 
```
if (!exportUnsampledSpans && !isRecording(samplingDecision)) {
    return Span.wrap(spanContext);
}
```

This would also require adding a configurable property to the SdkSpanBuilder for the property to be set.

**Comment by jack-berg** [comment]
It sounds like you have a sampler returning `SamplingDecision.DROP`. In order for this `exportUnsampledSpans` option to be useful, the sampler should return `SamplingDecision.RECORD_ONLY` at least some of the time. 

Its not possible (nor is it good design) for the BatchSpanProcessor's configuration to influence the sampling behavior of the SDK, and its the sampling behavior that causes a `PropagatedSpan` to be used.

**Comment by dreedyman** [comment]
@jack-berg Thanks for the info, will lean into getting Sampler configured for my use-case.
