### ISSUE TITLE
Create synchronous gauge meter using java SDK

### ISSUE THREAD

**Issue by iumairhasan** [open-telemetry/opentelemetry-java#6767]
### Issue
I'm trying to create [synchronous double gauge](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#gauge-creation) to record our host metrics (such as container memory usage percent and CPU percent) using java SDK and this defaults to noop double gauge and I do not see metrics in my destination cloudwatch. However, I confirmed that I'm able to create `LongHistogram` using the same opentelemetry meter that exports metrics to my destination cloudwatch location. 

1. Is it possible to create and use synchronous `DoubleGauge`? I see [documents](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#gauge-creation) are out of date compare to methods in [github sdk repo](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics) and looking into [SdkDoubleGauge.java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkDoubleGauge.java) I could not reason it; If I need to look at some other please let me know.
2. Are there any more setup or version setting required before using synchronous gauge metric?

Code snippet on creating both long histogram and double histogram meters - 
```
    Meter meter = getOpenTelemetry.getMeter(MyClass.class.getSimpleName());
..
..
    private LongHistogram getLongHistogramMeter(String meterName, String description, String unit) {
        return meter.histogramBuilder(meterName)
                .setDescription(description)
                .ofLongs()
                .setUnit(unit)
                .build();
    }

    private DoubleGauge getDoubleGaugeMeter(String meterName, String description, String unit) {
        return meter.gaugeBuilder(meterName)
                .setDescription(description)
                .setUnit(unit)
                .build();
    }
```

Output of each meter - 
```
LongHistogramMeter=SdkLongHistogram{descriptor=InstrumentDescriptor{name=my.meter.name, description=My description, unit=my_unit, type=HISTOGRAM, valueType=LONG, advice=Advice{explicitBucketBoundaries=null, attributes=null}}}

DoubleGaugeMeter=io.opentelemetry.api.metrics.DefaultMeter$NoopDoubleGauge@35cec305
```

However, if I create a gauge meter using callback then I can observe output in my exporter

Code snippet for callback - 

```
    meter.gaugeBuilder(MY_METER_NAME)
            .setDescription(MY_METER_DESCRIPTION)
            .setUnit(MY_UNIT)
            .buildWithCallback(measurement -> {
                measurement.record(metricValue, attributes);
            });
```

### Exporter
* I'm exporting my metrics to Cloudwatch using otel collector

### Version 
* I'm using [opentelemetry sdk](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk) version 1.42.1
* Collector - `0.41.0` version of https://gallery.ecr.aws/aws-observability/aws-otel-collector

**Comment by jack-berg** [comment]
What is your value for the gauge `meterName` variable used to initialize the gauge? Do you see any warnings in the log output?

Instrument names must consist of 255 or fewer characters including alphanumeric, _, ., -, /, and start with a letter. There are checks to validate this, and return a noop if invalid.

There's good unit testing to ensure that everything works as expected when the inputs are valid. For example, the following code snippet:
```
    InMemoryMetricReader reader = InMemoryMetricReader.create();
    OpenTelemetry openTelemetry =
        OpenTelemetrySdk.builder()
            .setMeterProvider(SdkMeterProvider.builder().registerMetricReader(reader).build())
            .build();

    DoubleGauge doubleGauge =
        openTelemetry
            .getMeter("meter")
            .gaugeBuilder("gauge")
            .setDescription("description")
            .setUnit("unit")
            .build();

    System.out.println(doubleGauge);

    doubleGauge.set(1.0);
    reader.collectAllMetrics().forEach(System.out::println);
```
Outputs:
```
SdkDoubleGauge{descriptor=InstrumentDescriptor{name=gauge, description=description, unit=unit, type=GAUGE, valueType=DOUBLE, advice=Advice{explicitBucketBoundaries=null, attributes=null}}}
ImmutableMetricData{resource=Resource{schemaUrl=null, attributes={service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.43.0-SNAPSHOT"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=meter, version=null, schemaUrl=null, attributes={}}, name=gauge, description=description, unit=unit, type=DOUBLE_GAUGE, data=ImmutableGaugeData{points=[ImmutableDoublePointData{startEpochNanos=1728403579432006000, epochNanos=1728403579495505000, attributes={}, value=1.0, exemplars=[]}]}}
```

**Comment by iumairhasan** [comment]
Hey Jack, thanks for responding. 

> What is your value for the gauge meterName variable used to initialize the gauge?

I have `metricName=my.metric.name`, example `system.filesystem.mount_point `

> Do you see any warnings in the log output?

No, I don't see any warning or error in log output from/related to open telemetry.


I see that DoubleGauge was added to open telemetry package from `1.38 version` -- [DoubleGauge.java#L15](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/metrics/DoubleGauge.java#L15), can you help me confirm if this is the right maven dependency to use [io.opentelemetry/opentelemetry-sdk](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk/1.42.1) to consume this metric? 

Also, I wanted to confirm if I'm looking at the right place to understand "SDK" references for my code change, because I see the github repository has [SDK](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk) package and another [API](https://github.com/open-telemetry/opentelemetry-java/tree/main/api) package, and I dont see this `1.38` reference in SDK.

**Comment by jack-berg** [comment]
> can you help me confirm if this is the right maven dependency to use [io.opentelemetry/opentelemetry-sdk](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk/1.42.1) to consume this metric?

This is correct.

> Also, I wanted to confirm if I'm looking at the right place to understand "SDK" references for my code change, because I see the github repository has [SDK](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk) package and another [API](https://github.com/open-telemetry/opentelemetry-java/tree/main/api) package, and I dont see this 1.38 reference in SDK.

The API is a set of interfaces for recording telemetry meant to be taken as a dependency by instrumentation libraries. It has zero dependencies and is designed to support alternative implementations. The SDK is the built-in reference implementation of the API, which we recommend for most users. Application owners should take a dependency on the SDK, and configure it to process / export data to suit. 

One key point is we _highly_ recommend using the [opentelemetry BOM](https://github.com/open-telemetry/opentelemetry-java?tab=readme-ov-file#published-releases) to keep dependency versions in sync. It could be that you have a transitive version conflict and are using a newer version of `opentelemetry-api` with an older version of `opentelemetry-sdk`. 

If you're unable to resolve the problem with this info, consider sending a small reproduction of the issue so we can analyze further, or attach a debugger to see why exactly your code is returning a noop gauge.

**Comment by iumairhasan** [comment]
Thanks for the pointers Jack, it looks like the transitive dependency of [opentelemetry-sdk-metrics](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk-metrics) required an update of `1.42.1` version too. I was able to resolve this after upgrading all transitive dependencies.

Updated output - 
```
"LongHistogramMeter=SdkLongHistogram{descriptor=InstrumentDescriptor{name=docker.container.count, description=Number of docker containers running actively in host, unit=count, type=HISTOGRAM, valueType=LONG, advice=Advice{explicitBucketBoundaries=null, attributes=null}}}"

"DoubleGaugeMeter=SdkDoubleGauge{descriptor=InstrumentDescriptor{name=docker.container.memory_usage_percent, description=Memory usage percentage of container, unit=percent, type=GAUGE, valueType=DOUBLE, advice=Advice{explicitBucketBoundaries=null, attributes=null}}}"
```

Appreciate all your help.

**Comment by iumairhasan** [comment]
Thanks for the pointers Jack, it looks like the transitive dependency of [opentelemetry-sdk-metrics](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk-metrics) required an update of `1.42.1` version too. I was able to resolve this after upgrading all transitive dependencies.

Updated output - 
```
"LongHistogramMeter=SdkLongHistogram{descriptor=InstrumentDescriptor{name=metric.name, description= description, unit=unit, type=HISTOGRAM, valueType=LONG, advice=Advice{explicitBucketBoundaries=null, attributes=null}}}"

"DoubleGaugeMeter=SdkDoubleGauge{descriptor=InstrumentDescriptor{name=metric.name, description= description, unit=unit, type=GAUGE, valueType=DOUBLE, advice=Advice{explicitBucketBoundaries=null, attributes=null}}}"
```

Appreciate all your help.
