### ISSUE TITLE
Stabilize `otel.experimental.resource.disabled.keys`

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#6777]
As discussed in this [comment](https://github.com/open-telemetry/opentelemetry-java/issues/6772#issuecomment-2405263383), `otel.experimental.resource.disabled.keys` has been experimental for a while - introduced in #4169 on 2/17/2022. 

It seems both important and correctly modeled. We should stabilize it.

**Comment by trask** [comment]
just want to confirm that we are ok with expanding the surface area of stable env var / system properties given that they won't be compatible with the upcoming configuration v2 (declarative configuration)?

https://github.com/open-telemetry/opentelemetry-configuration/blob/844869c2eb37a07ff6471923b3c0488078840bd5/examples/kitchen-sink.yaml#L368

**Comment by jack-berg** [comment]
These properties are around to stay, even if there's an alternative recommended approach. I'm reluctant to expand the surface area, but don't consider promotion to stable an expansion.

**Comment by vasantteja** [comment]
Can I work on this?

**Comment by jack-berg** [comment]
Sure - I've assigned you. 

Quick note: we'll want to retain support for `otel.experimental.resource.disabled.keys` for at least 1 minor release cycle, but warn if we see it. Pseudocode is something like:
```
List<String> disabledKeys = configProperties.getList("otel.resource.disabled.keys");
if (disabledKeys.isEmpty()) {
  disabledKeys = configProperties.getList("otel.experimental.resource.disabled.keys");
  if (!disabledKeys.isEmpty()) {
     // log warning
  }
}
```
