### ISSUE TITLE
JApiCmp Failure in setting up opentelemetry-java locally

### ISSUE THREAD

**Issue by Annosha** [open-telemetry/opentelemetry-java#6789]
**Describe the bug**
Followed the instructions in CONTRIBUTING.md, [Composing builds](https://github.com/open-telemetry/opentelemetry-java/blob/main/CONTRIBUTING.md#composing-builds) installed following pre reqs:
Generated build substitutions and pasted them in settings.gradle.kts

**Steps to reproduce**

1. cloned the repo
2. ./gradlew build 
Gave following error:
```> Task :api:all:jApiCmp FAILED

> Task :exporters:prometheus:test

PrometheusHttpServerTest > fetch_DuplicateMetrics() STANDARD_ERROR
    [prometheus-http-2-1] WARN io.opentelemetry.exporter.prometheus.Otel2PrometheusConverter - Conflicting metrics: Multiple metrics with name foo_unit but different units found. Dropping the one with unit null.

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

> Task :exporters:prometheus:test

PrometheusMetricReaderProviderTest > createMetricReader_WithConfiguration() FAILED
    org.assertj.core.error.AssertJMultipleFailuresError:
    [Extracted: httpServer] (1 failure)
    -- failure 1 --
    expected: "localhost"
     but was: "kubernetes.docker.internal"
    at PrometheusMetricReaderProviderTest.lambda$createMetricReader_WithConfiguration$1(PrometheusMetricReaderProviderTest.java:99)
        at app//io.opentelemetry.exporter.prometheus.internal.PrometheusMetricReaderProviderTest.createMetricReader_WithConfiguration(PrometheusMetricReaderProviderTest.java:97)

114 tests completed, 1 failed, 1 skipped

> Task :exporters:prometheus:test FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':api:all:jApiCmp'.
> A failure occurred while executing me.champeau.gradle.japicmp.JApiCmpWorkAction
   > Detected binary changes.
         - current: opentelemetry-api-1.43.0-SNAPSHOT.jar
         - baseline: opentelemetry-api-1.43.0.jar.

     See failure report at file:///C:/Users/Aman/Desktop/java/opentelemetry-java/api/all/build/reports/rich-report.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':exporters:prometheus:test'.
> There were failing tests. See the report at: file:///C:/Users/Aman/Desktop/java/opentelemetry-java/exporters/prometheus/build/reports/tests/test/index.html
==============================================================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 52s
476 actionable tasks: 130 executed, 199 from cache, 147 up-to-date`
```

**What did you see instead?**
![buildfail1](https://github.com/user-attachments/assets/02f9b644-5235-4cb3-9136-1017da5c03ca)

**Environment**
Compiler:  openjdk 17.0.12
OS: Microsoft Windows 10 Pro
Docker up and running too

**Additional context**
1. Build log suggest JApiCmp Failure. Shall I go for backward compatibility?  Or I need to update the baseline version for API? (Which one is recommended for a beginner?) Is this step the right one to tackle the compatibility issue? 
2.  Prometheus Exporter Test Failures:  relate to the fetch_DuplicateMetrics() and createMetricReader_WithConfiguration() tests.
The test report located at _opentelemetry-java/exporters/prometheus/build/reports/tests/test/index.html_ has:
![binaryCompReport](https://github.com/user-attachments/assets/91adc93b-0652-4de3-af0e-00f8d876110a)

 Here is the log for running test in isolation:
```
 `./gradlew :exporters:prometheus:test --info
`
`> Task :exporters:prometheus:test

114 tests completed, 1 failed, 1 skipped
Finished generating test XML results (0.031 secs) into: C:\Users\Aman\Desktop\java\opentelemetry-java\exporters\prometheus\build\test-results\test
Generating HTML test report...
Finished generating test html results (0.053 secs) into: C:\Users\Aman\Desktop\java\opentelemetry-java\exporters\prometheus\build\reports\tests\test

> Task :exporters:prometheus:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':exporters:prometheus:test'.
> There were failing tests. See the report at: file:///C:/Users/Aman/Desktop/java/opentelemetry-java/exporters/prometheus/build/reports/tests/test/index.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 9s
66 actionable tasks: 3 executed, 63 up-to-date
```

**Comment by shalk** [comment]
i do not think the project can not pass the test on windows. 

It is your env problem not a bug.

**Comment by Annosha** [comment]
@shalk Perhaps that's the case. Can we move this issue to Questions? 
Do you have any hints to where I should be looking to debug the issue?

**Comment by trask** [comment]
hi @Annosha!

I can confirm that `./gradlew :exporters:prometheus:test` fails for me on windows as well

instead of `./gradlew build`, I typically run `./gradlew assemble` (or ./gradlew publishToMavenLocal depending on my needs)

**Comment by Annosha** [comment]
@shalk Thank you for your helping. Env on my system is in place with this repo. with all the required pre-reqs and dependencies.  Perhaps we should add about failing tests on win in CONTRIBUTING.md or README.md. (I've spent quite sometime troubleshooting, as this may not be welcoming for new contributors)
May I ask why they not pass on windows?  

@trask thank you for suggesting the command I wonder why the tests fail? Do you want to anything to add!

**Comment by shalk** [comment]
I know the code can pass macos and ubuntu.  But I do not know the reason for not pass on windows.
I see you have cross all language code base.
For a experienced java developer , it is not easy to setup this code base. Have fun!

**Comment by Annosha** [comment]
@shalkI believe it would be beneficial to include a note in the CONTRIBUTING.md regarding the potential for test failures on Windows, to improve clarity and make the documentation more beginner-friendly.
