### ISSUE TITLE
sdk unexpectedly extract log data

### ISSUE THREAD

**Issue by howan36** [open-telemetry/opentelemetry-java#6846]
{
    "@timestamp": "2024-11-03T01:19:54.333781834+08:00",
    "@version": "1",
    "message": "200 OK GET https://api-dev-mpp.xxxx.cn/api/routes/updatedAt",
    "logger_name": "org.zalando.logbook.Logbook",
    "thread_name": "reactor-http-epoll-4",
    "level": "TRACE",
    "level_value": 5000,
    "http_request": Object{...},
    "http_response": Object{...}
}

the log from my container stdout is like above, but data in grafana loki only has message field content,
like:  timestape 200 OK POST https://api-dev-mpp.xxxx.cn/api/routes/updatedAt, others are missing

i am not sure how to change this default extract behaviour of java otel sdk

**Comment by jkwatson** [comment]
I don't think this is an SDK issue, but an instrumentation issue. What logging framework are you using, and how is it being configured? Are you using the javaagent, or some other way of getting log instrumentation?

**Comment by howan36** [comment]
i use the opentelemetry operator instrumentation way to inject sdk, and use logback framework

**Comment by howan36** [comment]
no special config for logback, just print the request and response message, and some tracing data, like trace_id

**Comment by trask** [comment]
closing this one, let's continue discussion in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/12573
