### ISSUE TITLE
Add convenience method `setAttribute(Attribute<Long>, int)` to SpanBuilder (matching the existing convenience method in Span)

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#6870]
It would be nice if SpanBuilder had the same `setAttribute(AttributeKey<Long> key, int value)` convenience method as Span:

https://github.com/open-telemetry/opentelemetry-java/blob/6c0d140dff4b5fd6e168e6b6a65edf4cf73c7571/api/all/src/main/java/io/opentelemetry/api/trace/Span.java#L169-L171

**Comment by Stoyas** [comment]
trying to work on it
