### ISSUE TITLE
Create a FAQ file

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#688]
Today in our SIG call there was a question regarding why `Span` does not implement the `Closeable` interface, which has a reason but is not so obvious. Because of this, it would be nice to have a FAQ with common questions/issues.

**Comment by almarksismah** [comment]
Hey, I just signed the petition "all netizens of the world: FREE CHEN QIUSHI AND FANG BIN！" and wanted to see if you could help by adding your name. Our goal is to reach 100 signatures and we need more support. You can read more and sign the petition here: http://chng.it/KzzgkGLmQ9 Thanks!

**Comment by almarksismah** [comment]
Hey, I just signed the petition "all netizens of the world: FREE CHEN QIUSHI AND FANG BIN！" and wanted to see if you could help by adding your name. Our goal is to reach 100 signatures and we need more support. You can read more and sign the petition here: http://chng.it/KzzgkGLmQ9 Thanks!

**Comment by almarksismah** [comment]
Hey, I just signed the petition "all netizens of the world: FREE CHEN QIUSHI AND FANG BIN！" and wanted to see if you could help by adding your name. Our goal is to reach 100 signatures and we need more support. You can read more and sign the petition here: http://chng.it/KzzgkGLmQ9 Thanks!

**Comment by almarksismah** [comment]
Hey, I just signed the petition "all netizens of the world: FREE CHEN QIUSHI AND FANG BIN！" You can read more and sign the petition here: http://chng.it/KzzgkGLmQ9 Thanks!

**Comment by andrewhsu** [comment]
From the sig mtg today, if doesn't go in with this milestone, will carry over to next.

**Comment by arminru** [comment]
@carlosalberto The reason for Span not being Closeable is, for example, illustrated here: https://github.com/opentracing/opentracing-java/issues/361#issuecomment-542660304
