### ISSUE TITLE
TraceId.getLowerLong returns idHi

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#690]
See the following code:

https://github.com/open-telemetry/opentelemetry-java/blob/9afb1e405919f7516f2af8e27e65546a5abe7866/api/src/main/java/io/opentelemetry/trace/TraceId.java#L213-L214

It seems this should use `idLo` instead of `idHi` to match the method name.

**Comment by thisthat** [comment]
I think the problem is not the implementation but the naming of the method. My suggestion is to rename it using the keyword *leftmost* following the suggestion of @c24t in [PR 331](https://github.com/open-telemetry/opentelemetry-specification/pull/331#issue-330774237)

**Comment by bogdandrutu** [comment]
This is closed and the new method was added `getTraceRandomPart`
