### ISSUE TITLE
Provide usage examples

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#692]
We should add samples for using OpenTelemetry Java to make it easier for beginners to get a feeling of how to use the API properly.
OpenCensus had examples included right in the repo and so do OTel [Python](https://github.com/open-telemetry/opentelemetry-python/tree/master/examples), [JS](https://github.com/open-telemetry/opentelemetry-js/tree/master/examples), [Go](https://github.com/open-telemetry/opentelemetry-go/tree/master/example) and [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/samples).

**Comment by thisthat** [comment]
I can take care of it!

**Comment by arminru** [comment]
Should we make the examples a subproject which breaks the build if the API is changed without updating the examples accordingly?

Having the examples as standalone projects which reference OTel via Maven makes more sense for users looking at them but this way they're more likely to get outdated if no one cares to update them regularly.

**Comment by carlosalberto** [comment]
> Should we make the examples a subproject which breaks the build if the API is changed without updating the examples accordingly?

I personally like this, as otherwise it would be *very* easy to forget about them ;)

**Comment by bogdandrutu** [comment]
I think we have the first set of examples, we should file more granular issues if we need more examples.
