### ISSUE TITLE
Enable integration with AWS Cloudatch via new OTLP endpoint

### ISSUE THREAD

**Issue by shorn** [open-telemetry/opentelemetry-java#6979]
**Is your feature request related to a problem? Please describe.**
Send traces to AWS.

**Describe the solution you'd like**
Want to send traces to AWS using the SDK - do not want to use AWS ADOT or any other collector process.

**Describe alternatives you've considered**
No way to do it as far as I know.
Possibly I could write a custom span exporter that does AWS Sigv4 signing?  Not sure.

**Additional context**
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-OTLPEndpoint.html
e.g. `https://xray.us-east-1.amazonaws.com/v1/traces`

I don't use the java agent, I use the SDK directly to export traces.  
The SDK currently works fine with OTLP compatible products like NewRelic and GrafanaCloud, using a simple `api-key` or `Authorization` header.

But not with AWS' OTLP endpoint.

If I do this:
```
      var spanExporter = OtlpHttpSpanExporter.builder().
        setEndpoint(xray.url()).
        build();

      config.addSpanProcessor(BatchSpanProcessor.builder(spanExporter).
        setMaxQueueSize(xray.maxQueueSize()).
        setMaxExportBatchSize(xray.maxBatchSize()).
        setScheduleDelay(xray.scheduleDelay()).
        setExporterTimeout(xray.exportTimeout()).
        build()
      );
```

It will fail with: 
```
Dec 21, 2024 3:34:00 AM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export spans. Server responded with HTTP status code 403. Error message: Missing Authentication Token
```

As far as I know, there is no concept of an "Authentication token" that you create on the AWS side (like NewRelic and GrafanaCloud) and they're actually expecting the client will sign each HTTP request AWS SigV4:
https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

**Comment by jkwatson** [comment]
My suggestion is that someone build the custom exporter (or a wrapper for the existing OTLP exporters) using the AWS SDK in the opentelemetry-java-contrib project. Since this isn't an officially defined exporter in the OpenTelemetry specification, it's most-likely not something we would support in the core repository.

**Comment by shorn** [comment]
Ok - so closed as WON'T FIX?
