### ISSUE TITLE
Confusing naming around "Bound"

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#705]
The metrics API has (at least 😄) two things that confuse me:
* It often talks about "a Bound" which would be "a Boundary" to me, not "a bound instrument"
* The function `unbind(BoundFoo)` is confusing. After calling that function, do I have an unbound BoundFoo? Maybe `removeBoundInstrument` would be a better name (or `BoundFoo.close`).

**Comment by jkwatson** [comment]
Yes, I want to get rid of "bound" as a noun, and make sure it's always being used as an adjective. This is on my very near-term radar (like, this week). 

How about `release(BoundFoo)` ?

**Comment by jkwatson** [comment]
Hi @Oberon00 . I'm also confused by the current shape of the metrics API. I think it needs a major re-think before 1.0, because I don't think that it is very usable or discoverable as it is right now. I also don't think it's actually meeting the spec, either (especially around non-bound-instrument usage).

**Comment by jkwatson** [comment]
See #711 for the issue to get the non-bound-instrument calling convention added to the API.

**Comment by jkwatson** [comment]
see #717 for a bunch more cleanup that should help with this.

**Comment by jkwatson** [comment]
@Oberon00 Are things looking better now? Can we close this with the various cleanup I did?

**Comment by Oberon00** [comment]
Looks much better now, but GitHub search still turns up a few instances in test code, like https://github.com/open-telemetry/opentelemetry-java/blob/91053c45c8432ce29111e7883fa7ce03f189c6bf/api/src/test/java/io/opentelemetry/metrics/LongGaugeTest.java#L107

**Comment by jkwatson** [comment]
Got it. I'll get to this soonish.
