### ISSUE TITLE
No way to change HttpTextFormat

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#718]
There is no way to change the HttpTextFormat in the `TracerSdk`.

https://github.com/open-telemetry/opentelemetry-java/blob/a8d14d8886c7359705710d92e4679b80f8514e93/sdk/src/main/java/io/opentelemetry/sdk/trace/TracerSdk.java#L34

I know this will probably be reworked with #655 or https://github.com/open-telemetry/oteps/pull/66 but honestly, these look like mid- to long-term projects. So in the meantime it would be great to have a setter for the HttpTextFormat (and probably the BinaryFormat).

**Comment by carlosalberto** [comment]
Now that OTEP 66 has been merged, I'd expect the related changes to land relatively soon :)

**Comment by carlosalberto** [comment]
This can now be set through `OpenTelemetry.setPropagators()` ;)
