### ISSUE TITLE
Remove @VisibleForTesting getters from RERSpan and use toSpanData in tests instead?

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#719]
As noted by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-java/pull/706#discussion_r359499162 and https://github.com/open-telemetry/opentelemetry-java/pull/706#discussion_r359499245: We could remove the `@VisibleForTesting` getters from `RecordEventsReadableSpan` if we used `toSpanData` instead in unit tests.

**Comment by jkwatson** [comment]
Note: while working on this, I found there are also some unused pieces of data in the RERSpan that are being exposed only for testing. I'm planning on removing that data; we can add it back if we end up with a use case for it.
