### ISSUE TITLE
Should setAttribute() on an ended span throw an exception?

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-java#774]
Currently, setting an attribute on an ended span fails silently. I would argue that this should throw an exception instead, since you're attempting an operation in a state where it's invalid.

Suggestion: Throw an exception when ```Span::setAttribute()``` is called on an ended span.

**Comment by carlosalberto** [comment]
I'd be up against that, as we are trying to avoid throwing errors as part of instrumentation, unless it's a fatal error.

I.e. instrumentation should **not** raise errors in the actual application ;)

**Comment by prydin** [comment]
Yeah, I know I argued the opposite position earlier today. :) But in this particular case, I think that setting attributes on an ended span indicates that someone is doing something very wrong. (I know I was when I came across this).

But there's a reason I put a question mark at the end of the title. I'm not sure myself. But I think it would be a good idea to try to draw the line what we consider a benign condition (such as an attribute being null) and something being broken.

**Comment by bogdandrutu** [comment]
I think it is probably useful to support a "debug" level for the SDK where we may throw exception there or simply log error with stacktrace to see where that happens.

**Comment by jkwatson** [comment]
Interesting idea, @bogdandrutu . Kind of like turning on java assertions? Or, we could put java assertions in the code and you could run with assertions turned on?

**Comment by trask** [comment]
+1 for just logging it at debug level with stack trace

**Comment by carlosalberto** [comment]
+1 for logging as well.

**Comment by jkwatson** [comment]
The SDK is already logging this at FINE. Should we add logging to the API DefaultSpan as well, to potentially catch it at instrumentation time? Also, is FINE the right log level?

**Comment by Oberon00** [comment]
I think the API default span should not even (need to) know whether it is ended. It should be optimized for as little overhead as possible.

**Comment by carlosalberto** [comment]
Although I'd like to see logging at the `DefaultTracer` implementation, I also think we should have as little overhead as possible there. So, in my opinion, having logging in the SDK is enough.

**Comment by jkwatson** [comment]
ok, is FINE good enough for the SDK logging? If so, then we can close this issue.

**Comment by jkwatson** [comment]
closing since it looks like the implementation is FINE for now

**Comment by apanasevich** [comment]
Hi there!
Found this issue but cannot find a way to enable SDK logging. I run my app with parameter -Dotel.javaagent.logging=application. Tried to set envvar OTEL_LOG_LEVEL to OTEL_LOG_LEVEL=FINE or OTEL_LOG_LEVEL=DEBUG but with no luck. What is the correct way to enable FINE logging?

**Comment by jack-berg** [comment]
The SDK uses JUL for logging, so you can either directly configure JUL or configure JUL logs to bridge to SLF4J and configure logback / log4j / etc. For the logs discussed in this issue, the name of the [logger](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpan.java#L40) is `io.opentelemetry.sdk.trace.SdkSpan`.

**Comment by apanasevich** [comment]
@jack-berg Thanks a lot for such a detailed answer!
