### ISSUE TITLE
Jaeger example not working

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#775]
Using the Jaeger example to send traces provides nothing. Inspecting the docker logs, I got this:

```sh
WARNING: 2020/01/18 04:15:55 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: \"\\x16\\x03\\x01\\x00\\x82\\x01\\x00\\x00~\\x03\\x03Gj\\x92m\\x81\\x94\\x0e\\xfd\\aH\\xcb\\xd0\\xe7\""

```

@thisthat

**Comment by thisthat** [comment]
Also on gitter another user had problem with Jaeger locally. I'll update the example removing the encryption on the channel (this was the fix).
