### ISSUE TITLE
Java project status isn't updated properly because milestones aren't correct

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-java#780]
👋 Howdy, just a little housekeeping note, but I've had people contact me with questions as to why Java progress seems so far behind on the project status page (https://opentelemetry.io/project-status/). You can find out how to align your milestones with the project status page in this issue: https://github.com/open-telemetry/community/issues/201

**Comment by AdrianSchneble** [comment]
I was about to open an issue about the same topic, but apparently, you beat me to it. Judging by the [latest (and only) release of this repo](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v0.2.0), the project should be marked as "v0.2.0" in the overview page.

I'm not sure what the difference between - for instance - [the python reference implementation ](https://github.com/open-telemetry/opentelemetry-python/releases/tag/v0.2.0) or this project is, except that the python project includes release notes and is marked as "pre-release".
This project's release matches the required naming pattern "v0.2", and from what I can tell, the [entry in progress_source.yaml](https://github.com/open-telemetry/opentelemetry.io/blob/master/data/progress_source.yaml#L41) is correctly formatted.

**Comment by austinlparker** [comment]
The project status tracker actually derives its information from the GitHub milestones. The release notes on the status page are pulled from GitHub releases. If you look at the Python milestones (https://github.com/open-telemetry/opentelemetry-python/milestones) you'll see that they're working towards 0.4, so the tracker indicates them as being between 0.3 and 0.4.

**Comment by anuraaga** [comment]
Hey - I checked https://opentelemetry.io/project-status/ and see release notes but don't see any milestones. Are they still published? Or if not, are we good with closing this issue? Happy to help if anything's needed just not sure what that is right now.

**Comment by jkwatson** [comment]
> Hey - I checked https://opentelemetry.io/project-status/ and see release notes but don't see any milestones. Are they still published? Or if not, are we good with closing this issue? Happy to help if anything's needed just not sure what that is right now.

@austinlparker ping! Yes, looks like maybe we can close this issue.

**Comment by jkwatson** [comment]
@austinlparker closing. Please re-open if you think there's still an issue.

**Comment by austinlparker** [comment]
Whoops, I totally missed this. Yeah we stopped publishing that table, so this is fine to stay closed.
