### ISSUE TITLE
API: Make SpanContext.getInvalid() public

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#787]
For Propagators and other components returning invalid `SpanContext` instances it would be handy to share the `SpanContext.getInvalid()` instance, which is currently private.

If I remember correctly, there were a few reasons having keeping it private, mostly around users not abusing it. Do we want to change this?

(Observe this would be mostly an optimization. **Any** `SpanContext` can be created and users can check its `getValid()` method. On the other hand, `TraceId` and `SpanId` do expose their invalid instances).

See #767 for example.

**Comment by DotSpy** [comment]
Trace id and span id now exposing invalid states they have
```
  public static SpanId getInvalid() {
    return INVALID;
  }
```
for now ```SpanContext.getInvalid()``` just wrapping all public methods
```
  private static final SpanContext INVALID =
      create(
          TraceId.getInvalid(),
          SpanId.getInvalid(),
          TraceFlags.getDefault(),
          TraceState.getDefault());
```
so no harm for current state of project to make it public, otherwise ```TraceId.getInvalid()``` and ```SpanId.getInvalid()``` should be protected\private too

**Comment by jkwatson** [comment]
complete with #896
