### ISSUE TITLE
Benchmark usage of the SpanContext

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#792]

**Comment by DotSpy** [comment]
@jkwatson can u provide more details about it? I would like to help with it

**Comment by jkwatson** [comment]
@DotSpy I think part of this issue is to dig into the SpanContext and figure out what might need some benchmarking. I haven't had time to dig into it myself. Are you up for doing some of that digging and making some benchmark recommendations that could be built?

**Comment by DotSpy** [comment]
Yeap, i will dig and ask questions during investigation, if all go right i will be able to switch to another tasks with benchmarks. Do we have restrictions for frameworks that i can use for it?

**Comment by DotSpy** [comment]
Also i saw some benchmarks in opentelemetry-js project, i will ask guys there

**Comment by jkwatson** [comment]
There's a pending PR to use JMH for the benchmarking (#678). I think we should stick with that.

**Comment by DotSpy** [comment]
@jkwatson  Assign me to this one please

**Comment by DotSpy** [comment]
I did main PR benchmarks for context, for beta i think it's okay and we need to find some hardware on which we can run it to make measurements stick to it. So after we will be able to improve performance and write more specific benchmarks for context. @jkwatson what do u think is it possible to find such hardware?

**Comment by jkwatson** [comment]
I think we'd need to lean on our friends in the CNCF to see if we can get a benchmarking platform. Not sure who can drive this. @bogdandrutu maybe?

**Comment by jkwatson** [comment]
Is there anything further we'd like to benchmark around the SpanContext itself, @carlosalberto ?
