### ISSUE TITLE
Verify naming of things matches the specification

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#794]
(note: probably the registries aren't matching this now)

**Comment by thisthat** [comment]
I'd like to do this :wink:

**Comment by jkwatson** [comment]
assigned!

**Comment by thisthat** [comment]
Upon #870, #872, #878, #879, #882, and #883 are either closed or merged, we can close this issue.

**Comment by bogdandrutu** [comment]
#878 is closed as obsolete after the specification change
