### ISSUE TITLE
Create examples of configuring the SDK and using it

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#795]
We'd like some more full-featured example code to make it easy for people to get started using OTel.

Here's what I'd like to see in this example:
* Configuring sampling
* Choosing a built-in span processor and adding an exporter to it.
* Shutting down the span processor when exiting.

**Comment by thisthat** [comment]
When I started to look into OTel, I wrote some notes for myself that I can extend to prepare a Quick Start document.

**Comment by jkwatson** [comment]
Fantastic, @thisthat . I'll assign this to you for now, then.

**Comment by thisthat** [comment]
Was this addressed in #869 or should I add a concrete example in the examples folder?

**Comment by jkwatson** [comment]
Would love some actual compiling code examples that people could run, so, 👍 on having concrete examples.

**Comment by jkwatson** [comment]
@thisthat I updated the description of this issue. Please let me know if it's not clear.

**Comment by thisthat** [comment]
Thank you @jkwatson! Everything is clear!
