### ISSUE TITLE
Implement remotely configurable sampling for Jaeger exporter

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#796]
details needed on what this entails....

**Comment by pavolloffay** [comment]
@jkwatson @carlosalberto  please provide more details in the description.

**Comment by carlosalberto** [comment]
Details to be found in https://github.com/open-telemetry/opentelemetry-specification/issues/231

**Comment by carlosalberto** [comment]
@pavolloffay Details are kinda spread that issue. Let me know what you think.

**Comment by objectiser** [comment]
Shouldn't this issue be entitled "Implement remotely configurable sampling" or something like that, and aim to provide a similar (i.e. functionally equivalent) mechanism as used in Jaeger - but applicable for any exporter used by the client?

cc @yurishkuro

**Comment by pavolloffay** [comment]
The sampling strategy is served by collector gRPC endpoint. Here is the proto definition https://github.com/jaegertracing/jaeger/blob/master/model/proto/api_v2/sampling.proto#L85

* RemoteSampler in Jaeger client: https://github.com/jaegertracing/jaeger-client-java/blob/46798bdf199357afc535c98b8f6734b37090bf78/jaeger-core/src/main/java/io/jaegertracing/internal/samplers/RemoteControlledSampler.java#L36
* JSON model https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/samplers/http/SamplingStrategyResponse.java
* add serving of Jaeger sampling JSON to OTEL collector https://github.com/open-telemetry/opentelemetry-collector/pull/547

**Comment by pavolloffay** [comment]
I have started looking into this. In Jaeger this is implemented in this package https://github.com/jaegertracing/jaeger-client-java/tree/46798bdf199357afc535c98b8f6734b37090bf78/jaeger-core/src/main/java/io/jaegertracing/internal/samplers.

It actually requires these classes: `RemoteControlledSampler`. `RateLimitingSampler`, `PerOperationSampler`, `GuaranteedThroughputSampler`.

I am wondering whether it would be better to depend on `jaeger-core` artifact https://mvnrepository.com/artifact/io.jaegertracing/jaeger-core/1.2.0 and just create the adapter for `RemoteControlledSampler`. 

@bogdandrutu any concerns on depending on `jaeger-core`?

**Comment by yurishkuro** [comment]
My preference would be for OTel to be a clean cut, not to bundle Jaeger.

Also, Jaeger sampling is upfront, I don't understand how it can be done in the exporter.

**Comment by pavolloffay** [comment]
It won't be in the exporter. It will be OTEL sampler implementation, we should decide whether it will be located in the same package as Jaeger exporter or a different one.
