### ISSUE TITLE
Create Jaeger "helper function" to create the export pipeline.

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#797]

**Comment by pavolloffay** [comment]
@jkwatson @carlosalberto  please provide more details in the description.

**Comment by carlosalberto** [comment]
From the last meeting, it was mentioned that details should be found in: https://github.com/open-telemetry/opentelemetry-specification/issues/231

**Comment by carlosalberto** [comment]
It sounds this is the specific part @pavolloffay 

> One missing functionality is the ability to configure the client via environmental variables https://www.jaegertracing.io/docs/1.13/client-features/. This was proven to be useful for cloud/containerized deployments.

**Comment by bogdandrutu** [comment]
I think we should have a method like:
```java
void installDefaultJaegerExporter(TraceProviderSdk traceProviderSdk) {
  // Creates the exporter
  // Configures default values for batch SpanProcessor and installs the exporter to it. If you want by default to use Disruptor async SpanProcessor, configure and install that as well
  // Installs the default configured SpanProcessor to the traceProviderSdk.
}
```

This is to simplify user life when it comes to configure Jaeger, they should not have to configure all batching etc just to get things running (they can do the advanced config if needed).

**Comment by bogdandrutu** [comment]
@pavolloffay for example even in our examples https://github.com/open-telemetry/opentelemetry-java/blob/master/examples/jaeger/src/main/java/io/opentelemetry/example/JaegerExample.java#L28 we do create a poor export pipeline that exports spans one by one, that method should be replaced by this method that needs to be implemented.
