### ISSUE TITLE
Create an example of how to configure sampling and limits for the Tracer SDK

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#798]

**Comment by thisthat** [comment]
I can work on this!

**Comment by jkwatson** [comment]
excellent. assigning it to you, @thisthat

**Comment by thisthat** [comment]
Was this addressed in #869 or should I add a concrete example in the examples folder?

**Comment by jkwatson** [comment]
My opinion, but compiling code examples are very nice to have, beyond just the quick start guide. So, 👍 for more examples.

**Comment by thisthat** [comment]
We can close this issue. It was resolved as part of #1003
