### ISSUE TITLE
Set up CNCF CLA for this project

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-java#8]
* If we want to move this codebase into the CNCF, committers need to sign a CLA
* Users can't sign a CLA because we're not in the CNCF yet 
* So we cannot accept 3rd party PRs until the CNCF acceptance process is complete.
* Once we have a project name, github org, etc, we can start accepting PRs
* We can still accept comments and suggestions.

TODO: Mention this situation in the README.

**Comment by tylerbenson** [comment]
I think this might be done...  New PRs seem to have the CLA check.
