### ISSUE TITLE
Implement array (list) span attributes (spec#368)

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#801]
https://github.com/open-telemetry/opentelemetry-specification/pull/368 was merged but is not implemented in opentelemetry-java yet. Relevant wording change:

> - (Required) The attribute value, which is either:
>   - A primitive type: string, boolean or numeric.
>   - An array of primitive type values. The array MUST be homogeneous,
>     i.e. it MUST NOT contain values of different types.

**Comment by arminru** [comment]
@thisthat

**Comment by thisthat** [comment]
I am preparing a PR for this

**Comment by matt-debug** [comment]
Fixed it boss

**Comment by thisthat** [comment]
Pending on https://github.com/open-telemetry/opentelemetry-specification/pull/459

**Comment by thisthat** [comment]
After #807 is merged, we can close this issue!
