### ISSUE TITLE
Should @Trace annotation be part of the API?

### ISSUE THREAD

**Issue by safris** [open-telemetry/opentelemetry-java#813]
In a previous Auto-instrumentation SIG, we discussed the question:

> Where should DataDog's `@Trace` annotation live?
> **Does it make sense for the `@Trace` annotation to be part of the OpenTelemetry API?**

My superficial evaluation of the pros and cons for the `@Trace` annotation to be part of the OpenTelemetry API:

**Pros**

1. The `@Trace` annotation is a <ins>common and well-established</ins> pattern for manual instrumentation of Java code, and such an annotation seems appropriate for OpenTelemetry.

1. Tracing frameworks, such as [Stackify](https://github.com/stackify/stackify-java-apm-annot#trace-annotation), [NewRelic](https://docs.newrelic.com/docs/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation), [SignalFx](https://docs.signalfx.com/en/latest/apm/apm-instrument/apm-java.html#trace-annotation) and [MagicTest](http://www.magicwerk.org/page-magictest-reference.html), as well as application frameworks such as [Spring GemFire](https://docs.spring.io/spring-gemfire/docs/current/reference/html/#gemfire-repositories.queries.oql-extensions) and [JBoss](https://docs.jboss.org/jbossaop/docs/2.0.0.GA/docs/aspect-framework/examples/metadata/metadata.html) have their own `@Trace` annotation. User code that includes these framework-specific `@Trace` annotations become coupled to the particular frameworks.

   With a `@Trace` annotation defined in the OpenTelemetry API, the user code <ins>relinquishes its coupling to particular frameworks</ins>.

1. Auto-instrumentation agents do not need to define their own `@Trace` annotation. If the OpenTelemetry API chooses to not provide a `@Trace` annotation, the long-term outcome will be a general increase of framework-specific `@Trace` annotations in the ecosystem of tracing, telemetry and testing. If the OpenTelemetry API provides a `@Trace` annotation, <ins>the long-term outcome will be a general reduction of framework-specific `@Trace` annotations</ins>.

**Cons**

1. The `@Trace` annotation would need to be architected to cover a comprehensive set of use-cases for which this annotation is currently commonly used. The `@Trace` annotation would need to have attributes that allow the user particular controls over the context that is intended to be traced. This consideration would need further analysis in order to clearly define the goals and non-goals of such an annotation in OpenTelemetry. <ins>The `@Trace` annotation would broaden the surface area of APIs requiring support from OpenTelemetry.</ins>

1. <ins>The `@Trace` annotation would not be functionally meaningful insofar as manual instrumentation with OpenTelemetry is concerned.</ins> As per the architecture of annotations in Java, annotations are "annotations", as opposed to "actions". Code that is annotated does not inherently result in actions to be performed via the annotations. Such functionality would require higher-level technologies to interpret the `@Trace` annotation and thereafter execute the actions -- frameworks such as Spring, AspectJ, etc, or agents like NewRelic, DataDog, etc provide such functionality.

I would like to hear thoughts and concerns from others on this topic!

**Comment by pavolloffay** [comment]
`@Trace` annotation is also defined in MicroProfile-OpenTracing (`@Traced`) https://github.com/eclipse/microprofile-opentracing/blob/master/api/src/main/java/org/eclipse/microprofile/opentracing/Traced.java.

**Comment by AdrianSchneble** [comment]
I'm not involved in the development of OpenTelemetry, but at work, me and a colleague recently implemented OpenTracing support for an internal UI framework.
We would most definitely want an `@Trace` annotation in our project, and if it's not provided by OpenTelemetry, we would have to develop one ourselves or use an implementation by some open source project. In fact, I had already implemented one myself, but had to deactivate it again due to project-internal reasons (unrelated to using an annotation in general).
In any case, a built-in `@Trace` annotation would be greatly appreciated :)

**Comment by andrewhsu** [comment]
From the SIG mtg, sounds like this would be best to be put in the `contrib`.

**Comment by iNikem** [comment]
I find the name of this annotation very unfortunate. It does not denote `Trace` in Otel terms, but `Span`. Are we sure we want to follow the industry de facto standard and to confuse future users?

**Comment by carlosalberto** [comment]
@iNikem I don't think we are married to this name yet. Any suggestions on this? If we found a better alternative, we can definitely use such.

**Comment by iNikem** [comment]
@carlosalberto Probably something along the lines of `@WithSpan`, `@AsSpan` or `@NewSpan`? It should denote that this method invocation will result in creation of new span. Or that it is "wrapped" in a span.

**Comment by iNikem** [comment]
Spring Sleuth uses `@NewSpan`. I think this is my favourite option at the moment.

**Comment by trask** [comment]
I like both `@NewSpan` and `@WithSpan`. I'm not opposed to `@Trace` either, but can see the confusion between trace (verb) and trace (noun).

**Comment by iNikem** [comment]
I am quite new here, so my understanding may be a naive one. But it seems to me that first steps are obvious and not very complicated:

1. Add new annotation `NewSpan` to Otel-java contrib.
2. Teach otel-java-auto-instrumentation to create new spans whenever `NewSpan` annotation is found. This means simply extending the list of support annotations in https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/f958c2df2de7bf5393bba70de074be7fc1caed97/instrumentation/trace-annotation/src/main/java/io/opentelemetry/auto/instrumentation/traceannotation/TraceAnnotationsInstrumentation.java#L51
3. Next start composing ideas about what possible attributes we need on that annotation. Two obvious candidates are operation name and list of ignored exceptions.

If such gradual plan is acceptable, I can start working on it. Does it require some kind of more formal proposal/written plan or something?

**Comment by johnbley** [comment]
@iNikem that plan looks good to me. I'll throw in my vote for `@NewSpan` sounding good enough.  Other possibilities might be `@CreateSpan` or `@BuildSpan` (to match the Span.Builder verbiage).

**Comment by carlosalberto** [comment]
I'd personally prefer `@WithSpan` a little bit more. My two cents ;) 

@tylerbenson Any opinion on this?

**Comment by andrewhsu** [comment]
from the java sig mtg today, notes:
https://github.com/open-telemetry/opentelemetry-java/tree/master/contrib is for the api whereas https://github.com/open-telemetry/opentelemetry-java/tree/master/sdk_contrib is for the sdk

**Comment by tylerbenson** [comment]
No objection.  `@WithSpan` seems to match the other parts of the `opentelemetry-java` codebase better.

**Comment by tylerbenson** [comment]
One thing to consider is if we can make it easy for a user to add additional attributes to that span purely with annotations.  This can be done as a field on the annotation, or as a separate annotation.  The part that gets a bit more complicated is choosing how to allow defining multiple attributes (duplicate annotations, an array of elements, etc).

We should also consider the expected default span name, exception handling, and other attributes.

**Comment by iNikem** [comment]
Yes, adding an annotation is just a beginning of a long journey. My proposal for first version is to follow the same logic as autoinstrumentation already uses for 3rd party annotations: span name is `ClassName.methodNam` and all exceptions set span status as failed.

It may depend on what exactly we want to allow users to configure, but my first approach would be to add new attributes to annotation. But at some point I will do a review of existing annotations from other projects and will compile a list of potential configuration options to add.

**Comment by trask** [comment]
@iNikem this sounds like a good plan to me.

👍 for `@WithSpan`

**Comment by bogdandrutu** [comment]
We added the annotation in contrib package for the moment.

**Comment by siavashingka** [comment]
I think `@WithSpan` is not enough, and as you probably know a Trace consist of multiple Spans and this annotation is just for having a new Span, my requirement now is to create a new Trace and it seems it is not achievable through annotations and you have to do it using manual tracing

**Comment by jkwatson** [comment]
> I think `@WithSpan` is not enough, and as you probably know a Trace consist of multiple Spans and this annotation is just for having a new Span, my requirement now is to create a new Trace and it seems it is not achievable through annotations and you have to do it using manual tracing

Can you elaborate? You can add as many WithSpan annotations as you want. These together will form a trace.

**Comment by siavashingka** [comment]
Hi @jkwatson, yes you're right we can create Spans as much as we want, but when you want to create separated traces there are no annotations available for creating a new trace with a new name, for example:
We had an application written in Spring boot, and there was a method annotated with `@Scheduled`, in that method we were trying to connect to a broker and start subscribing to the topic and dispatch different messages to different handler methods from there because this method was our starting point to start subscribing to a topic, and handle messages with different handlers, Otel agent considers the scheduled method as a long-running method and at the same time, a starting point of a big trace, so it doesn't matter that you annotate your handler methods with `@WithSpan` because all of them are owned by one huge root Trace from Otel point of view which is not usable in your dashboards.

**Comment by jkwatson** [comment]
@siavashingka Since your issue is specifically about interacting with the auto-instrumentation agent, I recommend opening a discussion/issue in the opentelemetry-java-instrumentation project. What you want to do is quite easy if you're fulling manually instrumenting, but not so easy with the agent.
