### ISSUE TITLE
Errorprone should not check jmh sources\generated files

### ISSUE THREAD

**Issue by DotSpy** [open-telemetry/opentelemetry-java#835]
JMH source and generated sources not conventional, because we trying to hack JIT optimizations.
For now it generate a lot of warnings
![image](https://user-images.githubusercontent.com/11577813/74064466-c2b1a200-4a03-11ea-824b-373fa7fe895d.png)

**Comment by bogdandrutu** [comment]
Is this done?

**Comment by jkwatson** [comment]
I think it's still doing this. The exclusions aren't working the way I thought they would, so I think this needs another look.
