### ISSUE TITLE
Create a stress test module

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#837]
the go implementation has stress testing for metrics. It would be good if java has something similar (for both metrics and traces)

**Comment by bogdandrutu** [comment]
We implemented this for metrics. Do we want to close this issue or we keep it for trace?

**Comment by jkwatson** [comment]
I think having a tracer version would be great. I'm happy to keep this open to track that need.

**Comment by carlosalberto** [comment]
I agree with keeping this issue open for the tracing part.
