### ISSUE TITLE
What to do about GRPC context propagation?

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-java#85]
Link: https://github.com/grpc/grpc-java/blob/master/context/src/main/java/io/grpc/Context.java

Currently, our context propagation package is embedded as a resource in gRPC. This does not result in all of gRPC becoming a dependency, but it is a surprising package name. It would be better if context propagation was removed from gRPC, so that it can be used by both projects without a strange looking dependency change.
 
Proposal:
* Continue to depend on GRPC in alpha.
* And then in beta, work with GRPC spin context propagation out into this project (or an independent repo).

**Comment by SergeyKanzhelev** [comment]
Marking defferred as we moving it for after alpha

**Comment by tylerbenson** [comment]
It does seem rather jarring having it as a dependency.  Perhaps work on the gRPC side could be started soon to get that split out?  It would be a shame  to have that end up being a blocker for GA.

**Comment by yurishkuro** [comment]
Here is the document that I promised: https://docs.google.com/document/d/1UxrEYOaQlF_E4gtiPoFmcZ4YKKe1GxohvCvQDuwvD1I/edit#

Comments are welcome. Some parts of it still need work & agreement on the APIs.

**Comment by yurishkuro** [comment]
Related discussion: #128

**Comment by bogdandrutu** [comment]
Closing based on the discussion in https://github.com/open-telemetry/opentelemetry-java/issues/128
