### ISSUE TITLE
Do not validate tracestate

### ISSUE THREAD

**Issue by justinfoote** [open-telemetry/opentelemetry-java#876]
The opentelemetry-java implementation of W3C TraceContext is currently validating every tracestate entry (See [here](https://github.com/open-telemetry/opentelemetry-java/blob/1fced4898fd82a7c9e237c65de4dc235e7085758/api/src/main/java/io/opentelemetry/trace/TraceState.java#L207-L213)).  An invalid tracestate entry will cause an `IllegalArgumentException`, via `Utils::checkArgument`, which will bubble up to `HttpTraceContext::extract`, [here](https://github.com/open-telemetry/opentelemetry-java/blob/1fced4898fd82a7c9e237c65de4dc235e7085758/api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java#L155).  That exception causes the entire W3C TraceContext payload to be discarded!

The W3C spec allows for tracestate validation, with this text:
> The vendor MAY validate the tracestate header. If the tracestate header cannot be parsed the vendor MAY discard the entire header. Invalid tracestate entries MAY also be discarded.

But I don't believe it intends for vendors to discard traceparent and restart the trace.  
In addition, there is an open issue (https://github.com/w3c/trace-context/issues/384) to change that to a _SHOULD NOT_, rather than a _MAY_.

I propose that this project remove all validation of tracestate entries.

Or, at the very least, I propose that this project drop only invalid tracestate entries, rather than the entire W3C TraceContext payload.

**Comment by jkwatson** [comment]
See https://github.com/open-telemetry/opentelemetry-specification/issues/478 for possible spec change.

**Comment by carlosalberto** [comment]
Related to #895

**Comment by bogdandrutu** [comment]
@jkwatson lazy parsing and validation of the tracestate is a nice addition to our project. I am happy to see a PR around that idea.

**Comment by Oberon00** [comment]
I think a better design might be to propagate and store the tracestate more independent of trace+spanid on the Context. That would be a spec change though.

**Comment by jkwatson** [comment]
I'd like to move this to post-GA, if that's ok with folks. Please let me know if you want me to move it back.

**Comment by iNikem** [comment]
I would like to point out, that there are 2 different use cases here. One is while reading TraceState from the wire, another is during manipulating TraceState before propagation/export. The second use case is now explicitly addressed [by the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#tracestate):

> Every mutating operations MUST validate input parameters

**Comment by jkwatson** [comment]
> I would like to point out, that there are 2 different use cases here. One is while reading TraceState from the wire, another is during manipulating TraceState before propagation/export. The second use case is now explicitly addressed [by the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#tracestate):
> 
> > Every mutating operations MUST validate input parameters

Interesting. Given that we do validate on mutation, and we also validate when we read it off the wire, do you feel like we need to remove the "off the wire" validation before GA, @iNikem ?

**Comment by iNikem** [comment]
Remove validation seems to be non-breaking change for me, thus it can be done after GA.

**Comment by jkwatson** [comment]
related: #2084

**Comment by jkwatson** [comment]
Closing for now. We can re-open if the spec gets changed to support this.
