### ISSUE TITLE
BUG: Invalid trace context header crashes extract

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#895]
See e.g.: https://github.com/open-telemetry/opentelemetry-java/blob/f4dea297be6eac28eade6dd1895ad73eed28d8f8/api/src/main/java/io/opentelemetry/trace/propagation/HttpTraceContext.java#L137

This is not in compliance with https://github.com/open-telemetry/opentelemetry-specification/blob/69768aa7bb8bdcd2c1490e5a1f38e109dc0517a3/specification/error-handling.md#basic-error-handling-principles:

> OpenTelemetry implementations MUST NOT throw unhandled exceptions at run time.

https://github.com/open-telemetry/opentelemetry-specification/issues/478 is related to this, but this issue here also concerns traceparent.

An invalid (non-null) spancontext should be returned instead of throwing.

**Comment by carlosalberto** [comment]
You are right. There was some love provided there to avoid raising errors but we need to wrap this effort up.
