### ISSUE TITLE
Clarification on Android compatibility - is android 14 actually - Android 4.0 (API level 14)

### ISSUE THREAD

**Issue by michaelwilde** [open-telemetry/opentelemetry-java#915]
in the readme for API and SDK, it says "Java 7 and Android 14" compatible. Android 4.0 (API level 14). vs the public release number of Android.  If so, i'm happy to update the readme's for ya.

**Comment by jkwatson** [comment]
That would be great, @michaelwilde . Also, consider that we've recently changed the SDK to require Android API level 24, so if you could include that update as well, that would be fantastic.

**Comment by michaelwilde** [comment]
Sweet.. i'll PR it and you can correct me if i'm rong.  ;)
