### ISSUE TITLE
Do not report errors on Inject with null values.

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#916]
When using `inject()`, a `null` carrier might make sense if a lambda is used or an anonymous class is used, for example.

Similar to #899 we want to be more lenient.

**Comment by thisthat** [comment]
Relevant comment for context: https://github.com/open-telemetry/opentelemetry-java/pull/899#discussion_r382492698

**Comment by jkwatson** [comment]
Do we want this to apply to all the implementations of HttpTextFormat? HttpTraceContext, B3Propagator, Jaeger, etc?

**Comment by jkwatson** [comment]
Also, I think this only really applies to the `carrier` that's passed in, and not the other parameters, correct?
