### ISSUE TITLE
PrestaShop access to the orders at the back office

### ISSUE THREAD

**Issue by KasiaBa** [open-telemetry/opentelemetry-java#927]
Hello,

I am not sure if it is the right place to put my question as I do not have experience in programming...
I have a problem with the access to the orders at the back office of PrestaShop.
The error message that i got was : 
---------
The server returned a "500 Internal Server Error". 
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
-----------
Is there easy solution?
In fact I have a problem to find a way to contact directly PrestaShop. 
Could you suggest something? I have waisted already a lot of time trying to find a solution...
Thanks a lot in advance!
Kasia
[2020_02_24_PrestaShop_PHP.pdf](https://github.com/open-telemetry/opentelemetry-java/files/4249568/2020_02_24_PrestaShop_PHP.pdf)

**Comment by thisthat** [comment]
@open-telemetry/java-approvers someone can close this issue for OFF-Topic/Spam?
