### ISSUE TITLE
Questions about Nes mini hacked

### ISSUE THREAD

**Issue by sirpippin** [open-telemetry/opentelemetry-java#931]
Hello

I have a few questions about the Nes mini, and how i can use it thé way i would like to.

1. Since u can play consoles from Nes to Sega to Playstation on it, i would like to get a controller that works for all consoles. I was thinking about the Wii classic pro, but i heard 3rd party ones don't work so i get An original, BUT, can u use 2 controllers for 2player games or does this not work?

2. This is a 2 way question. I would like to expand my memory with the otg adapter and a USB, and i can see u can export thé games to USB, but can u use multiple USB drives with each different games on them? And second, do u always need tot put them on the console first and then export them? Or can u put them directly onto thé USB? Since Playstation games are of considerable size...

3. For my last question. Has Anyone tried the adapter for original Nes controllers on the mini, with thé zapgun on and old tv? does this work?

I Cant find An answer to these questions on the internet, with this info i can further fully configure my Nes mini to my liking and for 2 players and with all consoles!

Thanks in advance!!!

**Comment by matt-debug** [comment]
Auto save

**Comment by matt-debug** [comment]
> Hello
> 
> I have a few questions about the Nes mini, and how i can use it thé way i would like to.
> 
> 1. Since u can play consoles from Nes to Sega to Playstation on it, i would like to get a controller that works for all consoles. I was thinking about the Wii classic pro, but i heard 3rd party ones don't work so i get An original, BUT, can u use 2 controllers for 2player games or does this not work?
> 2. This is a 2 way question. I would like to expand my memory with the otg adapter and a USB, and i can see u can export thé games to USB, but can u use multiple USB drives with each different games on them? And second, do u always need tot put them on the console first and then export them? Or can u put them directly onto thé USB? Since Playstation games are of considerable size...
> 3. For my last question. Has Anyone tried the adapter for original Nes controllers on the mini, with thé zapgun on and old tv? does this work?
> 
> I Cant find An answer to these questions on the internet, with this info i can further fully configure my Nes mini to my liking and for 2 players and with all consoles!
> 
> Thanks in advance!!!
