### ISSUE TITLE
Benchmarks use change iterations time\count and iterate over all SpanID\TraceID in benchmark

### ISSUE THREAD

**Issue by DotSpy** [open-telemetry/opentelemetry-java#933]
I created this PR because i don't want to lose some ideas from @sfriberg and i wanna apply it also to HTTPBecnhmarks, but we don't need benchmarks for Beta, so i can continue with more important tasks.
In pr https://github.com/open-telemetry/opentelemetry-java/pull/905 @sfriberg suggested to:
"From a readability standpoint of output data I would probably run longer iterations of a second and run 20-30 of them instead.

To make the output a bit more readable you can set the time unit used for the output to be milli, micro or nano instead will make it easier to read instead of getting the scientific notation."
and 
"I see two options to consider
For the first one you need to consider the overhead of the module calculation compared to the rest of the benchmarked code to ensure that doesn't end up being the main part of your execution
```
  private static final byte[] bytes = ...;
  private int index = 0;
  @Benchmark
  public byte[] measureToByteArray() {
    b = binaryTraceContext.fromByteArray(bytes[index]));
    index = (index + 1) % bytes.length
    return b;
  }
```
To ensure a side effect you can also do this basic add in this case which should be trivial enough to not really impact your benchmark much and probably generate less code than the blackhole call.
```
  private static final int COUNT = X;
  @Benchmark
  @OperationsPerInvocation(COUNT)
  public int measureToByteArray() {
    int result = 0;
    for (int = 0; i < COUNT; i++) {
        result = binaryTraceContext.fromByteArray(bytes[i]).length;
    }
    return result;
  }
```
"

**Comment by DotSpy** [comment]
@jkwatson please assign me to this one

**Comment by DotSpy** [comment]
@bogdandrutu is it possible to do with grpc context now? I wanna do smth like
```
  private final List<Context> contexts =
      Arrays.asList(
          TracingContextUtils.withSpan(DefaultSpan.create(spanContexts.get(0)), Context.ROOT),
          TracingContextUtils.withSpan(DefaultSpan.create(spanContexts.get(1)), Context.ROOT),
          TracingContextUtils.withSpan(DefaultSpan.create(spanContexts.get(2)), Context.ROOT),
          TracingContextUtils.withSpan(DefaultSpan.create(spanContexts.get(3)), Context.ROOT),
          TracingContextUtils.withSpan(DefaultSpan.create(spanContexts.get(4)), Context.ROOT));

  @OperationsPerInvocation(COUNT)
  public Map<String, String> measureInject() {
    for (int i = 0; i < COUNT; i++) {
      httpTraceContext.inject(contexts.get(i), carrier, setter);
    }
    return carrier;
  }
```

**Comment by carlosalberto** [comment]
@DotSpy Yes, you should be able to create `Context` objects this way.
