### ISSUE TITLE
Revise handling of null and empty attribute values

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#948]
In #771 we introduced handling of null and empty strings by dropping them silently.
At this time, the expected behavior was not yet defined in the OTel specification. This was now added to in https://github.com/open-telemetry/opentelemetry-specification/pull/459 (https://github.com/open-telemetry/opentelemetry-specification/commit/23dbc05986eec68741f82c79174df85a4379836e).

The following changes have to be made to conform to the spec:
- empty string values and empty arrays must NOT be dropped but stored since these are valid attribute values
- null values must still be ignored but since OTel-Java support overwriting of attributes, setting null must result in removing a previously set attribute from the map - same goes with arrays that are null themselves

**Comment by bogdandrutu** [comment]
@arminru @thisthat are you planing to have a PR for this?

**Comment by thisthat** [comment]
@bogdandrutu I was pending on #807 to be merged. If you prefer, we can close #807 and I can address null/empty attributes and arrays in this one.
