### ISSUE TITLE
Implement SamplingResult according to the spec 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-java#962]
I was looking for which SDKs implemented the Sampling spec as written: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#sampling

It feels like the most of SDKs still implements the previous version with the `Decision` class.

**Comment by ptravers** [comment]
I would like to pick up this issue. I believe the issue needs to be updated to instead reference:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#sampling

**Comment by jkwatson** [comment]
assigned!
