### ISSUE TITLE
Add Jaeger propagator

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#967]
Similar to https://github.com/open-telemetry/opentelemetry-java/issues/853 but for Jaeger clients.

* https://www.jaegertracing.io/docs/1.17/client-libraries/#propagation-format
* https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/propagation/TextMapCodec.java

Does OTEL client support exporting/injecting of TraceContext/SpanContext into two formats? At the same time use W3C TraceContext and Jaeger? The use case is to allow gradual migration of existing deployments using Jaeger prop. format to W3C.

**Comment by Oberon00** [comment]
Related #718 "No way to change HttpTextFormat"

**Comment by jarebudev** [comment]
Hi, I can take a look into this if nobody is already working on it

**Comment by pavolloffay** [comment]
Go ahead @jarebudev

**Comment by carlosalberto** [comment]
We need to support baggage in the Jaeger format to close this one.

**Comment by jarebudev** [comment]
i can take a look at this, should have a bit more spare time to help out

**Comment by jarebudev** [comment]
I should have a PR ready this week time permitting.
To confirm - is this for inject only, or both inject and extract?

**Comment by jkwatson** [comment]
Unless there's some reason I don't understand, I think we'd want both inject and extract.

**Comment by jarebudev** [comment]
> Unless there's some reason I don't understand, I think we'd want both inject and extract.

Finally got back to this.. :)

I have made changes so that JaegerPropagator injects baggage items and is ready for a PR.

For extracting baggage from Jaeger, unless I've missed something, I was wondering how we'd extract a baggage item when the HTTP headers ```uberctx-{baggage-key}```  passed to the propagator are not fixed and we can only get 'known' headers (e.g. ```uber-trace-id```) using the ```HttpTextFormat.Getter.get()``` method?  Do we need an additional method on the ```Getter``` interface to return all keys?

**Comment by carlosalberto** [comment]
@jarebudev 

We need to support iteration of keys in the `Getter` - see [this](https://github.com/open-telemetry/opentelemetry-specification/issues/433) (on my queue, and it's also marked as "required-for-ga"). Hope to work on that next week, and once that is done, you will be able to complete this task ;)

**Comment by carlosalberto** [comment]
Assigning this to me as this will be part of the over all updates for `Getter.Keys()`. Hope that is fine @jarebudev 😅
