### ISSUE TITLE
automated releases

### ISSUE THREAD

**Issue by andrewhsu** [open-telemetry/opentelemetry-java#971]
from what we talked about at SIG mtg today @carlosalberto

**Comment by bogdandrutu** [comment]
@carlosalberto any update on this?

**Comment by carlosalberto** [comment]
@bogdandrutu Hey! It looks you didn't get my message over gitter - but it *seems* I still don't have enough permissions in Bintray itself, see:

<img width="584" alt="Screen Shot 2020-03-16 at 12 13 16 AM" src="https://user-images.githubusercontent.com/260065/76712644-0d1cf180-671b-11ea-887d-2a611eb20851.png">

**Comment by carlosalberto** [comment]
@bogdandrutu Got this from support at Bintray (meaning I should be able to publish again without you troubleshooting on your end). Will test on early Monday:

> I would like to inform you that I have worked with our internal team and reset your permissions. I would request you to kindly verify at your end and let us know if you still see the issue.
