### ISSUE TITLE
Use resource label service.name as Jaeger service name

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java#978]
`Resource` object attached to a span should contain service name in labels:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-resource-semantic-conventions.md#service

This service name could be used as Jaeger service name. The service name is a required parameter to create Jaeger GRPC exporter. We could relax this requirement and set the service to `unknown` and once a span is exported use the name from span.

Questions:
* Is the `service.name` always set? I run the test now and there weren't any labels in the `Resource` object.
* Is the `service.name` same for all the spans?

**Comment by jkwatson** [comment]
Nothing forces that a `service.name` will always be set, but the Resource is shared across all spans that are produced by the SDK.  The semantic conventions for the attributes are encoded here:  https://github.com/open-telemetry/opentelemetry-java/blob/6330901b1e8834a756feebcf8d97b58499fbd37a/sdk/src/main/java/io/opentelemetry/sdk/resources/ResourceConstants.java#L26

**Comment by jkwatson** [comment]
I'm not sure of the status of this issue. It looks like, from looking at the current state of the code, that we are putting all the Resource attributes into the Jaeger process tags. I don't know a ton about Jaeger, so I don't know what will happen if the both the configured service.name and the one from the Resource gets put into the tags for the spans.

@pavolloffay do you know if this is still an issue, or whether we can close it?

**Comment by anuraaga** [comment]
FWIW, the intuitive behavior for me would be to use `service.name` resource only and remove exporter-specific configuration for service name. Whether a service.name is required or not is a feature of backends I think, and almost all backends do actually require it. While I still wish we had a top-level property in OTel itself for service name, given we don't but it's still "effectively required" by OTLP exporter it seems consistent to only use the resource for all the exporters. Also if multiple exporters are configured it allows them to match up easily.

**Comment by jkwatson** [comment]
How viable would it be to require that service.name was set in the Resource before allowing the SDK to start up? That would solve a lot of problems, I think. But, are there people out there who don't want a `service.name` for some reason?

**Comment by jkwatson** [comment]
FYI, https://github.com/open-telemetry/opentelemetry-java/issues/2076

**Comment by jkwatson** [comment]
this is now complete and done. closing.
