### ISSUE TITLE
Allow B3 propagator to selectively extract between single and multi headers

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-java#985]
The current implementation allows the `B3Propagator` to select whether to extract and inject from single or multiple headers.

It may be desirable to allow the B3Propagator to always check if the single header key exists and if it does use that, otherwise try to extract from multiple headers.

Q: Should the B3Propagator support only supporting one type? ie if single or multi headers are explicitly selected, ignore other types.

**Comment by carlosalberto** [comment]
Thanks for creating the issue. I *feel* we should only support one type at injection (specified with a param as it's done now), and support multiple types upon extraction.

**Comment by carlosalberto** [comment]
Closing this one as the new `MultiTraceExtractor` can handle this case.
