### ISSUE TITLE
Remove SpanData.getHasRemoteParent() and the logic to determine that

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#987]
This property was removed from the proto definition and is no longer a requirement in OpenTelemetery.

**Comment by Oberon00** [comment]
On the other hand, the spec requires access to the whole parent Context or SpanContext.

**Comment by anuraaga** [comment]
Relabeled to required-for-ga since this is about removing a public API

**Comment by Oberon00** [comment]
Can we close this issue? Removing that functionality would violaze the spec, I think. At least at Dynatrace, we rely on this feature.

**Comment by anuraaga** [comment]
@Oberon00 Does `Span.fromContext(spanData.getContext()).isRemote()` work?

**Comment by anuraaga** [comment]
Oops nevermind - I recall us adding `Context` to the export pipeline but can't find it

**Comment by anuraaga** [comment]
@Oberon00 Should we replace `getParentSpanId` with `getParentSpanContext`? https://github.com/open-telemetry/opentelemetry-java/blob/master/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java#L59

**Comment by Oberon00** [comment]
I think storing the full parent SpanContext would work, and would even be required by the spec: https://github.com/open-telemetry/opentelemetry-specification/blob/v0.7.0/specification/trace/sdk.md#additional-span-interfaces:

> **Readable span**: A function receiving this as argument MUST be able to
> access all information that was added to the span,
> as listed [in the API spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v0.7.0/specification/trace/api.md#span-data-members).

And in the API spec, at that anchor:

> ...
> * A parent span in the form of a `Span`, `SpanContext`, or `null`
> ...
