### ISSUE TITLE
Separate single and combined B3 header logic

### ISSUE THREAD

**Issue by MikeGoldsmith** [open-telemetry/opentelemetry-java#999]
The B3Propagator includes logic for both injecting and extacting span context from both single and multiple headers. To help simplify the code, the two code paths could be broken into two classes.

**Comment by ksameersrk** [comment]
@bogdandrutu  I would like to take a stab at this. I see that this has not been done at least in the master branch. Should I create a PR for this?

**Comment by carlosalberto** [comment]
@ksameersrk Just assigned it to you. Thanks for helping out!
